export const text: text = {
  _colon: `: `,
  _comma: `، `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `؟ `,
  _space: ` `,
  about: `حول المستخدم`,
  accept: `قبول`,
  accountActivation: `تفعيل الحساب`,
  accountAlreadyExists: `يوجد حساب مسجّل بالفعل`,
  accountDoesNotExist: `الحساب غير مسجّل`,
  add: `إضافة`,
  addArt: `اضف عمل فني`,
  addBlog: `اضف منشور كتابي`,
  addedNAgo: (n) => `أضيف قبل ${n}`,
  addMore: `(en) Add more`,
  addNewArt: `أضف عمل فني جديد`,
  addPreview: `أضف معاينة`,
  addSignInVia: `إضافة تسجيل الدخول عبر`,
  advancedOptions: `(en) Advanced options`,
  all: `الكل`,
  alreadySignedIn: `تم تسجيل الدخول بالفعل`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (n) => `(en) Amount should not be less than $${n}`,
  animeArtByArtistsFromAllOverTheWorld: `أعمال فنية من جميع أنحاء العالم. أعمال فنية مختارة من عالم الأنمي. اختيارنا الفني عبارة عن قائمة لا نهاية لها من أفضل الأعمال الفنية للأنمي.`,
  animeArtSubscribeToArtistsLikeAndCreate: `أعمال أنمي فنية - تابع مختلف الفنانين, أبدي إعجابك وأنشئ مجموعاتك`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `أنمي.كلوب - أول موقع يقدم للفنانين أرباح من مشاهدات قوقل آد-سينس. ادعم الفنانين بمشاهدة محتواهم أو أبدأ الربح من خلال المشاهدات`,
  animeClubViewPostAndEarnFromAnimeContent: `أنمي.كلوب - شاهد وانشر واربح من محتوى عالم الأنمي`,
  animeCommunity: `مجتمع الأنمي`,
  animeOnly: `أنمي فقط`,
  apply: `تطبيق`,
  appsVersionIs: `نسخة التطبيق`,
  areYouSureYouWantTo: `هل أنت متأكد من`,
  art: `أعمال فنية`,
  artAssociatedWithAnime: `أعمال فنية متعلقة بالأنمي`,
  artBy: `العمل الفني من قبل`,
  artCannotBeChanged: `العمل الفني لا يمكن تغييره`,
  authenticationFailed: `فشلت المصادقة`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `الرجوع`,
  blog: `المدونة`,
  bookmarks: `العلامات المرجعية`,
  browseArt: `تصفح الأعمال`,
  cancel: `إلغاء`,
  cannotStartWithChars: `لا يمكن البدء بـs{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  changeArt: `تغيير العمل الفني`,
  changeAvatar: `تغيير الصورة الشخصية`,
  changePassword: `تغيير كلمة السر`,
  chooseExistingChatOrStartANewOne: `اختر محادثةً موجودة أو ابدأ دردشة جديدة`,
  city: `المدينة`,
  clearAll: `امسح الكل`,
  close: `أغلق`,
  comingSoon: `قريبًا...`,
  community: `المجتمع`,
  confirmAccount: `تأكيد الحساب`,
  confirmPassword: `تأكيد كلمة السر`,
  contactInformation: `(en) Contact information`,
  contractTitle: `(en) Contract Title`,
  copyLink: `نسخ الرابط`,
  couldNotCreateANewRecord: `تعذر إنشاء سجل جديد`,
  country: `الدولة`,
  createANewAccountFailed: `فشل إنشاء حساب جديد`,
  createNewAccount: `إنشاء حساب جديد`,
  delete: `حذف`,
  deleteArt: `حذف الرسم`,
  deletePost: `حذف المنشور`,
  description: `الوصف`,
  details: `التفاصيل`,
  didntReceiveEmail: `لم تتلقى البريد؟`,
  donations: `التبرعات`,
  done: `انتهاء`,
  drawingContest: `مسابقة الرسم`,
  dueDate: `(en) Due date`,
  earningFromArts: `الربح من خلال نشر أعمالك الفنية`,
  edit: `تعديل`,
  editPost: `تعديل المنشور`,
  editProfile: `تعديل الملف الشخصي`,
  editTranslations: `تعديل الترجمات`,
  email: `البريد الإلكتروني`,
  emailAlreadyUsedByAnotherAccount: `البريد الإلكتروني قيد الاستخدام من قبل حساب آخر`,
  emailSubscription: `الاشتراك البريدي`,
  enterOrPasteALink: `أدخل أو ألصق رابطًا`,
  error404NotFound: `خطأ 404 - لم يتم العثور`,
  errorPleaseContactCustomerSupport: `خطأ! الرجاء التواصل مع دعم العملاء...`,
  exitEditor: `الخروج من وضع التحرير`,
  extensions: `امتدادات الملف`,
  fileSizeIsTooBig: `حجم الملف أكبر من المطلوب`,
  filter: `تصفية`,
  filterBy: `تصفية على حسب`,
  findUser: `البحث عن مستخدم`,
  follow: `متابعة`,
  followers: `متابعون`,
  following: `تُتابع`,
  followMeOn: `تابعني على`,
  followUsOnTwitter: `تابعنا على تويتر`,
  forAllOtherInquiriesPleaseContactUsAt: `لباقي الاستفسارات, اتصل بنا على:`,
  forgotPassword: `نسيت كلمة السر`,
  forNewMasterpieces: `لأعمال فنية مميزة جديدة`,
  four04: `— 404! —`,
  getDetails: `الحصول على تفاصيل`,
  guestView: `وضع الضيف`,
  hire: `(en) Hire`,
  homepage: `الصفحة الرئيسية`,
  howToContactYou: `(en) How to contact you`,
  iAgreeWith: `أتفق على`,
  id: `المُعرف`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `ارتفاع الصورة يحتاج أن يكون أكبر من أو يساوي`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `عرض الصورة يحتاج أن يكون أكبر من أو يساوي`,
  introduction: `مقدمة`,
  invalidCode: `رمز غير صحيح`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `جزء غير صالح بعد @`,
  invalidPartBeforeAt: `جزء غير صالح قبل @`,
  jobDetails: `(en) Job Details`,
  joinChat: `الانضمام للمحادثة`,
  joinUsOnFacebook: `انضم معنا على الفيسبوك`,
  languages: `اللغات`,
  likes: `إعجابات`,
  linkCopiedToClipboard: `تم نسخ الرابط إلى الحافظة`,
  livingIn: `أعيش في`,
  location: `(en) Location`,
  logout: `تسجيل الخروج`,
  maximumNChars: (n) => `الحد الأقصى للأحرف ${n}`,
  maxSize: `الحجم الأقصى`,
  menu: `القائمة`,
  message: `رسالة`,
  messages: `الرسائل`,
  minHeight: `الارتفاع الأدنى`,
  minimumNChars: (n) => `الحد الأدنى ${n} حرف`,
  minWidth: `العرض الأدنى`,
  moreFrom: (n) => `المزيد من خلال ${n}`,
  mustBeNChars: (n) => `لا بد أن تكون ${n} حرف`,
  need1Lowercase: `يلزم 1 حرف صغير`,
  need1Number: `يلزم 1 رقم`,
  need1Uppercase: `يلزم 1 حرف كبير`,
  needAtLeast1CharacterFromN: (n) => `يلزم على الأقل 1 حرف كبير من [${n}]`,
  needNCharacter: (n) => `يلزم ${n} حرف`,
  newAccount: `حساب جديد`,
  newArt: `عمل فني جديد`,
  newBlog: `منشور جديد`,
  newPassword: `كلمة سر جديدة`,
  newsFeed: `شريط الأخبار`,
  no: `لا`,
  noAddedFavoriteArts: `لا توجد أي رسومات مُفضلة تمت إضافتها`,
  noInternetConnection: `لا يوجد اتصال بالانترنت!`,
  notifications: `الإشعارات`,
  nsfwContent18Plus: `محتوى للبالغين (18+)`,
  ohNoItIsNotHere: `آه كلا! لا يوجد هنا شيء!`,
  oldPassword: `كلمة السر القديمة`,
  online: `متصل`,
  onlyHexNumbersStartsWithTChar: `أرقام ست عشرية فقط [0-9a-fA-F], تبدأ بحرف "t"`,
  onlyLatinLettersNumbersOrSpecialSymbols: `أرقام لاتنية فقط وأرقام ورموز خاصة`,
  onlyNumbers: `أرقام فقط`,
  open: `(en) Open`,
  openGuestView: `افتح وضع الضيف`,
  openingSoon: `قريبًا الافتتاح!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `أو`,
  password: `كلمة السر`,
  payments: `المدفوعات`,
  pleaseCheckYour: `الرجاء التحقق من`,
  pleaseDropOnlyOneImage: `الرجاء إضافة صورة واحدة فقط`,
  pleaseEnterAtLeastNChars: (n) => `الرجاء إدخال ${n} أحرف على الأقل`,
  pleaseFillOutYourDetails: `الرجاء تعبئة بياناتك`,
  pleaseSignInToYourAccount: `الرجاء تسجيل الدخول لحسابك`,
  pleaseTryAgainOrClick: (n) => `يرجى المحاولة مرة أخرى أو النقر فوق ${n}`,
  pleaseVerifyYourAccount: `الرجاء تأكيد حسابك`,
  pressHereTo: `أضغط هنا من أجل`,
  privacyPolicy: `سياسة الخصوصية`,
  profile: `ملف التعريف`,
  publishOn: (n) => `(en) Publish on ${n}`,
  save: `حفظ`,
  saveAvatar: `حفظ الصورة الشخصية`,
  saveChanges: `حفظ التغييرات`,
  selectAnime: `اختر أنمي`,
  selectAvatar: `اختر صورة شخصية`,
  selectCharacters: `اختر شخصية`,
  selectFile: `اختر ملف`,
  selectThumbnail: `اختر صورة مصغرة`,
  sendEmail: `ارسل رسالة بريد`,
  settings: `الإعدادات`,
  shareYourStory: `شارك قصتك!`,
  shop: `تسوق`,
  showLess: `عرض أقل`,
  showMore: `عرض أكثر`,
  signIn: `تسجيل دخول`,
  skip: `تخطى`,
  socialMedia: `وسائل التواصل الاجتماعي`,
  spaceCharacterIsNotAllowed: `غير مسموح بالمسافة`,
  subscribeToTalentsToKeepUpWithTheirProgress: `اشترك في صفحات المواهب لمتابعة إنجازاتهم`,
  successChangedPasswordPleaseSignIn: `تم بنجاح تم تغيير كلمة السر. الرجاء تسجيل الدخول`,
  successCreatedRecord: `تم بنجاح إنشاء السجل!`,
  successUpdatedRecord: `تم بنجاح تحديث السجل!`,
  supportMeOn: `ادعمني على`,
  tellUsAboutYourself: `اخبرنا عن نفسك`,
  termsAndConditions: `الأحكام والشروط`,
  termsOfUse: `شروط الاستخدام`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `العنوان`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `ادخل النص هنا...`,
  upload: `(en) Upload`,
  uploadAnotherArt: `تحميل عمل فني آخر`,
  uploadAnotherAvatar: `تحميل صورة شخصية أخرى`,
  uploadArtNow: `قم بتحميل عمل فني الآن!`,
  uploadNew: `تحميل جديد`,
  uploadNewArt: `تحميل عمل فني جديد`,
  uploadNewPost: `تحميل منشور جديد`,
  username: `اسم المستخدم`,
  usernameAlreadyExists: `اسم المستخدم مستخدم من قبل`,
  valueIsNotTheSame: `القيمة ليست هي نفسها`,
  verificationCode: `رمز التأكيد`,
  verifyCode: `أكد الرمز`,
  visitOurDiscordChannelToGetMoreDetails: `قم بزيارة قناتنا في ديسكورد للحصول على مزيد من التفاصيل`,
  weAreOnInstagram: `تجدنا على انستقرام`,
  weAreWorkingOnIt: `نعمل على الأمر`,
  weDoNotDisplayNSFWContentYet: `لا نعرض محتوى للبالغين بعد`,
  weHaveSentTooManyVerificationEmails: `قمنا بإرسال رسائل تأكيد أكثر من اللازم, الرجاء المحاولة مرة أخرى بعد عدة دقائق`,
  welcomeToAnimeClub: `أهلًا بك في أنمي.كلوب!`,
  weSentAnEmailTo: `أرسلنا بريد إلكتروني إلى:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `قمنا بإرسال رسالة تأكيد جديدة على البريد. الرجاء إدخال رمز التأكيد`,
  weSupportOnlyTheFollowingFileExtensions: `ندعم فقط امتدادات الملفات التالية:`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `البريد الإلكتروني أو كلمة المرور غير صحيحين`,
  yes: `نعم`,
  youAreAlreadyAuthenticated: `سبق وقمنا بالتحقق من حسابك`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanStillNavigateToThePreviouslyOpenedPages: `لا يزال بإمكانك التنقل للصفحات المفتوحة مسبقًا`,
  youDidNotSelectAnyChats: `لم تُحدد أي محادثات`,
  youDidNotUpdateAnyValues: `لم تقم بتحديث أي قيم`,
  youDoNotHaveAnyChats: `ليس لديك أي محادثات`,
  youHaveNotSavedAnyChanges: `لم تقم بحفظ أي تغييرات, الخروج؟`,
  yourAccountIsVerifiedPleaseSignIn: `تم التحقق من حسابك. الرجاء تسجيل الدخول`,
  yourArts: `أعمالك الفنية`,
  yourAvatar: `صورتك الشخصية`,
  yourBlog: `مدونتك`,
  yourFansAreWaiting: `معجبيك في انتظارك`,
  yourFeedIsEmpty: `شريطك الإخباري فارغ`,
  yourSessionHasExpiredPleaseSignInAgain: `انتهت جلستك, الرجاء تسجيل الدخول مجددًا`,
}
