export const text: text = {
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `(en) Anime.club uses ${v[0]} to get you paid quickly and keep your personal and payment information secure`,
  clickTheButtonBelowToOpenYourStripeDashboard: `(en) Click the button below to open your Stripe dashboard and view your account details`,
  visitStripeDashboard: `(en) Visit Stripe dashboard`,
  files: `(en) Files`,
  prohibitedTransaction: `(en) Prohibited transaction`,
  uploadTheFilesYourBuyerWillGet: `(en) Upload the files your <b>buyer will get</b>`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `(en) Make sure everything is ready to go — no edits after publishing`,
  filesForTheBuyer: `(en) Files for the buyer`,
  filesForPreview: `(en) Files for preview`,
  needsYourReview: `(en) Needs Your Review`,
  awaitingSellersResponse: `(en) Awaiting seller's response`,
  buyersRequest: `(en) Buyer's request`,
  comments: `(en) Comments`,
  awaitingClientReview: `(en) Awaiting Client Review`,
  copy: `(en) Copy`,
  thankYouForYourPurchase: `(en) Thank you for your purchase!`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `(en) Great news! ${v[0]} purchased your item. Time to celebrate!`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `(en) @${v[0]} hasn't listed any products for sale yet`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `(en) @${v[0]} hasn’t added anything to their portfolio yet`,
  hideListing: `(en) Hide listing`,
  uploadUpToNumberFiles: (...v) => `(en) Upload up to <b>${v[0]}</b> files`,
  supportedFormats: `(en) Supported formats:`,
  minimumDimensions: (...v) => `(en) Minimum size: ${v[0]}×${v[1]} pixels`,
  maximumFileSize: (...v) => `(en) Maximum file size: <b>${v[0]}</b> per file`,
  thisListingWontBeVisibleToBuyersAnymore: `(en) This listing won’t be visible to buyers anymore — but you can show it again whenever you’re ready`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `(en) Buyers will be able to see this listing. You can hide it again anytime`,
  listingHiddenFromBuyers: `(en) Listing hidden from buyers`,
  listingIsNowVisibleToBuyers: `(en) Listing is now visible to buyers`,
  showListing: `(en) Show listing`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `(en) If there's no response by ${v[0]}, the order will be canceled automatically`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `(en) If no reply is received by ${v[0]}, you'll automatically receive a full refund`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `(en) If you miss the deadline, the buyer can cancel the order for a full refund, and any associated Stripe fees will be deducted from your payout.`,
  addAComment: `(en) Add a comment`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `(en) These rules are provided by the seller and apply only to this item`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `(en) If you have questions or concerns, please contact the seller directly`,
  platformPoliciesMayStillApply: `(en) Platform policies may still apply`,
  copiedToClipboard: `(en) Copied to clipboard`,
  uploadedFilesLocked: `(en) You uploaded these files when you created the post. They're now locked but still visible below`,
  new: `(en) New`,
  createPersonalizedWorkTailoredToEachRequest: `(en) Create personalized work tailored to each request`,
  offerDigitalProducts: `(en) Offer digital products that buyers can access right away`,
  instantDownload: `(en) Instant Download`,
  customWork: `(en) Custom Work`,
  allListings: `(en) All Listings`,
  newCommission: `(en) New commission`,
  noOrders: `(en) No orders`,
  buyNow: `(en) Buy now`,
  attachedFiles: `(en) Attached files`,
  numFilesIncluded: (...v) => `(en) <b>${v[0]}</b> file(s) included`,
  tellTheBuyersWhatTheyWillGet: `(en) Tell buyers exactly what they will get — for example, the number of illustrations, file formats, or canvas specs like resolution and DPI`,
  beSpecificAboutTheContent: `(en) Be specific about the content (e.g. number of files, formats, canvas resolution)`,
  mentionYourDeliveryTimeInDays: `(en) Mention your <b>delivery time</b> (in days)`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `(en) Let buyers know if you offer <b>revisions</b>, and how many`,
  listAnyContentOrRequestsYouDontAccept: `(en) List any content or requests you <b>don't accept</b> (e.g. NSFW, political, religious, or offensive material)`,
  offerOptionalExtras: `(en) Offer optional extras like <b>rush delivery</b>, an <b>extra character</b>, or a <b>detailed background</b>`,
  extrasHelpBoostIncome: `(en) Extras help buyers customize their order and can boost your income`,
  pleaseAllowPopups: `(en) Please allow popups`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `(en) You'll be able to download your files immediately after purchase—no waiting required!`,
  orderAOneOfAKindCustomPieceCraftedToMatchYourVision: `(en) Order a one-of-a-kind custom piece, crafted to match your vision`,
  youAreCoveredIfThereIsAProblem: `(en) You're covered! If there's a problem and the dispute is valid, you'll get 100% of your money back`,
  artGallery: `(en) Art Gallery`,
  commission: `(en) Commission`,
  commissions: `(en) Commissions`,
  digitalDownloads: `(en) Digital Downloads`,
  changesSaved: `(en) Changes saved!`,
  setUpStripeAccountToGetPaidWithAnimeClub: `(en) Set up a Stripe account to get paid with Anime.club`,
  sellerTermsOfService: `(en) Seller Terms of Service`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `(en) Describe what’s included and what the buyer can expect after purchase`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `(en) The reason you provide for cancelling this order will be shared with the buyer`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `(en) Optionally, you can add a description to share more about your creation`,
  pleaseProvideATitleForYourArtwork: `(en) Please provide a title for your artwork`,
  usernameStartedFollowingYou: (...v) => `(en) <b>${v[0]}</b> started following you`,
  usernameLeftAReaction: (...v) => `(en) <b>${v[0]}</b> left a reaction`,
  vote: `(en) Vote`,
  tapAddToCreateOne: `(en) Tap “Add” to create one`,
  reply: `(en) Reply`,
  replyToUsername: (...v) => `(en) Reply to ${v[0]}`,
  numOfReplies: (...v) => `(en) ${v[0]} replies`,
  replies: `(en) Replies`,
  youCanChooseFromTheListOrEnterACustomReason: `(en) You can choose from the list or enter a custom reason`,
  _colon: `: `,
  _comma: `، `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `؟ `,
  _space: ` `,
  _hyphen: `- `,
  about: `حول المستخدم`,
  accept: `قبول`,
  acceptOrder: `قبول الطلب`,
  acceptTheOrder: `قبول الطلب`,
  accountManagment: `إدارة الحساب`,
  account: `الحساب`,
  accountDeleted: `تم حذف الحساب`,
  animeShopBuyAndSellProducts: `متجر الأنمي - بيع وشراء المنتجات`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `الصور المولدة بالذكاء الاصطناعي وفلاتر الشبكات العصبية محظورة`,
  accountActivation: `تفعيل الحساب`,
  accountAlreadyExists: `يوجد حساب مسجّل بالفعل`,
  accountDoesNotExist: `الحساب غير مسجّل`,
  accountRemoval: `حذف الحساب`,
  add: `إضافة`,
  addArt: `اضف عمل فني`,
  addBlog: `اضف منشور كتابي`,
  additionalResources: `موارد إضافية`,
  addMoreProductsToYourShop: `أضف المزيد من المنتجات إلى متجرك`,
  addMore: `إضافة المزيد`,
  addNewArt: `أضف عمل فني جديد`,
  addSignInVia: `إضافة تسجيل الدخول عبر`,
  addToCart: `إضافة إلى السلة`,
  advancedOptions: `خيارات متقدمة`,
  all: `الكل`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `جميع الملفات التي ترفعها هنا ستكون متاحة للمشتري`,
  alreadySignedIn: `تم تسجيل الدخول بالفعل`,
  amount: `المبلغ`,
  amountShouldNotBeLessThan: (...v) => `المبلغ لا يجب أن يكون أقل من ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `أعمال فنية من جميع أنحاء العالم. أعمال فنية مختارة من عالم الأنمي. اختيارنا الفني عبارة عن قائمة لا نهاية لها من أفضل الأعمال الفنية للأنمي.`,
  animeArtSubscribeToArtistsLikeAndCreate: `أعمال أنمي فنية - تابع مختلف الفنانين, أبدي إعجابك وأنشئ مجموعاتك`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `أنمي.كلوب - أول موقع يقدم للفنانين أرباح من مشاهدات قوقل آد-سينس. ادعم الفنانين بمشاهدة محتواهم أو أبدأ الربح من خلال المشاهدات`,
  animeClubViewPostAndEarnFromAnimeContent: `أنمي.كلوب - شاهد وانشر واربح من محتوى عالم الأنمي`,
  animeCommunity: `مجتمع الأنمي`,
  animeDotclubNeverAsksForYourPrivateInformation: `أنمي.كلوب لا يطلب أبدًا معلوماتك الخاصة`,
  animeSocialNetwork: `شبكة الأنمي الاجتماعية`,
  announcements: `الإعلانات`,
  apply: `تطبيق`,
  appSettings: `إعدادات التطبيق`,
  appsVersionIs: `نسخة التطبيق`,
  areYouSureYouWantTo: `هل أنت متأكد من`,
  art: `أعمال فنية`,
  artAssociatedWithAnime: `أعمال فنية متعلقة بالأنمي`,
  artBy: (...v) => `فن من ${v[0]}`,
  artCannotBeChanged: `العمل الفني لا يمكن تغييره`,
  artworksAvailableToView: (...v) => `${v[0]} لوحات فنية متاحة للعرض`,
  authenticationFailed: `فشلت المصادقة`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `النشر التلقائي على إنستغرام متاح فقط لحسابات الأعمال على إنستغرام`,
  attentionYourOrderHasBeenDisputed: `انتباه! تم الاعتراض على طلبك. يرجى التحقق من التفاصيل`,
  back: `الرجوع`,
  basePrice: `السعر الأساسي`,
  bigAppreciationToTheSellerForTheHardWork: `تقدير كبير للبائع على العمل الجاد`,
  block: `حظر`,
  buyerReviewedTheOrder: `قام المشتري بمراجعة الطلب`,
  buyerHasNotLeftAReviewYet: `لم يترك المشتري مراجعة بعد`,
  feedbackReceived: `تم استلام الملاحظات!`,
  blockUser: (...v) => `حظر @${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `قبل القبول، يرجى مراجعة طلب المشتري بعناية`,
  blog: `المدونة`,
  bookmarks: `العلامات المرجعية`,
  browseArt: `تصفح الأعمال`,
  browseShop: `تصفح المتجر`,
  buyer: `المشتري`,
  cancel: `إلغاء`,
  canceled: `تم الإلغاء`,
  cancelOrder: `إلغاء الطلب`,
  cannotStartWithChars: `لا يمكن البدء بـs{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `تغيير`,
  checkOutMyShop: `تفضل بزيارة متجري`,
  checkOrderStatus: `تحقق من حالة الطلب`,
  changeArt: `تغيير العمل الفني`,
  changeAvatar: `تغيير الصورة الشخصية`,
  changeEmail: `تغيير البريد الإلكتروني`,
  changePassword: `تغيير كلمة السر`,
  chooseExistingChatOrStartANewOne: `اختر محادثةً موجودة أو ابدأ دردشة جديدة`,
  city: `المدينة`,
  clearAll: `امسح الكل`,
  close: `أغلق`,
  colorTheme: `موضوع اللون`,
  comingSoon: `قريبًا...`,
  commercialUseAllowed: `الاستخدام التجاري مسموح`,
  commercialUseAllowsBuyersToUseYourProduct: `الاستخدام التجاري يسمح للمشترين باستخدام منتجك لأغراض تجارية مثل البيع أو الترويج لخدماتهم`,
  community: `المجتمع`,
  completed: `تم الانتهاء`,
  confirmAccount: `تأكيد الحساب`,
  confirmOrder: `تأكيد الطلب`,
  confirmPassword: `تأكيد كلمة السر`,
  connectWithUsOn: `الاتصال بنا على`,
  contactInformation: `معلومات الاتصال`,
  contactSeller: `الاتصال بالبائع`,
  contactSupport: `الاتصال بالدعم الفني`,
  contactUs: `اتصل بنا`,
  continue: `استمرار`,
  contractTitle: `عنوان العقد`,
  congratulations: `تهانينا!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `تهانينا على إكمال طلبك بنجاح!`,
  copyrightViolation: `انتهاك حقوق النشر`,
  couldNotCreateANewRecord: `تعذر إنشاء سجل جديد`,
  country: `الدولة`,
  cover: `الغلاف`,
  createANewAccountFailed: `فشل إنشاء حساب جديد`,
  createExtrasForYourProduct: `إنشاء إضافات لمنتجك`,
  createNewAccount: `إنشاء حساب جديد`,
  createAShopWithStripe: `أنشئ متجرك عبر Stripe`,
  createdBy: `أنشئ بواسطة`,
  currentPassword: `كلمة المرور الحالية`,
  daily: `يوميًا`,
  darkDefault: `الافتراضي الداكن`,
  darkHighContrast: `عالي التباين الداكن`,
  dayTheme: `موضوع النهار`,
  delete: `حذف`,
  deleteShop: `حذف المتجر`,
  deleteAccount: `حذف الحساب`,
  deleteArt: `حذف الرسم`,
  decline: `رفض`,
  deletePost: `حذف المنشور`,
  deleteProduct: `حذف المنتج`,
  download: `تحميل`,
  downloadThemBelow: `قم بتحميلها أدناه`,
  deliveryTime: `وقت التسليم`,
  describeTheDetailsOfYourExtra: `صف تفاصيل الإضافة الخاصة بك`,
  description: `الوصف`,
  details: `التفاصيل`,
  didntReceiveEmail: `لم تتلقى البريد؟`,
  displayName: `اسم العرض`,
  disputed: `متنازع عليه`,
  donations: `التبرعات`,
  done: `انتهاء`,
  dragAndDropOrSelectFiles: `اسحب وأفلت أو حدد الملفات`,
  drawingContest: `مسابقة الرسم`,
  dueDate: `تاريخ الاستحقاق`,
  earlier: `أقرب`,
  earningFromArts: `الربح من خلال نشر أعمالك الفنية`,
  edit: `تعديل`,
  editPost: `تعديل المنشور`,
  editProfile: `تعديل الملف الشخصي`,
  editTranslations: `تعديل الترجمات`,
  email: `البريد الإلكتروني`,
  emailAlreadyUsedByAnotherAccount: `البريد الإلكتروني قيد الاستخدام من قبل حساب آخر`,
  emailNotifications: `إشعارات البريد الإلكتروني`,
  enterOrPasteALink: `أدخل أو ألصق رابطًا`,
  enjoyYourPurchase: `استمتع بمشتراك! 😊`,
  enterTheAddressAssociatedWithYourAccount: `أدخل العنوان المرتبط بحسابك، وسنرسل لك رابطًا لإعادة تعيين كلمة المرور`,
  enterYourPassword: `أدخل كلمة المرور الخاصة بك`,
  error: `خطأ`,
  errorPleaseContactCustomerSupport: `خطأ! الرجاء التواصل مع دعم العملاء...`,
  exitWithoutSaving: `الخروج بدون حفظ`,
  extensions: `امتدادات الملف`,
  extras: `إضافات`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `الإضافات هي ميزات اختيارية لتعزيز منتجك`,
  fileSizeIsTooBig: `حجم الملف أكبر من المطلوب`,
  fileSizeIsTooSmall: `حجم الملف صغير جدًا`,
  filter: `تصفية`,
  filterBy: `تصفية على حسب`,
  findUser: `البحث عن مستخدم`,
  finishSettingUpYourShop: `إنهاء إعداد متجرك`,
  follow: `متابعة`,
  followers: `متابعون`,
  following: `تُتابع`,
  followMeOn: `تابعني على`,
  follows: `متابعون`,
  forAllOtherInquiriesPleaseContactUsAt: `لباقي الاستفسارات, اتصل بنا على:`,
  forgotPassword: `نسيت كلمة السر`,
  fromAnimeDotClub: `من أنمي.كلوب`,
  getDetails: `الحصول على تفاصيل`,
  getStarted: `البدء`,
  guestView: `وضع الضيف`,
  greatNewsYourOrderIsNowInProgress: `أخبار رائعة! طلبك الآن قيد التنفيذ`,
  harassment: `التحرش`,
  haveAnyQuestions: `هل لديك أي أسئلة؟`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> قد ألغى الطلب`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> قام بتسليم العمل`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]} لم يضف وصفًا لـ "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]} لم يشارك أي تفاصيل عامة حتى الآن`,
  hate: `الكراهية`,
  hereAreAFewWaysToGetThingsRolling: `إليك بعض الطرق للبدء`,
  hire: `توظيف`,
  homepage: `الصفحة الرئيسية`,
  howToContactYou: `كيفية الاتصال بك`,
  howToFindYouOnOtherSocialNetworks: `كيفية العثور عليك على شبكات التواصل الاجتماعي الأخرى`,
  iAgreeWith: `أتفق على`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `إذا لم يكن هناك رد بحلول ${v[0]}, سيتم وضع علامة على الطلب كمكتمل تلقائيًا`,
  id: `المُعرف`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `ارتفاع الصورة يحتاج أن يكون أكبر من أو يساوي`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `عرض الصورة يحتاج أن يكون أكبر من أو يساوي`,
  impersonation: `الانتحال`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `تضمين الكلمات الرئيسية التي قد يستخدمها المشترون للبحث عن منتج مثل منتجك`,
  inProgress: `قيد التقدم`,
  introduction: `مقدمة`,
  includes: `يتضمن`,
  invalidCode: `رمز غير صحيح`,
  invalidCurrentPassword: `كلمة المرور الحالية غير صالحة`,
  invalidDate: `تاريخ غير صالح`,
  invalidPartAfterAt: `جزء غير صالح بعد @`,
  invalidPartBeforeAt: `جزء غير صالح قبل @`,
  jobDetails: `تفاصيل الوظيفة`,
  joinAnimeClubCommunity: `انضم إلى مجتمع أنمي.كلوب مع الآلاف من الأشخاص النشطين والفنانين الرائعين كل يوم`,
  joinChat: `الانضمام للمحادثة`,
  joinUsOnFacebook: `انضم معنا على الفيسبوك`,
  language: `اللغة`,
  lackOfInformation: `نقص في المعلومات`,
  languages: `اللغات`,
  letEveryoneKnowHowToDonateToYou: `اسمح للجميع بمعرفة كيفية التبرع لك`,
  letOthersKnowAboutYou: `اسمح للآخرين بمعرفة معلومات عنك`,
  letsUploadYourFirstProduct: `لنقم بتحميل منتجك الأول`,
  letUsKnowWhatsHappening: `اسمح لنا بمعرفة ما يحدث وسنتحقق من ذلك`,
  lightDefault: `الإضاءة الافتراضية الفاتحة`,
  lightHighContrast: `التباين الفاتح العالي`,
  likes: `إعجابات`,
  limit: `الحد`,
  livesIn: `أعيش في`,
  loading: `جار التحميل`,
  location: `الموقع`,
  logInOrSignUp: `تسجيل الدخول أو التسجيل`,
  logOut: `تسجيل الخروج`,
  maximumNChars: (...v) => `الحد الأقصى للأحرف ${v[0]}`,
  maximumNumberOfDaysToCompleteTheOrder: `الحد الأقصى لعدد الأيام لإكمال الطلب`,
  maximumQuantity: `الحد الأقصى للكمية`,
  maxSize: `الحجم الأقصى`,
  menu: `القائمة`,
  message: `رسالة`,
  messages: `الرسائل`,
  minHeight: `الارتفاع الأدنى`,
  minimumNChars: (...v) => `الحد الأدنى ${v[0]} حرف`,
  minorAbuseOrSexualization: `إساءة أو جنسنة طفيفة`,
  makeSureToIncludeClearInstructions: `تأكد من تضمين تعليمات واضحة حول كيفية استخدام كل مرجع`,
  makeSureYouFullyUnderstandTheRequirements: `تأكد من فهمك الكامل للمتطلبات وقدرتك على إكمال الطلب في الموعد`,
  makeSureYourProductsArePricedCompetitively: `تأكد من أن أسعار منتجاتك تنافسية`,
  minWidth: `العرض الأدنى`,
  monthly: `شهريًا`,
  moreFrom: (...v) => `المزيد من خلال ${v[0]}`,
  mustBeNChars: (...v) => `لا بد أن تكون ${v[0]} حرف`,
  myPayments: `مدفوعاتي`,
  myProfile: `ملفي الشخصي`,
  mySettings: `إعداداتي`,
  need1Lowercase: `يلزم 1 حرف صغير`,
  need1Number: `يلزم 1 رقم`,
  need1Uppercase: `يلزم 1 حرف كبير`,
  needAtLeast1CharacterFromN: (...v) => `يلزم على الأقل 1 حرف كبير من [${v[0]}]`,
  needNCharacter: (...v) => `يلزم ${v[0]} حرف`,
  newAccount: `حساب جديد`,
  newArt: `عمل فني جديد`,
  newArtworks: `أعمال فنية جديدة`,
  newBlog: `منشور جديد`,
  newOrder: `طلب جديد`,
  newPassword: `كلمة سر جديدة`,
  newProduct: `منتج جديد`,
  newsFeed: `شريط الأخبار`,
  next: `التالي`,
  nextTimeYouAuthenticateYouCouldUseThe: `في المرة القادمة التي تقوم فيها بالمصادقة، يمكنك استخدام الحساب المتصل بدلاً من تسجيل الدخول وكلمة المرور`,
  nightTheme: `موضوع الليل`,
  no: `لا`,
  noInternetConnection: `لا يوجد اتصال بالانترنت!`,
  nonConsensualIntimateContent: `محتوى حميم غير مرغوب فيه`,
  none: `لا شيء`,
  noNotifications: `لا توجد إشعارات`,
  noResults: `لا توجد نتائج`,
  noReviewsJustYet: `لا توجد مراجعات بعد`,
  notifications: `الإشعارات`,
  noActiveOrdersToShow: `لا توجد طلبات نشطة للعرض`,
  notAcceptingOrders: `لا يقبل الطلبات`,
  noSalesYetNoWorries: `لا توجد مبيعات بعد؟ لا تقلق، أنت في البداية فقط`,
  nsfwContent18Plus: `محتوى للبالغين (18+)`,
  NSFWIndicatesAdultContent: `18+ يشير NSFW إلى محتوى للبالغين. اختر هذا الحقل فقط إذا كان منتجك مخصصًا للبالغين`,
  numberOfAdjustmentsAClientCouldRequest: `عدد التعديلات التي يمكن للعميل طلبها`,
  online: `متصل`,
  onlyLatinLettersNumbersHyphen: `فقط الأحرف اللاتينية والأرقام والشرطة والشرطة السفلية والنقطة`,
  onlyNumbers: `أرقام فقط`,
  onlyYouCanSeeWhatYouveSaved: `فقط أنت يمكنك رؤية ما حفظته`,
  open: `مفتوح`,
  openDispute: `فتح نزاع`,
  openGuestView: `افتح وضع الضيف`,
  openingSoon: `قريبًا الافتتاح!`,
  openToWork: `مفتوح للعمل`,
  optional: `اختياري`,
  requestDetails: `تفاصيل الطلب`,
  or: `أو`,
  order: `طلب`,
  outOfStock: `غير متوفر`,
  ordered: (...v) => `تم الطلب ${v[0]}`,
  orderAgain: `أعد الطلب مرة أخرى`,
  orderDetails: `تفاصيل الطلب`,
  orderConfirmed: `تم تأكيد الطلب`,
  orderCompleted: `تم إكمال الطلب 🎉`,
  orderStatus: `حالة الطلب`,
  orderOptions: `خيارات الطلب`,
  otherReason: `سبب آخر`,
  pageNotFound: `الصفحة غير موجودة`,
  password: `كلمة السر`,
  payments: `المدفوعات`,
  personal: `شخصي`,
  personalCircumstances: `ظروف شخصية`,
  pleaseCheckYour: (...v) => `يرجى التحقق من ${v[0]} الخاص بك`,
  pleaseRateYourOrder: `يرجى تقييم طلبك`,
  feelFreeToShareReferenceImagesAndMaterials: `لا تتردد في مشاركة الصور المرجعية والمواد لمساعدة الفنان في إنشاء عملك`,
  pleaseDoNotShareYourPrivateInformationToOthers: `يرجى عدم مشاركة معلوماتك الخاصة مع الآخرين`,
  pleaseEnterANumberBetweenXandX: (...v) => `يرجى إدخال رقم بين ${v[0]} و ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `الرجاء إدخال ${v[0]} أحرف على الأقل`,
  pleaseFillOutYourDetails: `الرجاء تعبئة بياناتك`,
  pleaseFixTheErrorsBeforeSubmitting: `يرجى تصحيح الأخطاء قبل الإرسال`,
  pleaseSignInToYourAccount: `الرجاء تسجيل الدخول لحسابك`,
  platform: `منصة`,
  pleaseStartTyping: `يرجى البدء في الكتابة`,
  pleaseTakeAMomentToReviewTheOrder: `يرجى أخذ لحظة لمراجعة الطلب`,
  pleaseReviewTheBuyersReferenceFiles: `يرجى مراجعة ملفات المراجع الخاصة بالمشتري واتباعها كما هو موضح في وصف الطلب`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `يرجى مراجعة التفاصيل بعناية قبل المتابعة`,
  pleaseRespondToTheOrderBy: (...v) => `يرجى الرد على الطلب قبل ${v[0]}`,
  pleaseTryAgainOrClick: (...v) => `يرجى المحاولة مرة أخرى أو النقر فوق ${v[0]}`,
  pleaseVerifyYourAccount: `الرجاء تأكيد حسابك`,
  pressHereTo: `أضغط هنا من أجل`,
  price: `السعر`,
  payouts: `المدفوعات`,
  privacyPolicy: `سياسة الخصوصية`,
  privateInformation: `المعلومات الخاصة`,
  proceedToCheckout: `المتابعة للدفع`,
  product: `المنتج`,
  itemReviews: `مراجعات المنتج`,
  portfolio: `معرض الأعمال`,
  profile: `ملف التعريف`,
  promotions: `العروض الترويجية`,
  publicInformation: `المعلومات العامة`,
  publishOn: (...v) => `النشر على ${v[0]}`,
  purchases: `المشتريات`,
  rankings: `التصنيفات`,
  reorderFiles: `إعادة ترتيب الملفات`,
  report: `الإبلاغ`,
  review: `مراجعة`,
  rules: `القواعد`,
  reviews: `المراجعات`,
  numOfReviews: (...v) => `المراجعات: ${v[0]} `,
  reviewed: `تمت المراجعة`,
  reviewTitle: `عنوان المراجعة`,
  reason: `السبب`,
  revisions: `المراجعات`,
  includesXRevisionS: (...v) => `يتضمن ${v[0]} مراجعة/مراجعات`,
  sales: `المبيعات`,
  save: `حفظ`,
  saveAvatar: `حفظ الصورة الشخصية`,
  saveChanges: `حفظ التغييرات`,
  selectAnime: `اختر أنمي`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `اختر موضوعًا واحدًا أو مزامنته مع نظامك والتبديل تلقائيًا بين موضوعات النهار والليل`,
  selectAvatar: `اختر صورة شخصية`,
  selectCharacters: `اختر شخصية`,
  seller: `البائع`,
  selectFile: `اختر ملف`,
  selectTheme: `اختر موضوعًا`,
  selectThumbnail: `اختر صورة مصغرة`,
  selfHarmOrSuicide: `الإيذاء الذاتي أو الانتحار`,
  sendEmail: `ارسل رسالة بريد`,
  settings: `الإعدادات`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `إعداد متجر مجاني ويستغرق بضع دقائق فقط`,
  share: `مشاركة`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `شارك قواعدك وأنواع الطلبات التي لا تقبلها`,
  shareYourShopOnSocialMedia: `شارك متجرك على وسائل التواصل الاجتماعي`,
  shareYourFavoritePiecesOn: (...v) => `شارك أعمالك المفضلة على ${v[0]}`,
  shareYourArtWithTheWorld: `شارك فنك مع العالم`,
  shareYourStory: `شارك قصتك!`,
  sharingPersonalInformation: `مشاركة المعلومات الشخصية`,
  shop: `تسوق`,
  shopReviews: `مراجعات المتجر`,
  shopOrders: `طلبات المتجر`,
  showLess: `عرض أقل`,
  showMore: `عرض أكثر`,
  signIn: `تسجيل دخول`,
  singleTheme: `موضوع واحد`,
  size: `الحجم`,
  skip: `تخطى`,
  socialMedia: `وسائل التواصل الاجتماعي`,
  spaceCharacterIsNotAllowed: `غير مسموح بالمسافة`,
  spam: `البريد المزعج`,
  yourFavoritesWillShowUpHereAddSome: `مفضلاتك ستظهر هنا. أضف بعضها!`,
  submitAReport: `إرسال تقرير`,
  submitWork: `إرسال العمل`,
  subscribeToTalentsToKeepUpWithTheirProgress: `اشترك في صفحات المواهب لمتابعة إنجازاتهم`,
  successChangedPasswordPleaseSignIn: `تم بنجاح تم تغيير كلمة السر. الرجاء تسجيل الدخول`,
  successCreatedRecord: `تم بنجاح إنشاء السجل!`,
  successfullyDownloaded: `تم التحميل بنجاح!`,
  successfullyUploaded: `تم الرفع بنجاح!`,
  supportMeOn: `ادعمني على`,
  syncWithSystem: `مزامنة مع النظام`,
  tellUsAboutYourself: `اخبرنا عن نفسك`,
  termsAndConditions: `الأحكام والشروط`,
  termsOfUse: `شروط الاستخدام`,
  thankYouForReport: `شكرًا لمساعدتك في الحفاظ على مجتمع آمن ومحترم عبر الإنترنت`,
  thankYouForYourReview: `شكرًا لمراجعتك!`,
  theLinkIsBrokenOrPageHasBeenRemoved: `الرابط معطل أو تمت إزالة الصفحة`,
  themeMode: `وضع الموضوع`,
  thisIsThePriceYouPropose: `هذا هو السعر الذي تقترحه`,
  thisFieldIsOptional: `هذا الحقل اختياري`,
  thisCannotBeUndone: `لا يمكن التراجع عن هذا`,
  ensureYouveUploadedTheFinalVersion: `تأكد من رفع النسخة النهائية قبل الإرسال`,
  threateningViolence: `تهديد العنف`,
  title: `العنوان`,
  timeConstraints: `قيود الوقت`,
  titleYourExtraService: `عنوان خدمتك الإضافية`,
  theMaximumQuantityThatACustomerCanAdd: `الحد الأقصى للكمية التي يمكن للعميل إضافتها`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `فترة المراجعة محدودة بـ ${v[0]} أيام`,
  toHelpTheCreatorCompleteYourOrder: `لمساعدة المنشئ في إكمال طلبك بما يرضيك، يرجى تقديم وصف تفصيلي لما تريده. قم بتضمين الموضوع المطلوب، النمط، وميزات الشخصية، وأي مواصفات مهمة أخرى`,
  today: `اليوم`,
  toGetWorkRelatedNotifications: `للحصول على إشعارات تتعلق بالعمل`,
  total: `الإجمالي`,
  toViewThisDataYouNeedToUnblock: (...v) => `لعرض هذه البيانات، تحتاج إلى إلغاء حظر @${v[0]}`,
  trademarkViolation: `انتهاك العلامة التجارية`,
  typeYourTextHere: `ادخل النص هنا...`,
  theSellerHasUploadedTheseFilesForYou: `قام البائع برفع هذه الملفات لك`,
  unblock: `إلغاء الحظر`,
  unblockUser: (...v) => `إلغاء حظر @${v[0]}`,
  unfollow: `إلغاء المتابعة`,
  unlimited: `غير محدود`,
  upload: `تحميل`,
  uploadNew: `تحميل جديد`,
  uploadNewPost: `تحميل منشور جديد`,
  uploadNewProduct: `تحميل منتج جديد`,
  username: `اسم المستخدم`,
  pleaseUploadOnlyFinishedWorkHere: `يرجى رفع الأعمال المنتهية فقط هنا`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `يجب رفع جميع ملفات العمل قيد التنفيذ في الرسائل`,
  usernameAlreadyExists: `اسم المستخدم مستخدم من قبل`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> و ${v[1]} يتابعونك`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b> و${v[1]} آخرين تفاعلوا`,
  useThisEmailTo: `استخدم هذا البريد الإلكتروني للمصادقة وتلقي الإشعارات`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v: string[]) =>
    `للأسف، اضطر ${v[0]} لإلغاء هذا الطلب`,
  valueIsNotTheSame: `القيمة ليست هي نفسها`,
  verificationCode: `رمز التأكيد`,
  verifyCode: `أكد الرمز`,
  viewDetails: `عرض التفاصيل`,
  viewReview: `عرض المراجعة`,
  viewEveryNotificationOfAGroupSeparately: `عرض كل إشعار من مجموعة بشكل منفصل`,
  visitOurDiscordChannelToGetMoreDetails: `قم بزيارة قناتنا في ديسكورد للحصول على مزيد من التفاصيل`,
  weAreOnInstagram: `تجدنا على انستقرام`,
  weAreWorkingOnIt: `نعمل على الأمر`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `عمل رائع! تم إكمال العمل بنجاح`,
  weDoNotDisplayNSFWContentYet: `لا نعرض محتوى للبالغين بعد`,
  weekly: `أسبوعيًا`,
  whenYouPurchaseSomethingItWillAppearHere: `عند شراء شيء ما، سيظهر هنا`,
  weHaveSentTooManyEmails: `لقد أرسلنا الكثير من الرسائل الإلكترونية، يرجى المحاولة مرة أخرى في وقت لاحق أو الاتصال بخدمة العملاء`,
  welcomeToAnimeClub: `أهلًا بك في أنمي.كلوب!`,
  weSentAnEmailTo: `أرسلنا بريد إلكتروني إلى:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `قمنا بإرسال رسالة تأكيد جديدة على البريد. الرجاء إدخال رمز التأكيد`,
  weAreExcitedToSeeYourProgressKeepItUp: `نحن متحمسون لرؤية تقدمك. استمر في ذلك!`,
  weSupportOnlyTheFollowingFileExtensions: `ندعم فقط امتدادات الملفات التالية:`,
  work: `عمل`,
  weWouldLoveToHearFromYou: `نود أن نسمع منك`,
  workDescription: `وصف العمل`,
  leaveAReview: `اترك مراجعة`,
  wrongEmailOrPassword: `البريد الإلكتروني أو كلمة المرور غير صحيحين`,
  yes: `نعم`,
  yesterday: `أمس`,
  youReceivedANewOrderFrom: (...v) => `لقد تلقيت طلبًا جديدًا من <b>${v[0]}</b>`,
  youReceivedAReview: `لقد استلمت مراجعة`,
  youHaveSuccessfullyCreatedYourShop: `لقد أنشأت متجرك بنجاح`,
  youAreAlreadyAuthenticated: `سبق وقمنا بالتحقق من حسابك`,
  youCanAutoPublishToYourSocialMediaAccount: `يمكنك النشر التلقائي على حسابات التواصل الاجتماعي الخاصة بك`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `يمكنك تعديل أنواع الإشعارات التي تتلقاها عبر البريد الإلكتروني`,
  youCanRequestRemovalOfYourAccount: `يمكنك طلب إزالة حسابك مع جميع بياناتك`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `ملاحظاتك ترشد المشترين وتساعد البائعين على تقديم منتجات أفضل`,
  youCanStillNavigateToThePreviouslyOpenedPages: `لا يزال بإمكانك التنقل للصفحات المفتوحة مسبقًا`,
  youDidNotSelectAnyChats: `لم تُحدد أي محادثات`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `سترى المراجعات هنا بمجرد أن يشارك المشترون تجربتهم`,
  youDidNotUpdateAnyValues: `لم تقم بتحديث أي قيم`,
  youDoNotHaveAnyChats: `ليس لديك أي محادثات`,
  youHaveNotSetAPassword: `لم تقم بتعيين كلمة مرور`,
  youHaveNotSharedAnythingYet: `لم تشارك أي شيء حتى الآن`,
  youHaveReachedTheMaximumNumberOfFiles: `لقد وصلت إلى الحد الأقصى لعدد الملفات`,
  kindlyHoldOnForTheBuyersReview: `يرجى الانتظار لمراجعة المشتري للطلب.`,
  yourAccountIsVerifiedPleaseSignIn: `تم التحقق من حسابك. الرجاء تسجيل الدخول`,
  yourAccountWillBeRemoved: (...v) => `سيتم إزالة حسابك ${v[0]}`,
  youHaveNoPurchases: `ليس لديك أي مشتريات`,
  couldYouPleaseProvideTheReasonForTheCancellation: `هل يمكنك تقديم سبب الإلغاء من فضلك`,
  yourArts: `أعمالك الفنية`,
  youCanceledTheOrder: `لقد ألغيت الطلب`,
  yourAvatar: `صورتك الشخصية`,
  yourBlog: `مدونتك`,
  yourFansAreWaiting: `معجبيك في انتظارك`,
  yourFeedIsEmpty: `شريطك الإخباري فارغ`,
  yourSessionHasExpiredPleaseSignInAgain: `انتهت جلستك, الرجاء تسجيل الدخول مجددًا`,
}
