export const text: text = {
  commercialUseAllowsBuyersToUseYourProduct: `(en) Commercial use allows buyers to use your product for business purposes, like selling or promoting their services`,
  describeTheDetailsOfYourExtra: `(en) Describe the details of your extra`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `(en) Extras are optional add-ons to enhance your product`,
  makeSureToIncludeClearInstructions: `(en) Make sure to include clear instructions on how each reference should be used`,
  NSFWIndicatesAdultContent: `(en) 18+ NSFW indicates adult content. Check this field only if your product is intended for mature audiences`,
  pleaseFeelFreeToShareYourReference: `(en) Please feel free to share your reference images and supporting materials to guide the artist in creating your piece`,
  pleaseReviewTheBuyersReferenceFiles: `(en) Please review the buyer's reference files and follow them as specified in the order's description`,
  thisFieldIsOptional: `(en) This field is optional`,
  uploadFiles: `(en) Upload files`,
  _colon: `: `,
  _comma: `، `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `؟ `,
  _space: ` `,
  about: `حول المستخدم`,
  accept: `قبول`,
  acceptOrder: `قبول الطلب`,
  account: `الحساب`,
  accountDeleted: `تم حذف الحساب`,
  accountActivation: `تفعيل الحساب`,
  accountAlreadyExists: `يوجد حساب مسجّل بالفعل`,
  accountDoesNotExist: `الحساب غير مسجّل`,
  accountRemoval: `حذف الحساب`,
  add: `إضافة`,
  addArt: `اضف عمل فني`,
  addBlog: `اضف منشور كتابي`,
  addFile: `إضافة ملف`,
  additionalResources: `موارد إضافية`,
  addMore: `إضافة المزيد`,
  addNewArt: `أضف عمل فني جديد`,
  addPreview: `أضف معاينة`,
  addSignInVia: `إضافة تسجيل الدخول عبر`,
  addToCart: `إضافة إلى السلة`,
  advancedOptions: `خيارات متقدمة`,
  all: `الكل`,
  alreadySignedIn: `تم تسجيل الدخول بالفعل`,
  amount: `المبلغ`,
  amountShouldNotBeLessThan: (...v) => `المبلغ لا يجب أن يكون أقل من ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `أعمال فنية من جميع أنحاء العالم. أعمال فنية مختارة من عالم الأنمي. اختيارنا الفني عبارة عن قائمة لا نهاية لها من أفضل الأعمال الفنية للأنمي.`,
  animeArtSubscribeToArtistsLikeAndCreate: `أعمال أنمي فنية - تابع مختلف الفنانين, أبدي إعجابك وأنشئ مجموعاتك`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `أنمي.كلوب - أول موقع يقدم للفنانين أرباح من مشاهدات قوقل آد-سينس. ادعم الفنانين بمشاهدة محتواهم أو أبدأ الربح من خلال المشاهدات`,
  animeClubViewPostAndEarnFromAnimeContent: `أنمي.كلوب - شاهد وانشر واربح من محتوى عالم الأنمي`,
  animeCommunity: `مجتمع الأنمي`,
  animeDotclubNeverAsksForYourPrivateInformation: `أنمي.كلوب لا يطلب أبدًا معلوماتك الخاصة`,
  animeSocialNetwork: `شبكة الأنمي الاجتماعية`,
  announcements: `الإعلانات`,
  apply: `تطبيق`,
  appSettings: `إعدادات التطبيق`,
  appsVersionIs: `نسخة التطبيق`,
  areYouSureYouWantTo: `هل أنت متأكد من`,
  art: `أعمال فنية`,
  artAssociatedWithAnime: `أعمال فنية متعلقة بالأنمي`,
  artBy: (...v) => `فن من ${v[0]}`,
  artCannotBeChanged: `العمل الفني لا يمكن تغييره`,
  artworksAvailableToView: (...v) => `${v[0]} لوحات فنية متاحة للعرض`,
  authenticationFailed: `فشلت المصادقة`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `النشر التلقائي على إنستغرام متاح فقط لحسابات الأعمال على إنستغرام`,
  attentionYourOrderHasBeenDisputed: `انتباه! تم الاعتراض على طلبك. يرجى التحقق من التفاصيل`,
  awaitingReview: `في انتظار المراجعة`,
  awaitingSeller: `في انتظار البائع`,
  back: `الرجوع`,
  basePrice: `السعر الأساسي`,
  block: `حظر`,
  blockUser: (...v) => `حظر @${v[0]}`,
  blog: `المدونة`,
  bookmarks: `العلامات المرجعية`,
  browseArt: `تصفح الأعمال`,
  browseShop: `تصفح المتجر`,
  buyer: `المشتري`,
  cancel: `إلغاء`,
  canceled: `تم الإلغاء`,
  cancelOrder: `إلغاء الطلب`,
  cancellationReason: `سبب الإلغاء`,
  cancellationInitiator: `مبادر الإلغاء`,
  cannotStartWithChars: `لا يمكن البدء بـs{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `تغيير`,
  checkOrderStatus: `تحقق من حالة الطلب`,
  changeArt: `تغيير العمل الفني`,
  changeAvatar: `تغيير الصورة الشخصية`,
  changeEmail: `تغيير البريد الإلكتروني`,
  changePassword: `تغيير كلمة السر`,
  chooseExistingChatOrStartANewOne: `اختر محادثةً موجودة أو ابدأ دردشة جديدة`,
  city: `المدينة`,
  clearAll: `امسح الكل`,
  clientReview: `مراجعة العميل`,
  close: `أغلق`,
  colorTheme: `موضوع اللون`,
  comingSoon: `قريبًا...`,
  commercialUse: `الاستخدام التجاري`,
  community: `المجتمع`,
  completed: `تم الانتهاء`,
  confirmAccount: `تأكيد الحساب`,
  confirmOrder: `تأكيد الطلب`,
  confirmPassword: `تأكيد كلمة السر`,
  connectWithUsOn: `الاتصال بنا على`,
  contactInformation: `معلومات الاتصال`,
  contactSeller: `الاتصال بالبائع`,
  contactSupport: `الاتصال بالدعم الفني`,
  contactUs: `اتصل بنا`,
  continue: `استمرار`,
  contractTitle: `عنوان العقد`,
  copyLink: `نسخ الرابط`,
  congratulations: `تهانينا!`,
  copyrightViolation: `انتهاك حقوق النشر`,
  couldNotCreateANewRecord: `تعذر إنشاء سجل جديد`,
  country: `الدولة`,
  cover: `الغلاف`,
  createANewAccountFailed: `فشل إنشاء حساب جديد`,
  createExtrasForYourProduct: `إنشاء إضافات لمنتجك`,
  createNewAccount: `إنشاء حساب جديد`,
  createYourShop: `إنشاء متجرك`,
  currentPassword: `كلمة المرور الحالية`,
  daily: `يوميًا`,
  darkDefault: `الافتراضي الداكن`,
  darkHighContrast: `عالي التباين الداكن`,
  dayTheme: `موضوع النهار`,
  delete: `حذف`,
  deleteShop: `حذف المتجر`,
  deleteAccount: `حذف الحساب`,
  deleteArt: `حذف الرسم`,
  decline: `رفض`,
  deletePost: `حذف المنشور`,
  deleteProduct: `حذف المنتج`,
  deliveryTime: `وقت التسليم`,
  describeTheDetailsOfYourProduct: `وصف تفاصيل منتجك`,
  description: `الوصف`,
  details: `التفاصيل`,
  didntReceiveEmail: `لم تتلقى البريد؟`,
  displayName: `اسم العرض`,
  disputed: `متنازع عليه`,
  donations: `التبرعات`,
  done: `انتهاء`,
  dragAndDropOrSelectFiles: `اسحب وأفلت أو حدد الملفات`,
  drawingContest: `مسابقة الرسم`,
  dueDate: `تاريخ الاستحقاق`,
  earlier: `أقرب`,
  earningFromArts: `الربح من خلال نشر أعمالك الفنية`,
  edit: `تعديل`,
  editPost: `تعديل المنشور`,
  editProfile: `تعديل الملف الشخصي`,
  editTranslations: `تعديل الترجمات`,
  email: `البريد الإلكتروني`,
  emailAlreadyUsedByAnotherAccount: `البريد الإلكتروني قيد الاستخدام من قبل حساب آخر`,
  emailNotifications: `إشعارات البريد الإلكتروني`,
  enterOrPasteALink: `أدخل أو ألصق رابطًا`,
  enterTheAddressAssociatedWithYourAccount: `أدخل العنوان المرتبط بحسابك، وسنرسل لك رابطًا لإعادة تعيين كلمة المرور`,
  enterYourPassword: `أدخل كلمة المرور الخاصة بك`,
  error: `خطأ`,
  errorPleaseContactCustomerSupport: `خطأ! الرجاء التواصل مع دعم العملاء...`,
  exitWithoutSaving: `الخروج بدون حفظ`,
  extensions: `امتدادات الملف`,
  extras: `إضافات`,
  fileSizeIsTooBig: `حجم الملف أكبر من المطلوب`,
  fileSizeIsTooSmall: `حجم الملف صغير جدًا`,
  filter: `تصفية`,
  filterBy: `تصفية على حسب`,
  findUser: `البحث عن مستخدم`,
  finishSettingUpYourShop: `إنهاء إعداد متجرك`,
  follow: `متابعة`,
  followers: `متابعون`,
  following: `تُتابع`,
  followMeOn: `تابعني على`,
  follows: `متابعون`,
  forAllOtherInquiriesPleaseContactUsAt: `لباقي الاستفسارات, اتصل بنا على:`,
  forgotPassword: `نسيت كلمة السر`,
  fromAnimeDotClub: `من أنمي.كلوب`,
  getDetails: `الحصول على تفاصيل`,
  getStarted: `البدء`,
  guestView: `وضع الضيف`,
  greatNewsYourOrderIsNowInProgress: `أخبار رائعة! طلبك الآن قيد التنفيذ`,
  harassment: `التحرش`,
  haveAnyQuestions: `هل لديك أي أسئلة؟`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> قد ألغى الطلب`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]} لم يضف وصفًا لـ "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} لم يشارك أي تفاصيل عامة حتى الآن`,
  hate: `الكراهية`,
  hire: `توظيف`,
  homepage: `الصفحة الرئيسية`,
  howToContactYou: `كيفية الاتصال بك`,
  howToFindYouOnOtherSocialNetworks: `كيفية العثور عليك على شبكات التواصل الاجتماعي الأخرى`,
  iAgreeWith: `أتفق على`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `إذا لم يكن هناك رد بحلول ${v[0]}, سيتم وضع علامة على الطلب كمكتمل تلقائيًا`,
  id: `المُعرف`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `ارتفاع الصورة يحتاج أن يكون أكبر من أو يساوي`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `عرض الصورة يحتاج أن يكون أكبر من أو يساوي`,
  impersonation: `الانتحال`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `تضمين الكلمات الرئيسية التي قد يستخدمها المشترون للبحث عن منتج مثل منتجك`,
  inProgress: `قيد التقدم`,
  introduction: `مقدمة`,
  invalidCode: `رمز غير صحيح`,
  invalidCurrentPassword: `كلمة المرور الحالية غير صالحة`,
  invalidDate: `تاريخ غير صالح`,
  invalidPartAfterAt: `جزء غير صالح بعد @`,
  invalidPartBeforeAt: `جزء غير صالح قبل @`,
  jobDetails: `تفاصيل الوظيفة`,
  joinAnimeClubCommunity: `انضم إلى مجتمع أنمي.كلوب مع الآلاف من الأشخاص النشطين والفنانين الرائعين كل يوم`,
  joinChat: `الانضمام للمحادثة`,
  joinUsOnFacebook: `انضم معنا على الفيسبوك`,
  language: `اللغة`,
  lackOfInformation: `نقص في المعلومات`,
  languages: `اللغات`,
  letEveryoneKnowHowToDonateToYou: `اسمح للجميع بمعرفة كيفية التبرع لك`,
  letOthersKnowAboutYou: `اسمح للآخرين بمعرفة معلومات عنك`,
  letsUploadYourFirstProduct: `لنقم بتحميل منتجك الأول`,
  letUsKnowWhatsHappening: `اسمح لنا بمعرفة ما يحدث وسنتحقق من ذلك`,
  lightDefault: `الإضاءة الافتراضية الفاتحة`,
  lightHighContrast: `التباين الفاتح العالي`,
  likes: `إعجابات`,
  limit: `الحد`,
  linkCopiedToClipboard: `تم نسخ الرابط إلى الحافظة`,
  livesIn: `أعيش في`,
  loading: `جار التحميل`,
  location: `الموقع`,
  logInOrSignUp: `تسجيل الدخول أو التسجيل`,
  logOut: `تسجيل الخروج`,
  maximumNChars: (...v) => `الحد الأقصى للأحرف ${v[0]}`,
  maximumNumberOfDaysToCompleteTheOrder: `الحد الأقصى لعدد الأيام لإكمال الطلب`,
  maximumQuantity: `الحد الأقصى للكمية`,
  maxSize: `الحجم الأقصى`,
  menu: `القائمة`,
  message: `رسالة`,
  messages: `الرسائل`,
  minHeight: `الارتفاع الأدنى`,
  minimumNChars: (...v) => `الحد الأدنى ${v[0]} حرف`,
  minorAbuseOrSexualization: `إساءة أو جنسنة طفيفة`,
  minWidth: `العرض الأدنى`,
  monthly: `شهريًا`,
  moreFrom: (...v) => `المزيد من خلال ${v[0]}`,
  mustBeNChars: (...v) => `لا بد أن تكون ${v[0]} حرف`,
  myPayments: `مدفوعاتي`,
  myProfile: `ملفي الشخصي`,
  mySettings: `إعداداتي`,
  need1Lowercase: `يلزم 1 حرف صغير`,
  need1Number: `يلزم 1 رقم`,
  need1Uppercase: `يلزم 1 حرف كبير`,
  needAtLeast1CharacterFromN: (...v) =>
    `يلزم على الأقل 1 حرف كبير من [${v[0]}]`,
  needNCharacter: (...v) => `يلزم ${v[0]} حرف`,
  newAccount: `حساب جديد`,
  newArt: `عمل فني جديد`,
  newArtworks: `أعمال فنية جديدة`,
  newBlog: `منشور جديد`,
  newOrder: `طلب جديد`,
  newPassword: `كلمة سر جديدة`,
  newProduct: `منتج جديد`,
  newsFeed: `شريط الأخبار`,
  next: `التالي`,
  nextTimeYouAuthenticateYouCouldUseThe: `في المرة القادمة التي تقوم فيها بالمصادقة، يمكنك استخدام الحساب المتصل بدلاً من تسجيل الدخول وكلمة المرور`,
  nightTheme: `موضوع الليل`,
  no: `لا`,
  noAddedFavoriteArts: `لا توجد أي رسومات مُفضلة تمت إضافتها`,
  noInternetConnection: `لا يوجد اتصال بالانترنت!`,
  nonConsensualIntimateContent: `محتوى حميم غير مرغوب فيه`,
  none: `لا شيء`,
  noNotifications: `لا توجد إشعارات`,
  noResults: `لا توجد نتائج`,
  notifications: `الإشعارات`,
  noActiveOrdersToShow: `لا توجد طلبات نشطة للعرض`,
  notAcceptingOrders: `لا يقبل الطلبات`,
  nsfwContent18Plus: `محتوى للبالغين (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `عدد التعديلات التي يمكن للعميل طلبها`,
  online: `متصل`,
  onlyLatinLettersNumbersHyphen: `فقط الأحرف اللاتينية والأرقام والشرطة والشرطة السفلية والنقطة`,
  onlyNumbers: `أرقام فقط`,
  open: `مفتوح`,
  openDispute: `فتح نزاع`,
  openGuestView: `افتح وضع الضيف`,
  openingSoon: `قريبًا الافتتاح!`,
  openToWork: `مفتوح للعمل`,
  optional: `اختياري`,
  or: `أو`,
  order: `طلب`,
  outOfStock: `غير متوفر`,
  ordered: (...v) => `تم الطلب ${v[0]}`,
  orderAgain: `أعد الطلب مرة أخرى`,
  orderDetails: `تفاصيل الطلب`,
  orderConfirmed: `تم تأكيد الطلب`,
  orderStatus: `حالة الطلب`,
  orderOptions: `خيارات الطلب`,
  otherReason: `سبب آخر`,
  pageNotFound: `الصفحة غير موجودة`,
  password: `كلمة السر`,
  payments: `المدفوعات`,
  personal: `شخصي`,
  personalCircumstances: `ظروف شخصية`,
  pleaseCheckYour: (...v) => `يرجى التحقق من ${v[0]} الخاص بك`,
  pleaseDoNotShareYourPrivateInformationToOthers: `يرجى عدم مشاركة معلوماتك الخاصة مع الآخرين`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `يرجى إدخال رقم بين ${v[0]} و ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `الرجاء إدخال ${v[0]} أحرف على الأقل`,
  pleaseFillOutYourDetails: `الرجاء تعبئة بياناتك`,
  pleaseSignInToYourAccount: `الرجاء تسجيل الدخول لحسابك`,
  platform: `منصة`,
  pleaseStartTyping: `يرجى البدء في الكتابة`,
  pleaseTryAgainOrClick: (...v) =>
    `يرجى المحاولة مرة أخرى أو النقر فوق ${v[0]}`,
  pleaseVerifyYourAccount: `الرجاء تأكيد حسابك`,
  pressHereTo: `أضغط هنا من أجل`,
  price: `السعر`,
  privacyPolicy: `سياسة الخصوصية`,
  privateInformation: `المعلومات الخاصة`,
  proceedToCheckout: `المتابعة للدفع`,
  product: `المنتج`,
  profile: `ملف التعريف`,
  prohibitedTransaction: `المعاملة المحظورة`,
  promotions: `العروض الترويجية`,
  publicInformation: `المعلومات العامة`,
  publishOn: (...v) => `النشر على ${v[0]}`,
  purchases: `المشتريات`,
  rankings: `التصنيفات`,
  reorderFiles: `إعادة ترتيب الملفات`,
  report: `الإبلاغ`,
  revisions: `المراجعات`,
  sales: `المبيعات`,
  save: `حفظ`,
  saveAvatar: `حفظ الصورة الشخصية`,
  saveChanges: `حفظ التغييرات`,
  selectAnime: `اختر أنمي`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `اختر موضوعًا واحدًا أو مزامنته مع نظامك والتبديل تلقائيًا بين موضوعات النهار والليل`,
  selectAvatar: `اختر صورة شخصية`,
  selectCharacters: `اختر شخصية`,
  seller: `البائع`,
  selectFile: `اختر ملف`,
  selectTheme: `اختر موضوعًا`,
  selectThumbnail: `اختر صورة مصغرة`,
  selfHarmOrSuicide: `الإيذاء الذاتي أو الانتحار`,
  sendEmail: `ارسل رسالة بريد`,
  settings: `الإعدادات`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `إعداد متجر مجاني ويستغرق بضع دقائق فقط`,
  share: `مشاركة`,
  shareYourArtWithTheWorld: `شارك فنك مع العالم`,
  shareYourStory: `شارك قصتك!`,
  sharingPersonalInformation: `مشاركة المعلومات الشخصية`,
  shop: `تسوق`,
  shopOrders: `طلبات المتجر`,
  showLess: `عرض أقل`,
  showMore: `عرض أكثر`,
  signIn: `تسجيل دخول`,
  singleTheme: `موضوع واحد`,
  size: `الحجم`,
  skip: `تخطى`,
  socialMedia: `وسائل التواصل الاجتماعي`,
  spaceCharacterIsNotAllowed: `غير مسموح بالمسافة`,
  spam: `البريد المزعج`,
  submitAReport: `إرسال تقرير`,
  submitWork: `إرسال العمل`,
  subscribeToTalentsToKeepUpWithTheirProgress: `اشترك في صفحات المواهب لمتابعة إنجازاتهم`,
  successChangedPasswordPleaseSignIn: `تم بنجاح تم تغيير كلمة السر. الرجاء تسجيل الدخول`,
  successCreatedRecord: `تم بنجاح إنشاء السجل!`,
  successUpdatedRecord: `تم بنجاح تحديث السجل!`,
  supportMeOn: `ادعمني على`,
  syncWithSystem: `مزامنة مع النظام`,
  tellUsAboutYourself: `اخبرنا عن نفسك`,
  termsAndConditions: `الأحكام والشروط`,
  termsOfUse: `شروط الاستخدام`,
  thankYouForReport: `شكرًا لمساعدتك في الحفاظ على مجتمع آمن ومحترم عبر الإنترنت`,
  theLinkIsBrokenOrPageHasBeenRemoved: `الرابط معطل أو تمت إزالة الصفحة`,
  themeMode: `وضع الموضوع`,
  thisIsThePriceYouPropose: `هذا هو السعر الذي تقترحه`,
  threateningViolence: `تهديد العنف`,
  title: `العنوان`,
  timeConstraints: `قيود الوقت`,
  titleYourExtraService: `عنوان خدمتك الإضافية`,
  theMaximumQuantityThatACustomerCanAdd: `الحد الأقصى للكمية التي يمكن للعميل إضافتها`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `فترة المراجعة محدودة بـ ${v[0]} أيام`,
  toHelpTheCreatorCompleteYourOrder: `لمساعدة المنشئ في إكمال طلبك بما يرضيك، يرجى تقديم وصف تفصيلي لما تريده. قم بتضمين الموضوع المطلوب، النمط، وميزات الشخصية، وأي مواصفات مهمة أخرى`,
  today: `اليوم`,
  toGetWorkRelatedNotifications: `للحصول على إشعارات تتعلق بالعمل`,
  total: `الإجمالي`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `لعرض هذه البيانات، تحتاج إلى إلغاء حظر @${v[0]}`,
  trademarkViolation: `انتهاك العلامة التجارية`,
  typeYourTextHere: `ادخل النص هنا...`,
  unblock: `إلغاء الحظر`,
  unblockUser: (...v) => `إلغاء حظر @${v[0]}`,
  unfollow: `إلغاء المتابعة`,
  unlimited: `غير محدود`,
  upload: `تحميل`,
  uploadNew: `تحميل جديد`,
  uploadNewPost: `تحميل منشور جديد`,
  uploadNewProduct: `تحميل منتج جديد`,
  username: `اسم المستخدم`,
  usernameAlreadyExists: `اسم المستخدم مستخدم من قبل`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> و ${v[1]} يتابعونك`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `<b>${v[0]}</b> و ${v[1]} يعجبون بعملك الفني`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b> يتابعك`,
  usernameLikesYourArt: (...v) => `<b>${v[0]}</b> يعجب بعملك الفني`,
  useThisEmailTo: `استخدم هذا البريد الإلكتروني للمصادقة وتلقي الإشعارات`,
  valueIsNotTheSame: `القيمة ليست هي نفسها`,
  verificationCode: `رمز التأكيد`,
  verifyCode: `أكد الرمز`,
  viewDetails: `عرض التفاصيل`,
  viewReview: `عرض المراجعة`,
  viewEveryNotificationOfAGroupSeparately: `عرض كل إشعار من مجموعة بشكل منفصل`,
  visitOurDiscordChannelToGetMoreDetails: `قم بزيارة قناتنا في ديسكورد للحصول على مزيد من التفاصيل`,
  weAreOnInstagram: `تجدنا على انستقرام`,
  weAreWorkingOnIt: `نعمل على الأمر`,
  wellDoneYourWorkHasBeenSuccessfullyCompleted: `عمل جيد! تم إكمال عملك بنجاح`,
  weDoNotDisplayNSFWContentYet: `لا نعرض محتوى للبالغين بعد`,
  weekly: `أسبوعيًا`,
  whenYouPurchaseSomethingItWillAppearHere: `عند شراء شيء ما، سيظهر هنا`,
  weHaveSentTooManyEmails: `لقد أرسلنا الكثير من الرسائل الإلكترونية، يرجى المحاولة مرة أخرى في وقت لاحق أو الاتصال بخدمة العملاء`,
  welcomeToAnimeClub: `أهلًا بك في أنمي.كلوب!`,
  weSentAnEmailTo: `أرسلنا بريد إلكتروني إلى:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `قمنا بإرسال رسالة تأكيد جديدة على البريد. الرجاء إدخال رمز التأكيد`,
  weAreExcitedToSeeYourProgressKeepItUp: `نحن متحمسون لرؤية تقدمك. استمر في ذلك!`,
  weSupportOnlyTheFollowingFileExtensions: `ندعم فقط امتدادات الملفات التالية:`,
  work: `عمل`,
  weWouldLoveToHearFromYou: `نود أن نسمع منك`,
  workDescription: `وصف العمل`,
  leaveAReview: `اترك مراجعة`,
  wrongEmailOrPassword: `البريد الإلكتروني أو كلمة المرور غير صحيحين`,
  yes: `نعم`,
  yesterday: `أمس`,
  youReceivedANewOrderFrom: (...v) =>
    `لقد تلقيت طلبًا جديدًا من <b>${v[0]}</b>`,
  youHaveSuccessfullyCreatedYourShop: `لقد أنشأت متجرك بنجاح`,
  youAreAlreadyAuthenticated: `سبق وقمنا بالتحقق من حسابك`,
  youCanAutoPublishToYourSocialMediaAccount: `يمكنك النشر التلقائي على حسابات التواصل الاجتماعي الخاصة بك`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `يمكنك تعديل أنواع الإشعارات التي تتلقاها عبر البريد الإلكتروني`,
  youCanRequestRemovalOfYourAccount: `يمكنك طلب إزالة حسابك مع جميع بياناتك`,
  youCanStillNavigateToThePreviouslyOpenedPages: `لا يزال بإمكانك التنقل للصفحات المفتوحة مسبقًا`,
  youDidNotSelectAnyChats: `لم تُحدد أي محادثات`,
  youDidNotUpdateAnyValues: `لم تقم بتحديث أي قيم`,
  youDoNotHaveAnyChats: `ليس لديك أي محادثات`,
  youHaveNotSetAPassword: `لم تقم بتعيين كلمة مرور`,
  youHaveNotSharedAnythingYet: `لم تشارك أي شيء حتى الآن`,
  youHaveReachedTheMaximumNumberOfFiles: `لقد وصلت إلى الحد الأقصى لعدد الملفات`,
  kindlyHoldOnForTheBuyersReview: `يرجى الانتظار لمراجعة المشتري للطلب.`,
  yourAccountIsVerifiedPleaseSignIn: `تم التحقق من حسابك. الرجاء تسجيل الدخول`,
  yourAccountWillBeRemoved: (...v) => `سيتم إزالة حسابك ${v[0]}`,
  youHaveNoPurchases: `ليس لديك أي مشتريات`,
  couldYouPleaseProvideTheReasonForTheCancellation: `هل يمكنك تقديم سبب الإلغاء من فضلك`,
  yourFeedbackWouldBeGreatlyAppreciated: `سيكون تقديرنا لملاحظاتك كبيرًا`,
  yourArts: `أعمالك الفنية`,
  yourAvatar: `صورتك الشخصية`,
  yourBlog: `مدونتك`,
  yourFansAreWaiting: `معجبيك في انتظارك`,
  yourFeedIsEmpty: `شريطك الإخباري فارغ`,
  yourSessionHasExpiredPleaseSignInAgain: `انتهت جلستك, الرجاء تسجيل الدخول مجددًا`,
}
