import { text as traditional } from "./chinese-traditional"
import { regionalize } from "./chinese-traditional-regionalize"

const regional = regionalize(traditional, [
  [`文件`, `檔案`],
  [`消息`, `訊息`],
  [`在線`, `網上`],
  [`電子郵件`, `電郵`],
  [`郵件`, `電郵`],
  [`使用者`, `用戶`],
  [`網路`, `網絡`],
  [`意見回饋`, `意見`],
  [`檢舉`, `舉報`],
  [`上傳`, `上載`],
  [`聯繫`, `聯絡`],
  [`結賬`, `結帳`],
  [`分辨率`, `解像度`],
  [`定制`, `訂製`],
  [`擴展名`, `副檔名`],
  [`回復`, `回覆`],
] as const)

/** Traditional Chinese for Hong Kong, also used as the initial Macau wording baseline. */
export const text: text = {
  ...regional,
  accountActivation: `帳戶啟用`,
  accountAlreadyExists: `帳戶已存在`,
  advancedOptions: `進階選項`,
  animeSocialNetwork: `動漫\n社交網絡`,
  appSettings: `應用程式設定`,
  appsVersionIs: `應用程式版本為`,
  back: `返回`,
  cannotStartWithChars: `不能以下列字符開頭：{:"^$*[]{}()?-"!@#%&/\\,><':;|~\``,
  close: `關閉`,
  currentPassword: `現時密碼`,
  digitalDownloads: `數碼下載`,
  enterOrPasteALink: `輸入或貼上連結`,
  filter: `篩選`,
  filterBy: `篩選依據`,
  follow: `關注`,
  following: `正在關注`,
  followMeOn: `在以下平台關注我`,
  guestView: `訪客模式`,
  id: `ID`,
  invalidCurrentPassword: `現時密碼無效`,
  messages: `訊息`,
  minorAbuseOrSexualization: `虐待或性化未成年人`,
  moreFrom: (username: string) => `更多來自 ${username} 的作品`,
  needAtLeast1CharacterFromN: (characters: string) => `至少需要一個 [${characters}] 中的字符`,
  needNCharacter: (character: string) => `需要字符 ${character}`,
  newsFeed: `動態消息`,
  no: `否`,
  notes: `備註`,
  offerDigitalProducts: `提供買家可立即取得的數碼商品`,
  openDispute: `提出爭議`,
  openDisputeChat: `開啟爭議聊天室`,
  or: `或`,
  paymentProcessingFee: `付款處理費`,
  payouts: `款項發放`,
  platformFee: `平台費`,
  pleaseTryAgainOrClick: (buttonName: string) => `請再試一次，或點擊 ${buttonName}`,
  proceedToCheckout: `前往結帳`,
  profile: `個人資料`,
  sellerNet: `賣家實收`,
  settings: `設定`,
  skip: `跳過`,
  tax: `稅項`,
  theReviewPeriodIsLimitedtoNdays: (numOfDays: number | string) =>
    `審核期為 <b>${numOfDays}</b> 天`,
  uploadNewPost: `上載新帖文`,
  username: `用戶名稱`,
  usernameAlreadyExists: `此用戶名稱已存在`,
  verifyCode: `驗證`,
  weekly: `每週`,
  yourFeedIsEmpty: `您的動態消息目前沒有內容`,
}
