export const text: text = {
  _colon: `：`,
  _comma: `、`,
  _dot: `。`,
  _exclamation: `！`,
  _question: `？`,
  _space: ``,
  _hyphen: `—`,
  about: `关于`,
  accept: `接受`,
  acceptOrder: `接受订单`,
  acceptTheOrder: `接受订单`,
  accountManagment: `账户管理`,
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `Anime.club 使用 ${v[0]}，让您快速收款，并保障您的个人信息和付款信息安全`,
  account: `账户`,
  accountDeleted: `账户已删除`,
  clickTheButtonBelowToOpenYourStripeDashboard: `点击下方按钮打开 Stripe 控制面板并查看账户详情`,
  animeShopBuyAndSellProducts: `动漫商店 - 购买和出售产品`,
  visitStripeDashboard: `访问 Stripe 控制面板`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `禁止使用AI生成的图片和神经网络滤镜`,
  accountActivation: `帐号激活`,
  accountAlreadyExists: `用户名已经被注册`,
  accountDoesNotExist: `帐号不存在`,
  accountRemoval: `账户删除`,
  files: `文件`,
  prohibitedTransaction: `禁止的交易`,
  add: `加`,
  addArt: `添加艺术品`,
  addBlog: `添加博客`,
  additionalResources: `附加资源`,
  addMoreProductsToYourShop: `为您的商店添加更多产品`,
  addMore: `添加更多`,
  addNewArt: `添加新艺术品`,
  addSignInVia: `通过添加登录`,
  addToCart: `添加到购物车`,
  advancedOptions: `高级选项`,
  uploadTheFilesYourBuyerWillGet: `上传<b>买家将收到的</b>文件`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `请确保一切准备就绪——发布后无法编辑`,
  filesForTheBuyer: `提供给买家的文件`,
  filesForPreview: `预览文件`,
  all: `全部`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `您在此上传的所有文件都将对买家可见`,
  alreadySignedIn: `已登录`,
  amount: `金额`,
  amountShouldNotBeLessThan: (...v) => `金额不应少于 ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `来自世界各地的艺术家的动漫艺术。策划艺术与动漫有关。艺术选择是最佳动漫艺术的无限清单`,
  animeArtSubscribeToArtistsLikeAndCreate: `动漫艺术-订阅喜欢的艺术家并创建收藏`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club-第一个通过Google AdSense向观看者提供艺术家付款的平台。通过查看艺术家的内容或开始从观看中获得收益来支持艺术家`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club-查看，发布动漫内容并从中获得收益`,
  animeCommunity: `动漫社区`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club从不要求您的私人信息`,
  animeSocialNetwork: `动漫社交网络`,
  announcements: `公告`,
  appearance: `外观`,
  apply: `申请`,
  appSettings: `应用设置`,
  appsVersionIs: `应用的版本为`,
  areYouSureYouWantTo: `你确定你要`,
  art: `艺术`,
  artAssociatedWithAnime: `与动漫相关的艺术`,
  artBy: (...v) => `${v[0]}的艺术品`,
  artCannotBeChanged: `艺术不能改变。`,
  artworksAvailableToView: (...v) => `有${v[0]}件艺术品可供查看`,
  authenticationFailed: `验证失败`,
  system: `系统`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `自动发布到Instagram仅适用于Instagram商业账户`,
  attentionYourOrderHasBeenDisputed: `注意！您的订单已被争议。请检查详情`,
  needsYourReview: `需要您审核`,
  awaitingSellersResponse: `等待卖家回复`,
  back: `背部`,
  basePrice: `基础价格`,
  bigAppreciationToTheSellerForTheHardWork: `非常感谢卖家的辛勤付出`,
  block: `屏蔽`,
  buyerReviewedTheOrder: `买家已评价订单`,
  buyerHasNotLeftAReviewYet: `买家尚未留下评价`,
  feedbackReceived: `已收到反馈！`,
  blockUser: (...v) => `屏蔽@${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `在接受之前，请仔细查看买家的请求`,
  blog: `博客`,
  bookmarks: `书签`,
  browseArt: `浏览艺术品`,
  browseShop: `浏览商店`,
  buyer: `买家`,
  buyersRequest: `买家的请求`,
  cancel: `取消`,
  canceled: `已取消`,
  comments: `评论`,
  cancelOrder: `取消订单`,
  cannotStartWithChars: `无法以{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `更改`,
  checkOutMyShop: `查看我的商店`,
  checkOrderStatus: `检查订单状态`,
  changeArt: `改变艺术`,
  changeAvatar: `更改头像`,
  changeEmail: `更改电子邮件`,
  changePassword: `更改密码`,
  chooseExistingChatOrStartANewOne: `选择现有的聊天或开始新的聊天`,
  city: `市`,
  clearAll: `全部清除`,
  awaitingClientReview: `等待客户审核`,
  close: `关`,
  color: `颜色`,
  colorTheme: `颜色主题`,
  comingSoon: `快来了…`,
  commercialUseAllowed: `允许商业用途`,
  commercialUseAllowsBuyersToUseYourProduct: `商业用途允许买家将您的产品用于销售或推广等商业目的`,
  community: `社区`,
  completed: `已完成`,
  confirmAccount: `确认帐号`,
  confirmOrder: `确认订单`,
  confirmPassword: `确认密码`,
  connectWithUsOn: `在以下社交媒体上关注我们`,
  contactInformation: `联系信息`,
  contactSeller: `联系卖家`,
  contactSupport: `联系支持`,
  contactUs: `联系我们`,
  continue: `继续`,
  contractTitle: `合同标题`,
  copy: `复制`,
  congratulations: `恭喜！`,
  thankYouForYourPurchase: `感谢您的购买！`,
  congratulationsOnSuccessfullyCompletingYourOrder: `恭喜您成功完成订单！`,
  copyrightViolation: `版权侵权`,
  couldNotCreateANewRecord: `无法创建新记录`,
  country: `国家`,
  cover: `封面`,
  createANewAccountFailed: `创建新帐户失败`,
  createExtrasForYourProduct: `为您的产品创建额外内容`,
  createNewAccount: `建立新帐户`,
  createAShopWithStripe: `通过Stripe创建商店`,
  createdBy: `创建者`,
  currentPassword: `当前密码`,
  daily: `每日`,
  dark: `深色`,
  delete: `删除`,
  deleteShop: `删除店铺`,
  deleteAccount: `删除账户`,
  deleteArt: `删除作品`,
  decline: `拒绝`,
  deletePost: `删除贴文`,
  deleteProduct: `删除产品`,
  download: `下载`,
  downloadThemBelow: `在下方下载`,
  deliveryTime: `交货时间`,
  describeTheDetailsOfYourExtra: `描述您的额外服务细节`,
  description: `描述`,
  details: `细节`,
  didntReceiveEmail: `没有收到邮件吗？`,
  displayName: `显示名称`,
  disputed: `有争议`,
  donations: `捐赠`,
  documentation: `文档`,
  done: `完成了`,
  dragAndDropOrSelectFiles: `拖放或选择文件`,
  drawingContest: `绘画比赛`,
  dueDate: `截止日期`,
  earlier: `更早`,
  earningFromArts: `艺术收入`,
  edit: `编辑`,
  editPost: `修改帖子`,
  editProfile: `编辑个人资料`,
  editTranslations: `编辑译文`,
  email: `电子邮件`,
  emailAlreadyUsedByAnotherAccount: `电子邮件已被另一账户使用`,
  emailNotifications: `电子邮件通知`,
  enterOrPasteALink: `输入或粘贴链接`,
  enjoyYourPurchase: `祝您购物愉快！😊`,
  enterTheAddressAssociatedWithYourAccount: `输入与您的帐户关联的地址，我们将向您发送重置密码的链接`,
  enterYourPassword: `输入您的密码`,
  error: `错误`,
  errorPleaseContactCustomerSupport: `错误！请联系客户支持...`,
  exitWithoutSaving: `退出而不保存`,
  extensions: `扩展名`,
  extras: `额外`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `额外服务是可选的附加功能，可提升您的产品`,
  fileSizeIsTooBig: `档案太大`,
  fileSizeIsTooSmall: `文件大小太小`,
  filter: `过滤`,
  filterBy: `过滤`,
  findUser: `寻找使用者`,
  finishSettingUpYourShop: `完成商店设置`,
  follow: `跟随`,
  followers: `追随者`,
  following: `下列的`,
  followMeOn: `跟我来`,
  follows: `关注`,
  forAllOtherInquiriesPleaseContactUsAt: `任何其他问题，请联系我们：`,
  forgotPassword: `忘记密码`,
  fromAnimeDotClub: `来自Anime.club`,
  getDetails: `获得详细信息`,
  getStarted: `开始`,
  guestView: `来宾视图`,
  greatNewsYourOrderIsNowInProgress: `好消息！您的订单正在进行中`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `好消息！${v[0]} 购买了您的商品。庆祝一下吧！`,
  harassment: `骚扰`,
  haveAnyQuestions: `有任何问题吗？`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> 已取消订单`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> 已提交作品`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]}没有为"${v[1]}"添加描述`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]}尚未分享任何公共详细信息`,
  usernameHasntListedAnyProductsForSaleYet: (...v) => `@${v[0]} 尚未上架任何商品`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) => `@${v[0]} 尚未在作品集中添加任何内容`,
  hate: `仇恨`,
  hereAreAFewWaysToGetThingsRolling: `以下是一些开始的方法`,
  hire: `雇佣`,
  hideListing: `隐藏商品`,
  uploadUpToNumberFiles: (...v) => `最多可上传 <b>${v[0]}</b> 个文件`,
  supportedFormats: `支持的格式：`,
  minimumDimensions: (...v) => `最小尺寸：${v[0]}×${v[1]} 像素`,
  maximumFileSize: (...v) => `单个文件最大：<b>${v[0]}</b>`,
  thisListingWontBeVisibleToBuyersAnymore: `买家将无法再看到此商品——您可以随时重新显示`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `买家将能看到此商品。您可以随时再次隐藏`,
  listingHiddenFromBuyers: `已对买家隐藏商品`,
  listingIsNowVisibleToBuyers: `商品现已对买家可见`,
  showListing: `显示商品`,
  homepage: `主页`,
  howToContactYou: `如何联系您`,
  howToFindYouOnOtherSocialNetworks: `如何在其他社交网络上找到您`,
  iAgreeWith: `我同意`,
  ifTheresNoResponseByTimeLimit: (...v) => `如果在 ${v[0]} 之前没有回应，订单将自动标记为已完成`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `如果在 ${v[0]} 前没有回复，订单将自动取消`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `如果在 ${v[0]} 前没有收到回复，您将自动获得全额退款`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `如果您错过截止时间，买家可以取消订单并获得全额退款，相关 Stripe 费用将从您的收款中扣除。`,
  id: `账号`,
  addAComment: `添加评论`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `图片高度必须大于或等于`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `图片宽度必须大于或等于`,
  impersonation: `冒充`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `这些规则由卖家提供，仅适用于此商品`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `如有疑问或顾虑，请直接联系卖家`,
  platformPoliciesMayStillApply: `平台政策仍可能适用`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `包括买家可能用于搜索类似于您产品的关键字`,
  increaseContrast: `增强对比度`,
  inProgress: `进行中`,
  introduction: `介绍`,
  includes: `包含`,
  invalidCode: `无效的代码。`,
  invalidCurrentPassword: `当前密码无效`,
  invalidDate: `无效日期`,
  invalidPartAfterAt: `@之后的无效部分`,
  invalidPartBeforeAt: `@之前的无效部分`,
  jobDetails: `工作详情`,
  joinAnimeClubCommunity: `加入Anime.club社区，每天有数千名活跃的创作者和酷炫的动漫艺术品`,
  joinChat: `加入聊天室`,
  joinUsOnFacebook: `加入我们的Facebook`,
  language: `语言`,
  lackOfInformation: `信息不足`,
  languages: `语言`,
  letEveryoneKnowHowToDonateToYou: `让每个人都知道如何向您捐赠`,
  letOthersKnowAboutYou: `让其他人了解您`,
  letsUploadYourFirstProduct: `让我们上传您的第一个产品`,
  letUsKnowWhatsHappening: `让我们知道发生了什么，我们会调查一下`,
  light: `浅色`,
  likes: `喜欢`,
  limit: `限制`,
  copiedToClipboard: `已复制到剪贴板`,
  livesIn: `住在`,
  loading: `加载中`,
  location: `位置`,
  logInOrSignUp: `登录或注册`,
  logOut: `退出登录`,
  maximumNChars: (...v) => `最多${v[0]}个字符`,
  maximumNumberOfDaysToCompleteTheOrder: `完成订单的最大天数`,
  maximumQuantity: `最大数量`,
  maxSize: `最大尺寸`,
  menu: `菜单`,
  uploadedFilesLocked: `这些文件是您创建帖子时上传的。现已锁定，但仍显示在下方`,
  message: `消息`,
  messages: `私信`,
  minHeight: `最小高度`,
  minimumNChars: (...v) => `最少${v[0]}个字符`,
  minorAbuseOrSexualization: `轻微虐待或性化`,
  makeSureToIncludeClearInstructions: `请确保包含每个参考资料的清晰使用说明`,
  makeSureYouFullyUnderstandTheRequirements: `请确保您完全理解需求并能按时完成订单`,
  makeSureYourProductsArePricedCompetitively: `请确保您的产品定价具有竞争力`,
  minWidth: `最小宽度`,
  monthly: `每月`,
  moreFrom: (...v) => `更多`,
  mustBeNChars: (...v) => `必须是${v[0]}个字符`,
  myPayments: `我的付款`,
  myProfile: `我的个人资料`,
  mySettings: `我的设置`,
  need1Lowercase: `需要1个小写`,
  need1Number: `需要1个号码`,
  need1Uppercase: `需要1个大写`,
  needAtLeast1CharacterFromN: (...v) => `需要至少[${v[0]}]个字符`,
  needNCharacter: (...v) => `需要${v[0]}个字符`,
  new: `新`,
  newAccount: `新账户`,
  newArt: `新艺术`,
  createPersonalizedWorkTailoredToEachRequest: `根据每项请求创作个性化作品`,
  offerDigitalProducts: `提供买家可立即获取的数字商品`,
  instantDownload: `即时下载`,
  customWork: `定制作品`,
  newArtworks: `新艺术品`,
  newBlog: `新博客`,
  newOrder: `新订单`,
  newPassword: `新密码`,
  newProduct: `新产品`,
  allListings: `所有商品`,
  newCommission: `新委托`,
  newsFeed: `新闻专线`,
  next: `下一个`,
  nextTimeYouAuthenticateYouCouldUseThe: `下次验证时，您可以使用连接的帐户，而不是登录和密码`,
  no: `没有`,
  noOrders: `暂无订单`,
  noInternetConnection: `没有网络连接！`,
  nonConsensualIntimateContent: `非自愿亲密内容`,
  none: `无`,
  noNotifications: `没有通知`,
  noResults: `没有结果`,
  noReviewsJustYet: `暂时还没有评价`,
  noCommentsJustYet: `暂时还没有评论`,
  beTheFirstToShareYourThoughts: `成为第一个分享想法的人吧`,
  notifications: `通知事项`,
  noActiveOrdersToShow: `没有活动订单显示`,
  notAcceptingOrders: `不接受订单`,
  noSalesYetNoWorries: `还没有销售？别担心，您才刚刚开始`,
  nsfwContent18Plus: `NSFW内容（18+）`,
  NSFWIndicatesAdultContent: `18+ NSFW表示成人内容。仅当您的产品面向成熟观众时勾选此项`,
  numberOfAdjustmentsAClientCouldRequest: `客户可以请求的调整次数`,
  online: `在线`,
  onlyLatinLettersNumbersHyphen: `仅限拉丁字母、数字、连字符、下划线和点字符`,
  onlyNumbers: `仅数字`,
  onlyYouCanSeeWhatYouveSaved: `只有您可以看到您保存的内容`,
  open: `打开`,
  openDispute: `打开争议`,
  openGuestView: `开启访客检视`,
  openingSoon: `即将开业！`,
  openToWork: `接受工作机会`,
  optional: `可选的`,
  requestDetails: `请求详情`,
  or: `要么`,
  order: `订单`,
  outOfStock: `缺货`,
  ordered: (...v) => `已订购 ${v[0]}`,
  orderAgain: `再次下单`,
  orderDetails: `订单详情`,
  orderConfirmed: `订单已确认`,
  orderCompleted: `订单已完成 🎉`,
  orderStatus: `订单状态`,
  orderOptions: `订单选项`,
  otherReason: `其他原因`,
  pageNotFound: `页面未找到`,
  buyNow: `立即购买`,
  password: `密码`,
  payments: `付款方式`,
  attachedFiles: `附件`,
  numFilesIncluded: (...v) => `包含 <b>${v[0]}</b> 个文件`,
  personal: `个人`,
  personalCircumstances: `个人情况`,
  theseAreYourTermsForThisItem: `这是您为此商品设定的条款`,
  theBuyerAcceptedThemAtCheckout: `买家在结账时已接受这些条款`,
  nothingIsChargedUntilTheSellerAccepts: `卖家接受前不会扣款；如果卖家拒接，您不会被收取任何费用`,
  orderCanceledTheBuyersPaymentWasReleased: `订单已取消。我们已释放买家卡上的预授权，银行可能需要几天才能显示`,
  orderCanceledYourPaymentWasReleased: `订单已取消。我们已释放你卡上的预授权，银行可能需要几天才能显示`,
  yourTermsOfService: `您的服务条款`,
  showMyTermsOfService: `查看我的服务条款`,
  showSellerTermsOfService: `查看卖家的服务条款`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheSeller: `你填写的取消原因将会分享给卖家`,
  changedMyMind: `改变主意了`,
  orderedByMistake: `下单失误`,
  sellerHasntResponded: `卖家没有回应`,
  foundAnotherArtist: `找到了其他画师`,
  youWillBeAbleToUploadReferenceFilesAfterCheckout: `结账后即可上传参考文件`,
  tellTheBuyersWhatTheyWillGet: `明确告诉买家他们将获得什么，例如插画数量、文件格式，或分辨率和 DPI 等画布规格`,
  beSpecificAboutTheContent: `请具体说明内容（例如文件数量、格式、画布分辨率）`,
  mentionYourDeliveryTimeInDays: `注明您的<b>交付时间</b>（天数）`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `告知买家您是否提供<b>修改</b>以及可修改的次数`,
  listAnyContentOrRequestsYouDontAccept: `列出您<b>不接受</b>的内容或请求（例如 NSFW、政治、宗教或冒犯性材料）`,
  offerOptionalExtras: `提供可选附加服务，例如<b>加急交付</b>、<b>额外角色</b>或<b>精细背景</b>`,
  extrasHelpBoostIncome: `附加服务可让买家定制订单，也能提高您的收入`,
  pleaseAllowPopups: `请允许弹出式窗口`,
  pleaseCheckYour: (...v) => `请检查您的${v[0]}`,
  pleaseRateYourOrder: `请为您的订单评分`,
  feelFreeToShareReferenceImagesAndMaterials: `欢迎分享参考图片和资料，帮助艺术家创作您的作品`,
  pleaseDoNotShareYourPrivateInformationToOthers: `请勿向他人分享您的私人信息`,
  pleaseEnterANumberBetweenXandX: (...v) => `请输入${v[0]}和${v[1]}之间的数字`,
  pleaseEnterAtLeastNChars: (...v) => `请输入至少${v[0]}个字符`,
  pleaseFillOutYourDetails: `请填写您的详细信息`,
  pleaseFixTheErrorsBeforeSubmitting: `请在提交前修正错误`,
  pleaseSignInToYourAccount: `请登录到您的帐户`,
  platform: `平台`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `购买后即可立即下载文件，无需等待！`,
  thisIsACustomOrderNotAReadyMadeProduct: `这是定制订单，不是现成商品。您下单后，卖家才会开始创作`,
  pleaseStartTyping: `请开始输入`,
  pleaseTakeAMomentToReviewTheOrder: `请花点时间审核订单`,
  pleaseReviewTheBuyersReferenceFiles: `请查看买家的参考文件，并按订单描述要求执行`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `请在继续前仔细查看详情`,
  pleaseRespondToTheOrderBy: (...v) => `请在${v[0]}前回复订单`,
  pleaseTryAgainOrClick: (...v) => `请重复或者点击`,
  whatWouldYouLikeToCreate: `您想创作什么？`,
  shareYourArt: `分享您的艺术作品`,
  ifYourArtIsNsfwCheckThisToAvoidAWarningOrBan: `如果您的作品属于 NSFW，请务必勾选此项。否则您可能会收到警告，甚至导致封禁。`,
  takeCustomRequests: `接受定制请求`,
  sellDownloadableContent: `销售可下载内容`,
  digitalDownloadsExamples: `笔刷、素材、教程等`,
  artGallery: `艺术画廊`,
  commission: `委托`,
  commissions: `委托`,
  digitalDownloads: `数字下载`,
  pleaseVerifyYourAccount: `请验证您的帐户`,
  pressHereTo: `按这里`,
  price: `价格`,
  payouts: `付款`,
  privacyPolicy: `隐私政策`,
  privateInformation: `私人信息`,
  proceedToCheckout: `去结账`,
  product: `产品`,
  itemReviews: `商品评价`,
  portfolio: `作品集`,
  profile: `账户`,
  promotions: `促销`,
  publicInformation: `公共信息`,
  publishOn: (...v) => `发布于${v[0]}`,
  purchases: `购买`,
  rankings: `排名`,
  reorderFiles: `重新排序文件`,
  report: `举报`,
  review: `评价`,
  rules: `规则`,
  reviews: `评价`,
  numOfReviews: (...v) => `评价：${v[0]} `,
  reviewed: `已评价`,
  reviewTitle: `评价标题`,
  reason: `原因`,
  revisions: `修订版本`,
  includesXRevisionS: (...v) => `包含${v[0]}次修改`,
  sales: `销售额`,
  save: `保存`,
  saveAvatar: `保存头像`,
  saveChanges: `保存更改`,
  selectAnime: `选择动漫`,
  selectAppearanceContrastAndColorTheme: `选择外观、对比度和颜色主题`,
  selectAvatar: `选择头像`,
  selectCharacters: `选择角色`,
  seller: `卖家`,
  selectFile: `选择文件`,
  selectThumbnail: `选择缩略图`,
  selfHarmOrSuicide: `自残或自杀`,
  sendEmail: `发电子邮件`,
  settings: `设定值`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `设置商店是免费的，只需几分钟`,
  share: `分享`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `分享您的规则和不接受的请求类型`,
  shareYourShopOnSocialMedia: `在社交媒体上分享您的商店`,
  shareYourFavoritePiecesOn: (...v) => `在${v[0]}分享您喜欢的作品`,
  shareYourArtWithTheWorld: `与世界分享您的艺术品`,
  shareYourStory: `分享你的故事！`,
  sharingPersonalInformation: `分享个人信息`,
  shop: `店`,
  shopReviews: `商店评价`,
  shopOrders: `商店订单`,
  showLess: `显示较少`,
  showMore: `展示更多`,
  show: `显示`,
  hide: `隐藏`,
  signIn: `登入`,
  size: `大小`,
  skip: `跳跃`,
  socialMedia: `社交媒体`,
  spaceCharacterIsNotAllowed: `不允许使用空格字符`,
  spam: `垃圾邮件`,
  yourFavoritesWillShowUpHereAddSome: `您的收藏会显示在这里，快去添加吧！`,
  submitAReport: `提交报告`,
  submitWork: `提交作品`,
  subscribeToTalentsToKeepUpWithTheirProgress: `关注艺术家，追踪其动态`,
  successChangedPasswordPleaseSignIn: `成功！修改密码。请登录`,
  successCreatedRecord: `成功！创建记录！`,
  changesSaved: `更改已保存！`,
  successfullyDownloaded: `下载成功！`,
  successfullyUploaded: `上传成功！`,
  setUpStripeAccountToGetPaidWithAnimeClub: `设置 Stripe 账户以通过 Anime.club 收款`,
  supportMeOn: `支持我`,
  tellUsAboutYourself: `向我们介绍你自己`,
  sellerTermsOfService: `卖家服务条款`,
  termsAndConditions: `条款和条件`,
  termsOfUse: `使用条款`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `说明包含的内容以及买家购买后可以获得什么`,
  thankYouForReport: `感谢您帮助维护安全和尊重的在线社区`,
  thankYouForYourReview: `感谢您的评价！`,
  theLinkIsBrokenOrPageHasBeenRemoved: `链接已损坏或页面已删除`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `您提供的订单取消原因将与买家分享`,
  thisIsThePriceYouPropose: `这是您提议的价格`,
  thisFieldIsOptional: `此项为可选`,
  thisCannotBeUndone: `此操作无法撤销`,
  ensureYouveUploadedTheFinalVersion: `请确保您已上传最终版本再提交`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `您也可以添加描述，分享更多创作信息`,
  pleaseProvideATitleForYourArtwork: `请为您的艺术作品填写标题`,
  threateningViolence: `威胁暴力`,
  title: `标题`,
  timeConstraints: `时间限制`,
  titleYourExtraService: `为您的额外服务命名`,
  theMaximumQuantityThatACustomerCanAdd: `客户可以添加的最大数量`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `审查期限制为 ${v[0]} 天`,
  toHelpTheCreatorCompleteYourOrder: `为了帮助创作者完成您的订单，请提供详细的描述。包括所需的主题、风格和角色特征，以及任何其他重要规格`,
  today: `今天`,
  toGetWorkRelatedNotifications: `获取与工作相关的通知`,
  total: `总计`,
  toViewThisDataYouNeedToUnblock: (...v) => `查看此数据，您需要解除对 @${v[0]} 的屏蔽`,
  trademarkViolation: `商标侵权`,
  typeYourTextHere: `在此输入文字...`,
  theSellerHasUploadedTheseFilesForYou: `卖家已为您上传这些文件`,
  unblock: `解除屏蔽`,
  unblockUser: (...v) => `解除对 @${v[0]} 的屏蔽`,
  unfollow: `取消关注`,
  unlimited: `无限制`,
  upload: `上传`,
  uploadNew: `上载新`,
  uploadNewPost: `上载新讯息`,
  uploadNewProduct: `上传新产品`,
  username: `用户名`,
  pleaseUploadOnlyFinishedWorkHere: `请只在此上传已完成的作品`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `所有进行中的文件应在消息中上传`,
  usernameAlreadyExists: `此用户名已存在`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b>和${v[1]}个人关注了你`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b>和${v[1]}人有反应`,
  usernameStartedFollowingYou: (...v) => `<b>${v[0]}</b> 开始关注您`,
  usernameLeftAReaction: (...v) => `<b>${v[0]}</b> 留下了回应`,
  usernameCommentedOnYourWork: (...v) => `<b>${v[0]}</b> 评论了您的作品`,
  usernameAndXMoreCommented: (...v) => `<b>${v[0]}</b> 和另外 ${v[1]} 人发表了评论`,
  usernameRepliedToYourComment: (...v) => `<b>${v[0]}</b> 回复了您的评论`,
  usernameAndXMoreRepliedToYourComment: (...v) => `<b>${v[0]}</b> 和另外 ${v[1]} 人回复了您的评论`,
  useThisEmailTo: `使用此电子邮件进行身份验证、接收通知`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) => `很遗憾，${v[0]}不得不取消此订单`,
  valueIsNotTheSame: `两次输入不一致`,
  vote: `投票`,
  tapAddToCreateOne: `点击“添加”进行创建`,
  verificationCode: `验证码`,
  verifyCode: `验证码`,
  viewDetails: `查看详情`,
  viewReview: `查看评论`,
  viewEveryNotificationOfAGroupSeparately: `单独查看每个组的通知`,
  visitOurDiscordChannelToGetMoreDetails: `访问我们的discord 频道以获取更多详细信息`,
  weAreOnInstagram: `我们在Instagram上`,
  weAreWorkingOnIt: `我们正在做这件事`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `干得好！作品已成功完成`,
  weDoNotDisplayNSFWContentYet: `我们尚未显示NSFW内容`,
  weekly: `每周`,
  whenYouPurchaseSomethingItWillAppearHere: `当您购买某物时，它将出现在这里`,
  weHaveSentTooManyEmails: `我们发送了太多电子邮件，请稍后再试或联系客户支持`,
  welcomeToAnimeClub: `欢迎来到Anime.club！`,
  weSentAnEmailTo: `我们发送了电子邮件至：`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `我们向您发送了一封新的验证电子邮件。请输入验证码`,
  weAreExcitedToSeeYourProgressKeepItUp: `我们很高兴看到您的进步。继续保持！`,
  weSupportOnlyTheFollowingFileExtensions: `我们仅支持以下文件扩展名：`,
  work: `工作`,
  weWouldLoveToHearFromYou: `我们很想听到您的意见`,
  workDescription: `工作描述`,
  leaveAReview: `留下评论`,
  wrongEmailOrPassword: `邮箱或密码错误`,
  yes: `是`,
  yesterday: `昨天`,
  youReceivedANewOrderFrom: (...v) => `您收到来自 <b>${v[0]}</b> 的新订单`,
  youReceivedAReview: `您收到了一条评价`,
  reply: `回复`,
  youHaveSuccessfullyCreatedYourShop: `您已成功创建店铺`,
  replyToUsername: (...v) => `回复 ${v[0]}`,
  numOfReplies: (...v) => `${v[0]} 条回复`,
  numOfNewComments: (...v) => `${v[0]} 条新评论`,
  numOfNewReactions: (...v) => `${v[0]} 个新回应`,
  replies: `回复`,
  youAreAlreadyAuthenticated: `您已经通过验证`,
  youCanAutoPublishToYourSocialMediaAccount: `您可以自动发布到您的社交媒体帐户`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `您可以修改通过电子邮件接收的通知类型`,
  youCanRequestRemovalOfYourAccount: `您可以请求删除您的帐户及其所有数据`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `您的反馈会指导买家并帮助卖家提供更好的产品`,
  youCanStillNavigateToThePreviouslyOpenedPages: `您仍然可以导航到以前打开的页面`,
  youCanChooseFromTheListOrEnterACustomReason: `您可以从列表中选择，也可以输入自定义原因`,
  youDidNotSelectAnyChats: `您没有选择任何聊天`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `买家分享体验后，您将在这里看到评价`,
  youDidNotUpdateAnyValues: `您没有更新任何值`,
  youDoNotHaveAnyChats: `您没有任何聊天`,
  youHaveNotSetAPassword: `您还没有设置密码`,
  youHaveNotSharedAnythingYet: `您还没有分享任何内容`,
  youHaveReachedTheMaximumNumberOfFiles: `您已达到文件的最大数量`,
  kindlyHoldOnForTheBuyersReview: `请耐心等待买家对订单的评论。`,
  yourAccountIsVerifiedPleaseSignIn: `您的帐户已通过验证。请登录`,
  yourAccountWillBeRemoved: (...v) => `您的帐户将在${v[0]}被删除`,
  youHaveNoPurchases: `您没有购买记录`,
  couldYouPleaseProvideTheReasonForTheCancellation: `请提供取消的原因`,
  yourArts: `您的艺术`,
  youCanceledTheOrder: `您已取消订单`,
  yourAvatar: `您的头像`,
  yourBlog: `您的博客`,
  yourFansAreWaiting: `您的粉丝正在等待`,
  yourFeedIsEmpty: `您的专线为空`,
  yourSessionHasExpiredPleaseSignInAgain: `您的会话已过期，请重新登录`,
}
