/**
 * Shared Traditional Chinese base
 */
export const text: text = {
  _colon: `：`,
  _comma: `、`,
  _dot: `。`,
  _exclamation: `！`,
  _hyphen: `—`,
  _question: `？`,
  _space: ``,
  about: `關於`,
  accept: `接受`,
  acceptOrder: `接受訂單`,
  acceptTheOrder: `接受訂單`,
  account: `帳戶`,
  accountActivation: `帳號激活`,
  accountAlreadyExists: `使用者名已經被註冊`,
  accountDeleted: `帳戶已刪除`,
  accountDoesNotExist: `帳號不存在`,
  accountManagment: `帳戶管理`,
  accountRemoval: `帳戶刪除`,
  add: `加`,
  addAComment: `新增評論`,
  addArt: `新增藝術品`,
  addBlog: `新增網誌`,
  additionalResources: `附加資源`,
  addMore: `新增更多`,
  addMoreProductsToYourShop: `為您的商店新增更多產品`,
  addNewArt: `新增新藝術品`,
  addSignInVia: `通過新增登入`,
  addToCart: `新增到購物車`,
  advancedOptions: `高級選項`,
  agreedRevisionsWereNotCompleted: `約定的修改未完成`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `禁止使用AI生成的圖片和神經網路濾鏡`,
  all: `全部`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `您在此上傳的所有文件都將對買家可見`,
  allListings: `所有商品`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `所有進行中的文件應在消息中上傳`,
  alreadySignedIn: `已登入`,
  amount: `金額`,
  amountShouldNotBeLessThan: (...v) => `金額不應少於 ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `來自世界各地的藝術家的動漫藝術。策劃藝術與動漫有關。藝術選擇是最佳動漫藝術的無限清單`,
  animeArtSubscribeToArtistsLikeAndCreate: `動漫藝術-訂閱喜歡的藝術家並建立收藏`,
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `Anime.club 使用 ${v[0]}，讓您快速收款，並保障您的個人信息和付款信息安全`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club-查看，發佈動漫內容並從中獲得收益`,
  animeCommunity: `動漫社區`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club從不要求您的私人信息`,
  animeShopBuyAndSellProducts: `動漫商店 - 購買和出售產品`,
  animeSocialNetwork: `動漫社交網路`,
  announcements: `公告`,
  appearance: `外觀`,
  apply: `申請`,
  appSettings: `應用設定`,
  appsVersionIs: `應用的版本為`,
  areYouSureYouWantTo: `你確定你要`,
  art: `藝術`,
  artAssociatedWithAnime: `與動漫相關的藝術`,
  artBy: (...v) => `${v[0]}的藝術品`,
  artCannotBeChanged: `藝術不能改變。`,
  artGallery: `藝術畫廊`,
  artworksAvailableToView: (...v) => `有${v[0]}件藝術品可供查看`,
  attachedFiles: `附件`,
  attentionYourOrderHasBeenDisputed: `注意！您的訂單已被爭議。請檢查詳情`,
  authenticationFailed: `驗證失敗`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `自動發佈到Instagram僅適用於Instagram商業帳戶`,
  awaitingClientReview: `等待客戶審核`,
  awaitingSellersResponse: `等待賣家回復`,
  back: `背部`,
  basePrice: `基礎價格`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `在接受之前，請仔細查看買家的請求`,
  beSpecificAboutTheContent: `請具體說明內容（例如文件數量、格式、畫布分辨率）`,
  beTheFirstToShareYourThoughts: `成為第一個分享想法的人吧`,
  bigAppreciationToTheSellerForTheHardWork: `非常感謝賣家的辛勤付出`,
  block: `封鎖`,
  blockUser: (...v) => `封鎖@${v[0]}`,
  blog: `網誌`,
  bookmarks: `書簽`,
  browseArt: `瀏覽藝術品`,
  browseShop: `瀏覽商店`,
  buyer: `買家`,
  buyerHasNotLeftAReviewYet: `買家尚未留下評價`,
  buyerReviewedTheOrder: `買家已評價訂單`,
  buyersRequest: `買家的請求`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `買家將能看到此商品。您可以隨時再次隱藏`,
  buyNow: `立即購買`,
  cancel: `取消`,
  canceled: `已取消`,
  cancelOrder: `取消訂單`,
  cannotStartWithChars: `無法以{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `更改`,
  changeArt: `改變藝術`,
  changeAvatar: `更改頭像`,
  changedMyMind: `改變主意了`,
  changeEmail: `更改電子郵件`,
  changePassword: `更改密碼`,
  changesSaved: `更改已儲存！`,
  chat: `聊天`,
  checkOrderStatus: `檢查訂單狀態`,
  checkOutMyShop: `查看我的商店`,
  chooseExistingChatOrStartANewOne: `選擇現有的聊天或開始新的聊天`,
  city: `市`,
  clearAll: `全部清除`,
  clickTheButtonBelowToOpenYourStripeDashboard: `點擊下方按鈕打開 Stripe 控制面板並查看帳戶詳情`,
  clickToAddANote: `點擊新增備注`,
  close: `關`,
  color: `顏色`,
  colorTheme: `顏色主題`,
  comingSoon: `快來了…`,
  comments: `評論`,
  commercialUseAllowed: `允許商業用途`,
  commercialUseAllowsBuyersToUseYourProduct: `商業用途允許買家將您的產品用於銷售或推廣等商業目的`,
  commission: `委託`,
  commissions: `委託`,
  community: `社區`,
  completed: `已完成`,
  confirmAccount: `確認帳號`,
  confirmOrder: `確認訂單`,
  confirmPassword: `確認密碼`,
  congratulations: `恭喜！`,
  congratulationsOnSuccessfullyCompletingYourOrder: `恭喜您成功完成訂單！`,
  connectWithUsOn: `在以下社交媒體上關注我們`,
  contactInformation: `聯繫信息`,
  contactSeller: `聯繫賣家`,
  contactSupport: `聯繫支援`,
  contactUs: `聯繫我們`,
  continue: `繼續`,
  contractTitle: `合同標題`,
  copiedToClipboard: `已複製到剪貼板`,
  copy: `複製`,
  copyrightViolation: `版權侵權`,
  couldNotCreateANewRecord: `無法建立新記錄`,
  couldYouPleaseProvideTheReasonForTheCancellation: `請提供取消的原因`,
  country: `國家`,
  cover: `封面`,
  createANewAccountFailed: `建立新帳戶失敗`,
  createAShopWithStripe: `通過Stripe建立商店`,
  createdBy: `建立者`,
  createExtrasForYourProduct: `為您的產品建立額外內容`,
  createNewAccount: `建立新帳戶`,
  createPersonalizedWorkTailoredToEachRequest: `根據每項請求創作個性化作品`,
  currentPassword: `當前密碼`,
  daily: `每日`,
  dark: `深色`,
  decline: `拒絕`,
  delete: `刪除`,
  deleteAccount: `刪除帳戶`,
  deleteArt: `刪除作品`,
  deletePost: `刪除貼文`,
  deleteProduct: `刪除產品`,
  deleteShop: `刪除店鋪`,
  deliveryTime: `交貨時間`,
  describeTheDetailsOfYourExtra: `描述您的額外服務細節`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `說明包含的內容以及買家購買後可以獲得什麼`,
  description: `描述`,
  details: `細節`,
  didntReceiveEmail: `沒有收到郵件嗎？`,
  digitalDownloads: `數字下載`,
  digitalDownloadsExamples: `筆刷、素材、教程等`,
  discard: `放棄`,
  discoverAnimeArtAndArtistsFromAroundTheWorld: `在 Anime.club 探索來自世界各地的動漫藝術和藝術家。關注創作者、支援他們的作品、探索原創藝術，或分享你自己的作品`,
  displayName: `顯示名稱`,
  disputed: `有爭議`,
  documentation: `文檔`,
  donations: `捐贈`,
  done: `完成了`,
  download: `下載`,
  downloadThemBelow: `在下方下載`,
  dragAndDropOrSelectFiles: `拖放或選擇文件`,
  drawingContest: `繪畫比賽`,
  dueDate: `截止日期`,
  earlier: `更早`,
  earningFromArts: `藝術收入`,
  edit: `編輯`,
  editPost: `修改貼文`,
  editProfile: `編輯個人資料`,
  editTranslations: `編輯譯文`,
  email: `電子郵件`,
  emailAlreadyUsedByAnotherAccount: `電子郵件已被另一帳戶使用`,
  emailNotifications: `電子郵件通知`,
  enjoyYourPurchase: `祝您購物愉快！😊`,
  ensureYouveUploadedTheFinalVersion: `請確保您已上傳最終版本再提交`,
  enterOrPasteALink: `輸入或粘貼連結`,
  enterTheAddressAssociatedWithYourAccount: `輸入與您的帳戶關聯的地址，我們將向您發送重置密碼的連結`,
  enterYourPassword: `輸入您的密碼`,
  error: `錯誤`,
  errorPleaseContactCustomerSupport: `錯誤！請聯繫客戶支援...`,
  exitWithoutSaving: `退出而不儲存`,
  extensions: `擴展名`,
  extras: `額外`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `額外服務是可選的附加功能，可提升您的產品`,
  extrasHelpBoostIncome: `附加服務可讓買家定制訂單，也能提高您的收入`,
  feedbackReceived: `已收到意見回饋！`,
  feelFreeToShareReferenceImagesAndMaterials: `歡迎分享參考圖片和資料，幫助藝術家創作您的作品`,
  files: `文件`,
  filesAreCorruptedOrUnusable: `文件已損壞或無法使用`,
  filesForPreview: `預覽文件`,
  filesForTheBuyer: `提供給買家的文件`,
  fileSizeIsTooBig: `檔案太大`,
  fileSizeIsTooSmall: `文件大小太小`,
  filter: `過濾`,
  filterBy: `過濾`,
  findUser: `尋找使用者`,
  finishSettingUpYourShop: `完成商店設定`,
  follow: `跟隨`,
  followers: `追隨者`,
  following: `下列的`,
  followMeOn: `跟我來`,
  follows: `關注`,
  forAllOtherInquiriesPleaseContactUsAt: `任何其他問題，請聯繫我們：`,
  forgotPassword: `忘記密碼`,
  foundAnotherArtist: `找到了其他畫師`,
  fromAnimeDotClub: `來自Anime.club`,
  getDetails: `獲得詳細信息`,
  getStarted: `開始`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `好消息！${v[0]} 購買了您的商品。慶祝一下吧！`,
  greatNewsYourOrderIsNowInProgress: `好消息！您的訂單正在進行中`,
  grid: `網格`,
  guestView: `來賓視圖`,
  harassment: `騷擾`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]}沒有為"${v[1]}"新增描述`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]}尚未分享任何公共詳細信息`,
  hate: `仇恨`,
  haveAnyQuestions: `有任何問題嗎？`,
  hereAreAFewWaysToGetThingsRolling: `以下是一些開始的方法`,
  hide: `隱藏`,
  hideListing: `隱藏商品`,
  hire: `雇傭`,
  homepage: `主頁`,
  howToContactYou: `如何聯繫您`,
  howToFindYouOnOtherSocialNetworks: `如何在其他社交網路上找到您`,
  iAgreeWith: `我同意`,
  id: `賬號`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `如果在 ${v[0]} 前沒有收到回復，您將自動獲得全額退款`,
  ifTheresNoResponseByTimeLimit: (...v) => `如果在 ${v[0]} 之前沒有回應，訂單將自動標記為已完成`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `如果在 ${v[0]} 前沒有回復，訂單將自動取消`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `如有疑問或顧慮，請直接聯繫賣家`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `如果您錯過截止時間，買家可以取消訂單並獲得全額退款，相關 Stripe 費用將從您的收款中扣除。`,
  ifYourArtIsNsfwCheckThisToAvoidAWarningOrBan: `如果您的作品屬於 NSFW，請務必勾選此項。否則您可能會收到警告，甚至導致封禁。`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `圖片高度必須大於或等於`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `圖片寬度必須大於或等於`,
  impersonation: `冒充`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `包括買家可能用於搜尋類似於您產品的關鍵字`,
  includes: `包含`,
  includesXRevisionS: (...v) => `包含${v[0]}次修改`,
  increaseContrast: `增強對比度`,
  inProgress: `進行中`,
  introduction: `介紹`,
  invalidCode: `無效的代碼。`,
  invalidCurrentPassword: `當前密碼無效`,
  invalidDate: `無效日期`,
  invalidPartAfterAt: `@之後的無效部分`,
  invalidPartBeforeAt: `@之前的無效部分`,
  itemReviews: `商品評價`,
  jobDetails: `工作詳情`,
  joinAnimeClubCommunity: `加入Anime.club社區，每天有數千名活躍的創作者和酷炫的動漫藝術品`,
  joinChat: `加入聊天室`,
  joinUsOnFacebook: `加入我們的Facebook`,
  kindlyHoldOnForTheBuyersReview: `請耐心等待買家對訂單的評論。`,
  lackOfInformation: `信息不足`,
  language: `語言`,
  languages: `語言`,
  layout: `佈局`,
  leaveAReview: `留下評論`,
  legal: `法律`,
  legalIntro: `閱讀管理 anime.club 並說明如何處理個人信息的法律文件`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `告知買家您是否提供<b>修改</b>以及可修改的次數`,
  letEveryoneKnowHowToDonateToYou: `讓每個人都知道如何向您捐贈`,
  letOthersKnowAboutYou: `讓其他人瞭解您`,
  letsUploadYourFirstProduct: `讓我們上傳您的第一個產品`,
  letUsKnowWhatsHappening: `讓我們知道發生了什麼，我們會調查一下`,
  light: `淺色`,
  likes: `喜歡`,
  limit: `限制`,
  listAnyContentOrRequestsYouDontAccept: `列出您<b>不接受</b>的內容或請求（例如 NSFW、政治、宗教或冒犯性材料）`,
  listingHiddenFromBuyers: `已對買家隱藏商品`,
  listingIsNowVisibleToBuyers: `商品現已對買家可見`,
  livesIn: `住在`,
  loading: `載入中`,
  location: `位置`,
  logInOrSignUp: `登入或註冊`,
  logOut: `退出登入`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `請確保一切準備就緒——發佈後無法編輯`,
  makeSureToIncludeClearInstructions: `請確保包含每個參考資料的清晰使用說明`,
  makeSureYouFullyUnderstandTheRequirements: `請確保您完全理解需求並能按時完成訂單`,
  makeSureYourProductsArePricedCompetitively: `請確保您的產品定價具有競爭力`,
  masonry: `瀑布流`,
  maximumFileSize: (...v) => `單個文件最大：<b>${v[0]}</b>`,
  maximumNChars: (...v) => `最多${v[0]}個字符`,
  maximumNumberOfDaysToCompleteTheOrder: `完成訂單的最大天數`,
  maximumQuantity: `最大數量`,
  maxSize: `最大尺寸`,
  mentionYourDeliveryTimeInDays: `注明您的<b>交付時間</b>（天數）`,
  menu: `菜單`,
  message: `消息`,
  messageDeleted: `消息已刪除`,
  messages: `私信`,
  minHeight: `最小高度`,
  minimumDimensions: (...v) => `最小尺寸：${v[0]}×${v[1]} 像素`,
  minimumNChars: (...v) => `最少${v[0]}個字符`,
  minorAbuseOrSexualization: `輕微虐待或性化`,
  minWidth: `最小寬度`,
  monthly: `每月`,
  moreFrom: (...v) => `更多`,
  mustBeNChars: (...v) => `必須是${v[0]}個字符`,
  myPayments: `我的付款`,
  myProfile: `我的個人資料`,
  mySettings: `我的設定`,
  need1Lowercase: `需要1個小寫`,
  need1Number: `需要1個號碼`,
  need1Uppercase: `需要1個大寫`,
  needAtLeast1CharacterFromN: (...v) => `需要至少[${v[0]}]個字符`,
  needNCharacter: (...v) => `需要${v[0]}個字符`,
  needsYourReview: `需要您審核`,
  new: `新`,
  newAccount: `新帳戶`,
  newArt: `新藝術`,
  newArtworks: `新藝術品`,
  newBlog: `新網誌`,
  newCommission: `新委託`,
  newOrder: `新訂單`,
  newPassword: `新密碼`,
  newProduct: `新產品`,
  newsFeed: `新聞專線`,
  next: `下一個`,
  nextTimeYouAuthenticateYouCouldUseThe: `下次驗證時，您可以使用連接的帳戶，而不是登入和密碼`,
  no: `沒有`,
  noActiveOrdersToShow: `沒有活動訂單顯示`,
  noCommentsJustYet: `暫時還沒有評論`,
  noInternetConnection: `沒有網路連接！`,
  nonConsensualIntimateContent: `非自願親密內容`,
  none: `無`,
  noNotifications: `沒有通知`,
  noOrders: `暫無訂單`,
  noResults: `沒有結果`,
  noReviewsJustYet: `暫時還沒有評價`,
  noSalesYetNoWorries: `還沒有銷售？別擔心，您才剛剛開始`,
  notAcceptingOrders: `不接受訂單`,
  noteOnlyVisibleToYou: `備注（僅你可見）`,
  notes: `備注`,
  nothingIsChargedUntilTheSellerAccepts: `賣家接受前不會扣款；如果賣家拒接，您不會被收取任何費用`,
  notifications: `通知事項`,
  nsfwContent18Plus: `NSFW內容（18+）`,
  NSFWIndicatesAdultContent: `18+ NSFW表示成人內容。僅當您的產品面向成熟觀眾時勾選此項`,
  numberOfAdjustmentsAClientCouldRequest: `客戶可以請求的調整次數`,
  numFilesIncluded: (...v) => `包含 <b>${v[0]}</b> 個文件`,
  numOfNewComments: (...v) => `${v[0]} 條新評論`,
  numOfNewReactions: (...v) => `${v[0]} 個新回應`,
  numOfReplies: (...v) => `${v[0]} 條回復`,
  numOfReviews: (...v) => `評價：${v[0]} `,
  offerDigitalProducts: `提供買家可立即獲取的數字商品`,
  offerOptionalExtras: `提供可選附加服務，例如<b>加急交付</b>、<b>額外角色</b>或<b>精細背景</b>`,
  online: `在線`,
  onlyLatinLettersNumbersHyphen: `僅限拉丁字母、數字、連字符、下划線和點字符`,
  onlyNumbers: `僅數字`,
  onlyYouCanSeeWhatYouveSaved: `只有您可以看到您儲存的內容`,
  open: `打開`,
  openDispute: `打開爭議`,
  openDisputeChat: `打開爭議聊天`,
  openDisputeGuidance: `請清楚說明訂單存在的問題以及你期望的解決方案。發起爭議後，我們會建立一個包含你、賣家和 anime.club 支援團隊的群聊。雙方都可以在其中提供證據。支援團隊可以查看訂單詳情以及已在訂單中共享的所有文件。`,
  openGuestView: `開啓訪客檢視`,
  openingSoon: `即將開業！`,
  openToWork: `接受工作機會`,
  optional: `可選的`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `您也可以新增描述，分享更多創作信息`,
  or: `要麼`,
  order: `訂單`,
  orderAgain: `再次下單`,
  orderCanceledTheBuyersPaymentWasReleased: `訂單已取消。我們已釋放買家卡上的預授權，銀行可能需要幾天才能顯示`,
  orderCanceledYourPaymentWasReleased: `訂單已取消。我們已釋放你卡上的預授權，銀行可能需要幾天才能顯示`,
  orderCompleted: `訂單已完成 🎉`,
  orderConfirmed: `訂單已確認`,
  orderDetails: `訂單詳情`,
  ordered: (...v) => `已訂購 ${v[0]}`,
  orderedByMistake: `下單失誤`,
  orderOptions: `訂單選項`,
  orderStatus: `訂單狀態`,
  otherOrderIssue: `其他訂單問題`,
  otherReason: `其他原因`,
  outOfStock: `缺貨`,
  pageNotFound: `頁面未找到`,
  password: `密碼`,
  paymentProcessingFee: `付款處理費`,
  payments: `付款方式`,
  payouts: `付款`,
  personal: `個人`,
  personalCircumstances: `個人情況`,
  platform: `平台`,
  platformFee: `平台費`,
  platformPoliciesMayStillApply: `平台政策仍可能適用`,
  pleaseAllowPopups: `請允許彈出式窗口`,
  pleaseCheckYour: (...v) => `請檢查您的${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `請勿向他人分享您的私人信息`,
  pleaseEnterANumberBetweenXandX: (...v) => `請輸入${v[0]}和${v[1]}之間的數字`,
  pleaseEnterAtLeastNChars: (...v) => `請輸入至少${v[0]}個字符`,
  pleaseFillOutYourDetails: `請填寫您的詳細信息`,
  pleaseFixTheErrorsBeforeSubmitting: `請在提交前修正錯誤`,
  pleaseProvideATitleForYourArtwork: `請為您的藝術作品填寫標題`,
  pleaseRateYourOrder: `請為您的訂單評分`,
  pleaseRespondToTheOrderBy: (...v) => `請在${v[0]}前回復訂單`,
  pleaseReviewTheBuyersReferenceFiles: `請查看買家的參考文件，並按訂單描述要求執行`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `請在繼續前仔細查看詳情`,
  pleaseSignInToYourAccount: `請登入到您的帳戶`,
  pleaseStartTyping: `請開始輸入`,
  pleaseSubmitTheOrderBy: (...v) => `請在${v[0]}前提交訂單`,
  pleaseTakeAMomentToReviewTheOrder: `請花點時間審核訂單`,
  pleaseTryAgainOrClick: (...v) => `請重復或者點擊`,
  pleaseUploadOnlyFinishedWorkHere: `請只在此上傳已完成的作品`,
  pleaseVerifyYourAccount: `請驗證您的帳戶`,
  portfolio: `作品集`,
  pressHereTo: `按這裡`,
  price: `價格`,
  privacyPolicy: `隱私政策`,
  privateInformation: `私密`,
  proceedToCheckout: `去結賬`,
  product: `產品`,
  profile: `帳戶`,
  prohibitedTransaction: `禁止的交易`,
  promotions: `促銷`,
  publicInformation: `公開`,
  publishOn: (...v) => `發佈於${v[0]}`,
  purchases: `購買`,
  rankings: `排名`,
  reason: `原因`,
  reorderFiles: `重新排序文件`,
  replies: `回復`,
  reply: `回復`,
  replyToUsername: (...v) => `回復 ${v[0]}`,
  report: `檢舉`,
  requestDetails: `請求詳情`,
  review: `評價`,
  reviewed: `已評價`,
  reviews: `評價`,
  reviewTitle: `評價標題`,
  revisions: `修訂版本`,
  rules: `規則`,
  sales: `銷售額`,
  save: `儲存`,
  saveAvatar: `儲存頭像`,
  saveChanges: `儲存更改`,
  selectAnime: `選擇動漫`,
  selectAppearanceContrastAndColorTheme: `選擇外觀、對比度和顏色主題`,
  selectAvatar: `選擇頭像`,
  selectCharacters: `選擇角色`,
  selectFile: `選擇文件`,
  selectThumbnail: `選擇縮略圖`,
  selfHarmOrSuicide: `自殘或自殺`,
  sellDownloadableContent: `銷售可下載內容`,
  seller: `賣家`,
  sellerHasntResponded: `賣家沒有回應`,
  sellerNet: `賣家實收`,
  sellerTermsOfService: `賣家服務條款`,
  send: `發送`,
  sendEmail: `發電子郵件`,
  settings: `設定值`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `設定商店是免費的，只需幾分鐘`,
  setUpStripeAccountToGetPaidWithAnimeClub: `設定 Stripe 帳戶以通過 Anime.club 收款`,
  share: `分享`,
  sharedFilesAreNotConsideredDelivery: `共享的文件不視為交付`,
  shareYourArt: `分享您的藝術作品`,
  shareYourArtWithTheWorld: `與世界分享您的藝術品`,
  shareYourFavoritePiecesOn: (...v) => `在${v[0]}分享您喜歡的作品`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `分享您的規則和不接受的請求類型`,
  shareYourShopOnSocialMedia: `在社交媒體上分享您的商店`,
  shareYourStory: `分享你的故事！`,
  sharingPersonalInformation: `分享個人信息`,
  shop: `店`,
  shopOrders: `商店訂單`,
  shopReviews: `商店評價`,
  show: `顯示`,
  showLess: `顯示較少`,
  showListing: `顯示商品`,
  showMore: `展示更多`,
  showMyTermsOfService: `查看我的服務條款`,
  showSellerTermsOfService: `查看賣家的服務條款`,
  signIn: `登入`,
  size: `大小`,
  skip: `跳躍`,
  socialMedia: `社交媒體`,
  spaceCharacterIsNotAllowed: `不允許使用空格字符`,
  spam: `垃圾郵件`,
  submitAReport: `提交報告`,
  submitWork: `提交作品`,
  subscribeToTalentsToKeepUpWithTheirProgress: `關注藝術家，追蹤其動態`,
  successChangedPasswordPleaseSignIn: `成功！修改密碼。請登入`,
  successCreatedRecord: `成功！建立記錄！`,
  successfullyDownloaded: `下載成功！`,
  successfullyUploaded: `上傳成功！`,
  supportedFormats: `支援的格式：`,
  supportMeOn: `支援我`,
  system: `系統`,
  takeCustomRequests: `接受定制請求`,
  tapAddToCreateOne: `點擊“新增”進行建立`,
  tax: `稅款`,
  tellTheBuyersWhatTheyWillGet: `明確告訴買家他們將獲得什麼，例如插畫數量、文件格式，或分辨率和 DPI 等畫布規格`,
  tellUsAboutYourself: `向我們介紹你自己`,
  termsAndConditions: `條款和條件`,
  termsOfUse: `使用條款`,
  thankYouForReport: `感謝您幫助維護安全和尊重的在線社區`,
  thankYouForYourPurchase: `感謝您的購買！`,
  thankYouForYourReview: `感謝您的評價！`,
  theBuyerAcceptedThemAtCheckout: `買家在結賬時已接受這些條款`,
  theBuyerCanSeeTheseFilesRightAway: `買家可以立即看到這些文件`,
  theLinkIsBrokenOrPageHasBeenRemoved: `連結已損壞或頁面已刪除`,
  theMaximumQuantityThatACustomerCanAdd: `客戶可以新增的最大數量`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `您提供的訂單取消原因將與買家分享`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheSeller: `你填寫的取消原因將會分享給賣家`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `審查期限制為 ${v[0]} 天`,
  theseAreYourTermsForThisItem: `這是您為此商品設定的條款`,
  theSellerCanSeeTheseFilesRightAway: `賣家可以立即看到這些文件`,
  theSellerConfirmedYourOrderAndIsWorkingOnIt: `賣家已<b>確認</b>您的訂單，正在處理中`,
  theSellerHasUploadedTheseFilesForYou: `賣家已為您上傳這些文件`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `這些規則由賣家提供，僅適用於此商品`,
  thisCannotBeUndone: `此操作無法撤銷`,
  thisFieldIsOptional: `此項為可選`,
  thisIsACustomOrderNotAReadyMadeProduct: `這是定制訂單，不是現成商品。您下單後，賣家才會開始創作`,
  thisIsThePriceYouPropose: `這是您提議的價格`,
  thisListingWontBeVisibleToBuyersAnymore: `買家將無法再看到此商品——您可以隨時重新顯示`,
  threateningViolence: `威脅暴力`,
  timeConstraints: `時間限制`,
  title: `標題`,
  titleYourExtraService: `為您的額外服務命名`,
  today: `今天`,
  toGetWorkRelatedNotifications: `獲取與工作相關的通知`,
  toHelpTheCreatorCompleteYourOrder: `為了幫助創作者完成您的訂單，請提供詳細的描述。包括所需的主題、風格和角色特徵，以及任何其他重要規格`,
  total: `總計`,
  toViewThisDataYouNeedToUnblock: (...v) => `查看此資料，您需要解除對 @${v[0]} 的封鎖`,
  trademarkViolation: `商標侵權`,
  typeYourTextHere: `在此輸入文字...`,
  unblock: `解除封鎖`,
  unblockUser: (...v) => `解除對 @${v[0]} 的封鎖`,
  unfollow: `取消關注`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) => `很遺憾，${v[0]}不得不取消此訂單`,
  unlimited: `無限制`,
  upload: `上傳`,
  uploadedFilesLocked: `這些文件是您建立貼文時上傳的。現已鎖定，但仍顯示在下方`,
  uploadNew: `上載新`,
  uploadNewPost: `上載新訊息`,
  uploadNewProduct: `上傳新產品`,
  uploadTheFilesYourBuyerWillGet: `上傳<b>買家將收到的</b>文件`,
  uploadUpToNumberFiles: (...v) => `最多可上傳 <b>${v[0]}</b> 個文件`,
  username: `使用者名`,
  usernameAlreadyExists: `此使用者名已存在`,
  usernameAndXMoreCommented: (...v) => `<b>${v[0]}</b> 和另外 ${v[1]} 人發表了評論`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b>和${v[1]}個人關注了你`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b>和${v[1]}人有反應`,
  usernameAndXMoreRepliedToYourComment: (...v) => `<b>${v[0]}</b> 和另外 ${v[1]} 人回復了您的評論`,
  usernameCommentedOnYourWork: (...v) => `<b>${v[0]}</b> 評論了您的作品`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> 已取消訂單`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) => `@${v[0]} 尚未在作品集中新增任何內容`,
  usernameHasntListedAnyProductsForSaleYet: (...v) => `@${v[0]} 尚未上架任何商品`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> 已提交作品`,
  usernameLeftAReaction: (...v) => `<b>${v[0]}</b> 留下了回應${v[1] ? ` ${v[1]}` : ``}`,
  usernameRepliedToYourComment: (...v) => `<b>${v[0]}</b> 回復了您的評論`,
  usernameStartedFollowingYou: (...v) => `<b>${v[0]}</b> 開始關注您`,
  useThisEmailTo: `使用此電子郵件進行身份驗證、接收通知`,
  valueIsNotTheSame: `兩次輸入不一致`,
  verificationCode: `驗證碼`,
  verifyCode: `驗證碼`,
  viewDetails: `查看詳情`,
  viewEveryNotificationOfAGroupSeparately: `單獨查看每個組的通知`,
  viewReview: `查看評論`,
  views: `瀏覽量`,
  visitOurDiscordChannelToGetMoreDetails: `訪問我們的discord 頻道以獲取更多詳細信息`,
  visitStripeDashboard: `訪問 Stripe 控制面板`,
  vote: `投票`,
  weAreExcitedToSeeYourProgressKeepItUp: `我們很高興看到您的進步。繼續保持！`,
  weAreOnInstagram: `我們在Instagram上`,
  weAreWorkingOnIt: `我們正在做這件事`,
  weDoNotDisplayNSFWContentYet: `我們尚未顯示NSFW內容`,
  weekly: `每周`,
  weHaveSentTooManyEmails: `我們發送了太多電子郵件，請稍後再試或聯繫客戶支援`,
  welcomeToAnimeClub: `歡迎來到Anime.club！`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `乾得好！作品已成功完成`,
  weSentAnEmailTo: `我們發送了電子郵件至：`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `我們向您發送了一封新的驗證電子郵件。請輸入驗證碼`,
  weSupportOnlyTheFollowingFileExtensions: `我們僅支援以下文件擴展名：`,
  weWouldLoveToHearFromYou: `我們很想聽到您的意見`,
  whatWouldYouLikeToCreate: `您想創作什麼？`,
  whenYouPurchaseSomethingItWillAppearHere: `當您購買某物時，它將出現在這裡`,
  work: `工作`,
  workDescription: `工作描述`,
  workDoesNotMatchRequest: `作品與要求不符`,
  workIsIncompleteOrFilesAreMissing: `作品未完成或文件缺失`,
  workIsNotOriginalOrUsesAI: `作品並非原創或使用了 AI`,
  wrongEmailOrPassword: `電子郵件或密碼錯誤`,
  yes: `是`,
  yesterday: `昨天`,
  youAreAlreadyAuthenticated: `您已經通過驗證`,
  youCanAutoPublishToYourSocialMediaAccount: `您可以自動發佈到您的社交媒體帳戶`,
  youCanceledTheOrder: `您已取消訂單`,
  youCanChooseFromTheListOrEnterACustomReason: `您可以從列表中選擇，也可以輸入自定義原因`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `您可以修改通過電子郵件接收的通知類型`,
  youCanRequestRemovalOfYourAccount: `您可以請求刪除您的帳戶及其所有資料`,
  youCanStillNavigateToThePreviouslyOpenedPages: `您仍然可以導航到以前打開的頁面`,
  youDidNotSelectAnyChats: `您沒有選擇任何聊天`,
  youDidNotUpdateAnyValues: `您沒有更新任何值`,
  youDisputedTheOrder: `爭議已發起。請在消息中查看爭議聊天`,
  youDoNotHaveAnyChats: `您沒有任何聊天`,
  youHaveNoPurchases: `您沒有購買記錄`,
  youHaveNotSetAPassword: `您還沒有設定密碼`,
  youHaveNotSharedAnythingYet: `您還沒有分享任何內容`,
  youHaveReachedTheMaximumNumberOfFiles: `您已達到文件的最大數量`,
  youHaveSuccessfullyCreatedYourShop: `您已成功建立店鋪`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `買家分享體驗後，您將在這裡看到評價`,
  youMustPressSubmitButtonToFinalizeTheOrder: `必須點擊提交按鈕才能完成訂單`,
  yourAccountIsVerifiedPleaseSignIn: `您的帳戶已通過驗證。請登入`,
  yourAccountWillBeRemoved: (...v) => `您的帳戶將在${v[0]}被刪除`,
  yourArts: `您的藝術`,
  yourAvatar: `您的頭像`,
  yourBlog: `您的網誌`,
  youReceivedANewOrderFrom: (...v) => `您收到來自 <b>${v[0]}</b> 的新訂單`,
  youReceivedAReview: `您收到了一條評價`,
  yourFansAreWaiting: `您的粉絲正在等待`,
  yourFavoritesWillShowUpHereAddSome: `您的收藏會顯示在這裡，快去新增吧！`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `您的意見回饋會指導買家並幫助賣家提供更好的產品`,
  yourFeedIsEmpty: `您的專線為空`,
  yourSessionHasExpiredPleaseSignInAgain: `您的會話已過期，請重新登入`,
  yourTermsOfService: `您的服務條款`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `購買後即可立即下載文件，無需等待！`,
  youWillBeAbleToUploadReferenceFilesAfterCheckout: `結賬後即可上傳參考文件`,
}
