export const text: text = {
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `(en) Anime.club uses ${v[0]} to get you paid quickly and keep your personal and payment information secure`,
  files: `(en) Files`,
  prohibitedTransaction: `(en) Prohibited transaction`,
  uploadTheFilesYourBuyerWillGet: `(en) Upload the files your <b>buyer will get</b>`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `(en) Make sure everything is ready to go — no edits after publishing`,
  filesForTheBuyer: `(en) Files for the buyer`,
  filesForPreview: `(en) Files for preview`,
  needsYourReview: `(en) Needs Your Review`,
  awaitingSellerResponse: `(en) Awaiting seller response`,
  buyersRequest: `(en) Buyer's request`,
  awaitingClientReview: `(en) Awaiting Client Review`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `(en) @${v[0]} hasn't listed any products for sale yet`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `(en) @${v[0]} hasn’t added anything to their portfolio yet`,
  hideListing: `(en) Hide listing`,
  uploadUpToNumberFiles: (...v) => `(en) Upload up to <b>${v[0]}</b> files`,
  supportedFormats: `(en) Supported formats:`,
  minimumDimensions: (...v) => `(en) Minimum size: ${v[0]}×${v[1]} pixels`,
  maximumFileSize: (...v) => `(en) Maximum file size: <b>${v[0]}</b> per file`,
  thisListingWontBeVisibleToBuyersAnymore: `(en) This listing won’t be visible to buyers anymore — but you can show it again whenever you’re ready`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `(en) Buyers will be able to see this listing. You can hide it again anytime`,
  listingHiddenFromBuyers: `(en) Listing hidden from buyers`,
  listingIsNowVisibleToBuyers: `(en) Listing is now visible to buyers`,
  showListing: `(en) Show listing`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `(en) These rules are provided by the seller and apply only to this item`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `(en) If you have questions or concerns, please contact the seller directly`,
  platformPoliciesMayStillApply: `(en) Platform policies may still apply`,
  uploadedFilesLocked: `(en) You uploaded these files when you created the post. They're now locked but still visible below`,
  new: `(en) New`,
  createPersonalizedWorkTailoredToEachRequest: `(en) Create personalized work tailored to each request`,
  offerDigitalProducts: `(en) Offer digital products that buyers can access right away`,
  instantDownload: `(en) Instant Download`,
  customWork: `(en) Custom Work`,
  newCommission: `(en) New commission`,
  noOrders: `(en) No orders`,
  tellTheBuyersWhatTheyWillGet: `(en) Tell buyers exactly what they will get — for example, the number of illustrations, file formats, or canvas specs like resolution and DPI`,
  beSpecificAboutTheContent: `(en) Be specific about the content (e.g. number of files, formats, canvas resolution)`,
  mentionYourDeliveryTimeInDays: `(en) Mention your <b>delivery time</b> (in days)`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `(en) Let buyers know if you offer <b>revisions</b>, and how many`,
  listAnyContentOrRequestsYouDontAccept: `(en) List any content or requests you <b>don't accept</b> (e.g. NSFW, political, religious, or offensive material)`,
  offerOptionalExtras: `(en) Offer optional extras like <b>rush delivery</b>, an <b>extra character</b>, or a <b>detailed background</b>`,
  extrasHelpBoostIncome: `(en) Extras help buyers customize their order and can boost your income`,
  artGallery: `(en) Art Gallery`,
  commission: `(en) Commission`,
  digitalStore: `(en) Digital Store`,
  setUpStripeAccountToGetPaidWithAnimeClub: `(en) Set up a Stripe account to get paid with Anime.club`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `(en) Describe what’s included and what the buyer can expect after purchase`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `(en) The reason you provide for cancelling this order will be shared with the buyer`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `(en) Optionally, you can add a description to share more about your creation`,
  pleaseProvideATitleForYourArtwork: `(en) Please provide a title for your artwork`,
  tapAddToCreateOne: `(en) Tap “Add” to create one`,
  youCanChooseFromTheListOrEnterACustomReason: `(en) You can choose from the list or enter a custom reason`,
  _colon: `：`,
  _comma: `、`,
  _dot: `。`,
  _exclamation: `！`,
  _question: `？`,
  _space: ``,
  _hyphen: `—`,
  about: `关于`,
  accept: `接受`,
  acceptOrder: `接受订单`,
  acceptTheOrder: `接受订单`,
  accountManagment: `账户管理`,
  account: `账户`,
  accountDeleted: `账户已删除`,
  animeShopBuyAndSellProducts: `动漫商店 - 购买和出售产品`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `禁止使用AI生成的图片和神经网络滤镜`,
  accountActivation: `帐号激活`,
  accountAlreadyExists: `用户名已经被注册`,
  accountDoesNotExist: `帐号不存在`,
  accountRemoval: `账户删除`,
  add: `加`,
  addArt: `添加艺术品`,
  addBlog: `添加博客`,
  additionalResources: `附加资源`,
  addMoreProductsToYourShop: `为您的商店添加更多产品`,
  addMore: `添加更多`,
  addNewArt: `添加新艺术品`,
  addSignInVia: `通过添加登录`,
  addToCart: `添加到购物车`,
  advancedOptions: `高级选项`,
  all: `全部`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `您在此上传的所有文件都将对买家可见`,
  alreadySignedIn: `已登录`,
  amount: `金额`,
  amountShouldNotBeLessThan: (...v) => `金额不应少于 ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `来自世界各地的艺术家的动漫艺术。策划艺术与动漫有关。艺术选择是最佳动漫艺术的无限清单`,
  animeArtSubscribeToArtistsLikeAndCreate: `动漫艺术-订阅喜欢的艺术家并创建收藏`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club-第一个通过Google AdSense向观看者提供艺术家付款的平台。通过查看艺术家的内容或开始从观看中获得收益来支持艺术家`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club-查看，发布动漫内容并从中获得收益`,
  animeCommunity: `动漫社区`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club从不要求您的私人信息`,
  animeSocialNetwork: `动漫社交网络`,
  announcements: `公告`,
  apply: `申请`,
  appSettings: `应用设置`,
  appsVersionIs: `应用的版本为`,
  areYouSureYouWantTo: `你确定你要`,
  art: `艺术`,
  artAssociatedWithAnime: `与动漫相关的艺术`,
  artBy: (...v) => `${v[0]}的艺术品`,
  artCannotBeChanged: `艺术不能改变。`,
  artworksAvailableToView: (...v) => `有${v[0]}件艺术品可供查看`,
  authenticationFailed: `验证失败`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `自动发布到Instagram仅适用于Instagram商业账户`,
  attentionYourOrderHasBeenDisputed: `注意！您的订单已被争议。请检查详情`,
  back: `背部`,
  basePrice: `基础价格`,
  bigAppreciationToTheSellerForTheHardWork: `非常感谢卖家的辛勤付出`,
  block: `屏蔽`,
  buyerReviewedTheOrder: `买家已评价订单`,
  buyerHasNotLeftAReviewYet: `买家尚未留下评价`,
  feedbackReceived: `已收到反馈！`,
  blockUser: (...v) => `屏蔽@${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `在接受之前，请仔细查看买家的请求`,
  blog: `博客`,
  bookmarks: `书签`,
  browseArt: `浏览艺术品`,
  browseShop: `浏览商店`,
  buyer: `买家`,
  cancel: `取消`,
  canceled: `已取消`,
  cancelOrder: `取消订单`,
  cannotStartWithChars: `无法以{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `更改`,
  checkOutMyShop: `查看我的商店`,
  checkOrderStatus: `检查订单状态`,
  changeArt: `改变艺术`,
  changeAvatar: `更改头像`,
  changeEmail: `更改电子邮件`,
  changePassword: `更改密码`,
  chooseExistingChatOrStartANewOne: `选择现有的聊天或开始新的聊天`,
  city: `市`,
  clearAll: `全部清除`,
  close: `关`,
  colorTheme: `颜色主题`,
  comingSoon: `快来了…`,
  commercialUseAllowed: `允许商业用途`,
  commercialUseAllowsBuyersToUseYourProduct: `商业用途允许买家将您的产品用于销售或推广等商业目的`,
  community: `社区`,
  completed: `已完成`,
  confirmAccount: `确认帐号`,
  confirmOrder: `确认订单`,
  confirmPassword: `确认密码`,
  connectWithUsOn: `在以下社交媒体上关注我们`,
  contactInformation: `联系信息`,
  contactSeller: `联系卖家`,
  contactSupport: `联系支持`,
  contactUs: `联系我们`,
  continue: `继续`,
  contractTitle: `合同标题`,
  copyLink: `复制链接`,
  congratulations: `恭喜！`,
  congratulationsOnSuccessfullyCompletingYourOrder: `恭喜您成功完成订单！`,
  copyrightViolation: `版权侵权`,
  couldNotCreateANewRecord: `无法创建新记录`,
  country: `国家`,
  cover: `封面`,
  createANewAccountFailed: `创建新帐户失败`,
  createExtrasForYourProduct: `为您的产品创建额外内容`,
  createNewAccount: `建立新帐户`,
  createAShopWithStripe: `通过Stripe创建商店`,
  createdBy: `创建者`,
  currentPassword: `当前密码`,
  daily: `每日`,
  darkDefault: `暗色默认`,
  darkHighContrast: `暗色高对比度`,
  dayTheme: `日间主题`,
  delete: `删除`,
  deleteShop: `删除店铺`,
  deleteAccount: `删除账户`,
  deleteArt: `删除作品`,
  decline: `拒绝`,
  deletePost: `删除贴文`,
  deleteProduct: `删除产品`,
  download: `下载`,
  downloadThemBelow: `在下方下载`,
  deliveryTime: `交货时间`,
  describeTheDetailsOfYourExtra: `描述您的额外服务细节`,
  description: `描述`,
  details: `细节`,
  didntReceiveEmail: `没有收到邮件吗？`,
  displayName: `显示名称`,
  disputed: `有争议`,
  donations: `捐赠`,
  done: `完成了`,
  dragAndDropOrSelectFiles: `拖放或选择文件`,
  drawingContest: `绘画比赛`,
  dueDate: `截止日期`,
  earlier: `更早`,
  earningFromArts: `艺术收入`,
  edit: `编辑`,
  editPost: `修改帖子`,
  editProfile: `编辑个人资料`,
  editTranslations: `编辑译文`,
  email: `电子邮件`,
  emailAlreadyUsedByAnotherAccount: `电子邮件已被另一账户使用`,
  emailNotifications: `电子邮件通知`,
  enterOrPasteALink: `输入或粘贴链接`,
  enjoyYourPurchase: `祝您购物愉快！😊`,
  enterTheAddressAssociatedWithYourAccount: `输入与您的帐户关联的地址，我们将向您发送重置密码的链接`,
  enterYourPassword: `输入您的密码`,
  error: `错误`,
  errorPleaseContactCustomerSupport: `错误！请联系客户支持...`,
  exitWithoutSaving: `退出而不保存`,
  extensions: `扩展名`,
  extras: `额外`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `额外服务是可选的附加功能，可提升您的产品`,
  fileSizeIsTooBig: `档案太大`,
  fileSizeIsTooSmall: `文件大小太小`,
  filter: `过滤`,
  filterBy: `过滤`,
  findUser: `寻找使用者`,
  finishSettingUpYourShop: `完成商店设置`,
  follow: `跟随`,
  followers: `追随者`,
  following: `下列的`,
  followMeOn: `跟我来`,
  follows: `关注`,
  forAllOtherInquiriesPleaseContactUsAt: `任何其他问题，请联系我们：`,
  forgotPassword: `忘记密码`,
  fromAnimeDotClub: `来自Anime.club`,
  getDetails: `获得详细信息`,
  getStarted: `开始`,
  guestView: `来宾视图`,
  greatNewsYourOrderIsNowInProgress: `好消息！您的订单正在进行中`,
  harassment: `骚扰`,
  haveAnyQuestions: `有任何问题吗？`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> 已取消订单`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> 已提交作品`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]}没有为"${v[1]}"添加描述`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]}尚未分享任何公共详细信息`,
  hate: `仇恨`,
  hereAreAFewWaysToGetThingsRolling: `以下是一些开始的方法`,
  hire: `雇佣`,
  homepage: `主页`,
  howToContactYou: `如何联系您`,
  howToFindYouOnOtherSocialNetworks: `如何在其他社交网络上找到您`,
  iAgreeWith: `我同意`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `如果在 ${v[0]} 之前没有回应，订单将自动标记为已完成`,
  id: `账号`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `图片高度必须大于或等于`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `图片宽度必须大于或等于`,
  impersonation: `冒充`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `包括买家可能用于搜索类似于您产品的关键字`,
  inProgress: `进行中`,
  introduction: `介绍`,
  includes: `包含`,
  invalidCode: `无效的代码。`,
  invalidCurrentPassword: `当前密码无效`,
  invalidDate: `无效日期`,
  invalidPartAfterAt: `@之后的无效部分`,
  invalidPartBeforeAt: `@之前的无效部分`,
  jobDetails: `工作详情`,
  joinAnimeClubCommunity: `加入Anime.club社区，每天有数千名活跃的创作者和酷炫的动漫艺术品`,
  joinChat: `加入聊天室`,
  joinUsOnFacebook: `加入我们的Facebook`,
  language: `语言`,
  lackOfInformation: `信息不足`,
  languages: `语言`,
  letEveryoneKnowHowToDonateToYou: `让每个人都知道如何向您捐赠`,
  letOthersKnowAboutYou: `让其他人了解您`,
  letsUploadYourFirstProduct: `让我们上传您的第一个产品`,
  letUsKnowWhatsHappening: `让我们知道发生了什么，我们会调查一下`,
  lightDefault: `浅色默认`,
  lightHighContrast: `浅色高对比度`,
  likes: `喜欢`,
  limit: `限制`,
  linkCopiedToClipboard: `链接已复制到剪贴板`,
  livesIn: `住在`,
  loading: `加载中`,
  location: `位置`,
  logInOrSignUp: `登录或注册`,
  logOut: `退出登录`,
  maximumNChars: (...v) => `最多${v[0]}个字符`,
  maximumNumberOfDaysToCompleteTheOrder: `完成订单的最大天数`,
  maximumQuantity: `最大数量`,
  maxSize: `最大尺寸`,
  menu: `菜单`,
  message: `消息`,
  messages: `私信`,
  minHeight: `最小高度`,
  minimumNChars: (...v) => `最少${v[0]}个字符`,
  minorAbuseOrSexualization: `轻微虐待或性化`,
  makeSureToIncludeClearInstructions: `请确保包含每个参考资料的清晰使用说明`,
  makeSureYouFullyUnderstandTheRequirements: `请确保您完全理解需求并能按时完成订单`,
  makeSureYourProductsArePricedCompetitively: `请确保您的产品定价具有竞争力`,
  minWidth: `最小宽度`,
  monthly: `每月`,
  moreFrom: (...v) => `更多`,
  mustBeNChars: (...v) => `必须是${v[0]}个字符`,
  myPayments: `我的付款`,
  myProfile: `我的个人资料`,
  mySettings: `我的设置`,
  need1Lowercase: `需要1个小写`,
  need1Number: `需要1个号码`,
  need1Uppercase: `需要1个大写`,
  needAtLeast1CharacterFromN: (...v) => `需要至少[${v[0]}]个字符`,
  needNCharacter: (...v) => `需要${v[0]}个字符`,
  newAccount: `新账户`,
  newArt: `新艺术`,
  newArtworks: `新艺术品`,
  newBlog: `新博客`,
  newOrder: `新订单`,
  newPassword: `新密码`,
  newProduct: `新产品`,
  newProducts: `新产品`,
  newsFeed: `新闻专线`,
  next: `下一个`,
  nextTimeYouAuthenticateYouCouldUseThe: `下次验证时，您可以使用连接的帐户，而不是登录和密码`,
  nightTheme: `夜间主题`,
  no: `没有`,
  noInternetConnection: `没有网络连接！`,
  nonConsensualIntimateContent: `非自愿亲密内容`,
  none: `无`,
  noNotifications: `没有通知`,
  noResults: `没有结果`,
  noReviewsJustYet: `暂时还没有评价`,
  notifications: `通知事项`,
  noActiveOrdersToShow: `没有活动订单显示`,
  notAcceptingOrders: `不接受订单`,
  noSalesYetNoWorries: `还没有销售？别担心，您才刚刚开始`,
  nsfwContent18Plus: `NSFW内容（18+）`,
  NSFWIndicatesAdultContent: `18+ NSFW表示成人内容。仅当您的产品面向成熟观众时勾选此项`,
  numberOfAdjustmentsAClientCouldRequest: `客户可以请求的调整次数`,
  online: `在线`,
  onlyLatinLettersNumbersHyphen: `仅限拉丁字母、数字、连字符、下划线和点字符`,
  onlyNumbers: `仅数字`,
  onlyYouCanSeeWhatYouveSaved: `只有您可以看到您保存的内容`,
  open: `打开`,
  openDispute: `打开争议`,
  openGuestView: `开启访客检视`,
  openingSoon: `即将开业！`,
  openToWork: `接受工作机会`,
  optional: `可选的`,
  requestDetails: `请求详情`,
  or: `要么`,
  order: `订单`,
  outOfStock: `缺货`,
  ordered: (...v) => `已订购 ${v[0]}`,
  orderAgain: `再次下单`,
  orderDetails: `订单详情`,
  orderConfirmed: `订单已确认`,
  orderCompleted: `订单已完成 🎉`,
  orderStatus: `订单状态`,
  orderOptions: `订单选项`,
  otherReason: `其他原因`,
  pageNotFound: `页面未找到`,
  password: `密码`,
  payments: `付款方式`,
  personal: `个人`,
  personalCircumstances: `个人情况`,
  pleaseCheckYour: (...v) => `请检查您的${v[0]}`,
  pleaseRateYourOrder: `请为您的订单评分`,
  feelFreeToShareReferenceImagesAndMaterials: `欢迎分享参考图片和资料，帮助艺术家创作您的作品`,
  pleaseDoNotShareYourPrivateInformationToOthers: `请勿向他人分享您的私人信息`,
  pleaseEnterANumberBetweenXandX: (...v) => `请输入${v[0]}和${v[1]}之间的数字`,
  pleaseEnterAtLeastNChars: (...v) => `请输入至少${v[0]}个字符`,
  pleaseFillOutYourDetails: `请填写您的详细信息`,
  pleaseFixTheErrorsBeforeSubmitting: `请在提交前修正错误`,
  pleaseSignInToYourAccount: `请登录到您的帐户`,
  platform: `平台`,
  pleaseStartTyping: `请开始输入`,
  pleaseTakeAMomentToReviewTheOrder: `请花点时间审核订单`,
  pleaseReviewTheBuyersReferenceFiles: `请查看买家的参考文件，并按订单描述要求执行`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `请在继续前仔细查看详情`,
  pleaseRespondToTheOrderBy: (...v) => `请在${v[0]}前回复订单`,
  pleaseTryAgainOrClick: (...v) => `请重复或者点击`,
  pleaseVerifyYourAccount: `请验证您的帐户`,
  pressHereTo: `按这里`,
  price: `价格`,
  payouts: `付款`,
  privacyPolicy: `隐私政策`,
  privateInformation: `私人信息`,
  proceedToCheckout: `去结账`,
  product: `产品`,
  itemReviews: `商品评价`,
  portfolio: `作品集`,
  profile: `账户`,
  promotions: `促销`,
  publicInformation: `公共信息`,
  publishOn: (...v) => `发布于${v[0]}`,
  purchases: `购买`,
  rankings: `排名`,
  reorderFiles: `重新排序文件`,
  report: `举报`,
  review: `评价`,
  rules: `规则`,
  reviews: `评价`,
  numOfReviews: (...v) => `评价：${v[0]} `,
  reviewed: `已评价`,
  reviewTitle: `评价标题`,
  reason: `原因`,
  revisions: `修订版本`,
  includesXRevisionS: (...v) => `包含${v[0]}次修改`,
  sales: `销售额`,
  save: `保存`,
  saveAvatar: `保存头像`,
  saveChanges: `保存更改`,
  selectAnime: `选择动漫`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `选择单个主题或与您的系统同步，并在白天和黑夜主题之间自动切换`,
  selectAvatar: `选择头像`,
  selectCharacters: `选择角色`,
  seller: `卖家`,
  selectFile: `选择文件`,
  selectTheme: `选择主题`,
  selectThumbnail: `选择缩略图`,
  selfHarmOrSuicide: `自残或自杀`,
  sendEmail: `发电子邮件`,
  settings: `设定值`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `设置商店是免费的，只需几分钟`,
  share: `分享`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `分享您的规则和不接受的请求类型`,
  shareYourShopOnSocialMedia: `在社交媒体上分享您的商店`,
  shareYourFavoritePiecesOn: (...v) => `在${v[0]}分享您喜欢的作品`,
  shareYourArtWithTheWorld: `与世界分享您的艺术品`,
  shareYourStory: `分享你的故事！`,
  sharingPersonalInformation: `分享个人信息`,
  shop: `店`,
  shopReviews: `商店评价`,
  shopOrders: `商店订单`,
  showLess: `显示较少`,
  showMore: `展示更多`,
  signIn: `登入`,
  singleTheme: `单个主题`,
  size: `大小`,
  skip: `跳跃`,
  socialMedia: `社交媒体`,
  spaceCharacterIsNotAllowed: `不允许使用空格字符`,
  spam: `垃圾邮件`,
  yourFavoritesWillShowUpHereAddSome: `您的收藏会显示在这里，快去添加吧！`,
  submitAReport: `提交报告`,
  submitWork: `提交作品`,
  subscribeToTalentsToKeepUpWithTheirProgress: `关注艺术家，追踪其动态`,
  successChangedPasswordPleaseSignIn: `成功！修改密码。请登录`,
  successCreatedRecord: `成功！创建记录！`,
  successUpdatedRecord: `成功！更新记录！`,
  successfullyDownloaded: `下载成功！`,
  successfullyUploaded: `上传成功！`,
  supportMeOn: `支持我`,
  syncWithSystem: `与系统同步`,
  tellUsAboutYourself: `向我们介绍你自己`,
  termsAndConditions: `条款和条件`,
  termsOfUse: `使用条款`,
  thankYouForReport: `感谢您帮助维护安全和尊重的在线社区`,
  thankYouForYourReview: `感谢您的评价！`,
  thankForYourSupport: `感谢您的支持！`,
  theLinkIsBrokenOrPageHasBeenRemoved: `链接已损坏或页面已删除`,
  themeMode: `主题模式`,
  thisIsThePriceYouPropose: `这是您提议的价格`,
  thisFieldIsOptional: `此项为可选`,
  thisCannotBeUndone: `此操作无法撤销`,
  ensureYouveUploadedTheFinalVersion: `请确保您已上传最终版本再提交`,
  threateningViolence: `威胁暴力`,
  title: `标题`,
  timeConstraints: `时间限制`,
  titleYourExtraService: `为您的额外服务命名`,
  theMaximumQuantityThatACustomerCanAdd: `客户可以添加的最大数量`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `审查期限制为 ${v[0]} 天`,
  toHelpTheCreatorCompleteYourOrder: `为了帮助创作者完成您的订单，请提供详细的描述。包括所需的主题、风格和角色特征，以及任何其他重要规格`,
  today: `今天`,
  toGetWorkRelatedNotifications: `获取与工作相关的通知`,
  total: `总计`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `查看此数据，您需要解除对 @${v[0]} 的屏蔽`,
  trademarkViolation: `商标侵权`,
  typeYourTextHere: `在此输入文字...`,
  theSellerHasUploadedTheseFilesForYou: `卖家已为您上传这些文件`,
  unblock: `解除屏蔽`,
  unblockUser: (...v) => `解除对 @${v[0]} 的屏蔽`,
  unfollow: `取消关注`,
  unlimited: `无限制`,
  upload: `上传`,
  uploadNew: `上载新`,
  uploadNewPost: `上载新讯息`,
  uploadNewProduct: `上传新产品`,
  username: `用户名`,
  pleaseUploadOnlyFinishedWorkHere: `请只在此上传已完成的作品`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `所有进行中的文件应在消息中上传`,
  usernameAlreadyExists: `此用户名已存在`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b>和${v[1]}个人关注了你`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b>和${v[1]}人有反应`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b>关注了你`,
  usernameReacted: (...v) => `<b>${v[0]}</b>有反应`,
  useThisEmailTo: `使用此电子邮件进行身份验证、接收通知`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `很遗憾，${v[0]}不得不取消此订单`,
  valueIsNotTheSame: `两次输入不一致`,
  verificationCode: `验证码`,
  verifyCode: `验证码`,
  viewDetails: `查看详情`,
  viewReview: `查看评论`,
  viewEveryNotificationOfAGroupSeparately: `单独查看每个组的通知`,
  visitOurDiscordChannelToGetMoreDetails: `访问我们的discord 频道以获取更多详细信息`,
  weAreOnInstagram: `我们在Instagram上`,
  weAreWorkingOnIt: `我们正在做这件事`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `干得好！作品已成功完成`,
  weDoNotDisplayNSFWContentYet: `我们尚未显示NSFW内容`,
  weekly: `每周`,
  whenYouPurchaseSomethingItWillAppearHere: `当您购买某物时，它将出现在这里`,
  weHaveSentTooManyEmails: `我们发送了太多电子邮件，请稍后再试或联系客户支持`,
  welcomeToAnimeClub: `欢迎来到Anime.club！`,
  weSentAnEmailTo: `我们发送了电子邮件至：`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `我们向您发送了一封新的验证电子邮件。请输入验证码`,
  weAreExcitedToSeeYourProgressKeepItUp: `我们很高兴看到您的进步。继续保持！`,
  weSupportOnlyTheFollowingFileExtensions: `我们仅支持以下文件扩展名：`,
  work: `工作`,
  weWouldLoveToHearFromYou: `我们很想听到您的意见`,
  workDescription: `工作描述`,
  leaveAReview: `留下评论`,
  wrongEmailOrPassword: `邮箱或密码错误`,
  yes: `是`,
  yesterday: `昨天`,
  youReceivedANewOrderFrom: (...v) => `您收到来自 <b>${v[0]}</b> 的新订单`,
  youReceivedAReview: `您收到了一条评价`,
  youHaveSuccessfullyCreatedYourShop: `您已成功创建店铺`,
  youAreAlreadyAuthenticated: `您已经通过验证`,
  youCanAutoPublishToYourSocialMediaAccount: `您可以自动发布到您的社交媒体帐户`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `您可以修改通过电子邮件接收的通知类型`,
  youCanRequestRemovalOfYourAccount: `您可以请求删除您的帐户及其所有数据`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `您的反馈会指导买家并帮助卖家提供更好的产品`,
  youCanStillNavigateToThePreviouslyOpenedPages: `您仍然可以导航到以前打开的页面`,
  youDidNotSelectAnyChats: `您没有选择任何聊天`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `买家分享体验后，您将在这里看到评价`,
  youDidNotUpdateAnyValues: `您没有更新任何值`,
  youDoNotHaveAnyChats: `您没有任何聊天`,
  youHaveNotSetAPassword: `您还没有设置密码`,
  youHaveNotSharedAnythingYet: `您还没有分享任何内容`,
  youHaveReachedTheMaximumNumberOfFiles: `您已达到文件的最大数量`,
  kindlyHoldOnForTheBuyersReview: `请耐心等待买家对订单的评论。`,
  yourAccountIsVerifiedPleaseSignIn: `您的帐户已通过验证。请登录`,
  yourAccountWillBeRemoved: (...v) => `您的帐户将在${v[0]}被删除`,
  youHaveNoPurchases: `您没有购买记录`,
  couldYouPleaseProvideTheReasonForTheCancellation: `请提供取消的原因`,
  yourArts: `您的艺术`,
  youCanceledTheOrder: `您已取消订单`,
  yourAvatar: `您的头像`,
  yourBlog: `您的博客`,
  yourFansAreWaiting: `您的粉丝正在等待`,
  yourFeedIsEmpty: `您的专线为空`,
  yourSessionHasExpiredPleaseSignInAgain: `您的会话已过期，请重新登录`,
}
