import { text as traditional } from "./chinese-traditional"
import { regionalize } from "./chinese-traditional-regionalize"

const regional = regionalize(traditional, [
  [`文件`, `檔案`],
  [`消息`, `訊息`],
  [`在線`, `線上`],
  [`應用`, `應用程式`],
  [`上載`, `上傳`],
  [`聯繫`, `聯絡`],
  [`結賬`, `結帳`],
  [`分辨率`, `解析度`],
  [`定制`, `客製`],
  [`擴展名`, `副檔名`],
  [`回復`, `回覆`],
] as const)

/** Traditional Chinese for Taiwan, composed from the shared Hant pack with Taiwan terminology. */
export const text: text = {
  ...regional,
  accountActivation: `帳號啟用`,
  accountAlreadyExists: `帳號已存在`,
  advancedOptions: `進階選項`,
  animeSocialNetwork: `動漫\n社群網路`,
  appSettings: `應用程式設定`,
  appsVersionIs: `應用程式版本為`,
  back: `返回`,
  cannotStartWithChars: `不能以下列字元開頭：{:"^$*[]{}()?-"!@#%&/\\,><':;|~\``,
  close: `關閉`,
  currentPassword: `目前密碼`,
  digitalDownloads: `數位下載`,
  enterOrPasteALink: `輸入或貼上連結`,
  filter: `篩選`,
  filterBy: `篩選依據`,
  follow: `追蹤`,
  following: `正在追蹤`,
  followMeOn: `在以下平台追蹤我`,
  guestView: `訪客檢視`,
  id: `ID`,
  invalidCurrentPassword: `目前密碼無效`,
  messages: `訊息`,
  minorAbuseOrSexualization: `兒少虐待或性化`,
  moreFrom: (username: string) => `更多來自 ${username} 的作品`,
  needAtLeast1CharacterFromN: (characters: string) => `至少需要一個 [${characters}] 中的字元`,
  needNCharacter: (character: string) => `需要字元 ${character}`,
  newsFeed: `動態消息`,
  no: `否`,
  notes: `備註`,
  offerDigitalProducts: `提供買家可立即取得的數位商品`,
  openDispute: `提出爭議`,
  openDisputeChat: `開啟爭議聊天室`,
  or: `或`,
  paymentProcessingFee: `付款處理費`,
  payouts: `撥款`,
  platformFee: `平台費`,
  pleaseTryAgainOrClick: (buttonName: string) => `請再試一次，或按一下 ${buttonName}`,
  proceedToCheckout: `前往結帳`,
  profile: `個人檔案`,
  sellerNet: `賣家實收`,
  settings: `設定`,
  skip: `略過`,
  tax: `稅金`,
  theReviewPeriodIsLimitedtoNdays: (numOfDays: number | string) =>
    `審核期為 <b>${numOfDays}</b> 天`,
  uploadNewPost: `上傳新貼文`,
  username: `使用者名稱`,
  usernameAlreadyExists: `此使用者名稱已存在`,
  verifyCode: `驗證`,
  weekly: `每週`,
  yourFeedIsEmpty: `您的動態消息目前沒有內容`,
}
