export const text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _hyphen: `- `,
  _question: `? `,
  _space: ` `,
  about: `About`,
  accept: `Accept`,
  acceptOrder: `Accept order`,
  acceptTheOrder: `Accept the order`,
  account: `Account`,
  accountActivation: `Account activation`,
  accountAlreadyExists: `Account already exists`,
  accountDeleted: `Account deleted`,
  accountDoesNotExist: `Account does not exist`,
  accountManagment: `Account management`,
  accountRemoval: `Account removal`,
  add: `Add`,
  addAComment: `Add a comment`,
  addArt: `Add art`,
  addBlog: `Add blog`,
  additionalResources: `Additional resources`,
  addMore: `Add more`,
  addMoreProductsToYourShop: `Add more products to your shop`,
  addNewArt: `Add new art`,
  addSignInVia: `Add sign in via`,
  addToCart: `Add to cart`,
  advancedOptions: `Advanced options`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `AI-generated images and neural network filters are prohibited`,
  all: `All`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `All files you upload here will be available to the buyer`,
  allListings: `All Listings`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `All WIP-related files should be uploaded in messages`,
  alreadySignedIn: `Already signed in`,
  amount: `Amount`,
  amountShouldNotBeLessThan: (amount: number) => `Amount should not be less than ${amount}`,
  animeArtByArtistsFromAllOverTheWorld: `Anime art by artists from all over the world. Art is curated to be related to anime. The art selection is an infinite list of best anime art`,
  animeArtSubscribeToArtistsLikeAndCreate: `Anime art - subscribe to artists, like, and create collections`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - the first platform to offer artists payments from views via Google AdSense. Support artists by viewing their content or start earning from views`,
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (providerName: string) =>
    `Anime.club uses ${providerName} to get you paid quickly and keep your personal and payment information secure`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - view, post, and earn from anime content`,
  animeCommunity: `Anime community`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club never asks for your private information`,
  animeShopBuyAndSellProducts: `Anime shop - buy and sell products`,
  animeSocialNetwork: `Anime\nSocial Network`,
  announcements: `Announcements`,
  appearance: `Appearance`,
  apply: `Apply`,
  appSettings: `App settings`,
  appsVersionIs: `App's version is`,
  areYouSureYouWantTo: `Are you sure you want to`,
  art: `Art`,
  artAssociatedWithAnime: `Art associated with anime`,
  artBy: (username: string) => `Art by ${username}`,
  artCannotBeChanged: `Art cannot be changed`,
  artGallery: `Art Gallery`,
  artworksAvailableToView: (num: number) => `${num} artworks available to view`,
  attachedFiles: `Attached files`,
  attentionYourOrderHasBeenDisputed: `Attention! Your order has been disputed. Please check the details`,
  authenticationFailed: `Authentication failed`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Auto publishing to Instagram is only available to Instagram business accounts`,
  awaitingClientReview: `Awaiting Client Review`,
  awaitingSellersResponse: `Awaiting seller's response`,
  back: `Back`,
  basePrice: `Base Price`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `Before accepting, please review the buyer's request carefully`,
  beSpecificAboutTheContent: `Be specific about the content (e.g. number of files, formats, canvas resolution)`,
  beTheFirstToShareYourThoughts: `Be the first to share your thoughts`,
  bigAppreciationToTheSellerForTheHardWork: `Big appreciation to the seller for the hard work`,
  block: `Block`,
  blockUser: (username: string) => `Block @${username}`,
  blog: `Blog`,
  bookmarks: `Bookmarks`,
  browseArt: `Browse art`,
  browseShop: `Browse shop`,
  buyer: `Buyer`,
  buyerHasNotLeftAReviewYet: `Buyer has not left a review yet`,
  buyerReviewedTheOrder: `Buyer reviewed the order`,
  buyersRequest: `Buyer's request`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `Buyers will be able to see this listing. You can hide it again anytime`,
  buyNow: `Buy now`,
  cancel: `Cancel`,
  canceled: `Canceled`,
  cancelOrder: `Cancel order`,
  cannotStartWithChars: `Cannot start with {:"^$*[]{}()?-"!@#%&/\\,><':;|~\`"`,
  change: `Change`,
  changeArt: `Change art`,
  changeAvatar: `Change avatar`,
  changedMyMind: `Changed my mind`,
  changeEmail: `Change email`,
  changePassword: `Change password`,
  changesSaved: `Changes saved!`,
  checkOrderStatus: `Check order status`,
  checkOutMyShop: `Check out my shop`,
  chooseExistingChatOrStartANewOne: `Choose existing chat or start a new one`,
  city: `City`,
  clearAll: `Clear all`,
  clickTheButtonBelowToOpenYourStripeDashboard: `Click the button below to open your Stripe dashboard and view your account details`,
  close: `Close`,
  color: `Color`,
  colorTheme: `Color theme`,
  comingSoon: `Coming soon…`,
  comments: `Comments`,
  commercialUseAllowed: `Commercial use allowed`,
  commercialUseAllowsBuyersToUseYourProduct: `Commercial use allows buyers to use your product for business purposes, like selling or promoting their services`,
  commission: `Commission`,
  commissions: `Commissions`,
  community: `Community`,
  completed: `Completed`,
  confirmAccount: `Confirm account`,
  confirmOrder: `Confirm order`,
  confirmPassword: `Confirm password`,
  congratulations: `Congratulations!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `Congratulations on successfully completing your order!`,
  connectWithUsOn: `Connect with us on`,
  contactInformation: `Contact information`,
  contactSeller: `Contact seller`,
  contactSupport: `Contact support`,
  contactUs: `Contact us`,
  continue: `Continue`,
  contractTitle: `Contract Title`,
  copiedToClipboard: `Copied to clipboard`,
  copy: `Copy`,
  copyrightViolation: `Copyright violation`,
  couldNotCreateANewRecord: `Could not create a new record`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Could you please provide the reason for the cancellation`,
  country: `Country`,
  cover: `Cover`,
  createANewAccountFailed: `Create a new account failed`,
  createAShopWithStripe: `Create a shop with Stripe`,
  createdBy: `Created by`,
  createExtrasForYourProduct: `Create extras for your product`,
  createNewAccount: `Create new account`,
  createPersonalizedWorkTailoredToEachRequest: `Create personalized work tailored to each request`,
  currentPassword: `Current password`,
  customWork: `Custom Work`,
  daily: `Daily`,
  dark: `Dark`,
  decline: `Decline`,
  delete: `Delete`,
  deleteAccount: `Delete account`,
  deleteArt: `Delete art`,
  deletePost: `Delete post`,
  deleteProduct: `Delete product`,
  deleteShop: `Delete shop`,
  deliveryTime: `Delivery time`,
  describeTheDetailsOfYourExtra: `Describe the details of your extra`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `Describe what’s included and what the buyer can expect after purchase`,
  description: `Description`,
  details: `Details`,
  didntReceiveEmail: `Didn't receive email?`,
  digitalDownloads: `Digital Downloads`,
  digitalDownloadsExamples: `Brushes, assets, tutorials & more`,
  displayName: `Display name`,
  disputed: `Disputed`,
  documentation: `Documentation`,
  donations: `Donations`,
  done: `Done`,
  download: `Dowload`,
  downloadThemBelow: `Download them below`,
  dragAndDropOrSelectFiles: `Drag & Drop or Select file(s)`,
  drawingContest: `Drawing contest`,
  dueDate: `Due date`,
  earlier: `Earlier`,
  earningFromArts: `Earning from arts`,
  edit: `Edit`,
  editPost: `Edit post`,
  editProfile: `Edit profile`,
  editTranslations: `Edit translations`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email already used by another account`,
  emailNotifications: `Email Notifications`,
  enjoyYourPurchase: `Enjoy your purchase! 😊`,
  ensureYouveUploadedTheFinalVersion: ` Ensure you've uploaded the final version before submitting`,
  enterOrPasteALink: `Enter or paste a link`,
  enterTheAddressAssociatedWithYourAccount: `Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `Enter your password`,
  error: `Error`,
  errorPleaseContactCustomerSupport: `Error! Please contact customer support...`,
  exitWithoutSaving: `Exit without saving`,
  extensions: `Extensions`,
  extras: `Extras`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `Extras are optional add-ons to enhance your product`,
  extrasHelpBoostIncome: `Extras help buyers customize their order and can boost your income`,
  feedbackReceived: `Feedback received!`,
  feelFreeToShareReferenceImagesAndMaterials: `Feel free to share reference images and materials to help the artist create your piece`,
  files: `Files`,
  filesForPreview: `Files for preview`,
  filesForTheBuyer: `Files for the buyer`,
  fileSizeIsTooBig: `File size is too big`,
  fileSizeIsTooSmall: `File size is too small`,
  filter: `Filter`,
  filterBy: `Filter by`,
  findUser: `Find user`,
  finishSettingUpYourShop: `Finish setting up your shop`,
  follow: `Follow`,
  followers: `Followers`,
  following: `Following`,
  followMeOn: `Follow me on`,
  follows: `Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `For all other inquiries, please contact us at:`,
  forgotPassword: `Forgot password`,
  foundAnotherArtist: `Found another artist`,
  fromAnimeDotClub: `From anime.club`,
  getDetails: `Get details`,
  getStarted: `Get started`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (buyerUsername: string) =>
    `Great news! ${buyerUsername} purchased your item. Time to celebrate!`,
  greatNewsYourOrderIsNowInProgress: `Great news! Your order is now in progress`,
  guestView: `Guest view`,
  harassment: `Harassment`,
  hasNotAddedADescriptionFor: (username: string, title: string) =>
    `@${username} has not added a description for "${title}"`,
  hasNotSharedAnyPublicDetailsYet: (username: string) =>
    `@${username} has not shared any public details yet`,
  hate: `Hate`,
  haveAnyQuestions: `Have any questions?`,
  hereAreAFewWaysToGetThingsRolling: `Here are a few ways to get things rolling`,
  hide: `Hide`,
  hideListing: `Hide listing`,
  hire: `Hire`,
  homepage: `Homepage`,
  howToContactYou: `How to contact you`,
  howToFindYouOnOtherSocialNetworks: `How to find you on other social networks`,
  iAgreeWith: `I agree with`,
  id: `ID`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (timeLimit: string | number) =>
    `If no reply is received by ${timeLimit}, you'll automatically receive a full refund`,
  ifTheresNoResponseByTimeLimit: (reviewTimeLimit: string | number) =>
    `If there's no response by ${reviewTimeLimit}, the order will be marked as completed automatically`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (timeLimit: string | number) =>
    `If there's no response by ${timeLimit}, the order will be canceled automatically`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `If you have questions or concerns, please contact the seller directly`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `If you miss the deadline, the buyer can cancel the order for a full refund, and any associated Stripe fees will be deducted from your payout.`,
  ifYourArtIsNsfwCheckThisToAvoidAWarningOrBan: `If your art is NSFW, make sure to check this. Otherwise you may get a warning that could lead to a ban.`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Img height needs to be bigger than or equal to`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Img width needs to be bigger than or equal to`,
  impersonation: `Impersonation`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Include keywords that buyers would likely use to search for a product like yours`,
  includes: `Includes`,
  includesXRevisionS: (num: number) => `Includes ${num} revision(s)`,
  increaseContrast: `Increase contrast`,
  inProgress: `In progress`,
  instantDownload: `Instant Download`,
  introduction: `Introduction`,
  invalidCode: `Invalid code`,
  invalidCurrentPassword: `Invalid current password`,
  invalidDate: `Invalid date`,
  invalidPartAfterAt: `Invalid part after @`,
  invalidPartBeforeAt: `Invalid part before @`,
  itemReviews: `Item reviews`,
  jobDetails: `Job Details`,
  joinAnimeClubCommunity: `Join Anime.club community with thousands of active creators and cool anime art everyday!`,
  joinChat: `Join Chat`,
  joinUsOnFacebook: `Join us on facebook`,
  kindlyHoldOnForTheBuyersReview: `Kindly hold on for the buyer's review of the order`,
  lackOfInformation: `Lack of information`,
  language: `Language`,
  languages: `Languages`,
  leaveAReview: `Leave a review`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `Let buyers know if you offer <b>revisions</b>, and how many`,
  letEveryoneKnowHowToDonateToYou: `Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `Let others know about you`,
  letsUploadYourFirstProduct: `Let's upload your first product`,
  letUsKnowWhatsHappening: `Let us know what's happening and we'll look into it`,
  light: `Light`,
  likes: `Likes`,
  limit: `Limit`,
  listAnyContentOrRequestsYouDontAccept: `List any content or requests you <b>don't accept</b> (e.g. NSFW, political, religious, or offensive material)`,
  listingHiddenFromBuyers: `Listing hidden from buyers`,
  listingIsNowVisibleToBuyers: `Listing is now visible to buyers`,
  livesIn: `Lives in`,
  loading: `Loading`,
  location: `Location`,
  logInOrSignUp: `Log in or sign up`,
  logOut: `Log out`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `Make sure everything is ready to go — no edits after publishing`,
  makeSureToIncludeClearInstructions: `Make sure to include clear instructions on how each reference should be used`,
  makeSureYouFullyUnderstandTheRequirements: `Make sure you fully understand the requirements and can complete the order by the deadline`,
  makeSureYourProductsArePricedCompetitively: `Make sure your products are priced competitively`,
  maximumFileSize: (sizeMB: string) => `Maximum file size: <b>${sizeMB}</b> per file`,
  maximumNChars: (num: number) => `Maximum ${num} chars`,
  maximumNumberOfDaysToCompleteTheOrder: `Maximum number of days to complete the order`,
  maximumQuantity: `Maximum quantity`,
  maxSize: `Max size`,
  mentionYourDeliveryTimeInDays: `Mention your <b>delivery time</b> (in days)`,
  menu: `Menu`,
  message: `Message`,
  messages: `Messages`,
  minHeight: `Min height`,
  minimumDimensions: (width: number, height: number) => `Minimum size: ${width}×${height} pixels`,
  minimumNChars: (num: number) => `Minimum ${num} chars`,
  minorAbuseOrSexualization: `Minor abuse or sexualization`,
  minWidth: `Min width`,
  monthly: `Monthly`,
  moreFrom: (username: string) => `More from ${username}`,
  mustBeNChars: (num: number) => `Must be ${num} chars`,
  myPayments: `My payments`,
  myProfile: `My profile`,
  mySettings: `My settings`,
  need1Lowercase: `Need 1 lowercase`,
  need1Number: `Need 1 number`,
  need1Uppercase: `Need 1 uppercase`,
  needAtLeast1CharacterFromN: (characters: string) =>
    `Need at least 1 character from [${characters}]`,
  needNCharacter: (character: string) => `Need ${character} character`,
  needsYourReview: "Needs Your Review",
  new: `New`,
  newAccount: `New account`,
  newArt: `New art`,
  newArtworks: `New artworks`,
  newBlog: `New blog`,
  newCommission: `New commission`,
  newOrder: `New order`,
  newPassword: `New password`,
  newProduct: `New product`,
  newsFeed: `News feed`,
  next: `Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `Next time you authenticate, you could use the connected account, instead of the login and password`,
  no: `no`,
  noActiveOrdersToShow: `No active orders to show`,
  noCommentsJustYet: `No comments just yet`,
  noInternetConnection: `No Internet connection!`,
  nonConsensualIntimateContent: `Non-consensual intimate content`,
  none: `None`,
  noNotifications: `No notifications`,
  noOrders: `No orders`,
  noResults: `No results`,
  noReviewsJustYet: `No reviews just yet`,
  noSalesYetNoWorries: `No sales yet? No worries, you're just starting out`,
  notAcceptingOrders: `Not accepting orders`,
  nothingIsChargedUntilTheSellerAccepts: `Nothing is charged until the seller accepts, and if they decline you’re not charged at all`,
  notifications: `Notifications`,
  nsfwContent18Plus: `NSFW Content (18+)`,
  NSFWIndicatesAdultContent: `18+ NSFW indicates adult content. Check this field only if the content is intended for mature audiences`,
  numberOfAdjustmentsAClientCouldRequest: `Number of adjustments a client could request`,
  numFilesIncluded: (num: number) => `<b>${num}</b> file(s) included`,
  numOfNewComments: (count: number) => `${count} new ${count === 1 ? `comment` : `comments`}`,
  numOfNewReactions: (count: number) => `${count} new ${count === 1 ? `reaction` : `reactions`}`,
  numOfReplies: (count: number) => `${count} ${count === 1 ? `reply` : `replies`}`,
  numOfReviews: (num: number | string) => `Reviews: ${num} `,
  offerDigitalProducts: `Offer digital products that buyers can access right away`,
  offerOptionalExtras: `Offer optional extras like <b>rush delivery</b>, an <b>extra character</b>, or a <b>detailed background</b>`,
  online: `Online`,
  onlyLatinLettersNumbersHyphen: `Only latin letters, numbers, hyphen, underscore, and dot characters`,
  onlyNumbers: `Only numbers`,
  onlyYouCanSeeWhatYouveSaved: `Only you can see what you've saved`,
  open: `Open`,
  openDispute: `Open dispute`,
  openGuestView: `Open guest view`,
  openingSoon: `Opening Soon!`,
  openToWork: `Open to work`,
  optional: `Optional`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `Optionally, you can add a description to share more about your creation`,
  or: `or`,
  order: `Order`,
  orderAgain: `Order again`,
  orderCanceledTheBuyersPaymentWasReleased: `Order canceled. We released the hold on the buyer's card, their bank may take a few days to clear it`,
  orderCanceledYourPaymentWasReleased: `Order canceled. We released the hold on your card, your bank may take a few days to clear it`,
  orderCompleted: `Order Completed 🎉`,
  orderConfirmed: `Order confirmed`,
  orderDetails: `Order details`,
  ordered: (relativeTime: string) => `Ordered ${relativeTime}`,
  orderedByMistake: `Ordered by mistake`,
  orderOptions: `Order Options`,
  orderStatus: `Order status`,
  otherReason: `Other reason`,
  outOfStock: `Out of stock`,
  pageNotFound: `Page not found`,
  password: `Password`,
  payments: `Payments`,
  payouts: `Payouts`,
  personal: `Personal`,
  personalCircumstances: `Personal circumstances`,
  platform: `Platform`,
  platformPoliciesMayStillApply: `Platform policies may still apply`,
  pleaseAllowPopups: `Please allow popups`,
  pleaseCheckYour: (value: string) => `Please check your ${value}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Please do not share your private information to others`,
  pleaseEnterANumberBetweenXandX: (min: number, max: number) =>
    `Please enter a number between ${min} and ${max}`,
  pleaseEnterAtLeastNChars: (num: number) => `Please enter at least ${num} characters `,
  pleaseFillOutYourDetails: `Please fill out your details`,
  pleaseFixTheErrorsBeforeSubmitting: `Please fix the errors before submitting`,
  pleaseProvideATitleForYourArtwork: `Please provide a title for your artwork`,
  pleaseRateYourOrder: `Please rate your order`,
  pleaseRespondToTheOrderBy: (date: string) => `Please respond to the order by ${date}`,
  pleaseReviewTheBuyersReferenceFiles: `Please review the buyer's reference files and follow them as specified in the order's description`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `Please review the details carefully before proceeding`,
  pleaseSignInToYourAccount: `Please sign in to your account`,
  pleaseStartTyping: `Please start typing`,
  pleaseTakeAMomentToReviewTheOrder: `Please take a moment to review the order`,
  pleaseTryAgainOrClick: (buttonName: string) => `Please try again or click ${buttonName}`,
  pleaseUploadOnlyFinishedWorkHere: `Please upload only finished work here`,
  pleaseVerifyYourAccount: `Please verify your account`,
  portfolio: `Portfolio`,
  pressHereTo: `Press here to`,
  price: `Price`,
  privacyPolicy: `Privacy policy`,
  privateInformation: `Private information`,
  proceedToCheckout: `Proceed to Checkout`,
  product: `Product`,
  profile: `Profile`,
  prohibitedTransaction: `Prohibited transaction`,
  promotions: `Promotions`,
  publicInformation: `Public information`,
  publishOn: (socialMedia: string) => `Publish on ${socialMedia}`,
  purchases: `Purchases`,
  rankings: `Rankings`,
  reason: `Reason`,
  reorderFiles: `Reorder files`,
  replies: `Replies`,
  reply: `Reply`,
  replyToUsername: (username: string) => `Reply to ${username}`,
  report: `Report`,
  requestDetails: `Request details`,
  review: `Review`,
  reviewed: `Reviewed`,
  reviews: `Reviews`,
  reviewTitle: `Review title`,
  revisions: `Revisions`,
  rules: `Rules`,
  sales: `Sales`,
  save: `Save`,
  saveAvatar: `Save avatar`,
  saveChanges: `Save changes`,
  selectAnime: `Select Anime`,
  selectAppearanceContrastAndColorTheme: `Select appearance, contrast, and color theme`,
  selectAvatar: `Select avatar`,
  selectCharacters: `Select Character(s)`,
  selectFile: `Select file`,
  selectThumbnail: `Select thumbnail`,
  selfHarmOrSuicide: `Self-harm or suicide`,
  sellDownloadableContent: `Sell downloadable content`,
  seller: `Seller`,
  sellerHasntResponded: `Seller hasn't responded`,
  sellerTermsOfService: `Seller Terms of Service`,
  sendEmail: `Send email`,
  settings: `Settings`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Setting up a shop is free and only takes a few minutes`,
  setUpStripeAccountToGetPaidWithAnimeClub: "Set up a Stripe account to get paid with Anime.club",
  share: `Share`,
  shareYourArt: `Share your art`,
  shareYourArtWithTheWorld: `Share your art with the world`,
  shareYourFavoritePiecesOn: (url: string) => `Share your favorite pieces on ${url}`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `Share your rules and the types of requests you don’t accept`,
  shareYourShopOnSocialMedia: `Share your shop on social media`,
  shareYourStory: `Share your story!`,
  sharingPersonalInformation: `Sharing personal information`,
  shop: `Shop`,
  shopOrders: `Shop orders`,
  shopReviews: `Shop reviews`,
  show: `Show`,
  showLess: `Show less`,
  showListing: `Show listing`,
  showMore: `Show more`,
  showMyTermsOfService: `Show my terms of service`,
  showSellerTermsOfService: `Show seller's terms of service`,
  signIn: `Sign in`,
  size: `Size`,
  skip: `Skip`,
  socialMedia: `Social media`,
  spaceCharacterIsNotAllowed: `Space character is not allowed`,
  spam: `Spam`,
  submitAReport: `Submit a report`,
  submitWork: `Submit work`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Subscribe to talents to keep up with their progress`,
  successChangedPasswordPleaseSignIn: `Success! Changed password. Please sign in`,
  successCreatedRecord: `Success! Created record!`,
  successfullyDownloaded: `Successfully downloaded!`,
  successfullyUploaded: `Successfully uploaded!`,
  supportedFormats: `Supported formats:`,
  supportMeOn: `Support me on`,
  system: `System`,
  takeCustomRequests: `Take custom requests`,
  tapAddToCreateOne: `Tap “Add” to create one`,
  tellTheBuyersWhatTheyWillGet: `Tell buyers exactly what they will get. For example, the number of illustrations, file formats, or canvas specs like resolution and DPI`,
  tellUsAboutYourself: `Tell us about yourself`,
  termsAndConditions: `Terms and Conditions`,
  termsOfUse: `Terms of use`,
  thankYouForReport: `Thank you for helping to maintain a safe and respectful online community`,
  thankYouForYourPurchase: `Thank you for your purchase!`,
  thankYouForYourReview: `Thank you for your review!`,
  theBuyerAcceptedThemAtCheckout: `The buyer accepted them at checkout`,
  theLinkIsBrokenOrPageHasBeenRemoved: `The link is broken or page has been removed`,
  theMaximumQuantityThatACustomerCanAdd: `The maximum quantity that a customer can add`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `The reason you provide for cancelling this order will be shared with the buyer`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheSeller: `The reason you provide for cancelling this order will be shared with the seller`,
  theReviewPeriodIsLimitedtoNdays: (numOfDays: number | string) =>
    `The review period is limited to <b>${numOfDays}</b> days`,
  theseAreYourTermsForThisItem: `These are your terms for this item`,
  theSellerHasUploadedTheseFilesForYou: `The seller has uploaded these files for you`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `These rules are provided by the seller and apply only to this item`,
  thisCannotBeUndone: `This cannot be undone`,
  thisFieldIsOptional: `This field is optional`,
  thisIsACustomOrderNotAReadyMadeProduct: `You’re ordering custom work, not a ready-made product`,
  thisIsThePriceYouPropose: `This is the price you propose`,
  thisListingWontBeVisibleToBuyersAnymore: `This listing won’t be visible to buyers anymore — but you can show it again whenever you’re ready`,
  threateningViolence: `Threatening violence`,
  timeConstraints: `Time constraints`,
  title: `Title`,
  titleYourExtraService: `Title your extra service`,
  today: `Today`,
  toGetWorkRelatedNotifications: `To get work-related notifications`,
  toHelpTheCreatorCompleteYourOrder: `To help the creator complete your order to your satisfaction, please provide a detailed description of what you want. Include the desired theme, style, and character features, as well as any other important specifications`,
  total: `Total`,
  toViewThisDataYouNeedToUnblock: (username: string) =>
    `To view this data, you need to unblock @${username}`,
  trademarkViolation: `Trademark violation`,
  typeYourTextHere: `Type your text here...`,
  unblock: `Unblock`,
  unblockUser: (username: string) => `Unblock @${username}`,
  unfollow: `Unfollow`,
  unfortunatelyTheSellerHadToCancelThisOrder: (user: string) =>
    `Unfortunately, ${user} had to cancel this order`,
  unlimited: `Unlimited`,
  upload: `Upload`,
  uploadedFilesLocked: `You uploaded these files when you created the post. They're now locked but still visible below`,
  uploadNew: `Upload new`,
  uploadNewPost: `Upload new post`,
  uploadNewProduct: `Upload new product`,
  uploadTheFilesYourBuyerWillGet: `Upload the files your <b>buyer will get</b>`,
  uploadUpToNumberFiles: (limit: number) => `Upload up to <b>${limit}</b> files`,
  username: `Username`,
  usernameAlreadyExists: `Username already exists`,
  usernameAndXMoreCommented: (username: string, numberOfNotifiers: number) =>
    `<b>${username}</b> and ${numberOfNotifiers} more commented`,
  usernameAndXMoreFollowYou: (username: string, numberOfNotifiers: number) =>
    `<b>${username}</b> and ${numberOfNotifiers} more just followed you`,
  usernameAndXMoreReacted: (username: string, numberOfNotifiers: number) =>
    `<b>${username}</b> and ${numberOfNotifiers} more reacted`,
  usernameAndXMoreRepliedToYourComment: (username: string, numberOfNotifiers: number) =>
    `<b>${username}</b> and ${numberOfNotifiers} more replied to your comment`,
  usernameCommentedOnYourWork: (username: string) => `<b>${username}</b> commented on your work`,
  usernameHasCanceledTheOrder: (username: string) => `<b>${username}</b> has canceled the order`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (username: string) =>
    `@${username} hasn’t added anything to their portfolio yet`,
  usernameHasntListedAnyProductsForSaleYet: (username: string) =>
    `@${username} hasn't listed any products for sale yet`,
  usernameHasSubmittedTheWork: (username: string) => `<b>${username}</b> has submitted the work`,
  usernameLeftAReaction: (username: string) => `<b>${username}</b> left a reaction`,
  usernameRepliedToYourComment: (username: string) => `<b>${username}</b> replied to your comment`,
  usernameStartedFollowingYou: (username: string) => `<b>${username}</b> started following you`,
  useThisEmailTo: `Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `Value is not the same`,
  verificationCode: `Verification Code`,
  verifyCode: `Verify code`,
  viewDetails: `View details`,
  viewEveryNotificationOfAGroupSeparately: `View every notification of a group separately`,
  viewReview: `View review`,
  visitOurDiscordChannelToGetMoreDetails: `Visit our discord channel to get more details`,
  visitStripeDashboard: `Visit Stripe dashboard`,
  vote: `Vote`,
  weAreExcitedToSeeYourProgressKeepItUp: `We are excited to see your progress. Keep it up!`,
  weAreOnInstagram: `We are on Instagram`,
  weAreWorkingOnIt: `We are working on it`,
  weDoNotDisplayNSFWContentYet: `We do not display NSFW content yet`,
  weekly: `Weekly`,
  weHaveSentTooManyEmails: `We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Welcome to Anime.club!`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `Well done! Work has been successfully completed`,
  weSentAnEmailTo: `We sent an email to:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `We sent you a new verification email. Please enter the code`,
  weSupportOnlyTheFollowingFileExtensions: `We support only the following file extensions:`,
  weWouldLoveToHearFromYou: `We would love to hear from you`,
  whatWouldYouLikeToCreate: `What would you like to create?`,
  whenYouPurchaseSomethingItWillAppearHere: `When you purchase something, it will appear here`,
  work: `Work`,
  workDescription: `Work description`,
  wrongEmailOrPassword: `Wrong email or password`,
  yes: `yes`,
  yesterday: `Yesterday`,
  youAreAlreadyAuthenticated: `You are already authenticated`,
  youCanAutoPublishToYourSocialMediaAccount: `You can auto publish to your social media account`,
  youCanceledTheOrder: `You canceled the order`,
  youCanChooseFromTheListOrEnterACustomReason: `You can choose from the list or enter a custom reason`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `You can modify the types of notifications you receive via email`,
  youCanRequestRemovalOfYourAccount: `You can request removal of your account with all your data`,
  youCanStillNavigateToThePreviouslyOpenedPages: `You can still navigate to the previously opened pages`,
  youDidNotSelectAnyChats: `You did not select any chats`,
  youDidNotUpdateAnyValues: `You did not update any values`,
  youDoNotHaveAnyChats: `You do not have any chats`,
  youHaveNoPurchases: `You have no purchases`,
  youHaveNotSetAPassword: `You have not set a password`,
  youHaveNotSharedAnythingYet: `You have not shared anything yet`,
  youHaveReachedTheMaximumNumberOfFiles: `You have reached the maximum number of files`,
  youHaveSuccessfullyCreatedYourShop: `You have successfully created your shop`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `You’ll see reviews here once buyers share their experience`,
  yourAccountIsVerifiedPleaseSignIn: `Your account is verified. Please sign in`,
  yourAccountWillBeRemoved: (time: string) => `Your account will be removed ${time}`,
  yourArts: `Your arts`,
  yourAvatar: `Your avatar`,
  yourBlog: `Your blog`,
  youReceivedANewOrderFrom: (username: string) =>
    `You received a new order from <b>${username}</b>`,
  youReceivedAReview: `You received a review`,
  yourFansAreWaiting: `Your fans are waiting`,
  yourFavoritesWillShowUpHereAddSome: `Your favorites will show up here. Add some!`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `Your feedback guides buyers and helps sellers offer better products`,
  yourFeedIsEmpty: `your feed is empty`,
  yourSessionHasExpiredPleaseSignInAgain: `Your session has expired, please sign in again`,
  yourTermsOfService: `Your Terms of Service`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `You'll be able to download your files immediately after purchase—no waiting required!`,
  youWillBeAbleToUploadReferenceFilesAfterCheckout: `You’ll be able to upload reference files after checkout`,
}
export type english = typeof text
