export const text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `About`,
  accept: `Accept`,
  account: `Account`,
  accountActivation: `Account activation`,
  accountAlreadyExists: `Account already exists`,
  accountDoesNotExist: `Account does not exist`,
  add: `Add`,
  addArt: `Add art`,
  addBlog: `Add blog`,
  addFile: `Add file`,
  additionalResources: `Additional resources`,
  addMore: `Add more`,
  addNewArt: `Add new art`,
  addPreview: `Add preview`,
  addSignInVia: `Add sign in via`,
  addToCart: `Add to cart`,
  advancedOptions: `Advanced options`,
  all: `All`,
  alreadySignedIn: `Already signed in`,
  amount: `Amount`,
  amountShouldNotBeLessThan: (amount: number) =>
    `Amount should not be less than ${amount}`,
  animeArtByArtistsFromAllOverTheWorld: `Anime art by artists from all over the world. Art is curated to be related to anime. The art selection is an infinite list of best anime art`,
  animeArtSubscribeToArtistsLikeAndCreate: `Anime art - subscribe to artists, like, and create collections`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - the first platform to offer artists payments from views via Google AdSense. Support artists by viewing their content or start earning from views`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - view, post, and earn from anime content`,
  animeCommunity: `Anime community`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club never asks for your private information`,
  animeSocialNetwork: `Anime\nSocial Network`,
  announcements: `Announcements`,
  apply: `Apply`,
  appSettings: `App settings`,
  appsVersionIs: `App's version is`,
  areYouSureYouWantTo: `Are you sure you want to`,
  art: `Art`,
  artAssociatedWithAnime: `Art associated with anime`,
  artBy: (username: string) => `Art by ${username}`,
  artCannotBeChanged: `Art cannot be changed`,
  artworksAvailableToView: (num: number) => `${num} artworks available to view`,
  authenticationFailed: `Authentication failed`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `Back`,
  basePrice: `Base Price`,
  blog: `Blog`,
  bookmarks: `Bookmarks`,
  browseArt: `Browse art`,
  cancel: `Cancel`,
  cannotStartWithChars: `Cannot start with {:"^$*[]{}()?-"!@#%&/\\,><':;|~\`"`,
  change: `Change`,
  changeArt: `Change art`,
  changeAvatar: `Change avatar`,
  changeEmail: `Change email`,
  changePassword: `Change password`,
  chooseExistingChatOrStartANewOne: `Choose existing chat or start a new one`,
  city: `City`,
  clearAll: `Clear all`,
  close: `Close`,
  colorTheme: `Color theme`,
  comingSoon: `Coming soon…`,
  commercialUse: `Commercial use`,
  community: `Community`,
  confirmAccount: `Confirm account`,
  confirmPassword: `Confirm password`,
  connectWithUsOn: `Connect with us on`,
  contactInformation: `Contact information`,
  contactSeller: `Contact seller`,
  contactCustomer: `Contact customer`,
  contactSupport: `Contact support`,
  continue: `Continue`,
  contractTitle: `Contract Title`,
  copyLink: `Copy link`,
  couldNotCreateANewRecord: `Could not create a new record`,
  country: `Country`,
  cover: `Cover`,
  creator: `Creator`,
  createANewAccountFailed: `Create a new account failed`,
  createExtrasForYourProduct: `Create extras for your product`,
  createNewAccount: `Create new account`,
  createYourShop: `Create your shop`,
  currentPassword: `Current password`,
  daily: `Daily`,
  darkDefault: `Dark default`,
  darkHighContrast: `Dark high contrast`,
  dayTheme: `Day theme`,
  delete: `Delete`,
  deleteArt: `Delete art`,
  deletePost: `Delete post`,
  deleteProduct: `Delete product`,
  deliveryTime: `Delivery time`,
  describeTheDetailsOfYourProduct: `Describe the details of your product`,
  description: `Description`,
  details: `Details`,
  didntReceiveEmail: `Didn't receive email?`,
  displayName: `Display name`,
  donations: `Donations`,
  done: `Done`,
  dragAndDropOrSelectFiles: `Drag & Drop or Select file(s)`,
  drawingContest: `Drawing contest`,
  dueDate: `Due date`,
  earlier: `Earlier`,
  earningFromArts: `Earning from arts`,
  edit: `Edit`,
  editPost: `Edit post`,
  editProfile: `Edit profile`,
  editTranslations: `Edit translations`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email already used by another account`,
  emailNotifications: `Email Notifications`,
  enterOrPasteALink: `Enter or paste a link`,
  enterTheAddressAssociatedWithYourAccount: `Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `Enter your password`,
  error: `Error`,
  errorPleaseContactCustomerSupport: `Error! Please contact customer support...`,
  exitEditor: `Exit editor`,
  extensions: `Extensions`,
  extras: `Extras`,
  fileSizeIsTooBig: `File size is too big`,
  filter: `Filter`,
  filterBy: `Filter by`,
  findUser: `Find user`,
  follow: `Follow`,
  followers: `Followers`,
  following: `Following`,
  followMeOn: `Follow me on`,
  follows: `Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `For all other inquiries, please contact us at:`,
  forgotPassword: `Forgot password`,
  fromAnimeDotClub: `From anime.club`,
  getDetails: `Get details`,
  getStarted: `Get started`,
  guestView: `Guest view`,
  hasNotAddedADescriptionFor: (username: string, title: string) =>
    `@${username} has not added a description for "${title}"`,
  hasNotSharedAnyPublicDetailsYet: (username: string) =>
    `@${username} has not shared any public details yet`,
  hire: `Hire`,
  homepage: `Homepage`,
  howToContactYou: `How to contact you`,
  howToFindYouOnOtherSocialNetworks: `How to find you on other social networks`,
  iAgreeWith: `I agree with`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Img height needs to be bigger than or equal to`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Img width needs to be bigger than or equal to`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Include keywords that buyers would likely use to search for a product like yours`,
  introduction: `Introduction`,
  invalidCode: `Invalid code`,
  invalidCurrentPassword: `Invalid current password`,
  invalidDate: `Invalid date`,
  invalidPartAfterAt: `Invalid part after @`,
  invalidPartBeforeAt: `Invalid part before @`,
  jobDetails: `Job Details`,
  joinAnimeClubCommunity: `Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `Join Chat`,
  joinUsOnFacebook: `Join us on facebook`,
  language: `Language`,
  languages: `Languages`,
  letEveryoneKnowHowToDonateToYou: `Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `Let others know about you`,
  licenseForForProfitBusinessUse: `License for for-profit business use`,
  lightDefault: `Light default`,
  lightHighContrast: `Light high contrast`,
  likes: `Likes`,
  linkCopiedToClipboard: `Link copied to clipboard`,
  livesIn: `Lives in`,
  loading: `Loading`,
  location: `Location`,
  logInOrSignUp: `Log in or sign up`,
  logOut: `Log out`,
  maximumNChars: (num: number) => `Maximum ${num} chars`,
  maximumNumberOfDaysToCompleteTheOrder: `Maximum number of days to complete the order`,
  maximumQuantity: `Maximum quantity`,
  maxSize: `Max size`,
  menu: `Menu`,
  message: `Message`,
  messages: `Messages`,
  minHeight: `Min height`,
  minimumNChars: (num: number) => `Minimum ${num} chars`,
  minWidth: `Min width`,
  monthly: `Monthly`,
  moreFrom: (username: string) => `More from ${username}`,
  mustBeNChars: (num: number) => `Must be ${num} chars`,
  myPayments: `My payments`,
  myProfile: `My profile`,
  mySettings: `My settings`,
  need1Lowercase: `Need 1 lowercase`,
  need1Number: `Need 1 number`,
  need1Uppercase: `Need 1 uppercase`,
  needAtLeast1CharacterFromN: (characters: string) =>
    `Need at least 1 character from [${characters}]`,
  needNCharacter: (character: string) => `Need ${character} character`,
  newAccount: `New account`,
  newArt: `New art`,
  newArtworks: `New artworks`,
  newBlog: `New blog`,
  newPassword: `New password`,
  newProduct: `New product`,
  newsFeed: `News feed`,
  next: `Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `Night theme`,
  no: `no`,
  noAddedFavoriteArts: `no added favorite arts`,
  noInternetConnection: `No Internet connection!`,
  none: `None`,
  noNotifications: `No notifications`,
  noResults: `No results`,
  notifications: `Notifications`,
  nsfwContent18Plus: `NSFW Content (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `Number of adjustments a client could request`,
  online: `Online`,
  onlyLatinLettersNumbersHyphen: `Only latin letters, numbers, hyphen, underscore, and dot characters`,
  onlyNumbers: `Only numbers`,
  open: `Open`,
  openGuestView: `Open guest view`,
  openingSoon: `Opening Soon!`,
  openToWork: `Open to work`,
  optional: `Optional`,
  or: `or`,
  orderOptions: `Order Options`,
  orderAgain: `Order again`,
  pageNotFound: `Page not found`,
  password: `Password`,
  payments: `Payments`,
  personal: `Personal`,
  pleaseCheckYour: (value: string) => `Please check your ${value}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `Please drop only one image`,
  pleaseEnterANumberBetweenXandX: (min: number, max: number) =>
    `Please enter a number between ${min} and ${max}`,
  pleaseEnterAtLeastNChars: (num: number) =>
    `Please enter at least ${num} characters `,
  pleaseFillOutYourDetails: `Please fill out your details`,
  pleaseSignInToYourAccount: `Please sign in to your account`,
  pleaseTryAgainOrClick: (buttonName: string) =>
    `Please try again or click ${buttonName}`,
  pleaseVerifyYourAccount: `Please verify your account`,
  pressHereTo: `Press here to`,
  price: `Price`,
  privacyPolicy: `Privacy policy`,
  privateInformation: `Private information`,
  proceedToCheckout: `Proceed to Checkout`,
  product: `Product`,
  profile: `Profile`,
  promotions: `Promotions`,
  publicInformation: `Public information`,
  publishOn: (socialMedia: string) => `Publish on ${socialMedia}`,
  rankings: `Rankings`,
  reorderFiles: `Reorder files`,
  report: `Report`,
  revisions: `Revisions`,
  save: `Save`,
  saveAvatar: `Save avatar`,
  saveChanges: `Save changes`,
  selectAnime: `Select Anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `Select avatar`,
  selectCharacters: `Select Character(s)`,
  selectFile: `Select file`,
  selectTheme: `Select theme`,
  selectThumbnail: `Select thumbnail`,
  sendEmail: `Send email`,
  settings: `Settings`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Setting up a shop is free and only takes a few minutes`,
  share: `Share`,
  shareYourArtWithTheWorld: `Share your art with the world`,
  shareYourStory: `Share your story!`,
  shop: `Shop`,
  shopOrders: `Shop orders`,
  showLess: `Show less`,
  showMore: `Show more`,
  signIn: `Sign in`,
  singleTheme: `Single theme`,
  size: `Size`,
  skip: `Skip`,
  socialMedia: `Social media`,
  spaceCharacterIsNotAllowed: `Space character is not allowed`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Subscribe to talents to keep up with their progress`,
  successChangedPasswordPleaseSignIn: `Success! Changed password. Please sign in`,
  successCreatedRecord: `Success! Created record!`,
  successUpdatedRecord: `Success! Updated record!`,
  supportMeOn: `Support me on`,
  syncWithSystem: `Sync with system`,
  tellUsAboutYourself: `Tell us about yourself`,
  termsAndConditions: `Terms and Conditions`,
  termsOfUse: `Terms of use`,
  theLinkIsBrokenOrPageHasBeenRemoved: `The link is broken or page has been removed`,
  themeMode: `Theme mode`,
  thisIsThePriceYouPropose: `This is the price you propose`,
  title: `Title`,
  titleYourExtraService: `Title your extra service`,
  today: `Today`,
  toGetWorkRelatedNotifications: `To get work-related notifications`,
  total: `Total`,
  typeYourTextHere: `Type your text here...`,
  unlimited: `Unlimited`,
  upload: `Upload`,
  uploadNew: `Upload new`,
  uploadNewPost: `Upload new post`,
  username: `Username`,
  usernameAlreadyExists: `Username already exists`,
  usernameAndXMoreFollowYou: (username: string, numberOfNotifiers: number) =>
    `<b>${username}</b> and ${numberOfNotifiers} more follow you`,
  usernameAndXMoreLikeYourArtwork: (
    username: string,
    numberOfNotifiers: number,
  ) => `<b>${username}</b> and ${numberOfNotifiers} more like your artwork`,
  usernameFollowsYou: (username: string) => `<b>${username}</b> follows you`,
  usernameLikesYourArt: (username: string) =>
    `<b>${username}</b> likes your art`,
  useThisEmailTo: `Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `Value is not the same`,
  verificationCode: `Verification Code`,
  verifyCode: `Verify code`,
  viewDetails: `View details`,
  viewEveryNotificationOfAGroupSeparately: `View every notification of a group separately`,
  visitOurDiscordChannelToGetMoreDetails: `Visit our discord channel to get more details`,
  weAreOnInstagram: `We are on Instagram`,
  weAreWorkingOnIt: `We are working on it`,
  weDoNotDisplayNSFWContentYet: `We do not display NSFW content yet`,
  weekly: `Weekly`,
  weHaveSentTooManyEmails: `We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Welcome to Anime.club!`,
  weSentAnEmailTo: `We sent an email to:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `We sent you a new verification email. Please enter the code`,
  weSupportOnlyTheFollowingFileExtensions: `We support only the following file extensions:`,
  work: `Work`,
  workDescription: `Work description`,
  wrongEmailOrPassword: `Wrong email or password`,
  yes: `yes`,
  yesterday: `Yesterday`,
  youAreAlreadyAuthenticated: `You are already authenticated`,
  youCanAutoPublishToYourSocialMediaAccount: `You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `You can still navigate to the previously opened pages`,
  youDidNotSelectAnyChats: `You did not select any chats`,
  youDidNotUpdateAnyValues: `You did not update any values`,
  youDoNotHaveAnyChats: `You do not have any chats`,
  youHaveNotSavedAnyChanges: `You have not saved any changes`,
  youHaveNotSetAPassword: `You have not set a password`,
  youHaveNotSharedAnythingYet: `You have not shared anything yet`,
  youHaveReachedTheMaximumNumberOfFiles: `You have reached the maximum number of files`,
  yourAccountIsVerifiedPleaseSignIn: `Your account is verified. Please sign in`,
  yourArts: `Your arts`,
  yourAvatar: `Your avatar`,
  yourBlog: `Your blog`,
  yourFansAreWaiting: `Your fans are waiting`,
  yourFeedIsEmpty: `your feed is empty`,
  yourSessionHasExpiredPleaseSignInAgain: `Your session has expired, please sign in again`,
}
export type english = typeof text
