export const text: text = {
  _dash: `(en) - `,
  acceptTheOrder: `(en) Accept the order`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `(en) AI-generated images and neural network filters are prohibited`,
  addMoreProductsToYourShop: `(en) Add more products to your shop`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `(en) All files you upload here will be available to the buyer`,
  bigAppreciationToTheSellerForTheirHardWork: `(en) Big appreciation to the seller for their hard work`,
  buyerReviewedTheOrder: `(en) Buyer reviewed the order`,
  buyerHasNotLeftAReviewYet: `(en) Buyer has not left a review yet`,
  feedbackReceived: `(en) Feedback received!`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `(en) Before accepting, please review the buyer's request carefully`,
  checkOutMyShop: `(en) Check out my shop`,
  commercialUseAllowed: `(en) Commercial use allowed`,
  commercialUseAllowsBuyersToUseYourProduct: `(en) Commercial use allows buyers to use your product for business purposes, like selling or promoting their services`,
  congratulationsOnSuccessfullyCompletingYourOrder: `(en) Congratulations on successfully completing your order!`,
  createAShopWithStripe: `(en) Create a shop with Stripe`,
  createdBy: `(en) Created by`,
  download: `(en) Dowload`,
  downloadThemBelow: `(en) Download them below`,
  describeTheDetailsOfYourExtra: `(en) Describe the details of your extra`,
  enjoyYourPurchase: `(en) Enjoy your purchase! 😊`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `(en) Extras are optional add-ons to enhance your product`,
  usernameHasSubmittedTheWork: (...v) =>
    `(en) <b>${v[0]}</b> has submitted the work`,
  hereAreAFewWaysToGetThingsRolling: `(en) Here are a few ways to get things rolling`,
  makeSureToIncludeClearInstructions: `(en) Make sure to include clear instructions on how each reference should be used`,
  makeSureYouFullyUnderstandTheRequirements: `(en) Make sure you fully understand the requirements and can complete the order by the deadline`,
  makeSureYourProductsArePricedCompetitively: `(en) Make sure your products are priced competitively`,
  noReviewsJustYet: `(en) No reviews just yet`,
  noSalesYetNoWorries: `(en) No sales yet? No worries, you're just starting out`,
  NSFWIndicatesAdultContent: `(en) 18+ NSFW indicates adult content. Check this field only if your product is intended for mature audiences`,
  onlyYouCanSeeWhatYouveSaved: `(en) Only you can see what you've saved`,
  requestDetails: `(en) Request details`,
  orderCompleted: `(en) Order Completed 🎉`,
  pleaseRateYourOrder: `(en) Please rate your order`,
  feelFreeToShareReferenceImagesAndMaterials: `(en) Feel free to share reference images and materials to help the artist create your piece`,
  pleaseFixTheErrorsBeforeSubmitting: `(en) Please fix the errors before submitting`,
  pleaseTakeAMomentToReviewTheOrder: `(en) Please take a moment to review the order 🙏 `,
  pleaseReviewTheBuyersReferenceFiles: `(en) Please review the buyer's reference files and follow them as specified in the order's description`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `(en) Please review the details carefully before proceeding`,
  pleaseRespondToTheOrderBy: (...v) =>
    `(en) Please respond to the order by ${v[0]}`,
  review: `(en) Review`,
  rules: `(en) Rules`,
  reviews: `(en) Reviews`,
  reviewed: `(en) Reviewed`,
  reviewTitle: `(en) Review title`,
  reason: `(en) Reason`,
  yourOrderIncludesXRevisionS: (...v) =>
    `(en) Your order includes ${v[0]} revision(s)`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `(en) Share your rules and the types of requests you don’t accept`,
  shareYourShopOnSocialMedia: `(en) Share your shop on social media`,
  shareYourFavoritePiecesOn: (...v) =>
    `(en) Share your favorite pieces on ${v[0]}`,
  shopReviews: `(en) Shop reviews`,
  startAddingFavoritesToSeeThemHere: `(en) Start adding favorites to see them here`,
  successfullyDownloaded: `(en) Successfully downloaded!`,
  successfullyUploaded: `(en) Successfully uploaded!`,
  tellTheBuyerWhatTheyWillGetWithThisProduct: `(en) Tell the buyer what they will get with this product`,
  thankYouForYourReview: `(en) Thank you for your review!`,
  thankForYourSupport: `(en) Thank you for your support!`,
  thisFieldIsOptional: `(en) This field is optional`,
  thisCannotBeUndone: `(en) This cannot be undone`,
  ensureYouveUploadedTheFinalVersion: `(en)  Ensure you've uploaded the final version before submitting`,
  theSellerHasUploadedTheseFilesForYou: `(en) The seller has uploaded these files for you`,
  pleaseUploadOnlyFinishedWorkHereMaximumFiles: `(en) Please upload only finished work here`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `(en) All WIP-related files should be uploaded in messages`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `(en) Unfortunately, ${v[0]} had to cancel this order`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `(en) Well done! Work has been successfully completed`,
  youReceivedAReview: `(en) You received a review`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `(en) Your feedback guides buyers and helps sellers offer better products`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `(en) You’ll see reviews here once buyers share their experience`,
  youCanceledTheOrder: `(en) You canceled the order`,
  _colon: ` : `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: ` ! `,
  _question: ` ? `,
  _space: ` `,
  about: `Sur`,
  accept: `Accepter`,
  acceptOrder: `Accepter la commande`,
  account: `Compte`,
  accountDeleted: `Compte supprimé`,
  accountActivation: `Activation de compte`,
  accountAlreadyExists: `Compte existe déjà`,
  accountDoesNotExist: `Compte n'existe pas`,
  accountRemoval: `Suppression de compte`,
  add: `Ajouter`,
  addArt: `Ajouter une illustration`,
  addBlog: `Ajouter un blog`,
  addFile: `Ajouter un fichier`,
  additionalResources: `Ressources supplémentaires`,
  addMore: `Ajouter plus`,
  addNewArt: `Ajouter un nouvel art`,
  addPreview: `Ajouter un aperçu`,
  addSignInVia: `Ajouter une connexion via`,
  addToCart: `Ajouter au panier`,
  advancedOptions: `Options avancées`,
  all: `Tout`,
  alreadySignedIn: `Déjà connecté`,
  amount: `Montant`,
  amountShouldNotBeLessThan: (...v) =>
    `Le montant ne doit pas être inférieur à ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `L'art de l'anime par des artistes du monde entier. L'art est organisé pour être lié à l'anime. La sélection d'art est une liste infinie des meilleurs dessins animés`,
  animeArtSubscribeToArtistsLikeAndCreate: `L'art de l'anime - abonnez-vous à des artistes, aimez et créez des collections`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - la première plate-forme à proposer aux artistes des paiements à partir de vues via Google AdSense. Soutenez les artistes en affichant leur contenu ou commencez à gagner des vues`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - afficher, publier et gagner du contenu d'anime`,
  animeCommunity: `Communauté d'anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club ne demande jamais vos informations privées`,
  animeSocialNetwork: `Réseau social anime`,
  announcements: `Annonces`,
  apply: `Appliquer`,
  appSettings: `Paramètres de l'application`,
  appsVersionIs: `La version de l'application est`,
  areYouSureYouWantTo: `Êtes-vous sûr de vouloir`,
  art: `Art`,
  artAssociatedWithAnime: `Art associé à l'anime`,
  artBy: (...v) => `Art par ${v[0]}`,
  artCannotBeChanged: `L'art ne peut pas être changé`,
  artworksAvailableToView: (...v) =>
    `${v[0]} œuvres d'art disponibles à la visualisation`,
  authenticationFailed: `Authentification échouée`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `La publication automatique sur Instagram n'est disponible que pour les comptes professionnels Instagram`,
  attentionYourOrderHasBeenDisputed: `Attention ! Votre commande a été contestée. Veuillez vérifier les détails`,
  awaitingReview: `En attente de révision`,
  awaitingSeller: `En attente du vendeur`,
  back: `Arrière`,
  basePrice: `Prix de base`,
  block: `Bloquer`,
  blockUser: (...v) => `Bloquer @${v[0]}`,
  blog: `Blog`,
  bookmarks: `Signets`,
  browseArt: `Parcourir l'art`,
  browseShop: `Parcourir la boutique`,
  buyer: `Acheteur`,
  cancel: `Annuler`,
  canceled: `Annulé`,
  cancelOrder: `Annuler la commande`,
  cannotStartWithChars: `Impossible de démarrer avec s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Changer`,
  checkOrderStatus: `Vérifier le statut de la commande`,
  changeArt: `Changer d'art`,
  changeAvatar: `Changer d'avatar`,
  changeEmail: `Changer d'email`,
  changePassword: `Changer le mot de passe`,
  chooseExistingChatOrStartANewOne: `Sélectionnez un chat existant ou créez-en un nouveau`,
  city: `Ville`,
  clearAll: `Tout désélectionner`,
  clientReview: `Avis du client`,
  close: `Fermer`,
  colorTheme: `Thème de couleur`,
  comingSoon: `À venir …`,
  community: `Communauté`,
  completed: `Terminé`,
  confirmAccount: `Confirmer le compte`,
  confirmOrder: `Confirmer la commande`,
  confirmPassword: `Confirmez le mot de passe`,
  connectWithUsOn: `Connectez-vous avec nous sur`,
  contactInformation: `Informations de contact`,
  contactSeller: `Contacter le vendeur`,
  contactSupport: `Contacter le support`,
  contactUs: `Contactez-nous`,
  continue: `Continuer`,
  contractTitle: `Titre du contrat`,
  copyLink: `Copier le lien`,
  congratulations: `Félicitations !`,
  copyrightViolation: `Violation de droits d'auteur`,
  couldNotCreateANewRecord: `Impossible de créer un nouvel enregistrement`,
  country: `Pays`,
  cover: `Couverture`,
  createANewAccountFailed: `Échec de la création d'un nouveau compte a échoué`,
  createExtrasForYourProduct: `Créer des extras pour votre produit`,
  createNewAccount: `Créer un nouveau compte`,
  currentPassword: `Mot de passe actuel`,
  daily: `Quotidien`,
  darkDefault: `Thème sombre par défaut`,
  darkHighContrast: `Thème sombre à fort contraste`,
  dayTheme: `Thème de jour`,
  delete: `Supprimer`,
  deleteShop: `Supprimer la boutique`,
  deleteAccount: `Supprimer le compte`,
  deleteArt: `Supprimer l'art`,
  decline: `Refuser`,
  deletePost: `Supprimer le message`,
  deleteProduct: `Supprimer le produit`,
  deliveryTime: `Délai de livraison`,
  description: `Description`,
  details: `Détails`,
  didntReceiveEmail: `Vous n'avez pas reçu le courriel ?`,
  displayName: `Nom d'affichage`,
  disputed: `Contesté`,
  donations: `Dons`,
  done: `Terminé`,
  dragAndDropOrSelectFiles: `Glisser-déposer ou sélectionner des fichiers`,
  drawingContest: `Concours de dessin`,
  dueDate: `Date d'échéance`,
  earlier: `Plus tôt`,
  earningFromArts: `Gagner des arts`,
  edit: `Modifier`,
  editPost: `Editer le poste`,
  editProfile: `Editer le profil`,
  editTranslations: `Modifier les traductions`,
  email: `Courriel`,
  emailAlreadyUsedByAnotherAccount: `Adresse électronique déjà utilisée par un autre compte`,
  emailNotifications: `Notifications par e-mail`,
  enterOrPasteALink: `Entrez ou collez un lien`,
  enterTheAddressAssociatedWithYourAccount: `Entrez l'adresse associée à votre compte et nous vous enverrons un lien pour réinitialiser votre mot de passe`,
  enterYourPassword: `Entrez votre mot de passe`,
  error: `Erreur`,
  errorPleaseContactCustomerSupport: `Erreur!  Veuillez contacter le service à la clientèle ...`,
  exitWithoutSaving: `Quitter sans enregistrer`,
  extensions: `Extensions`,
  extras: `Extras`,
  fileSizeIsTooBig: `La taille du fichier est trop grande`,
  fileSizeIsTooSmall: `La taille du fichier est trop petite`,
  filter: `Filtre`,
  filterBy: `Filter par`,
  findUser: `Trouver utilisateur`,
  finishSettingUpYourShop: `Terminer la configuration de votre boutique`,
  follow: `Suivre`,
  followers: `Abonnés`,
  following: `Abonnement`,
  followMeOn: `Suivez-moi sur`,
  follows: `Abonnements`,
  forAllOtherInquiriesPleaseContactUsAt: `Pour toute autre demande, veuillez nous contacter à :`,
  forgotPassword: `J'ai oublié mon mot de passe`,
  fromAnimeDotClub: `De anime.club`,
  getDetails: `Plus d'informations`,
  getStarted: `Commencer`,
  guestView: `Vue client`,
  greatNewsYourOrderIsNowInProgress: `Bonne nouvelle ! Votre commande est en cours`,
  harassment: `Harcèlement`,
  haveAnyQuestions: `Avez-vous des questions ?`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> a annulé la commande`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]} n'a pas ajouté de description pour "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} n'a pas encore partagé de détails publics`,
  hate: `Haine`,
  hire: `Embaucher`,
  homepage: `Page d'accueil`,
  howToContactYou: `Comment vous contacter`,
  howToFindYouOnOtherSocialNetworks: `Comment vous trouver sur d'autres réseaux sociaux`,
  iAgreeWith: `Je suis d'accord avec`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Si aucune réponse n'est reçue d'ici ${v[0]}, la commande sera automatiquement marquée comme terminée`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `La hauteur de l'img doit être supérieure ou égale à`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `La largeur de l'img doit être supérieure ou égale à`,
  impersonation: `Usurpation d'identité`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Inclure des mots-clés que les acheteurs utiliseraient probablement pour rechercher un produit comme le vôtre`,
  inProgress: `En cours`,
  introduction: `Introduction `,
  invalidCode: `Code invalide`,
  invalidCurrentPassword: `Mot de passe actuel invalide`,
  invalidDate: `Date invalide`,
  invalidPartAfterAt: `Pièce non valide après @`,
  invalidPartBeforeAt: `Pièce non valide avant @`,
  jobDetails: `Détails du travail`,
  joinAnimeClubCommunity: `Rejoignez la communauté Anime.club avec des milliers de créateurs actifs et de superbes œuvres d'art anime tous les jours`,
  joinChat: `Rejoindre le chat`,
  joinUsOnFacebook: `Rejoignez nous sur Facebook`,
  language: `Langue`,
  lackOfInformation: `Manque d'informations`,
  languages: `Langues`,
  letEveryoneKnowHowToDonateToYou: `Faites savoir à tout le monde comment vous faire un don`,
  letOthersKnowAboutYou: `Faites savoir aux autres qui vous êtes`,
  letsUploadYourFirstProduct: `Téléchargeons votre premier produit`,
  letUsKnowWhatsHappening: `Faites-nous savoir ce qui se passe et nous examinerons la situation`,
  lightDefault: `Thème clair par défaut`,
  lightHighContrast: `Thème clair à fort contraste`,
  likes: `Likes`,
  limit: `Limite`,
  linkCopiedToClipboard: `Lien copié dans le presse-papiers`,
  livesIn: `Vivre dans`,
  loading: `Chargement`,
  location: `Emplacement`,
  logInOrSignUp: `Se connecter ou s'inscrire`,
  logOut: `Se déconnecter`,
  maximumNChars: (...v) => `${v[0]} caractères maximum`,
  maximumNumberOfDaysToCompleteTheOrder: `Nombre maximum de jours pour compléter la commande`,
  maximumQuantity: `Quantité maximale`,
  maxSize: `Taille maximum`,
  menu: `Menu`,
  message: `Message`,
  messages: `Messages`,
  minHeight: `Hauteur minimum`,
  minimumNChars: (...v) => `${v[0]} caractères minimum`,
  minorAbuseOrSexualization: `Abus ou sexualisation mineurs`,
  minWidth: `Largeur minimum`,
  monthly: `Mensuel`,
  moreFrom: (...v) => `Du même ${v[0]}`,
  mustBeNChars: (...v) => `Doit être ${v[0]} caractères`,
  myPayments: `Mes paiements`,
  myProfile: `Mon profil`,
  mySettings: `Mes paramètres`,
  need1Lowercase: `Besoin de 1 minuscule`,
  need1Number: `Besoin de 1 numéro`,
  need1Uppercase: `Besoin de 1 majuscule`,
  needAtLeast1CharacterFromN: (...v) =>
    `Besoin d'au moins 1 caractère de [${v[0]}]`,
  needNCharacter: (...v) => `Besoin de caractère ${v[0]}`,
  newAccount: `Nouveau compte`,
  newArt: `Nouvel art`,
  newArtworks: `Nouvelles œuvres d'art`,
  newBlog: `Nouveau blog`,
  newOrder: `Nouvelle commande`,
  newPassword: `Nouveau mot de passe`,
  newProduct: `Nouveau produit`,
  newsFeed: `Fil d'actualité`,
  next: `Suivant`,
  nextTimeYouAuthenticateYouCouldUseThe: `La prochaine fois que vous vous authentifierez, vous pourrez utiliser le compte connecté, au lieu de l'identifiant et du mot de passe`,
  nightTheme: `Thème sombre`,
  no: `non`,
  noInternetConnection: `Pas de connexion Internet !`,
  nonConsensualIntimateContent: `Contenu intime non consensuel`,
  none: `Aucun`,
  noNotifications: `Aucune notification`,
  noResults: `Aucun résultat`,
  notifications: `Notifications`,
  noActiveOrdersToShow: `Aucune commande active à afficher`,
  notAcceptingOrders: `N'accepte pas les commandes`,
  nsfwContent18Plus: `Contenu NSFW (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `Nombre d'ajustements qu'un client pourrait demander`,
  online: `En ligne`,
  onlyLatinLettersNumbersHyphen: `Seulement des lettres latines, des chiffres, des tirets, des traits de soulignement et des points`,
  onlyNumbers: `Seulement les chiffres`,
  open: `Ouvrir`,
  openDispute: `Ouvrir un litige`,
  openGuestView: `Ouvrir la vue client`,
  openingSoon: `Ouverture prochaine !`,
  openToWork: `Ouvert au travail`,
  optional: `Optionnel`,
  or: `OU`,
  order: `Commande`,
  outOfStock: `En rupture de stock`,
  ordered: (...v) => `Commandé ${v[0]}`,
  orderAgain: `Commander à nouveau`,
  orderDetails: `Détails de la commande`,
  orderConfirmed: `Commande confirmée`,
  orderStatus: `Statut de la commande`,
  orderOptions: `Options de commande`,
  otherReason: `Autre raison`,
  pageNotFound: `Page non trouvée`,
  password: `Mot de passe`,
  payments: `Paiements`,
  personal: `Personnel`,
  personalCircumstances: `Circonstances personnelles`,
  pleaseCheckYour: (...v) => `Veuillez vérifier votre ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Veuillez ne pas partager vos informations privées avec d'autres personnes`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `Veuillez entrer un nombre entre ${v[0]} et ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) =>
    `Veuillez saisir au moins ${v[0]} caractères`,
  pleaseFillOutYourDetails: `Veuillez remplir vos coordonnées`,
  pleaseSignInToYourAccount: `Veuillez vous-connecter à votre compte`,
  platform: `Plateforme`,
  pleaseStartTyping: `Veuillez commencer à taper`,
  pleaseTryAgainOrClick: (...v) => `Veuillez réesayer ou cliquer sur ${v[0]}`,
  pleaseVerifyYourAccount: `Veuillez vérifier votre compte`,
  pressHereTo: `Cliquez ici pour`,
  price: `Prix`,
  privacyPolicy: `Politique de confidentialité`,
  privateInformation: `Informations privées`,
  proceedToCheckout: `Procéder au paiement`,
  product: `Produit`,
  profile: `Profil`,
  prohibitedTransaction: `Transaction interdite`,
  promotions: `Promotions`,
  publicInformation: `Informations publiques`,
  publishOn: (...v) => `Publier sur ${v[0]}`,
  purchases: `Achats`,
  rankings: `Classements`,
  reorderFiles: `Réorganiser les fichiers`,
  report: `Signaler`,
  revisions: `Révisions`,
  sales: `Ventes`,
  save: `Sauvegarder`,
  saveAvatar: `Sauvegarder l'avatar`,
  saveChanges: `Sauvegarder les modifications`,
  selectAnime: `Sélectionner l'anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Sélectionnez un thème unique ou synchronisez avec votre système et passez automatiquement entre les thèmes jour et nuit`,
  selectAvatar: `Sélectionner l'avatar`,
  selectCharacters: `Sélectionner le (s) personnage (s)`,
  seller: `Vendeur`,
  selectFile: `Choisir le dossier`,
  selectTheme: `Sélectionner un thème`,
  selectThumbnail: `Sélectionner la vignette`,
  selfHarmOrSuicide: `Auto-mutilation ou suicide`,
  sendEmail: `Envoyer un courriel`,
  settings: `Paramètres`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `La mise en place d'une boutique est gratuite et ne prend que quelques minutes`,
  share: `Partager`,
  shareYourArtWithTheWorld: `Partagez votre art avec le monde`,
  shareYourStory: `Partagez votre histoire !`,
  sharingPersonalInformation: `Partage d'informations personnelles`,
  shop: `Magasin`,
  shopOrders: `Commandes de la boutique`,
  showLess: `Afficher moins`,
  showMore: `Afficher plus`,
  signIn: `Se connecter`,
  singleTheme: `Thème unique`,
  size: `Taille`,
  skip: `Ignorer`,
  socialMedia: `Médias sociaux`,
  spaceCharacterIsNotAllowed: `Caractère espace n'est pas autorisé`,
  spam: `Spam`,
  submitAReport: `Soumettre un rapport`,
  submitWork: `Soumettre un travail`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Abonnez-vous aux auteurs pour suivre leur progression`,
  successChangedPasswordPleaseSignIn: `Succès ! Mot de passe modifié. Veuillez vous connecter`,
  successCreatedRecord: `Succès ! Record créé !`,
  successUpdatedRecord: `Succès ! Record mis à jour !`,
  supportMeOn: `Soutenez-moi sur`,
  syncWithSystem: `Synchroniser avec le système`,
  tellUsAboutYourself: `Parlez nous de vous`,
  termsAndConditions: `Termes et conditions`,
  termsOfUse: `Conditions d'utilisation`,
  thankYouForReport: `Merci d'avoir contribué à maintenir une communauté en ligne sûre et respectueuse`,
  theLinkIsBrokenOrPageHasBeenRemoved: `Le lien est cassé ou la page a été supprimée`,
  themeMode: `Mode thème`,
  thisIsThePriceYouPropose: `C'est le prix que vous proposez`,
  threateningViolence: `Menace de violence`,
  title: `Titre`,
  timeConstraints: `Contraintes de temps`,
  titleYourExtraService: `Nommez votre service supplémentaire`,
  theMaximumQuantityThatACustomerCanAdd: `La quantité maximale qu'un client peut ajouter`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `La période de révision est limitée à ${v[0]} jours`,
  toHelpTheCreatorCompleteYourOrder: `Pour aider le créateur à compléter votre commande à votre satisfaction, veuillez fournir une description détaillée de ce que vous voulez. Incluez le thème souhaité, le style et les caractéristiques du personnage, ainsi que toute autre spécification importante`,
  today: `Aujourd'hui`,
  toGetWorkRelatedNotifications: `Pour recevoir des notifications liées au travail`,
  total: `Total`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Pour voir ces données, vous devez débloquer @${v[0]}`,
  trademarkViolation: `Violation de marque`,
  typeYourTextHere: `Écrivez votre texte ici ...`,
  unblock: `Débloquer`,
  unblockUser: (...v) => `Débloquer @${v[0]}`,
  unfollow: `Ne plus suivre`,
  unlimited: `Illimité`,
  upload: `Télécharger`,
  uploadNew: `Télécharger un nouveau`,
  uploadNewPost: `Télécharger un nouveau poste`,
  uploadNewProduct: `Télécharger un nouveau produit`,
  username: `Nom d'utilisateur`,
  usernameAlreadyExists: `Ce nom d'utilisateur existe déjà`,
  usernameAndXMoreFollowYou: (...v) =>
    `<b>${v[0]}</b> et ${v[1]} autres vous suivent`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `<b>${v[0]}</b> et ${v[1]} autres aiment votre œuvre d'art`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b> vous suit`,
  usernameLikesYourArt: (...v) => `<b>${v[0]}</b> aime votre art`,
  useThisEmailTo: `Utilisez cet e-mail pour : vous authentifier, recevoir des notifications`,
  valueIsNotTheSame: `La valeur n'est pas la même`,
  verificationCode: `Code de vérification`,
  verifyCode: `Vérifier le code`,
  viewDetails: `Voir les détails`,
  viewReview: `Voir l'avis`,
  viewEveryNotificationOfAGroupSeparately: `Voir chaque notification d'un groupe séparément`,
  visitOurDiscordChannelToGetMoreDetails: `Pour plus d'informations, visitez notre chaîne Discord`,
  weAreOnInstagram: `Nous sommes sur Instagram`,
  weAreWorkingOnIt: `Nous y travaillons`,
  weDoNotDisplayNSFWContentYet: `Nous n'affichons pas encore de contenu NSFW`,
  weekly: `Hebdomadaire`,
  whenYouPurchaseSomethingItWillAppearHere: `Lorsque vous achetez quelque chose, cela apparaîtra ici`,
  weHaveSentTooManyEmails: `Nous avons envoyé trop d'e-mails, veuillez réessayer plus tard ou contacter le service client`,
  welcomeToAnimeClub: `Bienvenue sur Anime.club !`,
  weSentAnEmailTo: `Nous avons envoyé un courriel à :`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Nous vous avons envoyé un nouvel courriel de vérification. Veuillez saisir le code`,
  weAreExcitedToSeeYourProgressKeepItUp: `Nous sommes impatients de voir vos progrès. Continuez comme ça !`,
  weSupportOnlyTheFollowingFileExtensions: `Nous ne prenons en charge que les extensions de fichiers suivantes :`,
  work: `Travail`,
  weWouldLoveToHearFromYou: `Nous aimerions avoir de vos nouvelles`,
  workDescription: `Description du travail`,
  leaveAReview: `Laisser un avis`,
  wrongEmailOrPassword: `E-mail ou mot de passe erroné`,
  yes: `oui`,
  yesterday: `Hier`,
  youReceivedANewOrderFrom: (...v) =>
    `Vous avez reçu une nouvelle commande de <b>${v[0]}</b>`,
  youHaveSuccessfullyCreatedYourShop: `Vous avez créé votre boutique avec succès`,
  youAreAlreadyAuthenticated: `Vous êtes déjà authentifié`,
  youCanAutoPublishToYourSocialMediaAccount: `Vous pouvez publier automatiquement sur votre compte de médias sociaux`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Vous pouvez modifier les types de notifications que vous recevez par e-mail`,
  youCanRequestRemovalOfYourAccount: `Vous pouvez demander la suppression de votre compte avec toutes vos données`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Vous pouvez toujours accéder aux pages précédemment ouvertes`,
  youDidNotSelectAnyChats: `Vous n'avez sélectionné aucun chat`,
  youDidNotUpdateAnyValues: `Vous n'avez mis à jour aucune valeur`,
  youDoNotHaveAnyChats: `Vous n'avez aucun chat disponible`,
  youHaveNotSetAPassword: `Vous n'avez pas défini de mot de passe`,
  youHaveNotSharedAnythingYet: `Vous n'avez encore rien partagé`,
  youHaveReachedTheMaximumNumberOfFiles: `Vous avez atteint le nombre maximum de fichiers`,
  kindlyHoldOnForTheBuyersReview: `Veuillez patienter pour l'avis de l'acheteur sur la commande.`,
  yourAccountIsVerifiedPleaseSignIn: `Votre compte est vérifié.  Veuillez vous connecter`,
  yourAccountWillBeRemoved: (...v) => `Votre compte sera supprimé ${v[0]}`,
  youHaveNoPurchases: `Vous n'avez aucun achat`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Pourriez-vous fournir la raison de l'annulation`,
  yourFeedbackWouldBeGreatlyAppreciated: `Vos commentaires seraient grandement appréciés`,
  yourArts: `Vos arts`,
  yourAvatar: `Votre avatar`,
  yourBlog: `Votre blog`,
  yourFansAreWaiting: `Vos fans attendent`,
  yourFeedIsEmpty: `votre flux est vide`,
  yourSessionHasExpiredPleaseSignInAgain: `Votre session a expiré, veuillez vous reconnecter`,
}
