export const text: text = {
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `(en) Anime.club uses ${v[0]} to get you paid quickly and keep your personal and payment information secure`,
  clickTheButtonBelowToOpenYourStripeDashboard: `(en) Click the button below to open your Stripe dashboard and view your account details`,
  visitStripeDashboard: `(en) Visit Stripe dashboard`,
  files: `(en) Files`,
  prohibitedTransaction: `(en) Prohibited transaction`,
  uploadTheFilesYourBuyerWillGet: `(en) Upload the files your <b>buyer will get</b>`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `(en) Make sure everything is ready to go — no edits after publishing`,
  filesForTheBuyer: `(en) Files for the buyer`,
  filesForPreview: `(en) Files for preview`,
  needsYourReview: `(en) Needs Your Review`,
  awaitingSellersResponse: `(en) Awaiting seller's response`,
  buyersRequest: `(en) Buyer's request`,
  comments: `(en) Comments`,
  awaitingClientReview: `(en) Awaiting Client Review`,
  copy: `(en) Copy`,
  thankYouForYourPurchase: `(en) Thank you for your purchase!`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `(en) Great news! ${v[0]} purchased your item. Time to celebrate!`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `(en) @${v[0]} hasn't listed any products for sale yet`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `(en) @${v[0]} hasn’t added anything to their portfolio yet`,
  hideListing: `(en) Hide listing`,
  uploadUpToNumberFiles: (...v) => `(en) Upload up to <b>${v[0]}</b> files`,
  supportedFormats: `(en) Supported formats:`,
  minimumDimensions: (...v) => `(en) Minimum size: ${v[0]}×${v[1]} pixels`,
  maximumFileSize: (...v) => `(en) Maximum file size: <b>${v[0]}</b> per file`,
  thisListingWontBeVisibleToBuyersAnymore: `(en) This listing won’t be visible to buyers anymore — but you can show it again whenever you’re ready`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `(en) Buyers will be able to see this listing. You can hide it again anytime`,
  listingHiddenFromBuyers: `(en) Listing hidden from buyers`,
  listingIsNowVisibleToBuyers: `(en) Listing is now visible to buyers`,
  showListing: `(en) Show listing`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `(en) If there's no response by ${v[0]}, the order will be canceled automatically`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `(en) If no reply is received by ${v[0]}, you'll automatically receive a full refund`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `(en) If you miss the deadline, the buyer can cancel the order for a full refund, and any associated Stripe fees will be deducted from your payout.`,
  addAComment: `(en) Add a comment`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `(en) These rules are provided by the seller and apply only to this item`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `(en) If you have questions or concerns, please contact the seller directly`,
  platformPoliciesMayStillApply: `(en) Platform policies may still apply`,
  copiedToClipboard: `(en) Copied to clipboard`,
  uploadedFilesLocked: `(en) You uploaded these files when you created the post. They're now locked but still visible below`,
  new: `(en) New`,
  createPersonalizedWorkTailoredToEachRequest: `(en) Create personalized work tailored to each request`,
  offerDigitalProducts: `(en) Offer digital products that buyers can access right away`,
  instantDownload: `(en) Instant Download`,
  customWork: `(en) Custom Work`,
  allListings: `(en) All Listings`,
  newCommission: `(en) New commission`,
  noOrders: `(en) No orders`,
  buyNow: `(en) Buy now`,
  attachedFiles: `(en) Attached files`,
  numFilesIncluded: (...v) => `(en) <b>${v[0]}</b> file(s) included`,
  tellTheBuyersWhatTheyWillGet: `(en) Tell buyers exactly what they will get — for example, the number of illustrations, file formats, or canvas specs like resolution and DPI`,
  beSpecificAboutTheContent: `(en) Be specific about the content (e.g. number of files, formats, canvas resolution)`,
  mentionYourDeliveryTimeInDays: `(en) Mention your <b>delivery time</b> (in days)`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `(en) Let buyers know if you offer <b>revisions</b>, and how many`,
  listAnyContentOrRequestsYouDontAccept: `(en) List any content or requests you <b>don't accept</b> (e.g. NSFW, political, religious, or offensive material)`,
  offerOptionalExtras: `(en) Offer optional extras like <b>rush delivery</b>, an <b>extra character</b>, or a <b>detailed background</b>`,
  extrasHelpBoostIncome: `(en) Extras help buyers customize their order and can boost your income`,
  pleaseAllowPopups: `(en) Please allow popups`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `(en) You'll be able to download your files immediately after purchase—no waiting required!`,
  orderAOneOfAKindCustomPieceCraftedToMatchYourVision: `(en) Order a one-of-a-kind custom piece, crafted to match your vision`,
  youAreCoveredIfThereIsAProblem: `(en) You're covered! If there's a problem and the dispute is valid, you'll get 100% of your money back`,
  artGallery: `(en) Art Gallery`,
  commission: `(en) Commission`,
  commissions: `(en) Commissions`,
  digitalDownloads: `(en) Digital Downloads`,
  changesSaved: `(en) Changes saved!`,
  setUpStripeAccountToGetPaidWithAnimeClub: `(en) Set up a Stripe account to get paid with Anime.club`,
  sellerTermsOfService: `(en) Seller Terms of Service`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `(en) Describe what’s included and what the buyer can expect after purchase`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `(en) The reason you provide for cancelling this order will be shared with the buyer`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `(en) Optionally, you can add a description to share more about your creation`,
  pleaseProvideATitleForYourArtwork: `(en) Please provide a title for your artwork`,
  usernameStartedFollowingYou: (...v) => `(en) <b>${v[0]}</b> started following you`,
  usernameLeftAReaction: (...v) => `(en) <b>${v[0]}</b> left a reaction`,
  vote: `(en) Vote`,
  tapAddToCreateOne: `(en) Tap “Add” to create one`,
  reply: `(en) Reply`,
  replyToUsername: (...v) => `(en) Reply to ${v[0]}`,
  numOfReplies: (...v) => `(en) ${v[0]} replies`,
  replies: `(en) Replies`,
  youCanChooseFromTheListOrEnterACustomReason: `(en) You can choose from the list or enter a custom reason`,
  _colon: ` : `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: ` ! `,
  _question: ` ? `,
  _space: ` `,
  _hyphen: `- `,
  about: `Sur`,
  accept: `Accepter`,
  acceptOrder: `Accepter la commande`,
  acceptTheOrder: `Accepter la commande`,
  accountManagment: `Gestion du compte`,
  account: `Compte`,
  accountDeleted: `Compte supprimé`,
  animeShopBuyAndSellProducts: `Boutique d'anime - acheter et vendre des produits`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `Les images générées par IA et les filtres de réseaux neuronaux sont interdits`,
  accountActivation: `Activation de compte`,
  accountAlreadyExists: `Compte existe déjà`,
  accountDoesNotExist: `Compte n'existe pas`,
  accountRemoval: `Suppression de compte`,
  add: `Ajouter`,
  addArt: `Ajouter une illustration`,
  addBlog: `Ajouter un blog`,
  additionalResources: `Ressources supplémentaires`,
  addMoreProductsToYourShop: `Ajoutez plus de produits à votre boutique`,
  addMore: `Ajouter plus`,
  addNewArt: `Ajouter un nouvel art`,
  addSignInVia: `Ajouter une connexion via`,
  addToCart: `Ajouter au panier`,
  advancedOptions: `Options avancées`,
  all: `Tout`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `Tous les fichiers que vous téléchargez ici seront disponibles pour l'acheteur`,
  alreadySignedIn: `Déjà connecté`,
  amount: `Montant`,
  amountShouldNotBeLessThan: (...v) => `Le montant ne doit pas être inférieur à ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `L'art de l'anime par des artistes du monde entier. L'art est organisé pour être lié à l'anime. La sélection d'art est une liste infinie des meilleurs dessins animés`,
  animeArtSubscribeToArtistsLikeAndCreate: `L'art de l'anime - abonnez-vous à des artistes, aimez et créez des collections`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - la première plate-forme à proposer aux artistes des paiements à partir de vues via Google AdSense. Soutenez les artistes en affichant leur contenu ou commencez à gagner des vues`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - afficher, publier et gagner du contenu d'anime`,
  animeCommunity: `Communauté d'anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club ne demande jamais vos informations privées`,
  animeSocialNetwork: `Réseau social anime`,
  announcements: `Annonces`,
  apply: `Appliquer`,
  appSettings: `Paramètres de l'application`,
  appsVersionIs: `La version de l'application est`,
  areYouSureYouWantTo: `Êtes-vous sûr de vouloir`,
  art: `Art`,
  artAssociatedWithAnime: `Art associé à l'anime`,
  artBy: (...v) => `Art par ${v[0]}`,
  artCannotBeChanged: `L'art ne peut pas être changé`,
  artworksAvailableToView: (...v) => `${v[0]} œuvres d'art disponibles à la visualisation`,
  authenticationFailed: `Authentification échouée`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `La publication automatique sur Instagram n'est disponible que pour les comptes professionnels Instagram`,
  attentionYourOrderHasBeenDisputed: `Attention ! Votre commande a été contestée. Veuillez vérifier les détails`,
  back: `Arrière`,
  basePrice: `Prix de base`,
  bigAppreciationToTheSellerForTheHardWork: `Grande appréciation au vendeur pour le travail acharné`,
  block: `Bloquer`,
  buyerReviewedTheOrder: `L'acheteur a évalué la commande`,
  buyerHasNotLeftAReviewYet: `L'acheteur n'a pas encore laissé d'avis`,
  feedbackReceived: `Retour reçu !`,
  blockUser: (...v) => `Bloquer @${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `Avant d'accepter, veuillez examiner attentivement la demande de l'acheteur`,
  blog: `Blog`,
  bookmarks: `Signets`,
  browseArt: `Parcourir l'art`,
  browseShop: `Parcourir la boutique`,
  buyer: `Acheteur`,
  cancel: `Annuler`,
  canceled: `Annulé`,
  cancelOrder: `Annuler la commande`,
  cannotStartWithChars: `Impossible de démarrer avec s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Changer`,
  checkOutMyShop: `Découvrez ma boutique`,
  checkOrderStatus: `Vérifier le statut de la commande`,
  changeArt: `Changer d'art`,
  changeAvatar: `Changer d'avatar`,
  changeEmail: `Changer d'email`,
  changePassword: `Changer le mot de passe`,
  chooseExistingChatOrStartANewOne: `Sélectionnez un chat existant ou créez-en un nouveau`,
  city: `Ville`,
  clearAll: `Tout désélectionner`,
  close: `Fermer`,
  colorTheme: `Thème de couleur`,
  comingSoon: `À venir …`,
  commercialUseAllowed: `Utilisation commerciale autorisée`,
  commercialUseAllowsBuyersToUseYourProduct: `L'utilisation commerciale permet aux acheteurs d'utiliser votre produit à des fins commerciales, comme la vente ou la promotion de leurs services`,
  community: `Communauté`,
  completed: `Terminé`,
  confirmAccount: `Confirmer le compte`,
  confirmOrder: `Confirmer la commande`,
  confirmPassword: `Confirmez le mot de passe`,
  connectWithUsOn: `Connectez-vous avec nous sur`,
  contactInformation: `Informations de contact`,
  contactSeller: `Contacter le vendeur`,
  contactSupport: `Contacter le support`,
  contactUs: `Contactez-nous`,
  continue: `Continuer`,
  contractTitle: `Titre du contrat`,
  congratulations: `Félicitations !`,
  congratulationsOnSuccessfullyCompletingYourOrder: `Félicitations pour avoir terminé votre commande avec succès !`,
  copyrightViolation: `Violation de droits d'auteur`,
  couldNotCreateANewRecord: `Impossible de créer un nouvel enregistrement`,
  country: `Pays`,
  cover: `Couverture`,
  createANewAccountFailed: `Échec de la création d'un nouveau compte a échoué`,
  createExtrasForYourProduct: `Créer des extras pour votre produit`,
  createNewAccount: `Créer un nouveau compte`,
  createAShopWithStripe: `Créer une boutique avec Stripe`,
  createdBy: `Créé par`,
  currentPassword: `Mot de passe actuel`,
  daily: `Quotidien`,
  darkDefault: `Thème sombre par défaut`,
  darkHighContrast: `Thème sombre à fort contraste`,
  dayTheme: `Thème de jour`,
  delete: `Supprimer`,
  deleteShop: `Supprimer la boutique`,
  deleteAccount: `Supprimer le compte`,
  deleteArt: `Supprimer l'art`,
  decline: `Refuser`,
  deletePost: `Supprimer le message`,
  deleteProduct: `Supprimer le produit`,
  download: `Télécharger`,
  downloadThemBelow: `Téléchargez-les ci-dessous`,
  deliveryTime: `Délai de livraison`,
  describeTheDetailsOfYourExtra: `Décrivez les détails de votre extra`,
  description: `Description`,
  details: `Détails`,
  didntReceiveEmail: `Vous n'avez pas reçu le courriel ?`,
  displayName: `Nom d'affichage`,
  disputed: `Contesté`,
  donations: `Dons`,
  done: `Terminé`,
  dragAndDropOrSelectFiles: `Glisser-déposer ou sélectionner des fichiers`,
  drawingContest: `Concours de dessin`,
  dueDate: `Date d'échéance`,
  earlier: `Plus tôt`,
  earningFromArts: `Gagner des arts`,
  edit: `Modifier`,
  editPost: `Editer le poste`,
  editProfile: `Editer le profil`,
  editTranslations: `Modifier les traductions`,
  email: `Courriel`,
  emailAlreadyUsedByAnotherAccount: `Adresse électronique déjà utilisée par un autre compte`,
  emailNotifications: `Notifications par e-mail`,
  enterOrPasteALink: `Entrez ou collez un lien`,
  enjoyYourPurchase: `Profitez de votre achat ! 😊`,
  enterTheAddressAssociatedWithYourAccount: `Entrez l'adresse associée à votre compte et nous vous enverrons un lien pour réinitialiser votre mot de passe`,
  enterYourPassword: `Entrez votre mot de passe`,
  error: `Erreur`,
  errorPleaseContactCustomerSupport: `Erreur!  Veuillez contacter le service à la clientèle ...`,
  exitWithoutSaving: `Quitter sans enregistrer`,
  extensions: `Extensions`,
  extras: `Extras`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `Les extras sont des options facultatives pour améliorer votre produit`,
  fileSizeIsTooBig: `La taille du fichier est trop grande`,
  fileSizeIsTooSmall: `La taille du fichier est trop petite`,
  filter: `Filtre`,
  filterBy: `Filter par`,
  findUser: `Trouver utilisateur`,
  finishSettingUpYourShop: `Terminer la configuration de votre boutique`,
  follow: `Suivre`,
  followers: `Abonnés`,
  following: `Abonnement`,
  followMeOn: `Suivez-moi sur`,
  follows: `Abonnements`,
  forAllOtherInquiriesPleaseContactUsAt: `Pour toute autre demande, veuillez nous contacter à :`,
  forgotPassword: `J'ai oublié mon mot de passe`,
  fromAnimeDotClub: `De anime.club`,
  getDetails: `Plus d'informations`,
  getStarted: `Commencer`,
  guestView: `Vue client`,
  greatNewsYourOrderIsNowInProgress: `Bonne nouvelle ! Votre commande est en cours`,
  harassment: `Harcèlement`,
  haveAnyQuestions: `Avez-vous des questions ?`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> a annulé la commande`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> a soumis le travail`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]} n'a pas ajouté de description pour "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]} n'a pas encore partagé de détails publics`,
  hate: `Haine`,
  hereAreAFewWaysToGetThingsRolling: `Voici quelques façons de démarrer`,
  hire: `Embaucher`,
  homepage: `Page d'accueil`,
  howToContactYou: `Comment vous contacter`,
  howToFindYouOnOtherSocialNetworks: `Comment vous trouver sur d'autres réseaux sociaux`,
  iAgreeWith: `Je suis d'accord avec`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Si aucune réponse n'est reçue d'ici ${v[0]}, la commande sera automatiquement marquée comme terminée`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `La hauteur de l'img doit être supérieure ou égale à`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `La largeur de l'img doit être supérieure ou égale à`,
  impersonation: `Usurpation d'identité`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Inclure des mots-clés que les acheteurs utiliseraient probablement pour rechercher un produit comme le vôtre`,
  inProgress: `En cours`,
  introduction: `Introduction `,
  includes: `Inclut`,
  invalidCode: `Code invalide`,
  invalidCurrentPassword: `Mot de passe actuel invalide`,
  invalidDate: `Date invalide`,
  invalidPartAfterAt: `Pièce non valide après @`,
  invalidPartBeforeAt: `Pièce non valide avant @`,
  jobDetails: `Détails du travail`,
  joinAnimeClubCommunity: `Rejoignez la communauté Anime.club avec des milliers de créateurs actifs et de superbes œuvres d'art anime tous les jours`,
  joinChat: `Rejoindre le chat`,
  joinUsOnFacebook: `Rejoignez nous sur Facebook`,
  language: `Langue`,
  lackOfInformation: `Manque d'informations`,
  languages: `Langues`,
  letEveryoneKnowHowToDonateToYou: `Faites savoir à tout le monde comment vous faire un don`,
  letOthersKnowAboutYou: `Faites savoir aux autres qui vous êtes`,
  letsUploadYourFirstProduct: `Téléchargeons votre premier produit`,
  letUsKnowWhatsHappening: `Faites-nous savoir ce qui se passe et nous examinerons la situation`,
  lightDefault: `Thème clair par défaut`,
  lightHighContrast: `Thème clair à fort contraste`,
  likes: `Likes`,
  limit: `Limite`,
  livesIn: `Vivre dans`,
  loading: `Chargement`,
  location: `Emplacement`,
  logInOrSignUp: `Se connecter ou s'inscrire`,
  logOut: `Se déconnecter`,
  maximumNChars: (...v) => `${v[0]} caractères maximum`,
  maximumNumberOfDaysToCompleteTheOrder: `Nombre maximum de jours pour compléter la commande`,
  maximumQuantity: `Quantité maximale`,
  maxSize: `Taille maximum`,
  menu: `Menu`,
  message: `Message`,
  messages: `Messages`,
  minHeight: `Hauteur minimum`,
  minimumNChars: (...v) => `${v[0]} caractères minimum`,
  minorAbuseOrSexualization: `Abus ou sexualisation mineurs`,
  makeSureToIncludeClearInstructions: `Assurez-vous d'inclure des instructions claires sur la façon d'utiliser chaque référence`,
  makeSureYouFullyUnderstandTheRequirements: `Assurez-vous de bien comprendre les exigences et de pouvoir terminer la commande dans les délais`,
  makeSureYourProductsArePricedCompetitively: `Assurez-vous que vos produits sont à des prix compétitifs`,
  minWidth: `Largeur minimum`,
  monthly: `Mensuel`,
  moreFrom: (...v) => `Du même ${v[0]}`,
  mustBeNChars: (...v) => `Doit être ${v[0]} caractères`,
  myPayments: `Mes paiements`,
  myProfile: `Mon profil`,
  mySettings: `Mes paramètres`,
  need1Lowercase: `Besoin de 1 minuscule`,
  need1Number: `Besoin de 1 numéro`,
  need1Uppercase: `Besoin de 1 majuscule`,
  needAtLeast1CharacterFromN: (...v) => `Besoin d'au moins 1 caractère de [${v[0]}]`,
  needNCharacter: (...v) => `Besoin de caractère ${v[0]}`,
  newAccount: `Nouveau compte`,
  newArt: `Nouvel art`,
  newArtworks: `Nouvelles œuvres d'art`,
  newBlog: `Nouveau blog`,
  newOrder: `Nouvelle commande`,
  newPassword: `Nouveau mot de passe`,
  newProduct: `Nouveau produit`,
  newsFeed: `Fil d'actualité`,
  next: `Suivant`,
  nextTimeYouAuthenticateYouCouldUseThe: `La prochaine fois que vous vous authentifierez, vous pourrez utiliser le compte connecté, au lieu de l'identifiant et du mot de passe`,
  nightTheme: `Thème sombre`,
  no: `non`,
  noInternetConnection: `Pas de connexion Internet !`,
  nonConsensualIntimateContent: `Contenu intime non consensuel`,
  none: `Aucun`,
  noNotifications: `Aucune notification`,
  noResults: `Aucun résultat`,
  noReviewsJustYet: `Pas encore d'avis`,
  notifications: `Notifications`,
  noActiveOrdersToShow: `Aucune commande active à afficher`,
  notAcceptingOrders: `N'accepte pas les commandes`,
  noSalesYetNoWorries: `Pas encore de ventes ? Pas d'inquiétude, vous débutez seulement`,
  nsfwContent18Plus: `Contenu NSFW (18+)`,
  NSFWIndicatesAdultContent: `18+ NSFW indique un contenu pour adultes. Cochez ce champ uniquement si votre produit est destiné à un public mature`,
  numberOfAdjustmentsAClientCouldRequest: `Nombre d'ajustements qu'un client pourrait demander`,
  online: `En ligne`,
  onlyLatinLettersNumbersHyphen: `Seulement des lettres latines, des chiffres, des tirets, des traits de soulignement et des points`,
  onlyNumbers: `Seulement les chiffres`,
  onlyYouCanSeeWhatYouveSaved: `Vous seul pouvez voir ce que vous avez enregistré`,
  open: `Ouvrir`,
  openDispute: `Ouvrir un litige`,
  openGuestView: `Ouvrir la vue client`,
  openingSoon: `Ouverture prochaine !`,
  openToWork: `Ouvert au travail`,
  optional: `Optionnel`,
  requestDetails: `Détails de la demande`,
  or: `OU`,
  order: `Commande`,
  outOfStock: `En rupture de stock`,
  ordered: (...v) => `Commandé ${v[0]}`,
  orderAgain: `Commander à nouveau`,
  orderDetails: `Détails de la commande`,
  orderConfirmed: `Commande confirmée`,
  orderCompleted: `Commande terminée 🎉`,
  orderStatus: `Statut de la commande`,
  orderOptions: `Options de commande`,
  otherReason: `Autre raison`,
  pageNotFound: `Page non trouvée`,
  password: `Mot de passe`,
  payments: `Paiements`,
  personal: `Personnel`,
  personalCircumstances: `Circonstances personnelles`,
  pleaseCheckYour: (...v) => `Veuillez vérifier votre ${v[0]}`,
  pleaseRateYourOrder: `Veuillez évaluer votre commande`,
  feelFreeToShareReferenceImagesAndMaterials: `N'hésitez pas à partager des images de référence et des matériaux pour aider l'artiste à créer votre œuvre`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Veuillez ne pas partager vos informations privées avec d'autres personnes`,
  pleaseEnterANumberBetweenXandX: (...v) => `Veuillez entrer un nombre entre ${v[0]} et ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `Veuillez saisir au moins ${v[0]} caractères`,
  pleaseFillOutYourDetails: `Veuillez remplir vos coordonnées`,
  pleaseFixTheErrorsBeforeSubmitting: `Veuillez corriger les erreurs avant de soumettre`,
  pleaseSignInToYourAccount: `Veuillez vous-connecter à votre compte`,
  platform: `Plateforme`,
  pleaseStartTyping: `Veuillez commencer à taper`,
  pleaseTakeAMomentToReviewTheOrder: `Veuillez prendre un moment pour examiner la commande`,
  pleaseReviewTheBuyersReferenceFiles: `Veuillez examiner les fichiers de référence de l'acheteur et les suivre comme indiqué dans la description de la commande`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `Veuillez examiner attentivement les détails avant de continuer`,
  pleaseRespondToTheOrderBy: (...v) => `Veuillez répondre à la commande avant le ${v[0]}`,
  pleaseTryAgainOrClick: (...v) => `Veuillez réesayer ou cliquer sur ${v[0]}`,
  pleaseVerifyYourAccount: `Veuillez vérifier votre compte`,
  pressHereTo: `Cliquez ici pour`,
  price: `Prix`,
  payouts: `Paiements`,
  privacyPolicy: `Politique de confidentialité`,
  privateInformation: `Informations privées`,
  proceedToCheckout: `Procéder au paiement`,
  product: `Produit`,
  itemReviews: `Avis sur l'article`,
  portfolio: `Portfolio`,
  profile: `Profil`,
  promotions: `Promotions`,
  publicInformation: `Informations publiques`,
  publishOn: (...v) => `Publier sur ${v[0]}`,
  purchases: `Achats`,
  rankings: `Classements`,
  reorderFiles: `Réorganiser les fichiers`,
  report: `Signaler`,
  review: `Avis`,
  rules: `Règles`,
  reviews: `Avis`,
  numOfReviews: (...v) => `Avis : ${v[0]} `,
  reviewed: `Évalué`,
  reviewTitle: `Titre de l'avis`,
  reason: `Raison`,
  revisions: `Révisions`,
  includesXRevisionS: (...v) => `Inclut ${v[0]} révision(s)`,
  sales: `Ventes`,
  save: `Sauvegarder`,
  saveAvatar: `Sauvegarder l'avatar`,
  saveChanges: `Sauvegarder les modifications`,
  selectAnime: `Sélectionner l'anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Sélectionnez un thème unique ou synchronisez avec votre système et passez automatiquement entre les thèmes jour et nuit`,
  selectAvatar: `Sélectionner l'avatar`,
  selectCharacters: `Sélectionner le (s) personnage (s)`,
  seller: `Vendeur`,
  selectFile: `Choisir le dossier`,
  selectTheme: `Sélectionner un thème`,
  selectThumbnail: `Sélectionner la vignette`,
  selfHarmOrSuicide: `Auto-mutilation ou suicide`,
  sendEmail: `Envoyer un courriel`,
  settings: `Paramètres`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `La mise en place d'une boutique est gratuite et ne prend que quelques minutes`,
  share: `Partager`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `Partagez vos règles et les types de demandes que vous n'acceptez pas`,
  shareYourShopOnSocialMedia: `Partagez votre boutique sur les réseaux sociaux`,
  shareYourFavoritePiecesOn: (...v) => `Partagez vos œuvres préférées sur ${v[0]}`,
  shareYourArtWithTheWorld: `Partagez votre art avec le monde`,
  shareYourStory: `Partagez votre histoire !`,
  sharingPersonalInformation: `Partage d'informations personnelles`,
  shop: `Magasin`,
  shopReviews: `Avis sur la boutique`,
  shopOrders: `Commandes de la boutique`,
  showLess: `Afficher moins`,
  showMore: `Afficher plus`,
  signIn: `Se connecter`,
  singleTheme: `Thème unique`,
  size: `Taille`,
  skip: `Ignorer`,
  socialMedia: `Médias sociaux`,
  spaceCharacterIsNotAllowed: `Caractère espace n'est pas autorisé`,
  spam: `Spam`,
  yourFavoritesWillShowUpHereAddSome: `Vos favoris apparaîtront ici. Ajoutez-en !`,
  submitAReport: `Soumettre un rapport`,
  submitWork: `Soumettre un travail`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Abonnez-vous aux auteurs pour suivre leur progression`,
  successChangedPasswordPleaseSignIn: `Succès ! Mot de passe modifié. Veuillez vous connecter`,
  successCreatedRecord: `Succès ! Record créé !`,
  successfullyDownloaded: `Téléchargé avec succès !`,
  successfullyUploaded: `Téléchargé avec succès !`,
  supportMeOn: `Soutenez-moi sur`,
  syncWithSystem: `Synchroniser avec le système`,
  tellUsAboutYourself: `Parlez nous de vous`,
  termsAndConditions: `Termes et conditions`,
  termsOfUse: `Conditions d'utilisation`,
  thankYouForReport: `Merci d'avoir contribué à maintenir une communauté en ligne sûre et respectueuse`,
  thankYouForYourReview: `Merci pour votre avis !`,
  theLinkIsBrokenOrPageHasBeenRemoved: `Le lien est cassé ou la page a été supprimée`,
  themeMode: `Mode thème`,
  thisIsThePriceYouPropose: `C'est le prix que vous proposez`,
  thisFieldIsOptional: `Ce champ est facultatif`,
  thisCannotBeUndone: `Ceci ne peut pas être annulé`,
  ensureYouveUploadedTheFinalVersion: `Assurez-vous d'avoir téléchargé la version finale avant de soumettre`,
  threateningViolence: `Menace de violence`,
  title: `Titre`,
  timeConstraints: `Contraintes de temps`,
  titleYourExtraService: `Nommez votre service supplémentaire`,
  theMaximumQuantityThatACustomerCanAdd: `La quantité maximale qu'un client peut ajouter`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `La période de révision est limitée à ${v[0]} jours`,
  toHelpTheCreatorCompleteYourOrder: `Pour aider le créateur à compléter votre commande à votre satisfaction, veuillez fournir une description détaillée de ce que vous voulez. Incluez le thème souhaité, le style et les caractéristiques du personnage, ainsi que toute autre spécification importante`,
  today: `Aujourd'hui`,
  toGetWorkRelatedNotifications: `Pour recevoir des notifications liées au travail`,
  total: `Total`,
  toViewThisDataYouNeedToUnblock: (...v) => `Pour voir ces données, vous devez débloquer @${v[0]}`,
  trademarkViolation: `Violation de marque`,
  typeYourTextHere: `Écrivez votre texte ici ...`,
  theSellerHasUploadedTheseFilesForYou: `Le vendeur a téléchargé ces fichiers pour vous`,
  unblock: `Débloquer`,
  unblockUser: (...v) => `Débloquer @${v[0]}`,
  unfollow: `Ne plus suivre`,
  unlimited: `Illimité`,
  upload: `Télécharger`,
  uploadNew: `Télécharger un nouveau`,
  uploadNewPost: `Télécharger un nouveau poste`,
  uploadNewProduct: `Télécharger un nouveau produit`,
  username: `Nom d'utilisateur`,
  pleaseUploadOnlyFinishedWorkHere: `Veuillez ne télécharger ici que le travail terminé`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `Tous les fichiers en cours doivent être téléchargés dans les messages`,
  usernameAlreadyExists: `Ce nom d'utilisateur existe déjà`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> et ${v[1]} autres vous suivent`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b> et ${v[1]} autres ont réagi`,
  useThisEmailTo: `Utilisez cet e-mail pour : vous authentifier, recevoir des notifications`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v: string[]) =>
    `Malheureusement, ${v[0]} a dû annuler cette commande`,
  valueIsNotTheSame: `La valeur n'est pas la même`,
  verificationCode: `Code de vérification`,
  verifyCode: `Vérifier le code`,
  viewDetails: `Voir les détails`,
  viewReview: `Voir l'avis`,
  viewEveryNotificationOfAGroupSeparately: `Voir chaque notification d'un groupe séparément`,
  visitOurDiscordChannelToGetMoreDetails: `Pour plus d'informations, visitez notre chaîne Discord`,
  weAreOnInstagram: `Nous sommes sur Instagram`,
  weAreWorkingOnIt: `Nous y travaillons`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `Bravo ! Le travail a été terminé avec succès`,
  weDoNotDisplayNSFWContentYet: `Nous n'affichons pas encore de contenu NSFW`,
  weekly: `Hebdomadaire`,
  whenYouPurchaseSomethingItWillAppearHere: `Lorsque vous achetez quelque chose, cela apparaîtra ici`,
  weHaveSentTooManyEmails: `Nous avons envoyé trop d'e-mails, veuillez réessayer plus tard ou contacter le service client`,
  welcomeToAnimeClub: `Bienvenue sur Anime.club !`,
  weSentAnEmailTo: `Nous avons envoyé un courriel à :`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Nous vous avons envoyé un nouvel courriel de vérification. Veuillez saisir le code`,
  weAreExcitedToSeeYourProgressKeepItUp: `Nous sommes impatients de voir vos progrès. Continuez comme ça !`,
  weSupportOnlyTheFollowingFileExtensions: `Nous ne prenons en charge que les extensions de fichiers suivantes :`,
  work: `Travail`,
  weWouldLoveToHearFromYou: `Nous aimerions avoir de vos nouvelles`,
  workDescription: `Description du travail`,
  leaveAReview: `Laisser un avis`,
  wrongEmailOrPassword: `E-mail ou mot de passe erroné`,
  yes: `oui`,
  yesterday: `Hier`,
  youReceivedANewOrderFrom: (...v) => `Vous avez reçu une nouvelle commande de <b>${v[0]}</b>`,
  youReceivedAReview: `Vous avez reçu un avis`,
  youHaveSuccessfullyCreatedYourShop: `Vous avez créé votre boutique avec succès`,
  youAreAlreadyAuthenticated: `Vous êtes déjà authentifié`,
  youCanAutoPublishToYourSocialMediaAccount: `Vous pouvez publier automatiquement sur votre compte de médias sociaux`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Vous pouvez modifier les types de notifications que vous recevez par e-mail`,
  youCanRequestRemovalOfYourAccount: `Vous pouvez demander la suppression de votre compte avec toutes vos données`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `Vos retours guident les acheteurs et aident les vendeurs à offrir de meilleurs produits`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Vous pouvez toujours accéder aux pages précédemment ouvertes`,
  youDidNotSelectAnyChats: `Vous n'avez sélectionné aucun chat`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `Vous verrez les avis ici une fois que les acheteurs auront partagé leur expérience`,
  youDidNotUpdateAnyValues: `Vous n'avez mis à jour aucune valeur`,
  youDoNotHaveAnyChats: `Vous n'avez aucun chat disponible`,
  youHaveNotSetAPassword: `Vous n'avez pas défini de mot de passe`,
  youHaveNotSharedAnythingYet: `Vous n'avez encore rien partagé`,
  youHaveReachedTheMaximumNumberOfFiles: `Vous avez atteint le nombre maximum de fichiers`,
  kindlyHoldOnForTheBuyersReview: `Veuillez patienter pour l'avis de l'acheteur sur la commande.`,
  yourAccountIsVerifiedPleaseSignIn: `Votre compte est vérifié.  Veuillez vous connecter`,
  yourAccountWillBeRemoved: (...v) => `Votre compte sera supprimé ${v[0]}`,
  youHaveNoPurchases: `Vous n'avez aucun achat`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Pourriez-vous fournir la raison de l'annulation`,
  yourArts: `Vos arts`,
  youCanceledTheOrder: `Vous avez annulé la commande`,
  yourAvatar: `Votre avatar`,
  yourBlog: `Votre blog`,
  yourFansAreWaiting: `Vos fans attendent`,
  yourFeedIsEmpty: `votre flux est vide`,
  yourSessionHasExpiredPleaseSignInAgain: `Votre session a expiré, veuillez vous reconnecter`,
}
