export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Über`,
  accept: `Akzeptieren`,
  accountActivation: `Kontoaktivierung`,
  accountAlreadyExists: `Konto existiert bereits`,
  accountDoesNotExist: `Konto existiert nicht`,
  add: `Hinzufügen`,
  addArt: `Kunst hinzufügen`,
  addBlog: `Blog hinzufügen`,
  addedNAgo: (n) => `Vor ${n} hinzugefügt`,
  addNewArt: `Neue Kunst hinzufügen`,
  addPreview: `Vorschau hinzufügen`,
  animeArtByArtistsFromAllOverTheWorld: `Kunst des Anime von Künstlern aus aller Welt. Kunst ist kuratiert, um mit Anime in Verbindung zu stehen. Die Kunstauswahl ist eine unendliche Liste der besten Anime-Kunst`,
  animeArtSubscribeToArtistsLikeAndCreate: `Kunst des Anime - Abonnieren Sie Künstler wie und erstellen Sie eine Sammlung`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - die erste Plattform, die Künstlern Zahlungen aus Ansichten über Google AdSense anbietet. Unterstützen Sie Künstler, indem Sie ihre Inhalte anzeigen oder mit Ansichten verdienen`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - Anzeigen, Posten und Verdienen von Anime-Inhalten`,
  animeCommunity: `Gemeinschaft von Anime`,
  animeOnly: `Nur Anime`,
  appsVersionIs: `Anwendungsversion ist`,
  areYouSureYouWantTo: `Bist du sicher, dass du willst`,
  art: `Kunst`,
  artAssociatedWithAnime: `Kunst im Zusammenhang mit Anime`,
  artBy: `Kunst von `,
  artCannotBeChanged: `Kunst kann nicht verändert werden`,
  authenticationFailed: `Authentifizierung fehlgeschlagen`,
  back: `Zurück`,
  blog: `Blog`,
  bookmarks: `Lesezeichen`,
  browseArt: `Kunst durchsuchen`,
  cancel: `stornieren`,
  cannotStartWithChars: `Kann nicht mit s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  changeArt: `Kunst ändern`,
  changeAvatar: `Avatar ändern`,
  changePassword: `Passwort ändern`,
  city: `Stadt`,
  clearAll: `Alle löschen`,
  close: `Schließen`,
  comingSoon: `Kommt bald…`,
  community: `Gemeinschaft`,
  confirmAccount: `Konto bestätigen`,
  confirmPassword: `Bestätige das Passwort`,
  copyLink: `Link kopieren`,
  couldNotCreateANewRecord: `Es konnte kein neuer Datensatz erstellt werden`,
  country: `Land`,
  createANewAccountFailed: `Fehler beim Erstellen eines neuen Kontos`,
  createNewAccount: `Neuen Account erstellen`,
  delete: `Löschen`,
  deleteArt: `Art löschen`,
  deletePost: `Beitrag löschen`,
  description: `Beschreibung`,
  details: `Einzelheiten`,
  didntReceiveEmail: `Haben Sie keine E-Mail erhalten?`,
  donations: `Spenden`,
  done: `Getan`,
  earningFromArts: `Mit Kunst verdienen`,
  edit: `Bearbeiten`,
  editPost: `Beitrag bearbeiten`,
  editProfile: `Profil bearbeiten`,
  editTranslations: `Übersetzungen bearbeiten`,
  email: `E-Mail`,
  emailSubscription: `E-Mail-Abonnement`,
  error404NotFound: `Fehler 404 - Nicht gefunden`,
  errorPleaseContactCustomerSupport: `Error! Bitte wenden Sie sich an den Kundendienst...`,
  exitEditor: `Editor beenden`,
  extensions: `Erweiterungen`,
  favorites: `Favoriten`,
  fileSizeIsTooBig: `Die Dateigröße ist zu groß`,
  filter: `Filter`,
  filterBy: `Filter nach`,
  follow: `Folgen`,
  followMeOn: `Folge mir auf`,
  followUsOnTwitter: `Folge uns auf Twitter`,
  forAllOtherInquiriesPleaseContactUsAt: `Für alle anderen Anfragen kontaktieren Sie uns bitte unter:`,
  forgotPassword: `Passwort vergessen`,
  forNewMasterpieces: `Für neue Meisterwerke`,
  four04: `— 404! —`,
  guestView: `Gastansicht`,
  homepage: `Startseite`,
  iAgreeWith: `Ich bin einverstanden mit`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Die Höhe von Img muss größer oder gleich sein`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Die Breite von Img muss größer oder gleich sein`,
  introduction: `Einführung`,
  invalidCode: `Ungültiger Code`,
  invalidPartAfterAt: `Ungültiger Teil nach @`,
  invalidPartBeforeAt: `Ungültiger Teil vor @`,
  joinChat: `Chat beitreten`,
  joinUsOnFacebook: `Folge uns auf Facebook`,
  livingIn: `Leben in`,
  logout: `Ausloggen`,
  maximumNChars: (n) => `Maximal ${n} Zeichen`,
  maxSize: `Maximale Größe`,
  menu: `Speisekarte`,
  minHeight: `Mindesthöhe`,
  minimumNChars: (n) => `Mindestens ${n} Zeichen`,
  minWidth: `Mindestbreite`,
  moreFrom: (n) => `Mehr von ${n}`,
  mustBeNChars: (n) => `Muss ${n} Zeichen sein`,
  need1Lowercase: `Benötigen Sie 1 Kleinbuchstaben`,
  need1Number: `Benötigen Sie 1 Nummer`,
  need1Uppercase: `Benötigen Sie 1 Großbuchstaben`,
  needAtLeast1CharacterFromN: (n) => `Benötige mindestens 1 Zeichen aus [${n}]`,
  needNCharacter: (n) => `Muss ${n} Zeichen haben`,
  newAccount: `Neues Konto`,
  newArt: `Neue Kunst`,
  newBlog: `Neuer Blog`,
  newPassword: `Neues Passwort `,
  newsFeed: `Newsfeed`,
  no: `Nein`,
  noAddedFavoriteArts: `keine hinzugefügten favorisierten Arts`,
  noInternetConnection: `Keine Internetverbindung!`,
  nsfwContent18Plus: `NSFW-Inhalt (18+)`,
  ohNoItIsNotHere: `Ach nein! Es ist nicht hier!`,
  oldPassword: `Altes Passwort`,
  onlyHexNumbersStartsWithTChar: `Nur Hex-Zahlen [0-9a-fA-F] beginnen mit 't' char`,
  onlyLatinLettersNumbersOrSpecialSymbols: `Nur lateinische Buchstaben, Zahlen, Sonderzeichen`,
  onlyNumbers: `Nur Zahlen`,
  openGuestView: `Gastansicht öffnen`,
  openingSoon: `Öffnet bald!`,
  or: `ODER`,
  password: `Passwort`,
  payments: `Zahlungen`,
  pleaseCheckYour: `Bitte überprüfen Sie Ihre`,
  pleaseDropOnlyOneImage: `Bitte lassen Sie nur ein Bild fallen`,
  pleaseEnterAtLeastNChars: (n) =>
    `Bitte geben Sie mindestens ${n} Zeichen ein`,
  pleaseFillOutYourDetails: `Bitte füllen Sie Ihre Daten`,
  pleaseSignInToYourAccount: `Bitte melden Sie sich an Ihrem Konto`,
  pleaseTryAgainOrClick: (n) =>
    `Bitte versuche es später noch einmal oder klicke auf ${n}`,
  pleaseVerifyYourAccount: `Bitte verifizieren sie ihr Konto`,
  pressHereTo: `Drücken Sie hier um`,
  profile: `Profil`,
  save: `Speichern`,
  saveAvatar: `Avatar speichern`,
  saveChanges: `Änderungen speichern`,
  selectAnime: `Wählen Sie Anime`,
  selectAvatar: `Avatar auswählen`,
  selectCharacters: `Charakter(e) auswählen`,
  selectFile: `Wählen Sie Datei`,
  selectThumbnail: `Wählen Sie eine Miniaturansicht`,
  sendEmail: `E-Mail senden`,
  settings: `Einstellungen`,
  shareYourStory: `Teile deine Geschichte!`,
  shop: `Geschäft`,
  signIn: `Einloggen`,
  skip: `Überspringen`,
  socialMedia: `Sozialen Medien`,
  spaceCharacterIsNotAllowed: `Leerzeichen sind nicht erlaubt`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Abonniere Künstler und bleibe auf dem Laufenden `,
  successChangedPasswordPleaseSignIn: `Erfolg! Passwort geändert. Bitte einloggen`,
  successCreatedRecord: `Erfolg! Datensatz erstellt!`,
  successUpdatedRecord: `Erfolg! Datensatz aktualisiert!`,
  supportMeOn: `Unterstütze mich bei`,
  tellUsAboutYourself: `Erzähl uns von dir`,
  termsAndConditions: `Allgemeine Geschäftsbedingungen `,
  termsOfUse: `Nutzungsbedingungen`,
  title: `Titel`,
  typeYourTextHere: `Bitte hier ihren Text eingeben...`,
  uploadAnotherArt: `Laden Sie eine andere Kunst hoch`,
  uploadAnotherAvatar: `Laden Sie einen anderen Avatar hoch`,
  uploadArtNow: `Laden Sie jetzt Kunst hoch!`,
  uploadNew: `Neu hochladen`,
  uploadNewArt: `Neue Kunst hochladen`,
  uploadNewPost: `Neuen Beitrag hochladen`,
  username: `Nutzername`,
  usernameAlreadyExists: `Benutzername existiert bereits`,
  valueIsNotTheSame: `Wert ist nicht derselbe`,
  verificationCode: `Bestätigungscode`,
  verifyCode: `Code überprüfen`,
  weAreOnInstagram: `Wir sind auf Instagram`,
  weAreWorkingOnIt: `Wir arbeiten daran`,
  weDoNotDisplayNSFWContentYet: `Wir zeigen noch keine NSFW-Inhalte an`,
  weHaveSentTooManyVerificationEmails: `Wir haben zu viele Bestätigungs-E-Mails gesendet. Bitte versuchen Sie es nach einigen Minuten erneut`,
  welcomeToAnimeClub: `Willkommen bei Anime.club!`,
  weSentAnEmailTo: `Wir haben eine E-Mail gesendet an:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Wir haben Ihnen eine neue Bestätigungs-E-Mail gesendet. Bitte geben Sie den Code ein`,
  weSupportOnlyTheFollowingFileExtensions: `Wir unterstützen nur die folgenden Dateierweiterungen:`,
  wrongEmailOrPassword: `Falsche E-Mail oder falsches Passwort`,
  yes: `Ja`,
  youAreAlreadyAuthenticated: `Sie sind bereits authentifiziert`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Sie können weiterhin zu den zuvor geöffneten Seiten navigieren`,
  youDidNotUpdateAnyValues: `Sie haben keine Werte aktualisiert`,
  youHaveNotSavedAnyChanges: `Sie haben keine Änderungen gespeichert. Verlassen?`,
  yourAccountIsVerifiedPleaseSignIn: `Ihr Konto wird überprüft. Bitte einloggen`,
  yourArts: `Ihre Kunst`,
  yourAvatar: `Ihr avatar`,
  yourBlog: `Ihr Blog`,
  yourFansAreWaiting: `Ihre Fans warten`,
  yourFeedIsEmpty: `Dein Feed ist leer`,
  yourSessionHasExpiredPleaseSignInAgain: `Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an`,
}
