export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Über`,
  accept: `Akzeptieren`,
  acceptOffer: `(en) Accept order`,
  account: `(en) Account`,
  accountActivation: `Kontoaktivierung`,
  accountAlreadyExists: `Konto existiert bereits`,
  accountDoesNotExist: `Konto existiert nicht`,
  add: `Hinzufügen`,
  addArt: `Kunst hinzufügen`,
  addBlog: `Blog hinzufügen`,
  addFile: `(en) Add file`,
  additionalResources: `(en) Additional resources`,
  addMore: `(en) Add more`,
  addNewArt: `Neue Kunst hinzufügen`,
  addPreview: `Vorschau hinzufügen`,
  addSignInVia: `Anmeldung hinzufügen über`,
  addToCart: `(en) Add to cart`,
  advancedOptions: `(en) Advanced options`,
  all: `Alle`,
  alreadySignedIn: `Bereits angemeldet`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (...v) =>
    `(en) Amount should not be less than ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Kunst des Anime von Künstlern aus aller Welt. Kunst ist kuratiert, um mit Anime in Verbindung zu stehen. Die Kunstauswahl ist eine unendliche Liste der besten Anime-Kunst`,
  animeArtSubscribeToArtistsLikeAndCreate: `Kunst des Anime - Abonnieren Sie Künstler wie und erstellen Sie eine Sammlung`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - die erste Plattform, die Künstlern Zahlungen aus Ansichten über Google AdSense anbietet. Unterstützen Sie Künstler, indem Sie ihre Inhalte anzeigen oder mit Ansichten verdienen`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - Anzeigen, Posten und Verdienen von Anime-Inhalten`,
  animeCommunity: `Gemeinschaft von Anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `(en) Anime.club never asks for your private information`,
  animeSocialNetwork: `(en) Anime
Social Network`,
  announcements: `(en) Announcements`,
  apply: `Übernehmen`,
  appSettings: `(en) App settings`,
  appsVersionIs: `Anwendungsversion ist`,
  areYouSureYouWantTo: `Bist du sicher, dass du willst`,
  art: `Kunst`,
  artAssociatedWithAnime: `Kunst im Zusammenhang mit Anime`,
  artBy: (...v) => `(en) Art by ${v[0]}`,
  artCannotBeChanged: `Kunst kann nicht verändert werden`,
  artworksAvailableToView: (...v) => `(en) ${v[0]} artworks available to view`,
  awaitingSeller: `(en) Awaiting seller`,
  awaitingReview: `(en) Awaiting review`,
  authenticationFailed: `Authentifizierung fehlgeschlagen`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `Zurück`,
  basePrice: `(en) Base Price`,
  blog: `Blog`,
  bookmarks: `Lesezeichen`,
  browseArt: `Kunst durchsuchen`,
  cancel: `stornieren`,
  canceled: `(en) Canceled`,
  cannotStartWithChars: `Kann nicht mit s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `(en) Change`,
  changeArt: `Kunst ändern`,
  changeAvatar: `Avatar ändern`,
  changeEmail: `(en) Change email`,
  changePassword: `Passwort ändern`,
  chooseExistingChatOrStartANewOne: `Vorhandenen Chat auswählen oder einen neuen beginnen`,
  city: `Stadt`,
  clearAll: `Alle löschen`,
  close: `Schließen`,
  clientReview: `(en) Client review`,
  colorTheme: `(en) Color theme`,
  comingSoon: `Kommt bald…`,
  commercialUse: `(en) Commercial use`,
  community: `Gemeinschaft`,
  confirmAccount: `Konto bestätigen`,
  confirmOrder: `(en) Confirm order`,
  confirmPassword: `Bestätige das Passwort`,
  connectWithUsOn: `(en) Connect with us on`,
  contactInformation: `(en) Contact information`,
  contactSeller: `(en) Contact seller`,
  contactCustomer: `(en) Contact customer`,
  contactSupport: `(en) Contact support`,
  continue: `(en) Continue`,
  contractTitle: `(en) Contract Title`,
  completed: `(en) Completed`,
  cancelOffer: `(en) Cancel order`,
  copyLink: `Link kopieren`,
  couldNotCreateANewRecord: `Es konnte kein neuer Datensatz erstellt werden`,
  country: `Land`,
  cover: `(en) Cover`,
  creator: `(en) Creator`,
  createANewAccountFailed: `Fehler beim Erstellen eines neuen Kontos`,
  createExtrasForYourProduct: `(en) Create extras for your product`,
  createNewAccount: `Neuen Account erstellen`,
  createYourShop: `(en) Create your shop`,
  currentPassword: `(en) Current password`,
  daily: `(en) Daily`,
  darkDefault: `(en) Dark default`,
  darkHighContrast: `(en) Dark high contrast`,
  dayTheme: `(en) Day theme`,
  delete: `Löschen`,
  disputed: `(en) Disputed`,
  deleteArt: `Art löschen`,
  deletePost: `Beitrag löschen`,
  deleteProduct: `(en) Delete product`,
  deliveryTime: `(en) Delivery time`,
  describeTheDetailsOfYourProduct: `(en) Describe the details of your product`,
  description: `Beschreibung`,
  details: `Einzelheiten`,
  didntReceiveEmail: `Haben Sie keine E-Mail erhalten?`,
  displayName: `(en) Display name`,
  donations: `Spenden`,
  done: `Getan`,
  dragAndDropOrSelectFiles: `(en) Drag & Drop or Select file(s)`,
  drawingContest: `Zeichnungswettbewerb`,
  dueDate: `(en) Due date`,
  earlier: `(en) Earlier`,
  earningFromArts: `Mit Kunst verdienen`,
  edit: `Bearbeiten`,
  editPost: `Beitrag bearbeiten`,
  editProfile: `Profil bearbeiten`,
  editTranslations: `Übersetzungen bearbeiten`,
  email: `E-Mail`,
  emailAlreadyUsedByAnotherAccount: `E-Mail-Adresse wird bereits von einem anderen Konto verwendet`,
  emailNotifications: `(en) Email Notifications`,
  enterOrPasteALink: `Einen Link eingeben oder einfügen`,
  enterTheAddressAssociatedWithYourAccount: `(en) Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `(en) Enter your password`,
  error: `(en) Error`,
  errorPleaseContactCustomerSupport: `Error! Bitte wenden Sie sich an den Kundendienst...`,
  exitEditor: `Editor beenden`,
  extensions: `Erweiterungen`,
  extras: `(en) Extras`,
  fileSizeIsTooBig: `Die Dateigröße ist zu groß`,
  filter: `Filter`,
  filterBy: `Filter nach`,
  findUser: `Nutzer finden`,
  follow: `Folgen`,
  followers: `Followers`,
  following: `Folgen`,
  followMeOn: `Folge mir auf`,
  follows: `(en) Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `Für alle anderen Anfragen kontaktieren Sie uns bitte unter:`,
  forgotPassword: `Passwort vergessen`,
  fromAnimeDotClub: `(en) From anime.club`,
  getDetails: `Weitere Einzelheiten`,
  getStarted: `(en) Get started`,
  guestView: `Gastansicht`,
  hasNotAddedADescriptionFor: (...v) =>
    `(en) @${v[0]} has not added a description for "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `(en) @${v[0]} has not shared any public details yet`,
  hire: `(en) Hire`,
  homepage: `Startseite`,
  howToContactYou: `(en) How to contact you`,
  howToFindYouOnOtherSocialNetworks: `(en) How to find you on other social networks`,
  iAgreeWith: `Ich bin einverstanden mit`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Die Höhe von Img muss größer oder gleich sein`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Die Breite von Img muss größer oder gleich sein`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `(en) Include keywords that buyers would likely use to search for a product like yours`,
  introduction: `Einführung`,
  inProgress: `(en) In progress`,
  invalidCode: `Ungültiger Code`,
  invalidCurrentPassword: `(en) Invalid current password`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `Ungültiger Teil nach @`,
  invalidPartBeforeAt: `Ungültiger Teil vor @`,
  jobDetails: `(en) Job Details`,
  joinAnimeClubCommunity: `(en) Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `Chat beitreten`,
  joinUsOnFacebook: `Folge uns auf Facebook`,
  language: `(en) Language`,
  languages: `Sprachen`,
  letEveryoneKnowHowToDonateToYou: `(en) Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `(en) Let others know about you`,
  licenseForForProfitBusinessUse: `(en) License for for-profit business use`,
  lightDefault: `(en) Light default`,
  lightHighContrast: `(en) Light high contrast`,
  likes: `Likes`,
  linkCopiedToClipboard: `Link in Zwischenablage kopiert`,
  livesIn: `Leben in`,
  loading: `(en) Loading`,
  location: `(en) Location`,
  logInOrSignUp: `(en) Log in or sign up`,
  logOut: `(en) Log out`,
  maximumNChars: (...v) => `Maximal ${v[0]} Zeichen`,
  maximumNumberOfDaysToCompleteTheOrder: `(en) Maximum number of days to complete the order`,
  maximumQuantity: `(en) Maximum quantity`,
  maxSize: `Maximale Größe`,
  menu: `Speisekarte`,
  message: `Nachricht`,
  messages: `Nachrichten`,
  minHeight: `Mindesthöhe`,
  minimumNChars: (...v) => `Mindestens ${v[0]} Zeichen`,
  minWidth: `Mindestbreite`,
  monthly: `(en) Monthly`,
  moreFrom: (...v) => `Mehr von ${v[0]}`,
  mustBeNChars: (...v) => `Muss ${v[0]} Zeichen sein`,
  myPayments: `(en) My payments`,
  myProfile: `(en) My profile`,
  mySettings: `(en) My settings`,
  need1Lowercase: `Benötigen Sie 1 Kleinbuchstaben`,
  need1Number: `Benötigen Sie 1 Nummer`,
  need1Uppercase: `Benötigen Sie 1 Großbuchstaben`,
  needAtLeast1CharacterFromN: (...v) =>
    `Benötige mindestens 1 Zeichen aus [${v[0]}]`,
  needNCharacter: (...v) => `Muss ${v[0]} Zeichen haben`,
  newAccount: `Neues Konto`,
  newOffer: `(en) New order`,
  newArt: `Neue Kunst`,
  newArtworks: `(en) New artworks`,
  newBlog: `Neuer Blog`,
  newPassword: `Neues Passwort`,
  newProduct: `(en) New product`,
  newsFeed: `Newsfeed`,
  next: `(en) Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `(en) Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `(en) Night theme`,
  no: `Nein`,
  noAddedFavoriteArts: `keine hinzugefügten favorisierten Arts`,
  noInternetConnection: `Keine Internetverbindung!`,
  none: `(en) None`,
  noNotifications: `(en) No notifications`,
  noResults: `(en) No results`,
  notifications: `Benachrichtigungen`,
  nsfwContent18Plus: `NSFW-Inhalt (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `(en) Number of adjustments a client could request`,
  online: `Online`,
  onlyLatinLettersNumbersHyphen: `(en) Only latin letters, numbers, hyphen, underscore, and dot characters`,
  onlyNumbers: `Nur Zahlen`,
  open: `(en) Open`,
  openGuestView: `Gastansicht öffnen`,
  openingSoon: `Öffnet bald!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `ODER`,
  orderOptions: `(en) Order Options`,
  orderAgain: `(en) Order again`,
  pageNotFound: `(en) Page not found`,
  password: `Passwort`,
  payments: `Zahlungen`,
  personal: `(en) Personal`,
  pleaseCheckYour: (...v) => `(en) Please check your ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `(en) Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `Bitte lassen Sie nur ein Bild fallen`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `(en) Please enter a number between ${v[0]} and ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) =>
    `Bitte geben Sie mindestens ${v[0]} Zeichen ein`,
  pleaseFillOutYourDetails: `Bitte füllen Sie Ihre Daten`,
  pleaseSignInToYourAccount: `Bitte melden Sie sich an Ihrem Konto`,
  pleaseTryAgainOrClick: (...v) =>
    `Bitte versuche es später noch einmal oder klicke auf ${v[0]}`,
  pleaseVerifyYourAccount: `Bitte verifizieren sie ihr Konto`,
  pressHereTo: `Drücken Sie hier um`,
  price: `(en) Price`,
  privacyPolicy: `Datenschutzrichtlinie`,
  privateInformation: `(en) Private information`,
  proceedToCheckout: `(en) Proceed to Checkout`,
  product: `(en) Product`,
  profile: `Profil`,
  promotions: `(en) Promotions`,
  publicInformation: `(en) Public information`,
  publishOn: (...v) => `(en) Publish on ${v[0]}`,
  rankings: `(en) Rankings`,
  reorderFiles: `(en) Reorder files`,
  report: `(en) Report`,
  revisions: `(en) Revisions`,
  save: `Speichern`,
  saveAvatar: `Avatar speichern`,
  saveChanges: `Änderungen speichern`,
  selectAnime: `Wählen Sie Anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `(en) Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `Avatar auswählen`,
  selectCharacters: `Charakter(e) auswählen`,
  selectFile: `Wählen Sie Datei`,
  selectTheme: `(en) Select theme`,
  selectThumbnail: `Wählen Sie eine Miniaturansicht`,
  sendEmail: `E-Mail senden`,
  settings: `Einstellungen`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `(en) Setting up a shop is free and only takes a few minutes`,
  share: `(en) Share`,
  shareYourArtWithTheWorld: `(en) Share your art with the world`,
  shareYourStory: `Teile deine Geschichte!`,
  shop: `Geschäft`,
  shopOrders: `(en) Shop orders`,
  showLess: `Weniger anzeigen`,
  showMore: `Mehr anzeigen`,
  signIn: `Einloggen`,
  singleTheme: `(en) Single theme`,
  size: `(en) Size`,
  skip: `Überspringen`,
  socialMedia: `Sozialen Medien`,
  submitWork: `(en) Submit work`,
  spaceCharacterIsNotAllowed: `Leerzeichen sind nicht erlaubt`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Abonniere Künstler und bleibe auf dem Laufenden `,
  successChangedPasswordPleaseSignIn: `Erfolg! Passwort geändert. Bitte einloggen`,
  successCreatedRecord: `Erfolg! Datensatz erstellt!`,
  successUpdatedRecord: `Erfolg! Datensatz aktualisiert!`,
  supportMeOn: `Unterstütze mich bei`,
  syncWithSystem: `(en) Sync with system`,
  tellUsAboutYourself: `Erzähl uns von dir`,
  termsAndConditions: `Allgemeine Geschäftsbedingungen`,
  termsOfUse: `Nutzungsbedingungen`,
  theLinkIsBrokenOrPageHasBeenRemoved: `(en) The link is broken or page has been removed`,
  themeMode: `(en) Theme mode`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `Titel`,
  titleYourExtraService: `(en) Title your extra service`,
  today: `(en) Today`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  total: `(en) Total`,
  typeYourTextHere: `Bitte hier ihren Text eingeben...`,
  unlimited: `(en) Unlimited`,
  upload: `(en) Upload`,
  uploadNew: `Neu hochladen`,
  uploadNewPost: `Neuen Beitrag hochladen`,
  username: `Nutzername`,
  usernameAlreadyExists: `Benutzername existiert bereits`,
  usernameAndXMoreFollowYou: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more follow you`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more like your artwork`,
  usernameFollowsYou: (...v) => `(en) <b>${v[0]}</b> follows you`,
  usernameLikesYourArt: (...v) => `(en) <b>${v[0]}</b> likes your art`,
  useThisEmailTo: `(en) Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `Wert ist nicht derselbe`,
  verificationCode: `Bestätigungscode`,
  verifyCode: `Code überprüfen`,
  viewDetails: `(en) View details`,
  viewEveryNotificationOfAGroupSeparately: `(en) View every notification of a group separately`,
  visitOurDiscordChannelToGetMoreDetails: `Für weitere Einzelheiten besuchen Sie unseren Discord-Kanal`,
  weAreOnInstagram: `Wir sind auf Instagram`,
  weAreWorkingOnIt: `Wir arbeiten daran`,
  weDoNotDisplayNSFWContentYet: `Wir zeigen noch keine NSFW-Inhalte an`,
  weekly: `(en) Weekly`,
  weHaveSentTooManyEmails: `(en) We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Willkommen bei Anime.club!`,
  weSentAnEmailTo: `Wir haben eine E-Mail gesendet an:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Wir haben Ihnen eine neue Bestätigungs-E-Mail gesendet. Bitte geben Sie den Code ein`,
  weSupportOnlyTheFollowingFileExtensions: `Wir unterstützen nur die folgenden Dateierweiterungen:`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `Falsche E-Mail oder falsches Passwort`,
  yes: `Ja`,
  yesterday: `(en) Yesterday`,
  youAreAlreadyAuthenticated: `Sie sind bereits authentifiziert`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `(en) You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Sie können weiterhin zu den zuvor geöffneten Seiten navigieren`,
  youDidNotSelectAnyChats: `Sie haben keine Chats ausgewählt`,
  youDidNotUpdateAnyValues: `Sie haben keine Werte aktualisiert`,
  youDoNotHaveAnyChats: `Sie haben keine Chats`,
  youHaveNotSavedAnyChanges: `Sie haben keine Änderungen gespeichert. Verlassen?`,
  youHaveNotSetAPassword: `(en) You have not set a password`,
  youHaveNotSharedAnythingYet: `(en) You have not shared anything yet`,
  youHaveReachedTheMaximumNumberOfFiles: `(en) You have reached the maximum number of files`,
  yourAccountIsVerifiedPleaseSignIn: `Ihr Konto wird überprüft. Bitte einloggen`,
  yourArts: `Ihre Kunst`,
  yourAvatar: `Ihr avatar`,
  yourBlog: `Ihr Blog`,
  yourFansAreWaiting: `Ihre Fans warten`,
  yourFeedIsEmpty: `Dein Feed ist leer`,
  yourSessionHasExpiredPleaseSignInAgain: `Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an`,
}
