export const text: text = {
  _dash: `(en) - `,
  acceptTheOrder: `(en) Accept the order`,
  accountManagment: `(en) Account management`,
  animeShopBuyAndSellProducts: `(en) Anime shop - buy and sell products`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `(en) AI-generated images and neural network filters are prohibited`,
  addMoreProductsToYourShop: `(en) Add more products to your shop`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `(en) All files you upload here will be available to the buyer`,
  bigAppreciationToTheSellerForTheirHardWork: `(en) Big appreciation to the seller for their hard work`,
  buyerReviewedTheOrder: `(en) Buyer reviewed the order`,
  buyerHasNotLeftAReviewYet: `(en) Buyer has not left a review yet`,
  feedbackReceived: `(en) Feedback received!`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `(en) Before accepting, please review the buyer's request carefully`,
  checkOutMyShop: `(en) Check out my shop`,
  commercialUseAllowed: `(en) Commercial use allowed`,
  commercialUseAllowsBuyersToUseYourProduct: `(en) Commercial use allows buyers to use your product for business purposes, like selling or promoting their services`,
  congratulationsOnSuccessfullyCompletingYourOrder: `(en) Congratulations on successfully completing your order!`,
  createAShopWithStripe: `(en) Create a shop with Stripe`,
  createdBy: `(en) Created by`,
  download: `(en) Dowload`,
  downloadThemBelow: `(en) Download them below`,
  describeTheDetailsOfYourExtra: `(en) Describe the details of your extra`,
  enjoyYourPurchase: `(en) Enjoy your purchase! 😊`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `(en) Extras are optional add-ons to enhance your product`,
  usernameHasSubmittedTheWork: (...v) =>
    `(en) <b>${v[0]}</b> has submitted the work`,
  hereAreAFewWaysToGetThingsRolling: `(en) Here are a few ways to get things rolling`,
  makeSureToIncludeClearInstructions: `(en) Make sure to include clear instructions on how each reference should be used`,
  makeSureYouFullyUnderstandTheRequirements: `(en) Make sure you fully understand the requirements and can complete the order by the deadline`,
  makeSureYourProductsArePricedCompetitively: `(en) Make sure your products are priced competitively`,
  newProducts: `(en) New products`,
  noReviewsJustYet: `(en) No reviews just yet`,
  noSalesYetNoWorries: `(en) No sales yet? No worries, you're just starting out`,
  NSFWIndicatesAdultContent: `(en) 18+ NSFW indicates adult content. Check this field only if your product is intended for mature audiences`,
  onlyYouCanSeeWhatYouveSaved: `(en) Only you can see what you've saved`,
  requestDetails: `(en) Request details`,
  orderCompleted: `(en) Order Completed 🎉`,
  pleaseRateYourOrder: `(en) Please rate your order`,
  feelFreeToShareReferenceImagesAndMaterials: `(en) Feel free to share reference images and materials to help the artist create your piece`,
  pleaseFixTheErrorsBeforeSubmitting: `(en) Please fix the errors before submitting`,
  pleaseTakeAMomentToReviewTheOrder: `(en) Please take a moment to review the order`,
  pleaseReviewTheBuyersReferenceFiles: `(en) Please review the buyer's reference files and follow them as specified in the order's description`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `(en) Please review the details carefully before proceeding`,
  pleaseRespondToTheOrderBy: (...v) =>
    `(en) Please respond to the order by ${v[0]}`,
  payouts: `(en) Payouts`,
  itemReviews: `(en) Item reviews`,
  portfolio: `(en) Portfolio`,
  review: `(en) Review`,
  rules: `(en) Rules`,
  reviews: `(en) Reviews`,
  numOfReviews: (...v) => `(en) ${v[0]} reviews`,
  reviewed: `(en) Reviewed`,
  reviewTitle: `(en) Review title`,
  reason: `(en) Reason`,
  yourOrderIncludesXRevisionS: (...v) =>
    `(en) Your order includes ${v[0]} revision(s)`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `(en) Share your rules and the types of requests you don’t accept`,
  shareYourShopOnSocialMedia: `(en) Share your shop on social media`,
  shareYourFavoritePiecesOn: (...v) =>
    `(en) Share your favorite pieces on ${v[0]}`,
  shopReviews: `(en) Shop reviews`,
  startAddingFavoritesToSeeThemHere: `(en) Start adding favorites to see them here`,
  successfullyDownloaded: `(en) Successfully downloaded!`,
  successfullyUploaded: `(en) Successfully uploaded!`,
  tellTheBuyerWhatTheyWillGetWithThisProduct: `(en) Tell the buyer what they will get with this product`,
  thankYouForYourReview: `(en) Thank you for your review!`,
  thankForYourSupport: `(en) Thank you for your support!`,
  thisFieldIsOptional: `(en) This field is optional`,
  thisCannotBeUndone: `(en) This cannot be undone`,
  ensureYouveUploadedTheFinalVersion: `(en)  Ensure you've uploaded the final version before submitting`,
  theSellerHasUploadedTheseFilesForYou: `(en) The seller has uploaded these files for you`,
  pleaseUploadOnlyFinishedWorkHereMaximumFiles: `(en) Please upload only finished work here`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `(en) All WIP-related files should be uploaded in messages`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `(en) Unfortunately, ${v[0]} had to cancel this order`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `(en) Well done! Work has been successfully completed`,
  youReceivedAReview: `(en) You received a review`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `(en) Your feedback guides buyers and helps sellers offer better products`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `(en) You’ll see reviews here once buyers share their experience`,
  youCanceledTheOrder: `(en) You canceled the order`,
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Über`,
  accept: `Akzeptieren`,
  acceptOrder: `Bestellung annehmen`,
  account: `Konto`,
  accountDeleted: `Konto gelöscht`,
  accountActivation: `Kontoaktivierung`,
  accountAlreadyExists: `Konto existiert bereits`,
  accountDoesNotExist: `Konto existiert nicht`,
  accountRemoval: `Kontolöschung`,
  add: `Hinzufügen`,
  addArt: `Kunst hinzufügen`,
  addBlog: `Blog hinzufügen`,
  addFile: `Datei hinzufügen`,
  additionalResources: `Zusätzliche Ressourcen`,
  addMore: `Mehr hinzufügen`,
  addNewArt: `Neue Kunst hinzufügen`,
  addPreview: `Vorschau hinzufügen`,
  addSignInVia: `Anmeldung hinzufügen über`,
  addToCart: `Zum Warenkorb hinzufügen`,
  advancedOptions: `Erweiterte Optionen`,
  all: `Alle`,
  alreadySignedIn: `Bereits angemeldet`,
  amount: `Menge`,
  amountShouldNotBeLessThan: (...v) =>
    `Menge sollte nicht weniger als ${v[0]} sein`,
  animeArtByArtistsFromAllOverTheWorld: `Kunst des Anime von Künstlern aus aller Welt. Kunst ist kuratiert, um mit Anime in Verbindung zu stehen. Die Kunstauswahl ist eine unendliche Liste der besten Anime-Kunst`,
  animeArtSubscribeToArtistsLikeAndCreate: `Kunst des Anime - Abonnieren Sie Künstler wie und erstellen Sie eine Sammlung`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - die erste Plattform, die Künstlern Zahlungen aus Ansichten über Google AdSense anbietet. Unterstützen Sie Künstler, indem Sie ihre Inhalte anzeigen oder mit Ansichten verdienen`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - Anzeigen, Posten und Verdienen von Anime-Inhalten`,
  animeCommunity: `Gemeinschaft von Anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club fragt niemals nach Ihren privaten Informationen`,
  animeSocialNetwork: `Anime-Soziales Netzwerk`,
  announcements: `Ankündigungen`,
  apply: `Übernehmen`,
  appSettings: `App-Einstellungen`,
  appsVersionIs: `Anwendungsversion ist`,
  areYouSureYouWantTo: `Bist du sicher, dass du willst`,
  art: `Kunst`,
  artAssociatedWithAnime: `Kunst im Zusammenhang mit Anime`,
  artBy: (...v) => `Kunst von ${v[0]}`,
  artCannotBeChanged: `Kunst kann nicht verändert werden`,
  artworksAvailableToView: (...v) => `${v[0]} Kunstwerke verfügbar zum Ansehen`,
  authenticationFailed: `Authentifizierung fehlgeschlagen`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Automatisches Veröffentlichen auf Instagram ist nur für Instagram Geschäftskonten verfügbar`,
  attentionYourOrderHasBeenDisputed: `Achtung! Ihre Bestellung wurde angefochten. Bitte überprüfen Sie die Details`,
  awaitingReview: `Warten auf Überprüfung`,
  awaitingSeller: `Warten auf Verkäufer`,
  back: `Zurück`,
  basePrice: `Grundpreis`,
  block: `Blockieren`,
  blockUser: (...v) => `@${v[0]} blockieren`,
  blog: `Blog`,
  bookmarks: `Lesezeichen`,
  browseArt: `Kunst durchsuchen`,
  browseShop: `Shop durchsuchen`,
  buyer: `Käufer`,
  cancel: `stornieren`,
  canceled: `Abgebrochen`,
  cancelOrder: `Bestellung stornieren`,
  cannotStartWithChars: `Kann nicht mit s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Ändern`,
  checkOrderStatus: `Bestellstatus überprüfen`,
  changeArt: `Kunst ändern`,
  changeAvatar: `Avatar ändern`,
  changeEmail: `E-Mail ändern`,
  changePassword: `Passwort ändern`,
  chooseExistingChatOrStartANewOne: `Vorhandenen Chat auswählen oder einen neuen beginnen`,
  city: `Stadt`,
  clearAll: `Alle löschen`,
  clientReview: `Kundenbewertung`,
  close: `Schließen`,
  colorTheme: `Farbthema`,
  comingSoon: `Kommt bald…`,
  community: `Gemeinschaft`,
  completed: `Abgeschlossen`,
  confirmAccount: `Konto bestätigen`,
  confirmOrder: `Bestellung bestätigen`,
  confirmPassword: `Bestätige das Passwort`,
  connectWithUsOn: `Verbinde dich mit uns auf`,
  contactInformation: `Kontaktinformationen`,
  contactSeller: `Verkäufer kontaktieren`,
  contactSupport: `Support kontaktieren`,
  contactUs: `Kontaktieren Sie uns`,
  continue: `Weiter`,
  contractTitle: `Vertragstitel`,
  copyLink: `Link kopieren`,
  congratulations: `Herzlichen Glückwunsch!`,
  copyrightViolation: `Urheberrechtsverletzung`,
  couldNotCreateANewRecord: `Es konnte kein neuer Datensatz erstellt werden`,
  country: `Land`,
  cover: `Cover`,
  createANewAccountFailed: `Fehler beim Erstellen eines neuen Kontos`,
  createExtrasForYourProduct: `Erstelle Extras für dein Produkt`,
  createNewAccount: `Neuen Account erstellen`,
  currentPassword: `Aktuelles Passwort`,
  daily: `Täglich`,
  darkDefault: `Dunkel Standard`,
  darkHighContrast: `Dunkel hoher Kontrast`,
  dayTheme: `Tages-Thema`,
  delete: `Löschen`,
  deleteShop: `Shop löschen`,
  deleteAccount: `Konto löschen`,
  deleteArt: `Art löschen`,
  decline: `Ablehnen`,
  deletePost: `Beitrag löschen`,
  deleteProduct: `Produkt löschen`,
  deliveryTime: `Lieferzeit`,
  description: `Beschreibung`,
  details: `Einzelheiten`,
  didntReceiveEmail: `Haben Sie keine E-Mail erhalten?`,
  displayName: `Anzeigename`,
  disputed: `Umstritten`,
  donations: `Spenden`,
  done: `Getan`,
  dragAndDropOrSelectFiles: `Ziehen und Ablegen oder Dateien auswählen`,
  drawingContest: `Zeichnungswettbewerb`,
  dueDate: `Fälligkeitsdatum`,
  earlier: `Früher`,
  earningFromArts: `Mit Kunst verdienen`,
  edit: `Bearbeiten`,
  editPost: `Beitrag bearbeiten`,
  editProfile: `Profil bearbeiten`,
  editTranslations: `Übersetzungen bearbeiten`,
  email: `E-Mail`,
  emailAlreadyUsedByAnotherAccount: `E-Mail-Adresse wird bereits von einem anderen Konto verwendet`,
  emailNotifications: `E-Mail-Benachrichtigungen`,
  enterOrPasteALink: `Einen Link eingeben oder einfügen`,
  enterTheAddressAssociatedWithYourAccount: `Geben Sie die Adresse ein, die mit Ihrem Konto verknüpft ist, und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts per E-Mail`,
  enterYourPassword: `Geben Sie Ihr Passwort ein`,
  error: `Fehler`,
  errorPleaseContactCustomerSupport: `Error! Bitte wenden Sie sich an den Kundendienst...`,
  exitWithoutSaving: `Ohne Speichern verlassen`,
  extensions: `Erweiterungen`,
  extras: `Extras`,
  fileSizeIsTooBig: `Die Dateigröße ist zu groß`,
  fileSizeIsTooSmall: `Dateigröße ist zu klein`,
  filter: `Filter`,
  filterBy: `Filter nach`,
  findUser: `Nutzer finden`,
  finishSettingUpYourShop: `Beenden Sie die Einrichtung Ihres Shops`,
  follow: `Folgen`,
  followers: `Followers`,
  following: `Folgen`,
  followMeOn: `Folge mir auf`,
  follows: `Folgt`,
  forAllOtherInquiriesPleaseContactUsAt: `Für alle anderen Anfragen kontaktieren Sie uns bitte unter:`,
  forgotPassword: `Passwort vergessen`,
  fromAnimeDotClub: `Von anime.club`,
  getDetails: `Weitere Einzelheiten`,
  getStarted: `Loslegen`,
  guestView: `Gastansicht`,
  greatNewsYourOrderIsNowInProgress: `Gute Nachrichten! Ihre Bestellung wird jetzt bearbeitet`,
  harassment: `Belästigung`,
  haveAnyQuestions: `Haben Sie Fragen?`,
  usernameHasCanceledTheOrder: (...v) =>
    `<b>${v[0]}</b> hat die Bestellung storniert`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]} hat keine Beschreibung für "${v[1]}" hinzugefügt`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} hat noch keine öffentlichen Details geteilt`,
  hate: `Hass`,
  hire: `Einstellen`,
  homepage: `Startseite`,
  howToContactYou: `Wie man dich kontaktieren kann`,
  howToFindYouOnOtherSocialNetworks: `Wie man dich auf anderen sozialen Netzwerken finden kann`,
  iAgreeWith: `Ich bin einverstanden mit`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Wenn bis ${v[0]} keine Antwort erfolgt, wird die Bestellung automatisch als abgeschlossen markiert`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Die Höhe von Img muss größer oder gleich sein`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Die Breite von Img muss größer oder gleich sein`,
  impersonation: `Identitätsdiebstahl`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Schließe Schlüsselwörter ein, die Käufer wahrscheinlich verwenden würden, um nach einem Produkt wie deinem zu suchen`,
  inProgress: `In Bearbeitung`,
  introduction: `Einführung`,
  invalidCode: `Ungültiger Code`,
  invalidCurrentPassword: `Ungültiges aktuelles Passwort`,
  invalidDate: `Ungültiges Datum`,
  invalidPartAfterAt: `Ungültiger Teil nach @`,
  invalidPartBeforeAt: `Ungültiger Teil vor @`,
  jobDetails: `Jobdetails`,
  joinAnimeClubCommunity: `Tritt der Anime.club-Community bei, mit Tausenden von aktiven Künstlern und coolen Anime-Kunstwerken jeden Tag`,
  joinChat: `Chat beitreten`,
  joinUsOnFacebook: `Folge uns auf Facebook`,
  language: `Sprache`,
  lackOfInformation: `Mangel an Informationen`,
  languages: `Sprachen`,
  letEveryoneKnowHowToDonateToYou: `Lass alle wissen, wie sie dir spenden können`,
  letOthersKnowAboutYou: `Lass andere über dich wissen`,
  letsUploadYourFirstProduct: `Lassen Sie uns Ihr erstes Produkt hochladen`,
  letUsKnowWhatsHappening: `Lass uns wissen, was passiert, und wir werden uns darum kümmern`,
  lightDefault: `Hell Standard`,
  lightHighContrast: `Hell hoher Kontrast`,
  likes: `Likes`,
  limit: `Limit`,
  linkCopiedToClipboard: `Link in Zwischenablage kopiert`,
  livesIn: `Leben in`,
  loading: `Laden`,
  location: `Ort`,
  logInOrSignUp: `Einloggen oder Registrieren`,
  logOut: `Ausloggen`,
  maximumNChars: (...v) => `Maximal ${v[0]} Zeichen`,
  maximumNumberOfDaysToCompleteTheOrder: `Maximale Anzahl von Tagen, um die Bestellung abzuschließen`,
  maximumQuantity: `Maximale Menge`,
  maxSize: `Maximale Größe`,
  menu: `Speisekarte`,
  message: `Nachricht`,
  messages: `Nachrichten`,
  minHeight: `Mindesthöhe`,
  minimumNChars: (...v) => `Mindestens ${v[0]} Zeichen`,
  minorAbuseOrSexualization: `Geringfügiger Missbrauch oder Sexualisierung`,
  minWidth: `Mindestbreite`,
  monthly: `Monatlich`,
  moreFrom: (...v) => `Mehr von ${v[0]}`,
  mustBeNChars: (...v) => `Muss ${v[0]} Zeichen sein`,
  myPayments: `Meine Zahlungen`,
  myProfile: `Mein Profil`,
  mySettings: `Meine Einstellungen`,
  need1Lowercase: `Benötigen Sie 1 Kleinbuchstaben`,
  need1Number: `Benötigen Sie 1 Nummer`,
  need1Uppercase: `Benötigen Sie 1 Großbuchstaben`,
  needAtLeast1CharacterFromN: (...v) =>
    `Benötige mindestens 1 Zeichen aus [${v[0]}]`,
  needNCharacter: (...v) => `Muss ${v[0]} Zeichen haben`,
  newAccount: `Neues Konto`,
  newArt: `Neue Kunst`,
  newArtworks: `Neue Kunstwerke`,
  newBlog: `Neuer Blog`,
  newOrder: `Neue Bestellung`,
  newPassword: `Neues Passwort`,
  newProduct: `Neues Produkt`,
  newsFeed: `Newsfeed`,
  next: `Weiter`,
  nextTimeYouAuthenticateYouCouldUseThe: `Das nächste Mal, wenn Sie sich authentifizieren, können Sie das verbundene Konto anstelle von Login und Passwort verwenden`,
  nightTheme: `Nachtthema`,
  no: `Nein`,
  noInternetConnection: `Keine Internetverbindung!`,
  nonConsensualIntimateContent: `Nicht einvernehmlicher intimer Inhalt`,
  none: `Keine`,
  noNotifications: `Keine Benachrichtigungen`,
  noResults: `Keine Ergebnisse`,
  notifications: `Benachrichtigungen`,
  noActiveOrdersToShow: `Keine aktiven Bestellungen zum Anzeigen`,
  notAcceptingOrders: `Nimmt keine Bestellungen an`,
  nsfwContent18Plus: `NSFW-Inhalt (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `Anzahl der Anpassungen, die ein Kunde anfordern könnte`,
  online: `Online`,
  onlyLatinLettersNumbersHyphen: `Nur lateinische Buchstaben, Zahlen, Bindestrich, Unterstrich und Punktzeichen`,
  onlyNumbers: `Nur Zahlen`,
  open: `Öffnen`,
  openDispute: `Streitfall eröffnen`,
  openGuestView: `Gastansicht öffnen`,
  openingSoon: `Öffnet bald!`,
  openToWork: `Offen für Arbeit`,
  optional: `Optional`,
  or: `ODER`,
  order: `Bestellung`,
  outOfStock: `Nicht vorrätig`,
  ordered: (...v) => `Bestellt ${v[0]}`,
  orderAgain: `Erneut bestellen`,
  orderDetails: `Bestelldetails`,
  orderConfirmed: `Bestellung bestätigt`,
  orderStatus: `Bestellstatus`,
  orderOptions: `Bestelloptionen`,
  otherReason: `Anderer Grund`,
  pageNotFound: `Seite nicht gefunden`,
  password: `Passwort`,
  payments: `Zahlungen`,
  personal: `Persönlich`,
  personalCircumstances: `Persönliche Umstände`,
  pleaseCheckYour: (...v) => `Bitte überprüfen Sie Ihre ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Bitte teilen Sie Ihre privaten Informationen nicht mit anderen`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `Bitte geben Sie eine Zahl zwischen ${v[0]} und ${v[1]} ein`,
  pleaseEnterAtLeastNChars: (...v) =>
    `Bitte geben Sie mindestens ${v[0]} Zeichen ein`,
  pleaseFillOutYourDetails: `Bitte füllen Sie Ihre Daten`,
  pleaseSignInToYourAccount: `Bitte melden Sie sich an Ihrem Konto`,
  platform: `Plattform`,
  pleaseStartTyping: `Bitte beginnen Sie zu tippen`,
  pleaseTryAgainOrClick: (...v) =>
    `Bitte versuche es später noch einmal oder klicke auf ${v[0]}`,
  pleaseVerifyYourAccount: `Bitte verifizieren sie ihr Konto`,
  pressHereTo: `Drücken Sie hier um`,
  price: `Preis`,
  privacyPolicy: `Datenschutzrichtlinie`,
  privateInformation: `Private Informationen`,
  proceedToCheckout: `Zur Kasse gehen`,
  product: `Produkt`,
  profile: `Profil`,
  prohibitedTransaction: `Verbotene Transaktion`,
  promotions: `Promotionen`,
  publicInformation: `Öffentliche Informationen`,
  publishOn: (...v) => `Veröffentlichen auf ${v[0]}`,
  purchases: `Käufe`,
  rankings: `Rankings`,
  reorderFiles: `Dateien neu anordnen`,
  report: `Melden`,
  revisions: `Überarbeitungen`,
  sales: `Verkäufe`,
  save: `Speichern`,
  saveAvatar: `Avatar speichern`,
  saveChanges: `Änderungen speichern`,
  selectAnime: `Wählen Sie Anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Wählen Sie ein einzelnes Thema oder synchronisieren Sie es mit Ihrem System und wechseln Sie automatisch zwischen Tag- und Nacht-Themes`,
  selectAvatar: `Avatar auswählen`,
  selectCharacters: `Charakter(e) auswählen`,
  seller: `Verkäufer`,
  selectFile: `Wählen Sie Datei`,
  selectTheme: `Thema auswählen`,
  selectThumbnail: `Wählen Sie eine Miniaturansicht`,
  selfHarmOrSuicide: `Selbstverletzung oder Selbstmord`,
  sendEmail: `E-Mail senden`,
  settings: `Einstellungen`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Das Einrichten eines Shops ist kostenlos und dauert nur wenige Minuten`,
  share: `Teilen`,
  shareYourArtWithTheWorld: `Teilen Sie Ihre Kunst mit der Welt`,
  shareYourStory: `Teile deine Geschichte!`,
  sharingPersonalInformation: `Teilen persönlicher Informationen`,
  shop: `Geschäft`,
  shopOrders: `Shop-Bestellungen`,
  showLess: `Weniger anzeigen`,
  showMore: `Mehr anzeigen`,
  signIn: `Einloggen`,
  singleTheme: `Einzelnes Thema`,
  size: `Größe`,
  skip: `Überspringen`,
  socialMedia: `Sozialen Medien`,
  spaceCharacterIsNotAllowed: `Leerzeichen sind nicht erlaubt`,
  spam: `Spam`,
  submitAReport: `Bericht einreichen`,
  submitWork: `Arbeit einreichen`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Abonniere Künstler und bleibe auf dem Laufenden `,
  successChangedPasswordPleaseSignIn: `Erfolg! Passwort geändert. Bitte einloggen`,
  successCreatedRecord: `Erfolg! Datensatz erstellt!`,
  successUpdatedRecord: `Erfolg! Datensatz aktualisiert!`,
  supportMeOn: `Unterstütze mich bei`,
  syncWithSystem: `Mit System synchronisieren`,
  tellUsAboutYourself: `Erzähl uns von dir`,
  termsAndConditions: `Allgemeine Geschäftsbedingungen`,
  termsOfUse: `Nutzungsbedingungen`,
  thankYouForReport: `Vielen Dank, dass Sie dazu beitragen, eine sichere und respektvolle Online-Community aufrechtzuerhalten`,
  theLinkIsBrokenOrPageHasBeenRemoved: `Der Link ist defekt oder die Seite wurde entfernt`,
  themeMode: `Themenmodus`,
  thisIsThePriceYouPropose: `Dies ist der von Ihnen vorgeschlagene Preis`,
  threateningViolence: `Gewaltandrohung`,
  title: `Titel`,
  timeConstraints: `Zeitbeschränkungen`,
  titleYourExtraService: `Benennen Sie Ihren zusätzlichen Service`,
  theMaximumQuantityThatACustomerCanAdd: `Die maximale Menge, die ein Kunde hinzufügen kann`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `Die Überprüfungsfrist ist auf ${v[0]} Tage begrenzt`,
  toHelpTheCreatorCompleteYourOrder: `Um dem Ersteller zu helfen, Ihre Bestellung zu Ihrer Zufriedenheit abzuschließen, geben Sie bitte eine detaillierte Beschreibung dessen, was Sie möchten. Geben Sie das gewünschte Thema, den Stil und die Charaktereigenschaften sowie alle anderen wichtigen Spezifikationen an`,
  today: `Heute`,
  toGetWorkRelatedNotifications: `Um arbeitsbezogene Benachrichtigungen zu erhalten`,
  total: `Gesamt`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Um diese Daten anzuzeigen, müssen Sie @${v[0]} freischalten`,
  trademarkViolation: `Markenrechtsverletzung`,
  typeYourTextHere: `Bitte hier ihren Text eingeben...`,
  unblock: `Freischalten`,
  unblockUser: (...v) => `@${v[0]} freischalten`,
  unfollow: `Entfolgen`,
  unlimited: `Unbegrenzt`,
  upload: `Hochladen`,
  uploadNew: `Neu hochladen`,
  uploadNewPost: `Neuen Beitrag hochladen`,
  uploadNewProduct: `Neues Produkt hochladen`,
  username: `Nutzername`,
  usernameAlreadyExists: `Benutzername existiert bereits`,
  usernameAndXMoreFollowYou: (...v) =>
    `<b>${v[0]}</b> und ${v[1]} weitere folgen dir`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `<b>${v[0]}</b> und ${v[1]} weitere mögen dein Kunstwerk`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b> folgt dir`,
  usernameLikesYourArt: (...v) => `<b>${v[0]}</b> mag deine Kunst`,
  useThisEmailTo: `Verwenden Sie diese E-Mail-Adresse, um sich zu authentifizieren und Benachrichtigungen zu erhalten`,
  valueIsNotTheSame: `Wert ist nicht derselbe`,
  verificationCode: `Bestätigungscode`,
  verifyCode: `Code überprüfen`,
  viewDetails: `Details anzeigen`,
  viewReview: `Bewertung anzeigen`,
  viewEveryNotificationOfAGroupSeparately: `Jede Benachrichtigung einer Gruppe separat anzeigen`,
  visitOurDiscordChannelToGetMoreDetails: `Für weitere Einzelheiten besuchen Sie unseren Discord-Kanal`,
  weAreOnInstagram: `Wir sind auf Instagram`,
  weAreWorkingOnIt: `Wir arbeiten daran`,
  weDoNotDisplayNSFWContentYet: `Wir zeigen noch keine NSFW-Inhalte an`,
  weekly: `Wöchentlich`,
  whenYouPurchaseSomethingItWillAppearHere: `Wenn Sie etwas kaufen, wird es hier angezeigt`,
  weHaveSentTooManyEmails: `Wir haben zu viele E-Mails gesendet. Bitte versuchen Sie es später erneut oder wenden Sie sich an den Kundensupport`,
  welcomeToAnimeClub: `Willkommen bei Anime.club!`,
  weSentAnEmailTo: `Wir haben eine E-Mail gesendet an:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Wir haben Ihnen eine neue Bestätigungs-E-Mail gesendet. Bitte geben Sie den Code ein`,
  weAreExcitedToSeeYourProgressKeepItUp: `Wir sind gespannt auf Ihre Fortschritte. Machen Sie weiter so!`,
  weSupportOnlyTheFollowingFileExtensions: `Wir unterstützen nur die folgenden Dateierweiterungen:`,
  work: `Arbeit`,
  weWouldLoveToHearFromYou: `Wir würden gerne von Ihnen hören`,
  workDescription: `Beschreibung der Arbeit`,
  leaveAReview: `Eine Bewertung hinterlassen`,
  wrongEmailOrPassword: `Falsche E-Mail oder falsches Passwort`,
  yes: `Ja`,
  yesterday: `Gestern`,
  youReceivedANewOrderFrom: (...v) =>
    `Sie haben eine neue Bestellung von <b>${v[0]}</b> erhalten`,
  youHaveSuccessfullyCreatedYourShop: `Sie haben Ihren Shop erfolgreich erstellt`,
  youAreAlreadyAuthenticated: `Sie sind bereits authentifiziert`,
  youCanAutoPublishToYourSocialMediaAccount: `Sie können automatisch auf Ihr Social-Media-Konto veröffentlichen`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Sie können die Arten von Benachrichtigungen ändern, die Sie per E-Mail erhalten`,
  youCanRequestRemovalOfYourAccount: `Sie können die Entfernung Ihres Kontos mit allen Ihren Daten anfordern`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Sie können weiterhin zu den zuvor geöffneten Seiten navigieren`,
  youDidNotSelectAnyChats: `Sie haben keine Chats ausgewählt`,
  youDidNotUpdateAnyValues: `Sie haben keine Werte aktualisiert`,
  youDoNotHaveAnyChats: `Sie haben keine Chats`,
  youHaveNotSetAPassword: `Sie haben kein Passwort festgelegt`,
  youHaveNotSharedAnythingYet: `Sie haben noch nichts geteilt`,
  youHaveReachedTheMaximumNumberOfFiles: `Sie haben die maximale Anzahl von Dateien erreicht`,
  kindlyHoldOnForTheBuyersReview: `Bitte warten Sie auf die Bewertung des Käufers zur Bestellung.`,
  yourAccountIsVerifiedPleaseSignIn: `Ihr Konto wird überprüft. Bitte einloggen`,
  yourAccountWillBeRemoved: (...v) => `Ihr Konto wird ${v[0]} entfernt`,
  youHaveNoPurchases: `Sie haben keine Käufe`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Könnten Sie bitte den Grund für die Stornierung angeben`,
  yourFeedbackWouldBeGreatlyAppreciated: `Ihr Feedback wäre sehr willkommen`,
  yourArts: `Ihre Kunst`,
  yourAvatar: `Ihr avatar`,
  yourBlog: `Ihr Blog`,
  yourFansAreWaiting: `Ihre Fans warten`,
  yourFeedIsEmpty: `Dein Feed ist leer`,
  yourSessionHasExpiredPleaseSignInAgain: `Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an`,
}
