export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `| `,
  _exclamation: `! `,
  _question: `? `,
  about: `के बारे में`,
  accountActivation: `खाता सक्रियण`,
  accountAlreadyExists: ` खाता पहले से ही मौजूद है`,
  accountDoesNotExist: `खाता मौजूद नहीं है`,
  add: `जोड़ना`,
  addArt: `कला जोड़ें`,
  addBlog: `ब्लॉग जोड़ें`,
  addedNAgo: (n) => `${n} पहले जोड़ा गया`,
  addNewArt: `नई कला जोड़ें`,
  addPreview: `पूर्वावलोकन जोड़ें`,
  animeArtByArtistsFromAllOverTheWorld: `दुनिया भर से कलाकारों द्वारा मोबाइल फोनों के लिए कला । कला मोबाइल फोनों के लिए संबंधित होने के लिए क्यूरेट है । कला चयन सबसे अच्छा मोबाइल फोनों के लिए कला की एक अनंत सूची है`,
  animeArtSubscribeToArtistsLikeAndCreate: `एनीमे कला - कलाकारों की सदस्यता लें, जैसे, और संग्रह बनाएं`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - गूगल ऐडसेंस के माध्यम से विचारों से कलाकारों के भुगतान की पेशकश करने वाला पहला मंच। कलाकारों को उनकी सामग्री देखकर समर्थन दें या विचारों से कमाई शुरू करें	`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club   - एनीमे कंटेंट से देखें, पोस्ट   करें और कमाएं`,
  animeCommunity: `एनीमे   समुदाय`,
  animeOnly: `केवल   एनीमे`,
  appsVersionIs: `एप्लिकेशन   का संस्करण है`,
  areYouSureYouWantTo: `क्या   आप यकीन है कि आप चाहते हैं`,
  art: `कला`,
  artAssociatedWithAnime: `एनीमे के साथ जुड़ी कला`,
  artBy: `          द्वारा   कला        `,
  artCannotBeChanged: `कला को बदला नहीं जा सकता`,
  authenticationFailed: `प्रमाणीकरण विफल हो गया`,
  back: `वापस        `,
  blog: `ब्लॉग`,
  browseArt: `कला ब्राउज़ करें`,
  cancel: `रद्द करें`,
  cannotStartWithChars: `एस के   साथ शुरू नहीं कर सकते{:"^$*[]{}()?-"!@#%&/,><':;|~\`"        `,
  changeArt: `कला को बदलो`,
  changeAvatar: `अवतार बदलो`,
  changePassword: `पासवर्ड बदलें`,
  city: `शहर`,
  clearAll: `सभी को साफ़ करें`,
  close: `बंद करें`,
  comingSoon: `जल्द ही आ रहा…`,
  community: `समुदाय`,
  confirmAccount: `          खाते   की पुष्टि करें        `,
  confirmPassword: `          पासवर्ड   की पुष्टि करें        `,
  couldNotCreateANewRecord: `एक नया रिकॉर्ड नहीं बना सकता`,
  country: `देश`,
  createANewAccountFailed: `एक नया खाता बनाने में विफल रहा`,
  createNewAccount: `नया खाता बनाएं`,
  delete: `हटाएं`,
  deleteArt: `(en) Delete art`,
  deletePost: `(en) Delete post`,
  description: `वर्णन`,
  details: `विवरण`,
  didntReceiveEmail: `ईमेल प्राप्त नहीं किया था?`,
  done: `हो गया`,
  earningFromArts: `कला से कमाई`,
  editArt: `कला को संपादित करें`,
  editPost: `पोस्ट संपादित करें`,
  editProfile: `प्रोफ़ाइल को संपादित करें`,
  email: `ईमेल`,
  emailSubscription: `ईमेल सदस्यता`,
  error404NotFound: `त्रुटि 404-नहीं मिला`,
  errorPleaseContactCustomerSupport: `त्रुटि! कृपया ग्राहक सहायता से संपर्क करें ...`,
  exitEditor: `संपादक से बाहर निकलें`,
  extensions: `एक्सटेंशन`,
  fileSizeIsTooBig: `फ़ाइल का आकार बहुत बड़ा है`,
  filter: `फ़िल्टर`,
  filterBy: `द्वारा फ़िल्टर करें`,
  follow: `          का   पालन करें`,
  followMeOn: `मुझे का पालन करें पर`,
  followUsOnTwitter: `ट्विटर पर हमें का पालन करें`,
  forAllOtherInquiriesPleaseContactUsAt: `अन्य सभी पूछताछ के लिए, कृपया हमसे संपर्क करें:`,
  forgotPassword: `पासवर्ड भूल गए`,
  forNewMasterpieces: `नई कृतियों के लिए`,
  four04: `— 404! —`,
  guestView: `अतिथि दृश्य`,
  homepage: `मुखपृष्ठ`,
  iAgreeWith: `मैं के साथ सहमत हूँ`,
  id: `(en) ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `आइएमजी   की ऊंचाई से बड़ा या बराबर होने की जरूरत है`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `आईएमजी की चौड़ाई से बड़ा या बराबर होने की जरूरत है`,
  introduction: `परिचय`,
  invalidCode: `अवैध कोड`,
  invalidPartAfterAt: `@ के बाद अमान्य भाग`,
  invalidPartBeforeAt: `@ से पहले अमान्य भाग`,
  joinChat: `चैट में शामिल हों`,
  joinUsOnFacebook: `फेसबुक पर हमसे जुड़ें`,
  livingIn: `में रहते हैं`,
  logout: `लॉगआउट`,
  maximumNChars: (n) => `अधिकतम ${n} वर्ण`,
  maxSize: `अधिकतम आकार`,
  menu: `मेन्यू`,
  minHeight: `न्यूनतम ऊँचाई`,
  minimumNChars: (n) => `न्यूनतम ${n} वर्ण`,
  minWidth: `न्यूनतम चौड़ाई`,
  mustBeNChars: (n) => `${n} वर्ण होना चाहिए`,
  need1Lowercase: `1 लोअरकेस की आवश्यकता है`,
  need1Number: `1 नंबर की आवश्यकता है`,
  need1Uppercase: `1 अपरकेस की आवश्यकता है`,
  needAtLeast1CharacterFromN: (n) => `[${n}] से कम से कम 1 चरित्र की आवश्यकता है`,
  needNCharacter: (n) => `${n} चरित्र की आवश्यकता है`,
  newAccount: `नया खाता`,
  newArt: `नई कला`,
  newBlog: `नया ब्लॉग`,
  newPassword: `नया पासवर्ड`,
  no: `नहीं।`,
  noInternetConnection: `कोई इंटरनेट कनेक्शन नहीं!`,
  nsfwContent18Plus: `एनएसएफडब्ल्यू सामग्री (18+)`,
  ohNoItIsNotHere: `अरे नहीं! यह यहाँ नहीं है!`,
  oldPassword: `पुराना पासवर्ड`,
  onlyHexNumbersStartsWithTChar: `केवल हेक्स संख्या [0-9a-fA-F], ' टी ' चार के साथ शुरू होता है`,
  onlyLatinLettersNumbersOrSpecialSymbols: `केवल लैटिन अक्षर, संख्या, विशेष प्रतीक`,
  onlyNumbers: `केवल संख्या`,
  openGuestView: `अतिथि दृश्य खोलें`,
  openingSoon: `जल्द ही खुल रहा है!`,
  or: `या`,
  password: `पासवर्ड`,
  payments: `भुगतान`,
  pleaseCheckYour: `कृपया अपनी जांच करें`,
  pleaseDropOnlyOneImage: `कृपया केवल एक छवि ड्रॉप करें`,
  pleaseEnterAtLeastNChars: (n) => `कृपया कम से कम एन वर्ण दर्ज करें`,
  pleaseFillOutYourDetails: `कृपया अपना विवरण भरें`,
  pleaseSignInToYourAccount: `कृपया अपने खाते में प्रवेश करें`,
  pleaseVerifyYourAccount: `कृपया अपने खाते को सत्यापित करें`,
  pressHereTo: `यहाँ प्रेस करने के लिए`,
  save: `सहेजें`,
  saveAvatar: `अवतार सहेजें`,
  saveChanges: `परिवर्तनों को सहेजें`,
  saveThumbnail: `थंबनेल सहेजें`,
  selectAnime: `एनीमे का चयन करें`,
  selectAvatar: `अवतार का चयन करें`,
  selectCharacters: `चरित्र का चयन करें`,
  selectFile: `फ़ाइल का चयन करें`,
  selectThumbnail: `थंबनेल का चयन करें`,
  sendEmail: `ईमेल भेजें`,
  settings: `सेटिंग्स`,
  shareYourStory: `अपनी कहानी साझा करें!`,
  shop: `दुकान`,
  signIn: `साइन इन करें`,
  skip: `छोड़ें`,
  socialMedia: `सोशल मीडिया`,
  spaceCharacterIsNotAllowed: `अंतरिक्ष चरित्र की अनुमति नहीं है`,
  successChangedPasswordPleaseSignIn: `सफलता! पासवर्ड बदल दिया है. कृपया साइन इन करें`,
  successCreatedRecord: `सफलता! रिकार्ड बनाया गया!`,
  successUpdatedRecord: `सफलता! रिकॉर्ड अपडेट किया गया !`,
  tellUsAboutYourself: `हमें अपने बारे में बताएं`,
  termsAndConditions: `नियम और शर्तें`,
  termsOfUse: `उपयोग की शर्तें`,
  title: `शीर्षक`,
  typeYourTextHere: `अपना पाठ यहां टाइप करें...`,
  uploadAnotherArt: `एक और कला अपलोड करें`,
  uploadAnotherAvatar: `एक और अवतार अपलोड करें`,
  uploadArtNow: `अब कला अपलोड करें!`,
  uploadNew: `नई अपलोड करें`,
  uploadNewArt: `नई कला अपलोड करें`,
  uploadNewPost: `नई पोस्ट अपलोड करें`,
  username: `उपयोगकर्ता नाम`,
  usernameAlreadyExists: ` उपयोगकर्ता नाम पहले से ही मौजूद है`,
  valueIsNotTheSame: `(en) Value is not the same`,
  verificationCode: `सत्यापन कोड`,
  verifyCode: `कोड सत्यापित करें`,
  weAreOnInstagram: `हम इंस्टाग्राम पर हैं`,
  weAreWorkingOnIt: `हम इस पर काम कर रहे हैं`,
  weDoNotDisplayNSFWContentYet: `हम अभी तक एनएसएफडब्ल्यू सामग्री प्रदर्शित नहीं करते`,
  weHaveSentTooManyVerificationEmails: `हम भी कई सत्यापन ईमेल भेजा है, कुछ ही मिनटों के बाद पुन: प्रयास करें`,
  welcomeToAnimeClub: `Anime.club में आपका स्वागत है!`,
  weSentAnEmailTo: `हमने एक ईमेल भेजा है:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `हमने आपको एक नया सत्यापन ईमेल भेजा है। कृपया कोड दर्ज करें`,
  weSupportOnlyTheFollowingFileExtensions: `हम केवल निम्नलिखित फ़ाइल एक्सटेंशन का समर्थन करते हैं:`,
  yes: `हाँ`,
  youAreAlreadyAuthenticated: `आप पहले से ही प्रमाणीकृत हैं`,
  youCanStillNavigateToThePreviouslyOpenedPages: `आप अभी भी पहले खोले गए पृष्ठों पर नेविगेट कर सकते हैं`,
  youDidNotUpdateAnyValues: `आपने कोई मान अपडेट नहीं किया है`,
  youHaveNotSavedAnyChanges: `आपने कोई परिवर्तन नहीं सहेजे हैं। छोड़ना?`,
  yourAccountIsVerifiedPleaseSignIn: `आपका खाता सत्यापित है. कृपया साइन इन करें`,
  yourArts: `आपकी कलाएँ`,
  yourAvatar: `आपका अवतार`,
  yourBlog: `आपका ब्लॉग`,
  yourFansAreWaiting: `अपने प्रशंसकों इंतजार कर रहे हैं`,
  yourSessionHasExpiredPleaseSignInAgain: `आपका सत्र समाप्त हो गया है, कृपया फिर से साइन इन करें`,
}