export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `| `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `के बारे में`,
  accept: `स्वीकार करना`,
  accountActivation: `खाता सक्रियण`,
  accountAlreadyExists: ` खाता पहले से ही मौजूद है`,
  accountDoesNotExist: `खाता मौजूद नहीं है`,
  add: `जोड़ना`,
  addArt: `चित्र जोड़ें`,
  addBlog: `ब्लॉग जोड़ें`,
  addedNAgo: (n) => `${n} पहले जोड़ा गया`,
  addMore: `(en) Add more`,
  addNewArt: `नई चित्र जोड़ें`,
  addPreview: `पूर्व संवीक्षा जोड़ें`,
  addSignInVia: `साइन इन के माध्यम से जोड़ें`,
  advancedOptions: `(en) Advanced options`,
  all: `सब`,
  alreadySignedIn: `पहले से ही साइन इन`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (n) => `(en) Amount should not be less than $${n}`,
  animeArtByArtistsFromAllOverTheWorld: `दुनिया भर के कलाकारों के द्वारा आनिमे चित्रकला। चित्रकला आनिमे से संबंधित होना चाहिए। कला चयन सर्वश्रेष्ठ आनिमे कला की एक अनंत सूची है`,
  animeArtSubscribeToArtistsLikeAndCreate: `आनिमे कला - कलाकारों की सदस्यता लें, पसंद करें, और संग्रह बनाएं`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - गूगल ऐडसेंस के माध्यम से कलाकारों को भुगतान की पेशकश करने वाला पहला मंच। कलाकारों को उनके कंटेंट को देखकर समर्थन दें या व्यूज़ से कमाई शुरू करें	`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club   - आनिमे कंटेंट से देखें, पोस्ट करें और कमाएं`,
  animeCommunity: `आनिमे समुदाय`,
  animeOnly: `केवल आनिमे`,
  apply: `लागू करें`,
  appsVersionIs: `एप्लिकेशन का संस्करण है`,
  areYouSureYouWantTo: `क्या आपको यकीन है कि आप चाहते हैं`,
  art: `चित्र`,
  artAssociatedWithAnime: `आनिमे के साथ जुड़ी कला`,
  artBy: `चित्रकला द्वारा`,
  artCannotBeChanged: `चित्रकला को बदला नहीं जा सकता`,
  authenticationFailed: `प्रमाणीकरण विफल हो गया`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `वापस`,
  blog: `ब्लॉग`,
  bookmarks: `बुकमार्क`,
  browseArt: `चित्रकला ब्राउज़ करें`,
  cancel: `रद्द करें`,
  cannotStartWithChars: `इस के साथ शुरू नहीं कर सकते{:"^$*[]{}()?-"!@#%&/,><':;|~\`"        `,
  changeArt: `चित्रकला बदलें `,
  changeAvatar: `अवतार बदलें `,
  changePassword: `पासवर्ड बदलें`,
  chooseExistingChatOrStartANewOne: `मौजूदा चैट चुनें या एक नई शुरू करें`,
  city: `शहर`,
  clearAll: `सभी को साफ़ करें`,
  close: `बंद करें`,
  comingSoon: `जल्द ही आ रहा…`,
  community: `समुदाय`,
  confirmAccount: `खाते की पुष्टि करें`,
  confirmPassword: `पासवर्ड की पुष्टि करें`,
  contactInformation: `(en) Contact information`,
  contractTitle: `(en) Contract Title`,
  copyLink: `लिंक कॉपी करें`,
  couldNotCreateANewRecord: `नया रिकॉर्ड नहीं बना सकते`,
  country: `देश`,
  createANewAccountFailed: `नया खाता बनाने में विफल रहा`,
  createNewAccount: `नया खाता बनाएं`,
  delete: `हटाएं`,
  deleteArt: `चित्रकला हटाएं`,
  deletePost: `पोस्ट हटायें`,
  description: `वर्णन`,
  details: `विवरण`,
  didntReceiveEmail: `ईमेल प्राप्त नहीं हुआ?`,
  donations: `दान`,
  done: `समाप्त`,
  drawingContest: `ड्राइंग प्रतियोगिता`,
  dueDate: `(en) Due date`,
  earningFromArts: `चित्रकला से कमाई`,
  edit: `संपादित करें`,
  editPost: `पोस्ट संपादित करें`,
  editProfile: `प्रोफ़ाइल को संपादित करें`,
  editTranslations: `अनुवाद संपादित करें`,
  email: `ईमेल`,
  emailAlreadyUsedByAnotherAccount: `पहले से ही किसी अन्य खाते द्वारा उपयोग किया जाने लगा ईमेल`,
  emailSubscription: `ईमेल सदस्यता`,
  enterOrPasteALink: `एक लिंक डालें या पेस्ट करें`,
  error404NotFound: `त्रुटि 404-नहीं मिला`,
  errorPleaseContactCustomerSupport: `त्रुटि! कृपया ग्राहक सहायता से संपर्क करें ...`,
  exitEditor: `संपादक से बाहर निकलें`,
  extensions: `एक्सटेंशन`,
  fileSizeIsTooBig: `फ़ाइल की साइज़ बहुत बड़ी है`,
  filter: `फ़िल्टर`,
  filterBy: `द्वारा फ़िल्टर करें`,
  findUser: `यूजर खोजें`,
  follow: `फॉलो करें`,
  followers: `फॉलोअर्स`,
  following: `फॉलोइंग`,
  followMeOn: `मुझे फॉलो करें`,
  followUsOnTwitter: `ट्विटर पर हमें फॉलो करें`,
  forAllOtherInquiriesPleaseContactUsAt: `अन्य सभी पूछताछ के लिए, कृपया हमसे संपर्क करें:`,
  forgotPassword: `पासवर्ड भूल गए`,
  forNewMasterpieces: `नई कृतियों के लिए`,
  four04: `— 404! —`,
  getDetails: `विवरण प्राप्त करें`,
  guestView: `अतिथि दृश्य`,
  hire: `(en) Hire`,
  homepage: `मुखपृष्ठ`,
  howToContactYou: `(en) How to contact you`,
  iAgreeWith: `मैं सहमत हूँ`,
  id: `आईडी`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `इमेज की ऊंचाई से बड़ा या बराबर होने की जरूरत है`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `इमेज की चौड़ाई से बड़ा या बराबर होने की जरूरत है`,
  introduction: `परिचय`,
  invalidCode: `अवैध कोड`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `@ के बाद अमान्य भाग`,
  invalidPartBeforeAt: `@ से पहले अमान्य भाग`,
  jobDetails: `(en) Job Details`,
  joinChat: `चैट में शामिल हों`,
  joinUsOnFacebook: `फेसबुक पर हमसे जुड़ें`,
  languages: `भाषाओं`,
  likes: `लाइक्स`,
  linkCopiedToClipboard: `लिंक को क्लिपबोर्ड पर कॉपी किया गया`,
  livesIn: `में रहते हैं`,
  location: `(en) Location`,
  logout: `लॉगआउट`,
  maximumNChars: (n) => `अधिकतम ${n} वर्ण`,
  maxSize: `अधिकतम साइज़`,
  menu: `मेन्यू`,
  message: `संदेश`,
  messages: `संदेश`,
  minHeight: `न्यूनतम ऊँचाई`,
  minimumNChars: (n) => `न्यूनतम ${n} वर्ण`,
  minWidth: `न्यूनतम चौड़ाई`,
  moreFrom: (n) => `एन से अधिक`,
  mustBeNChars: (n) => `${n} वर्ण होना चाहिए`,
  need1Lowercase: `1 लोअरकेस की आवश्यकता है`,
  need1Number: `1 नंबर की आवश्यकता है`,
  need1Uppercase: `1 अपरकेस की आवश्यकता है`,
  needAtLeast1CharacterFromN: (n) =>
    `[${n}] से कम से कम 1 करेक्टर की आवश्यकता है`,
  needNCharacter: (n) => `${n} करेक्टर की आवश्यकता है`,
  newAccount: `नया खाता`,
  newArt: `नई चित्रकला`,
  newBlog: `नया ब्लॉग`,
  newPassword: `नया पासवर्ड`,
  newsFeed: `समाचार फ़ीड`,
  no: `नहीं।`,
  noAddedFavoriteArts: `कोई पसंदीदा कला नहीं`,
  noInternetConnection: `कोई इंटरनेट कनेक्शन नहीं!`,
  notifications: `नोटिफिकेशन्स`,
  nsfwContent18Plus: `एनएसएफडब्ल्यू सामग्री (18+)`,
  ohNoItIsNotHere: `अरे नहीं! यह यहाँ नहीं है!`,
  oldPassword: `पुराना पासवर्ड`,
  online: `ऑनलाइन`,
  onlyHexNumbersStartsWithTChar: `केवल हेक्स संख्या [0-9a-fA-F], ' टी ' चार के साथ शुरू होता है`,
  onlyLatinLettersNumbersOrSpecialSymbols: `केवल लैटिन अक्षर, संख्या, विशेष प्रतीक`,
  onlyNumbers: `केवल संख्या`,
  open: `(en) Open`,
  openGuestView: `अतिथि दृश्य खोलें`,
  openingSoon: `जल्द ही खुल रहा है!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `या`,
  password: `पासवर्ड`,
  payments: `भुगतान`,
  pleaseCheckYour: `कृपया जांच करें`,
  pleaseDropOnlyOneImage: `कृपया केवल एक छवि ड्रॉप करें`,
  pleaseEnterAtLeastNChars: (n) => `कृपया कम से कम एन वर्ण दर्ज करें`,
  pleaseFillOutYourDetails: `कृपया अपना विवरण भरें`,
  pleaseSignInToYourAccount: `कृपया अपने खाते में प्रवेश करें`,
  pleaseTryAgainOrClick: (n) => `कृपया पुनः प्रयास करें या ${n} पर क्लिक करें`,
  pleaseVerifyYourAccount: `कृपया अपने खाते को परखें`,
  pressHereTo: `यहाँ प्रेस करने से`,
  privacyPolicy: `निजता नीति`,
  profile: `प्रोफ़ाइल`,
  publishOn: (n) => `(en) Publish on ${n}`,
  save: `सेव`,
  saveAvatar: `अवतार सेव करें`,
  saveChanges: `परिवर्तनों को सेव करें`,
  selectAnime: `आनिमे को चुने`,
  selectAvatar: `अवतार को चुने`,
  selectCharacters: `करेक्टर को चुने`,
  selectFile: `फ़ाइल चुने`,
  selectThumbnail: `थंबनेल को चुने`,
  sendEmail: `ईमेल भेजें`,
  settings: `सेटिंग्स`,
  shareYourStory: `अपनी कहानी शेयर करें!`,
  shop: `दुकान`,
  showLess: `कम दिखाएं`,
  showMore: `ज्यादा दिखाएं`,
  signIn: `साइन इन करें`,
  skip: `आगे बड़ें`,
  socialMedia: `सोशल मीडिया`,
  spaceCharacterIsNotAllowed: `स्पेस करेक्टर की अनुमति नहीं है`,
  subscribeToTalentsToKeepUpWithTheirProgress: `उनकी प्रगति को बनाए रखने के लिए प्रतिभाओं की सदस्यता लें`,
  successChangedPasswordPleaseSignIn: `सफलता! पासवर्ड बदल दिया है।  कृपया साइन इन करें`,
  successCreatedRecord: `सफलता! रिकार्ड बना दिया गया है। `,
  successUpdatedRecord: `सफलता! रिकॉर्ड अपडेट किया गया है । `,
  supportMeOn: `मेरा समर्थन करें`,
  tellUsAboutYourself: `हमें अपने बारे में बताएं`,
  termsAndConditions: `नियम और शर्तें`,
  termsOfUse: `उपयोग की शर्तें`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `शीर्षक`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `अपना अक्षर यहां दर्ज करें...`,
  upload: `(en) Upload`,
  uploadAnotherArt: `एक और चित्रकला अपलोड करें`,
  uploadAnotherAvatar: `कोई और अवतार अपलोड करें`,
  uploadArtNow: `चित्रकला अभी अपलोड करें!`,
  uploadNew: `नया अपलोड करें`,
  uploadNewArt: `नई कला अपलोड करें`,
  uploadNewPost: `नया पोस्ट अपलोड करें`,
  username: `उपयोगकर्ता नाम`,
  usernameAlreadyExists: ` उपयोगकर्ता नाम पहले से ही मौजूद है`,
  valueIsNotTheSame: `दर्ज चीज़े सामान्य नहीं है `,
  verificationCode: `वेरीफिकेशन कोड`,
  verifyCode: `कोड वेरिफाए करें`,
  visitOurDiscordChannelToGetMoreDetails: `अधिक जानकारी प्राप्त करने के लिए हमारे कलह चैनल पर जाएं`,
  weAreOnInstagram: `हम इंस्टाग्राम पर हैं`,
  weAreWorkingOnIt: `हम इस पर काम कर रहें हैं`,
  weDoNotDisplayNSFWContentYet: `हम अभी तक एनएसएफडब्ल्यू कंटेंट प्रदर्शित नहीं करतें`,
  weHaveSentTooManyVerificationEmails: `हमने बहुत सारे वेरीफिकेशन मेल भेज दिए है`,
  welcomeToAnimeClub: `Anime.club में आपका स्वागत है!`,
  weSentAnEmailTo: `हमने इस पर ईमेल भेजा है:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `हमने आपको एक नया वेरीफिकेशन ईमेल भेजा है। कृपया कोड दर्ज करें`,
  weSupportOnlyTheFollowingFileExtensions: `हम केवल निम्नलिखित फ़ाइल एक्सटेंशन का समर्थन करते हैं:`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `गलत ईमेल या पासवर्ड`,
  yes: `हाँ`,
  youAreAlreadyAuthenticated: `आप पहले से ही प्रमाणीकृत हैं`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanStillNavigateToThePreviouslyOpenedPages: `आप अभी भी पहले खोले गए पेज पर जा सकते हैं`,
  youDidNotSelectAnyChats: `आपने कोई चैट नहीं चुनी हैं`,
  youDidNotUpdateAnyValues: `आपने कोई भी वैल्यू अपडेट नहीं करीं है`,
  youDoNotHaveAnyChats: `आपके पास कोई चैट नहीं हैं`,
  youHaveNotSavedAnyChanges: `आपने कोई परिवर्तन दर्ज नहीं किए हैं`,
  yourAccountIsVerifiedPleaseSignIn: `आपका खाता वेरिफाए हो चुका है। कृपया साइन इन करें`,
  yourArts: `आपकी चित्रकलाएँ`,
  yourAvatar: `आपका अवतार`,
  yourBlog: `आपका ब्लॉग`,
  yourFansAreWaiting: `अपके प्रशंसक इंतजार कर रहे हैं`,
  yourFeedIsEmpty: `आपका फ़ीड खाली है`,
  yourSessionHasExpiredPleaseSignInAgain: `आपका सेशन समाप्त हो गया है, कृपया फिर से साइन इन करें`,
}
