export const text: text = {
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `(en) Anime.club uses ${v[0]} to get you paid quickly and keep your personal and payment information secure`,
  clickTheButtonBelowToOpenYourStripeDashboard: `(en) Click the button below to open your Stripe dashboard and view your account details`,
  visitStripeDashboard: `(en) Visit Stripe dashboard`,
  files: `(en) Files`,
  prohibitedTransaction: `(en) Prohibited transaction`,
  uploadTheFilesYourBuyerWillGet: `(en) Upload the files your <b>buyer will get</b>`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `(en) Make sure everything is ready to go — no edits after publishing`,
  filesForTheBuyer: `(en) Files for the buyer`,
  filesForPreview: `(en) Files for preview`,
  needsYourReview: `(en) Needs Your Review`,
  awaitingSellersResponse: `(en) Awaiting seller's response`,
  buyersRequest: `(en) Buyer's request`,
  awaitingClientReview: `(en) Awaiting Client Review`,
  copy: `(en) Copy`,
  thankYouForYourPurchase: `(en) Thank you for your purchase!`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `(en) Great news! ${v[0]} purchased your item. Time to celebrate!`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `(en) @${v[0]} hasn't listed any products for sale yet`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `(en) @${v[0]} hasn’t added anything to their portfolio yet`,
  hideListing: `(en) Hide listing`,
  uploadUpToNumberFiles: (...v) => `(en) Upload up to <b>${v[0]}</b> files`,
  supportedFormats: `(en) Supported formats:`,
  minimumDimensions: (...v) => `(en) Minimum size: ${v[0]}×${v[1]} pixels`,
  maximumFileSize: (...v) => `(en) Maximum file size: <b>${v[0]}</b> per file`,
  thisListingWontBeVisibleToBuyersAnymore: `(en) This listing won’t be visible to buyers anymore — but you can show it again whenever you’re ready`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `(en) Buyers will be able to see this listing. You can hide it again anytime`,
  listingHiddenFromBuyers: `(en) Listing hidden from buyers`,
  listingIsNowVisibleToBuyers: `(en) Listing is now visible to buyers`,
  showListing: `(en) Show listing`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `(en) If there's no response by ${v[0]}, the order will be canceled automatically`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `(en) If no reply is received by ${v[0]}, you'll automatically receive a full refund`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `(en) If you miss the deadline, the buyer can cancel the order for a full refund, and any associated Stripe fees will be deducted from your payout.`,
  addAComment: `(en) Add a comment`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `(en) These rules are provided by the seller and apply only to this item`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `(en) If you have questions or concerns, please contact the seller directly`,
  platformPoliciesMayStillApply: `(en) Platform policies may still apply`,
  copiedToClipboard: `(en) Copied to clipboard`,
  uploadedFilesLocked: `(en) You uploaded these files when you created the post. They're now locked but still visible below`,
  new: `(en) New`,
  createPersonalizedWorkTailoredToEachRequest: `(en) Create personalized work tailored to each request`,
  offerDigitalProducts: `(en) Offer digital products that buyers can access right away`,
  instantDownload: `(en) Instant Download`,
  customWork: `(en) Custom Work`,
  allListings: `(en) All Listings`,
  newCommission: `(en) New commission`,
  noOrders: `(en) No orders`,
  buyNow: `(en) Buy now`,
  attachedFiles: `(en) Attached files`,
  numFilesIncluded: (...v) => `(en) <b>${v[0]}</b> file(s) included`,
  tellTheBuyersWhatTheyWillGet: `(en) Tell buyers exactly what they will get — for example, the number of illustrations, file formats, or canvas specs like resolution and DPI`,
  beSpecificAboutTheContent: `(en) Be specific about the content (e.g. number of files, formats, canvas resolution)`,
  mentionYourDeliveryTimeInDays: `(en) Mention your <b>delivery time</b> (in days)`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `(en) Let buyers know if you offer <b>revisions</b>, and how many`,
  listAnyContentOrRequestsYouDontAccept: `(en) List any content or requests you <b>don't accept</b> (e.g. NSFW, political, religious, or offensive material)`,
  offerOptionalExtras: `(en) Offer optional extras like <b>rush delivery</b>, an <b>extra character</b>, or a <b>detailed background</b>`,
  extrasHelpBoostIncome: `(en) Extras help buyers customize their order and can boost your income`,
  pleaseAllowPopups: `(en) Please allow popups`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `(en) You'll be able to download your files immediately after purchase—no waiting required!`,
  orderAOneOfAKindCustomPieceCraftedToMatchYourVision: `(en) Order a one-of-a-kind custom piece, crafted to match your vision`,
  youAreCoveredIfThereIsAProblem: `(en) You're covered! If there's a problem and the dispute is valid, you'll get 100% of your money back`,
  artGallery: `(en) Art Gallery`,
  commission: `(en) Commission`,
  commissions: `(en) Commissions`,
  digitalDownloads: `(en) Digital Downloads`,
  changesSaved: `(en) Changes saved!`,
  setUpStripeAccountToGetPaidWithAnimeClub: `(en) Set up a Stripe account to get paid with Anime.club`,
  sellerTermsOfService: `(en) Seller Terms of Service`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `(en) Describe what’s included and what the buyer can expect after purchase`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `(en) The reason you provide for cancelling this order will be shared with the buyer`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `(en) Optionally, you can add a description to share more about your creation`,
  pleaseProvideATitleForYourArtwork: `(en) Please provide a title for your artwork`,
  usernameStartedFollowingYou: (...v) =>
    `(en) <b>${v[0]}</b> started following you`,
  usernameLeftAReaction: (...v) => `(en) <b>${v[0]}</b> left a reaction`,
  vote: `(en) Vote`,
  tapAddToCreateOne: `(en) Tap “Add” to create one`,
  reply: `(en) Reply`,
  replyToUsername: (...v) => `(en) Reply to ${v[0]}`,
  numOfReplies: (...v) => `(en) ${v[0]} replies`,
  youCanChooseFromTheListOrEnterACustomReason: `(en) You can choose from the list or enter a custom reason`,
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  _hyphen: `- `,
  about: `Tentang`,
  accept: `Terima`,
  acceptOrder: `Terima pesanan`,
  acceptTheOrder: `Terima pesanan`,
  accountManagment: `Manajemen akun`,
  account: `Akun`,
  accountDeleted: `Akun dihapus`,
  animeShopBuyAndSellProducts: `Toko anime - beli dan jual produk`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `Gambar yang dihasilkan AI dan filter jaringan saraf dilarang`,
  accountActivation: `Aktivasi Akun`,
  accountAlreadyExists: `Akun sudah ada`,
  accountDoesNotExist: `Akun tidak tersedia`,
  accountRemoval: `Penghapusan akun`,
  add: `Tambahkan`,
  addArt: `Tambahkan karya`,
  addBlog: `Tambahkan blog`,
  additionalResources: `Sumber daya tambahan`,
  addMoreProductsToYourShop: `Tambahkan lebih banyak produk ke toko Anda`,
  addMore: `Tambah lagi`,
  addNewArt: `Tambahkan karya baru`,
  addSignInVia: `Log masuk melalui`,
  addToCart: `Tambah ke keranjang`,
  advancedOptions: `Opsi lanjutan`,
  all: `Semua`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `Semua file yang Anda unggah di sini akan tersedia untuk pembeli`,
  alreadySignedIn: `Anda sudah masuk`,
  amount: `Jumlah`,
  amountShouldNotBeLessThan: (...v) => `Jumlah tidak boleh kurang dari ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Karya anime oleh seniman dari berbagai belahan dunia. Karya dikurasi terkait anime. Seleksi karya adalah daftar panjang karya anime terbaik`,
  animeArtSubscribeToArtistsLikeAndCreate: `Karya anime - berlanggangan ke seniman, sukai, dan buat koleksi`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - platform pertama yang memberikan bayaran pada seniman dari tampilan di Google Adsense. Dukung para seniman dengan melihat konten mereka atau mulai menghasilkan dari menampilkan karya`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - lihat, unggah, dan menghasilkan dari konten anime`,
  animeCommunity: `Komunitas anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club tidak pernah meminta informasi pribadi Anda`,
  animeSocialNetwork: `Jaringan Sosial Anime`,
  announcements: `Pengumuman`,
  apply: `Terapkan`,
  appSettings: `Pengaturan aplikasi`,
  appsVersionIs: `Versi aplikasi `,
  areYouSureYouWantTo: `Apa Anda yakin Anda ingin`,
  art: `Karya`,
  artAssociatedWithAnime: `Karya terkait anime`,
  artBy: (...v) => `Seni oleh ${v[0]}`,
  artCannotBeChanged: `Karya tidak dapat diubah`,
  artworksAvailableToView: (...v) =>
    `${v[0]} karya seni tersedia untuk dilihat`,
  authenticationFailed: `Autentikasi gagal`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Penerbitan otomatis ke Instagram hanya tersedia untuk akun bisnis Instagram`,
  attentionYourOrderHasBeenDisputed: `Perhatian! Pesanan Anda telah dipersengketakan. Silakan periksa detailnya`,
  back: `Kembali`,
  basePrice: `Harga dasar`,
  bigAppreciationToTheSellerForTheHardWork: `Apresiasi besar untuk penjual atas kerja kerasnya`,
  block: `Blokir`,
  buyerReviewedTheOrder: `Pembeli telah meninjau pesanan`,
  buyerHasNotLeftAReviewYet: `Pembeli belum meninggalkan ulasan`,
  feedbackReceived: `Umpan balik diterima!`,
  blockUser: (...v) => `Blokir @${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `Sebelum menerima, harap tinjau permintaan pembeli dengan cermat`,
  blog: `Blog `,
  bookmarks: `Markah`,
  browseArt: `Jelajahi karya`,
  browseShop: `Jelajahi toko`,
  buyer: `Pembeli`,
  cancel: `batalkan`,
  canceled: `Dibatalkan`,
  cancelOrder: `Batalkan pesanan`,
  cannotStartWithChars: `Tidak dapat memulai dengan {:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Ubah`,
  checkOutMyShop: `Lihat toko saya`,
  checkOrderStatus: `Periksa status pesanan`,
  changeArt: `Ubah karya`,
  changeAvatar: `Ubah avatar`,
  changeEmail: `Ubah email`,
  changePassword: `Ubah kata sandi`,
  chooseExistingChatOrStartANewOne: `Pilih obrolan yang ada atau mulai baru`,
  city: `Kota`,
  clearAll: `Bersihkan semua`,
  close: `Tutup`,
  colorTheme: `Tema warna`,
  comingSoon: `Segera...`,
  commercialUseAllowed: `Penggunaan komersial diizinkan`,
  commercialUseAllowsBuyersToUseYourProduct: `Penggunaan komersial memungkinkan pembeli menggunakan produk Anda untuk tujuan bisnis, seperti menjual atau mempromosikan layanan mereka`,
  community: `Komunitas`,
  completed: `Selesai`,
  confirmAccount: `Konfirmasi akun`,
  confirmOrder: `Konfirmasi pesanan`,
  confirmPassword: `Konfirmasi Kata Sandi`,
  connectWithUsOn: `Terhubung dengan kami di`,
  contactInformation: `Informasi kontak`,
  contactSeller: `Hubungi penjual`,
  contactSupport: `Hubungi dukungan`,
  contactUs: `Hubungi kami`,
  continue: `Lanjutkan`,
  contractTitle: `Judul kontrak`,
  congratulations: `Selamat!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `Selamat atas keberhasilan menyelesaikan pesanan Anda!`,
  copyrightViolation: `Pelanggaran hak cipta`,
  couldNotCreateANewRecord: `Tidak dapat membuat catatan baru`,
  country: `Negara`,
  cover: `Sampul`,
  createANewAccountFailed: `Gagal membuat akun baru`,
  createExtrasForYourProduct: `Buat ekstra untuk produk Anda`,
  createNewAccount: `Membuat akun baru`,
  createAShopWithStripe: `Buat toko dengan Stripe`,
  createdBy: `Dibuat oleh`,
  currentPassword: `Kata sandi saat ini`,
  daily: `Harian`,
  darkDefault: `Tema gelap default`,
  darkHighContrast: `Tema gelap kontras tinggi`,
  dayTheme: `Tema siang`,
  delete: `Hapus`,
  deleteShop: `Hapus toko`,
  deleteAccount: `Hapus akun`,
  deleteArt: `Hapus karya`,
  decline: `Tolak`,
  deletePost: `Hapus postingan`,
  deleteProduct: `Hapus produk`,
  download: `Unduh`,
  downloadThemBelow: `Unduh di bawah ini`,
  deliveryTime: `Waktu pengiriman`,
  describeTheDetailsOfYourExtra: `Jelaskan detail ekstra Anda`,
  description: `Deskripsi`,
  details: `Detail`,
  didntReceiveEmail: `Tidak menerima email?`,
  displayName: `Nama tampilan`,
  disputed: `Disengketakan`,
  donations: `Donasi`,
  done: `Selesai`,
  dragAndDropOrSelectFiles: `Seret dan lepaskan atau pilih file`,
  drawingContest: `Kontes menggambar`,
  dueDate: `Batas waktu`,
  earlier: `Lebih awal`,
  earningFromArts: `Menghasilkan dari karya`,
  edit: `Edit`,
  editPost: `Edit postingan`,
  editProfile: `Edit profil`,
  editTranslations: `Rubah terjemahan`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email telah digunakan oleh seseorang`,
  emailNotifications: `Notifikasi email`,
  enterOrPasteALink: `Masuk atau tempelkan tautan`,
  enjoyYourPurchase: `Nikmati pembelian Anda! 😊`,
  enterTheAddressAssociatedWithYourAccount: `Masukkan alamat yang terkait dengan akun Anda, dan kami akan mengirimkan tautan untuk mereset kata sandi Anda melalui email`,
  enterYourPassword: `Masukkan kata sandi Anda`,
  error: `Kesalahan`,
  errorPleaseContactCustomerSupport: `Error! Silakan hubungi layanan pelanggan...`,
  exitWithoutSaving: `Keluar tanpa menyimpan`,
  extensions: `Ekstensi`,
  extras: `Ekstra`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `Ekstra adalah tambahan opsional untuk meningkatkan produk Anda`,
  fileSizeIsTooBig: `Ukuran file terlalu besar`,
  fileSizeIsTooSmall: `Ukuran file terlalu kecil`,
  filter: `Filter`,
  filterBy: `Filter berdasarkan`,
  findUser: `Temukan pengguna`,
  finishSettingUpYourShop: `Selesaikan pengaturan toko Anda`,
  follow: `Ikuti`,
  followers: `Pengikut`,
  following: `Mengikuti`,
  followMeOn: `Ikuti saya di`,
  follows: `Mengikuti`,
  forAllOtherInquiriesPleaseContactUsAt: `Untuk pertanyaan lain, silakan hubungi kami di:`,
  forgotPassword: `Lupa kata sandi`,
  fromAnimeDotClub: `Dari anime.club`,
  getDetails: `Dapatkan detail`,
  getStarted: `Mulai`,
  guestView: `Tampilan Pengunjung`,
  greatNewsYourOrderIsNowInProgress: `Berita baik! Pesanan Anda sedang diproses`,
  harassment: `Pelecehan`,
  haveAnyQuestions: `Ada pertanyaan?`,
  usernameHasCanceledTheOrder: (...v) =>
    `<b>${v[0]}</b> telah membatalkan pesanan`,
  usernameHasSubmittedTheWork: (...v) =>
    `<b>${v[0]}</b> telah mengirimkan karya`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]} belum menambahkan deskripsi untuk "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} belum membagikan detail publik apa pun`,
  hate: `Kebencian`,
  hereAreAFewWaysToGetThingsRolling: `Berikut beberapa cara untuk memulai`,
  hire: `Merekrut`,
  homepage: `Beranda`,
  howToContactYou: `Cara menghubungi Anda`,
  howToFindYouOnOtherSocialNetworks: `Cara menemukan Anda di jaringan sosial lainnya`,
  iAgreeWith: `Saya setuju`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Jika tidak ada tanggapan hingga ${v[0]}, pesanan akan otomatis ditandai sebagai selesai`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Tinggi gambar harus lebih besar atau sama dengan`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Lebar gambar harus lebih besar atau sama dengan`,
  impersonation: `Pemalsuan identitas`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Sertakan kata kunci yang kemungkinan akan digunakan pembeli untuk mencari produk seperti milikmu`,
  inProgress: `Sedang berlangsung`,
  introduction: `Pendahuluan`,
  includes: `Termasuk`,
  invalidCode: `Kode tidak valid`,
  invalidCurrentPassword: `Kata sandi saat ini tidak valid`,
  invalidDate: `Tanggal tidak valid`,
  invalidPartAfterAt: `Bagian tidak valid setelah @`,
  invalidPartBeforeAt: `Bagian tidak valid sebelum @`,
  jobDetails: `Detail pekerjaan`,
  joinAnimeClubCommunity: `Bergabunglah dengan komunitas Anime.club dengan ribuan kreator aktif dan seni anime keren setiap hari`,
  joinChat: `Bergabung dalam obrolan`,
  joinUsOnFacebook: `Ikuti kami di facebook`,
  language: `Bahasa`,
  lackOfInformation: `Kurangnya informasi`,
  languages: `Bahasa`,
  letEveryoneKnowHowToDonateToYou: `Biarkan semua orang tahu cara mendonasikan kepadamu`,
  letOthersKnowAboutYou: `Biarkan orang lain tahu tentangmu`,
  letsUploadYourFirstProduct: `Mari unggah produk pertama Anda`,
  letUsKnowWhatsHappening: `Beritahu kami apa yang terjadi dan kami akan memeriksanya`,
  lightDefault: `Tema default terang`,
  lightHighContrast: `Tema terang kontras tinggi`,
  likes: `Suka`,
  limit: `Batas`,
  livesIn: `Tinggal di`,
  loading: `Memuat`,
  location: `Lokasi`,
  logInOrSignUp: `Masuk atau daftar`,
  logOut: `Keluar`,
  maximumNChars: (...v) => `Paling banyak ${v[0]} karakter`,
  maximumNumberOfDaysToCompleteTheOrder: `Jumlah maksimum hari untuk menyelesaikan pesanan`,
  maximumQuantity: `Jumlah maksimum`,
  maxSize: `Ukuran maksimum`,
  menu: `Menu`,
  message: `Pesan`,
  messages: `Pesan`,
  minHeight: `Tinggi minimum`,
  minimumNChars: (...v) => `Paling sedikit ${v[0]} karakter`,
  minorAbuseOrSexualization: `Pelecehan atau seksualisasi minor`,
  makeSureToIncludeClearInstructions: `Pastikan untuk menyertakan instruksi yang jelas tentang cara menggunakan setiap referensi`,
  makeSureYouFullyUnderstandTheRequirements: `Pastikan Anda benar-benar memahami persyaratan dan dapat menyelesaikan pesanan tepat waktu`,
  makeSureYourProductsArePricedCompetitively: `Pastikan produk Anda diberi harga yang kompetitif`,
  minWidth: `Lebar minimum`,
  monthly: `Bulanan`,
  moreFrom: (...v) => `Lebih lanjut dari (${v[0]})`,
  mustBeNChars: (...v) => `Harus ${v[0]} karakter`,
  myPayments: `Pembayaran saya`,
  myProfile: `Profil saya`,
  mySettings: `Pengaturan saya`,
  need1Lowercase: `Perlu 1 huruf kecil`,
  need1Number: `Perlu 1 angka`,
  need1Uppercase: `Perlu 1 huruf besar`,
  needAtLeast1CharacterFromN: (...v) =>
    `Perlu paling tidak 1 karakter dari [${v[0]}]`,
  needNCharacter: (...v) => `Perlu ${v[0]} karakter`,
  newAccount: `Akun baru`,
  newArt: `Karya baru`,
  newArtworks: `Karya seni baru`,
  newBlog: `Blog baru`,
  newOrder: `Pesanan baru`,
  newPassword: `Kata Sandi Baru`,
  newProduct: `Produk baru`,
  newsFeed: `Umpan berita`,
  next: `Berikutnya`,
  nextTimeYouAuthenticateYouCouldUseThe: `Kali berikutnya saat Anda mengautentikasi, Anda dapat menggunakan akun terhubung, bukan login dan kata sandi`,
  nightTheme: `Tema malam`,
  no: `tidak`,
  noInternetConnection: `Tidak ada koneksi internet!`,
  nonConsensualIntimateContent: `Konten intim tanpa persetujuan`,
  none: `Tidak ada`,
  noNotifications: `Tidak ada notifikasi`,
  noResults: `Tidak ada hasil`,
  noReviewsJustYet: `Belum ada ulasan`,
  notifications: `Notifikasi`,
  noActiveOrdersToShow: `Tidak ada pesanan aktif untuk ditampilkan`,
  notAcceptingOrders: `Tidak menerima pesanan`,
  noSalesYetNoWorries: `Belum ada penjualan? Jangan khawatir, Anda baru memulai`,
  nsfwContent18Plus: `Konten NSFW (18+)`,
  NSFWIndicatesAdultContent: `18+ NSFW menunjukkan konten dewasa. Centang ini hanya jika produk Anda untuk audiens dewasa`,
  numberOfAdjustmentsAClientCouldRequest: `Jumlah penyesuaian yang dapat diminta klien`,
  online: `Daring`,
  onlyLatinLettersNumbersHyphen: `Hanya huruf latin, angka, tanda hubung, garis bawah, dan titik`,
  onlyNumbers: `Hanya angka`,
  onlyYouCanSeeWhatYouveSaved: `Hanya Anda yang dapat melihat apa yang telah Anda simpan`,
  open: `Buka`,
  openDispute: `Buka sengketa`,
  openGuestView: `Buka tampilan pengunjung`,
  openingSoon: `Segera hadir!`,
  openToWork: `Terbuka untuk bekerja`,
  optional: `Opsional`,
  requestDetails: `Detail permintaan`,
  or: `ATAU`,
  order: `Pesanan`,
  outOfStock: `Kehabisan stok`,
  ordered: (...v) => `Dipesan ${v[0]}`,
  orderAgain: `Pesan lagi`,
  orderDetails: `Detail pesanan`,
  orderConfirmed: `Pesanan dikonfirmasi`,
  orderCompleted: `Pesanan selesai 🎉`,
  orderStatus: `Status pesanan`,
  orderOptions: `Opsi pesanan`,
  otherReason: `Alasan lain`,
  pageNotFound: `Halaman tidak ditemukan`,
  password: `Kata sandi`,
  payments: `Pembayaran`,
  personal: `Pribadi`,
  personalCircumstances: `Keadaan pribadi`,
  pleaseCheckYour: (...v) => `Silakan periksa ${v[0]} Anda`,
  pleaseRateYourOrder: `Silakan beri peringkat pesanan Anda`,
  feelFreeToShareReferenceImagesAndMaterials: `Silakan bagikan gambar referensi dan materi untuk membantu seniman membuat karya Anda`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Mohon jangan membagikan informasi pribadi Anda kepada orang lain`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `Silakan masukkan angka antara ${v[0]} dan ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) =>
    `Harap masukkan paling tidak ${v[0]} karakter`,
  pleaseFillOutYourDetails: `Silakan isi data lengkap Anda`,
  pleaseFixTheErrorsBeforeSubmitting: `Harap perbaiki kesalahan sebelum mengirimkan`,
  pleaseSignInToYourAccount: `Silakan masuk ke akun Anda`,
  platform: `Platform`,
  pleaseStartTyping: `Silakan mulai mengetik`,
  pleaseTakeAMomentToReviewTheOrder: `Luangkan waktu sejenak untuk meninjau pesanan`,
  pleaseReviewTheBuyersReferenceFiles: `Harap tinjau file referensi pembeli dan ikuti sesuai deskripsi pesanan`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `Harap tinjau detailnya dengan cermat sebelum melanjutkan`,
  pleaseRespondToTheOrderBy: (...v) => `Harap tanggapi pesanan sebelum ${v[0]}`,
  pleaseTryAgainOrClick: (...v) =>
    `Silakan coba sekali lagi atau klik (${v[0]})`,
  pleaseVerifyYourAccount: `Silakan verifikasi akun Anda`,
  pressHereTo: `Tekan di sini untuk`,
  price: `Harga`,
  payouts: `Pembayaran`,
  privacyPolicy: `Kebijakan kerahasiaan`,
  privateInformation: `Informasi pribadi`,
  proceedToCheckout: `Lanjut ke Checkout`,
  product: `Produk`,
  itemReviews: `Ulasan item`,
  portfolio: `Portofolio`,
  profile: `Profil`,
  promotions: `Promosi`,
  publicInformation: `Informasi publik`,
  publishOn: (...v) => `Terbitkan pada ${v[0]}`,
  purchases: `Pembelian`,
  rankings: `Peringkat`,
  reorderFiles: `Urutkan ulang file`,
  report: `Laporkan`,
  review: `Ulasan`,
  rules: `Aturan`,
  reviews: `Ulasan`,
  numOfReviews: (...v) => `Ulasan: ${v[0]} `,
  reviewed: `Ditinjau`,
  reviewTitle: `Judul ulasan`,
  reason: `Alasan`,
  revisions: `Revisi`,
  includesXRevisionS: (...v) => `Termasuk ${v[0]} revisi`,
  sales: `Penjualan`,
  save: `Simpan`,
  saveAvatar: `Simpan avatar`,
  saveChanges: `Simpan perubahan`,
  selectAnime: `Pilih Anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Pilih satu tema atau sinkronkan dengan sistem Anda dan beralih secara otomatis antara tema siang dan malam`,
  selectAvatar: `Pilih Avatar`,
  selectCharacters: `Pilih Karakter`,
  seller: `Penjual`,
  selectFile: `Pilih file`,
  selectTheme: `Pilih tema`,
  selectThumbnail: `Pilih gambar mini`,
  selfHarmOrSuicide: `Cedera diri atau bunuh diri`,
  sendEmail: `Kirim email`,
  settings: `Pengaturan`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Mendirikan toko gratis dan hanya membutuhkan beberapa menit`,
  share: `Bagikan`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `Bagikan aturan Anda dan jenis permintaan yang tidak Anda terima`,
  shareYourShopOnSocialMedia: `Bagikan toko Anda di media sosial`,
  shareYourFavoritePiecesOn: (...v) => `Bagikan karya favorit Anda di ${v[0]}`,
  shareYourArtWithTheWorld: `Bagikan seni Anda dengan dunia`,
  shareYourStory: `Bagikan kisah Anda!`,
  sharingPersonalInformation: `Berbagi informasi pribadi`,
  shop: `Belanja`,
  shopReviews: `Ulasan toko`,
  shopOrders: `Pesanan toko`,
  showLess: `Tunjukkan lebih sedikit`,
  showMore: `Tunjukkan lebih banyak`,
  signIn: `Masuk`,
  singleTheme: `Tema tunggal`,
  size: `Ukuran`,
  skip: `Lewati`,
  socialMedia: `Media sosial`,
  spaceCharacterIsNotAllowed: `Karakter spasi tidak dibolehkan`,
  spam: `Spam`,
  yourFavoritesWillShowUpHereAddSome: `Favorit Anda akan muncul di sini. Tambahkan beberapa!`,
  submitAReport: `Kirim laporan`,
  submitWork: `Kirim karya`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Ikuti si kreator untuk mendapatkan pembaruan mereka`,
  successChangedPasswordPleaseSignIn: `Berhasil! Mengubah kata sandi. Silakan masuk`,
  successCreatedRecord: `Berhasil! Catatan dibuat!`,
  successfullyDownloaded: `Berhasil diunduh!`,
  successfullyUploaded: `Berhasil diunggah!`,
  supportMeOn: `Dukung saya di`,
  syncWithSystem: `Sinkronkan dengan sistem`,
  tellUsAboutYourself: `Ceritakan diri Anda`,
  termsAndConditions: `Syarat dan Ketentuan`,
  termsOfUse: `Syarat penggunaan`,
  thankYouForReport: `Terima kasih telah membantu menjaga komunitas online yang aman dan menghormati`,
  thankYouForYourReview: `Terima kasih atas ulasan Anda!`,
  theLinkIsBrokenOrPageHasBeenRemoved: `Tautan rusak atau halaman telah dihapus`,
  themeMode: `Mode tema`,
  thisIsThePriceYouPropose: `Ini adalah harga yang Anda ajukan`,
  thisFieldIsOptional: `Bidang ini opsional`,
  thisCannotBeUndone: `Ini tidak dapat dibatalkan`,
  ensureYouveUploadedTheFinalVersion: `Pastikan Anda telah mengunggah versi final sebelum mengirimkan`,
  threateningViolence: `Ancaman kekerasan`,
  title: `Judul`,
  timeConstraints: `Keterbatasan waktu`,
  titleYourExtraService: `Beri judul pada layanan tambahan Anda`,
  theMaximumQuantityThatACustomerCanAdd: `Jumlah maksimum yang dapat ditambahkan oleh pelanggan`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `Periode ulasan dibatasi hingga ${v[0]} hari`,
  toHelpTheCreatorCompleteYourOrder: `Untuk membantu pembuat menyelesaikan pesanan Anda dengan memuaskan, silakan berikan deskripsi rinci tentang apa yang Anda inginkan. Sertakan tema yang diinginkan, gaya, dan fitur karakter, serta spesifikasi penting lainnya`,
  today: `Hari ini`,
  toGetWorkRelatedNotifications: `Untuk mendapatkan pemberitahuan terkait pekerjaan`,
  total: `Total`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Untuk melihat data ini, Anda perlu membuka blokir @${v[0]}`,
  trademarkViolation: `Pelanggaran merek dagang`,
  typeYourTextHere: `Ketikkan teks Anda di sini...`,
  theSellerHasUploadedTheseFilesForYou: `Penjual telah mengunggah file ini untuk Anda`,
  unblock: `Buka blokir`,
  unblockUser: (...v) => `Buka blokir @${v[0]}`,
  unfollow: `Berhenti mengikuti`,
  unlimited: `Tidak terbatas`,
  upload: `Unggah`,
  uploadNew: `Unggah baru`,
  uploadNewPost: `Unggah postingan baru`,
  uploadNewProduct: `Unggah produk baru`,
  username: `Nama pengguna`,
  pleaseUploadOnlyFinishedWorkHere: `Harap hanya unggah karya yang sudah selesai di sini`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `Semua file terkait WIP harus diunggah di pesan`,
  usernameAlreadyExists: `Nama pengguna sudah ada`,
  usernameAndXMoreFollowYou: (...v) =>
    `<b>${v[0]}</b> dan ${v[1]} lagi mengikuti Anda`,
  usernameAndXMoreReacted: (...v) =>
    `<b>${v[0]}</b> dan ${v[1]} lainnya bereaksi`,
  useThisEmailTo: `Gunakan email ini untuk: mengautentikasi, menerima notifikasi`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `Sayangnya, ${v[0]} harus membatalkan pesanan ini`,
  valueIsNotTheSame: `Isian tidak sama`,
  verificationCode: `Verifikasi Kode`,
  verifyCode: `Memverifikasi kode`,
  viewDetails: `Lihat detail`,
  viewReview: `Lihat ulasan`,
  viewEveryNotificationOfAGroupSeparately: `Lihat setiap notifikasi dari grup secara terpisah`,
  visitOurDiscordChannelToGetMoreDetails: `Gabung dengan Discord untuk mendapatkan info lebih lanjut`,
  weAreOnInstagram: `Kami ada di Instagram`,
  weAreWorkingOnIt: `Kami sedang mengatasinya`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `Kerja bagus! Karya berhasil diselesaikan`,
  weDoNotDisplayNSFWContentYet: `Kami belum menampilkan konten NSFW`,
  weekly: `Mingguan`,
  whenYouPurchaseSomethingItWillAppearHere: `Ketika Anda membeli sesuatu, itu akan muncul di sini`,
  weHaveSentTooManyEmails: `Kami telah mengirim terlalu banyak email, silakan coba lagi nanti atau hubungi dukungan pelanggan`,
  welcomeToAnimeClub: `Selamat datang di Anime.club!`,
  weSentAnEmailTo: `Kami mengirim email ke:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Kami telah mengirimkan email verifikasi baru. Silakan masukkan kodenya`,
  weAreExcitedToSeeYourProgressKeepItUp: `Kami senang melihat kemajuan Anda. Teruskan!`,
  weSupportOnlyTheFollowingFileExtensions: `Kami hanya mendukung file dengan ekstensi berikut:`,
  work: `Karya`,
  weWouldLoveToHearFromYou: `Kami ingin mendengar dari Anda`,
  workDescription: `Deskripsi karya`,
  leaveAReview: `Tinggalkan ulasan`,
  wrongEmailOrPassword: `Surel atau kata sandi salah`,
  yes: `Ya`,
  yesterday: `Kemarin`,
  youReceivedANewOrderFrom: (...v) =>
    `Anda menerima pesanan baru dari <b>${v[0]}</b>`,
  youReceivedAReview: `Anda menerima ulasan`,
  youHaveSuccessfullyCreatedYourShop: `Anda telah berhasil membuat toko Anda`,
  youAreAlreadyAuthenticated: `Anda sudah terauntentikasi`,
  youCanAutoPublishToYourSocialMediaAccount: `Anda dapat mempublikasikan secara otomatis ke akun media sosial Anda`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Anda dapat mengubah jenis pemberitahuan yang Anda terima melalui email`,
  youCanRequestRemovalOfYourAccount: `Anda dapat meminta penghapusan akun Anda beserta semua data Anda`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `Umpan balik Anda membimbing pembeli dan membantu penjual menawarkan produk yang lebih baik`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Anda masih bisa berpindah ke halaman yang sebelumnya terbuka`,
  youDidNotSelectAnyChats: `Anda belum memilih obrolan`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `Anda akan melihat ulasan di sini setelah pembeli membagikan pengalaman mereka`,
  youDidNotUpdateAnyValues: `Anda tidak memperbarui apapun`,
  youDoNotHaveAnyChats: `Anda tidak punya obrolan`,
  youHaveNotSetAPassword: `Anda belum mengatur kata sandi`,
  youHaveNotSharedAnythingYet: `Anda belum membagikan apa pun`,
  youHaveReachedTheMaximumNumberOfFiles: `Anda telah mencapai jumlah maksimum file`,
  kindlyHoldOnForTheBuyersReview: `Mohon tunggu ulasan pembeli tentang pesanan.`,
  yourAccountIsVerifiedPleaseSignIn: `Akun anda sudah terverifikasi. Silakan masuk`,
  yourAccountWillBeRemoved: (...v) => `Akun Anda akan dihapus ${v[0]}`,
  youHaveNoPurchases: `Anda tidak memiliki pembelian`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Bisakah Anda memberikan alasan pembatalan`,
  yourArts: `Karya Anda`,
  youCanceledTheOrder: `Anda membatalkan pesanan`,
  yourAvatar: `Avatar Anda`,
  yourBlog: `Blog Anda`,
  yourFansAreWaiting: `Penggemar anda sudah menunggu`,
  yourFeedIsEmpty: `Umpan anda kosong`,
  yourSessionHasExpiredPleaseSignInAgain: `Sesi anda sudah berakhir, silakan Login lagi`,
}
