export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  about: `Tentang`,
  accountActivation: `Aktivasi Akun`,
  accountAlreadyExists: `Akun sudah ada`,
  accountDoesNotExist: `Akun tidak tersedia`,
  add: `Tambahkan`,
  addArt: `Tambahkan karya`,
  addBlog: `Tambahkan blog`,
  addedNAgo: (n) => `Tambahkan ${n} dulu`,
  addNewArt: `Tambahkan karya baru`,
  addPreview: `Tambahkan pratayang`,
  animeArtByArtistsFromAllOverTheWorld: `Karya anime oleh seniman dari berbagai belahan dunia. Karya dikurasi terkait anime. Seleksi karya adalah daftar panjang karya anime terbaik`,
  animeArtSubscribeToArtistsLikeAndCreate: `Karya anime - berlanggangan ke seniman, sukai, dan buat koleksi`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - platform pertama yang memberikan bayaran pada seniman dari tampilan di Google Adsense. Dukung para seniman dengan melihat konten mereka atau mulai menghasilkan dari menampilkan karya`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - lihat, unggah, dan menghasilkan dari konten anime`,
  animeCommunity: `Komunitas anime`,
  animeOnly: `Hanya anime`,
  appsVersionIs: `Versi aplikasi `,
  areYouSureYouWantTo: `Apa Anda yakin Anda ingin`,
  art: `Karya`,
  artAssociatedWithAnime: `Karya terkait anime`,
  artBy: `Karya oleh`,
  artCannotBeChanged: `Karya tidak dapat diubah`,
  authenticationFailed: `Autentikasi gagal`,
  back: `Kembali`,
  blog: `Blog `,
  browseArt: `Jelajahi karya`,
  cancel: `batalkan`,
  cannotStartWithChars: `Tidak dapat memulai dengan {:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  changeArt: `Ubah karya`,
  changeAvatar: `Ubah avatar`,
  changePassword: `Ubah kata sandi`,
  city: `Kota`,
  clearAll: `Bersihkan semua`,
  close: `Tutup`,
  comingSoon: `Segera...`,
  community: `Komunitas`,
  confirmAccount: `Konfirmasi akun`,
  confirmPassword: `Konfirmasi Kata Sandi`,
  copyLink: `(en) Copy link`,
  couldNotCreateANewRecord: `Tidak dapat membuat catatan baru`,
  country: `Negara`,
  createANewAccountFailed: `Gagal membuat akun baru`,
  createNewAccount: `Membuat akun baru`,
  delete: `Hapus`,
  deleteArt: `(en) Delete art`,
  deletePost: `(en) Delete post`,
  description: `Deskripsi`,
  details: `Detail`,
  didntReceiveEmail: `Tidak menerima email?`,
  donations: `(en) Donations`,
  done: `Selesai`,
  earningFromArts: `Menghasilkan dari karya`,
  editArt: `Edit karya`,
  editPost: `Edit postingan`,
  editProfile: `Edit profil`,
  editTranslations: `(en) Edit translations`,
  email: `Email`,
  emailSubscription: `Berlanggganan Email`,
  error404NotFound: `Error 404 - Tidak ditemukan`,
  errorPleaseContactCustomerSupport: `Error! Silakan hubungi layanan pelanggan...`,
  exitEditor: `Keluar dari Editor`,
  extensions: `Ekstensi`,
  favorites: `(en) Favorites`,
  fileSizeIsTooBig: `Ukuran file terlalu besar`,
  filter: `Filter`,
  filterBy: `Filter berdasarkan`,
  follow: `Ikuti`,
  followMeOn: `Ikuti saya di`,
  followUsOnTwitter: `Ikuti kami di Twitter`,
  forAllOtherInquiriesPleaseContactUsAt: `Untuk pertanyaan lain, silakan hubungi kami di:`,
  forgotPassword: `Lupa kata sandi`,
  forNewMasterpieces: `Untuk mahakarya baru`,
  four04: `— 404! —`,
  guestView: `Tampilan Pengunjung`,
  homepage: `Beranda`,
  iAgreeWith: `Saya setuju`,
  id: `(en) ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Tinggi gambar harus lebih besar atau sama dengan`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Lebar gambar harus lebih besar atau sama dengan`,
  introduction: `Pendahuluan`,
  invalidCode: `Kode tidak valid`,
  invalidPartAfterAt: `Bagian tidak valid setelah @`,
  invalidPartBeforeAt: `Bagian tidak valid sebelum @`,
  joinChat: `Bergabung dalam obrolan`,
  joinUsOnFacebook: `Ikuti kami di facebook`,
  livingIn: `Tinggal di`,
  logout: `Keluar`,
  maximumNChars: (n) => `Paling banyak ${n} karakter`,
  maxSize: `Ukuran maksimum`,
  menu: `Menu`,
  minHeight: `Tinggi minimum`,
  minimumNChars: (n) => `Paling sedikit ${n} karakter`,
  minWidth: `Lebar minimum`,
  mustBeNChars: (n) => `Harus ${n} karakter`,
  need1Lowercase: `Perlu 1 huruf kecil`,
  need1Number: `Perlu 1 angka`,
  need1Uppercase: `Perlu 1 huruf besar`,
  needAtLeast1CharacterFromN: (n) => `Perlu paling tidak 1 karakter dari [${n}]`,
  needNCharacter: (n) => `Perlu ${n} karakter`,
  newAccount: `Akun baru`,
  newArt: `Karya baru`,
  newBlog: `Blog baru`,
  newPassword: `Kata Sandi Baru`,
  newsFeed: `(en) News feed`,
  no: `tidak`,
  noAddedFavoriteArts: `(en) no added favorite arts`,
  noInternetConnection: `Tidak ada koneksi internet!`,
  nsfwContent18Plus: `Konten NSFW (18+)`,
  ohNoItIsNotHere: `Oh tidak! Tidak ada di sini!`,
  oldPassword: `Kata Sandi Lama`,
  onlyHexNumbersStartsWithTChar: `Hanya nomor hex [0-9a-fA-F], mulai dengan 't' karakter`,
  onlyLatinLettersNumbersOrSpecialSymbols: `Hanya huruf latin, angka dan simbol khusus`,
  onlyNumbers: `Hanya angka`,
  openGuestView: `Buka tampilan pengunjung`,
  openingSoon: `Segera dibuka!`,
  or: `ATAU`,
  password: `Kata sandi`,
  payments: `Pembayaran`,
  pleaseCheckYour: `Silakan periksa `,
  pleaseDropOnlyOneImage: `Harap masukkan hanya satu gambar`,
  pleaseEnterAtLeastNChars: (n) => `Harap masukkan paling tidak ${n} karakter`,
  pleaseFillOutYourDetails: `Silakan isi data lengkap Anda`,
  pleaseSignInToYourAccount: `Silakan masuk ke akun Anda`,
  pleaseVerifyYourAccount: `Silakan verifikasi akun Anda`,
  pressHereTo: `Tekan di sini untuk`,
  save: `Simpan`,
  saveAvatar: `Simpan avatar`,
  saveChanges: `Simpan perubahan`,
  saveThumbnail: `Simpan gambar mini`,
  selectAnime: `Pilih Anime`,
  selectAvatar: `Pilih Avatar`,
  selectCharacters: `Pilih Karakter`,
  selectFile: `Pilih file`,
  selectThumbnail: `Pilih gambar mini`,
  sendEmail: `Kirim email`,
  settings: `Pengaturan`,
  shareYourStory: `Bagikan kisah Anda!`,
  shop: `Belanja`,
  signIn: `Masuk`,
  skip: `Lewati`,
  socialMedia: `Media sosial`,
  spaceCharacterIsNotAllowed: `Karakter spasi tidak dibolehkan`,
  subscribeToTalentsToKeepUpWithTheirProgress: `(en) Subscribe to talents to keep up with their progress`,
  successChangedPasswordPleaseSignIn: `Berhasil! Mengubah kata sandi. Silakan masuk`,
  successCreatedRecord: `Berhasil! Catatan dibuat!`,
  successUpdatedRecord: `Berhasil! Catatan diperbarui!`,
  supportMeOn: `(en) Support me on`,
  tellUsAboutYourself: `Ceritakan diri Anda`,
  termsAndConditions: `Syarat dan Ketentuan`,
  termsOfUse: `Syarat penggunaan`,
  title: `Judul`,
  typeYourTextHere: `Ketikkan teks Anda di sini...`,
  uploadAnotherArt: `Unggah karya lain`,
  uploadAnotherAvatar: `Unggah avatar lain`,
  uploadArtNow: `Unggah karya sekarang!`,
  uploadNew: `Unggah baru`,
  uploadNewArt: `Unggah karya baru`,
  uploadNewPost: `Unggah postingan baru`,
  username: `Nama pengguna`,
  usernameAlreadyExists: `Nama pengguna sudah ada`,
  valueIsNotTheSame: `(en) Value is not the same`,
  verificationCode: `Verifikasi Kode`,
  verifyCode: `Memverifikasi kode`,
  weAreOnInstagram: `Kami ada di Instagram`,
  weAreWorkingOnIt: `Kami sedang mengatasinya`,
  weDoNotDisplayNSFWContentYet: `Kami belum menampilkan konten NSFW`,
  weHaveSentTooManyVerificationEmails: `Kami sudah mengirim terlalu banyak email verifikasi, silakan coba beberapa saat lagi`,
  welcomeToAnimeClub: `Selamat datang di Anime.club!`,
  weSentAnEmailTo: `Kami mengirim email ke:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Kami sudah mengirimkan Anda email verifikasi baru. Silakan masukkan kodenya`,
  weSupportOnlyTheFollowingFileExtensions: `Kami hanya mendukung file dengan ekstensi berikut:`,
  yes: `ya`,
  youAreAlreadyAuthenticated: `Anda sudah terauntentikasi`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Anda masih bisa berpundah ke halaman yang sebelumnya terbuka`,
  youDidNotUpdateAnyValues: `Anda tidak memperbarui apapun`,
  youHaveNotSavedAnyChanges: `Anda belum menyimpan perubahan apapunKeluar?`,
  yourAccountIsVerifiedPleaseSignIn: `Akun anda sudah terverifikasi. Silakan masuk`,
  yourArts: `Karya Anda`,
  yourAvatar: `Avatar Anda`,
  yourBlog: `Blog Anda`,
  yourFansAreWaiting: `Penggemar anda sudah menunggu`,
  yourFeedIsEmpty: `(en) your feed is empty`,
  yourSessionHasExpiredPleaseSignInAgain: `Sesi anda sudah berakhir, silakan masuk lagi`,
}
