export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Tentang`,
  accept: `Terima`,
  account: `(en) Account`,
  accountActivation: `Aktivasi Akun`,
  accountAlreadyExists: `Akun sudah ada`,
  accountDoesNotExist: `Akun tidak tersedia`,
  add: `Tambahkan`,
  addArt: `Tambahkan karya`,
  addBlog: `Tambahkan blog`,
  additionalResources: `(en) Additional resources`,
  addMore: `(en) Add more`,
  addNewArt: `Tambahkan karya baru`,
  addPreview: `Tambahkan pratayang`,
  addSignInVia: `Log masuk melalui`,
  advancedOptions: `(en) Advanced options`,
  all: `Semua`,
  alreadySignedIn: `Anda sudah masuk`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (...v) =>
    `(en) Amount should not be less than ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Karya anime oleh seniman dari berbagai belahan dunia. Karya dikurasi terkait anime. Seleksi karya adalah daftar panjang karya anime terbaik`,
  animeArtSubscribeToArtistsLikeAndCreate: `Karya anime - berlanggangan ke seniman, sukai, dan buat koleksi`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - platform pertama yang memberikan bayaran pada seniman dari tampilan di Google Adsense. Dukung para seniman dengan melihat konten mereka atau mulai menghasilkan dari menampilkan karya`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - lihat, unggah, dan menghasilkan dari konten anime`,
  animeCommunity: `Komunitas anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `(en) Anime.club never asks for your private information`,
  animeSocialNetwork: `(en) Anime
Social Network`,
  announcements: `(en) Announcements`,
  apply: `Terapkan`,
  appSettings: `(en) App settings`,
  appsVersionIs: `Versi aplikasi `,
  areYouSureYouWantTo: `Apa Anda yakin Anda ingin`,
  art: `Karya`,
  artAssociatedWithAnime: `Karya terkait anime`,
  artBy: `Karya oleh`,
  artCannotBeChanged: `Karya tidak dapat diubah`,
  authenticationFailed: `Autentikasi gagal`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `Kembali`,
  blog: `Blog `,
  bookmarks: `Markah`,
  browseArt: `Jelajahi karya`,
  cancel: `batalkan`,
  cannotStartWithChars: `Tidak dapat memulai dengan {:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `(en) Change`,
  changeArt: `Ubah karya`,
  changeAvatar: `Ubah avatar`,
  changeEmail: `(en) Change email`,
  changePassword: `Ubah kata sandi`,
  chooseExistingChatOrStartANewOne: `Pilih obrolan yang ada atau mulai baru`,
  city: `Kota`,
  clearAll: `Bersihkan semua`,
  close: `Tutup`,
  colorTheme: `(en) Color theme`,
  comingSoon: `Segera...`,
  community: `Komunitas`,
  confirmAccount: `Konfirmasi akun`,
  confirmPassword: `Konfirmasi Kata Sandi`,
  connectWithUsOn: `(en) Connect with us on`,
  contactInformation: `(en) Contact information`,
  continue: `(en) Continue`,
  contractTitle: `(en) Contract Title`,
  copyLink: `Salin tautan`,
  couldNotCreateANewRecord: `Tidak dapat membuat catatan baru`,
  country: `Negara`,
  createANewAccountFailed: `Gagal membuat akun baru`,
  createNewAccount: `Membuat akun baru`,
  currentPassword: `(en) Current password`,
  daily: `(en) Daily`,
  darkDefault: `(en) Dark default`,
  darkHighContrast: `(en) Dark high contrast`,
  dayTheme: `(en) Day theme`,
  delete: `Hapus`,
  deleteArt: `Hapus karya`,
  deletePost: `Hapus postingan`,
  description: `Deskripsi`,
  details: `Detail`,
  didntReceiveEmail: `Tidak menerima email?`,
  donations: `Donasi`,
  done: `Selesai`,
  dragAndDropOrSelectFiles: `(en) Drag & Drop or Select file(s)`,
  drawingContest: `Kontes menggambar`,
  dueDate: `(en) Due date`,
  earlier: `(en) Earlier`,
  earningFromArts: `Menghasilkan dari karya`,
  edit: `Edit`,
  editPost: `Edit postingan`,
  editProfile: `Edit profil`,
  editTranslations: `Rubah terjemahan`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email telah digunakan oleh seseorang`,
  emailNotifications: `(en) Email Notifications`,
  enterOrPasteALink: `Masuk atau tempelkan tautan`,
  enterTheAddressAssociatedWithYourAccount: `(en) Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `(en) Enter your password`,
  error: `(en) Error`,
  errorPleaseContactCustomerSupport: `Error! Silakan hubungi layanan pelanggan...`,
  exitEditor: `Keluar dari Editor`,
  extensions: `Ekstensi`,
  fileSizeIsTooBig: `Ukuran file terlalu besar`,
  filter: `Filter`,
  filterBy: `Filter berdasarkan`,
  findUser: `Temukan pengguna`,
  follow: `Ikuti`,
  followers: `Pengikut`,
  following: `Mengikuti`,
  followMeOn: `Ikuti saya di`,
  follows: `(en) Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `Untuk pertanyaan lain, silakan hubungi kami di:`,
  forgotPassword: `Lupa kata sandi`,
  forNewMasterpieces: `Untuk mahakarya baru`,
  fromAnimeDotClub: `(en) From anime.club`,
  getDetails: `Dapatkan detail`,
  guestView: `Tampilan Pengunjung`,
  hire: `(en) Hire`,
  homepage: `Beranda`,
  howToContactYou: `(en) How to contact you`,
  howToFindYouOnOtherSocialNetworks: `(en) How to find you on other social networks`,
  iAgreeWith: `Saya setuju`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Tinggi gambar harus lebih besar atau sama dengan`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Lebar gambar harus lebih besar atau sama dengan`,
  introduction: `Pendahuluan`,
  invalidCode: `Kode tidak valid`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `Bagian tidak valid setelah @`,
  invalidPartBeforeAt: `Bagian tidak valid sebelum @`,
  jobDetails: `(en) Job Details`,
  joinAnimeClubCommunity: `(en) Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `Bergabung dalam obrolan`,
  joinUsOnFacebook: `Ikuti kami di facebook`,
  language: `(en) Language`,
  languages: `Bahasa`,
  letEveryoneKnowHowToDonateToYou: `(en) Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `(en) Let others know about you`,
  lightDefault: `(en) Light default`,
  lightHighContrast: `(en) Light high contrast`,
  likes: `Suka`,
  linkCopiedToClipboard: `Tautan disalin ke clipboard`,
  livesIn: `Tinggal di`,
  loading: `(en) Loading`,
  location: `(en) Location`,
  logInOrSignUp: `(en) Log in or sign up`,
  logOut: `(en) Log out`,
  maximumNChars: (...v) => `Paling banyak ${v[0]} karakter`,
  maxSize: `Ukuran maksimum`,
  menu: `Menu`,
  message: `Pesan`,
  messages: `Pesan`,
  minHeight: `Tinggi minimum`,
  minimumNChars: (...v) => `Paling sedikit ${v[0]} karakter`,
  minWidth: `Lebar minimum`,
  monthly: `(en) Monthly`,
  moreFrom: (...v) => `Lebih lanjut dari (${v[0]})`,
  mustBeNChars: (...v) => `Harus ${v[0]} karakter`,
  myPayments: `(en) My payments`,
  myProfile: `(en) My profile`,
  mySettings: `(en) My settings`,
  need1Lowercase: `Perlu 1 huruf kecil`,
  need1Number: `Perlu 1 angka`,
  need1Uppercase: `Perlu 1 huruf besar`,
  needAtLeast1CharacterFromN: (...v) =>
    `Perlu paling tidak 1 karakter dari [${v[0]}]`,
  needNCharacter: (...v) => `Perlu ${v[0]} karakter`,
  newAccount: `Akun baru`,
  newArt: `Karya baru`,
  newArtworks: `(en) New artworks`,
  newBlog: `Blog baru`,
  newPassword: `Kata Sandi Baru`,
  newsFeed: `Umpan berita`,
  next: `(en) Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `(en) Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `(en) Night theme`,
  no: `tidak`,
  noAddedFavoriteArts: `Belum ada karya favorit yang ditambahkan`,
  noInternetConnection: `Tidak ada koneksi internet!`,
  none: `(en) None`,
  noNotifications: `(en) No notifications`,
  noResults: `(en) No results`,
  notifications: `Notifikasi`,
  nsfwContent18Plus: `Konten NSFW (18+)`,
  online: `Daring`,
  onlyLatinLettersNumbersOrSpecialSymbols: `Hanya huruf latin, angka dan simbol khusus`,
  onlyNumbers: `Hanya angka`,
  open: `(en) Open`,
  openGuestView: `Buka tampilan pengunjung`,
  openingSoon: `Segera hadir!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `ATAU`,
  pageNotFound: `(en) Page not found`,
  password: `Kata sandi`,
  payments: `Pembayaran`,
  personal: `(en) Personal`,
  pleaseCheckYour: (...v) => `(en) Please check your ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `(en) Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `Harap masukkan hanya satu gambar`,
  pleaseEnterAtLeastNChars: (...v) =>
    `Harap masukkan paling tidak ${v[0]} karakter`,
  pleaseFillOutYourDetails: `Silakan isi data lengkap Anda`,
  pleaseSignInToYourAccount: `Silakan masuk ke akun Anda`,
  pleaseTryAgainOrClick: (...v) =>
    `Silakan coba sekali lagi atau klik (${v[0]})`,
  pleaseVerifyYourAccount: `Silakan verifikasi akun Anda`,
  pressHereTo: `Tekan di sini untuk`,
  privacyPolicy: `Kebijakan kerahasiaan`,
  privateInformation: `(en) Private information`,
  profile: `Profil`,
  promotions: `(en) Promotions`,
  publicInformation: `(en) Public information`,
  publishOn: (...v) => `(en) Publish on ${v[0]}`,
  rankings: `(en) Rankings`,
  reorderFiles: `(en) Reorder files`,
  report: `(en) Report`,
  save: `Simpan`,
  saveAvatar: `Simpan avatar`,
  saveChanges: `Simpan perubahan`,
  selectAnime: `Pilih Anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `(en) Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `Pilih Avatar`,
  selectCharacters: `Pilih Karakter`,
  selectFile: `Pilih file`,
  selectTheme: `(en) Select theme`,
  selectThumbnail: `Pilih gambar mini`,
  sendEmail: `Kirim email`,
  settings: `Pengaturan`,
  share: `(en) Share`,
  shareYourArtWithTheWorld: `(en) Share your art with the world`,
  shareYourStory: `Bagikan kisah Anda!`,
  shop: `Belanja`,
  showLess: `Tunjukkan lebih sedikit`,
  showMore: `Tunjukkan lebih banyak`,
  signIn: `Masuk`,
  singleTheme: `(en) Single theme`,
  size: `(en) Size`,
  skip: `Lewati`,
  socialMedia: `Media sosial`,
  spaceCharacterIsNotAllowed: `Karakter spasi tidak dibolehkan`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Ikuti si kreator untuk mendapatkan pembaruan mereka`,
  successChangedPasswordPleaseSignIn: `Berhasil! Mengubah kata sandi. Silakan masuk`,
  successCreatedRecord: `Berhasil! Catatan dibuat!`,
  successUpdatedRecord: `Berhasil! Catatan diperbarui!`,
  supportMeOn: `Dukung saya di`,
  syncWithSystem: `(en) Sync with system`,
  tellUsAboutYourself: `Ceritakan diri Anda`,
  termsAndConditions: `Syarat dan Ketentuan`,
  termsOfUse: `Syarat penggunaan`,
  theLinkIsBrokenOrPageHasBeenRemoved: `(en) The link is broken or page has been removed`,
  themeMode: `(en) Theme mode`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `Judul`,
  today: `(en) Today`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `Ketikkan teks Anda di sini...`,
  upload: `(en) Upload`,
  uploadAnotherArt: `Unggah karya lain`,
  uploadAnotherAvatar: `Unggah avatar lain`,
  uploadArtNow: `Unggah karya sekarang!`,
  uploadNew: `Unggah baru`,
  uploadNewArt: `Unggah karya baru`,
  uploadNewPost: `Unggah postingan baru`,
  username: `Nama pengguna`,
  usernameAlreadyExists: `Nama pengguna sudah ada`,
  usernameAndXMoreFollowYou: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more follow you`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more like your artwork`,
  usernameFollowsYou: (...v) => `(en) <b>${v[0]}</b> follows you`,
  usernameLikesYourArt: (...v) => `(en) <b>${v[0]}</b> likes your art`,
  useThisEmailTo: `(en) Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `Isian tidak sama`,
  verificationCode: `Verifikasi Kode`,
  verifyCode: `Memverifikasi kode`,
  visitOurDiscordChannelToGetMoreDetails: `Gabung dengan Discord untuk mendapatkan info lebih lanjut`,
  weAreOnInstagram: `Kami ada di Instagram`,
  weAreWorkingOnIt: `Kami sedang mengatasinya`,
  weDoNotDisplayNSFWContentYet: `Kami belum menampilkan konten NSFW`,
  weekly: `(en) Weekly`,
  weHaveSentTooManyEmails: `(en) We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Selamat datang di Anime.club!`,
  weSentAnEmailTo: `Kami mengirim email ke:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Kami telah mengirimkan email verifikasi baru. Silakan masukkan kodenya`,
  weSupportOnlyTheFollowingFileExtensions: `Kami hanya mendukung file dengan ekstensi berikut:`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `Surel atau kata sandi salah`,
  yes: `Ya`,
  yesterday: `(en) Yesterday`,
  youAreAlreadyAuthenticated: `Anda sudah terauntentikasi`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `(en) You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Anda masih bisa berpindah ke halaman yang sebelumnya terbuka`,
  youDidNotSelectAnyChats: `Anda belum memilih obrolan`,
  youDidNotUpdateAnyValues: `Anda tidak memperbarui apapun`,
  youDoNotHaveAnyChats: `Anda tidak punya obrolan`,
  youHaveNotSavedAnyChanges: `Anda belum menyimpan perubahan apapun. Keluar?`,
  youHaveNotSetAPassword: `(en) You have not set a password`,
  youHaveReachedTheMaximumNumberOfFiles: `(en) You have reached the maximum number of files`,
  yourAccountIsVerifiedPleaseSignIn: `Akun anda sudah terverifikasi. Silakan masuk`,
  yourArts: `Karya Anda`,
  yourAvatar: `Avatar Anda`,
  yourBlog: `Blog Anda`,
  yourFansAreWaiting: `Penggemar anda sudah menunggu`,
  yourFeedIsEmpty: `Umpan anda kosong`,
  yourSessionHasExpiredPleaseSignInAgain: `Sesi anda sudah berakhir, silakan Login lagi`,
}
