export const text: text = {
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `(en) Anime.club uses ${v[0]} to get you paid quickly and keep your personal and payment information secure`,
  clickTheButtonBelowToOpenYourStripeDashboard: `(en) Click the button below to open your Stripe dashboard and view your account details`,
  visitStripeDashboard: `(en) Visit Stripe dashboard`,
  files: `(en) Files`,
  prohibitedTransaction: `(en) Prohibited transaction`,
  uploadTheFilesYourBuyerWillGet: `(en) Upload the files your <b>buyer will get</b>`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `(en) Make sure everything is ready to go — no edits after publishing`,
  filesForTheBuyer: `(en) Files for the buyer`,
  filesForPreview: `(en) Files for preview`,
  needsYourReview: `(en) Needs Your Review`,
  awaitingSellersResponse: `(en) Awaiting seller's response`,
  buyersRequest: `(en) Buyer's request`,
  awaitingClientReview: `(en) Awaiting Client Review`,
  copy: `(en) Copy`,
  thankYouForYourPurchase: `(en) Thank you for your purchase!`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `(en) Great news! ${v[0]} purchased your item. Time to celebrate!`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `(en) @${v[0]} hasn't listed any products for sale yet`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `(en) @${v[0]} hasn’t added anything to their portfolio yet`,
  hideListing: `(en) Hide listing`,
  uploadUpToNumberFiles: (...v) => `(en) Upload up to <b>${v[0]}</b> files`,
  supportedFormats: `(en) Supported formats:`,
  minimumDimensions: (...v) => `(en) Minimum size: ${v[0]}×${v[1]} pixels`,
  maximumFileSize: (...v) => `(en) Maximum file size: <b>${v[0]}</b> per file`,
  thisListingWontBeVisibleToBuyersAnymore: `(en) This listing won’t be visible to buyers anymore — but you can show it again whenever you’re ready`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `(en) Buyers will be able to see this listing. You can hide it again anytime`,
  listingHiddenFromBuyers: `(en) Listing hidden from buyers`,
  listingIsNowVisibleToBuyers: `(en) Listing is now visible to buyers`,
  showListing: `(en) Show listing`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `(en) If there's no response by ${v[0]}, the order will be canceled automatically`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `(en) If no reply is received by ${v[0]}, you'll automatically receive a full refund`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `(en) If you miss the deadline, the buyer can cancel the order for a full refund, and any associated Stripe fees will be deducted from your payout.`,
  addAComment: `(en) Add a comment`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `(en) These rules are provided by the seller and apply only to this item`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `(en) If you have questions or concerns, please contact the seller directly`,
  platformPoliciesMayStillApply: `(en) Platform policies may still apply`,
  copiedToClipboard: `(en) Copied to clipboard`,
  uploadedFilesLocked: `(en) You uploaded these files when you created the post. They're now locked but still visible below`,
  new: `(en) New`,
  createPersonalizedWorkTailoredToEachRequest: `(en) Create personalized work tailored to each request`,
  offerDigitalProducts: `(en) Offer digital products that buyers can access right away`,
  instantDownload: `(en) Instant Download`,
  customWork: `(en) Custom Work`,
  allListings: `(en) All Listings`,
  newCommission: `(en) New commission`,
  noOrders: `(en) No orders`,
  buyNow: `(en) Buy now`,
  attachedFiles: `(en) Attached files`,
  numFilesIncluded: (...v) => `(en) <b>${v[0]}</b> file(s) included`,
  tellTheBuyersWhatTheyWillGet: `(en) Tell buyers exactly what they will get — for example, the number of illustrations, file formats, or canvas specs like resolution and DPI`,
  beSpecificAboutTheContent: `(en) Be specific about the content (e.g. number of files, formats, canvas resolution)`,
  mentionYourDeliveryTimeInDays: `(en) Mention your <b>delivery time</b> (in days)`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `(en) Let buyers know if you offer <b>revisions</b>, and how many`,
  listAnyContentOrRequestsYouDontAccept: `(en) List any content or requests you <b>don't accept</b> (e.g. NSFW, political, religious, or offensive material)`,
  offerOptionalExtras: `(en) Offer optional extras like <b>rush delivery</b>, an <b>extra character</b>, or a <b>detailed background</b>`,
  extrasHelpBoostIncome: `(en) Extras help buyers customize their order and can boost your income`,
  pleaseAllowPopups: `(en) Please allow popups`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `(en) You'll be able to download your files immediately after purchase—no waiting required!`,
  orderAOneOfAKindCustomPieceCraftedToMatchYourVision: `(en) Order a one-of-a-kind custom piece, crafted to match your vision`,
  youAreCoveredIfThereIsAProblem: `(en) You're covered! If there's a problem and the dispute is valid, you'll get 100% of your money back`,
  artGallery: `(en) Art Gallery`,
  commission: `(en) Commission`,
  commissions: `(en) Commissions`,
  digitalDownloads: `(en) Digital Downloads`,
  changesSaved: `(en) Changes saved!`,
  setUpStripeAccountToGetPaidWithAnimeClub: `(en) Set up a Stripe account to get paid with Anime.club`,
  sellerTermsOfService: `(en) Seller Terms of Service`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `(en) Describe what’s included and what the buyer can expect after purchase`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `(en) The reason you provide for cancelling this order will be shared with the buyer`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `(en) Optionally, you can add a description to share more about your creation`,
  pleaseProvideATitleForYourArtwork: `(en) Please provide a title for your artwork`,
  usernameStartedFollowingYou: (...v) =>
    `(en) <b>${v[0]}</b> started following you`,
  usernameLeftAReaction: (...v) => `(en) <b>${v[0]}</b> left a reaction`,
  vote: `(en) Vote`,
  tapAddToCreateOne: `(en) Tap “Add” to create one`,
  reply: `(en) Reply`,
  replyToUsername: (...v) => `(en) Reply to ${v[0]}`,
  numOfReplies: (...v) => `(en) ${v[0]} replies`,
  replies: `(en) Replies`,
  youCanChooseFromTheListOrEnterACustomReason: `(en) You can choose from the list or enter a custom reason`,
  _colon: `：`,
  _comma: `、`,
  _dot: `。`,
  _exclamation: `！`,
  _question: `？`,
  _space: ``,
  _hyphen: `—`,
  about: `情報`,
  accept: `受け入れる`,
  acceptOrder: `注文を承諾する`,
  acceptTheOrder: `注文を承諾する`,
  accountManagment: `アカウント管理`,
  account: `アカウント`,
  accountDeleted: `アカウントが削除されました`,
  animeShopBuyAndSellProducts: `アニメショップ - 商品の購入と販売`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `AI生成画像およびニューラルネットワークフィルターは禁止されています`,
  accountActivation: `アカウントの有効化`,
  accountAlreadyExists: `このアカウントはすでに存在しています`,
  accountDoesNotExist: `このアカウントは存在しません`,
  accountRemoval: `アカウント削除`,
  add: `追加する`,
  addArt: `アートを追加する`,
  addBlog: `ブログを追加する`,
  additionalResources: `追加リソース`,
  addMoreProductsToYourShop: `ショップにさらに商品を追加する`,
  addMore: `追加`,
  addNewArt: `新しいアートを追加する`,
  addSignInVia: `サインイン元を追加する：`,
  addToCart: `カートに追加`,
  advancedOptions: `高度なオプション`,
  all: `すべて`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `ここでアップロードしたすべてのファイルは購入者が利用できます`,
  alreadySignedIn: `サインイン済み`,
  amount: `金額`,
  amountShouldNotBeLessThan: (...v) =>
    `金額は${v[0]}以下にすることはできません`,
  animeArtByArtistsFromAllOverTheWorld: `世界中のアニメ作家によるアニメ アート。アニメとの関連性確認済みのアートです。アート セレクションは、選りすぐりのアートがずらりと続くリストです`,
  animeArtSubscribeToArtistsLikeAndCreate: `アニメ アート - アニメ作家にサブスクして、コレクションを作成してください`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - アニメ作家が、Google AdSenseを介して、視聴に対する収益を得ることのできる初のプラットフォームです。アニメ作家のコンテンツを視聴して応援するか、視聴で稼いでください`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - アニメのコンテンツを視聴して、投稿して、稼いでください`,
  animeCommunity: `アニメ コミュニティ`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.clubはあなたの個人情報を求めることはありません`,
  animeSocialNetwork: `アニメソーシャルネットワーク`,
  announcements: `お知らせ`,
  apply: `適用する`,
  appSettings: `アプリ設定`,
  appsVersionIs: `アプリのバージョン`,
  areYouSureYouWantTo: `本当に`,
  art: `アート`,
  artAssociatedWithAnime: `アニメ関連アート`,
  artBy: (...v) => `${v[0]}さんのアート`,
  artCannotBeChanged: `アートを変更することはできません`,
  artworksAvailableToView: (...v) => `閲覧可能なアートワーク${v[0]}点`,
  authenticationFailed: `認証できませんでした`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Instagramへの自動投稿はInstagramビジネスアカウントのみ利用可能です`,
  attentionYourOrderHasBeenDisputed: `注意！ご注文に異議が申し立てられました。詳細を確認してください`,
  back: `戻る`,
  basePrice: `基本価格`,
  bigAppreciationToTheSellerForTheHardWork: `出品者の努力に大きな感謝`,
  block: `ブロック`,
  buyerReviewedTheOrder: `購入者が注文をレビューしました`,
  buyerHasNotLeftAReviewYet: `購入者はまだレビューを残していません`,
  feedbackReceived: `フィードバックを受け取りました！`,
  blockUser: (...v) => `@${v[0]}をブロック`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `承諾する前に購入者のリクエストをよくご確認ください`,
  blog: `ブログ`,
  bookmarks: `ブックマーク`,
  browseArt: `アートを閲覧する`,
  browseShop: `ショップを閲覧`,
  buyer: `購入者`,
  cancel: `キャンセルする`,
  canceled: `キャンセル済み`,
  cancelOrder: `注文をキャンセル`,
  cannotStartWithChars: `s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"から始めることはできません`,
  change: `変更`,
  checkOutMyShop: `私のショップをチェック`,
  checkOrderStatus: `注文状況を確認する`,
  changeArt: `アートを変更する`,
  changeAvatar: `アバターを変更する`,
  changeEmail: `メールアドレスを変更`,
  changePassword: `パスワードを変更する`,
  chooseExistingChatOrStartANewOne: `既存のチャットを選択するか、新しいチャットを開始します`,
  city: `市町村`,
  clearAll: `すべてクリアにする`,
  close: `閉じる`,
  colorTheme: `カラーテーマ`,
  comingSoon: `近日公開...`,
  commercialUseAllowed: `商用利用可`,
  commercialUseAllowsBuyersToUseYourProduct: `商用利用により、購入者はあなたの商品を販売やサービスの宣伝などのビジネス目的で利用できます`,
  community: `コミュニティ`,
  completed: `完了`,
  confirmAccount: `アカウントを確認する`,
  confirmOrder: `注文を確認`,
  confirmPassword: `パスワードを確認する`,
  connectWithUsOn: `フォローして最新情報をチェック`,
  contactInformation: `連絡先情報`,
  contactSeller: `出品者に連絡`,
  contactSupport: `サポートに連絡`,
  contactUs: `お問い合わせ`,
  continue: `続ける`,
  contractTitle: `契約タイトル`,
  congratulations: `おめでとうございます！`,
  congratulationsOnSuccessfullyCompletingYourOrder: `ご注文の完了おめでとうございます！`,
  copyrightViolation: `著作権侵害`,
  couldNotCreateANewRecord: `新しい登録を作成できませんでした`,
  country: `国`,
  cover: `カバー`,
  createANewAccountFailed: `新しいアカウントを作成できませんでした`,
  createExtrasForYourProduct: `製品のエクストラを作成する`,
  createNewAccount: `新しいアカウントを作成する`,
  createAShopWithStripe: `Stripeでショップを作成`,
  createdBy: `作成者`,
  currentPassword: `現在のパスワード`,
  daily: `毎日`,
  darkDefault: `ダークデフォルト`,
  darkHighContrast: `ダークハイコントラスト`,
  dayTheme: `デイテーマ`,
  delete: `削除する`,
  deleteShop: `ショップを削除`,
  deleteAccount: `アカウントを削除する`,
  deleteArt: `アートを削除する`,
  decline: `拒否`,
  deletePost: `投稿を削除する`,
  deleteProduct: `製品を削除する`,
  download: `ダウンロード`,
  downloadThemBelow: `下記からダウンロード`,
  deliveryTime: `配達時間`,
  describeTheDetailsOfYourExtra: `エクストラの詳細を記載してください`,
  description: `内容`,
  details: `詳細`,
  didntReceiveEmail: `メールが届きませんでしたか？`,
  displayName: `表示名`,
  disputed: `紛争中`,
  donations: `寄付`,
  done: `完了`,
  dragAndDropOrSelectFiles: `ドラッグ＆ドロップまたはファイルを選択する`,
  drawingContest: `アニメ作品コンテスト`,
  dueDate: `期限日`,
  earlier: `以前`,
  earningFromArts: `アートの収益`,
  edit: `編集する`,
  editPost: `投稿を編集する`,
  editProfile: `プロフィールを編集する`,
  editTranslations: `翻訳を編集する`,
  email: `メール`,
  emailAlreadyUsedByAnotherAccount: `このメールアドレスは、別のアカウントがすでに使用しています`,
  emailNotifications: `メール通知`,
  enterOrPasteALink: `入力するか、リンクを貼り付けます`,
  enjoyYourPurchase: `ご購入ありがとうございます！😊`,
  enterTheAddressAssociatedWithYourAccount: `アカウントに関連付けられたアドレスを入力して、パスワードをリセットするためのリンクをメールで送信します`,
  enterYourPassword: `パスワードを入力してください`,
  error: `エラー`,
  errorPleaseContactCustomerSupport: `エラー！カスタマーサポートまでご連絡ください...`,
  exitWithoutSaving: `保存せずに終了`,
  extensions: `拡張機能`,
  extras: `エクストラ`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `エクストラは商品を強化するためのオプション追加機能です`,
  fileSizeIsTooBig: `ファイルのサイズが大きすぎます`,
  fileSizeIsTooSmall: `ファイルサイズが小さすぎます`,
  filter: `絞り込む`,
  filterBy: `以下の条件で絞り込む`,
  findUser: `ユーザーを検索する`,
  finishSettingUpYourShop: `ショップの設定を完了する`,
  follow: `フォローする`,
  followers: `フォロワー`,
  following: `フォロー中`,
  followMeOn: `以下でフォローしてください`,
  follows: `フォロー`,
  forAllOtherInquiriesPleaseContactUsAt: `その他ご不明な点がございましたら、当社までお問い合わせください。`,
  forgotPassword: `パスワードを忘れた`,
  fromAnimeDotClub: `Anime.clubから`,
  getDetails: `詳しく見る`,
  getStarted: `始める`,
  guestView: `ゲスト視聴`,
  greatNewsYourOrderIsNowInProgress: `素晴らしいニュース！ご注文が進行中です`,
  harassment: `嫌がらせ`,
  haveAnyQuestions: `質問がありますか？`,
  usernameHasCanceledTheOrder: (...v) =>
    `<b>${v[0]}</b> が注文をキャンセルしました`,
  usernameHasSubmittedTheWork: (...v) =>
    `<b>${v[0]}</b> さんが作品を提出しました`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]}は"${v[1]}"の説明を追加していません`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]}はまだ公開情報を共有していません`,
  hate: `憎しみ`,
  hereAreAFewWaysToGetThingsRolling: `始めるためのいくつかの方法はこちら`,
  hire: `雇う`,
  homepage: `ホームページ`,
  howToContactYou: `あなたに連絡する方法`,
  howToFindYouOnOtherSocialNetworks: `他のソーシャルネットワークであなたを見つける方法`,
  iAgreeWith: `以下に同意する`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `${v[0]} までに応答がない場合、注文は自動的に完了としてマークされます`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `以下より大きい画像の長さが必要です`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `以下より大きい画像の幅が必要です`,
  impersonation: `偽装`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `バイヤーがあなたの製品を検索するために使用する可能性のあるキーワードを含める`,
  inProgress: `進行中`,
  introduction: `導入`,
  includes: `含む`,
  invalidCode: `コードが無効です`,
  invalidCurrentPassword: `現在のパスワードが無効です`,
  invalidDate: `日付が無効です`,
  invalidPartAfterAt: `@の後の部分が無効です`,
  invalidPartBeforeAt: `@の前の部分が無効です`,
  jobDetails: `仕事の詳細`,
  joinAnimeClubCommunity: `アクティブなクリエイターやクールなアニメアートが毎日登場するAnime.clubコミュニティに参加しましょう`,
  joinChat: `チャットに参加する`,
  joinUsOnFacebook: `Facebookで参加してください`,
  language: `言語`,
  lackOfInformation: `情報不足`,
  languages: `言語`,
  letEveryoneKnowHowToDonateToYou: `寄付方法をみんなに知らせる`,
  letOthersKnowAboutYou: `あなたについて他の人に知らせる`,
  letsUploadYourFirstProduct: `最初の商品をアップロードしましょう`,
  letUsKnowWhatsHappening: `何が起こっているか教えてください。調査します`,
  lightDefault: `ライトデフォルト`,
  lightHighContrast: `ライトハイコントラスト`,
  likes: `いいね`,
  limit: `制限`,
  livesIn: `地域`,
  loading: `読み込み中`,
  location: `場所`,
  logInOrSignUp: `ログインまたはサインアップ`,
  logOut: `ログアウト`,
  maximumNChars: (...v) => `最大${v[0]}文字`,
  maximumNumberOfDaysToCompleteTheOrder: `注文を完了するための最大日数`,
  maximumQuantity: `最大数量`,
  maxSize: `最大サイズ`,
  menu: `メニュー`,
  message: `メッセージ`,
  messages: `メッセージ`,
  minHeight: `最小長さ`,
  minimumNChars: (...v) => `最小${v[0]}文字`,
  minorAbuseOrSexualization: `軽微な虐待または性的描写`,
  makeSureToIncludeClearInstructions: `各リファレンスの使い方について明確な指示を必ず含めてください`,
  makeSureYouFullyUnderstandTheRequirements: `要件を十分に理解し、期限までに注文を完了できることを確認してください`,
  makeSureYourProductsArePricedCompetitively: `商品が競争力のある価格であることを確認してください`,
  minWidth: `最小幅`,
  monthly: `毎月`,
  moreFrom: (...v) => `さらに${v[0]}`,
  mustBeNChars: (...v) => `${v[0]}文字必要です`,
  myPayments: `私の支払い`,
  myProfile: `私のプロフィール`,
  mySettings: `私の設定`,
  need1Lowercase: `小文字が1つ必要です`,
  need1Number: `数字が1つ必要です`,
  need1Uppercase: `大文字が1つ必要です`,
  needAtLeast1CharacterFromN: (...v) => `[${v[0]}]の1文字以上が必要です`,
  needNCharacter: (...v) => `${v[0]}文字必要です`,
  newAccount: `新しいアカウント`,
  newArt: `新しいアート`,
  newArtworks: `新しいアートワーク`,
  newBlog: `新しいブログ`,
  newOrder: `新しい注文`,
  newPassword: `新しいパスワード`,
  newProduct: `新しい製品`,
  newsFeed: `ニュースフィード`,
  next: `次へ`,
  nextTimeYouAuthenticateYouCouldUseThe: `次回認証する際は、ログインとパスワードの代わりに接続されたアカウントを使用できます`,
  nightTheme: `ナイトテーマ`,
  no: `いいえ`,
  noInternetConnection: `インターネットの接続がありません！`,
  nonConsensualIntimateContent: `非同意の親密なコンテンツ`,
  none: `なし`,
  noNotifications: `通知なし`,
  noResults: `結果なし`,
  noReviewsJustYet: `まだレビューはありません`,
  notifications: `通知`,
  noActiveOrdersToShow: `表示するアクティブな注文はありません`,
  notAcceptingOrders: `注文を受け付けていません`,
  noSalesYetNoWorries: `まだ販売がありませんか？ご心配なく、始まったばかりです`,
  nsfwContent18Plus: `18歳以上向けのコンテンツ`,
  NSFWIndicatesAdultContent: `18+ NSFWは成人向けコンテンツを示します。商品が大人向けの場合のみチェックしてください`,
  numberOfAdjustmentsAClientCouldRequest: `クライアントがリクエストできる調整の数`,
  online: `オンライン`,
  onlyLatinLettersNumbersHyphen: `ラテン文字、数字、ハイフン、アンダースコア、ドット文字のみ`,
  onlyNumbers: `数字のみ`,
  onlyYouCanSeeWhatYouveSaved: `保存した内容はあなただけが見ることができます`,
  open: `開く`,
  openDispute: `紛争を開く`,
  openGuestView: `ゲスト視聴を開く`,
  openingSoon: `近日公開！`,
  openToWork: `仕事に開かれています`,
  optional: `オプション`,
  requestDetails: `リクエスト詳細`,
  or: `または`,
  order: `注文`,
  outOfStock: `在庫切れ`,
  ordered: (...v) => `注文済み ${v[0]}`,
  orderAgain: `再注文する`,
  orderDetails: `注文の詳細`,
  orderConfirmed: `注文が確認されました`,
  orderCompleted: `注文完了 🎉`,
  orderStatus: `注文ステータス`,
  orderOptions: `注文オプション`,
  otherReason: `その他の理由`,
  pageNotFound: `ページが見つかりません`,
  password: `パスワード`,
  payments: `支払い`,
  personal: `個人的な`,
  personalCircumstances: `個人的な事情`,
  pleaseCheckYour: (...v) => `${v[0]}を確認してください`,
  pleaseRateYourOrder: `ご注文の評価をお願いします`,
  feelFreeToShareReferenceImagesAndMaterials: `アーティストが作品を作るのに役立つ参考画像や資料を自由に共有してください`,
  pleaseDoNotShareYourPrivateInformationToOthers: `他の人とあなたの個人情報を共有しないでください`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `${v[0]}と${v[1]}の間の数字を入力してください`,
  pleaseEnterAtLeastNChars: (...v) => `${v[0]}文字以上入力してください`,
  pleaseFillOutYourDetails: `詳細情報を入力してください`,
  pleaseFixTheErrorsBeforeSubmitting: `送信前にエラーを修正してください`,
  pleaseSignInToYourAccount: `アカウントにサインインしてください`,
  platform: `プラットフォーム`,
  pleaseStartTyping: `入力を開始してください`,
  pleaseTakeAMomentToReviewTheOrder: `ご注文内容を今一度ご確認ください`,
  pleaseReviewTheBuyersReferenceFiles: `購入者の参考ファイルを確認し、注文説明に従ってください`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `続行する前に詳細をよくご確認ください`,
  pleaseRespondToTheOrderBy: (...v) => `${v[0]}までにご注文にご対応ください`,
  pleaseTryAgainOrClick: (...v) =>
    `もう一度試すか、${v[0]}をクリックしてください`,
  pleaseVerifyYourAccount: `アカウントを確認してください`,
  pressHereTo: `以下のためにはここを押します`,
  price: `価格`,
  payouts: `支払い`,
  privacyPolicy: `プライバシーポリシー`,
  privateInformation: `個人情報`,
  proceedToCheckout: `チェックアウトに進む`,
  product: `製品`,
  itemReviews: `商品レビュー`,
  portfolio: `ポートフォリオ`,
  profile: `プロフィール`,
  promotions: `プロモーション`,
  publicInformation: `公開情報`,
  publishOn: (...v) => `${v[0]}に公開する`,
  purchases: `購入`,
  rankings: `ランキング`,
  reorderFiles: `ファイルを並び替える`,
  report: `報告する`,
  review: `レビュー`,
  rules: `ルール`,
  reviews: `レビュー`,
  numOfReviews: (...v) => `レビュー: ${v[0]} `,
  reviewed: `レビュー済み`,
  reviewTitle: `レビュータイトル`,
  reason: `理由`,
  revisions: `改訂`,
  includesXRevisionS: (...v) => `${v[0]}回の修正を含む`,
  sales: `販売`,
  save: `保存する`,
  saveAvatar: `アバターを保存する`,
  saveChanges: `変更を保存する`,
  selectAnime: `アニメを選択する`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `単一のテーマを選択するか、システムと同期して昼夜のテーマを自動的に切り替えます`,
  selectAvatar: `アバターを選択する`,
  selectCharacters: `キャラクターを選択する`,
  seller: `販売者`,
  selectFile: `ファイルを選択する`,
  selectTheme: `テーマを選択する`,
  selectThumbnail: `サムネイルを選択する`,
  selfHarmOrSuicide: `自傷行為または自殺`,
  sendEmail: `メールを送信する`,
  settings: `設定`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `ショップの設定は無料で、数分で完了します`,
  share: `共有する`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `受け付けないリクエストやルールを共有してください`,
  shareYourShopOnSocialMedia: `ショップをSNSでシェア`,
  shareYourFavoritePiecesOn: (...v) => `${v[0]}でお気に入り作品をシェア`,
  shareYourArtWithTheWorld: `あなたのアートを世界と共有する`,
  shareYourStory: `物語を共有してください！`,
  sharingPersonalInformation: `個人情報の共有`,
  shop: `ショップ`,
  shopReviews: `ショップレビュー`,
  shopOrders: `ショップの注文`,
  showLess: `表示を減らす`,
  showMore: `表示を増やす`,
  signIn: `ログイン`,
  singleTheme: `単一のテーマ`,
  size: `サイズ`,
  skip: `スキップ`,
  socialMedia: `ソーシャルメディア`,
  spaceCharacterIsNotAllowed: `スペースは使用できません`,
  spam: `スパム`,
  yourFavoritesWillShowUpHereAddSome: `お気に入りはここに表示されます。追加してください！`,
  submitAReport: `報告を送信する`,
  submitWork: `作品を提出する`,
  subscribeToTalentsToKeepUpWithTheirProgress: `作者にサブスクして進歩を追跡しましょう`,
  successChangedPasswordPleaseSignIn: `成功！パスワードが変更されました。ログインしてください。`,
  successCreatedRecord: `成功！登録が作成されました！`,
  successfullyDownloaded: `ダウンロードに成功しました！`,
  successfullyUploaded: `アップロードに成功しました！`,
  supportMeOn: `以下で応援してください`,
  syncWithSystem: `システムと同期する`,
  tellUsAboutYourself: `ご自分について語ってください`,
  termsAndConditions: `諸条件`,
  termsOfUse: `ご利用規約`,
  thankYouForReport: `安全で敬意を持ったオンラインコミュニティを維持するのに役立っていただきありがとうございます`,
  thankYouForYourReview: `レビューありがとうございます！`,
  theLinkIsBrokenOrPageHasBeenRemoved: `リンクが切れているか、ページが削除されました`,
  themeMode: `テーマモード`,
  thisIsThePriceYouPropose: `これがあなたが提案する価格です`,
  thisFieldIsOptional: `この項目は任意です`,
  thisCannotBeUndone: `この操作は元に戻せません`,
  ensureYouveUploadedTheFinalVersion: `最終版をアップロードしてから送信してください`,
  threateningViolence: `暴力を脅す`,
  title: `件名`,
  timeConstraints: `時間の制約`,
  titleYourExtraService: `追加サービスのタイトルを付ける`,
  theMaximumQuantityThatACustomerCanAdd: `顧客が追加できる最大数量`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `レビュー期間は ${v[0]} 日間に制限されています`,
  toHelpTheCreatorCompleteYourOrder: `クリエイターがご注文を満足のいく形で完了するために、希望するテーマ、スタイル、キャラクターの特徴、およびその他の重要な仕様を含む詳細な説明を提供してください`,
  today: `今日`,
  toGetWorkRelatedNotifications: `仕事に関する通知を受け取るには`,
  total: `合計`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `このデータを表示するには、@${v[0]} のブロックを解除する必要があります`,
  trademarkViolation: `商標侵害`,
  typeYourTextHere: `内容をここに入力してください...`,
  theSellerHasUploadedTheseFilesForYou: `出品者がこれらのファイルをアップロードしました`,
  unblock: `ブロック解除`,
  unblockUser: (...v) => `@${v[0]} のブロック解除`,
  unfollow: `フォロー解除`,
  unlimited: `無制限`,
  upload: `アップロード`,
  uploadNew: `新しいものをアップロードする`,
  uploadNewPost: `新しい投稿をアップロードする`,
  uploadNewProduct: `新しい製品をアップロードする`,
  username: `ユーザー名`,
  pleaseUploadOnlyFinishedWorkHere: `ここには完成した作品のみアップロードしてください`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `進行中のファイルはメッセージでアップロードしてください`,
  usernameAlreadyExists: `このユーザー名はすでに存在しています`,
  usernameAndXMoreFollowYou: (...v) =>
    `<b>${v[0]}</b>さんと他${v[1]}人があなたをフォローしています`,
  usernameAndXMoreReacted: (...v) =>
    `<b>${v[0]}</b>さんと他${v[1]}人がリアクションしました`,
  useThisEmailTo: `このメールアドレスを使用して認証し、通知を受け取る`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `残念ながら${v[0]}がこの注文をキャンセルしました`,
  valueIsNotTheSame: `値が同じではありません`,
  verificationCode: `検証コード`,
  verifyCode: `コードを確認する`,
  viewDetails: `詳細を見る`,
  viewReview: `レビューを見る`,
  viewEveryNotificationOfAGroupSeparately: `グループのすべての通知を個別に表示する`,
  visitOurDiscordChannelToGetMoreDetails: `Discordの当チャンネルで詳細をご覧ください`,
  weAreOnInstagram: `当社のInstagram`,
  weAreWorkingOnIt: `取り組んでおります`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `お疲れ様です！作品が無事に完了しました`,
  weDoNotDisplayNSFWContentYet: `18歳以上向けのコンテンツはまだ扱っておりません`,
  weekly: `週次`,
  whenYouPurchaseSomethingItWillAppearHere: `何かを購入すると、ここに表示されます`,
  weHaveSentTooManyEmails: `あまりにも多くのメールを送信しました。後でもう一度試すか、カスタマーサポートにお問い合わせください`,
  welcomeToAnimeClub: `Anime.clubへようこそ！`,
  weSentAnEmailTo: `以下へメールを送信しました。`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `新しい検証メールを送信しました。コードを入力してください`,
  weAreExcitedToSeeYourProgressKeepItUp: `あなたの進捗を見るのが楽しみです。続けてください！`,
  weSupportOnlyTheFollowingFileExtensions: `サポートされているファイル拡張子は、以下のみです。`,
  work: `仕事`,
  weWouldLoveToHearFromYou: `あなたからのご意見をお待ちしています`,
  workDescription: `仕事の説明`,
  leaveAReview: `レビューを残す`,
  wrongEmailOrPassword: `誤ったメールまたはパスワード`,
  yes: `はい`,
  yesterday: `昨日`,
  youReceivedANewOrderFrom: (...v) =>
    `<b>${v[0]}</b> から新しい注文を受け取りました`,
  youReceivedAReview: `レビューを受け取りました`,
  youHaveSuccessfullyCreatedYourShop: `ショップを正常に作成しました`,
  youAreAlreadyAuthenticated: `すでに認証されています`,
  youCanAutoPublishToYourSocialMediaAccount: `ソーシャルメディアアカウントに自動投稿できます`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `メールで受け取る通知の種類を変更できます`,
  youCanRequestRemovalOfYourAccount: `アカウントの削除とすべてのデータの削除をリクエストできます`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `あなたのフィードバックは購入者の参考になり、出品者がより良い商品を提供する助けになります`,
  youCanStillNavigateToThePreviouslyOpenedPages: `前に開いたページには移動できます`,
  youDidNotSelectAnyChats: `チャットを選択していません`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `購入者が体験を共有するとここにレビューが表示されます`,
  youDidNotUpdateAnyValues: `いかなる値も更新していません`,
  youDoNotHaveAnyChats: `チャットはありません`,
  youHaveNotSetAPassword: `パスワードが設定されていません`,
  youHaveNotSharedAnythingYet: `まだ何も共有していません`,
  youHaveReachedTheMaximumNumberOfFiles: `最大ファイル数に達しました`,
  kindlyHoldOnForTheBuyersReview: `購入者のレビューをお待ちください。`,
  yourAccountIsVerifiedPleaseSignIn: `アカウントが確認されました。ログインしてください`,
  yourAccountWillBeRemoved: (...v) => `アカウントは${v[0]}に削除されます`,
  youHaveNoPurchases: `購入履歴がありません`,
  couldYouPleaseProvideTheReasonForTheCancellation: `キャンセルの理由を教えてください`,
  yourArts: `自分のアート`,
  youCanceledTheOrder: `注文をキャンセルしました`,
  yourAvatar: `自分のアバター`,
  yourBlog: `自分のブログ`,
  yourFansAreWaiting: `ファンが待っています`,
  yourFeedIsEmpty: `フィードが空です`,
  yourSessionHasExpiredPleaseSignInAgain: `セッション切れになりました。もう一度ログインしてください`,
}
