export const text: text = {
  _colon: `：`,
  _comma: `、`,
  _dot: `。`,
  _exclamation: `！`,
  _question: `？`,
  _space: ``,
  about: `情報`,
  accept: `受け入れる`,
  accountActivation: `アカウントの有効化`,
  accountAlreadyExists: `このアカウントはすでに存在しています`,
  accountDoesNotExist: `このアカウントは存在しません`,
  add: `追加する`,
  addArt: `アートを追加する`,
  addBlog: `ブログを追加する`,
  addedNAgo: (n) => `${n}前に追加されました`,
  addNewArt: `新しいアートを追加する`,
  addPreview: `プレビューを追加する`,
  addSignInVia: `サインイン元を追加する：`,
  all: `(en) All`,
  alreadySignedIn: `サインイン済み`,
  animeArtByArtistsFromAllOverTheWorld: `世界中のアニメ作家によるアニメ アート。アニメとの関連性確認済みのアートです。アート セレクションは、選りすぐりのアートがずらりと続くリストです`,
  animeArtSubscribeToArtistsLikeAndCreate: `アニメ アート - アニメ作家にサブスクして、コレクションを作成してください`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - アニメ作家が、Google AdSenseを介して、視聴に対する収益を得ることのできる初のプラットフォームです。アニメ作家のコンテンツを視聴して応援するか、視聴で稼いでください`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - アニメのコンテンツを視聴して、投稿して、稼いでください`,
  animeCommunity: `アニメ コミュニティ`,
  animeOnly: `アニメのみ`,
  apply: `(en) Apply`,
  appsVersionIs: `アプリのバージョン`,
  areYouSureYouWantTo: `本当に`,
  art: `アート`,
  artAssociatedWithAnime: `アニメ関連アート`,
  artBy: `アニメ作家`,
  artCannotBeChanged: `アートを変更することはできません`,
  authenticationFailed: `認証できませんでした`,
  back: `戻る`,
  blog: `ブログ`,
  bookmarks: `ブックマーク`,
  browseArt: `アートを閲覧する`,
  cancel: `キャンセルする`,
  cannotStartWithChars: `s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"から始めることはできません`,
  changeArt: `アートを変更する`,
  changeAvatar: `アバターを変更する`,
  changePassword: `パスワードを変更する`,
  chooseExistingChatOrStartANewOne: `(en) Choose existing chat or start a new one`,
  city: `市町村`,
  clearAll: `すべてクリアにする`,
  close: `閉じる`,
  comingSoon: `近日公開...`,
  community: `コミュニティ`,
  confirmAccount: `アカウントを確認する`,
  confirmPassword: `パスワードを確認する`,
  copyLink: `リンクをコピーする`,
  couldNotCreateANewRecord: `新しい登録を作成できませんでした`,
  country: `国`,
  createANewAccountFailed: `新しいアカウントを作成できませんでした`,
  createNewAccount: `新しいアカウントを作成する`,
  delete: `削除する`,
  deleteArt: `アートを削除する`,
  deletePost: `投稿を削除する`,
  description: `内容`,
  details: `詳細`,
  didntReceiveEmail: `メールが届きませんでしたか？`,
  donations: `寄付`,
  done: `完了`,
  drawingContest: `アニメ作品コンテスト`,
  earningFromArts: `アートの収益`,
  edit: `編集する`,
  editPost: `投稿を編集する`,
  editProfile: `プロフィールを編集する`,
  editTranslations: `翻訳を編集する`,
  email: `メール`,
  emailAlreadyUsedByAnotherAccount: `このメールアドレスは、別のアカウントがすでに使用しています`,
  emailSubscription: `メール受信登録`,
  enterOrPasteALink: `(en) Enter or paste a link`,
  error404NotFound: `404エラー - お探しのページは見つかりませんでした`,
  errorPleaseContactCustomerSupport: `エラー！カスタマーサポートまでご連絡ください...`,
  exitEditor: `エディタを閉じる`,
  extensions: `拡張機能`,
  fileSizeIsTooBig: `ファイルのサイズが大きすぎます`,
  filter: `絞り込む`,
  filterBy: `以下の条件で絞り込む`,
  findUser: `(en) Find user`,
  follow: `フォローする`,
  followers: `(en) Followers`,
  following: `(en) Following`,
  followMeOn: `以下でフォローしてください`,
  followUsOnTwitter: `Twitterでフォローしてください`,
  forAllOtherInquiriesPleaseContactUsAt: `その他ご不明な点がございましたら、当社までお問い合わせください。`,
  forgotPassword: `パスワードを忘れた`,
  forNewMasterpieces: `新しい傑作`,
  four04: `— 404! —`,
  getDetails: `詳しく見る`,
  guestView: `ゲスト視聴`,
  homepage: `ホームページ`,
  iAgreeWith: `以下に同意する`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `以下より大きい画像の長さが必要です`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `以下より大きい画像の幅が必要です`,
  introduction: `導入`,
  invalidCode: `コードが無効です`,
  invalidPartAfterAt: `@の後の部分が無効です`,
  invalidPartBeforeAt: `@の前の部分が無効です`,
  joinChat: `チャットに参加する`,
  joinUsOnFacebook: `Facebookで参加してください`,
  languages: `言語`,
  likes: `(en) Likes`,
  linkCopiedToClipboard: `(en) Link copied to clipboard`,
  livingIn: `地域`,
  location: `(en) Location`,
  logout: `ログアウト`,
  maximumNChars: (n) => `最大${n}文字`,
  maxSize: `最大サイズ`,
  menu: `メニュー`,
  message: `メッセージ`,
  messages: `メッセージ`,
  minHeight: `最小長さ`,
  minimumNChars: (n) => `最小${n}文字`,
  minWidth: `最小幅`,
  moreFrom: (n) => `さらに${n}`,
  mustBeNChars: (n) => `${n}文字必要です`,
  need1Lowercase: `小文字が1つ必要です`,
  need1Number: `数字が1つ必要です`,
  need1Uppercase: `大文字が1つ必要です`,
  needAtLeast1CharacterFromN: (n) => `[${n}]の1文字以上が必要です`,
  needNCharacter: (n) => `${n}文字必要です`,
  newAccount: `新しいアカウント`,
  newArt: `新しいアート`,
  newBlog: `新しいブログ`,
  newPassword: `新しいパスワード`,
  newsFeed: `ニュースフィード`,
  no: `いいえ`,
  noAddedFavoriteArts: `追加されたお気に入りアートはありません`,
  noInternetConnection: `インターネットの接続がありません！`,
  notifications: `(en) Notifications`,
  nsfwContent18Plus: `18歳以上向けのコンテンツ`,
  ohNoItIsNotHere: `違います！ここにはありません！`,
  oldPassword: `元のパスワード`,
  online: `オンライン`,
  onlyHexNumbersStartsWithTChar: `16進数「0-9a-fA-F」のみ、「 t」文字で開始`,
  onlyLatinLettersNumbersOrSpecialSymbols: `英数字と特殊記号のみ`,
  onlyNumbers: `数字のみ`,
  openGuestView: `ゲスト視聴を開く`,
  openingSoon: `近日公開！`,
  openToWork: `(en) Open to work`,
  or: `または`,
  password: `パスワード`,
  payments: `支払い`,
  pleaseCheckYour: `以下を確認してください`,
  pleaseDropOnlyOneImage: `1つの画像のみドロップしてください`,
  pleaseEnterAtLeastNChars: (n) => `${n}文字以上入力してください`,
  pleaseFillOutYourDetails: `詳細情報を入力してください`,
  pleaseSignInToYourAccount: `アカウントにサインインしてください`,
  pleaseTryAgainOrClick: (n) => `もう一度試すか、${n}をクリックしてください`,
  pleaseVerifyYourAccount: `アカウントを確認してください`,
  pressHereTo: `以下のためにはここを押します`,
  privacyPolicy: `プライバシーポリシー`,
  profile: `プロフィール`,
  save: `保存する`,
  saveAvatar: `アバターを保存する`,
  saveChanges: `変更を保存する`,
  selectAnime: `アニメを選択する`,
  selectAvatar: `アバターを選択する`,
  selectCharacters: `キャラクターを選択する`,
  selectFile: `ファイルを選択する`,
  selectThumbnail: `サムネイルを選択する`,
  sendEmail: `メールを送信する`,
  settings: `設定`,
  shareYourStory: `物語を共有してください！`,
  shop: `ショップ`,
  showLess: `(en) Show less`,
  showMore: `(en) Show more`,
  signIn: `ログイン`,
  skip: `スキップ`,
  socialMedia: `ソーシャルメディア`,
  spaceCharacterIsNotAllowed: `スペースは使用できません`,
  subscribeToTalentsToKeepUpWithTheirProgress: `作者にサブスクして進歩を追跡しましょう`,
  successChangedPasswordPleaseSignIn: `成功！パスワードが変更されました。ログインしてください。`,
  successCreatedRecord: `成功！登録が作成されました！`,
  successUpdatedRecord: `成功！登録が更新されました！`,
  supportMeOn: `以下で応援してください`,
  tellUsAboutYourself: `ご自分について語ってください`,
  termsAndConditions: `諸条件`,
  termsOfUse: `ご利用規約`,
  title: `件名`,
  typeYourTextHere: `内容をここに入力してください...`,
  uploadAnotherArt: `他のアートをアップロードする`,
  uploadAnotherAvatar: `他のアバターをアップロードする`,
  uploadArtNow: `今すぐアートをアップロードしてください！`,
  uploadNew: `新しいものをアップロードする`,
  uploadNewArt: `新しいアートをアップロードする`,
  uploadNewPost: `新しい投稿をアップロードする`,
  username: `ユーザー名`,
  usernameAlreadyExists: `このユーザー名はすでに存在しています`,
  valueIsNotTheSame: `値が同じではありません`,
  verificationCode: `検証コード`,
  verifyCode: `コードを確認する`,
  visitOurDiscordChannelToGetMoreDetails: `Discordの当チャンネルで詳細をご覧ください`,
  weAreOnInstagram: `当社のInstagram`,
  weAreWorkingOnIt: `取り組んでおります`,
  weDoNotDisplayNSFWContentYet: `18歳以上向けのコンテンツはまだ扱っておりません`,
  weHaveSentTooManyVerificationEmails: `当社が送信した検証メールが多すぎます。数分後にもう一度お試しください`,
  welcomeToAnimeClub: `Anime.clubへようこそ！`,
  weSentAnEmailTo: `以下へメールを送信しました。`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `新しい検証メールを送信しました。コードを入力してください`,
  weSupportOnlyTheFollowingFileExtensions: `サポートされているファイル拡張子は、以下のみです。`,
  work: `(en) Work`,
  wrongEmailOrPassword: `誤ったメールまたはパスワード`,
  yes: `はい`,
  youAreAlreadyAuthenticated: `すでに認証されています`,
  youCanStillNavigateToThePreviouslyOpenedPages: `前に開いたページには移動できます`,
  youDidNotSelectAnyChats: `(en) You did not select any chats`,
  youDidNotUpdateAnyValues: `いかなる値も更新していません`,
  youDoNotHaveAnyChats: `(en) You do not have any chats`,
  youHaveNotSavedAnyChanges: `いかなる変更も保存していません`,
  yourAccountIsVerifiedPleaseSignIn: `アカウントが確認されました。ログインしてください`,
  yourArts: `自分のアート`,
  yourAvatar: `自分のアバター`,
  yourBlog: `自分のブログ`,
  yourFansAreWaiting: `ファンが待っています`,
  yourFeedIsEmpty: `フィードが空です`,
  yourSessionHasExpiredPleaseSignInAgain: `セッション切れになりました。もう一度ログインしてください`,
}
