export const text: text = {
  _colon: `：`,
  _comma: `、`,
  _dot: `。`,
  _exclamation: `！`,
  _question: `？`,
  _space: ``,
  about: `情報`,
  accept: `受け入れる`,
  account: `(en) Account`,
  accountActivation: `アカウントの有効化`,
  accountAlreadyExists: `このアカウントはすでに存在しています`,
  accountDoesNotExist: `このアカウントは存在しません`,
  add: `追加する`,
  addArt: `アートを追加する`,
  addBlog: `ブログを追加する`,
  addFile: `(en) Add file`,
  additionalResources: `(en) Additional resources`,
  addMore: `(en) Add more`,
  addNewArt: `新しいアートを追加する`,
  addPreview: `プレビューを追加する`,
  addSignInVia: `サインイン元を追加する：`,
  advancedOptions: `(en) Advanced options`,
  all: `すべて`,
  alreadySignedIn: `サインイン済み`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (...v) =>
    `(en) Amount should not be less than ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `世界中のアニメ作家によるアニメ アート。アニメとの関連性確認済みのアートです。アート セレクションは、選りすぐりのアートがずらりと続くリストです`,
  animeArtSubscribeToArtistsLikeAndCreate: `アニメ アート - アニメ作家にサブスクして、コレクションを作成してください`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - アニメ作家が、Google AdSenseを介して、視聴に対する収益を得ることのできる初のプラットフォームです。アニメ作家のコンテンツを視聴して応援するか、視聴で稼いでください`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - アニメのコンテンツを視聴して、投稿して、稼いでください`,
  animeCommunity: `アニメ コミュニティ`,
  animeDotclubNeverAsksForYourPrivateInformation: `(en) Anime.club never asks for your private information`,
  animeSocialNetwork: `(en) Anime
Social Network`,
  announcements: `(en) Announcements`,
  apply: `適用する`,
  appSettings: `(en) App settings`,
  appsVersionIs: `アプリのバージョン`,
  areYouSureYouWantTo: `本当に`,
  art: `アート`,
  artAssociatedWithAnime: `アニメ関連アート`,
  artBy: `アニメ作家`,
  artCannotBeChanged: `アートを変更することはできません`,
  authenticationFailed: `認証できませんでした`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `戻る`,
  blog: `ブログ`,
  bookmarks: `ブックマーク`,
  browseArt: `アートを閲覧する`,
  cancel: `キャンセルする`,
  cannotStartWithChars: `s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"から始めることはできません`,
  change: `(en) Change`,
  changeArt: `アートを変更する`,
  changeAvatar: `アバターを変更する`,
  changeEmail: `(en) Change email`,
  changePassword: `パスワードを変更する`,
  chooseExistingChatOrStartANewOne: `既存のチャットを選択するか、新しいチャットを開始します`,
  city: `市町村`,
  clearAll: `すべてクリアにする`,
  close: `閉じる`,
  colorTheme: `(en) Color theme`,
  comingSoon: `近日公開...`,
  commercialUse: `(en) Commercial use`,
  community: `コミュニティ`,
  confirmAccount: `アカウントを確認する`,
  confirmPassword: `パスワードを確認する`,
  connectWithUsOn: `(en) Connect with us on`,
  contactInformation: `(en) Contact information`,
  continue: `(en) Continue`,
  contractTitle: `(en) Contract Title`,
  copyLink: `リンクをコピーする`,
  couldNotCreateANewRecord: `新しい登録を作成できませんでした`,
  country: `国`,
  cover: `(en) Cover`,
  createANewAccountFailed: `新しいアカウントを作成できませんでした`,
  createNewAccount: `新しいアカウントを作成する`,
  currentPassword: `(en) Current password`,
  daily: `(en) Daily`,
  darkDefault: `(en) Dark default`,
  darkHighContrast: `(en) Dark high contrast`,
  dayTheme: `(en) Day theme`,
  delete: `削除する`,
  deleteArt: `アートを削除する`,
  deletePost: `投稿を削除する`,
  deliveryTime: `(en) Delivery time`,
  describeTheDetailsOfYourProduct: `(en) Describe the details of your product`,
  description: `内容`,
  details: `詳細`,
  didntReceiveEmail: `メールが届きませんでしたか？`,
  donations: `寄付`,
  done: `完了`,
  dragAndDropOrSelectFiles: `(en) Drag & Drop or Select file(s)`,
  drawingContest: `アニメ作品コンテスト`,
  dueDate: `(en) Due date`,
  earlier: `(en) Earlier`,
  earningFromArts: `アートの収益`,
  edit: `編集する`,
  editPost: `投稿を編集する`,
  editProfile: `プロフィールを編集する`,
  editTranslations: `翻訳を編集する`,
  email: `メール`,
  emailAlreadyUsedByAnotherAccount: `このメールアドレスは、別のアカウントがすでに使用しています`,
  emailNotifications: `(en) Email Notifications`,
  enterOrPasteALink: `入力するか、リンクを貼り付けます`,
  enterTheAddressAssociatedWithYourAccount: `(en) Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `(en) Enter your password`,
  error: `(en) Error`,
  errorPleaseContactCustomerSupport: `エラー！カスタマーサポートまでご連絡ください...`,
  exitEditor: `エディタを閉じる`,
  extensions: `拡張機能`,
  fileSizeIsTooBig: `ファイルのサイズが大きすぎます`,
  filter: `絞り込む`,
  filterBy: `以下の条件で絞り込む`,
  findUser: `ユーザーを検索する`,
  follow: `フォローする`,
  followers: `フォロワー`,
  following: `フォロー中`,
  followMeOn: `以下でフォローしてください`,
  follows: `(en) Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `その他ご不明な点がございましたら、当社までお問い合わせください。`,
  forgotPassword: `パスワードを忘れた`,
  fromAnimeDotClub: `(en) From anime.club`,
  getDetails: `詳しく見る`,
  guestView: `ゲスト視聴`,
  hasNotAddedADescriptionFor: (...v) =>
    `(en) @${v[0]} has not added a description for "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `(en) @${v[0]} has not shared any public details yet`,
  hire: `(en) Hire`,
  homepage: `ホームページ`,
  howToContactYou: `(en) How to contact you`,
  howToFindYouOnOtherSocialNetworks: `(en) How to find you on other social networks`,
  iAgreeWith: `以下に同意する`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `以下より大きい画像の長さが必要です`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `以下より大きい画像の幅が必要です`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `(en) Include keywords that buyers would likely use to search for a product like yours`,
  introduction: `導入`,
  invalidCode: `コードが無効です`,
  invalidCurrentPassword: `(en) Invalid current password`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `@の後の部分が無効です`,
  invalidPartBeforeAt: `@の前の部分が無効です`,
  jobDetails: `(en) Job Details`,
  joinAnimeClubCommunity: `(en) Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `チャットに参加する`,
  joinUsOnFacebook: `Facebookで参加してください`,
  language: `(en) Language`,
  languages: `言語`,
  letEveryoneKnowHowToDonateToYou: `(en) Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `(en) Let others know about you`,
  lightDefault: `(en) Light default`,
  lightHighContrast: `(en) Light high contrast`,
  likes: `いいね`,
  linkCopiedToClipboard: `リンクがクリップボードにコピーされました`,
  livesIn: `地域`,
  loading: `(en) Loading`,
  location: `(en) Location`,
  logInOrSignUp: `(en) Log in or sign up`,
  logOut: `(en) Log out`,
  maximumNChars: (...v) => `最大${v[0]}文字`,
  maximumNumberOfDaysToCompleteTheOrder: `(en) Maximum number of days to complete the order`,
  maxSize: `最大サイズ`,
  menu: `メニュー`,
  message: `メッセージ`,
  messages: `メッセージ`,
  minHeight: `最小長さ`,
  minimumNChars: (...v) => `最小${v[0]}文字`,
  minWidth: `最小幅`,
  monthly: `(en) Monthly`,
  moreFrom: (...v) => `さらに${v[0]}`,
  mustBeNChars: (...v) => `${v[0]}文字必要です`,
  myPayments: `(en) My payments`,
  myProfile: `(en) My profile`,
  mySettings: `(en) My settings`,
  need1Lowercase: `小文字が1つ必要です`,
  need1Number: `数字が1つ必要です`,
  need1Uppercase: `大文字が1つ必要です`,
  needAtLeast1CharacterFromN: (...v) => `[${v[0]}]の1文字以上が必要です`,
  needNCharacter: (...v) => `${v[0]}文字必要です`,
  newAccount: `新しいアカウント`,
  newArt: `新しいアート`,
  newArtworks: `(en) New artworks`,
  newBlog: `新しいブログ`,
  newPassword: `新しいパスワード`,
  newProduct: `(en) New product`,
  newsFeed: `ニュースフィード`,
  next: `(en) Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `(en) Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `(en) Night theme`,
  no: `いいえ`,
  noAddedFavoriteArts: `追加されたお気に入りアートはありません`,
  noInternetConnection: `インターネットの接続がありません！`,
  none: `(en) None`,
  noNotifications: `(en) No notifications`,
  noResults: `(en) No results`,
  notifications: `通知`,
  nsfwContent18Plus: `18歳以上向けのコンテンツ`,
  numberOfAdjustmentsAClientCouldRequest: `(en) Number of adjustments a client could request`,
  online: `オンライン`,
  onlyLatinLettersNumbersOrSpecialSymbols: `英数字と特殊記号のみ`,
  onlyNumbers: `数字のみ`,
  open: `(en) Open`,
  openGuestView: `ゲスト視聴を開く`,
  openingSoon: `近日公開！`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `または`,
  pageNotFound: `(en) Page not found`,
  password: `パスワード`,
  payments: `支払い`,
  personal: `(en) Personal`,
  pleaseCheckYour: (...v) => `(en) Please check your ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `(en) Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `1つの画像のみドロップしてください`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `(en) Please enter a number between ${v[0]} and ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `${v[0]}文字以上入力してください`,
  pleaseFillOutYourDetails: `詳細情報を入力してください`,
  pleaseSignInToYourAccount: `アカウントにサインインしてください`,
  pleaseTryAgainOrClick: (...v) =>
    `もう一度試すか、${v[0]}をクリックしてください`,
  pleaseVerifyYourAccount: `アカウントを確認してください`,
  pressHereTo: `以下のためにはここを押します`,
  price: `(en) Price`,
  privacyPolicy: `プライバシーポリシー`,
  privateInformation: `(en) Private information`,
  profile: `プロフィール`,
  promotions: `(en) Promotions`,
  publicInformation: `(en) Public information`,
  publishOn: (...v) => `(en) Publish on ${v[0]}`,
  rankings: `(en) Rankings`,
  reorderFiles: `(en) Reorder files`,
  report: `(en) Report`,
  revisions: `(en) Revisions`,
  save: `保存する`,
  saveAvatar: `アバターを保存する`,
  saveChanges: `変更を保存する`,
  selectAnime: `アニメを選択する`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `(en) Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `アバターを選択する`,
  selectCharacters: `キャラクターを選択する`,
  selectFile: `ファイルを選択する`,
  selectTheme: `(en) Select theme`,
  selectThumbnail: `サムネイルを選択する`,
  sendEmail: `メールを送信する`,
  settings: `設定`,
  share: `(en) Share`,
  shareYourArtWithTheWorld: `(en) Share your art with the world`,
  shareYourStory: `物語を共有してください！`,
  shop: `ショップ`,
  showLess: `表示を減らす`,
  showMore: `表示を増やす`,
  signIn: `ログイン`,
  singleTheme: `(en) Single theme`,
  size: `(en) Size`,
  skip: `スキップ`,
  socialMedia: `ソーシャルメディア`,
  spaceCharacterIsNotAllowed: `スペースは使用できません`,
  subscribeToTalentsToKeepUpWithTheirProgress: `作者にサブスクして進歩を追跡しましょう`,
  successChangedPasswordPleaseSignIn: `成功！パスワードが変更されました。ログインしてください。`,
  successCreatedRecord: `成功！登録が作成されました！`,
  successUpdatedRecord: `成功！登録が更新されました！`,
  supportMeOn: `以下で応援してください`,
  syncWithSystem: `(en) Sync with system`,
  tellUsAboutYourself: `ご自分について語ってください`,
  termsAndConditions: `諸条件`,
  termsOfUse: `ご利用規約`,
  theLinkIsBrokenOrPageHasBeenRemoved: `(en) The link is broken or page has been removed`,
  themeMode: `(en) Theme mode`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `件名`,
  today: `(en) Today`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `内容をここに入力してください...`,
  unlimited: `(en) Unlimited`,
  upload: `(en) Upload`,
  uploadNew: `新しいものをアップロードする`,
  uploadNewPost: `新しい投稿をアップロードする`,
  username: `ユーザー名`,
  usernameAlreadyExists: `このユーザー名はすでに存在しています`,
  usernameAndXMoreFollowYou: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more follow you`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more like your artwork`,
  usernameFollowsYou: (...v) => `(en) <b>${v[0]}</b> follows you`,
  usernameLikesYourArt: (...v) => `(en) <b>${v[0]}</b> likes your art`,
  useThisEmailTo: `(en) Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `値が同じではありません`,
  verificationCode: `検証コード`,
  verifyCode: `コードを確認する`,
  visitOurDiscordChannelToGetMoreDetails: `Discordの当チャンネルで詳細をご覧ください`,
  weAreOnInstagram: `当社のInstagram`,
  weAreWorkingOnIt: `取り組んでおります`,
  weDoNotDisplayNSFWContentYet: `18歳以上向けのコンテンツはまだ扱っておりません`,
  weekly: `(en) Weekly`,
  weHaveSentTooManyEmails: `(en) We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Anime.clubへようこそ！`,
  weSentAnEmailTo: `以下へメールを送信しました。`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `新しい検証メールを送信しました。コードを入力してください`,
  weSupportOnlyTheFollowingFileExtensions: `サポートされているファイル拡張子は、以下のみです。`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `誤ったメールまたはパスワード`,
  yes: `はい`,
  yesterday: `(en) Yesterday`,
  youAreAlreadyAuthenticated: `すでに認証されています`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `(en) You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `前に開いたページには移動できます`,
  youDidNotSelectAnyChats: `チャットを選択していません`,
  youDidNotUpdateAnyValues: `いかなる値も更新していません`,
  youDoNotHaveAnyChats: `チャットはありません`,
  youHaveNotSavedAnyChanges: `いかなる変更も保存していません`,
  youHaveNotSetAPassword: `(en) You have not set a password`,
  youHaveNotSharedAnythingYet: `(en) You have not shared anything yet`,
  youHaveReachedTheMaximumNumberOfFiles: `(en) You have reached the maximum number of files`,
  yourAccountIsVerifiedPleaseSignIn: `アカウントが確認されました。ログインしてください`,
  yourArts: `自分のアート`,
  yourAvatar: `自分のアバター`,
  yourBlog: `自分のブログ`,
  yourFansAreWaiting: `ファンが待っています`,
  yourFeedIsEmpty: `フィードが空です`,
  yourSessionHasExpiredPleaseSignInAgain: `セッション切れになりました。もう一度ログインしてください`,
}
