export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  _hyphen: `- `,
  about: `소개`,
  accept: `수락`,
  acceptOrder: `주문 수락`,
  acceptTheOrder: `주문 수락`,
  accountManagment: `계정 관리`,
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `Anime.club은 ${v[0]}을 통해 빠르게 정산하고 개인 정보와 결제 정보를 안전하게 보호합니다`,
  account: `계정`,
  accountDeleted: `계정이 삭제되었습니다`,
  clickTheButtonBelowToOpenYourStripeDashboard: `아래 버튼을 클릭해 Stripe 대시보드를 열고 계정 세부 정보를 확인하세요`,
  animeShopBuyAndSellProducts: `애니메이션 상점 - 상품 구매 및 판매`,
  visitStripeDashboard: `Stripe 대시보드 방문`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `AI 생성 이미지 및 신경망 필터는 금지되어 있습니다`,
  accountActivation: `계정 활성화`,
  accountAlreadyExists: `계정이 이미 있습니다.`,
  accountDoesNotExist: `계정이 없습니다.`,
  accountRemoval: `계정 삭제`,
  files: `파일`,
  prohibitedTransaction: `금지된 거래`,
  add: `추가`,
  addArt: `아트 추가`,
  addBlog: `블로그 추가`,
  additionalResources: `추가 자료`,
  addMoreProductsToYourShop: `상점에 더 많은 상품을 추가하세요`,
  addMore: `더 추가`,
  addNewArt: `새로운 아트 추가`,
  addSignInVia: `다음을 통해 로그인 추가`,
  addToCart: `장바구니에 추가`,
  advancedOptions: `고급 옵션`,
  uploadTheFilesYourBuyerWillGet: `<b>구매자가 받을</b> 파일을 업로드하세요`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `게시 후에는 수정할 수 없으니 모든 준비가 완료되었는지 확인하세요`,
  filesForTheBuyer: `구매자용 파일`,
  filesForPreview: `미리보기용 파일`,
  all: `전체`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `여기에 업로드한 모든 파일은 구매자가 이용할 수 있습니다`,
  alreadySignedIn: `이미 로그인되었습니다`,
  amount: `금액`,
  amountShouldNotBeLessThan: (...v) => `금액은 ${v[0]}보다 적을 수 없습니다.`,
  animeArtByArtistsFromAllOverTheWorld: `전 세계 예술가들의 애니메이션 아트. 아트는 애니메이션과 관련된 것으로 큐레이팅됩니다. 아트 선택은 최고의 애니메이션 아트의 무한 목록입니다`,
  animeArtSubscribeToArtistsLikeAndCreate: `애니메이션 아트-아티스트 구독, 좋아요 및 컬렉션 만들기`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club-Google 애드 센스를 통해 아티스트에게 조회수에 해당한 지불을 하는 최초의 플랫폼입니다. 콘텐츠를 보고 아티스트를 지원하거나 조회수에서 수익을 창출하세요.`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club-애니메이션 콘텐츠보기, 게시 및 수익`,
  animeCommunity: `애니메이션 커뮤니티`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club은 개인 정보를 요청하지 않습니다.`,
  animeSocialNetwork: `애니메이션 소셜 네트워크`,
  announcements: `공지사항`,
  appearance: `모양`,
  apply: `적용`,
  appSettings: `앱 설정`,
  appsVersionIs: `앱 버전은`,
  areYouSureYouWantTo: `당신은 정말로 원하십니까`,
  art: `아트`,
  artAssociatedWithAnime: `애니메이션과 관련된 아트`,
  artBy: (...v) => `${v[0]} 작품`,
  artCannotBeChanged: `아트은 변경할 수 없습니다`,
  artworksAvailableToView: (...v) => `${v[0]} 작품을 볼 수 있습니다.`,
  authenticationFailed: `인증 실패`,
  system: `시스템`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Instagram 자동 게시 기능은 Instagram 비즈니스 계정에서만 사용할 수 있습니다.`,
  attentionYourOrderHasBeenDisputed: `주의! 주문에 이의가 제기되었습니다. 세부 사항을 확인하십시오`,
  needsYourReview: `검토가 필요합니다`,
  awaitingSellersResponse: `판매자 답변 대기 중`,
  back: `뒤로`,
  basePrice: `기본 가격`,
  bigAppreciationToTheSellerForTheHardWork: `판매자의 노고에 큰 감사를 드립니다`,
  block: `차단`,
  buyerReviewedTheOrder: `구매자가 주문을 평가했습니다`,
  buyerHasNotLeftAReviewYet: `구매자가 아직 리뷰를 남기지 않았습니다`,
  feedbackReceived: `피드백이 접수되었습니다!`,
  blockUser: (...v) => `@${v[0]} 차단`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `수락하기 전에 구매자의 요청을 꼼꼼히 확인하세요`,
  blog: `블로그`,
  bookmarks: `북마크`,
  browseArt: `아트 검색`,
  browseShop: `상점 둘러보기`,
  buyer: `구매자`,
  buyersRequest: `구매자 요청`,
  cancel: `취소`,
  canceled: `취소됨`,
  comments: `댓글`,
  cancelOrder: `주문 취소`,
  cannotStartWithChars: `s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"로 시작할 수 없습니다.`,
  change: `변경`,
  checkOutMyShop: `내 상점을 확인하세요`,
  checkOrderStatus: `주문 상태 확인`,
  changeArt: `아트 변경`,
  changeAvatar: `아바타 변경`,
  changeEmail: `이메일 변경`,
  changePassword: `비밀번호 변경`,
  chooseExistingChatOrStartANewOne: `기존 채팅창 선택 또는 새로운 채팅 시작`,
  city: `도시`,
  clearAll: `모두 지우기`,
  awaitingClientReview: `의뢰인 검토 대기 중`,
  close: `닫기`,
  color: `색상`,
  colorTheme: `색상 테마`,
  comingSoon: `곧 출시됩니다…`,
  commercialUseAllowed: `상업적 사용 허용`,
  commercialUseAllowsBuyersToUseYourProduct: `상업적 사용을 허용하면 구매자가 귀하의 상품을 판매 또는 서비스 홍보 등 비즈니스 목적으로 사용할 수 있습니다`,
  community: `커뮤니티`,
  completed: `완료됨`,
  confirmAccount: `계정 확인`,
  confirmOrder: `주문 확인`,
  confirmPassword: `비밀번호 확인`,
  connectWithUsOn: `다음 채널에서 연락하세요`,
  contactInformation: `연락처 정보`,
  contactSeller: `판매자에게 연락하기`,
  contactSupport: `지원팀에게 연락하기`,
  contactUs: `문의하기`,
  continue: `계속하기`,
  contractTitle: `계약 제목`,
  copy: `복사`,
  congratulations: `축하합니다!`,
  thankYouForYourPurchase: `구매해 주셔서 감사합니다!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `주문을 성공적으로 완료하신 것을 축하합니다!`,
  copyrightViolation: `저작권 침해`,
  couldNotCreateANewRecord: `새 레코드를 만들 수 없습니다.`,
  country: `국가`,
  cover: `커버`,
  createANewAccountFailed: `새 계정을 만들지 못했습니다.`,
  createExtrasForYourProduct: `제품에 대한 추가 기능 만들기`,
  createNewAccount: `새 계정 만들기`,
  createAShopWithStripe: `Stripe로 상점 만들기`,
  createdBy: `제작자`,
  currentPassword: `현재 비밀번호`,
  daily: `매일`,
  dark: `어둡게`,
  delete: `삭제`,
  deleteShop: `상점 삭제`,
  deleteAccount: `계정 삭제`,
  deleteArt: `아트 삭제`,
  decline: `거절`,
  deletePost: `포스트 삭제`,
  deleteProduct: `제품 삭제`,
  download: `다운로드`,
  downloadThemBelow: `아래에서 다운로드하세요`,
  deliveryTime: `배송 시간`,
  describeTheDetailsOfYourExtra: `추가 서비스의 세부 정보를 설명하세요`,
  description: `서술`,
  details: `세부 사항`,
  didntReceiveEmail: `이메일을 받지 못하셨습니까?`,
  displayName: `표시 이름`,
  disputed: `분쟁 중`,
  donations: `기부`,
  documentation: `문서`,
  done: `완료`,
  dragAndDropOrSelectFiles: `드래그 & 드롭 또는 파일 선택`,
  drawingContest: `그림 콘테스트`,
  dueDate: `마감일`,
  earlier: `이전`,
  earningFromArts: `아트에서 수익`,
  edit: `편집`,
  editPost: `게시물 편집`,
  editProfile: `프로필 편집`,
  editTranslations: `번역 편집`,
  email: `이메일`,
  emailAlreadyUsedByAnotherAccount: `다른 계정에서 이미 이용 중인 이메일`,
  emailNotifications: `이메일 알림`,
  enterOrPasteALink: `링크 입력 또는 붙여넣기`,
  enjoyYourPurchase: `구매를 즐기세요! 😊`,
  enterTheAddressAssociatedWithYourAccount: `계정과 연결된 이메일 주소를 입력하면 비밀번호 재설정 링크를 이메일로 보내드립니다.`,
  enterYourPassword: `비밀번호 입력`,
  error: `오류`,
  errorPleaseContactCustomerSupport: `고객 지원에 문의하십시오 ...`,
  exitWithoutSaving: `저장하지 않고 종료`,
  extensions: `확장`,
  extras: `추가 기능`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `추가 기능은 상품을 향상시키는 선택적 부가 요소입니다`,
  fileSizeIsTooBig: `파일 크기가 너무 큽니다`,
  fileSizeIsTooSmall: `파일 크기가 너무 작습니다`,
  filter: `필터`,
  filterBy: `필터링`,
  findUser: `사용자 검색`,
  finishSettingUpYourShop: `상점 설정 완료`,
  follow: `팔로우하세요`,
  followers: `팔로워`,
  following: `팔로잉`,
  followMeOn: `저를 팔로우하세요`,
  follows: `팔로우`,
  forAllOtherInquiriesPleaseContactUsAt: `기타 모든 문의 사항은 다음 주소로 문의하십시오:`,
  forgotPassword: `비밀번호를 잊으 셨나요`,
  fromAnimeDotClub: `Anime.club에서`,
  getDetails: `세부 정보 보기`,
  getStarted: `시작하기`,
  guestView: `게스트보기`,
  greatNewsYourOrderIsNowInProgress: `좋은 소식입니다! 주문이 진행 중입니다`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `좋은 소식입니다! ${v[0]}님이 상품을 구매했습니다. 함께 축하해요!`,
  harassment: `학대`,
  haveAnyQuestions: `질문이 있습니까?`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b>님이 주문을 취소했습니다`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b>님이 작업을 제출했습니다`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]}님이 "${v[1]}"에 대한 설명을 추가하지 않았습니다.`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]}님이 아직 공개 정보를 공유하지 않았습니다.`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `@${v[0]}님은 아직 판매 상품을 등록하지 않았습니다`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `@${v[0]}님은 아직 포트폴리오에 아무것도 추가하지 않았습니다`,
  hate: `증오`,
  hereAreAFewWaysToGetThingsRolling: `시작하는 몇 가지 방법이 있습니다`,
  hire: `고용`,
  hideListing: `상품 숨기기`,
  uploadUpToNumberFiles: (...v) => `최대 <b>${v[0]}</b>개의 파일을 업로드할 수 있습니다`,
  supportedFormats: `지원 형식:`,
  minimumDimensions: (...v) => `최소 크기: ${v[0]}×${v[1]}픽셀`,
  maximumFileSize: (...v) => `파일당 최대 크기: <b>${v[0]}</b>`,
  thisListingWontBeVisibleToBuyersAnymore: `이 상품은 더 이상 구매자에게 표시되지 않습니다. 준비되면 언제든 다시 표시할 수 있습니다`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `구매자가 이 상품을 볼 수 있습니다. 언제든 다시 숨길 수 있습니다`,
  listingHiddenFromBuyers: `구매자에게 상품을 숨겼습니다`,
  listingIsNowVisibleToBuyers: `이제 구매자에게 상품이 표시됩니다`,
  showListing: `상품 표시`,
  homepage: `홈페이지`,
  howToContactYou: `연락 방법`,
  howToFindYouOnOtherSocialNetworks: `다른 소셜 네트워크에서 찾는 방법`,
  iAgreeWith: `동의합니다`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `${v[0]}까지 응답이 없으면 주문이 자동으로 완료된 것으로 표시됩니다`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `${v[0]}까지 답변이 없으면 주문이 자동으로 취소됩니다`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `${v[0]}까지 답변이 없으면 전액이 자동으로 환불됩니다`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `마감일을 놓치면 구매자가 주문을 취소하고 전액 환불을 받을 수 있으며, 관련 Stripe 수수료는 정산 금액에서 차감됩니다.`,
  id: `ID`,
  addAComment: `댓글 추가`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Img 높이는 다음보다 크거나 같아야 합니다.`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Img 너비는 다음보다 크거나 같아야 합니다.`,
  impersonation: `사칭`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `이 규칙은 판매자가 제공했으며 이 상품에만 적용됩니다`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `질문이나 우려 사항이 있으면 판매자에게 직접 문의하세요`,
  platformPoliciesMayStillApply: `플랫폼 정책도 적용될 수 있습니다`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `제품을 검색할 때 구매자가 사용할 것 같은 키워드 포함`,
  increaseContrast: `대비 높이기`,
  inProgress: `진행 중`,
  introduction: `소개`,
  includes: `포함`,
  invalidCode: `유효하지 않은 코드`,
  invalidCurrentPassword: `현재 비밀번호가 유효하지 않습니다.`,
  invalidDate: `유효하지 않은 날짜`,
  invalidPartAfterAt: `@ 뒤의 잘못된 부분`,
  invalidPartBeforeAt: `@ 앞의 잘못된 부분`,
  jobDetails: `일자리 세부 정보`,
  joinAnimeClubCommunity: `매일 활발한 창작자와 멋진 애니메이션 아트가 있는 Anime.club 커뮤니티에 참여하세요.`,
  joinChat: `채팅 참여`,
  joinUsOnFacebook: `페이스 북에서 참여하세요`,
  language: `언어`,
  lackOfInformation: `정보 부족`,
  languages: `언어`,
  letEveryoneKnowHowToDonateToYou: `기부 방법을 모두에게 알리세요.`,
  letOthersKnowAboutYou: `다른 사람들이 당신에 대해 알 수 있도록 하세요.`,
  letsUploadYourFirstProduct: `첫 번째 제품을 업로드합시다`,
  letUsKnowWhatsHappening: `무슨 일이 일어나고 있는지 알려주세요. 우리가 조사해 드리겠습니다.`,
  light: `밝게`,
  likes: `좋아요`,
  limit: `제한`,
  copiedToClipboard: `클립보드에 복사했습니다`,
  livesIn: `입주`,
  loading: `로딩 중`,
  location: `위치`,
  logInOrSignUp: `로그인 또는 가입`,
  logOut: `로그아웃`,
  maximumNChars: (...v) => `최대 ${v[0]}개 문자`,
  maximumNumberOfDaysToCompleteTheOrder: `주문 완료 최대 일수`,
  maximumQuantity: `최대 수량`,
  maxSize: `최대 크기`,
  menu: `메뉴`,
  uploadedFilesLocked: `게시물을 만들 때 업로드한 파일입니다. 현재 잠겨 있지만 아래에서 계속 확인할 수 있습니다`,
  message: `메시지`,
  messages: `쪽지`,
  minHeight: `최소 높이`,
  minimumNChars: (...v) => `최소 ${v[0]}개 문자`,
  minorAbuseOrSexualization: `미성년자 학대 또는 성적 수치심`,
  makeSureToIncludeClearInstructions: `각 참조 자료의 사용법에 대한 명확한 지침을 반드시 포함하세요`,
  makeSureYouFullyUnderstandTheRequirements: `요구 사항을 완전히 이해하고 마감일까지 주문을 완료할 수 있는지 확인하세요`,
  makeSureYourProductsArePricedCompetitively: `상품 가격이 경쟁력 있게 책정되어 있는지 확인하세요`,
  minWidth: `최소 너비`,
  monthly: `월간`,
  moreFrom: (...v) => `${v[0]}에서 더 보기`,
  mustBeNChars: (...v) => `${v[0]}개 문자 여야 합니다.`,
  myPayments: `내 결제`,
  myProfile: `내 프로필`,
  mySettings: `내 설정`,
  need1Lowercase: `소문자 1 개 필요`,
  need1Number: `숫자 1 개 필요`,
  need1Uppercase: `대문자 1 개 필요`,
  needAtLeast1CharacterFromN: (...v) => `[${v[0]}]에서 1개 문자 이상 필요`,
  needNCharacter: (...v) => `${v[0]}개 문자 필요`,
  new: `신규`,
  newAccount: `새 계정`,
  newArt: `새로운 아트`,
  createPersonalizedWorkTailoredToEachRequest: `각 요청에 맞춘 맞춤형 작품을 제작하세요`,
  offerDigitalProducts: `구매자가 즉시 이용할 수 있는 디지털 상품을 판매하세요`,
  instantDownload: `즉시 다운로드`,
  customWork: `맞춤 제작`,
  newArtworks: `새로운 아트워크`,
  newBlog: `새 블로그`,
  newOrder: `새로운 주문`,
  newPassword: `새 비밀번호`,
  newProduct: `새로운 제품`,
  allListings: `모든 상품`,
  newCommission: `새 커미션`,
  newsFeed: `뉴스 피드`,
  next: `다음`,
  nextTimeYouAuthenticateYouCouldUseThe: `다음 인증 시 연결된 계정을 사용할 수 있습니다. 로그인 및 비밀번호 대신`,
  no: `아니`,
  noOrders: `주문 없음`,
  noInternetConnection: `인터넷에 연결되지 않음!`,
  nonConsensualIntimateContent: `비동의적인 친밀한 콘텐츠`,
  none: `없음`,
  noNotifications: `알림 없음`,
  noResults: `결과 없음`,
  noReviewsJustYet: `아직 리뷰가 없습니다`,
  noCommentsJustYet: `아직 댓글이 없습니다`,
  beTheFirstToShareYourThoughts: `가장 먼저 의견을 남겨보세요`,
  notifications: `알림`,
  noActiveOrdersToShow: `표시할 활성 주문이 없습니다.`,
  notAcceptingOrders: `주문을 받지 않습니다`,
  noSalesYetNoWorries: `아직 판매가 없으신가요? 걱정하지 마세요, 이제 시작입니다`,
  nsfwContent18Plus: `NSFW 콘텐츠 (18 세 이상)`,
  NSFWIndicatesAdultContent: `18+ NSFW는 성인용 콘텐츠를 의미합니다. 상품이 성인 대상일 때만 선택하세요`,
  numberOfAdjustmentsAClientCouldRequest: `클라이언트가 요청할 수 있는 조정 횟수`,
  online: `온라인`,
  onlyLatinLettersNumbersHyphen: `라틴 문자, 숫자, 하이픈, 밑줄 및 마침표 문자만 사용 가능합니다.`,
  onlyNumbers: `숫자 만`,
  onlyYouCanSeeWhatYouveSaved: `저장한 내용은 본인만 볼 수 있습니다`,
  open: `열기`,
  openDispute: `분쟁 열기`,
  openGuestView: `게스트보기 열기`,
  openingSoon: `곧 오픈합니다!`,
  openToWork: `일할 준비가 되어 있음`,
  optional: `선택 사항`,
  requestDetails: `요청 세부 정보`,
  or: `또는`,
  order: `주문`,
  outOfStock: `재고 없음`,
  ordered: (...v) => `주문됨 ${v[0]}`,
  orderAgain: `다시 주문하기`,
  orderDetails: `주문 세부 정보`,
  orderConfirmed: `주문 확인됨`,
  orderCompleted: `주문 완료 🎉`,
  orderStatus: `주문 상태`,
  orderOptions: `주문 옵션`,
  otherReason: `다른 이유`,
  pageNotFound: `페이지를 찾을 수 없음`,
  buyNow: `지금 구매`,
  password: `암호`,
  payments: `지불`,
  attachedFiles: `첨부 파일`,
  numFilesIncluded: (...v) => `<b>${v[0]}</b>개의 파일 포함`,
  personal: `개인 정보`,
  personalCircumstances: `개인 사정`,
  theseAreYourTermsForThisItem: `이 상품에 적용되는 내 약관입니다`,
  theBuyerAcceptedThemAtCheckout: `구매자가 결제 시 이에 동의했습니다`,
  nothingIsChargedUntilTheSellerAccepts: `판매자가 수락할 때까지 결제되지 않으며, 거절하면 전혀 청구되지 않습니다`,
  orderCanceledTheBuyersPaymentWasReleased: `주문이 취소되었습니다. 구매자 카드의 승인 보류를 해제했으며, 은행 반영까지 며칠 걸릴 수 있습니다`,
  orderCanceledYourPaymentWasReleased: `주문이 취소되었습니다. 카드의 승인 보류를 해제했으며, 은행 반영까지 며칠 걸릴 수 있습니다`,
  yourTermsOfService: `내 서비스 약관`,
  showMyTermsOfService: `내 서비스 약관 보기`,
  showSellerTermsOfService: `판매자 서비스 약관 보기`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheSeller: `입력한 취소 사유는 판매자에게 공유됩니다`,
  changedMyMind: `마음이 바뀌었어요`,
  orderedByMistake: `실수로 주문했어요`,
  sellerHasntResponded: `판매자가 응답하지 않았어요`,
  foundAnotherArtist: `다른 작가를 찾았어요`,
  youWillBeAbleToUploadReferenceFilesAfterCheckout: `결제 후에 참고 파일을 업로드할 수 있습니다`,
  tellTheBuyersWhatTheyWillGet: `구매자가 받게 될 내용을 정확히 알려주세요. 예: 일러스트 수, 파일 형식, 해상도와 DPI 같은 캔버스 사양`,
  beSpecificAboutTheContent: `내용을 구체적으로 작성하세요(예: 파일 수, 형식, 캔버스 해상도)`,
  mentionYourDeliveryTimeInDays: `<b>작업 기간</b>(일수)을 작성하세요`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `<b>수정</b> 제공 여부와 제공 횟수를 알려주세요`,
  listAnyContentOrRequestsYouDontAccept: `<b>받지 않는</b> 콘텐츠나 요청을 적어주세요(예: NSFW, 정치적, 종교적 또는 불쾌감을 주는 자료)`,
  offerOptionalExtras: `<b>빠른 작업</b>, <b>캐릭터 추가</b>, <b>상세한 배경</b> 같은 선택 옵션을 제공하세요`,
  extrasHelpBoostIncome: `추가 옵션을 통해 구매자가 주문을 맞춤 설정하고 판매자는 수익을 높일 수 있습니다`,
  pleaseAllowPopups: `팝업을 허용해 주세요`,
  pleaseCheckYour: (...v) => `${v[0]}을(를) 확인해주세요.`,
  pleaseRateYourOrder: `주문을 평가해 주세요`,
  feelFreeToShareReferenceImagesAndMaterials: `아티스트가 작품을 만들 수 있도록 참고 이미지와 자료를 자유롭게 공유하세요`,
  pleaseDoNotShareYourPrivateInformationToOthers: `타인에게 개인 정보를 공유하지 마세요.`,
  pleaseEnterANumberBetweenXandX: (...v) => `${v[0]}와(과) ${v[1]} 사이의 숫자를 입력해주세요.`,
  pleaseEnterAtLeastNChars: (...v) => `${v[0]}자 이상 입력하세요.`,
  pleaseFillOutYourDetails: `세부 정보를 입력하십시오`,
  pleaseFixTheErrorsBeforeSubmitting: `제출 전에 오류를 수정해 주세요`,
  pleaseSignInToYourAccount: `귀하의 계정에 로그인하십시오`,
  platform: `플랫폼`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `구매 후 기다릴 필요 없이 파일을 바로 다운로드할 수 있습니다!`,
  thisIsACustomOrderNotAReadyMadeProduct: `완제품이 아닌 맞춤 주문입니다. 주문 후 판매자가 제작을 시작합니다`,
  pleaseStartTyping: `입력을 시작하십시오`,
  pleaseTakeAMomentToReviewTheOrder: `주문을 잠시 검토해 주세요`,
  pleaseReviewTheBuyersReferenceFiles: `구매자의 참조 파일을 검토하고 주문 설명에 따라 진행하세요`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `진행하기 전에 세부 정보를 꼼꼼히 확인하세요`,
  pleaseRespondToTheOrderBy: (...v) => `${v[0]}까지 주문에 응답해 주세요`,
  pleaseTryAgainOrClick: (...v) => `다시 시도하거나 ${v[0]}을 클릭하세요`,
  whatWouldYouLikeToCreate: `무엇을 만들고 싶으신가요?`,
  shareYourArt: `작품 공유`,
  ifYourArtIsNsfwCheckThisToAvoidAWarningOrBan: `작품이 NSFW라면 반드시 이 항목을 선택하세요. 선택하지 않으면 경고를 받거나 계정이 정지될 수 있습니다.`,
  takeCustomRequests: `맞춤 요청 받기`,
  sellDownloadableContent: `다운로드 콘텐츠 판매`,
  digitalDownloadsExamples: `브러시, 에셋, 튜토리얼 등`,
  artGallery: `아트 갤러리`,
  commission: `커미션`,
  commissions: `커미션`,
  digitalDownloads: `디지털 다운로드`,
  pleaseVerifyYourAccount: `계정을 확인하십시오`,
  pressHereTo: `여기를 눌러주세요`,
  price: `가격`,
  payouts: `정산`,
  privacyPolicy: `트위터 개인정보 처리방침`,
  privateInformation: `개인 정보`,
  proceedToCheckout: `결제 진행하기`,
  product: `제품`,
  itemReviews: `상품 리뷰`,
  portfolio: `포트폴리오`,
  profile: `프로필`,
  promotions: `프로모션`,
  publicInformation: `공개 정보`,
  publishOn: (...v) => `${v[0]}에 게시`,
  purchases: `구매`,
  rankings: `순위`,
  reorderFiles: `파일 재정렬`,
  report: `신고`,
  review: `리뷰`,
  rules: `규칙`,
  reviews: `리뷰`,
  numOfReviews: (...v) => `리뷰: ${v[0]} `,
  reviewed: `리뷰됨`,
  reviewTitle: `리뷰 제목`,
  reason: `이유`,
  revisions: `개정`,
  includesXRevisionS: (...v) => `${v[0]}회 수정 포함`,
  sales: `판매`,
  save: `저장`,
  saveAvatar: `아바타 저장`,
  saveChanges: `변경 사항 저장`,
  selectAnime: `애니메이션 선택 `,
  selectAppearanceContrastAndColorTheme: `모양, 대비 및 색상 테마 선택`,
  selectAvatar: `아바타 선택`,
  selectCharacters: `문자 선택`,
  seller: `판매자`,
  selectFile: `파일 선택`,
  selectThumbnail: `썸네일 선택`,
  selfHarmOrSuicide: `자해 또는 자살`,
  sendEmail: `이메일 보내기`,
  settings: `설정`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `상점 설정은 무료이며 몇 분만에 완료됩니다.`,
  share: `공유`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `수락하지 않는 요청 유형과 규칙을 공유하세요`,
  shareYourShopOnSocialMedia: `상점을 소셜 미디어에 공유하세요`,
  shareYourFavoritePiecesOn: (...v) => `${v[0]}에 좋아하는 작품을 공유하세요`,
  shareYourArtWithTheWorld: `당신의 예술을 세상과 공유하세요.`,
  shareYourStory: `당신의 이야기를 공유하세요!`,
  sharingPersonalInformation: `개인 정보 공유`,
  shop: `상점`,
  shopReviews: `상점 리뷰`,
  shopOrders: `상점 주문`,
  showLess: `간략히 보기`,
  showMore: `더 보기`,
  show: `표시`,
  hide: `숨기기`,
  signIn: `로그인`,
  size: `크기`,
  skip: `건너 뛰기`,
  socialMedia: `소셜 미디어`,
  spaceCharacterIsNotAllowed: `공백 문자는 허용되지 않습니다.`,
  spam: `스팸`,
  yourFavoritesWillShowUpHereAddSome: `즐겨찾기는 여기에 표시됩니다. 추가해 보세요!`,
  submitAReport: `신고 제출`,
  submitWork: `작품 제출`,
  subscribeToTalentsToKeepUpWithTheirProgress: `진행 상황을 확인하려면 크리에이터를 구독하세요`,
  successChangedPasswordPleaseSignIn: `성공! 비밀번호를 변경했습니다. 로그인 해주세요`,
  successCreatedRecord: `성공! 기록을 만들었습니다!`,
  changesSaved: `변경 사항을 저장했습니다!`,
  successfullyDownloaded: `성공적으로 다운로드되었습니다!`,
  successfullyUploaded: `성공적으로 업로드되었습니다!`,
  setUpStripeAccountToGetPaidWithAnimeClub: `Anime.club에서 정산받을 Stripe 계정을 설정하세요`,
  supportMeOn: `N에서 저를 지원해주세요`,
  tellUsAboutYourself: `자신에 대한 정보를 알려주십시오`,
  sellerTermsOfService: `판매자 이용 약관`,
  termsAndConditions: `계약 조건`,
  termsOfUse: `이용 약관`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `포함된 내용과 구매 후 구매자가 받을 수 있는 것을 설명하세요`,
  thankYouForReport: `안전하고 존중받는 온라인 커뮤니티를 유지하는 데 도움을 주셔서 감사합니다.`,
  thankYouForYourReview: `리뷰해 주셔서 감사합니다!`,
  theLinkIsBrokenOrPageHasBeenRemoved: `링크가 깨졌거나 페이지가 삭제되었습니다.`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `입력한 주문 취소 사유는 구매자에게 공유됩니다`,
  thisIsThePriceYouPropose: `제안한 가격입니다`,
  thisFieldIsOptional: `이 항목은 선택 사항입니다`,
  thisCannotBeUndone: `이 작업은 되돌릴 수 없습니다`,
  ensureYouveUploadedTheFinalVersion: `최종 버전을 업로드한 후 제출해 주세요`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `원한다면 설명을 추가해 작품에 대해 더 자세히 소개할 수 있습니다`,
  pleaseProvideATitleForYourArtwork: `작품 제목을 입력해 주세요`,
  threateningViolence: `폭력을 위협하는 행위`,
  title: `표제`,
  timeConstraints: `시간 제약`,
  titleYourExtraService: `추가 서비스 제목`,
  theMaximumQuantityThatACustomerCanAdd: `고객이 추가할 수 있는 최대 수량`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `검토 기간은 ${v[0]}일로 제한됩니다`,
  toHelpTheCreatorCompleteYourOrder: `창작자가 주문을 만족스럽게 완료할 수 있도록 원하는 주제, 스타일, 캐릭터 특징 및 기타 중요한 사양을 포함한 자세한 설명을 제공하십시오`,
  today: `오늘`,
  toGetWorkRelatedNotifications: `작업 관련 알림을 받으려면`,
  total: `합계`,
  toViewThisDataYouNeedToUnblock: (...v) => `이 데이터를 보려면 @${v[0]}의 차단을 해제해야 합니다.`,
  trademarkViolation: `상표권 침해`,
  typeYourTextHere: `여기에 텍스트를 입력하세요 ...`,
  theSellerHasUploadedTheseFilesForYou: `판매자가 이 파일들을 업로드했습니다`,
  unblock: `차단 해제`,
  unblockUser: (...v) => `@${v[0]} 차단 해제`,
  unfollow: `언팔로우`,
  unlimited: `무제한`,
  upload: `업로드`,
  uploadNew: `새로운 업로드`,
  uploadNewPost: `새 게시물 업로드`,
  uploadNewProduct: `새 제품 업로드`,
  username: `사용자 이름`,
  pleaseUploadOnlyFinishedWorkHere: `여기에는 완성된 작업만 업로드해 주세요`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `진행 중인 파일은 메시지로 업로드해 주세요`,
  usernameAlreadyExists: `사용자 이름이 이미 존재합니다`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b>님과 ${v[1]}명이 팔로우합니다.`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b>님과 ${v[1]}명이 반응했습니다`,
  usernameStartedFollowingYou: (...v) => `<b>${v[0]}</b>님이 팔로우하기 시작했습니다`,
  usernameLeftAReaction: (...v) => `<b>${v[0]}</b>님이 반응을 남겼습니다`,
  usernameCommentedOnYourWork: (...v) => `<b>${v[0]}</b>님이 작품에 댓글을 남겼습니다`,
  usernameAndXMoreCommented: (...v) => `<b>${v[0]}</b>님 외 ${v[1]}명이 댓글을 남겼습니다`,
  usernameRepliedToYourComment: (...v) => `<b>${v[0]}</b>님이 댓글에 답글을 남겼습니다`,
  usernameAndXMoreRepliedToYourComment: (...v) =>
    `<b>${v[0]}</b>님 외 ${v[1]}명이 댓글에 답글을 남겼습니다`,
  useThisEmailTo: `이 이메일을 사용하여 인증하고 알림을 받습니다.`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `안타깝게도 ${v[0]}님이 이 주문을 취소해야 했습니다`,
  valueIsNotTheSame: `값이 같지 않습니다`,
  vote: `투표`,
  tapAddToCreateOne: `“추가”를 눌러 만드세요`,
  verificationCode: `확인 코드`,
  verifyCode: `코드 확인`,
  viewDetails: `자세히 보기`,
  viewReview: `리뷰 보기`,
  viewEveryNotificationOfAGroupSeparately: `그룹의 모든 알림을 개별적으로 볼 수 있습니다.`,
  visitOurDiscordChannelToGetMoreDetails: `저희의 디스코드 채널을 방문하시면 자세한 내용을 보실 수 있습니다`,
  weAreOnInstagram: `우리는 인스타그램에 있습니다`,
  weAreWorkingOnIt: `열심히 준비를 하고 있습니다.`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `잘하셨습니다! 작업이 성공적으로 완료되었습니다`,
  weDoNotDisplayNSFWContentYet: `NSFW 콘텐츠는 아직 표시하지 않습니다.`,
  weekly: `주간`,
  whenYouPurchaseSomethingItWillAppearHere: `무언가를 구매하면 여기에 표시됩니다.`,
  weHaveSentTooManyEmails: `너무 많은 이메일을 보냈습니다. 나중에 다시 시도하거나 고객 지원에 문의하십시오.`,
  welcomeToAnimeClub: `Anime.club에 오신 것을 환영합니다!`,
  weSentAnEmailTo: `다음 주소로 이메일을 보냈습니다.`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `새 확인 이메일을 보냈습니다. 코드를 입력하세요`,
  weAreExcitedToSeeYourProgressKeepItUp: `귀하의 진행 상황을 보게 되어 기쁩니다. 계속 유지하십시오!`,
  weSupportOnlyTheFollowingFileExtensions: `다음 파일 확장자 만 지원합니다:`,
  work: `작업`,
  weWouldLoveToHearFromYou: `귀하의 의견을 듣고 싶습니다`,
  workDescription: `작업 설명`,
  leaveAReview: `리뷰 남기기`,
  wrongEmailOrPassword: `잘못된 이메일 또는 암호`,
  yes: `예 `,
  yesterday: `어제`,
  youReceivedANewOrderFrom: (...v) => `<b>${v[0]}</b>님으로부터 새 주문을 받았습니다`,
  youReceivedAReview: `리뷰를 받았습니다`,
  reply: `답글`,
  youHaveSuccessfullyCreatedYourShop: `상점을 성공적으로 생성했습니다`,
  replyToUsername: (...v) => `${v[0]}님에게 답글`,
  numOfReplies: (...v) => `답글 ${v[0]}개`,
  numOfNewComments: (...v) => `새 댓글 ${v[0]}개`,
  numOfNewReactions: (...v) => `새 반응 ${v[0]}개`,
  replies: `답글`,
  youAreAlreadyAuthenticated: `이미 인증되었습니다`,
  youCanAutoPublishToYourSocialMediaAccount: `소셜 미디어 계정에 자동으로 게시할 수 있습니다.`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `이메일로 받는 알림 유형을 수정할 수 있습니다.`,
  youCanRequestRemovalOfYourAccount: `계정 및 모든 데이터를 삭제 요청할 수 있습니다.`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `귀하의 피드백은 구매자에게 도움이 되고 판매자가 더 나은 상품을 제공하는 데 도움이 됩니다`,
  youCanStillNavigateToThePreviouslyOpenedPages: `이전에 열었던 페이지로 아직은 이동할 수 있습니다.`,
  youCanChooseFromTheListOrEnterACustomReason: `목록에서 선택하거나 직접 사유를 입력할 수 있습니다`,
  youDidNotSelectAnyChats: `채팅창을 선택하지 않았습니다`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `구매자가 경험을 공유하면 이곳에 리뷰가 표시됩니다`,
  youDidNotUpdateAnyValues: `값을 업데이트하지 않았습니다.`,
  youDoNotHaveAnyChats: `채팅창이 존재하지 않습니다`,
  youHaveNotSetAPassword: `비밀번호를 설정하지 않았습니다.`,
  youHaveNotSharedAnythingYet: `아직 아무것도 공유하지 않았습니다.`,
  youHaveReachedTheMaximumNumberOfFiles: `최대 파일 수에 도달했습니다.`,
  kindlyHoldOnForTheBuyersReview: `구매자의 주문 리뷰를 기다려주십시오.`,
  yourAccountIsVerifiedPleaseSignIn: `귀하의 계정이 확인되었습니다. 로그인 해주세요`,
  yourAccountWillBeRemoved: (...v) => `계정이 ${v[0]}에 삭제됩니다.`,
  youHaveNoPurchases: `구매 내역이 없습니다.`,
  couldYouPleaseProvideTheReasonForTheCancellation: `취소 이유를 제공해 주시겠습니까`,
  yourArts: `귀하의 아트`,
  youCanceledTheOrder: `주문을 취소하셨습니다`,
  yourAvatar: `귀하의 아바타`,
  yourBlog: `귀하의블로그`,
  yourFansAreWaiting: `팬들이 기다리고 있습니다`,
  yourFeedIsEmpty: `피드가 비었습니다`,
  yourSessionHasExpiredPleaseSignInAgain: `세션이 만료되었습니다. 다시 로그인하십시오.`,
}
