export const text: text = {
  _dash: `(en) - `,
  acceptTheOrder: `(en) Accept the order`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `(en) AI-generated images and neural network filters are prohibited`,
  addMoreProductsToYourShop: `(en) Add more products to your shop`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `(en) All files you upload here will be available to the buyer`,
  bigAppreciationToTheSellerForTheirHardWork: `(en) Big appreciation to the seller for their hard work`,
  buyerReviewedTheOrder: `(en) Buyer reviewed the order`,
  buyerHasNotLeftAReviewYet: `(en) Buyer has not left a review yet`,
  feedbackReceived: `(en) Feedback received!`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `(en) Before accepting, please review the buyer's request carefully`,
  checkOutMyShop: `(en) Check out my shop`,
  commercialUseAllowed: `(en) Commercial use allowed`,
  commercialUseAllowsBuyersToUseYourProduct: `(en) Commercial use allows buyers to use your product for business purposes, like selling or promoting their services`,
  congratulationsOnSuccessfullyCompletingYourOrder: `(en) Congratulations on successfully completing your order!`,
  createAShopWithStripe: `(en) Create a shop with Stripe`,
  createdBy: `(en) Created by`,
  download: `(en) Dowload`,
  downloadThemBelow: `(en) Download them below`,
  describeTheDetailsOfYourExtra: `(en) Describe the details of your extra`,
  enjoyYourPurchase: `(en) Enjoy your purchase! 😊`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `(en) Extras are optional add-ons to enhance your product`,
  usernameHasSubmittedTheWork: (...v) =>
    `(en) <b>${v[0]}</b> has submitted the work`,
  hereAreAFewWaysToGetThingsRolling: `(en) Here are a few ways to get things rolling`,
  makeSureToIncludeClearInstructions: `(en) Make sure to include clear instructions on how each reference should be used`,
  makeSureYouFullyUnderstandTheRequirements: `(en) Make sure you fully understand the requirements and can complete the order by the deadline`,
  makeSureYourProductsArePricedCompetitively: `(en) Make sure your products are priced competitively`,
  noSalesYetNoWorries: `(en) No sales yet? No worries, you're just starting out`,
  NSFWIndicatesAdultContent: `(en) 18+ NSFW indicates adult content. Check this field only if your product is intended for mature audiences`,
  onlyYouCanSeeWhatYouveSaved: `(en) Only you can see what you've saved`,
  requestDetails: `(en) Request details`,
  orderCompleted: `(en) Order Completed 🎉`,
  pleaseRateYourOrder: `(en) Please rate your order`,
  feelFreeToShareReferenceImagesAndMaterials: `(en) Feel free to share reference images and materials to help the artist create your piece`,
  pleaseFixTheErrorsBeforeSubmitting: `(en) Please fix the errors before submitting`,
  pleaseTakeAMomentToReviewTheOrder: `(en) Please take a moment to review the order 🙏 `,
  pleaseReviewTheBuyersReferenceFiles: `(en) Please review the buyer's reference files and follow them as specified in the order's description`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `(en) Please review the details carefully before proceeding`,
  pleaseRespondToTheOrderBy: (...v) =>
    `(en) Please respond to the order by ${v[0]}`,
  review: `(en) Review`,
  reviews: `(en) Reviews`,
  reviewed: `(en) Reviewed`,
  reviewTitle: `(en) Review title`,
  reason: `(en) Reason`,
  yourOrderIncludesXRevisionS: (...v) =>
    `(en) Your order includes ${v[0]} revision(s)`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `(en) Share your rules and the types of requests you don’t accept`,
  shareYourShopOnSocialMedia: `(en) Share your shop on social media`,
  shareYourFavoritePiecesOn: (...v) =>
    `(en) Share your favorite pieces on ${v[0]}`,
  shopReviews: `(en) Shop reviews`,
  startAddingFavoritesToSeeThemHere: `(en) Start adding favorites to see them here`,
  successfullyDownloaded: `(en) Successfully downloaded!`,
  tellTheBuyerWhatTheyWillGetWithThisProduct: `(en) Tell the buyer what they will get with this product`,
  thankYouForYourReview: `(en) Thank you for your review!`,
  thankForYourSupport: `(en) Thank you for your support!`,
  thisFieldIsOptional: `(en) This field is optional`,
  thisCannotBeUndone: `(en) This cannot be undone`,
  ensureYouveUploadedTheFinalVersion: `(en)  Ensure you've uploaded the final version before submitting`,
  theSellerHasUploadedTheseFilesForYou: `(en) The seller has uploaded these files for you`,
  pleaseUploadOnlyFinishedWorkHereMaximumFiles: `(en) Please upload only finished work here`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `(en) All WIP-related files should be uploaded in messages`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `(en) Unfortunately, ${v[0]} had to cancel this order`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `(en) Well done! Work has been successfully completed`,
  youReceivedAReview: `(en) You received a review`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `(en) Your feedback guides buyers and helps sellers offer better products`,
  youCanceledTheOrder: `(en) You canceled the order`,
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `소개`,
  accept: `수락`,
  acceptOrder: `주문 수락`,
  account: `계정`,
  accountDeleted: `계정이 삭제되었습니다`,
  accountActivation: `계정 활성화`,
  accountAlreadyExists: `계정이 이미 있습니다.`,
  accountDoesNotExist: `계정이 없습니다.`,
  accountRemoval: `계정 삭제`,
  add: `추가`,
  addArt: `아트 추가`,
  addBlog: `블로그 추가`,
  addFile: `파일 추가`,
  additionalResources: `추가 자료`,
  addMore: `더 추가`,
  addNewArt: `새로운 아트 추가`,
  addPreview: `미리보기 추가`,
  addSignInVia: `다음을 통해 로그인 추가`,
  addToCart: `장바구니에 추가`,
  advancedOptions: `고급 옵션`,
  all: `전체`,
  alreadySignedIn: `이미 로그인되었습니다`,
  amount: `금액`,
  amountShouldNotBeLessThan: (...v) => `금액은 ${v[0]}보다 적을 수 없습니다.`,
  animeArtByArtistsFromAllOverTheWorld: `전 세계 예술가들의 애니메이션 아트. 아트는 애니메이션과 관련된 것으로 큐레이팅됩니다. 아트 선택은 최고의 애니메이션 아트의 무한 목록입니다`,
  animeArtSubscribeToArtistsLikeAndCreate: `애니메이션 아트-아티스트 구독, 좋아요 및 컬렉션 만들기`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club-Google 애드 센스를 통해 아티스트에게 조회수에 해당한 지불을 하는 최초의 플랫폼입니다. 콘텐츠를 보고 아티스트를 지원하거나 조회수에서 수익을 창출하세요.`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club-애니메이션 콘텐츠보기, 게시 및 수익`,
  animeCommunity: `애니메이션 커뮤니티`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club은 개인 정보를 요청하지 않습니다.`,
  animeSocialNetwork: `애니메이션 소셜 네트워크`,
  announcements: `공지사항`,
  apply: `적용`,
  appSettings: `앱 설정`,
  appsVersionIs: `앱 버전은`,
  areYouSureYouWantTo: `당신은 정말로 원하십니까`,
  art: `아트`,
  artAssociatedWithAnime: `애니메이션과 관련된 아트`,
  artBy: (...v) => `${v[0]} 작품`,
  artCannotBeChanged: `아트은 변경할 수 없습니다`,
  artworksAvailableToView: (...v) => `${v[0]} 작품을 볼 수 있습니다.`,
  authenticationFailed: `인증 실패`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Instagram 자동 게시 기능은 Instagram 비즈니스 계정에서만 사용할 수 있습니다.`,
  attentionYourOrderHasBeenDisputed: `주의! 주문에 이의가 제기되었습니다. 세부 사항을 확인하십시오`,
  awaitingReview: `검토 대기 중`,
  awaitingSeller: `판매자 대기 중`,
  back: `뒤로`,
  basePrice: `기본 가격`,
  block: `차단`,
  blockUser: (...v) => `@${v[0]} 차단`,
  blog: `블로그`,
  bookmarks: `북마크`,
  browseArt: `아트 검색`,
  browseShop: `상점 둘러보기`,
  buyer: `구매자`,
  cancel: `취소`,
  canceled: `취소됨`,
  cancelOrder: `주문 취소`,
  cannotStartWithChars: `s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"로 시작할 수 없습니다.`,
  change: `변경`,
  checkOrderStatus: `주문 상태 확인`,
  changeArt: `아트 변경`,
  changeAvatar: `아바타 변경`,
  changeEmail: `이메일 변경`,
  changePassword: `비밀번호 변경`,
  chooseExistingChatOrStartANewOne: `기존 채팅창 선택 또는 새로운 채팅 시작`,
  city: `도시`,
  clearAll: `모두 지우기`,
  clientReview: `클라이언트 리뷰`,
  close: `닫기`,
  colorTheme: `색상 테마`,
  comingSoon: `곧 출시됩니다…`,
  community: `커뮤니티`,
  completed: `완료됨`,
  confirmAccount: `계정 확인`,
  confirmOrder: `주문 확인`,
  confirmPassword: `비밀번호 확인`,
  connectWithUsOn: `다음 채널에서 연락하세요`,
  contactInformation: `연락처 정보`,
  contactSeller: `판매자에게 연락하기`,
  contactSupport: `지원팀에게 연락하기`,
  contactUs: `문의하기`,
  continue: `계속하기`,
  contractTitle: `계약 제목`,
  copyLink: `링크 복사`,
  congratulations: `축하합니다!`,
  copyrightViolation: `저작권 침해`,
  couldNotCreateANewRecord: `새 레코드를 만들 수 없습니다.`,
  country: `국가`,
  cover: `커버`,
  createANewAccountFailed: `새 계정을 만들지 못했습니다.`,
  createExtrasForYourProduct: `제품에 대한 추가 기능 만들기`,
  createNewAccount: `새 계정 만들기`,
  currentPassword: `현재 비밀번호`,
  daily: `매일`,
  darkDefault: `어두운 기본`,
  darkHighContrast: `어두운 고대비`,
  dayTheme: `주간 테마`,
  delete: `삭제`,
  deleteShop: `상점 삭제`,
  deleteAccount: `계정 삭제`,
  deleteArt: `아트 삭제`,
  decline: `거절`,
  deletePost: `포스트 삭제`,
  deleteProduct: `제품 삭제`,
  deliveryTime: `배송 시간`,
  description: `서술`,
  details: `세부 사항`,
  didntReceiveEmail: `이메일을 받지 못하셨습니까?`,
  displayName: `표시 이름`,
  disputed: `분쟁 중`,
  donations: `기부`,
  done: `완료`,
  dragAndDropOrSelectFiles: `드래그 & 드롭 또는 파일 선택`,
  drawingContest: `그림 콘테스트`,
  dueDate: `마감일`,
  earlier: `이전`,
  earningFromArts: `아트에서 수익`,
  edit: `편집`,
  editPost: `게시물 편집`,
  editProfile: `프로필 편집`,
  editTranslations: `번역 편집`,
  email: `이메일`,
  emailAlreadyUsedByAnotherAccount: `다른 계정에서 이미 이용 중인 이메일`,
  emailNotifications: `이메일 알림`,
  enterOrPasteALink: `링크 입력 또는 붙여넣기`,
  enterTheAddressAssociatedWithYourAccount: `계정과 연결된 이메일 주소를 입력하면 비밀번호 재설정 링크를 이메일로 보내드립니다.`,
  enterYourPassword: `비밀번호 입력`,
  error: `오류`,
  errorPleaseContactCustomerSupport: `고객 지원에 문의하십시오 ...`,
  exitWithoutSaving: `저장하지 않고 종료`,
  extensions: `확장`,
  extras: `추가 기능`,
  fileSizeIsTooBig: `파일 크기가 너무 큽니다`,
  fileSizeIsTooSmall: `파일 크기가 너무 작습니다`,
  filter: `필터`,
  filterBy: `필터링`,
  findUser: `사용자 검색`,
  finishSettingUpYourShop: `상점 설정 완료`,
  follow: `팔로우하세요`,
  followers: `팔로워`,
  following: `팔로잉`,
  followMeOn: `저를 팔로우하세요`,
  follows: `팔로우`,
  forAllOtherInquiriesPleaseContactUsAt: `기타 모든 문의 사항은 다음 주소로 문의하십시오:`,
  forgotPassword: `비밀번호를 잊으 셨나요`,
  fromAnimeDotClub: `Anime.club에서`,
  getDetails: `세부 정보 보기`,
  getStarted: `시작하기`,
  guestView: `게스트보기`,
  greatNewsYourOrderIsNowInProgress: `좋은 소식입니다! 주문이 진행 중입니다`,
  harassment: `학대`,
  haveAnyQuestions: `질문이 있습니까?`,
  usernameHasCanceledTheOrder: (...v) =>
    `<b>${v[0]}</b>님이 주문을 취소했습니다`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]}님이 "${v[1]}"에 대한 설명을 추가하지 않았습니다.`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]}님이 아직 공개 정보를 공유하지 않았습니다.`,
  hate: `증오`,
  hire: `고용`,
  homepage: `홈페이지`,
  howToContactYou: `연락 방법`,
  howToFindYouOnOtherSocialNetworks: `다른 소셜 네트워크에서 찾는 방법`,
  iAgreeWith: `동의합니다`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `${v[0]}까지 응답이 없으면 주문이 자동으로 완료된 것으로 표시됩니다`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Img 높이는 다음보다 크거나 같아야 합니다.`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Img 너비는 다음보다 크거나 같아야 합니다.`,
  impersonation: `사칭`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `제품을 검색할 때 구매자가 사용할 것 같은 키워드 포함`,
  inProgress: `진행 중`,
  introduction: `소개`,
  invalidCode: `유효하지 않은 코드`,
  invalidCurrentPassword: `현재 비밀번호가 유효하지 않습니다.`,
  invalidDate: `유효하지 않은 날짜`,
  invalidPartAfterAt: `@ 뒤의 잘못된 부분`,
  invalidPartBeforeAt: `@ 앞의 잘못된 부분`,
  jobDetails: `일자리 세부 정보`,
  joinAnimeClubCommunity: `매일 활발한 창작자와 멋진 애니메이션 아트가 있는 Anime.club 커뮤니티에 참여하세요.`,
  joinChat: `채팅 참여`,
  joinUsOnFacebook: `페이스 북에서 참여하세요`,
  language: `언어`,
  lackOfInformation: `정보 부족`,
  languages: `언어`,
  letEveryoneKnowHowToDonateToYou: `기부 방법을 모두에게 알리세요.`,
  letOthersKnowAboutYou: `다른 사람들이 당신에 대해 알 수 있도록 하세요.`,
  letsUploadYourFirstProduct: `첫 번째 제품을 업로드합시다`,
  letUsKnowWhatsHappening: `무슨 일이 일어나고 있는지 알려주세요. 우리가 조사해 드리겠습니다.`,
  lightDefault: `밝은 기본`,
  lightHighContrast: `밝은 고대비`,
  likes: `좋아요`,
  limit: `제한`,
  linkCopiedToClipboard: `링크가 클립보드에 복사되었습니다`,
  livesIn: `입주`,
  loading: `로딩 중`,
  location: `위치`,
  logInOrSignUp: `로그인 또는 가입`,
  logOut: `로그아웃`,
  maximumNChars: (...v) => `최대 ${v[0]}개 문자`,
  maximumNumberOfDaysToCompleteTheOrder: `주문 완료 최대 일수`,
  maximumQuantity: `최대 수량`,
  maxSize: `최대 크기`,
  menu: `메뉴`,
  message: `메시지`,
  messages: `쪽지`,
  minHeight: `최소 높이`,
  minimumNChars: (...v) => `최소 ${v[0]}개 문자`,
  minorAbuseOrSexualization: `미성년자 학대 또는 성적 수치심`,
  minWidth: `최소 너비`,
  monthly: `월간`,
  moreFrom: (...v) => `${v[0]}에서 더 보기`,
  mustBeNChars: (...v) => `${v[0]}개 문자 여야 합니다.`,
  myPayments: `내 결제`,
  myProfile: `내 프로필`,
  mySettings: `내 설정`,
  need1Lowercase: `소문자 1 개 필요`,
  need1Number: `숫자 1 개 필요`,
  need1Uppercase: `대문자 1 개 필요`,
  needAtLeast1CharacterFromN: (...v) => `[${v[0]}]에서 1개 문자 이상 필요`,
  needNCharacter: (...v) => `${v[0]}개 문자 필요`,
  newAccount: `새 계정`,
  newArt: `새로운 아트`,
  newArtworks: `새로운 아트워크`,
  newBlog: `새 블로그`,
  newOrder: `새로운 주문`,
  newPassword: `새 비밀번호`,
  newProduct: `새로운 제품`,
  newsFeed: `뉴스 피드`,
  next: `다음`,
  nextTimeYouAuthenticateYouCouldUseThe: `다음 인증 시 연결된 계정을 사용할 수 있습니다. 로그인 및 비밀번호 대신`,
  nightTheme: `야간 테마`,
  no: `아니`,
  noInternetConnection: `인터넷에 연결되지 않음!`,
  nonConsensualIntimateContent: `비동의적인 친밀한 콘텐츠`,
  none: `없음`,
  noNotifications: `알림 없음`,
  noResults: `결과 없음`,
  notifications: `알림`,
  noActiveOrdersToShow: `표시할 활성 주문이 없습니다.`,
  notAcceptingOrders: `주문을 받지 않습니다`,
  nsfwContent18Plus: `NSFW 콘텐츠 (18 세 이상)`,
  numberOfAdjustmentsAClientCouldRequest: `클라이언트가 요청할 수 있는 조정 횟수`,
  online: `온라인`,
  onlyLatinLettersNumbersHyphen: `라틴 문자, 숫자, 하이픈, 밑줄 및 마침표 문자만 사용 가능합니다.`,
  onlyNumbers: `숫자 만`,
  open: `열기`,
  openDispute: `분쟁 열기`,
  openGuestView: `게스트보기 열기`,
  openingSoon: `곧 오픈합니다!`,
  openToWork: `일할 준비가 되어 있음`,
  optional: `선택 사항`,
  or: `또는`,
  order: `주문`,
  outOfStock: `재고 없음`,
  ordered: (...v) => `주문됨 ${v[0]}`,
  orderAgain: `다시 주문하기`,
  orderDetails: `주문 세부 정보`,
  orderConfirmed: `주문 확인됨`,
  orderStatus: `주문 상태`,
  orderOptions: `주문 옵션`,
  otherReason: `다른 이유`,
  pageNotFound: `페이지를 찾을 수 없음`,
  password: `암호`,
  payments: `지불`,
  personal: `개인 정보`,
  personalCircumstances: `개인 사정`,
  pleaseCheckYour: (...v) => `${v[0]}을(를) 확인해주세요.`,
  pleaseDoNotShareYourPrivateInformationToOthers: `타인에게 개인 정보를 공유하지 마세요.`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `${v[0]}와(과) ${v[1]} 사이의 숫자를 입력해주세요.`,
  pleaseEnterAtLeastNChars: (...v) => `${v[0]}자 이상 입력하세요.`,
  pleaseFillOutYourDetails: `세부 정보를 입력하십시오`,
  pleaseSignInToYourAccount: `귀하의 계정에 로그인하십시오`,
  platform: `플랫폼`,
  pleaseStartTyping: `입력을 시작하십시오`,
  pleaseTryAgainOrClick: (...v) => `다시 시도하거나 ${v[0]}을 클릭하세요`,
  pleaseVerifyYourAccount: `계정을 확인하십시오`,
  pressHereTo: `여기를 눌러주세요`,
  price: `가격`,
  privacyPolicy: `트위터 개인정보 처리방침`,
  privateInformation: `개인 정보`,
  proceedToCheckout: `결제 진행하기`,
  product: `제품`,
  profile: `프로필`,
  prohibitedTransaction: `금지된 거래`,
  promotions: `프로모션`,
  publicInformation: `공개 정보`,
  publishOn: (...v) => `${v[0]}에 게시`,
  purchases: `구매`,
  rankings: `순위`,
  reorderFiles: `파일 재정렬`,
  report: `신고`,
  revisions: `개정`,
  sales: `판매`,
  save: `저장`,
  saveAvatar: `아바타 저장`,
  saveChanges: `변경 사항 저장`,
  selectAnime: `애니메이션 선택 `,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `단일 테마를 선택하거나 시스템과 동기화하여 자동으로 주간 및 야간 테마를 전환하세요.`,
  selectAvatar: `아바타 선택`,
  selectCharacters: `문자 선택`,
  seller: `판매자`,
  selectFile: `파일 선택`,
  selectTheme: `테마 선택`,
  selectThumbnail: `썸네일 선택`,
  selfHarmOrSuicide: `자해 또는 자살`,
  sendEmail: `이메일 보내기`,
  settings: `설정`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `상점 설정은 무료이며 몇 분만에 완료됩니다.`,
  share: `공유`,
  shareYourArtWithTheWorld: `당신의 예술을 세상과 공유하세요.`,
  shareYourStory: `당신의 이야기를 공유하세요!`,
  sharingPersonalInformation: `개인 정보 공유`,
  shop: `상점`,
  shopOrders: `상점 주문`,
  showLess: `간략히 보기`,
  showMore: `더 보기`,
  signIn: `로그인`,
  singleTheme: `단일 테마`,
  size: `크기`,
  skip: `건너 뛰기`,
  socialMedia: `소셜 미디어`,
  spaceCharacterIsNotAllowed: `공백 문자는 허용되지 않습니다.`,
  spam: `스팸`,
  submitAReport: `신고 제출`,
  submitWork: `작품 제출`,
  subscribeToTalentsToKeepUpWithTheirProgress: `진행 상황을 확인하려면 크리에이터를 구독하세요`,
  successChangedPasswordPleaseSignIn: `성공! 비밀번호를 변경했습니다. 로그인 해주세요`,
  successCreatedRecord: `성공! 기록을 만들었습니다!`,
  successUpdatedRecord: `성공!기록이 업데이트 되였습니다!`,
  supportMeOn: `N에서 저를 지원해주세요`,
  syncWithSystem: `시스템과 동기화`,
  tellUsAboutYourself: `자신에 대한 정보를 알려주십시오`,
  termsAndConditions: `계약 조건`,
  termsOfUse: `이용 약관`,
  thankYouForReport: `안전하고 존중받는 온라인 커뮤니티를 유지하는 데 도움을 주셔서 감사합니다.`,
  theLinkIsBrokenOrPageHasBeenRemoved: `링크가 깨졌거나 페이지가 삭제되었습니다.`,
  themeMode: `테마 모드`,
  thisIsThePriceYouPropose: `제안한 가격입니다`,
  threateningViolence: `폭력을 위협하는 행위`,
  title: `표제`,
  timeConstraints: `시간 제약`,
  titleYourExtraService: `추가 서비스 제목`,
  theMaximumQuantityThatACustomerCanAdd: `고객이 추가할 수 있는 최대 수량`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `검토 기간은 ${v[0]}일로 제한됩니다`,
  toHelpTheCreatorCompleteYourOrder: `창작자가 주문을 만족스럽게 완료할 수 있도록 원하는 주제, 스타일, 캐릭터 특징 및 기타 중요한 사양을 포함한 자세한 설명을 제공하십시오`,
  today: `오늘`,
  toGetWorkRelatedNotifications: `작업 관련 알림을 받으려면`,
  total: `합계`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `이 데이터를 보려면 @${v[0]}의 차단을 해제해야 합니다.`,
  trademarkViolation: `상표권 침해`,
  typeYourTextHere: `여기에 텍스트를 입력하세요 ...`,
  unblock: `차단 해제`,
  unblockUser: (...v) => `@${v[0]} 차단 해제`,
  unfollow: `언팔로우`,
  unlimited: `무제한`,
  upload: `업로드`,
  uploadNew: `새로운 업로드`,
  uploadNewPost: `새 게시물 업로드`,
  uploadNewProduct: `새 제품 업로드`,
  username: `사용자 이름`,
  usernameAlreadyExists: `사용자 이름이 이미 존재합니다`,
  usernameAndXMoreFollowYou: (...v) =>
    `<b>${v[0]}</b>님과 ${v[1]}명이 팔로우합니다.`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `<b>${v[0]}</b>님과 ${v[1]}명이 작품을 좋아합니다.`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b>님이 팔로우합니다.`,
  usernameLikesYourArt: (...v) => `<b>${v[0]}</b>님이 작품을 좋아합니다.`,
  useThisEmailTo: `이 이메일을 사용하여 인증하고 알림을 받습니다.`,
  valueIsNotTheSame: `값이 같지 않습니다`,
  verificationCode: `확인 코드`,
  verifyCode: `코드 확인`,
  viewDetails: `자세히 보기`,
  viewReview: `리뷰 보기`,
  viewEveryNotificationOfAGroupSeparately: `그룹의 모든 알림을 개별적으로 볼 수 있습니다.`,
  visitOurDiscordChannelToGetMoreDetails: `저희의 디스코드 채널을 방문하시면 자세한 내용을 보실 수 있습니다`,
  weAreOnInstagram: `우리는 인스타그램에 있습니다`,
  weAreWorkingOnIt: `열심히 준비를 하고 있습니다.`,
  weDoNotDisplayNSFWContentYet: `NSFW 콘텐츠는 아직 표시하지 않습니다.`,
  weekly: `주간`,
  whenYouPurchaseSomethingItWillAppearHere: `무언가를 구매하면 여기에 표시됩니다.`,
  weHaveSentTooManyEmails: `너무 많은 이메일을 보냈습니다. 나중에 다시 시도하거나 고객 지원에 문의하십시오.`,
  welcomeToAnimeClub: `Anime.club에 오신 것을 환영합니다!`,
  weSentAnEmailTo: `다음 주소로 이메일을 보냈습니다.`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `새 확인 이메일을 보냈습니다. 코드를 입력하세요`,
  weAreExcitedToSeeYourProgressKeepItUp: `귀하의 진행 상황을 보게 되어 기쁩니다. 계속 유지하십시오!`,
  weSupportOnlyTheFollowingFileExtensions: `다음 파일 확장자 만 지원합니다:`,
  work: `작업`,
  weWouldLoveToHearFromYou: `귀하의 의견을 듣고 싶습니다`,
  workDescription: `작업 설명`,
  leaveAReview: `리뷰 남기기`,
  wrongEmailOrPassword: `잘못된 이메일 또는 암호`,
  yes: `예 `,
  yesterday: `어제`,
  youReceivedANewOrderFrom: (...v) =>
    `<b>${v[0]}</b>님으로부터 새 주문을 받았습니다`,
  youHaveSuccessfullyCreatedYourShop: `상점을 성공적으로 생성했습니다`,
  youAreAlreadyAuthenticated: `이미 인증되었습니다`,
  youCanAutoPublishToYourSocialMediaAccount: `소셜 미디어 계정에 자동으로 게시할 수 있습니다.`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `이메일로 받는 알림 유형을 수정할 수 있습니다.`,
  youCanRequestRemovalOfYourAccount: `계정 및 모든 데이터를 삭제 요청할 수 있습니다.`,
  youCanStillNavigateToThePreviouslyOpenedPages: `이전에 열었던 페이지로 아직은 이동할 수 있습니다.`,
  youDidNotSelectAnyChats: `채팅창을 선택하지 않았습니다`,
  youDidNotUpdateAnyValues: `값을 업데이트하지 않았습니다.`,
  youDoNotHaveAnyChats: `채팅창이 존재하지 않습니다`,
  youHaveNotSetAPassword: `비밀번호를 설정하지 않았습니다.`,
  youHaveNotSharedAnythingYet: `아직 아무것도 공유하지 않았습니다.`,
  youHaveReachedTheMaximumNumberOfFiles: `최대 파일 수에 도달했습니다.`,
  kindlyHoldOnForTheBuyersReview: `구매자의 주문 리뷰를 기다려주십시오.`,
  yourAccountIsVerifiedPleaseSignIn: `귀하의 계정이 확인되었습니다. 로그인 해주세요`,
  yourAccountWillBeRemoved: (...v) => `계정이 ${v[0]}에 삭제됩니다.`,
  youHaveNoPurchases: `구매 내역이 없습니다.`,
  couldYouPleaseProvideTheReasonForTheCancellation: `취소 이유를 제공해 주시겠습니까`,
  yourFeedbackWouldBeGreatlyAppreciated: `귀하의 피드백은 매우 감사하겠습니다`,
  yourArts: `귀하의 아트`,
  yourAvatar: `귀하의 아바타`,
  yourBlog: `귀하의블로그`,
  yourFansAreWaiting: `팬들이 기다리고 있습니다`,
  yourFeedIsEmpty: `피드가 비었습니다`,
  yourSessionHasExpiredPleaseSignInAgain: `세션이 만료되었습니다. 다시 로그인하십시오.`,
}
