export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `소개`,
  accept: `수락`,
  account: `(en) Account`,
  accountActivation: `계정 활성화`,
  accountAlreadyExists: `계정이 이미 있습니다.`,
  accountDoesNotExist: `계정이 없습니다.`,
  add: `추가`,
  addArt: `아트 추가`,
  addBlog: `블로그 추가`,
  additionalResources: `(en) Additional resources`,
  addMore: `(en) Add more`,
  addNewArt: `새로운 아트 추가`,
  addPreview: `미리보기 추가`,
  addSignInVia: `다음을 통해 로그인 추가`,
  advancedOptions: `(en) Advanced options`,
  all: `전체`,
  alreadySignedIn: `이미 로그인되었습니다`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (n) => `(en) Amount should not be less than $${n}`,
  animeArtByArtistsFromAllOverTheWorld: `전 세계 예술가들의 애니메이션 아트. 아트는 애니메이션과 관련된 것으로 큐레이팅됩니다. 아트 선택은 최고의 애니메이션 아트의 무한 목록입니다`,
  animeArtSubscribeToArtistsLikeAndCreate: `애니메이션 아트-아티스트 구독, 좋아요 및 컬렉션 만들기`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club-Google 애드 센스를 통해 아티스트에게 조회수에 해당한 지불을 하는 최초의 플랫폼입니다. 콘텐츠를 보고 아티스트를 지원하거나 조회수에서 수익을 창출하세요.`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club-애니메이션 콘텐츠보기, 게시 및 수익`,
  animeCommunity: `애니메이션 커뮤니티`,
  animeDotclubNeverAsksForYourPrivateInformation: `(en) Anime.club never asks for your private information`,
  animeSocialNetwork: `(en) Anime
Social Network`,
  announcements: `(en) Announcements`,
  apply: `적용`,
  appSettings: `(en) App settings`,
  appsVersionIs: `앱 버전은`,
  areYouSureYouWantTo: `당신은 정말로 원하십니까`,
  art: `아트`,
  artAssociatedWithAnime: `애니메이션과 관련된 아트`,
  artBy: `해당 아트`,
  artCannotBeChanged: `아트은 변경할 수 없습니다`,
  authenticationFailed: `인증 실패`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `뒤로`,
  blog: `블로그`,
  bookmarks: `북마크`,
  browseArt: `아트 검색`,
  cancel: `취소`,
  cannotStartWithChars: `s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"로 시작할 수 없습니다.`,
  change: `(en) Change`,
  changeArt: `아트 변경`,
  changeAvatar: `아바타 변경`,
  changeEmail: `(en) Change email`,
  changePassword: `비밀번호 변경`,
  chooseExistingChatOrStartANewOne: `기존 채팅창 선택 또는 새로운 채팅 시작`,
  city: `도시`,
  clearAll: `모두 지우기`,
  close: `닫기`,
  colorTheme: `(en) Color theme`,
  comingSoon: `곧 출시됩니다…`,
  community: `커뮤니티`,
  confirmAccount: `계정 확인`,
  confirmPassword: `비밀번호 확인`,
  connectWithUsOn: `(en) Connect with us on`,
  contactInformation: `(en) Contact information`,
  continue: `(en) Continue`,
  contractTitle: `(en) Contract Title`,
  copyLink: `링크 복사`,
  couldNotCreateANewRecord: `새 레코드를 만들 수 없습니다.`,
  country: `국가`,
  createANewAccountFailed: `새 계정을 만들지 못했습니다.`,
  createNewAccount: `새 계정 만들기`,
  currentPassword: `(en) Current password`,
  daily: `(en) Daily`,
  darkDefault: `(en) Dark default`,
  darkHighContrast: `(en) Dark high contrast`,
  dayTheme: `(en) Day theme`,
  delete: `삭제`,
  deleteArt: `아트 삭제`,
  deletePost: `포스트 삭제`,
  description: `서술`,
  details: `세부 사항`,
  didntReceiveEmail: `이메일을 받지 못하셨습니까?`,
  donations: `기부`,
  done: `완료`,
  dragAndDropOrSelectFiles: `(en) Drag & Drop or Select file(s)`,
  drawingContest: `그림 콘테스트`,
  dueDate: `(en) Due date`,
  earlier: `(en) Earlier`,
  earningFromArts: `아트에서 수익`,
  edit: `편집`,
  editPost: `게시물 편집`,
  editProfile: `프로필 편집`,
  editTranslations: `번역 편집`,
  email: `이메일`,
  emailAlreadyUsedByAnotherAccount: `다른 계정에서 이미 이용 중인 이메일`,
  emailNotifications: `(en) Email Notifications`,
  enterOrPasteALink: `링크 입력 또는 붙여넣기`,
  enterTheAddressAssociatedWithYourAccount: `(en) Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `(en) Enter your password`,
  error: `(en) Error`,
  errorPleaseContactCustomerSupport: `고객 지원에 문의하십시오 ...`,
  exitEditor: `편집기 종료`,
  extensions: `확장`,
  fileSizeIsTooBig: `파일 크기가 너무 큽니다`,
  filter: `필터`,
  filterBy: `필터링`,
  findUser: `사용자 검색`,
  follow: `팔로우하세요`,
  followers: `팔로워`,
  following: `팔로잉`,
  followMeOn: `저를 팔로우하세요`,
  follows: `(en) Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `기타 모든 문의 사항은 다음 주소로 문의하십시오:`,
  forgotPassword: `비밀번호를 잊으 셨나요`,
  forNewMasterpieces: `새로운 걸작을 위해`,
  fromAnimeDotClub: `(en) From anime.club`,
  getDetails: `세부 정보 보기`,
  guestView: `게스트보기`,
  hire: `(en) Hire`,
  homepage: `홈페이지`,
  howToContactYou: `(en) How to contact you`,
  howToFindYouOnOtherSocialNetworks: `(en) How to find you on other social networks`,
  iAgreeWith: `동의합니다`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Img 높이는 다음보다 크거나 같아야 합니다.`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Img 너비는 다음보다 크거나 같아야 합니다.`,
  introduction: `소개`,
  invalidCode: `유효하지 않은 코드`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `@ 뒤의 잘못된 부분`,
  invalidPartBeforeAt: `@ 앞의 잘못된 부분`,
  jobDetails: `(en) Job Details`,
  joinAnimeClubCommunity: `(en) Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `채팅 참여`,
  joinUsOnFacebook: `페이스 북에서 참여하세요`,
  language: `(en) Language`,
  languages: `언어`,
  letEveryoneKnowHowToDonateToYou: `(en) Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `(en) Let others know about you`,
  lightDefault: `(en) Light default`,
  lightHighContrast: `(en) Light high contrast`,
  likes: `좋아요`,
  linkCopiedToClipboard: `링크가 클립보드에 복사되었습니다`,
  livesIn: `입주`,
  location: `(en) Location`,
  logInOrSignUp: `(en) Log in or sign up`,
  logOut: `(en) Log out`,
  maximumNChars: (n) => `최대 ${n}개 문자`,
  maxSize: `최대 크기`,
  menu: `메뉴`,
  message: `메시지`,
  messages: `쪽지`,
  minHeight: `최소 높이`,
  minimumNChars: (n) => `최소 ${n}개 문자`,
  minWidth: `최소 너비`,
  monthly: `(en) Monthly`,
  moreFrom: (n) => `${n}에서 더 보기`,
  mustBeNChars: (n) => `${n}개 문자 여야 합니다.`,
  myPayments: `(en) My payments`,
  myProfile: `(en) My profile`,
  mySettings: `(en) My settings`,
  need1Lowercase: `소문자 1 개 필요`,
  need1Number: `숫자 1 개 필요`,
  need1Uppercase: `대문자 1 개 필요`,
  needAtLeast1CharacterFromN: (n) => `[${n}]에서 1개 문자 이상 필요`,
  needNCharacter: (n) => `${n}개 문자 필요`,
  newAccount: `새 계정`,
  newArt: `새로운 아트`,
  newArtworks: `(en) New artworks`,
  newBlog: `새 블로그`,
  newPassword: `새 비밀번호`,
  newsFeed: `뉴스 피드`,
  nextTimeYouAuthenticateYouCouldUseThe: `(en) Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `(en) Night theme`,
  no: `아니`,
  noAddedFavoriteArts: `즐겨찾기에 추가한 아트가 없음`,
  noInternetConnection: `인터넷에 연결되지 않음!`,
  none: `(en) None`,
  noNotifications: `(en) No notifications`,
  noResults: `(en) No results`,
  notifications: `알림`,
  nsfwContent18Plus: `NSFW 콘텐츠 (18 세 이상)`,
  online: `온라인`,
  onlyLatinLettersNumbersOrSpecialSymbols: `라틴 문자, 숫자, 특수 기호 만`,
  onlyNumbers: `숫자 만`,
  open: `(en) Open`,
  openGuestView: `게스트보기 열기`,
  openingSoon: `곧 오픈합니다!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `또는`,
  pageNotFound: `(en) Page not found`,
  password: `암호`,
  payments: `지불`,
  personal: `(en) Personal`,
  pleaseCheckYour: (n) => `(en) Please check your %VALUE_1`,
  pleaseDoNotShareYourPrivateInformationToOthers: `(en) Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `하나의 이미지 만 삭제하십시오`,
  pleaseEnterAtLeastNChars: (n) => `${n}자 이상 입력하세요.`,
  pleaseFillOutYourDetails: `세부 정보를 입력하십시오`,
  pleaseSignInToYourAccount: `귀하의 계정에 로그인하십시오`,
  pleaseTryAgainOrClick: (n) => `다시 시도하거나 ${n}을 클릭하세요`,
  pleaseVerifyYourAccount: `계정을 확인하십시오`,
  pressHereTo: `여기를 눌러주세요`,
  privacyPolicy: `트위터 개인정보 처리방침`,
  privateInformation: `(en) Private information`,
  profile: `프로필`,
  promotions: `(en) Promotions`,
  publicInformation: `(en) Public information`,
  publishOn: (n) => `(en) Publish on ${n}`,
  rankings: `(en) Rankings`,
  report: `(en) Report`,
  save: `저장`,
  saveAvatar: `아바타 저장`,
  saveChanges: `변경 사항 저장`,
  selectAnime: `애니메이션 선택 `,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `(en) Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `아바타 선택`,
  selectCharacters: `문자 선택`,
  selectFile: `파일 선택`,
  selectTheme: `(en) Select theme`,
  selectThumbnail: `썸네일 선택`,
  sendEmail: `이메일 보내기`,
  settings: `설정`,
  share: `(en) Share`,
  shareYourArtWithTheWorld: `(en) Share your art with the world`,
  shareYourStory: `당신의 이야기를 공유하세요!`,
  shop: `상점`,
  showLess: `간략히 보기`,
  showMore: `더 보기`,
  signIn: `로그인`,
  singleTheme: `(en) Single theme`,
  size: `(en) Size`,
  skip: `건너 뛰기`,
  socialMedia: `소셜 미디어`,
  spaceCharacterIsNotAllowed: `공백 문자는 허용되지 않습니다.`,
  subscribeToTalentsToKeepUpWithTheirProgress: `진행 상황을 확인하려면 크리에이터를 구독하세요`,
  successChangedPasswordPleaseSignIn: `성공! 비밀번호를 변경했습니다. 로그인 해주세요`,
  successCreatedRecord: `성공! 기록을 만들었습니다!`,
  successUpdatedRecord: `성공!기록이 업데이트 되였습니다!`,
  supportMeOn: `N에서 저를 지원해주세요`,
  syncWithSystem: `(en) Sync with system`,
  tellUsAboutYourself: `자신에 대한 정보를 알려주십시오`,
  termsAndConditions: `계약 조건`,
  termsOfUse: `이용 약관`,
  theLinkIsBrokenOrPageHasBeenRemoved: `(en) The link is broken or page has been removed`,
  themeMode: `(en) Theme mode`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `표제`,
  today: `(en) Today`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `여기에 텍스트를 입력하세요 ...`,
  upload: `(en) Upload`,
  uploadAnotherArt: `다른 아트 업로드`,
  uploadAnotherAvatar: `다른 아바타 업로드`,
  uploadArtNow: `지금 아트를 업로드하세요!`,
  uploadNew: `새로운 업로드`,
  uploadNewArt: `새로운 아트 업로드`,
  uploadNewPost: `새 게시물 업로드`,
  username: `사용자 이름`,
  usernameAlreadyExists: `사용자 이름이 이미 존재합니다`,
  usernameAndXMoreFollowYou: (n) =>
    `(en) <b>${n}</b> and undefined more follow you`,
  usernameAndXMoreLikeYourArtwork: (n) =>
    `(en) <b>${n}</b> and undefined more like your artwork`,
  usernameFollowsYou: (n) => `(en) <b>${n}</b> follows you`,
  usernameLikesYourArt: (n) => `(en) <b>${n}</b> likes your art`,
  useThisEmailTo: `(en) Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `값이 같지 않습니다`,
  verificationCode: `확인 코드`,
  verifyCode: `코드 확인`,
  visitOurDiscordChannelToGetMoreDetails: `저희의 디스코드 채널을 방문하시면 자세한 내용을 보실 수 있습니다`,
  weAreOnInstagram: `우리는 인스타그램에 있습니다`,
  weAreWorkingOnIt: `열심히 준비를 하고 있습니다.`,
  weDoNotDisplayNSFWContentYet: `NSFW 콘텐츠는 아직 표시하지 않습니다.`,
  weekly: `(en) Weekly`,
  weHaveSentTooManyEmails: `(en) We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Anime.club에 오신 것을 환영합니다!`,
  weSentAnEmailTo: `다음 주소로 이메일을 보냈습니다.`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `새 확인 이메일을 보냈습니다. 코드를 입력하세요`,
  weSupportOnlyTheFollowingFileExtensions: `다음 파일 확장자 만 지원합니다:`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `잘못된 이메일 또는 암호`,
  yes: `예 `,
  yesterday: `(en) Yesterday`,
  youAreAlreadyAuthenticated: `이미 인증되었습니다`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `(en) You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `이전에 열었던 페이지로 아직은 이동할 수 있습니다.`,
  youDidNotSelectAnyChats: `채팅창을 선택하지 않았습니다`,
  youDidNotUpdateAnyValues: `값을 업데이트하지 않았습니다.`,
  youDoNotHaveAnyChats: `채팅창이 존재하지 않습니다`,
  youHaveNotSavedAnyChanges: `변경 사항을 저장하지 않았습니다.`,
  youHaveNotSetAPassword: `(en) You have not set a password`,
  yourAccountIsVerifiedPleaseSignIn: `귀하의 계정이 확인되었습니다. 로그인 해주세요`,
  yourArts: `귀하의 아트`,
  yourAvatar: `귀하의 아바타`,
  yourBlog: `귀하의블로그`,
  yourFansAreWaiting: `팬들이 기다리고 있습니다`,
  yourFeedIsEmpty: `피드가 비었습니다`,
  yourSessionHasExpiredPleaseSignInAgain: `세션이 만료되었습니다. 다시 로그인하십시오.`,
}
