export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  _hyphen: `- `,
  about: `Sobre`,
  accept: `Aceitar`,
  acceptOrder: `Aceitar pedido`,
  acceptTheOrder: `Aceitar pedido`,
  accountManagment: `Gerenciamento de conta`,
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `O Anime.club usa ${v[0]} para que você receba seus pagamentos rapidamente e mantenha suas informações pessoais e de pagamento seguras`,
  account: `Conta`,
  accountDeleted: `Conta deletada`,
  clickTheButtonBelowToOpenYourStripeDashboard: `Clique no botão abaixo para abrir seu painel do Stripe e consultar os dados da sua conta`,
  animeShopBuyAndSellProducts: `Loja de anime - compre e venda produtos`,
  visitStripeDashboard: `Acessar painel do Stripe`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `Imagens geradas por IA e filtros de rede neural são proibidos`,
  accountActivation: `Ativação de conta`,
  accountAlreadyExists: `Conta já existe`,
  accountDoesNotExist: `Conta não existe`,
  accountRemoval: `Remoção de conta`,
  files: `Arquivos`,
  prohibitedTransaction: `Transação proibida`,
  add: `Adicionar`,
  addArt: `Adicionar arte`,
  addBlog: `Adicionar blog`,
  additionalResources: `Recursos adicionais`,
  addMoreProductsToYourShop: `Adicione mais produtos à sua loja`,
  addMore: `Adicionar mais`,
  addNewArt: `Adicionar nova arte`,
  addSignInVia: `Adicionar iniciar secção via`,
  addToCart: `Adicionar ao carrinho`,
  advancedOptions: `Opções avançadas`,
  uploadTheFilesYourBuyerWillGet: `Envie os arquivos que o <b>comprador receberá</b>`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `Certifique-se de que tudo esteja pronto — não será possível editar após a publicação`,
  filesForTheBuyer: `Arquivos para o comprador`,
  filesForPreview: `Arquivos para pré-visualização`,
  all: `Tudo`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `Todos os arquivos enviados aqui estarão disponíveis para o comprador`,
  alreadySignedIn: `Secção já iniciada`,
  amount: `Quantidade`,
  amountShouldNotBeLessThan: (...v) => `A quantidade não deve ser inferior a ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Arte de anime de artistas de todo o mundo. A arte é selecionada para ser relacionada ao anime. A seleção de arte é uma lista infinita das melhores artes de anime`,
  animeArtSubscribeToArtistsLikeAndCreate: `Arte de anime - inscreva-se em artistas, curta e crie coleções`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - a primeira plataforma a oferecer aos artistas pagamentos a partir de visualizações via Google AdSense. Apoie os artistas visualizando seu conteúdo ou comece a ganhar com as visualizações`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - veja, poste e ganhe com conteúdo de anime`,
  animeCommunity: `Comunidade de anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club nunca pede suas informações privadas`,
  animeSocialNetwork: `Rede social de anime`,
  announcements: `Anúncios`,
  appearance: `Aparência`,
  apply: `Aplicar`,
  appSettings: `Configurações do aplicativo`,
  appsVersionIs: `A versão do aplicativo é`,
  areYouSureYouWantTo: `Você tem certeza que quer`,
  art: `Arte`,
  artAssociatedWithAnime: `Arte associada a anime`,
  artBy: (...v) => `Arte por ${v[0]}`,
  artCannotBeChanged: `Arte não pode ser mudada`,
  artworksAvailableToView: (...v) => `${v[0]} obras de arte disponíveis para visualização`,
  authenticationFailed: `Autenticação falhou`,
  system: `Sistema`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `A publicação automática no Instagram está disponível apenas para contas comerciais do Instagram`,
  attentionYourOrderHasBeenDisputed: `Atenção! Seu pedido foi contestado. Por favor, verifique os detalhes`,
  needsYourReview: `Aguardando sua avaliação`,
  awaitingSellersResponse: `Aguardando resposta do vendedor`,
  back: `Costas`,
  basePrice: `Preço base`,
  bigAppreciationToTheSellerForTheHardWork: `Grande agradecimento ao vendedor pelo trabalho árduo`,
  block: `Bloquear`,
  buyerReviewedTheOrder: `O comprador avaliou o pedido`,
  buyerHasNotLeftAReviewYet: `O comprador ainda não deixou uma avaliação`,
  feedbackReceived: `Feedback recebido!`,
  blockUser: (...v) => `Bloquear @${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `Antes de aceitar, revise cuidadosamente o pedido do comprador`,
  blog: `Blog`,
  bookmarks: `Itens salvos`,
  browseArt: `Navegue pela arte`,
  browseShop: `Navegar na loja`,
  buyer: `Comprador`,
  buyersRequest: `Pedido do comprador`,
  cancel: `cancelar`,
  canceled: `Cancelado`,
  comments: `Comentários`,
  cancelOrder: `Cancelar pedido`,
  cannotStartWithChars: `Não pode começar com s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Alterar`,
  checkOutMyShop: `Veja minha loja`,
  checkOrderStatus: `Verificar status do pedido`,
  changeArt: `Mudar arte`,
  changeAvatar: `Mudar avatar`,
  changeEmail: `Alterar e-mail`,
  changePassword: `Mudar senha`,
  chooseExistingChatOrStartANewOne: `Escolha o bate-papo existente ou inicie um novo`,
  city: `Cidade`,
  clearAll: `Limpar`,
  awaitingClientReview: `Aguardando avaliação do cliente`,
  close: `Fechar`,
  color: `Cor`,
  colorTheme: `Tema de cor`,
  comingSoon: `Em breve...`,
  commercialUseAllowed: `Uso comercial permitido`,
  commercialUseAllowsBuyersToUseYourProduct: `O uso comercial permite que compradores usem seu produto para fins comerciais, como vender ou promover serviços`,
  community: `Comunidade`,
  completed: `Concluído`,
  confirmAccount: `Confirmar a conta`,
  confirmOrder: `Confirmar pedido`,
  confirmPassword: `Confirmar a senha`,
  connectWithUsOn: `Conecte-se conosco em`,
  contactInformation: `Informações de contato`,
  contactSeller: `Contatar vendedor`,
  contactSupport: `Contatar suporte`,
  contactUs: `Contate-nos`,
  continue: `Continuar`,
  contractTitle: `Título do contrato`,
  copy: `Copiar`,
  congratulations: `Parabéns!`,
  thankYouForYourPurchase: `Obrigado pela sua compra!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `Parabéns por concluir seu pedido com sucesso!`,
  copyrightViolation: `Violação de direitos autorais`,
  couldNotCreateANewRecord: `Não foi possível criar um novo registro`,
  country: `País`,
  cover: `Capa`,
  createANewAccountFailed: `Falha ao criar uma nova conta`,
  createExtrasForYourProduct: `Criar extras para o seu produto`,
  createNewAccount: `Criar nova conta`,
  createAShopWithStripe: `Crie uma loja com Stripe`,
  createdBy: `Criado por`,
  currentPassword: `Senha atual`,
  daily: `Diariamente`,
  dark: `Escuro`,
  delete: `Excluir`,
  deleteShop: `Excluir loja`,
  deleteAccount: `Excluir conta`,
  deleteArt: `Apagar art`,
  decline: `Recusar`,
  deletePost: `Apagar publicação`,
  deleteProduct: `Excluir produto`,
  download: `Baixar`,
  downloadThemBelow: `Baixe-os abaixo`,
  deliveryTime: `Tempo de entrega`,
  describeTheDetailsOfYourExtra: `Descreva os detalhes do seu extra`,
  description: `Descrição`,
  details: `Detalhes`,
  didntReceiveEmail: `Não recebeu correio electrónico?`,
  displayName: `Nome de exibição`,
  disputed: `Contestado`,
  donations: `Doações`,
  documentation: `Documentação`,
  done: `Pronto`,
  dragAndDropOrSelectFiles: `Arraste e solte ou selecione arquivo(s)`,
  drawingContest: `Concurso de desenho`,
  dueDate: `Data de vencimento`,
  earlier: `Anterior`,
  earningFromArts: `Ganhando com as artes`,
  edit: `Editar`,
  editPost: `Editar post`,
  editProfile: `Editar perfil`,
  editTranslations: `Editar traduções`,
  email: `Correio electrónico`,
  emailAlreadyUsedByAnotherAccount: `Email já usado por outra conta`,
  emailNotifications: `Notificações por e-mail`,
  enterOrPasteALink: `Insira ou cole um link`,
  enjoyYourPurchase: `Aproveite sua compra! 😊`,
  enterTheAddressAssociatedWithYourAccount: `Digite o endereço associado à sua conta e enviaremos um link para redefinir sua senha`,
  enterYourPassword: `Digite sua senha`,
  error: `Erro`,
  errorPleaseContactCustomerSupport: `Erro! Entre em contato com o suporte ao cliente...`,
  exitWithoutSaving: `Sair sem salvar`,
  extensions: `Extensões`,
  extras: `Extras`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `Extras são complementos opcionais para aprimorar seu produto`,
  fileSizeIsTooBig: `O tamanho do arquivo é muito grande`,
  fileSizeIsTooSmall: `O tamanho do arquivo é muito pequeno`,
  filter: `Filtro`,
  filterBy: `Filtrar por`,
  findUser: `Encontrar usuário`,
  finishSettingUpYourShop: `Conclua a configuração da sua loja`,
  follow: `Seguir`,
  followers: `Seguidores`,
  following: `Seguindo`,
  followMeOn: `Siga-me`,
  follows: `Seguidores`,
  forAllOtherInquiriesPleaseContactUsAt: `Para todas as outras perguntas, entre em contato conosco em:`,
  forgotPassword: `Esqueceu a senha`,
  fromAnimeDotClub: `Do anime.club`,
  getDetails: `Obter detalhes`,
  getStarted: `Comece agora`,
  guestView: `Vista de convidado`,
  greatNewsYourOrderIsNowInProgress: `Ótima notícia! Seu pedido está em andamento`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `Ótima notícia! ${v[0]} comprou seu item. É hora de comemorar!`,
  harassment: `Assédio`,
  haveAnyQuestions: `Tem alguma pergunta?`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> cancelou o pedido`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> enviou o trabalho`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]} não adicionou uma descrição para "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} ainda não compartilhou nenhum detalhe público`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `@${v[0]} ainda não colocou nenhum produto à venda`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `@${v[0]} ainda não adicionou nada ao portfólio`,
  hate: `Ódio`,
  hereAreAFewWaysToGetThingsRolling: `Aqui estão algumas maneiras de começar`,
  hire: `Contratar`,
  hideListing: `Ocultar anúncio`,
  uploadUpToNumberFiles: (...v) => `Envie até <b>${v[0]}</b> arquivos`,
  supportedFormats: `Formatos compatíveis:`,
  minimumDimensions: (...v) => `Tamanho mínimo: ${v[0]}×${v[1]} pixels`,
  maximumFileSize: (...v) => `Tamanho máximo: <b>${v[0]}</b> por arquivo`,
  thisListingWontBeVisibleToBuyersAnymore: `Este anúncio não ficará mais visível para os compradores — mas você poderá exibi-lo novamente quando quiser`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `Os compradores poderão ver este anúncio. Você poderá ocultá-lo novamente quando quiser`,
  listingHiddenFromBuyers: `Anúncio oculto dos compradores`,
  listingIsNowVisibleToBuyers: `O anúncio agora está visível para os compradores`,
  showListing: `Exibir anúncio`,
  homepage: `Página inicial`,
  howToContactYou: `Como entrar em contato com você`,
  howToFindYouOnOtherSocialNetworks: `Como encontrar você em outras redes sociais`,
  iAgreeWith: `Eu concordo com`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Se não houver resposta até ${v[0]}, o pedido será marcado como concluído automaticamente`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `Se não houver resposta até ${v[0]}, o pedido será cancelado automaticamente`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `Se não houver resposta até ${v[0]}, você receberá automaticamente um reembolso integral`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `Se você perder o prazo, o comprador poderá cancelar o pedido e receber um reembolso integral, e as taxas do Stripe relacionadas serão descontadas do seu pagamento.`,
  id: `ID`,
  addAComment: `Adicionar comentário`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `A altura do Img deve ser maior ou igual a`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `A largura do Img deve ser maior ou igual a`,
  impersonation: `Impersonificação`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `Estas regras foram definidas pelo vendedor e se aplicam somente a este item`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `Se tiver dúvidas ou preocupações, entre em contato diretamente com o vendedor`,
  platformPoliciesMayStillApply: `As políticas da plataforma ainda podem ser aplicáveis`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Inclua palavras-chave que compradores provavelmente usariam para procurar um produto como o seu`,
  increaseContrast: `Aumentar contraste`,
  inProgress: `Em progresso`,
  introduction: `Introdução`,
  includes: `Inclui`,
  invalidCode: `Código inválido`,
  invalidCurrentPassword: `Senha atual inválida`,
  invalidDate: `Data inválida`,
  invalidPartAfterAt: `Parte inválida após @`,
  invalidPartBeforeAt: `Parte inválida antes de @`,
  jobDetails: `Detalhes do trabalho`,
  joinAnimeClubCommunity: `Junte-se à comunidade Anime.club com milhares de criadores ativos e arte legal de anime todos os dias`,
  joinChat: `Entrar no chat`,
  joinUsOnFacebook: `Junte-se a nós no Facebook`,
  language: `Idioma`,
  lackOfInformation: `Falta de informação`,
  languages: `Línguas`,
  letEveryoneKnowHowToDonateToYou: `Deixe todos saberem como doar para você`,
  letOthersKnowAboutYou: `Deixe os outros saberem sobre você`,
  letsUploadYourFirstProduct: `Vamos carregar seu primeiro produto`,
  letUsKnowWhatsHappening: `Deixe-nos saber o que está acontecendo e nós investigaremos`,
  light: `Claro`,
  likes: `Gostos`,
  limit: `Limite`,
  copiedToClipboard: `Copiado para a área de transferência`,
  livesIn: `Vivendo em`,
  loading: `Carregando`,
  location: `Localização`,
  logInOrSignUp: `Entrar ou cadastrar-se`,
  logOut: `Sair`,
  maximumNChars: (...v) => `Máximo ${v[0]} caracteres`,
  maximumNumberOfDaysToCompleteTheOrder: `Número máximo de dias para concluir o pedido`,
  maximumQuantity: `Quantidade máxima`,
  maxSize: `Tamanho máximo`,
  menu: `Cardápio`,
  uploadedFilesLocked: `Você enviou estes arquivos ao criar a publicação. Agora eles estão bloqueados, mas continuam visíveis abaixo`,
  message: `Mensagem`,
  messages: `Mensagens`,
  minHeight: `Altura mínima`,
  minimumNChars: (...v) => `Mínimo ${v[0]} caracteres`,
  minorAbuseOrSexualization: `Abuso ou sexualização de menores`,
  makeSureToIncludeClearInstructions: `Inclua instruções claras sobre como cada referência deve ser usada`,
  makeSureYouFullyUnderstandTheRequirements: `Certifique-se de entender totalmente os requisitos e de poder concluir o pedido até o prazo`,
  makeSureYourProductsArePricedCompetitively: `Certifique-se de que seus produtos estejam com preços competitivos`,
  minWidth: `Largura mínima`,
  monthly: `Mensal`,
  moreFrom: (...v) => `Mais de ${v[0]}`,
  mustBeNChars: (...v) => `Deve ter ${v[0]} caracteres`,
  myPayments: `Meus pagamentos`,
  myProfile: `Meu perfil`,
  mySettings: `Minhas configurações`,
  need1Lowercase: `Precisa de 1 minúsculas`,
  need1Number: `Precisa de 1 número`,
  need1Uppercase: `Precisa de 1 maiúsculo`,
  needAtLeast1CharacterFromN: (...v) => `Precisa de pelo menos 1 caractere de [${v[0]}]`,
  needNCharacter: (...v) => `Deve ter ${v[0]} personagem`,
  new: `Novo`,
  newAccount: `Nova conta`,
  newArt: `Nova arte`,
  createPersonalizedWorkTailoredToEachRequest: `Crie trabalhos personalizados para cada pedido`,
  offerDigitalProducts: `Ofereça produtos digitais que os compradores podem acessar imediatamente`,
  instantDownload: `Download imediato`,
  customWork: `Trabalho personalizado`,
  newArtworks: `Novas obras de arte`,
  newBlog: `Novo blog`,
  newOrder: `Novo pedido`,
  newPassword: `Nova senha`,
  newProduct: `Novo produto`,
  allListings: `Todos os anúncios`,
  newCommission: `Nova encomenda`,
  newsFeed: `Feed de notícias`,
  next: `Próximo`,
  nextTimeYouAuthenticateYouCouldUseThe: `Na próxima vez que você se autenticar, poderá usar a conta conectada, em vez do login e senha`,
  no: `não`,
  noOrders: `Nenhum pedido`,
  noInternetConnection: `Sem conexão com a Internet!`,
  nonConsensualIntimateContent: `Conteúdo íntimo não consensual`,
  none: `Nenhum`,
  noNotifications: `Sem notificações`,
  noResults: `Nenhum resultado`,
  noReviewsJustYet: `Ainda sem avaliações`,
  noCommentsJustYet: `Ainda sem comentários`,
  beTheFirstToShareYourThoughts: `Seja o primeiro a compartilhar sua opinião`,
  notifications: `Notificações`,
  noActiveOrdersToShow: `Não há pedidos ativos para mostrar`,
  notAcceptingOrders: `Não aceitando pedidos`,
  noSalesYetNoWorries: `Ainda sem vendas? Não se preocupe, você está apenas começando`,
  nsfwContent18Plus: `Conteúdo NSFW (18+)`,
  NSFWIndicatesAdultContent: `18+ NSFW indica conteúdo adulto. Marque este campo apenas se seu produto for para adultos`,
  numberOfAdjustmentsAClientCouldRequest: `Número de ajustes que um cliente pode solicitar`,
  online: `Online`,
  onlyLatinLettersNumbersHyphen: `Somente letras latinas, números, hífen, sublinhado e ponto`,
  onlyNumbers: `Apenas números`,
  onlyYouCanSeeWhatYouveSaved: `Apenas você pode ver o que salvou`,
  open: `Aberto`,
  openDispute: `Abrir disputa`,
  openGuestView: `Abrir visualização de convidado`,
  openingSoon: `Aberto em breve!`,
  openToWork: `Aberto para trabalhar`,
  optional: `Opcional`,
  requestDetails: `Detalhes do pedido`,
  or: `OU`,
  order: `Pedido`,
  outOfStock: `Fora de estoque`,
  ordered: (...v) => `Pedido ${v[0]}`,
  orderAgain: `Fazer pedido novamente`,
  orderDetails: `Detalhes do pedido`,
  orderConfirmed: `Pedido confirmado`,
  orderCompleted: `Pedido concluído 🎉`,
  orderStatus: `Status do pedido`,
  orderOptions: `Opções de pedido`,
  otherReason: `Outro motivo`,
  pageNotFound: `Página não encontrada`,
  buyNow: `Comprar agora`,
  password: `Senha`,
  payments: `Pagamentos`,
  attachedFiles: `Arquivos anexados`,
  numFilesIncluded: (...v) => `<b>${v[0]}</b> arquivo(s) incluído(s)`,
  personal: `Pessoal`,
  personalCircumstances: `Circunstâncias pessoais`,
  tellTheBuyersWhatTheyWillGet: `Informe exatamente o que os compradores receberão. Por exemplo, o número de ilustrações, os formatos dos arquivos ou as especificações da tela, como resolução e DPI`,
  beSpecificAboutTheContent: `Descreva o conteúdo em detalhes (por exemplo, número de arquivos, formatos e resolução da tela)`,
  mentionYourDeliveryTimeInDays: `Informe seu <b>prazo de entrega</b> (em dias)`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `Informe aos compradores se você oferece <b>revisões</b> e quantas`,
  listAnyContentOrRequestsYouDontAccept: `Liste os conteúdos ou pedidos que você <b>não aceita</b> (por exemplo, material NSFW, político, religioso ou ofensivo)`,
  offerOptionalExtras: `Ofereça extras opcionais, como <b>entrega expressa</b>, <b>personagem adicional</b> ou <b>cenário detalhado</b>`,
  extrasHelpBoostIncome: `Os extras permitem que os compradores personalizem o pedido e podem aumentar sua renda`,
  pleaseAllowPopups: `Permita a abertura de pop-ups`,
  pleaseCheckYour: (...v) => `Por favor, verifique o seu ${v[0]}`,
  pleaseRateYourOrder: `Por favor, avalie seu pedido`,
  feelFreeToShareReferenceImagesAndMaterials: `Sinta-se à vontade para compartilhar imagens e materiais de referência para ajudar o artista a criar sua peça`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Por favor, não compartilhe suas informações privadas com outras pessoas`,
  pleaseEnterANumberBetweenXandX: (...v) => `Por favor, insira um número entre ${v[0]} e ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `Por favor, insira pelo menos ${v[0]} caracteres`,
  pleaseFillOutYourDetails: `Por favor, preencha seus dados`,
  pleaseFixTheErrorsBeforeSubmitting: `Corrija os erros antes de enviar`,
  pleaseSignInToYourAccount: `Por favor entre em sua conta`,
  platform: `Plataforma`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `Você poderá baixar seus arquivos imediatamente após a compra — sem precisar esperar!`,
  orderAOneOfAKindCustomPieceCraftedToMatchYourVision: `Encomende uma peça personalizada e exclusiva, criada de acordo com sua visão`,
  youAreCoveredIfThereIsAProblem: `Sua compra está protegida! Se houver algum problema e a contestação for válida, você receberá 100% do seu dinheiro de volta`,
  thisIsACustomOrderNotAReadyMadeProduct: `Este é um pedido personalizado, não um produto pronto. O vendedor começará a trabalhar nele após o pedido`,
  pleaseStartTyping: `Por favor, comece a digitar`,
  pleaseTakeAMomentToReviewTheOrder: `Reserve um momento para revisar o pedido`,
  pleaseReviewTheBuyersReferenceFiles: `Revise os arquivos de referência do comprador e siga conforme especificado na descrição do pedido`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `Revise os detalhes cuidadosamente antes de prosseguir`,
  pleaseRespondToTheOrderBy: (...v) => `Responda ao pedido até ${v[0]}`,
  pleaseTryAgainOrClick: (...v) => `Por favor, tente de novo e clique em ${v[0]}`,
  whatWouldYouLikeToCreate: `O que você gostaria de criar?`,
  shareYourArt: `Compartilhe sua arte`,
  ifYourArtIsNsfwCheckThisToAvoidAWarningOrBan: `Se sua arte for NSFW, marque esta opção. Caso contrário, você poderá receber uma advertência que pode resultar em banimento.`,
  takeCustomRequests: `Aceite pedidos personalizados`,
  sellDownloadableContent: `Venda conteúdo para download`,
  digitalDownloadsExamples: `Pincéis, recursos, tutoriais e muito mais`,
  artGallery: `Galeria de arte`,
  commission: `Encomenda`,
  commissions: `Encomendas`,
  digitalDownloads: `Downloads digitais`,
  pleaseVerifyYourAccount: `Por favor, verifique sua conta`,
  pressHereTo: `Pressione aqui para`,
  price: `Preço`,
  payouts: `Pagamentos`,
  privacyPolicy: `Política de Privacidade`,
  privateInformation: `Informação privada`,
  proceedToCheckout: `Prosseguir para o checkout`,
  product: `Produto`,
  itemReviews: `Avaliações de itens`,
  portfolio: `Portfólio`,
  profile: `Perfil`,
  promotions: `Promoções`,
  publicInformation: `Informação pública`,
  publishOn: (...v) => `Publicar em ${v[0]}`,
  purchases: `Compras`,
  rankings: `Classificações`,
  reorderFiles: `Reordenar arquivos`,
  report: `Denunciar`,
  review: `Avaliação`,
  rules: `Regras`,
  reviews: `Avaliações`,
  numOfReviews: (...v) => `Avaliações: ${v[0]} `,
  reviewed: `Avaliado`,
  reviewTitle: `Título da avaliação`,
  reason: `Motivo`,
  revisions: `Revisões`,
  includesXRevisionS: (...v) => `Inclui ${v[0]} revisão(ões)`,
  sales: `Vendas`,
  save: `Salvar`,
  saveAvatar: `Salvar avatar`,
  saveChanges: `Salvar alterações`,
  selectAnime: `Selecionar anime`,
  selectAppearanceContrastAndColorTheme: `Selecione a aparência, o contraste e o tema de cores`,
  selectAvatar: `Selecionar avatar`,
  selectCharacters: `Selecionar personagem(s)`,
  seller: `Vendedor`,
  selectFile: `Selecionar arquivo`,
  selectThumbnail: `Selecionar miniatura`,
  selfHarmOrSuicide: `Auto-mutilação ou suicídio`,
  sendEmail: `Enviar email`,
  settings: `Configurações`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Configurar uma loja é gratuito e leva apenas alguns minutos`,
  share: `Compartilhar`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `Compartilhe suas regras e os tipos de pedidos que você não aceita`,
  shareYourShopOnSocialMedia: `Compartilhe sua loja nas redes sociais`,
  shareYourFavoritePiecesOn: (...v) => `Compartilhe suas peças favoritas em ${v[0]}`,
  shareYourArtWithTheWorld: `Compartilhe sua arte com o mundo`,
  shareYourStory: `Compartilhe sua história!`,
  sharingPersonalInformation: `Compartilhamento de informações pessoais`,
  shop: `Loja`,
  shopReviews: `Avaliações da loja`,
  shopOrders: `Pedidos da loja`,
  showLess: `Mostrar menos`,
  showMore: `Mostrar mais`,
  show: `Mostrar`,
  hide: `Ocultar`,
  signIn: `Fazer login`,
  size: `Tamanho`,
  skip: `Pular`,
  socialMedia: `Mídia social`,
  spaceCharacterIsNotAllowed: `O caractere de espaço não é permitido`,
  spam: `Spam`,
  yourFavoritesWillShowUpHereAddSome: `Seus favoritos aparecerão aqui. Adicione alguns!`,
  submitAReport: `Enviar um relatório`,
  submitWork: `Enviar trabalho`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Subscreva-se ao talents para acompanhar o seu progresso`,
  successChangedPasswordPleaseSignIn: `Sucesso! Senha alterada. Por favor, inscreva-se`,
  successCreatedRecord: `Sucesso! Registro criado!`,
  changesSaved: `Alterações salvas!`,
  successfullyDownloaded: `Baixado com sucesso!`,
  successfullyUploaded: `Enviado com sucesso!`,
  setUpStripeAccountToGetPaidWithAnimeClub: `Configure uma conta do Stripe para receber pagamentos pelo Anime.club`,
  supportMeOn: `Apoie-me em`,
  tellUsAboutYourself: `Conte-nos sobre você`,
  sellerTermsOfService: `Termos de Serviço do Vendedor`,
  termsAndConditions: `Termos e condições`,
  termsOfUse: `Termos de uso`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `Descreva o que está incluído e o que o comprador pode esperar após a compra`,
  thankYouForReport: `Obrigado por ajudar a manter uma comunidade online segura e respeitosa`,
  thankYouForYourReview: `Obrigado pela sua avaliação!`,
  theLinkIsBrokenOrPageHasBeenRemoved: `O link está quebrado ou a página foi removida`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `O motivo informado para o cancelamento deste pedido será compartilhado com o comprador`,
  thisIsThePriceYouPropose: `Este é o preço que você propõe`,
  thisFieldIsOptional: `Este campo é opcional`,
  thisCannotBeUndone: `Isso não pode ser desfeito`,
  ensureYouveUploadedTheFinalVersion: `Certifique-se de ter enviado a versão final antes de submeter`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `Se quiser, adicione uma descrição para contar mais sobre sua criação`,
  pleaseProvideATitleForYourArtwork: `Dê um título à sua obra de arte`,
  threateningViolence: `Ameaçando violência`,
  title: `Título`,
  timeConstraints: `Restrições de tempo`,
  titleYourExtraService: `Dê um título ao seu serviço extra`,
  theMaximumQuantityThatACustomerCanAdd: `A quantidade máxima que um cliente pode adicionar`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `O período de revisão é limitado a ${v[0]} dias`,
  toHelpTheCreatorCompleteYourOrder: `Para ajudar o criador a concluir seu pedido de forma satisfatória, forneça uma descrição detalhada do que você deseja. Inclua o tema desejado, estilo e características do personagem, bem como quaisquer outras especificações importantes`,
  today: `Hoje`,
  toGetWorkRelatedNotifications: `Para receber notificações relacionadas ao trabalho`,
  total: `Total`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Para visualizar esses dados, você precisa desbloquear @${v[0]}`,
  trademarkViolation: `Violação de marca registrada`,
  typeYourTextHere: `Digite seu texto aqui...`,
  theSellerHasUploadedTheseFilesForYou: `O vendedor enviou estes arquivos para você`,
  unblock: `Desbloquear`,
  unblockUser: (...v) => `Desbloquear @${v[0]}`,
  unfollow: `Deixar de seguir`,
  unlimited: `Ilimitado`,
  upload: `Enviar`,
  uploadNew: `Fazer upload de novo`,
  uploadNewPost: `Fazer upload de nova mensagem`,
  uploadNewProduct: `Enviar novo produto`,
  username: `Nome de Usuário`,
  pleaseUploadOnlyFinishedWorkHere: `Envie apenas trabalhos finalizados aqui`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `Todos os arquivos relacionados a WIP devem ser enviados em mensagens`,
  usernameAlreadyExists: `Nome de usuário já existe`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> e mais ${v[1]} seguem você`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b> e mais ${v[1]} reagiram`,
  usernameStartedFollowingYou: (...v) => `<b>${v[0]}</b> começou a seguir você`,
  usernameLeftAReaction: (...v) => `<b>${v[0]}</b> reagiu`,
  usernameCommentedOnYourWork: (...v) => `<b>${v[0]}</b> comentou no seu trabalho`,
  usernameAndXMoreCommented: (...v) => `<b>${v[0]}</b> e mais ${v[1]} comentaram`,
  usernameRepliedToYourComment: (...v) => `<b>${v[0]}</b> respondeu ao seu comentário`,
  usernameAndXMoreRepliedToYourComment: (...v) =>
    `<b>${v[0]}</b> e mais ${v[1]} responderam ao seu comentário`,
  useThisEmailTo: `Use este e-mail para: autenticar, receber notificações`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `Infelizmente, ${v[0]} teve que cancelar este pedido`,
  valueIsNotTheSame: `Valor não é o mesmo`,
  vote: `Votar`,
  tapAddToCreateOne: `Toque em “Adicionar” para criar um`,
  verificationCode: `Código de verificação`,
  verifyCode: `Verificar o código`,
  viewDetails: `Ver detalhes`,
  viewReview: `Ver avaliação`,
  viewEveryNotificationOfAGroupSeparately: `Ver cada notificação de um grupo separadamente`,
  visitOurDiscordChannelToGetMoreDetails: `Visite o nosso canal discord para obter mais detalhes`,
  weAreOnInstagram: `Estamos no instagram`,
  weAreWorkingOnIt: `Estamos trabalhando nisso`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `Muito bem! O trabalho foi concluído com sucesso`,
  weDoNotDisplayNSFWContentYet: `Ainda não exibimos conteúdo NSFW`,
  weekly: `Semanal`,
  whenYouPurchaseSomethingItWillAppearHere: `Quando você comprar algo, aparecerá aqui`,
  weHaveSentTooManyEmails: `Enviamos muitos e-mails, por favor, tente novamente mais tarde ou entre em contato com o suporte ao cliente`,
  welcomeToAnimeClub: `Bem-vindo ao Anime.club!`,
  weSentAnEmailTo: `Enviamos um e-mail para:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Enviamos a você um novo e-mail de verificação. Por favor insira o código`,
  weAreExcitedToSeeYourProgressKeepItUp: `Estamos empolgados em ver seu progresso. Continue assim!`,
  weSupportOnlyTheFollowingFileExtensions: `Oferecemos suporte apenas para as seguintes extensões de arquivo:`,
  work: `Trabalho`,
  weWouldLoveToHearFromYou: `Adoraríamos ouvir de você`,
  workDescription: `Descrição do trabalho`,
  leaveAReview: `Deixe uma avaliação`,
  wrongEmailOrPassword: `Email ou senha incorretos`,
  yes: `sim`,
  yesterday: `Ontem`,
  youReceivedANewOrderFrom: (...v) => `Você recebeu um novo pedido de <b>${v[0]}</b>`,
  youReceivedAReview: `Você recebeu uma avaliação`,
  reply: `Responder`,
  youHaveSuccessfullyCreatedYourShop: `Você criou sua loja com sucesso`,
  replyToUsername: (...v) => `Responder a ${v[0]}`,
  numOfReplies: (...v) => `${v[0]} resposta(s)`,
  numOfNewComments: (...v) => `${v[0]} novo(s) comentário(s)`,
  numOfNewReactions: (...v) => `${v[0]} nova(s) reação(ões)`,
  replies: `Respostas`,
  youAreAlreadyAuthenticated: `Voce ja esta autenticado`,
  youCanAutoPublishToYourSocialMediaAccount: `Você pode publicar automaticamente em sua conta de mídia social`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Você pode modificar os tipos de notificações que recebe por e-mail`,
  youCanRequestRemovalOfYourAccount: `Você pode solicitar a remoção de sua conta com todos os seus dados`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `Seu feedback orienta compradores e ajuda vendedores a oferecer produtos melhores`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Você ainda pode navegar para as páginas abertas anteriormente`,
  youCanChooseFromTheListOrEnterACustomReason: `Você pode escolher uma opção da lista ou informar outro motivo`,
  youDidNotSelectAnyChats: `Você não selecionou nenhum bate-papo`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `Você verá avaliações aqui assim que os compradores compartilharem suas experiências`,
  youDidNotUpdateAnyValues: `Você não atualizou nenhum valor`,
  youDoNotHaveAnyChats: `Você não tem nenhum bate-papo`,
  youHaveNotSetAPassword: `Você não definiu uma senha`,
  youHaveNotSharedAnythingYet: `Você ainda não compartilhou nada`,
  youHaveReachedTheMaximumNumberOfFiles: `Você atingiu o número máximo de arquivos`,
  kindlyHoldOnForTheBuyersReview: `Por favor, aguarde a avaliação do comprador sobre o pedido.`,
  yourAccountIsVerifiedPleaseSignIn: `Sua conta foi verificada. Por favor, faça login`,
  yourAccountWillBeRemoved: (...v) => `Sua conta será removida ${v[0]}`,
  youHaveNoPurchases: `Você não tem compras`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Você poderia fornecer o motivo do cancelamento`,
  yourArts: `Suas artes`,
  youCanceledTheOrder: `Você cancelou o pedido`,
  yourAvatar: `Seu avatar`,
  yourBlog: `Seu blog`,
  yourFansAreWaiting: `Seus fãs estão esperando`,
  yourFeedIsEmpty: `seu feed está vazio`,
  yourSessionHasExpiredPleaseSignInAgain: `Sua sessão expirou, faça login novamente`,
}
