export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Sobre`,
  accept: `Aceitar`,
  account: `(en) Account`,
  accountActivation: `Ativação de conta`,
  accountAlreadyExists: `Conta já existe`,
  accountDoesNotExist: `Conta não existe`,
  add: `Adicionar`,
  addArt: `Adicionar arte`,
  addBlog: `Adicionar blog`,
  additionalResources: `(en) Additional resources`,
  addMore: `(en) Add more`,
  addNewArt: `Adicionar nova arte`,
  addPreview: `Adicionar visualização`,
  addSignInVia: `Adicionar iniciar secção via`,
  advancedOptions: `(en) Advanced options`,
  all: `Tudo`,
  alreadySignedIn: `Secção já iniciada`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (...v) =>
    `(en) Amount should not be less than ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Arte de anime de artistas de todo o mundo. A arte é selecionada para ser relacionada ao anime. A seleção de arte é uma lista infinita das melhores artes de anime`,
  animeArtSubscribeToArtistsLikeAndCreate: `Arte de anime - inscreva-se em artistas, curta e crie coleções`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - a primeira plataforma a oferecer aos artistas pagamentos a partir de visualizações via Google AdSense. Apoie os artistas visualizando seu conteúdo ou comece a ganhar com as visualizações`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - veja, poste e ganhe com conteúdo de anime`,
  animeCommunity: `Comunidade de anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `(en) Anime.club never asks for your private information`,
  animeSocialNetwork: `(en) Anime
Social Network`,
  announcements: `(en) Announcements`,
  apply: `Aplicar`,
  appSettings: `(en) App settings`,
  appsVersionIs: `A versão do aplicativo é`,
  areYouSureYouWantTo: `Você tem certeza que quer`,
  art: `Arte`,
  artAssociatedWithAnime: `Arte associada a anime`,
  artBy: `Arte de`,
  artCannotBeChanged: `Arte não pode ser mudada`,
  authenticationFailed: `Autenticação falhou`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `Costas`,
  blog: `Blog`,
  bookmarks: `Itens salvos`,
  browseArt: `Navegue pela arte`,
  cancel: `cancelar`,
  cannotStartWithChars: `Não pode começar com s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `(en) Change`,
  changeArt: `Mudar arte`,
  changeAvatar: `Mudar avatar`,
  changeEmail: `(en) Change email`,
  changePassword: `Mudar senha`,
  chooseExistingChatOrStartANewOne: `Escolha o bate-papo existente ou inicie um novo`,
  city: `Cidade`,
  clearAll: `Limpar`,
  close: `Fechar`,
  colorTheme: `(en) Color theme`,
  comingSoon: `Em breve...`,
  community: `Comunidade`,
  confirmAccount: `Confirmar a conta`,
  confirmPassword: `Confirmar a senha`,
  connectWithUsOn: `(en) Connect with us on`,
  contactInformation: `(en) Contact information`,
  continue: `(en) Continue`,
  contractTitle: `(en) Contract Title`,
  copyLink: `Copiar link`,
  couldNotCreateANewRecord: `Não foi possível criar um novo registro`,
  country: `País`,
  createANewAccountFailed: `Falha ao criar uma nova conta`,
  createNewAccount: `Criar nova conta`,
  currentPassword: `(en) Current password`,
  daily: `(en) Daily`,
  darkDefault: `(en) Dark default`,
  darkHighContrast: `(en) Dark high contrast`,
  dayTheme: `(en) Day theme`,
  delete: `Excluir`,
  deleteArt: `Apagar art`,
  deletePost: `Apagar publicação`,
  description: `Descrição`,
  details: `Detalhes`,
  didntReceiveEmail: `Não recebeu correio electrónico?`,
  donations: `Doações`,
  done: `Pronto`,
  dragAndDropOrSelectFiles: `(en) Drag & Drop or Select file(s)`,
  drawingContest: `Concurso de desenho`,
  dueDate: `(en) Due date`,
  earlier: `(en) Earlier`,
  earningFromArts: `Ganhando com as artes`,
  edit: `Editar`,
  editPost: `Editar post`,
  editProfile: `Editar perfil`,
  editTranslations: `Editar traduções`,
  email: `Correio electrónico`,
  emailAlreadyUsedByAnotherAccount: `Email já usado por outra conta`,
  emailNotifications: `(en) Email Notifications`,
  enterOrPasteALink: `Insira ou cole um link`,
  enterTheAddressAssociatedWithYourAccount: `(en) Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `(en) Enter your password`,
  error: `(en) Error`,
  errorPleaseContactCustomerSupport: `Erro! Entre em contato com o suporte ao cliente...`,
  exitEditor: `Sair do editor`,
  extensions: `Extensões`,
  fileSizeIsTooBig: `O tamanho do arquivo é muito grande`,
  filter: `Filtro`,
  filterBy: `Filtrar por`,
  findUser: `Encontrar usuário`,
  follow: `Seguir`,
  followers: `Seguidores`,
  following: `Seguindo`,
  followMeOn: `Siga-me`,
  follows: `(en) Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `Para todas as outras perguntas, entre em contato conosco em:`,
  forgotPassword: `Esqueceu a senha`,
  forNewMasterpieces: `Para novas obras-primas`,
  fromAnimeDotClub: `(en) From anime.club`,
  getDetails: `Obter detalhes`,
  guestView: `Vista de convidado`,
  hire: `(en) Hire`,
  homepage: `Página inicial`,
  howToContactYou: `(en) How to contact you`,
  howToFindYouOnOtherSocialNetworks: `(en) How to find you on other social networks`,
  iAgreeWith: `Eu concordo com`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `A altura do Img deve ser maior ou igual a`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `A largura do Img deve ser maior ou igual a`,
  introduction: `Introdução`,
  invalidCode: `Código inválido`,
  invalidDate: `(en) Invalid date`,
  invalidCurrentPassword: `(en) Invalid current password`,
  invalidPartAfterAt: `Parte inválida após @`,
  invalidPartBeforeAt: `Parte inválida antes de @`,
  jobDetails: `(en) Job Details`,
  joinAnimeClubCommunity: `(en) Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `Entrar no chat`,
  joinUsOnFacebook: `Junte-se a nós no Facebook`,
  language: `(en) Language`,
  languages: `Línguas`,
  letEveryoneKnowHowToDonateToYou: `(en) Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `(en) Let others know about you`,
  lightDefault: `(en) Light default`,
  lightHighContrast: `(en) Light high contrast`,
  likes: `Gostos`,
  linkCopiedToClipboard: `Link copiado para a área de transferência`,
  livesIn: `Vivendo em`,
  loading: `(en) Loading`,
  location: `(en) Location`,
  logInOrSignUp: `(en) Log in or sign up`,
  logOut: `(en) Log out`,
  maximumNChars: (...v) => `Máximo ${v[0]} caracteres`,
  maxSize: `Tamanho máximo`,
  menu: `Cardápio`,
  message: `Mensagem`,
  messages: `Mensagens`,
  minHeight: `Altura mínima`,
  minimumNChars: (...v) => `Mínimo ${v[0]} caracteres`,
  minWidth: `Largura mínima`,
  monthly: `(en) Monthly`,
  moreFrom: (...v) => `Mais de ${v[0]}`,
  mustBeNChars: (...v) => `Deve ter ${v[0]} caracteres`,
  myPayments: `(en) My payments`,
  myProfile: `(en) My profile`,
  mySettings: `(en) My settings`,
  need1Lowercase: `Precisa de 1 minúsculas`,
  need1Number: `Precisa de 1 número`,
  need1Uppercase: `Precisa de 1 maiúsculo`,
  needAtLeast1CharacterFromN: (...v) =>
    `Precisa de pelo menos 1 caractere de [${v[0]}]`,
  needNCharacter: (...v) => `Deve ter ${v[0]} personagem`,
  newAccount: `Nova conta`,
  newArt: `Nova arte`,
  newArtworks: `(en) New artworks`,
  newBlog: `Novo blog`,
  newPassword: `Nova senha`,
  newsFeed: `Feed de notícias`,
  next: `(en) Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `(en) Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `(en) Night theme`,
  no: `não`,
  noAddedFavoriteArts: `nenhum art favorito adicionado`,
  noInternetConnection: `Sem conexão com a Internet!`,
  none: `(en) None`,
  noNotifications: `(en) No notifications`,
  noResults: `(en) No results`,
  notifications: `Notificações`,
  nsfwContent18Plus: `Conteúdo NSFW (18+)`,
  online: `Online`,
  onlyLatinLettersNumbersOrSpecialSymbols: `Apenas letras latinas, números, símbolos especiais`,
  onlyNumbers: `Apenas números`,
  open: `(en) Open`,
  openGuestView: `Abrir visualização de convidado`,
  openingSoon: `Aberto em breve!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `OU`,
  pageNotFound: `(en) Page not found`,
  password: `Senha`,
  payments: `Pagamentos`,
  personal: `(en) Personal`,
  pleaseCheckYour: (...v) => `(en) Please check your ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `(en) Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `Por favor, solte apenas uma imagem`,
  pleaseEnterAtLeastNChars: (...v) =>
    `Por favor, insira pelo menos ${v[0]} caracteres`,
  pleaseFillOutYourDetails: `Por favor, preencha seus dados`,
  pleaseSignInToYourAccount: `Por favor entre em sua conta`,
  pleaseTryAgainOrClick: (...v) =>
    `Por favor, tente de novo e clique em ${v[0]}`,
  pleaseVerifyYourAccount: `Por favor, verifique sua conta`,
  pressHereTo: `Pressione aqui para`,
  privacyPolicy: `Política de Privacidade`,
  privateInformation: `(en) Private information`,
  profile: `Perfil`,
  promotions: `(en) Promotions`,
  publicInformation: `(en) Public information`,
  publishOn: (...v) => `(en) Publish on ${v[0]}`,
  rankings: `(en) Rankings`,
  reorderFiles: `(en) Reorder files`,
  report: `(en) Report`,
  save: `Salvar`,
  saveAvatar: `Salvar avatar`,
  saveChanges: `Salvar alterações`,
  selectAnime: `Selecionar anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `(en) Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `Selecionar avatar`,
  selectCharacters: `Selecionar personagem(s)`,
  selectFile: `Selecionar arquivo`,
  selectTheme: `(en) Select theme`,
  selectThumbnail: `Selecionar miniatura`,
  sendEmail: `Enviar email`,
  settings: `Configurações`,
  share: `(en) Share`,
  shareYourArtWithTheWorld: `(en) Share your art with the world`,
  shareYourStory: `Compartilhe sua história!`,
  shop: `Loja`,
  showLess: `Mostrar menos`,
  showMore: `Mostrar mais`,
  signIn: `Fazer login`,
  singleTheme: `(en) Single theme`,
  size: `(en) Size`,
  skip: `Pular`,
  socialMedia: `Mídia social`,
  spaceCharacterIsNotAllowed: `O caractere de espaço não é permitido`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Subscreva-se ao talents para acompanhar o seu progresso`,
  successChangedPasswordPleaseSignIn: `Sucesso! Senha alterada. Por favor, inscreva-se`,
  successCreatedRecord: `Sucesso! Registro criado!`,
  successUpdatedRecord: `Sucesso! Registro atualizado!`,
  supportMeOn: `Apoie-me em`,
  syncWithSystem: `(en) Sync with system`,
  tellUsAboutYourself: `Conte-nos sobre você`,
  termsAndConditions: `Termos e condições`,
  termsOfUse: `Termos de uso`,
  theLinkIsBrokenOrPageHasBeenRemoved: `(en) The link is broken or page has been removed`,
  themeMode: `(en) Theme mode`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `Título`,
  today: `(en) Today`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `Digite seu texto aqui...`,
  upload: `(en) Upload`,
  uploadAnotherArt: `Fazer upload de outra arte`,
  uploadAnotherAvatar: `Fazer upload de outro avatar`,
  uploadArtNow: `Fazer upload de arte agora!`,
  uploadNew: `Fazer upload de novo`,
  uploadNewArt: `Fazer upload de nova arte`,
  uploadNewPost: `Fazer upload de nova mensagem`,
  username: `Nome de Usuário`,
  usernameAlreadyExists: `Nome de usuário já existe`,
  usernameAndXMoreFollowYou: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more follow you`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more like your artwork`,
  usernameFollowsYou: (...v) => `(en) <b>${v[0]}</b> follows you`,
  usernameLikesYourArt: (...v) => `(en) <b>${v[0]}</b> likes your art`,
  useThisEmailTo: `(en) Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `Valor não é o mesmo`,
  verificationCode: `Código de verificação`,
  verifyCode: `Verificar o código`,
  visitOurDiscordChannelToGetMoreDetails: `Visite o nosso canal discord para obter mais detalhes`,
  weAreOnInstagram: `Estamos no instagram`,
  weAreWorkingOnIt: `Estamos trabalhando nisso`,
  weDoNotDisplayNSFWContentYet: `Ainda não exibimos conteúdo NSFW`,
  weekly: `(en) Weekly`,
  weHaveSentTooManyEmails: `(en) We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Bem-vindo ao Anime.club!`,
  weSentAnEmailTo: `Enviamos um e-mail para:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Enviamos a você um novo e-mail de verificação. Por favor insira o código`,
  weSupportOnlyTheFollowingFileExtensions: `Oferecemos suporte apenas para as seguintes extensões de arquivo:`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `Email ou senha incorretos`,
  yes: `sim`,
  yesterday: `(en) Yesterday`,
  youAreAlreadyAuthenticated: `Voce ja esta autenticado`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `(en) You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Você ainda pode navegar para as páginas abertas anteriormente`,
  youDidNotSelectAnyChats: `Você não selecionou nenhum bate-papo`,
  youDidNotUpdateAnyValues: `Você não atualizou nenhum valor`,
  youDoNotHaveAnyChats: `Você não tem nenhum bate-papo`,
  youHaveNotSavedAnyChanges: `Você não salvou nenhuma alteração. Sair?`,
  youHaveNotSetAPassword: `(en) You have not set a password`,
  youHaveReachedTheMaximumNumberOfFiles: `(en) You have reached the maximum number of files`,
  yourAccountIsVerifiedPleaseSignIn: `Sua conta foi verificada. Por favor, faça login`,
  yourArts: `Suas artes`,
  yourAvatar: `Seu avatar`,
  yourBlog: `Seu blog`,
  yourFansAreWaiting: `Seus fãs estão esperando`,
  yourFeedIsEmpty: `seu feed está vazio`,
  yourSessionHasExpiredPleaseSignInAgain: `Sua sessão expirou, faça login novamente`,
}
