export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  _hyphen: `- `,
  about: `Сведения`,
  accept: `Принять`,
  acceptOrder: `Принять заказ`,
  acceptTheOrder: `Принять заказ`,
  accountManagment: `Управление аккаунтом`,
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `Anime.club использует ${v[0]} , чтобы быстро переводить вам деньги и обеспечивать безопасность ваших личных и платежных данных`,
  account: `Аккаунт`,
  accountDeleted: `Учетная запись удалена`,
  clickTheButtonBelowToOpenYourStripeDashboard: `Нажмите кнопку ниже, чтобы открыть панель управления Stripe и просмотреть данные своего аккаунта`,
  animeShopBuyAndSellProducts: `Магазин аниме - покупайте и продавайте товары`,
  visitStripeDashboard: `Открыть панель управления Stripe`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `Изображения, созданные ИИ, и фильтры нейронных сетей запрещены`,
  accountActivation: `Активация аккаунта`,
  accountAlreadyExists: `Аккаунт уже существует`,
  accountDoesNotExist: `Аккаунт не существует`,
  accountRemoval: `Удаление аккаунта`,
  files: `Файлы`,
  prohibitedTransaction: `Запрещённая транзакция`,
  add: `Добавить`,
  addArt: `Добавить арт`,
  addBlog: `Добавить блог`,
  additionalResources: `Дополнительные материалы`,
  addMoreProductsToYourShop: `Добавьте больше товаров в ваш магазин`,
  addMore: `Добавить ещё`,
  addNewArt: `Добавить новый арт`,
  addSignInVia: `Добавить вход через`,
  addToCart: `Добавить в корзину`,
  advancedOptions: `Дополнительные параметры`,
  uploadTheFilesYourBuyerWillGet: `Загрузите файлы, которые <b>получит покупатель</b>`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `Убедитесь, что всё готово — после публикации внести изменения будет нельзя`,
  filesForTheBuyer: `Файлы для покупателя`,
  filesForPreview: `Файлы для предпросмотра`,
  all: `Все`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `Все файлы, загруженные здесь, будут доступны покупателю`,
  alreadySignedIn: `Уже авторизованы`,
  amount: `Сумма`,
  amountShouldNotBeLessThan: (...v) => `Сумма не должна быть меньше $${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Это коллекция аниме-артов, которые созданы талантливыми художниками из разных уголков мира. Арты проверяются на соответствие аниме-стилю. Наша галлерея - это бесконечный список лучших аниме работ.`,
  animeArtSubscribeToArtistsLikeAndCreate: `Аниме арты - подписывайтесь на художников, оценивайте и создавайте коллекции`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - первая платформа, предлагающая художникам оплату за просмотры через Google AdSense. Поддержите художников, просматривая их контент или начните зарабатывать на просмотрах.`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - просматривайте, размещайте и зарабатывайте на аниме-контенте.`,
  animeCommunity: `Аниме-сообщество`,
  animeDotclubNeverAsksForYourPrivateInformation: `Сотрудники Anime.club никогда не запрашивают вашу личную информацию`,
  animeSocialNetwork: `Аниме.club
Социальная сеть`,
  announcements: `Объявления`,
  appearance: `Внешний вид`,
  apply: `Применить`,
  appSettings: `Настройки приложения`,
  appsVersionIs: `Версия приложения`,
  areYouSureYouWantTo: `Вы уверены, что хотите`,
  art: `Арт`,
  artAssociatedWithAnime: `Арт связан с аниме`,
  artBy: (...v) => `Арт от ${v[0]}`,
  artCannotBeChanged: `Арт нельзя изменить`,
  artworksAvailableToView: (...v) => `${v[0]} артов доступно для просмотра`,
  authenticationFailed: `Ошибка аутентификации`,
  system: `Системная`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Автопубликация в Instagram доступна только для бизнес-аккаунтов Instagram`,
  attentionYourOrderHasBeenDisputed: `Внимание! Ваш заказ оспорен. Пожалуйста, ознакомьтесь с деталями`,
  needsYourReview: `Требуется ваша проверка`,
  awaitingSellersResponse: `Ожидание ответа продавца`,
  back: `Назад`,
  basePrice: `Исходная стоимость`,
  bigAppreciationToTheSellerForTheHardWork: `Большая благодарность продавцу за проделанную работу`,
  block: `Блокировать`,
  buyerReviewedTheOrder: `Покупатель оставил отзыв о заказе`,
  buyerHasNotLeftAReviewYet: `Покупатель еще не оставил отзыв`,
  feedbackReceived: `Отзыв получен!`,
  blockUser: (...v) => `Заблокировать @${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `Перед принятием внимательно ознакомьтесь с запросом покупателя`,
  blog: `Блог`,
  bookmarks: `Закладки`,
  browseArt: `Посмотреть арты`,
  browseShop: `Открыть магазин`,
  buyer: `Покупатель`,
  buyersRequest: `Запрос покупателя`,
  cancel: `отмена`,
  canceled: `Отменен`,
  comments: `Комментарии`,
  cancelOrder: `Отменить заказ`,
  cannotStartWithChars: `Не может начинаться с s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Изменить`,
  checkOutMyShop: `Посетите мой магазин`,
  checkOrderStatus: `Проверить статус`,
  changeArt: `Изменить арт`,
  changeAvatar: `Изменить аватар`,
  changeEmail: `Изменить email`,
  changePassword: `Изменить пароль`,
  chooseExistingChatOrStartANewOne: `Выберите существующий чат или начните новый`,
  city: `Город`,
  clearAll: `Очистить всё`,
  awaitingClientReview: `Ожидание проверки клиентом`,
  close: `Закрыть`,
  color: `Цвет`,
  colorTheme: `Цветовая тема`,
  comingSoon: `Скоро...`,
  commercialUseAllowed: `Коммерческое использование разрешено`,
  commercialUseAllowsBuyersToUseYourProduct: `Коммерческое использование позволяет покупателям использовать ваш продукт в бизнес-целях, таких как продажа или продвижение их услуг`,
  community: `Сообщество`,
  completed: `Завершен`,
  confirmAccount: `Подтвердить аккаунт`,
  confirmOrder: `Подтвердить заказ`,
  confirmPassword: `Подтвердить пароль`,
  connectWithUsOn: `Свяжитесь с нами в`,
  contactInformation: `Контактная информация`,
  contactSeller: `Связаться с продавцом`,
  contactSupport: `Связаться со службой поддержки`,
  contactUs: `Свяжитесь с нами`,
  continue: `Продолжить`,
  contractTitle: `Название контракта`,
  copy: `Копировать`,
  congratulations: `Поздравляем!`,
  thankYouForYourPurchase: `Спасибо за покупку!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `Поздравляем с успешным завершением вашего заказа!`,
  copyrightViolation: `Нарушение авторских прав`,
  couldNotCreateANewRecord: `Не удалось создать новую запись`,
  country: `Страна`,
  cover: `Обложка`,
  createANewAccountFailed: `Не удалось создать новый аккаунт`,
  createExtrasForYourProduct: `Создайте дополнительные услуги для вашего продукта`,
  createNewAccount: `Создать новый аккаунт`,
  createAShopWithStripe: `Создайте магазин с помощью Stripe`,
  createdBy: `Создано`,
  currentPassword: `Текущий пароль`,
  daily: `Ежедневно`,
  dark: `Тёмная`,
  delete: `Удалить`,
  deleteShop: `Удалить магазин`,
  deleteAccount: `Удалить аккаунт`,
  deleteArt: `Удалить арт`,
  decline: `Отклонить`,
  deletePost: `Удалить запись`,
  deleteProduct: `Удалить продукт`,
  download: `Скачать`,
  downloadThemBelow: `Скачайте их ниже`,
  deliveryTime: `Срок доставки`,
  describeTheDetailsOfYourExtra: `Опишите детали вашей дополнительной услуги`,
  description: `Описание`,
  details: `Подробности`,
  didntReceiveEmail: `Не получили email?`,
  displayName: `Отображаемое имя`,
  disputed: `Оспаривается`,
  donations: `Пожертвования`,
  documentation: `Документация`,
  done: `Готово`,
  dragAndDropOrSelectFiles: `Перетащите файлы или нажмите для выбора`,
  drawingContest: `Конкурс рисунков`,
  dueDate: `Срок сдачи`,
  earlier: `Раньше`,
  earningFromArts: `Заработок на артах`,
  edit: `Редактировать`,
  editPost: `Редактировать запись`,
  editProfile: `Редактировать профиль`,
  editTranslations: `Помочь с переводом`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email уже используется другим аккаунтом`,
  emailNotifications: `Email уведомления`,
  enterOrPasteALink: `Введите или вставьте ссылку`,
  enjoyYourPurchase: `Наслаждайтесь вашей покупкой! 😊`,
  enterTheAddressAssociatedWithYourAccount: `Введите email, связанный с вашим аккаунтом`,
  enterYourPassword: `Введите пароль`,
  error: `Ошибка`,
  errorPleaseContactCustomerSupport: `Ошибка! Свяжитесь со службой поддержки...`,
  exitWithoutSaving: `Выйти без сохранения`,
  extensions: `Расширения`,
  extras: `Дополнительные услуги`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `Дополнительные услуги - это опциональные дополнения для улучшения вашего продукта`,
  fileSizeIsTooBig: `Размер файла слишком большой`,
  fileSizeIsTooSmall: `Размер файла слишком мал`,
  filter: `Фильтр`,
  filterBy: `Фильтровать по`,
  findUser: `Найти пользователя`,
  finishSettingUpYourShop: `Завершите создание вашего магазина`,
  follow: `Подписаться`,
  followers: `Подписчиков`,
  following: `Подписок`,
  followMeOn: `Подпишитесь на меня в`,
  follows: `Подписки`,
  forAllOtherInquiriesPleaseContactUsAt: `По всем остальным вопросам, связь через:`,
  forgotPassword: `Не помню пароль`,
  fromAnimeDotClub: `От anime.club`,
  getDetails: `Подробнее`,
  getStarted: `Начать`,
  guestView: `Гостевой просмотр`,
  greatNewsYourOrderIsNowInProgress: `Отличные новости! Ваш заказ в работе`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `Отличные новости! ${v[0]} купил ваш товар. Самое время отпраздновать!`,
  harassment: `Домогательство`,
  haveAnyQuestions: `У Вас есть вопросы?`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> отменил заказ`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> отправил работу`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]} не добавил описание для "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]} ещё не поделился публичными данными`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `@${v[0]} пока не выставил ни одного товара на продажу`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `@${v[0]} пока ничего не добавил в портфолио`,
  hate: `Ненависть`,
  hereAreAFewWaysToGetThingsRolling: `Вот несколько способов начать`,
  hire: `Нанять`,
  hideListing: `Скрыть объявление`,
  uploadUpToNumberFiles: (...v) => `Загрузите до <b>${v[0]}</b> файлов`,
  supportedFormats: `Поддерживаемые форматы:`,
  minimumDimensions: (...v) => `Минимальный размер: ${v[0]}×${v[1]} пикселей`,
  maximumFileSize: (...v) => `Максимальный размер одного файла: <b>${v[0]}</b>`,
  thisListingWontBeVisibleToBuyersAnymore: `Покупатели больше не увидят это объявление, но вы сможете снова показать его в любое время`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `Покупатели смогут увидеть это объявление. Вы сможете снова скрыть его в любое время`,
  listingHiddenFromBuyers: `Объявление скрыто от покупателей`,
  listingIsNowVisibleToBuyers: `Теперь объявление видно покупателям`,
  showListing: `Показать объявление`,
  homepage: `Главная`,
  howToContactYou: `Как с вами связаться`,
  howToFindYouOnOtherSocialNetworks: `Как найти вас в других социальных сетях`,
  iAgreeWith: `Я согласен с`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Если до ${v[0]} не будет ответа, заказ будет автоматически отмечен как выполненный`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `Если до ${v[0]} ответа не будет, заказ отменится автоматически`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `Если до ${v[0]} ответа не будет, вы автоматически получите полный возврат средств`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `Если вы не уложитесь в срок, покупатель сможет отменить заказ и получить полный возврат средств, а все связанные комиссии Stripe будут вычтены из вашей выплаты.`,
  id: `ID`,
  addAComment: `Добавить комментарий`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Высота изображения должна быть больше или равна`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Ширина изображения должна быть больше или равна`,
  impersonation: `Выдача себя за другого`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `Эти правила установлены продавцом и относятся только к этому товару`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `Если у вас есть вопросы или сомнения, свяжитесь напрямую с продавцом`,
  platformPoliciesMayStillApply: `Правила платформы также могут применяться`,
  theseAreYourTermsForThisItem: `Это ваши условия для этого товара`,
  theBuyerAcceptedThemAtCheckout: `Покупатель принял их при оформлении заказа`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Укажите ключевые слова, которые покупатели, скорее всего, будут использовать для поиска продукта, подобного вашему`,
  increaseContrast: `Увеличить контрастность`,
  inProgress: `В процессе`,
  introduction: `Введение`,
  includes: `Включает`,
  invalidCode: `Неверный код`,
  invalidCurrentPassword: `Неверный текущий пароль`,
  invalidDate: `Неверная дата`,
  invalidPartAfterAt: `Недопустимая часть после @`,
  invalidPartBeforeAt: `Недопустимая часть перед @`,
  jobDetails: `Подробности о работе`,
  joinAnimeClubCommunity: `Присоединяйтесь к сообществу Anime.club — тысячи активных пользователей и крутые аниме-арты каждый день!`,
  joinChat: `Присоединиться к чату`,
  joinUsOnFacebook: `Присоединяйтесь к нам на Facebook`,
  language: `Язык`,
  lackOfInformation: `Недостаточно информации`,
  languages: `Языки`,
  letEveryoneKnowHowToDonateToYou: `Дайте всем знать, как вам донатить`,
  letOthersKnowAboutYou: `Дайте другим знать о себе`,
  letsUploadYourFirstProduct: `Давайте загрузим ваш первый продукт`,
  letUsKnowWhatsHappening: `Сообщите нам, что происходит, и мы разберемся`,
  light: `Светлая`,
  likes: `Нравится`,
  limit: `Лимит`,
  copiedToClipboard: `Скопировано в буфер обмена`,
  livesIn: `Проживает в`,
  loading: `Загрузка`,
  location: `Местоположение`,
  logInOrSignUp: `Войдите или зарегистрируйтесь`,
  logOut: `Выйти`,
  maximumNChars: (...v) => `Максимум символов: ${v[0]}`,
  maximumNumberOfDaysToCompleteTheOrder: `Максимальное количество дней для выполнения заказа`,
  maximumQuantity: `Максимальное количество`,
  maxSize: `Максимальный размер`,
  menu: `Меню`,
  uploadedFilesLocked: `Вы загрузили эти файлы при создании публикации. Теперь они заблокированы, но по-прежнему отображаются ниже`,
  message: `Сообщение`,
  messages: `Сообщения`,
  minHeight: `Минимальная высота`,
  minimumNChars: (...v) => `Минимум символов: ${v[0]}`,
  minorAbuseOrSexualization: `Насилие или сексуализация несовершеннолетних`,
  makeSureToIncludeClearInstructions: `Убедитесь, что вы включили четкие инструкции о том, как использовать каждую ссылку`,
  makeSureYouFullyUnderstandTheRequirements: `Убедитесь, что вы полностью понимаете требования и можете выполнить заказ в срок`,
  makeSureYourProductsArePricedCompetitively: `Убедитесь, что ваши товары имеют конкурентоспособные цены`,
  minWidth: `Минимальная ширина`,
  monthly: `Ежемесячно`,
  moreFrom: (...v) => `Больше от ${v[0]}`,
  mustBeNChars: (...v) => `Должно быть символов: ${v[0]}`,
  myPayments: `Мои платежи`,
  myProfile: `Мой профиль`,
  mySettings: `Мои настройки`,
  need1Lowercase: `Требуется 1 строчная буква`,
  need1Number: `Требуется 1 число`,
  need1Uppercase: `Требуется 1 прописная буква`,
  needAtLeast1CharacterFromN: (...v) => `Требуется не менее 1 символа из [${v[0]}]`,
  needNCharacter: (...v) => `Требуется ${v[0]} символ`,
  new: `Новое`,
  newAccount: `Новый аккаунт`,
  newArt: `Новый арт`,
  createPersonalizedWorkTailoredToEachRequest: `Создавайте персональные работы с учётом каждого запроса`,
  offerDigitalProducts: `Предлагайте цифровые товары, доступные покупателям сразу после покупки`,
  instantDownload: `Мгновенное скачивание`,
  customWork: `Работа на заказ`,
  newArtworks: `Новые арты`,
  newBlog: `Новый блог`,
  newOrder: `Новый заказ`,
  newPassword: `Новый пароль`,
  newProduct: `Новый продукт`,
  allListings: `Все объявления`,
  newCommission: `Новый заказ`,
  newsFeed: `Лента новостей`,
  next: `Продолжить`,
  nextTimeYouAuthenticateYouCouldUseThe: `В следующий раз вы можете использовать подключенный аккаунт вместо логина и пароля`,
  no: `нет`,
  noOrders: `Заказов нет`,
  noInternetConnection: `Подключение к Интернету отсутствует!`,
  nonConsensualIntimateContent: `Несогласованный интимный контент`,
  none: `Нет`,
  noNotifications: `Нет уведомлений`,
  noResults: `Нет результатов`,
  noReviewsJustYet: `Пока нет отзывов`,
  noCommentsJustYet: `Пока нет комментариев`,
  beTheFirstToShareYourThoughts: `Будьте первым, кто поделится мнением`,
  notifications: `Уведомления`,
  noActiveOrdersToShow: `Нет активных заказов для отображения`,
  notAcceptingOrders: `Не принимаю заказы`,
  noSalesYetNoWorries: `Пока нет продаж? Не переживайте, вы только начинаете`,
  nsfwContent18Plus: `Материалы для взрослых (18+)`,
  NSFWIndicatesAdultContent: `18+ NSFW указывает на контент для взрослых. Отметьте это поле, только если ваш продукт предназначен для зрелой аудитории`,
  numberOfAdjustmentsAClientCouldRequest: `Количество корректировок, которые клиент может запросить`,
  online: `В сети`,
  onlyLatinLettersNumbersHyphen: `Только латинские буквы, цифры, дефис, подчеркивание и точка`,
  onlyNumbers: `Только числа`,
  onlyYouCanSeeWhatYouveSaved: `Только вы можете видеть, что вы сохранили`,
  open: `Открыть`,
  openDispute: `Открыть спор`,
  openGuestView: `Открыть вид для гостей`,
  openingSoon: `Скоро открытие!`,
  openToWork: `Открыт для работы`,
  optional: `Необязательно`,
  requestDetails: `Детали запроса`,
  or: `или`,
  order: `Заказ`,
  outOfStock: `Нет в наличии`,
  ordered: (...v) => `Заказано ${v[0]}`,
  orderAgain: `Заказать снова`,
  orderDetails: `Детали заказа`,
  orderConfirmed: `Заказ подтверждён`,
  orderCompleted: `Заказ завершен 🎉`,
  orderStatus: `Статус заказа`,
  orderOptions: `Варианты заказа`,
  otherReason: `Другая причина`,
  pageNotFound: `Страница не найдена`,
  buyNow: `Купить сейчас`,
  password: `Пароль`,
  payments: `Платежи`,
  attachedFiles: `Прикреплённые файлы`,
  numFilesIncluded: (...v) => `Включено файлов: <b>${v[0]}</b>`,
  personal: `Личное`,
  personalCircumstances: `Личные обстоятельства`,
  changedMyMind: `Передумал`,
  orderedByMistake: `Заказал по ошибке`,
  sellerHasntResponded: `Продавец не ответил`,
  foundAnotherArtist: `Нашёл другого художника`,
  tellTheBuyersWhatTheyWillGet: `Точно опишите, что получат покупатели. Например, количество иллюстраций, форматы файлов или параметры холста, такие как разрешение и DPI`,
  beSpecificAboutTheContent: `Подробно опишите содержимое (например, количество файлов, форматы и разрешение холста)`,
  mentionYourDeliveryTimeInDays: `Укажите <b>срок доставки</b> в днях`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `Сообщите покупателям, предлагаете ли вы <b>корректировки</b> и сколько`,
  listAnyContentOrRequestsYouDontAccept: `Перечислите контент или запросы, которые вы <b>не принимаете</b> (например, NSFW, политические, религиозные или оскорбительные материалы)`,
  offerOptionalExtras: `Предложите дополнительные услуги, например <b>срочное выполнение</b>, <b>дополнительного персонажа</b> или <b>детализированный фон</b>`,
  extrasHelpBoostIncome: `Дополнительные услуги помогают покупателям персонализировать заказ, а вам — увеличить доход`,
  pleaseAllowPopups: `Разрешите всплывающие окна`,
  pleaseCheckYour: (...v) => `Проверьте ваш ${v[0]}`,
  pleaseRateYourOrder: `Пожалуйста, оцените ваш заказ`,
  feelFreeToShareReferenceImagesAndMaterials: `Не стесняйтесь делиться референсными изображениями и материалами, чтобы помочь художнику создать вашу работу`,
  youWillBeAbleToUploadReferenceFilesAfterCheckout: `Загрузить файлы-референсы можно будет после оплаты`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Пожалуйста, не сообщайте свою личную информацию другим`,
  pleaseEnterANumberBetweenXandX: (...v) => `Введите число от ${v[0]} до ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `Введите символов, не менее ${v[0]} `,
  pleaseFillOutYourDetails: `Заполните свои данные`,
  pleaseFixTheErrorsBeforeSubmitting: `Пожалуйста, исправьте ошибки перед отправкой`,
  pleaseSignInToYourAccount: `Войдите в свой аккаунт`,
  platform: `Платформа`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `Вы сможете скачать файлы сразу после покупки — ждать не придётся!`,
  thisIsACustomOrderNotAReadyMadeProduct: `Это индивидуальный заказ, а не готовый товар. Продавец начнёт работу после оформления заказа`,
  nothingIsChargedUntilTheSellerAccepts: `Деньги не списываются, пока продавец не примет заказ, а если он откажется, с вас ничего не спишут`,
  orderCanceledTheBuyersPaymentWasReleased: `Заказ отменён. Мы сняли блокировку средств на карте покупателя, банку может потребоваться несколько дней`,
  orderCanceledYourPaymentWasReleased: `Заказ отменён. Мы сняли блокировку средств на вашей карте, банку может потребоваться несколько дней`,
  pleaseStartTyping: `Пожалуйста, начните вводить`,
  pleaseTakeAMomentToReviewTheOrder: `Пожалуйста, уделите минуту, чтобы просмотреть заказ`,
  pleaseReviewTheBuyersReferenceFiles: `Пожалуйста, ознакомьтесь с референсными файлами покупателя и следуйте им, как указано в описании заказа`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `Пожалуйста, внимательно ознакомьтесь с деталями перед продолжением`,
  pleaseRespondToTheOrderBy: (...v) => `Пожалуйста, ответьте на заказ до ${v[0]}`,
  pleaseTryAgainOrClick: (...v) => `Повторите или нажмите ${v[0]}`,
  whatWouldYouLikeToCreate: `Что вы хотите создать?`,
  shareYourArt: `Поделитесь своим артом`,
  ifYourArtIsNsfwCheckThisToAvoidAWarningOrBan: `Если ваш арт содержит NSFW, обязательно отметьте это. Иначе вы можете получить предупреждение, которое приведёт к блокировке.`,
  takeCustomRequests: `Принимать индивидуальные заказы`,
  sellDownloadableContent: `Продавать скачиваемый контент`,
  digitalDownloadsExamples: `Кисти, материалы, уроки и многое другое`,
  artGallery: `Галерея артов`,
  commission: `Заказ`,
  commissions: `Заказы`,
  digitalDownloads: `Цифровые материалы`,
  pleaseVerifyYourAccount: `Подтвердите свой аккаунт`,
  pressHereTo: `Нажмите здесь, чтобы`,
  price: `Цена`,
  payouts: `Выплаты`,
  privacyPolicy: `Политика конфиденциальности`,
  privateInformation: `Личная информация`,
  proceedToCheckout: `Перейти к оформлению заказа`,
  product: `Продукт`,
  itemReviews: `Отзывы о товаре`,
  portfolio: `Портфолио`,
  profile: `Профиль`,
  promotions: `Акции`,
  publicInformation: `Публичная информация`,
  publishOn: (...v) => `Опубликовать на ${v[0]}`,
  purchases: `Покупки`,
  rankings: `Рейтинги`,
  reorderFiles: `Изменить порядок файлов`,
  report: `Пожаловаться`,
  review: `Отзыв`,
  rules: `Правила`,
  reviews: `Отзывы`,
  numOfReviews: (...v) => `Отзывы: ${v[0]} `,
  reviewed: `Проверено`,
  reviewTitle: `Заголовок отзыва`,
  reason: `Причина`,
  revisions: `Корректировки`,
  includesXRevisionS: (...v) => `Включает ${v[0]} исправлений`,
  sales: `Продажи`,
  save: `Сохранить`,
  saveAvatar: `Сохранить аватар`,
  saveChanges: `Сохранить изменения`,
  selectAnime: `Выбрать аниме`,
  selectAppearanceContrastAndColorTheme: `Выберите оформление, контрастность и цветовую тему`,
  selectAvatar: `Выбрать аватар`,
  selectCharacters: `Выбрать персонажей`,
  seller: `Продавец`,
  selectFile: `Выбрать файл`,
  selectThumbnail: `Выбрать миниатюру`,
  selfHarmOrSuicide: `Нанесение вреда себе или суицид`,
  sendEmail: `Отправить email`,
  settings: `Настройки`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Создание магазина бесплатно и занимает всего несколько минут`,
  share: `Поделиться`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `Поделитесь своими правилами и типами запросов, которые вы не принимаете`,
  shareYourShopOnSocialMedia: `Поделитесь своим магазином в социальных сетях`,
  shareYourFavoritePiecesOn: (...v) => `Поделитесь своими любимыми работами на ${v[0]}`,
  shareYourArtWithTheWorld: `Поделитесь своими творениями с миром`,
  shareYourStory: `Поделитесь своей историей!`,
  sharingPersonalInformation: `Раскрытие личной информации`,
  shop: `Магазин`,
  shopReviews: `Отзывы о магазине`,
  shopOrders: `Заказы магазина`,
  showLess: `Свернуть`,
  showMore: `Показать больше`,
  show: `Показать`,
  hide: `Скрыть`,
  signIn: `Войти`,
  size: `Размер`,
  skip: `Пропустить`,
  socialMedia: `Социальные сети`,
  spaceCharacterIsNotAllowed: `Пробел не допускается`,
  spam: `Спам`,
  yourFavoritesWillShowUpHereAddSome: `Здесь будут отображаться ваши закладки. Добавьте что-нибудь!`,
  submitAReport: `Отправить жалобу`,
  submitWork: `Отправить работу`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Подпишитесь на художников, чтобы отслеживать их успехи`,
  successChangedPasswordPleaseSignIn: `Пароль успешно изменён. Войдите`,
  successCreatedRecord: `Запись успешно создана!`,
  changesSaved: `Изменения сохранены!`,
  successfullyDownloaded: `Успешно загружено!`,
  successfullyUploaded: `Успешно загружено!`,
  setUpStripeAccountToGetPaidWithAnimeClub: `Создайте аккаунт в Stripe, чтобы получать выплаты через Anime.club`,
  supportMeOn: `Поддержите меня на`,
  tellUsAboutYourself: `Расскажите нам о себе`,
  sellerTermsOfService: `Условия обслуживания продавца`,
  yourTermsOfService: `Ваши условия обслуживания`,
  showMyTermsOfService: `Показать мои условия обслуживания`,
  showSellerTermsOfService: `Показать условия продавца`,
  termsAndConditions: `Правила и условия`,
  termsOfUse: `Условия использования`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `Опишите, что входит в предложение и что получит покупатель после покупки`,
  thankYouForReport: `Спасибо за помощь в поддержании безопасного и уважительного онлайн-сообщества`,
  thankYouForYourReview: `Спасибо за ваш отзыв!`,
  theLinkIsBrokenOrPageHasBeenRemoved: `Ссылка не работает или страница была удалена`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `Причина отмены заказа, которую вы укажете, будет сообщена покупателю`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheSeller: `Указанная вами причина отмены заказа будет передана продавцу`,
  thisIsThePriceYouPropose: `Это цена, которую вы предлагаете`,
  thisFieldIsOptional: `Это поле необязательно`,
  thisCannotBeUndone: `Это действие нельзя отменить`,
  ensureYouveUploadedTheFinalVersion: `Убедитесь, что вы загрузили финальную версию перед отправкой`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `При желании добавьте описание, чтобы подробнее рассказать о своей работе`,
  pleaseProvideATitleForYourArtwork: `Укажите название вашей работы`,
  threateningViolence: `Угрозы насилия`,
  title: `Название`,
  timeConstraints: `Ограничения по времени`,
  titleYourExtraService: `Назовите вашу дополнительную услугу`,
  theMaximumQuantityThatACustomerCanAdd: `Максимальное количество, которое покупатель может добавить`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `Период проверки ограничен ${v[0]} днями`,
  toHelpTheCreatorCompleteYourOrder: `Для того чтобы продавец мог выполнить ваш заказ в соответствии с вашими пожеланиями, пожалуйста, укажите подробно, что именно вы хотели бы получить: укажите тему, стиль, особенности персонажа и другие важные детали.`,
  today: `Сегодня`,
  toGetWorkRelatedNotifications: `Для получения уведомлений, связанных с работой`,
  total: `Итого`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Чтобы посмотреть эти данные, вам нужно разблокировать @${v[0]}`,
  trademarkViolation: `Нарушение товарного знака`,
  typeYourTextHere: `Напечатайте здесь свой текст...`,
  theSellerHasUploadedTheseFilesForYou: `Продавец загрузил эти файлы для вас`,
  unblock: `Разблокировать`,
  unblockUser: (...v) => `Разблокировать @${v[0]}`,
  unfollow: `Отписаться`,
  unlimited: `Неограниченно`,
  upload: `Загрузить`,
  uploadNew: `Загрузить новый`,
  uploadNewPost: `Загрузить новую запись`,
  uploadNewProduct: `Загрузить новый продукт`,
  username: `Логин`,
  pleaseUploadOnlyFinishedWorkHere: `Пожалуйста, загружайте здесь только завершенные работы`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `Все файлы, связанные с процессом работы, должны быть загружены в сообщения`,
  usernameAlreadyExists: `Такой логин уже используется`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> и ещё ${v[1]} подписаны на вас`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b> и ещё ${v[1]} отреагировали`,
  usernameStartedFollowingYou: (...v) => `<b>${v[0]}</b> подписался на вас`,
  usernameLeftAReaction: (...v) => `<b>${v[0]}</b> оставил реакцию`,
  usernameCommentedOnYourWork: (...v) => `<b>${v[0]}</b> прокомментировал вашу работу`,
  usernameAndXMoreCommented: (...v) => `<b>${v[0]}</b> и ещё ${v[1]} оставили комментарии`,
  usernameRepliedToYourComment: (...v) => `<b>${v[0]}</b> ответил на ваш комментарий`,
  usernameAndXMoreRepliedToYourComment: (...v) =>
    `<b>${v[0]}</b> и ещё ${v[1]} ответили на ваш комментарий`,
  useThisEmailTo: `Используйте этот email для: аутентификации, получения уведомлений`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `К сожалению, ${v[0]} пришлось отменить этот заказ`,
  valueIsNotTheSame: `Значение не совпадает`,
  vote: `Голосовать`,
  tapAddToCreateOne: `Нажмите «Добавить», чтобы создать`,
  verificationCode: `Проверочный код`,
  verifyCode: `Проверить код`,
  viewDetails: `Подробнее`,
  viewReview: `Просмотреть отзыв`,
  viewEveryNotificationOfAGroupSeparately: `Просмотр каждого уведомления группы отдельно`,
  visitOurDiscordChannelToGetMoreDetails: `Посетите наш канал Discord для получения более подробной информации`,
  weAreOnInstagram: `Мы в Instagram`,
  weAreWorkingOnIt: `Мы работаем над этим`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `Отличная работа! Работа успешно завершена`,
  weDoNotDisplayNSFWContentYet: `Мы пока не показываем материалы для взрослых`,
  weekly: `Еженедельно`,
  whenYouPurchaseSomethingItWillAppearHere: `Когда вы что-нибудь купите, они появятся здесь`,
  weHaveSentTooManyEmails: `Мы отправили слишком много писем, попробуйте позже или свяжитесь со службой поддержки`,
  welcomeToAnimeClub: `Добро пожаловать в Anime.club!`,
  weSentAnEmailTo: `Мы отправили email на:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Мы отправили вам новый email с подтверждением. Введите код`,
  weAreExcitedToSeeYourProgressKeepItUp: `Мы с нетерпением ждем вашего прогресса. Так держать!`,
  weSupportOnlyTheFollowingFileExtensions: `Мы поддерживаем только следующие расширения файлов:`,
  work: `Работа`,
  weWouldLoveToHearFromYou: `Будем рады обратной связи от вас`,
  workDescription: `Описание работы`,
  leaveAReview: `Оставить отзыв`,
  wrongEmailOrPassword: `Неправильный email или пароль`,
  yes: `да`,
  yesterday: `Вчера`,
  youReceivedANewOrderFrom: (...v) => `Вы получили новый заказ от <b>${v[0]}</b>`,
  youReceivedAReview: `Вы получили отзыв`,
  reply: `Ответить`,
  youHaveSuccessfullyCreatedYourShop: `Вы успешно создали свой магазин`,
  replyToUsername: (...v) => `Ответить ${v[0]}`,
  numOfReplies: (...v) => `Ответов: ${v[0]}`,
  numOfNewComments: (...v) => `Новых комментариев: ${v[0]}`,
  numOfNewReactions: (...v) => `Новых реакций: ${v[0]}`,
  replies: `Ответы`,
  youAreAlreadyAuthenticated: `Вы уже авторизованы`,
  youCanAutoPublishToYourSocialMediaAccount: `Вы можете автопубликовать информацию в своих социальных сетях`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Вы можете изменить типы уведомлений, которые вы получаете по электронной почте`,
  youCanRequestRemovalOfYourAccount: `Вы можете запросить удаление своей учетной записи со всеми своими данными`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `Ваш отзыв помогает покупателям и помогает продавцам предлагать лучшие продукты`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Вы по-прежнему можете переходить на ранее открытые страницы`,
  youCanChooseFromTheListOrEnterACustomReason: `Выберите причину из списка или укажите свою`,
  youDidNotSelectAnyChats: `Вы не выбрали ни одного чата`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `Вы увидите отзывы здесь, как только покупатели поделятся своим опытом`,
  youDidNotUpdateAnyValues: `Вы не обновили никаких значений`,
  youDoNotHaveAnyChats: `У вас нет чатов`,
  youHaveNotSetAPassword: `Вы не добавили пароль`,
  youHaveNotSharedAnythingYet: `Вы ещё ничем не поделились`,
  youHaveReachedTheMaximumNumberOfFiles: `Вы достигли максимального количества файлов`,
  kindlyHoldOnForTheBuyersReview: `Пожалуйста, подождите, пока покупатель оставит отзыв`,
  yourAccountIsVerifiedPleaseSignIn: `Ваш аккаунт подтвержден. Теперь вы можете войти`,
  yourAccountWillBeRemoved: (...v) => `Ваша учетная запись будет удалена ${v[0]}`,
  youHaveNoPurchases: `У Вас пока нет покупок`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Могли бы вы, пожалуйста, указать причину отмены`,
  yourArts: `Ваши арты`,
  youCanceledTheOrder: `Вы отменили заказ`,
  yourAvatar: `Ваш аватар`,
  yourBlog: `Ваш блог`,
  yourFansAreWaiting: `Ваши поклонники ждут`,
  yourFeedIsEmpty: `Ваша лента пуста`,
  yourSessionHasExpiredPleaseSignInAgain: `Срок действия вашей сессии истёк, повторите вход`,
}
