export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Сведения`,
  accept: `Принять`,
  accountActivation: `Активация учетной записи`,
  accountAlreadyExists: `Учетная запись уже существует`,
  accountDoesNotExist: `Учетная запись не существует`,
  add: `Добавить`,
  addArt: `Добавить арт`,
  addBlog: `Добавить блог`,
  addedNAgo: (n) => `Добавлено ${n} назад`,
  addMore: `(en) Add more`,
  addNewArt: `Добавить новый арт`,
  addPreview: `Добавить превью`,
  addSignInVia: `Добавить Войти с помощью`,
  advancedOptions: `(en) Advanced options`,
  all: `Все`,
  alreadySignedIn: `Уже авторизованы`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (n) => `(en) Amount should not be less than $${n}`,
  animeArtByArtistsFromAllOverTheWorld: `Аниме арты от художников со всего мира. Арты проверяются на связь с аниме. Галерея аниме артов это бесконечный список лучших арт работ`,
  animeArtSubscribeToArtistsLikeAndCreate: `Аниме арты - подпишитесь на художников и создавайте коллекции`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - первая платформа, предлагающая заработок на просмотрах от Google AdSense. Поддержи художников, просматривая их контент, или начни зарабатывать на просмотрах`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - смотри, добавляй и зарабатывай на аниме-контенте`,
  animeCommunity: `Аниме-сообщество`,
  animeOnly: `Только аниме`,
  apply: `Применить`,
  appsVersionIs: `Версия приложения`,
  areYouSureYouWantTo: `Вы уверены, что хотите`,
  art: `Арт`,
  artAssociatedWithAnime: `Арт связан с аниме`,
  artBy: `Автор`,
  artCannotBeChanged: `Арт не может быть изменен`,
  authenticationFailed: `Аутентификация не прошла`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `Назад`,
  blog: `Блог`,
  bookmarks: `Закладки`,
  browseArt: `Смотреть арты`,
  cancel: `отменить`,
  cannotStartWithChars: `Не может начинаться с s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  changeArt: `Изменить арт`,
  changeAvatar: `Изменить аватар`,
  changePassword: `Изменить пароль`,
  chooseExistingChatOrStartANewOne: `Выберите одно из своих сообщений или напишите новое`,
  city: `Город`,
  clearAll: `Очистить всё`,
  close: `Закрыть`,
  comingSoon: `Скоро...`,
  community: `Сообщество`,
  confirmAccount: `Подтвердить учетную запись`,
  confirmPassword: `Подтвердить пароль`,
  contactInformation: `(en) Contact information`,
  contractTitle: `(en) Contract Title`,
  copyLink: `Скопировать ссылку`,
  couldNotCreateANewRecord: `Не удалось создать новую запись`,
  country: `Страна`,
  createANewAccountFailed: `Создать новую учетную запись не удалось`,
  createNewAccount: `Создать новую учетную запись`,
  delete: `Удалить`,
  deleteArt: `Удалить арт`,
  deletePost: `Удалить запись`,
  description: `Описание`,
  details: `Подробности`,
  didntReceiveEmail: `Не получили email?`,
  donations: `Пожертвования`,
  done: `Выполнено`,
  drawingContest: `Арт соревнование`,
  dueDate: `(en) Due date`,
  earningFromArts: `Заработок на артах`,
  edit: `Изменить`,
  editPost: `Редактировать запись`,
  editProfile: `Редактировать профиль`,
  editTranslations: `Редактировать переводы`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email уже используется другим аккаунтом`,
  emailSubscription: `Email подписка`,
  enterOrPasteALink: `Скопируйте или вставьте ссылку`,
  error404NotFound: `Ошибка 404 - не найдено`,
  errorPleaseContactCustomerSupport: `Ошибка! Пожалуйста, свяжитесь со службой поддержки...`,
  exitEditor: `Выйти из редактора`,
  extensions: `Расширения`,
  fileSizeIsTooBig: `Слишком большой размер файла`,
  filter: `Фильтр`,
  filterBy: `Отфильтровать по`,
  findUser: `Найти пользователя`,
  follow: `Подписаться`,
  followers: `Подписчиков`,
  following: `Подписок`,
  followMeOn: `Подпишитесь на меня в`,
  followUsOnTwitter: `Подпишитесь на нас в твиттере`,
  forAllOtherInquiriesPleaseContactUsAt: `По всем остальным вопросам, пожалуйста, свяжитесь через:`,
  forgotPassword: `Забыли пароль`,
  forNewMasterpieces: `Для новых шедевров`,
  four04: `— 404! —`,
  getDetails: `Подробнее`,
  guestView: `Гостевой просмотр`,
  hire: `(en) Hire`,
  homepage: `Главная`,
  howToContactYou: `(en) How to contact you`,
  iAgreeWith: `Я согласен с`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Высота изображения должна быть больше или равна`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Ширина изображения должна быть больше или равна`,
  introduction: `Введение`,
  invalidCode: `Недействительный код`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `Неправильная часть после @`,
  invalidPartBeforeAt: `Неправильная часть до @`,
  jobDetails: `(en) Job Details`,
  joinChat: `Присоединиться к чату`,
  joinUsOnFacebook: `Присоединяйтесь к нам на Facebook`,
  languages: `Языки`,
  likes: `Отметки «Нравится»`,
  linkCopiedToClipboard: `Ссылка скопирована в буфер обмена`,
  livingIn: `Регион`,
  location: `Локация`,
  logout: `Выход из системы`,
  maximumNChars: (n) => `Максимум ${n} символов`,
  maxSize: `Макс. размер`,
  menu: `Меню`,
  message: `Сообщение`,
  messages: `Сообщения`,
  minHeight: `Мин. высота`,
  minimumNChars: (n) => `Минимум ${n} символов`,
  minWidth: `Мин. ширина`,
  moreFrom: (n) => `Также от ${n}`,
  mustBeNChars: (n) => `Должно быть ${n} символов`,
  need1Lowercase: `Нужна 1 маленькая буква`,
  need1Number: `Нужна 1 цифра`,
  need1Uppercase: `Нужна 1 заглавная буква`,
  needAtLeast1CharacterFromN: (n) => `Нужен как минимум 1 символ из [${n}]`,
  needNCharacter: (n) => `Нужен ${n} символ`,
  newAccount: `Новая учетная запись`,
  newArt: `Новый арт`,
  newBlog: `Новый блог`,
  newPassword: `Новый пароль`,
  newsFeed: `Новостная лента`,
  no: `нет`,
  noAddedFavoriteArts: `нет добавленных избранных артов`,
  noInternetConnection: `Нет подключения к интернету!`,
  notifications: `Уведомления`,
  nsfwContent18Plus: `Материал для взрослых (18+)`,
  ohNoItIsNotHere: `О нет! Этого здесь нет!`,
  oldPassword: `Старый пароль`,
  online: `Онлайн`,
  onlyHexNumbersStartsWithTChar: `Только hex числа [0-9a-fA-F], начинающиеся с символа 't'`,
  onlyLatinLettersNumbersOrSpecialSymbols: `Только латинские буквы, цифры, специальные символы`,
  onlyNumbers: `Только цифры`,
  open: `Открыть`,
  openGuestView: `Открыть гостевой просмотр`,
  openingSoon: `Скоро открытие!`,
  openToWork: `Открыт к работе`,
  optional: `(en) Optional`,
  or: `или`,
  password: `Пароль`,
  payments: `Платежи`,
  pleaseCheckYour: `Пожалуйста, проверьте ваш`,
  pleaseDropOnlyOneImage: `Пожалуйста, поместите только одно изображение`,
  pleaseEnterAtLeastNChars: (n) =>
    `Пожалуйста, введите не менее ${n} символов `,
  pleaseFillOutYourDetails: `Пожалуйста, заполните ваши данные`,
  pleaseSignInToYourAccount: `Пожалуйста, войдите в свою учетную запись`,
  pleaseTryAgainOrClick: (n) => `Пожалуйста, повторите или нажмите ${n}`,
  pleaseVerifyYourAccount: `Пожалуйста, подтвердите свою учетную запись`,
  pressHereTo: `Нажмите здесь, чтобы`,
  privacyPolicy: `Политика конфиденциальности`,
  profile: `Профиль`,
  publishOn: (n) => `(en) Publish on ${n}`,
  save: `Сохранить`,
  saveAvatar: `Сохранить аватар`,
  saveChanges: `Сохранить изменения`,
  selectAnime: `Выберите Аниме`,
  selectAvatar: `Выберите аватар`,
  selectCharacters: `Выберите персонажа(ей)`,
  selectFile: `Выберите файл`,
  selectThumbnail: `Выберите миниатюру`,
  sendEmail: `Отправить email`,
  settings: `Настройки`,
  shareYourStory: `Поделитесь своей историей!`,
  shop: `Магазин`,
  showLess: `Свернуть`,
  showMore: `Ещё`,
  signIn: `Войти в систему`,
  skip: `Пропустить`,
  socialMedia: `Социальные сети`,
  spaceCharacterIsNotAllowed: `Символ пробела не допускается`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Подпишитесь на создателей, чтобы следить за их прогрессом`,
  successChangedPasswordPleaseSignIn: `Успешно! Пароль изменен. Пожалуйста, войдите в систему`,
  successCreatedRecord: `Успешно! Запись создана!`,
  successUpdatedRecord: `Успешно! Запись обновлена!`,
  supportMeOn: `Поддержите меня на`,
  tellUsAboutYourself: `Расскажите нам о себе`,
  termsAndConditions: `Положения и условия`,
  termsOfUse: `Условия использования`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `Название`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `Введите свой текст здесь...`,
  upload: `(en) Upload`,
  uploadAnotherArt: `Загрузить другой арт`,
  uploadAnotherAvatar: `Загрузить другой аватар`,
  uploadArtNow: `Загрузите арт сейчас!`,
  uploadNew: `Загрузить новый`,
  uploadNewArt: `Загрузить новый арт`,
  uploadNewPost: `Загрузить новую запись`,
  username: `Логин`,
  usernameAlreadyExists: `Логин уже существует`,
  valueIsNotTheSame: `Значение не одинаково`,
  verificationCode: `Код проверки`,
  verifyCode: `Подтвердить код`,
  visitOurDiscordChannelToGetMoreDetails: `Посетите наш Discord канал для подробностей`,
  weAreOnInstagram: `Мы в Инстаграме`,
  weAreWorkingOnIt: `Мы работаем над этим`,
  weDoNotDisplayNSFWContentYet: `Мы пока не отображаем материал для взрослых`,
  weHaveSentTooManyVerificationEmails: `Мы отправили слишком много email'ов с проверкой, пожалуйста, попробуйте еще раз через несколько минут`,
  welcomeToAnimeClub: `Добро пожаловать на Anime.club!`,
  weSentAnEmailTo: `Мы отправили email на:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Мы отправили вам новый email с подтверждением. Пожалуйста, введите код`,
  weSupportOnlyTheFollowingFileExtensions: `Мы поддерживаем только следующие расширения файлов:`,
  work: `Работа`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `Неправильный емайл или пароль`,
  yes: `да`,
  youAreAlreadyAuthenticated: `Вы уже аутентифицированы`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Вы все еще можете перейти к ранее открытым страницам`,
  youDidNotSelectAnyChats: `Вы не выбрали сообщение`,
  youDidNotUpdateAnyValues: `Вы не обновили никаких значений`,
  youDoNotHaveAnyChats: `У Вас нет сообщений`,
  youHaveNotSavedAnyChanges: `Вы не сохранили никаких изменений`,
  yourAccountIsVerifiedPleaseSignIn: `Ваша учетная запись верифицирована. Пожалуйста, войдите в систему`,
  yourArts: `Ваши арты`,
  yourAvatar: `Ваш аватар`,
  yourBlog: `Ваш блог`,
  yourFansAreWaiting: `Ваши фанаты ждут`,
  yourFeedIsEmpty: `Ваша лента пуста`,
  yourSessionHasExpiredPleaseSignInAgain: `Ваш сеанс истёк, пожалуйста, войдите в систему ещё раз`,
}
