export const text: text = {
  accountDeleted: `(en) Account deleted`,
  leaveAReview: `(en) Leave a review`,
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Сведения`,
  accept: `Принять`,
  acceptOrder: `Принять заказ`,
  account: `Аккаунт`,
  accountActivation: `Активация аккаунта`,
  accountAlreadyExists: `Аккаунт уже существует`,
  accountDoesNotExist: `Аккаунт не существует`,
  accountRemoval: `Удаление аккаунта`,
  add: `Добавить`,
  addArt: `Добавить арт`,
  addBlog: `Добавить блог`,
  addFile: `Добавить файл`,
  additionalResources: `Дополнительные материалы`,
  addMore: `Добавить ещё`,
  addNewArt: `Добавить новый арт`,
  addPreview: `Добавить превью`,
  addSignInVia: `Добавить вход через`,
  addToCart: `Добавить в корзину`,
  advancedOptions: `Дополнительные параметры`,
  all: `Все`,
  alreadySignedIn: `Уже авторизованы`,
  amount: `Сумма`,
  amountShouldNotBeLessThan: (...v) => `Сумма не должна быть меньше $${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Это коллекция аниме-артов, которые созданы талантливыми художниками из разных уголков мира. Арты проверяются на соответствие аниме-стилю. Наша галлерея - это бесконечный список лучших аниме работ.`,
  animeArtSubscribeToArtistsLikeAndCreate: `Аниме арты - подписывайтесь на художников, оценивайте и создавайте коллекции`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - первая платформа, предлагающая художникам оплату за просмотры через Google AdSense. Поддержите художников, просматривая их контент или начните зарабатывать на просмотрах.`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - просматривайте, размещайте и зарабатывайте на аниме-контенте.`,
  animeCommunity: `Аниме-сообщество`,
  animeDotclubNeverAsksForYourPrivateInformation: `Сотрудники Anime.club никогда не запрашивают вашу личную информацию`,
  animeSocialNetwork: `Аниме.club
Социальная сеть`,
  announcements: `Объявления`,
  apply: `Применить`,
  appSettings: `Настройки приложения`,
  appsVersionIs: `Версия приложения`,
  areYouSureYouWantTo: `Вы уверены, что хотите`,
  art: `Арт`,
  artAssociatedWithAnime: `Арт связан с аниме`,
  artBy: (...v) => `Арт от ${v[0]}`,
  artCannotBeChanged: `Арт нельзя изменить`,
  artworksAvailableToView: (...v) => `${v[0]} артов доступно для просмотра`,
  authenticationFailed: `Ошибка аутентификации`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Автопубликация в Instagram доступна только для бизнес-аккаунтов Instagram`,
  awaitingReview: `Ожидает проверки`,
  awaitingSeller: `Ожидает продавца`,
  back: `Назад`,
  basePrice: `Исходная стоимость`,
  block: `Блокировать`,
  blockUser: (...v) => `Заблокировать @${v[0]}`,
  blog: `Блог`,
  bookmarks: `Закладки`,
  browseArt: `Посмотреть арты`,
  browseShop: `Открыть магазин`,
  cancel: `отмена`,
  canceled: `Отменен`,
  cancelOrder: `Отменить заказ`,
  cannotStartWithChars: `Не может начинаться с s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Изменить`,
  checkOrderStatus: `Проверить статус заказа`,
  changeArt: `Изменить арт`,
  changeAvatar: `Изменить аватар`,
  changeEmail: `Изменить email`,
  changePassword: `Изменить пароль`,
  chooseExistingChatOrStartANewOne: `Выберите существующий чат или начните новый`,
  city: `Город`,
  clearAll: `Очистить всё`,
  clientReview: `Отзыв клиента`,
  close: `Закрыть`,
  colorTheme: `Цветовая тема`,
  comingSoon: `Скоро...`,
  commercialUse: `Коммерческое использование`,
  community: `Сообщество`,
  completed: `Завершен`,
  confirmAccount: `Подтвердить аккаунт`,
  confirmOrder: `Подтвердить заказ`,
  confirmPassword: `Подтвердить пароль`,
  connectWithUsOn: `Свяжитесь с нами в`,
  contactCustomer: `Связаться с клиентом`,
  contactInformation: `Контактная информация`,
  contactSeller: `Связаться с продавцом`,
  contactSupport: `Связаться со службой поддержки`,
  continue: `Продолжить`,
  contractTitle: `Название контракта`,
  copyLink: `Скопировать ссылку`,
  congratulations: `Поздравляем!`,
  copyrightViolation: `Нарушение авторских прав`,
  couldNotCreateANewRecord: `Не удалось создать новую запись`,
  country: `Страна`,
  cover: `Обложка`,
  createANewAccountFailed: `Не удалось создать новый аккаунт`,
  createExtrasForYourProduct: `Создайте дополнительные услуги для вашего продукта`,
  createNewAccount: `Создать новый аккаунт`,
  createYourShop: `Создайте свой магазин`,
  currentPassword: `Текущий пароль`,
  daily: `Ежедневно`,
  darkDefault: `Темная тема`,
  darkHighContrast: `Темная тема высокого контраста`,
  dayTheme: `Дневная тема`,
  delete: `Удалить`,
  deleteShop: `Удалить магазин`,
  deleteAccount: `Удалить аккаунт`,
  deleteArt: `Удалить арт`,
  decline: `Отклонить`,
  deletePost: `Удалить запись`,
  deleteProduct: `Удалить продукт`,
  deliveryTime: `Срок доставки`,
  describeTheDetailsOfYourProduct: `Опишите детали вашего продукта`,
  description: `Описание`,
  details: `Подробности`,
  didntReceiveEmail: `Не получили email?`,
  displayName: `Отображаемое имя`,
  disputed: `Оспаривается`,
  donations: `Пожертвования`,
  done: `Готово`,
  dragAndDropOrSelectFiles: `Перетащите файлы или нажмите для выбора`,
  drawingContest: `Конкурс рисунков`,
  dueDate: `Срок сдачи`,
  earlier: `Раньше`,
  earningFromArts: `Заработок на артах`,
  edit: `Редактировать`,
  editPost: `Редактировать запись`,
  editProfile: `Редактировать профиль`,
  editTranslations: `Помочь с переводом`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email уже используется другим аккаунтом`,
  emailNotifications: `Email уведомления`,
  enterOrPasteALink: `Введите или вставьте ссылку`,
  enterTheAddressAssociatedWithYourAccount: `Введите email, связанный с вашим аккаунтом`,
  enterYourPassword: `Введите пароль`,
  error: `Ошибка`,
  errorPleaseContactCustomerSupport: `Ошибка! Свяжитесь со службой поддержки...`,
  exitWithoutSaving: `Выйти без сохранения`,
  extensions: `Расширения`,
  extras: `Дополнительные услуги`,
  fileSizeIsTooBig: `Размер файла слишком большой`,
  filter: `Фильтр`,
  filterBy: `Фильтровать по`,
  findUser: `Найти пользователя`,
  finishSettingUpYourShop: `Завершите создание вашего магазина`,
  follow: `Подписаться`,
  followers: `Подписчиков`,
  following: `Подписок`,
  followMeOn: `Подпишитесь на меня в`,
  follows: `Подписки`,
  forAllOtherInquiriesPleaseContactUsAt: `По всем остальным вопросам, связь через:`,
  forgotPassword: `Не помню пароль`,
  fromAnimeDotClub: `От anime.club`,
  getDetails: `Подробнее`,
  getStarted: `Начать`,
  guestView: `Гостевой просмотр`,
  harassment: `Домогательство`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]} не добавил описание для "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} ещё не поделился публичными данными`,
  hate: `Ненависть`,
  hire: `Нанять`,
  homepage: `Главная`,
  howToContactYou: `Как с вами связаться`,
  howToFindYouOnOtherSocialNetworks: `Как найти вас в других социальных сетях`,
  iAgreeWith: `Я согласен с`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Высота изображения должна быть больше или равна`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Ширина изображения должна быть больше или равна`,
  impersonation: `Выдача себя за другого`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Укажите ключевые слова, которые покупатели, скорее всего, будут использовать для поиска продукта, подобного вашему`,
  inProgress: `В процессе`,
  introduction: `Введение`,
  invalidCode: `Неверный код`,
  invalidCurrentPassword: `Неверный текущий пароль`,
  invalidDate: `Неверная дата`,
  invalidPartAfterAt: `Недопустимая часть после @`,
  invalidPartBeforeAt: `Недопустимая часть перед @`,
  jobDetails: `Подробности о работе`,
  joinAnimeClubCommunity: `Присоединяйтесь к сообществу Anime.club с тысячами активных креаторов и крутыми аниме-артами каждый день`,
  joinChat: `Присоединиться к чату`,
  joinUsOnFacebook: `Присоединяйтесь к нам на Facebook`,
  language: `Язык`,
  languages: `Языки`,
  letEveryoneKnowHowToDonateToYou: `Дайте всем знать, как вам донатить`,
  letOthersKnowAboutYou: `Дайте другим знать о себе`,
  letsUploadYourFirstProduct: `Давайте загрузим ваш первый продукт`,
  letUsKnowWhatsHappening: `Сообщите нам, что происходит, и мы разберемся`,
  licenseForForProfitBusinessUse: `Лицензия для коммерческого использования`,
  lightDefault: `Светлая тема`,
  lightHighContrast: `Светлая тема высокого контраста`,
  likes: `Нравится`,
  linkCopiedToClipboard: `Ссылка скопирована в буфер обмена`,
  livesIn: `Проживает в`,
  loading: `Загрузка`,
  location: `Местоположение`,
  logInOrSignUp: `Войдите или зарегистрируйтесь`,
  logOut: `Выйти`,
  maximumNChars: (...v) => `Максимум символов: ${v[0]}`,
  maximumNumberOfDaysToCompleteTheOrder: `Максимальное количество дней для выполнения заказа`,
  maximumQuantity: `Максимальное количество`,
  maxSize: `Максимальный размер`,
  menu: `Меню`,
  message: `Сообщение`,
  messages: `Сообщения`,
  minHeight: `Минимальная высота`,
  minimumNChars: (...v) => `Минимум символов: ${v[0]}`,
  minorAbuseOrSexualization: `Насилие или сексуализация несовершеннолетних`,
  minWidth: `Минимальная ширина`,
  monthly: `Ежемесячно`,
  moreFrom: (...v) => `Больше от ${v[0]}`,
  mustBeNChars: (...v) => `Должно быть символов: ${v[0]}`,
  myPayments: `Мои платежи`,
  myProfile: `Мой профиль`,
  mySettings: `Мои настройки`,
  need1Lowercase: `Требуется 1 строчная буква`,
  need1Number: `Требуется 1 число`,
  need1Uppercase: `Требуется 1 прописная буква`,
  needAtLeast1CharacterFromN: (...v) =>
    `Требуется не менее 1 символа из [${v[0]}]`,
  needNCharacter: (...v) => `Требуется ${v[0]} символ`,
  newAccount: `Новый аккаунт`,
  newArt: `Новый арт`,
  newArtworks: `Новые арты`,
  newBlog: `Новый блог`,
  newOrder: `Новый заказ`,
  newPassword: `Новый пароль`,
  newProduct: `Новый продукт`,
  newsFeed: `Лента новостей`,
  next: `Продолжить`,
  nextTimeYouAuthenticateYouCouldUseThe: `В следующий раз вы можете использовать подключенный аккаунт вместо логина и пароля`,
  nightTheme: `Ночная тема`,
  no: `нет`,
  noAddedFavoriteArts: `добавленных артов в избранное нет`,
  noInternetConnection: `Подключение к Интернету отсутствует!`,
  nonConsensualIntimateContent: `Несогласованный интимный контент`,
  none: `Нет`,
  noNotifications: `Нет уведомлений`,
  noResults: `Нет результатов`,
  notifications: `Уведомления`,
  noActiveOrdersToShow: `Нет активных заказов для отображения`,
  nsfwContent18Plus: `Материалы для взрослых (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `Количество корректировок, которые клиент может запросить`,
  online: `В сети`,
  onlyLatinLettersNumbersHyphen: `Только латинские буквы, цифры, дефис, подчеркивание и точка`,
  onlyNumbers: `Только числа`,
  open: `Открыть`,
  openDispute: `Открыть спор`,
  openGuestView: `Открыть вид для гостей`,
  openingSoon: `Скоро открытие!`,
  openToWork: `Открыт для работы`,
  optional: `Необязательно`,
  or: `или`,
  ordered: (...v) => `Заказано ${v[0]}`,
  orderAgain: `Заказать снова`,
  orderDetails: `Детали заказа`,
  orderStatus: `Статус заказа`,
  orderOptions: `Варианты заказа`,
  pageNotFound: `Страница не найдена`,
  password: `Пароль`,
  payments: `Платежи`,
  personal: `Личное`,
  pleaseCheckYour: (...v) => `Проверьте ваш ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Пожалуйста, не сообщайте свою личную информацию другим`,
  pleaseDropOnlyOneImage: `Перетащите сюда только одно изображение`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `Введите число от ${v[0]} до ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `Введите символов, не менее ${v[0]} `,
  pleaseFillOutYourDetails: `Заполните свои данные`,
  pleaseSignInToYourAccount: `Войдите в свой аккаунт`,
  pleaseTryAgainOrClick: (...v) => `Повторите или нажмите ${v[0]}`,
  pleaseVerifyYourAccount: `Подтвердите свой аккаунт`,
  pressHereTo: `Нажмите здесь, чтобы`,
  price: `Цена`,
  privacyPolicy: `Политика конфиденциальности`,
  privateInformation: `Личная информация`,
  proceedToCheckout: `Перейти к оформлению заказа`,
  product: `Продукт`,
  profile: `Профиль`,
  prohibitedTransaction: `Запрещенная транзакция`,
  promotions: `Акции`,
  publicInformation: `Публичная информация`,
  publishOn: (...v) => `Опубликовать на ${v[0]}`,
  purchases: `Покупки`,
  rankings: `Рейтинги`,
  reorderFiles: `Изменить порядок файлов`,
  report: `Пожаловаться`,
  revisions: `Корректировки`,
  sales: `Продажи`,
  save: `Сохранить`,
  saveAvatar: `Сохранить аватар`,
  saveChanges: `Сохранить изменения`,
  selectAnime: `Выбрать аниме`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Выберите одну тему или синхронизируйте с вашей системой и автоматически переключайтесь между дневной и ночной темами`,
  selectAvatar: `Выбрать аватар`,
  selectCharacters: `Выбрать персонажей`,
  selectFile: `Выбрать файл`,
  selectTheme: `Выбрать тему`,
  selectThumbnail: `Выбрать миниатюру`,
  selfHarmOrSuicide: `Нанесение вреда себе или суицид`,
  sendEmail: `Отправить email`,
  settings: `Настройки`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Создание магазина бесплатно и занимает всего несколько минут`,
  share: `Поделиться`,
  shareYourArtWithTheWorld: `Поделитесь своими творениями с миром`,
  shareYourStory: `Поделитесь своей историей!`,
  sharingPersonalInformation: `Раскрытие личной информации`,
  shop: `Магазин`,
  shopOrders: `Заказы магазина`,
  showLess: `Свернуть`,
  showMore: `Показать больше`,
  signIn: `Войти`,
  singleTheme: `Одна тема`,
  size: `Размер`,
  skip: `Пропустить`,
  socialMedia: `Социальные сети`,
  spaceCharacterIsNotAllowed: `Пробел не допускается`,
  spam: `Спам`,
  submitAReport: `Отправить жалобу`,
  submitWork: `Отправить работу`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Подпишитесь на художников, чтобы отслеживать их успехи`,
  successChangedPasswordPleaseSignIn: `Пароль успешно изменён. Войдите`,
  successCreatedRecord: `Запись успешно создана!`,
  successUpdatedRecord: `Запись успешно обновлена!`,
  supportMeOn: `Поддержите меня на`,
  syncWithSystem: `Синхронизировать с системой`,
  tellUsAboutYourself: `Расскажите нам о себе`,
  termsAndConditions: `Правила и условия`,
  termsOfUse: `Условия использования`,
  thankYouForReport: `Спасибо за помощь в поддержании безопасного и уважительного онлайн-сообщества`,
  theLinkIsBrokenOrPageHasBeenRemoved: `Ссылка не работает или страница была удалена`,
  themeMode: `Режим темы`,
  thisIsThePriceYouPropose: `Это цена, которую вы предлагаете`,
  threateningViolence: `Угрозы насилия`,
  title: `Название`,
  titleYourExtraService: `Назовите вашу дополнительную услугу`,
  theMaximumQuantityThatACustomerCanAdd: `Максимальное количество, которое покупатель может добавить`,
  toHelpTheCreatorCompleteYourOrder: `Для того чтобы продавец мог выполнить ваш заказ в соответствии с вашими пожеланиями, пожалуйста, укажите подробно, что именно вы хотели бы получить: укажите тему, стиль, особенности персонажа и другие важные детали.`,
  today: `Сегодня`,
  toGetWorkRelatedNotifications: `Для получения уведомлений, связанных с работой`,
  total: `Итого`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Чтобы посмотреть эти данные, вам нужно разблокировать @${v[0]}`,
  trademarkViolation: `Нарушение товарного знака`,
  typeYourTextHere: `Напечатайте здесь свой текст...`,
  unblock: `Разблокировать`,
  unblockUser: (...v) => `Разблокировать @${v[0]}`,
  unfollow: `Отписаться`,
  unlimited: `Неограниченно`,
  upload: `Загрузить`,
  uploadNew: `Загрузить новый`,
  uploadNewPost: `Загрузить новую запись`,
  uploadNewProduct: `Загрузить новый продукт`,
  username: `Логин`,
  usernameAlreadyExists: `Такой логин уже используется`,
  usernameAndXMoreFollowYou: (...v) =>
    `<b>${v[0]}</b> и ещё ${v[1]} подписаны на вас`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `<b>${v[0]}</b> и ещё ${v[1]} нравится ваш арт`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b> подписан на вас`,
  usernameLikesYourArt: (...v) => `<b>${v[0]}</b> нравится ваш арт`,
  useThisEmailTo: `Используйте этот email для: аутентификации, получения уведомлений`,
  valueIsNotTheSame: `Значение не совпадает`,
  verificationCode: `Проверочный код`,
  verifyCode: `Проверить код`,
  viewDetails: `Подробнее`,
  viewReview: `Просмотреть отзыв`,
  viewEveryNotificationOfAGroupSeparately: `Просмотр каждого уведомления группы отдельно`,
  visitOurDiscordChannelToGetMoreDetails: `Посетите наш канал Discord для получения более подробной информации`,
  weAreOnInstagram: `Мы в Instagram`,
  weAreWorkingOnIt: `Мы работаем над этим`,
  weDoNotDisplayNSFWContentYet: `Мы пока не показываем материалы для взрослых`,
  weekly: `Еженедельно`,
  whenYouPurchaseSomethingItWillAppearHere: `Когда вы что-то купите, оно появится здесь`,
  weHaveSentTooManyEmails: `Мы отправили слишком много писем, попробуйте позже или свяжитесь со службой поддержки`,
  welcomeToAnimeClub: `Добро пожаловать в Anime.club!`,
  weSentAnEmailTo: `Мы отправили email на:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Мы отправили вам новый email с подтверждением. Введите код`,
  weSupportOnlyTheFollowingFileExtensions: `Мы поддерживаем только следующие расширения файлов:`,
  work: `Работа`,
  workDescription: `Описание работы`,
  wrongEmailOrPassword: `Неправильный email или пароль`,
  yes: `да`,
  yesterday: `Вчера`,
  youHaveSuccessfullyCreatedYourShop: `Вы успешно создали свой магазин`,
  youAreAlreadyAuthenticated: `Вы уже авторизованы`,
  youCanAutoPublishToYourSocialMediaAccount: `Вы можете автопубликовать информацию в своих социальных сетях`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Вы можете изменить типы уведомлений, которые вы получаете по электронной почте`,
  youCanRequestRemovalOfYourAccount: `Вы можете запросить удаление своей учетной записи со всеми своими данными`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Вы по-прежнему можете переходить на ранее открытые страницы`,
  youDidNotSelectAnyChats: `Вы не выбрали ни одного чата`,
  youDidNotUpdateAnyValues: `Вы не обновили никаких значений`,
  youDoNotHaveAnyChats: `У вас нет чатов`,
  youHaveNotSetAPassword: `Вы не добавили пароль`,
  youHaveNotSharedAnythingYet: `Вы ещё ничем не поделились`,
  youHaveReachedTheMaximumNumberOfFiles: `Вы достигли максимального количества файлов`,
  yourAccountIsVerifiedPleaseSignIn: `Ваш аккаунт подтвержден. Теперь вы можете войти`,
  yourAccountWillBeRemoved: (...v) =>
    `Ваша учетная запись будет удалена ${v[0]}`,
  youHaveNoPurchases: `У вас нет покупок`,
  yourArts: `Ваши арты`,
  yourAvatar: `Ваш аватар`,
  yourBlog: `Ваш блог`,
  yourFansAreWaiting: `Ваши поклонники ждут`,
  yourFeedIsEmpty: `Ваша лента пуста`,
  yourSessionHasExpiredPleaseSignInAgain: `Срок действия вашей сессии истёк, повторите вход`,
}
