export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _hyphen: `- `,
  _question: `? `,
  _space: ` `,
  about: `Sobre`,
  accept: `Aceptar`,
  acceptOrder: `Aceptar orden`,
  acceptTheOrder: `Aceptar el pedido`,
  account: `Cuenta`,
  accountActivation: `Activación de cuenta`,
  accountAlreadyExists: `La cuenta ya existe`,
  accountDeleted: `Cuenta eliminada`,
  accountDoesNotExist: `La cuenta no existe`,
  accountManagment: `Gestión de cuenta`,
  accountRemoval: `Eliminación de cuenta`,
  add: `Agregar`,
  addAComment: `Agregar un comentario`,
  addArt: `Agregar arte`,
  addBlog: `Agregar blog`,
  additionalResources: `Recursos adicionales`,
  addMore: `Agregar más`,
  addMoreProductsToYourShop: `Agrega más productos a tu tienda`,
  addNewArt: `Agregar arte nuevo`,
  addSignInVia: `Añadir inicio de sesión mediante`,
  addToCart: `Agregar al carrito`,
  advancedOptions: `Opciones avanzadas`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `Las imágenes generadas por IA y los filtros de redes neuronales están prohibidos`,
  all: `Todo`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `Todos los archivos que subas aquí estarán disponibles para el comprador`,
  allListings: `Todas las publicaciones`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `Todos los archivos relacionados con WIP deben subirse en mensajes`,
  alreadySignedIn: `Sesión iniciada`,
  amount: `Cantidad`,
  amountShouldNotBeLessThan: (...v) => `La cantidad no debe ser menor a ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Arte de anime por artistas de todo el mundo. El arte está curado para estar relacionado con el anime. La selección de arte es una lista infinita del mejor arte de anime.`,
  animeArtSubscribeToArtistsLikeAndCreate: `Arte de anime - suscríbete a artistas, dale me gusta y crea colecciones`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - la primera plataforma que ofrece pagos a los artistas a partir de las vistas a través de Google AdSense. Apoye a los artistas viendo su contenido o comience a ganar dinero con las vistas`,
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `Anime.club usa ${v[0]} para pagarte rápidamente y mantener segura tu información personal y de pago`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club: vea, publique y gane contenido de anime`,
  animeCommunity: `Comunidad de anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club nunca solicita su información privada`,
  animeShopBuyAndSellProducts: `Tienda de anime - compra y venta de productos`,
  animeSocialNetwork: `Red social de anime`,
  announcements: `Anuncios`,
  appearance: `Apariencia`,
  apply: `Aplicar`,
  appSettings: `Configuración de la aplicación`,
  appsVersionIs: `La versión de la aplicación es`,
  areYouSureYouWantTo: `Estás seguro que quieres`,
  art: `Arte`,
  artAssociatedWithAnime: `Arte asociado con el anime`,
  artBy: (...v) => `Arte por ${v[0]}`,
  artCannotBeChanged: `El arte no se puede cambiar`,
  artGallery: `Galería de arte`,
  artworksAvailableToView: (...v) => `${v[0]} obras de arte disponibles para ver`,
  attachedFiles: `Archivos adjuntos`,
  attentionYourOrderHasBeenDisputed: `¡Atención! Su pedido ha sido disputado. Por favor, verifique los detalles`,
  authenticationFailed: `Error de autenticación`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `La publicación automática en Instagram solo está disponible para cuentas comerciales de Instagram`,
  awaitingClientReview: `Esperando la revisión del cliente`,
  awaitingSellersResponse: `Esperando la respuesta del vendedor`,
  back: `Volver`,
  basePrice: `Precio base`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `Antes de aceptar, revisa cuidadosamente la solicitud del comprador`,
  beSpecificAboutTheContent: `Describe el contenido con precisión (por ejemplo, cantidad de archivos, formatos y resolución del lienzo)`,
  beTheFirstToShareYourThoughts: `Sé el primero en compartir tu opinión`,
  bigAppreciationToTheSellerForTheHardWork: `Gran agradecimiento al vendedor por el arduo trabajo`,
  block: `Bloquear`,
  blockUser: (...v) => `Bloquear a @${v[0]}`,
  blog: `Blog`,
  bookmarks: `Guardados`,
  browseArt: `Examinar arte`,
  browseShop: `Explorar tienda`,
  buyer: `Comprador`,
  buyerHasNotLeftAReviewYet: `El comprador aún no ha dejado una reseña`,
  buyerReviewedTheOrder: `El comprador revisó el pedido`,
  buyersRequest: `Solicitud del comprador`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `Los compradores podrán ver esta publicación. Puedes volver a ocultarla cuando quieras`,
  buyNow: `Comprar ahora`,
  cancel: `cancelar`,
  canceled: `Cancelado`,
  cancelOrder: `Cancelar pedido`,
  cannotStartWithChars: `No puedo empezar con s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Cambiar`,
  changeArt: `Cambiar arte`,
  changeAvatar: `Cambiar avatar`,
  changedMyMind: `Cambié de opinión`,
  changeEmail: `Cambiar correo electrónico`,
  changePassword: `Cambiar contraseña`,
  changesSaved: `¡Cambios guardados!`,
  checkOrderStatus: `Verificar estado del pedido`,
  checkOutMyShop: `Visita mi tienda`,
  chooseExistingChatOrStartANewOne: `Elija un chat existente o inicie uno`,
  city: `Ciudad`,
  clearAll: `Borrar todo`,
  clickTheButtonBelowToOpenYourStripeDashboard: `Haz clic en el botón de abajo para abrir tu panel de Stripe y consultar los detalles de tu cuenta`,
  close: `Cerrar`,
  color: `Color`,
  colorTheme: `Tema de color`,
  comingSoon: `Próximamente...`,
  comments: `Comentarios`,
  commercialUseAllowed: `Uso comercial permitido`,
  commercialUseAllowsBuyersToUseYourProduct: `El uso comercial permite a los compradores usar tu producto para fines comerciales, como vender o promocionar sus servicios`,
  commission: `Comisión`,
  commissions: `Comisiones`,
  community: `Comunidad`,
  completed: `Completado`,
  confirmAccount: `Confirmar cuenta`,
  confirmOrder: `Confirmar pedido`,
  confirmPassword: `Confirmar contraseña`,
  congratulations: `¡Felicidades!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `¡Felicidades por completar tu pedido exitosamente!`,
  connectWithUsOn: `Conéctate con nosotros en`,
  contactInformation: `Información de contacto`,
  contactSeller: `Contactar al vendedor`,
  contactSupport: `Contactar soporte`,
  contactUs: `Contáctenos`,
  continue: `Continuar`,
  contractTitle: `Título del contrato`,
  copiedToClipboard: `Copiado al portapapeles`,
  copy: `Copiar`,
  copyrightViolation: `Violación de derechos de autor`,
  couldNotCreateANewRecord: `No se pudo crear un nuevo registro`,
  couldYouPleaseProvideTheReasonForTheCancellation: `¿Podría proporcionar la razón de la cancelación?`,
  country: `País`,
  cover: `Portada`,
  createANewAccountFailed: `Fallo al crear una nueva cuenta`,
  createAShopWithStripe: `Crea una tienda con Stripe`,
  createdBy: `Creado por`,
  createExtrasForYourProduct: `Crear extras para tu producto`,
  createNewAccount: `Crear una nueva cuenta`,
  createPersonalizedWorkTailoredToEachRequest: `Crea trabajos personalizados adaptados a cada solicitud`,
  currentPassword: `Contraseña actual`,
  customWork: `Trabajo personalizado`,
  daily: `Diario`,
  dark: `Oscuro`,
  decline: `Rechazar`,
  delete: `Eliminar`,
  deleteAccount: `Eliminar cuenta`,
  deleteArt: `Eliminar arte`,
  deletePost: `Eliminar publicación`,
  deleteProduct: `Eliminar producto`,
  deleteShop: `Eliminar tienda`,
  deliveryTime: `Tiempo de entrega`,
  describeTheDetailsOfYourExtra: `Describe los detalles de tu extra`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `Describe qué incluye y qué puede esperar el comprador después de la compra`,
  description: `Descripción`,
  details: `Detalles`,
  didntReceiveEmail: `¿No recibió un correo electrónico?`,
  digitalDownloads: `Descargas digitales`,
  digitalDownloadsExamples: `Pinceles, recursos, tutoriales y más`,
  displayName: `Nombre de visualización`,
  disputed: `Disputado`,
  documentation: `Documentación`,
  donations: `Donaciones`,
  done: `Hecho`,
  download: `Descargar`,
  downloadThemBelow: `Descárgalos abajo`,
  dragAndDropOrSelectFiles: `Arrastra y suelta o selecciona archivo(s)`,
  drawingContest: `Concurso de dibujo`,
  dueDate: `Fecha de vencimiento`,
  earlier: `Anterior`,
  earningFromArts: `Ganar de las artes`,
  edit: `Editar`,
  editPost: `Editar tu publicación`,
  editProfile: `Editar tu perfil`,
  editTranslations: `Editar traducciones`,
  email: `Correo electrónico`,
  emailAlreadyUsedByAnotherAccount: `El correo electrónico ya es usado por otra cuenta`,
  emailNotifications: `Notificaciones por correo electrónico`,
  enjoyYourPurchase: `¡Disfruta tu compra! 😊`,
  ensureYouveUploadedTheFinalVersion: `Asegúrate de haber subido la versión final antes de enviar`,
  enterOrPasteALink: `Introduzca o pegue un enlace`,
  enterTheAddressAssociatedWithYourAccount: `Ingresa la dirección asociada con tu cuenta y te enviaremos un enlace para restablecer tu contraseña`,
  enterYourPassword: `Ingresa tu contraseña`,
  error: `Error`,
  errorPleaseContactCustomerSupport: `¡Error! Por favor, póngase en contacto con el servicio de atención al cliente...`,
  exitWithoutSaving: `Salir sin guardar`,
  extensions: `Extensiones`,
  extras: `Extras`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `Los extras son complementos opcionales para mejorar tu producto`,
  extrasHelpBoostIncome: `Los extras permiten a los compradores personalizar su pedido y pueden aumentar tus ingresos`,
  feedbackReceived: `¡Reseña recibida!`,
  feelFreeToShareReferenceImagesAndMaterials: `Siéntete libre de compartir imágenes y materiales de referencia para ayudar al artista a crear tu pieza`,
  files: `Archivos`,
  filesForPreview: `Archivos de vista previa`,
  filesForTheBuyer: `Archivos para el comprador`,
  fileSizeIsTooBig: `El tamaño del archivo es demasiado grande`,
  fileSizeIsTooSmall: `El tamaño del archivo es demasiado pequeño`,
  filter: `Filtrar`,
  filterBy: `Filtrar por`,
  findUser: `Buscar usuario`,
  finishSettingUpYourShop: `Termina de configurar tu tienda`,
  follow: `Seguir`,
  followers: `Seguidores`,
  following: `Siguiendo`,
  followMeOn: `Sigueme en`,
  follows: `Seguidores`,
  forAllOtherInquiriesPleaseContactUsAt: `Para todas las demás consultas, por favor contáctenos en:`,
  forgotPassword: `Olvidó su contraseña`,
  foundAnotherArtist: `Encontré a otro artista`,
  fromAnimeDotClub: `De anime.club`,
  getDetails: `Obtener detalles`,
  getStarted: `Empezar`,
  greatNewsBuyerPurchasedYourItemTimeToCelebrate: (...v) =>
    `¡Buenas noticias! ${v[0]} compró tu artículo. ¡Es hora de celebrarlo!`,
  greatNewsYourOrderIsNowInProgress: `¡Buenas noticias! Su pedido está en progreso`,
  guestView: `Vista de invitado`,
  harassment: `Acoso`,
  hasNotAddedADescriptionFor: (...v) => `@${v[0]} no ha agregado una descripción para "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) => `@${v[0]} aún no ha compartido detalles públicos`,
  hate: `Odio`,
  haveAnyQuestions: `¿Tiene alguna pregunta?`,
  hereAreAFewWaysToGetThingsRolling: `Aquí tienes algunas formas de empezar`,
  hide: `Ocultar`,
  hideListing: `Ocultar publicación`,
  hire: `Contratar`,
  homepage: `Página de inicio`,
  howToContactYou: `Cómo contactarte`,
  howToFindYouOnOtherSocialNetworks: `Cómo encontrarte en otras redes sociales`,
  iAgreeWith: `Estoy de acuerdo con`,
  id: `ID`,
  ifNoReplyIsReceivedByTimeLimitYouWillReceiveFullRefund: (...v) =>
    `Si no recibes respuesta antes de ${v[0]}, recibirás automáticamente un reembolso completo`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Si no hay respuesta para ${v[0]}, el pedido se marcará como completado automáticamente`,
  ifTheresNoResponseByTimeLimitOrderWillBeCanceled: (...v) =>
    `Si no hay respuesta antes de ${v[0]}, el pedido se cancelará automáticamente`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `Si tienes preguntas o inquietudes, contacta directamente al vendedor`,
  ifYouMissTheDeadlineBuyerCanCancelForFullRefund: `Si no cumples el plazo, el comprador puede cancelar el pedido y recibir un reembolso completo, y las comisiones de Stripe asociadas se descontarán de tu pago.`,
  ifYourArtIsNsfwCheckThisToAvoidAWarningOrBan: `Si tu arte es NSFW, asegúrate de marcar esta opción. De lo contrario, podrías recibir una advertencia que podría acabar en una suspensión.`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `La altura de la imagen debe ser mayor o igual que`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `El ancho de la imagen debe ser mayor o igual que`,
  impersonation: `Suplantación de identidad`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Incluye palabras clave que los compradores probablemente usarían para buscar un producto como el tuyo`,
  includes: `Incluye`,
  includesXRevisionS: (...v) => `Incluye ${v[0]} revisión(es)`,
  increaseContrast: `Aumentar contraste`,
  inProgress: `En progreso`,
  instantDownload: `Descarga inmediata`,
  introduction: `Introducción`,
  invalidCode: `Código inválido`,
  invalidCurrentPassword: `Contraseña actual inválida`,
  invalidDate: `Fecha inválida`,
  invalidPartAfterAt: `Pieza no válida después de @`,
  invalidPartBeforeAt: `Pieza no válida antes de @`,
  itemReviews: `Reseñas de artículos`,
  jobDetails: `Detalles del trabajo`,
  joinAnimeClubCommunity: `Únete a la comunidad de Anime.club con miles de creadores activos y arte de anime genial todos los días`,
  joinChat: `Unirse al chat`,
  joinUsOnFacebook: `Únete a nosotros en Facebook`,
  kindlyHoldOnForTheBuyersReview: `Por favor, espere la reseña del comprador sobre el pedido.`,
  lackOfInformation: `Falta de información`,
  language: `Idioma`,
  languages: `Idiomas`,
  leaveAReview: `Dejar una reseña`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `Indica si ofreces <b>revisiones</b> y cuántas`,
  letEveryoneKnowHowToDonateToYou: `Haz que todos sepan cómo donarte`,
  letOthersKnowAboutYou: `Haz que otros sepan sobre ti`,
  letsUploadYourFirstProduct: `Subamos su primer producto`,
  letUsKnowWhatsHappening: `Haznos saber qué está sucediendo y lo investigaremos`,
  light: `Claro`,
  likes: `Me gusta`,
  limit: `Límite`,
  listAnyContentOrRequestsYouDontAccept: `Enumera el contenido o las solicitudes que <b>no aceptas</b> (por ejemplo, material NSFW, político, religioso u ofensivo)`,
  listingHiddenFromBuyers: `Publicación oculta para los compradores`,
  listingIsNowVisibleToBuyers: `La publicación ya es visible para los compradores`,
  livesIn: `Viviendo en`,
  loading: `Cargando`,
  location: `Ubicación`,
  logInOrSignUp: `Iniciar sesión o registrarse`,
  logOut: `Cerrar sesión`,
  makeSureEverythingIsReadyToGoNoEditsAfterPublishing: `Asegúrate de que todo esté listo: no podrás editarlo después de publicarlo`,
  makeSureToIncludeClearInstructions: `Asegúrate de incluir instrucciones claras sobre cómo debe usarse cada referencia`,
  makeSureYouFullyUnderstandTheRequirements: `Asegúrate de entender completamente los requisitos y de poder completar el pedido antes de la fecha límite`,
  makeSureYourProductsArePricedCompetitively: `Asegúrate de que tus productos tengan precios competitivos`,
  maximumFileSize: (...v) => `Tamaño máximo: <b>${v[0]}</b> por archivo`,
  maximumNChars: (...v) => `Máximo ${v[0]} caracteres`,
  maximumNumberOfDaysToCompleteTheOrder: `Número máximo de días para completar el pedido`,
  maximumQuantity: `Cantidad máxima`,
  maxSize: `Tamaño máximo`,
  mentionYourDeliveryTimeInDays: `Indica tu <b>plazo de entrega</b> (en días)`,
  menu: `Menú`,
  message: `Mensaje`,
  messages: `Mensajes`,
  minHeight: `Altura mínima`,
  minimumDimensions: (...v) => `Tamaño mínimo: ${v[0]}×${v[1]} píxeles`,
  minimumNChars: (...v) => `Mínimo ${v[0]} caracteres`,
  minorAbuseOrSexualization: `Abuso o sexualización de menores`,
  minWidth: `Ancho mínimo`,
  monthly: `Mensual`,
  moreFrom: (...v) => `Más de ${v[0]}`,
  mustBeNChars: (...v) => `Debe tener ${v[0]} caracteres`,
  myPayments: `Mis pagos`,
  myProfile: `Mi perfil`,
  mySettings: `Mis ajustes`,
  need1Lowercase: `Necesita 1 minúscula`,
  need1Number: `Necesita 1 número`,
  need1Uppercase: `Necesita 1 mayúscula`,
  needAtLeast1CharacterFromN: (...v) => `Necesita al menos 1 carácter de [${v[0]}]`,
  needNCharacter: (...v) => `Debe tener ${v[0]} carácter`,
  needsYourReview: `Necesita tu revisión`,
  new: `Nuevo`,
  newAccount: `Nueva cuenta`,
  newArt: `Arte nuevo`,
  newArtworks: `Nuevas obras de arte`,
  newBlog: `Nuevo blog`,
  newCommission: `Nueva comisión`,
  newOrder: `Nuevo pedido`,
  newPassword: `Nueva contraseña`,
  newProduct: `Nuevo producto`,
  newsFeed: `Noticias`,
  next: `Siguiente`,
  nextTimeYouAuthenticateYouCouldUseThe: `La próxima vez que te autentiques, podrías usar la cuenta conectada en lugar del inicio de sesión y la contraseña`,
  no: `No`,
  noActiveOrdersToShow: `No hay pedidos activos para mostrar`,
  noCommentsJustYet: `Aún no hay comentarios`,
  noInternetConnection: `¡Sin conexión a Internet!`,
  nonConsensualIntimateContent: `Contenido íntimo no consensuado`,
  none: `Ninguno`,
  noNotifications: `Sin notificaciones`,
  noOrders: `No hay pedidos`,
  noResults: `Sin resultados`,
  noReviewsJustYet: `Aún no hay reseñas`,
  noSalesYetNoWorries: `¿Aún no tienes ventas? No te preocupes, acabas de empezar`,
  notAcceptingOrders: `No aceptando pedidos`,
  nothingIsChargedUntilTheSellerAccepts: `No se cobra nada hasta que el vendedor acepta, y si lo rechaza no se te cobra nada`,
  notifications: `Notificaciones`,
  nsfwContent18Plus: `Contenido NSFW (18+)`,
  NSFWIndicatesAdultContent: `18+ NSFW indica contenido para adultos. Marca este campo solo si tu producto es para adultos`,
  numberOfAdjustmentsAClientCouldRequest: `Número de ajustes que un cliente podría solicitar`,
  numFilesIncluded: (...v) => `<b>${v[0]}</b> archivo(s) incluido(s)`,
  numOfNewComments: (...v) => `${v[0]} comentarios nuevos`,
  numOfNewReactions: (...v) => `${v[0]} reacciones nuevas`,
  numOfReplies: (...v) => `${v[0]} respuestas`,
  numOfReviews: (...v) => `Reseñas: ${v[0]} `,
  offerDigitalProducts: `Ofrece productos digitales a los que los compradores puedan acceder de inmediato`,
  offerOptionalExtras: `Ofrece extras opcionales, como <b>entrega urgente</b>, un <b>personaje adicional</b> o un <b>fondo detallado</b>`,
  online: `En línea`,
  onlyLatinLettersNumbersHyphen: `Sólo letras latinas, números, guiones, guiones bajos y puntos`,
  onlyNumbers: `Sólo números`,
  onlyYouCanSeeWhatYouveSaved: `Solo tú puedes ver lo que has guardado`,
  open: `Abierto`,
  openDispute: `Abrir disputa`,
  openGuestView: `Abrir vista de invitados`,
  openingSoon: `¡Próxima apertura!`,
  openToWork: `Abierto a trabajar`,
  optional: `Opcional`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `Si quieres, agrega una descripción para contar más sobre tu creación`,
  or: `O`,
  order: `Pedido`,
  orderAgain: `Volver a ordenar`,
  orderCanceledTheBuyersPaymentWasReleased: `Pedido cancelado. Liberamos la retención en la tarjeta del comprador, su banco puede tardar unos días en reflejarlo`,
  orderCanceledYourPaymentWasReleased: `Pedido cancelado. Liberamos la retención en tu tarjeta, tu banco puede tardar unos días en reflejarlo`,
  orderCompleted: `Pedido completado 🎉`,
  orderConfirmed: `Pedido confirmado`,
  orderDetails: `Detalles del pedido`,
  ordered: (...v) => `Pedido ${v[0]}`,
  orderedByMistake: `Pedido por error`,
  orderOptions: `Opciones de pedido`,
  orderStatus: `Estado del pedido`,
  otherReason: `Otra razón`,
  outOfStock: `Agotado`,
  pageNotFound: `Página no encontrada`,
  password: `Contraseña`,
  payments: `Pagos`,
  payouts: `Pagos`,
  personal: `Personal`,
  personalCircumstances: `Circunstancias personales`,
  platform: `Plataforma`,
  platformPoliciesMayStillApply: `Las políticas de la plataforma aún pueden aplicarse`,
  pleaseAllowPopups: `Permite las ventanas emergentes`,
  pleaseCheckYour: (...v) => `Por favor, revisa tu ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Por favor, no compartas tu información privada con otros`,
  pleaseEnterANumberBetweenXandX: (...v) => `Por favor, ingresa un número entre ${v[0]} y ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `Por favor ingrese al menos ${v[0]} caracteres`,
  pleaseFillOutYourDetails: `Por favor complete sus datos`,
  pleaseFixTheErrorsBeforeSubmitting: `Por favor, corrige los errores antes de enviar`,
  pleaseProvideATitleForYourArtwork: `Ingresa un título para tu obra`,
  pleaseRateYourOrder: `Por favor, califica tu pedido`,
  pleaseRespondToTheOrderBy: (...v) => `Responde al pedido antes del ${v[0]}`,
  pleaseReviewTheBuyersReferenceFiles: `Revisa los archivos de referencia del comprador y síguelos según lo especificado en la descripción del pedido`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `Revisa los detalles cuidadosamente antes de continuar`,
  pleaseSignInToYourAccount: `Por favor ingrese a su cuenta`,
  pleaseStartTyping: `Por favor, comience a escribir`,
  pleaseTakeAMomentToReviewTheOrder: `Tómate un momento para revisar el pedido`,
  pleaseTryAgainOrClick: (...v) => `Por favor intente de nuevo o clic ${v[0]}`,
  pleaseUploadOnlyFinishedWorkHere: `Por favor, sube solo trabajos terminados aquí`,
  pleaseVerifyYourAccount: `Por favor verifique su cuenta`,
  portfolio: `Portafolio`,
  pressHereTo: `Presione aquí para`,
  price: `Precio`,
  privacyPolicy: `Política de Privacidad`,
  privateInformation: `Información privada`,
  proceedToCheckout: `Proceder al pago`,
  product: `Producto`,
  profile: `Perfil`,
  prohibitedTransaction: `Transacción prohibida`,
  promotions: `Promociones`,
  publicInformation: `Información pública`,
  publishOn: (...v) => `Publicar en ${v[0]}`,
  purchases: `Compras`,
  rankings: `Clasificaciones`,
  reason: `Razón`,
  reorderFiles: `Reordenar archivos`,
  replies: `Respuestas`,
  reply: `Responder`,
  replyToUsername: (...v) => `Responder a ${v[0]}`,
  report: `Reportar`,
  requestDetails: `Detalles de la solicitud`,
  review: `Reseña`,
  reviewed: `Reseñado`,
  reviews: `Reseñas`,
  reviewTitle: `Título de la reseña`,
  revisions: `Revisiones`,
  rules: `Reglas`,
  sales: `Ventas`,
  save: `Guardar`,
  saveAvatar: `Guardar avatar`,
  saveChanges: `Guardar cambios`,
  selectAnime: `Seleccionar anime`,
  selectAppearanceContrastAndColorTheme: `Selecciona la apariencia, el contraste y el tema de color`,
  selectAvatar: `Seleccionar avatar`,
  selectCharacters: `Seleccionar personaje(s)`,
  selectFile: `Seleccionar archivo`,
  selectThumbnail: `Seleccionar miniatura`,
  selfHarmOrSuicide: `Autolesión o suicidio`,
  sellDownloadableContent: `Vende contenido descargable`,
  seller: `Vendedor`,
  sellerHasntResponded: `El vendedor no ha respondido`,
  sellerTermsOfService: `Términos de servicio para vendedores`,
  sendEmail: `Enviar correo electrónico`,
  settings: `Configuraciones`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Configurar una tienda es gratis y solo lleva unos minutos`,
  setUpStripeAccountToGetPaidWithAnimeClub: `Configura una cuenta de Stripe para recibir pagos con Anime.club`,
  share: `Compartir`,
  shareYourArt: `Comparte tu arte`,
  shareYourArtWithTheWorld: `Comparte tu arte con el mundo`,
  shareYourFavoritePiecesOn: (...v) => `Comparte tus piezas favoritas en ${v[0]}`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `Comparte tus reglas y los tipos de solicitudes que no aceptas`,
  shareYourShopOnSocialMedia: `Comparte tu tienda en redes sociales`,
  shareYourStory: `¡Comparte tu historia!`,
  sharingPersonalInformation: `Compartir información personal`,
  shop: `Tienda`,
  shopOrders: `Pedidos de la tienda`,
  shopReviews: `Reseñas de la tienda`,
  show: `Mostrar`,
  showLess: `Mostrar menos`,
  showListing: `Mostrar publicación`,
  showMore: `Mostrar más`,
  showMyTermsOfService: `Ver mis términos de servicio`,
  showSellerTermsOfService: `Ver los términos del vendedor`,
  signIn: `Iniciar sesión`,
  size: `Tamaño`,
  skip: `Omitir`,
  socialMedia: `Redes sociales`,
  spaceCharacterIsNotAllowed: `El carácter de espacio no está permitido`,
  spam: `Correo no deseado`,
  submitAReport: `Enviar un informe`,
  submitWork: `Enviar trabajo`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Suscríbete a talentos para mantenerte al día con su progreso`,
  successChangedPasswordPleaseSignIn: `Contraseña cambiada exitosamente. Por favor inicie sesión`,
  successCreatedRecord: `Registro creado exitosamente`,
  successfullyDownloaded: `¡Descargado exitosamente!`,
  successfullyUploaded: `¡Subido exitosamente!`,
  supportedFormats: `Formatos compatibles:`,
  supportMeOn: `Apóyame en`,
  system: `Sistema`,
  takeCustomRequests: `Acepta solicitudes personalizadas`,
  tapAddToCreateOne: `Toca “Agregar” para crear uno`,
  tellTheBuyersWhatTheyWillGet: `Indica exactamente qué recibirán los compradores. Por ejemplo, la cantidad de ilustraciones, los formatos de archivo o las especificaciones del lienzo, como la resolución y los DPI`,
  tellUsAboutYourself: `Cuéntanos acerca de tí`,
  termsAndConditions: `Términos y condiciones`,
  termsOfUse: `Condiciones de uso`,
  thankYouForReport: `Gracias por ayudar a mantener una comunidad en línea segura y respetuosa`,
  thankYouForYourPurchase: `¡Gracias por tu compra!`,
  thankYouForYourReview: `¡Gracias por tu reseña!`,
  theBuyerAcceptedThemAtCheckout: `El comprador los aceptó al pagar`,
  theLinkIsBrokenOrPageHasBeenRemoved: `El enlace está roto o la página ha sido eliminada`,
  theMaximumQuantityThatACustomerCanAdd: `La cantidad máxima que un cliente puede agregar`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `El motivo que indiques para cancelar este pedido se compartirá con el comprador`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheSeller: `El motivo que indiques para cancelar este pedido se compartirá con el vendedor`,
  theReviewPeriodIsLimitedtoNdays: (...v) => `El período de revisión está limitado a ${v[0]} días`,
  theseAreYourTermsForThisItem: `Estos son tus términos para este artículo`,
  theSellerHasUploadedTheseFilesForYou: `El vendedor ha subido estos archivos para ti`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `El vendedor proporciona estas reglas y solo se aplican a este artículo`,
  thisCannotBeUndone: `Esto no se puede deshacer`,
  thisFieldIsOptional: `Este campo es opcional`,
  thisIsACustomOrderNotAReadyMadeProduct: `Este es un pedido personalizado, no un producto listo para usar. El vendedor empieza a trabajar en él después de que hagas el pedido`,
  thisIsThePriceYouPropose: `Este es el precio que propones`,
  thisListingWontBeVisibleToBuyersAnymore: `Esta publicación dejará de ser visible para los compradores, pero podrás volver a mostrarla cuando quieras`,
  threateningViolence: `Amenaza de violencia`,
  timeConstraints: `Restricciones de tiempo`,
  title: `Título`,
  titleYourExtraService: `Titula tu servicio adicional`,
  today: `Hoy`,
  toGetWorkRelatedNotifications: `Para recibir notificaciones relacionadas con el trabajo`,
  toHelpTheCreatorCompleteYourOrder: `Para ayudar al creador a completar su pedido a su satisfacción, proporcione una descripción detallada de lo que desea. Incluya el tema deseado, el estilo y las características del personaje, así como cualquier otra especificación importante`,
  total: `Total`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Para ver estos datos, necesitas desbloquear a @${v[0]}`,
  trademarkViolation: `Violación de marca registrada`,
  typeYourTextHere: `Escribe tu texto aquí...`,
  unblock: `Desbloquear`,
  unblockUser: (...v) => `Desbloquear a @${v[0]}`,
  unfollow: `Dejar de seguir`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `Desafortunadamente, ${v[0]} tuvo que cancelar este pedido`,
  unlimited: `Ilimitado`,
  upload: `Subir`,
  uploadedFilesLocked: `Subiste estos archivos al crear la publicación. Ahora están bloqueados, pero siguen visibles abajo`,
  uploadNew: `Subir nuevo`,
  uploadNewPost: `Subir nueva publicación`,
  uploadNewProduct: `Subir nuevo producto`,
  uploadTheFilesYourBuyerWillGet: `Sube los archivos que <b>recibirá el comprador</b>`,
  uploadUpToNumberFiles: (...v) => `Sube hasta <b>${v[0]}</b> archivos`,
  username: `Nombre de usuario`,
  usernameAlreadyExists: `Nombre de usuario ya existe`,
  usernameAndXMoreCommented: (...v) => `<b>${v[0]}</b> y ${v[1]} más comentaron`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> y ${v[1]} más te siguen`,
  usernameAndXMoreReacted: (...v) => `<b>${v[0]}</b> y ${v[1]} más reaccionaron`,
  usernameAndXMoreRepliedToYourComment: (...v) =>
    `<b>${v[0]}</b> y ${v[1]} más respondieron a tu comentario`,
  usernameCommentedOnYourWork: (...v) => `<b>${v[0]}</b> comentó tu trabajo`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> ha cancelado el pedido`,
  usernameHasntAddedAnythingToTheirPortfolioYet: (...v) =>
    `@${v[0]} aún no ha agregado nada a su portafolio`,
  usernameHasntListedAnyProductsForSaleYet: (...v) =>
    `@${v[0]} aún no ha publicado ningún producto a la venta`,
  usernameHasSubmittedTheWork: (...v) => `<b>${v[0]}</b> ha entregado el trabajo`,
  usernameLeftAReaction: (...v) => `<b>${v[0]}</b> dejó una reacción`,
  usernameRepliedToYourComment: (...v) => `<b>${v[0]}</b> respondió a tu comentario`,
  usernameStartedFollowingYou: (...v) => `<b>${v[0]}</b> empezó a seguirte`,
  useThisEmailTo: `Usa este correo electrónico para: autenticarte, recibir notificaciones`,
  valueIsNotTheSame: `Valor no es el mismo`,
  verificationCode: `Código de verificación`,
  verifyCode: `Verificar código`,
  viewDetails: `Ver detalles`,
  viewEveryNotificationOfAGroupSeparately: `Ver cada notificación de un grupo por separado`,
  viewReview: `Ver reseña`,
  visitOurDiscordChannelToGetMoreDetails: `Visite nuestro canal de desacuerdos para obtener más detalles`,
  visitStripeDashboard: `Visitar el panel de Stripe`,
  vote: `Votar`,
  weAreExcitedToSeeYourProgressKeepItUp: `Estamos emocionados de ver su progreso. ¡Siga así!`,
  weAreOnInstagram: `Estamos en Instagram`,
  weAreWorkingOnIt: `Estamos trabajando en ello`,
  weDoNotDisplayNSFWContentYet: `Todavía no mostramos contenido NSFW`,
  weekly: `Semanal`,
  weHaveSentTooManyEmails: `Hemos enviado demasiados correos electrónicos, por favor inténtalo de nuevo más tarde o contacta al soporte al cliente`,
  welcomeToAnimeClub: `¡Bienvenido a Anime.club!`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `¡Bien hecho! El trabajo se ha completado exitosamente`,
  weSentAnEmailTo: `Enviamos un correo electrónico a:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Le enviamos un nuevo correo electrónico de verificación. Por favor ingrese el código`,
  weSupportOnlyTheFollowingFileExtensions: `Solo admitimos las siguientes extensiones de archivo:`,
  weWouldLoveToHearFromYou: `Nos encantaría saber de usted`,
  whatWouldYouLikeToCreate: `¿Qué te gustaría crear?`,
  whenYouPurchaseSomethingItWillAppearHere: `Cuando compres algo, aparecerá aquí`,
  work: `Trabajo`,
  workDescription: `Descripción del trabajo`,
  wrongEmailOrPassword: `Correo electrónico o contraseña incorrecto`,
  yes: `si`,
  yesterday: `Ayer`,
  youAreAlreadyAuthenticated: `Ya estas autenticado`,
  youCanAutoPublishToYourSocialMediaAccount: `Puedes publicar automáticamente en tu cuenta de redes sociales`,
  youCanceledTheOrder: `Cancelaste el pedido`,
  youCanChooseFromTheListOrEnterACustomReason: `Puedes elegir un motivo de la lista o escribir uno personalizado`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Puedes modificar los tipos de notificaciones que recibes por correo electrónico`,
  youCanRequestRemovalOfYourAccount: `Puedes solicitar la eliminación de tu cuenta con todos tus datos`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Todavía puede navegar a las páginas abiertas anteriormente`,
  youDidNotSelectAnyChats: `No seleccionó ningún chat`,
  youDidNotUpdateAnyValues: `No actualizaste ningún valor`,
  youDoNotHaveAnyChats: `No tiene ningún chat`,
  youHaveNoPurchases: `No tienes compras`,
  youHaveNotSetAPassword: `No has establecido una contraseña`,
  youHaveNotSharedAnythingYet: `Aún no has compartido nada`,
  youHaveReachedTheMaximumNumberOfFiles: `Has alcanzado el número máximo de archivos`,
  youHaveSuccessfullyCreatedYourShop: `Ha creado su tienda con éxito`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `Verás reseñas aquí una vez que los compradores compartan su experiencia`,
  yourAccountIsVerifiedPleaseSignIn: `Su cuenta está verificada. Por favor inicie sesión`,
  yourAccountWillBeRemoved: (...v) => `Tu cuenta será eliminada ${v[0]}`,
  yourArts: `Tu arte`,
  yourAvatar: `Tu avatar`,
  yourBlog: `Tu blog`,
  youReceivedANewOrderFrom: (...v) => `Ha recibido un nuevo pedido de <b>${v[0]}</b>`,
  youReceivedAReview: `Has recibido una reseña`,
  yourFansAreWaiting: `Tus fans están esperando`,
  yourFavoritesWillShowUpHereAddSome: `Tus favoritos aparecerán aquí. ¡Agrega algunos!`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `Tu opinión guía a los compradores y ayuda a los vendedores a ofrecer mejores productos`,
  yourFeedIsEmpty: `Tu feed está vacío`,
  yourSessionHasExpiredPleaseSignInAgain: `Su sesión ha expirado, por favor inicie sesión de nuevo`,
  yourTermsOfService: `Tus términos de servicio`,
  youWillBeAbleToDownloadYourFilesImmediatelyAfterPurchase: `Podrás descargar tus archivos inmediatamente después de la compra, ¡sin esperas!`,
  youWillBeAbleToUploadReferenceFilesAfterCheckout: `Podrás subir archivos de referencia después de pagar`,
}
