export const text: text = {
  animeClubUsesToPayYouQuicklyAndKeepYourInfoSecure: (...v) =>
    `(en) Anime club uses ${v[0]} to get you paid quickly and keep your personal and payment information secure`,
  files: `(en) Files`,
  prohibitedTransaction: `(en) Prohibited transaction`,
  needsYourReview: `(en) Needs Your Review`,
  awaitingSellerResponse: `(en) Awaiting seller response`,
  buyersRequest: `(en) Buyer's request`,
  awaitingClientReview: `(en) Awaiting Client Review`,
  hideListing: `(en) Hide listing`,
  uploadUpToNumberImages: (...v) => `(en) Upload up to <b>${v[0]}</b> images`,
  supportedFormats: `(en) Supported formats:`,
  minimumDimensions: (...v) => `(en) Minimum size: ${v[0]}×${v[1]} pixels`,
  maximumFileSize: (...v) => `(en) Maximum file size: <b>${v[0]}</b> per image`,
  thisListingWontBeVisibleToBuyersAnymore: `(en) This listing won’t be visible to buyers anymore — but you can show it again whenever you’re ready`,
  buyersWillBeAbleToSeeThisListingYouCanHideItAgainAnytime: `(en) Buyers will be able to see this listing. You can hide it again anytime`,
  listingHiddenFromBuyers: `(en) Listing hidden from buyers`,
  listingIsNowVisibleToBuyers: `(en) Listing is now visible to buyers`,
  showListing: `(en) Show listing`,
  theseRulesAreProvidedByTheSellerAndApplyOnlyToThisItem: `(en) These rules are provided by the seller and apply only to this item`,
  ifYouHaveQuestionsOrConcernsPleaseContactTheSellerDirectly: `(en) If you have questions or concerns, please contact the seller directly`,
  platformPoliciesMayStillApply: `(en) Platform policies may still apply`,
  uploadedFilesLocked: `(en) You uploaded these files when you created the post. They're now locked but still visible below`,
  new: `(en) New`,
  createPersonalizedWorkTailoredToEachRequest: `(en) Create personalized work tailored to each request`,
  offerDigitalProducts: `(en) Offer digital products that buyers can access right away`,
  instantDownload: `(en) Instant Download`,
  customWork: `(en) Custom Work`,
  noOrders: `(en) No orders`,
  tellTheBuyersWhatTheyWillGet: `(en) Tell buyers exactly what they will get — for example, the number of illustrations, file formats, or canvas specs like resolution and DPI`,
  beSpecificAboutTheContent: `(en) Be specific about the content (e.g. number of files, formats, canvas resolution)`,
  mentionYourDeliveryTimeInDays: `(en) Mention your <b>delivery time</b> (in days)`,
  letBuyersKnowIfYouOfferRevisionsAndHowMany: `(en) Let buyers know if you offer <b>revisions</b>, and how many`,
  listAnyContentOrRequestsYouDontAccept: `(en) List any content or requests you <b>don't accept</b> (e.g. NSFW, political, religious, or offensive material)`,
  offerOptionalExtras: `(en) Offer optional extras like <b>rush delivery</b>, an <b>extra character</b>, or a <b>detailed background</b>`,
  extrasHelpBoostIncome: `(en) Extras help buyers customize their order and can boost your income`,
  artGallery: `(en) Art Gallery`,
  commission: `(en) Commission`,
  digitalStore: `(en) Digital Store`,
  setUpStripeAccountToGetPaidWithAnimeClub: `(en) Set up a Stripe account to get paid with Anime club`,
  describeWhatsIncludedAndWhatTheBuyerCanExpectAfterPurchase: `(en) Describe what’s included and what the buyer can expect after purchase`,
  theReasonYouProvideForCancellingThisOrderWillBeSharedWithTheBuyer: `(en) The reason you provide for cancelling this order will be shared with the buyer`,
  optionallyYouCanAddADescriptionToShareMoreAboutYourCreation: `(en) Optionally, you can add a description to share more about your creation`,
  pleaseProvideATitleForYourArtwork: `(en) Please provide a title for your artwork`,
  tapAddToCreateOne: `(en) Tap “Add” to create one`,
  youCanChooseFromTheListOrEnterACustomReason: `(en) You can choose from the list or enter a custom reason`,
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  _hyphen: `- `,
  about: `Sobre`,
  accept: `Aceptar`,
  acceptOrder: `Aceptar orden`,
  acceptTheOrder: `Aceptar el pedido`,
  accountManagment: `Gestión de cuenta`,
  account: `Cuenta`,
  accountDeleted: `Cuenta eliminada`,
  animeShopBuyAndSellProducts: `Tienda de anime - compra y venta de productos`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `Las imágenes generadas por IA y los filtros de redes neuronales están prohibidos`,
  accountActivation: `Activación de cuenta`,
  accountAlreadyExists: `La cuenta ya existe`,
  accountDoesNotExist: `La cuenta no existe`,
  accountRemoval: `Eliminación de cuenta`,
  add: `Agregar`,
  addArt: `Agregar arte`,
  addBlog: `Agregar blog`,
  additionalResources: `Recursos adicionales`,
  addMoreProductsToYourShop: `Agrega más productos a tu tienda`,
  addMore: `Agregar más`,
  addNewArt: `Agregar arte nuevo`,
  addPreview: `Agregar vista previa`,
  addSignInVia: `Añadir inicio de sesión mediante`,
  addToCart: `Agregar al carrito`,
  advancedOptions: `Opciones avanzadas`,
  all: `Todo`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `Todos los archivos que subas aquí estarán disponibles para el comprador`,
  alreadySignedIn: `Sesión iniciada`,
  amount: `Cantidad`,
  amountShouldNotBeLessThan: (...v) =>
    `La cantidad no debe ser menor a ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Arte de anime por artistas de todo el mundo. El arte está curado para estar relacionado con el anime. La selección de arte es una lista infinita del mejor arte de anime.`,
  animeArtSubscribeToArtistsLikeAndCreate: `Arte de anime - suscríbete a artistas, dale me gusta y crea colecciones`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - la primera plataforma que ofrece pagos a los artistas a partir de las vistas a través de Google AdSense. Apoye a los artistas viendo su contenido o comience a ganar dinero con las vistas`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club: vea, publique y gane contenido de anime`,
  animeCommunity: `Comunidad de anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club nunca solicita su información privada`,
  animeSocialNetwork: `Red social de anime`,
  announcements: `Anuncios`,
  apply: `Aplicar`,
  appSettings: `Configuración de la aplicación`,
  appsVersionIs: `La versión de la aplicación es`,
  areYouSureYouWantTo: `Estás seguro que quieres`,
  art: `Arte`,
  artAssociatedWithAnime: `Arte asociado con el anime`,
  artBy: (...v) => `Arte por ${v[0]}`,
  artCannotBeChanged: `El arte no se puede cambiar`,
  artworksAvailableToView: (...v) =>
    `${v[0]} obras de arte disponibles para ver`,
  authenticationFailed: `Error de autenticación`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `La publicación automática en Instagram solo está disponible para cuentas comerciales de Instagram`,
  attentionYourOrderHasBeenDisputed: `¡Atención! Su pedido ha sido disputado. Por favor, verifique los detalles`,
  back: `Volver`,
  basePrice: `Precio base`,
  bigAppreciationToTheSellerForTheHardWork: `Gran agradecimiento al vendedor por el arduo trabajo`,
  block: `Bloquear`,
  buyerReviewedTheOrder: `El comprador revisó el pedido`,
  buyerHasNotLeftAReviewYet: `El comprador aún no ha dejado una reseña`,
  feedbackReceived: `¡Reseña recibida!`,
  blockUser: (...v) => `Bloquear a @${v[0]}`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `Antes de aceptar, revisa cuidadosamente la solicitud del comprador`,
  blog: `Blog`,
  bookmarks: `Guardados`,
  browseArt: `Examinar arte`,
  browseShop: `Explorar tienda`,
  buyer: `Comprador`,
  cancel: `cancelar`,
  canceled: `Cancelado`,
  cancelOrder: `Cancelar pedido`,
  cannotStartWithChars: `No puedo empezar con s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Cambiar`,
  checkOutMyShop: `Visita mi tienda`,
  checkOrderStatus: `Verificar estado del pedido`,
  changeArt: `Cambiar arte`,
  changeAvatar: `Cambiar avatar`,
  changeEmail: `Cambiar correo electrónico`,
  changePassword: `Cambiar contraseña`,
  chooseExistingChatOrStartANewOne: `Elija un chat existente o inicie uno`,
  city: `Ciudad`,
  clearAll: `Borrar todo`,
  close: `Cerrar`,
  colorTheme: `Tema de color`,
  comingSoon: `Próximamente...`,
  commercialUseAllowed: `Uso comercial permitido`,
  commercialUseAllowsBuyersToUseYourProduct: `El uso comercial permite a los compradores usar tu producto para fines comerciales, como vender o promocionar sus servicios`,
  community: `Comunidad`,
  completed: `Completado`,
  confirmAccount: `Confirmar cuenta`,
  confirmOrder: `Confirmar pedido`,
  confirmPassword: `Confirmar contraseña`,
  connectWithUsOn: `Conéctate con nosotros en`,
  contactInformation: `Información de contacto`,
  contactSeller: `Contactar al vendedor`,
  contactSupport: `Contactar soporte`,
  contactUs: `Contáctenos`,
  continue: `Continuar`,
  contractTitle: `Título del contrato`,
  copyLink: `Copiar link`,
  congratulations: `¡Felicidades!`,
  congratulationsOnSuccessfullyCompletingYourOrder: `¡Felicidades por completar tu pedido exitosamente!`,
  copyrightViolation: `Violación de derechos de autor`,
  couldNotCreateANewRecord: `No se pudo crear un nuevo registro`,
  country: `País`,
  cover: `Portada`,
  createANewAccountFailed: `Fallo al crear una nueva cuenta`,
  createExtrasForYourProduct: `Crear extras para tu producto`,
  createNewAccount: `Crear una nueva cuenta`,
  createAShopWithStripe: `Crea una tienda con Stripe`,
  createdBy: `Creado por`,
  currentPassword: `Contraseña actual`,
  daily: `Diario`,
  darkDefault: `Oscuro predeterminado`,
  darkHighContrast: `Oscuro alto contraste`,
  dayTheme: `Tema diurno`,
  delete: `Eliminar`,
  deleteShop: `Eliminar tienda`,
  deleteAccount: `Eliminar cuenta`,
  deleteArt: `Eliminar arte`,
  decline: `Rechazar`,
  deletePost: `Eliminar publicación`,
  deleteProduct: `Eliminar producto`,
  download: `Descargar`,
  downloadThemBelow: `Descárgalos abajo`,
  deliveryTime: `Tiempo de entrega`,
  describeTheDetailsOfYourExtra: `Describe los detalles de tu extra`,
  description: `Descripción`,
  details: `Detalles`,
  didntReceiveEmail: `¿No recibió un correo electrónico?`,
  displayName: `Nombre de visualización`,
  disputed: `Disputado`,
  donations: `Donaciones`,
  done: `Hecho`,
  dragAndDropOrSelectFiles: `Arrastra y suelta o selecciona archivo(s)`,
  drawingContest: `Concurso de dibujo`,
  dueDate: `Fecha de vencimiento`,
  earlier: `Anterior`,
  earningFromArts: `Ganar de las artes`,
  edit: `Editar`,
  editPost: `Editar tu publicación`,
  editProfile: `Editar tu perfil`,
  editTranslations: `Editar traducciones`,
  email: `Correo electrónico`,
  emailAlreadyUsedByAnotherAccount: `El correo electrónico ya es usado por otra cuenta`,
  emailNotifications: `Notificaciones por correo electrónico`,
  enterOrPasteALink: `Introduzca o pegue un enlace`,
  enjoyYourPurchase: `¡Disfruta tu compra! 😊`,
  enterTheAddressAssociatedWithYourAccount: `Ingresa la dirección asociada con tu cuenta y te enviaremos un enlace para restablecer tu contraseña`,
  enterYourPassword: `Ingresa tu contraseña`,
  error: `Error`,
  errorPleaseContactCustomerSupport: `¡Error! Por favor, póngase en contacto con el servicio de atención al cliente...`,
  exitWithoutSaving: `Salir sin guardar`,
  extensions: `Extensiones`,
  extras: `Extras`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `Los extras son complementos opcionales para mejorar tu producto`,
  fileSizeIsTooBig: `El tamaño del archivo es demasiado grande`,
  fileSizeIsTooSmall: `El tamaño del archivo es demasiado pequeño`,
  filter: `Filtrar`,
  filterBy: `Filtrar por`,
  findUser: `Buscar usuario`,
  finishSettingUpYourShop: `Termina de configurar tu tienda`,
  follow: `Seguir`,
  followers: `Seguidores`,
  following: `Siguiendo`,
  followMeOn: `Sigueme en`,
  follows: `Seguidores`,
  forAllOtherInquiriesPleaseContactUsAt: `Para todas las demás consultas, por favor contáctenos en:`,
  forgotPassword: `Olvidó su contraseña`,
  fromAnimeDotClub: `De anime.club`,
  getDetails: `Obtener detalles`,
  getStarted: `Empezar`,
  guestView: `Vista de invitado`,
  greatNewsYourOrderIsNowInProgress: `¡Buenas noticias! Su pedido está en progreso`,
  harassment: `Acoso`,
  haveAnyQuestions: `¿Tiene alguna pregunta?`,
  usernameHasCanceledTheOrder: (...v) =>
    `<b>${v[0]}</b> ha cancelado el pedido`,
  usernameHasSubmittedTheWork: (...v) =>
    `<b>${v[0]}</b> ha entregado el trabajo`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]} no ha agregado una descripción para "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} aún no ha compartido detalles públicos`,
  hate: `Odio`,
  hereAreAFewWaysToGetThingsRolling: `Aquí tienes algunas formas de empezar`,
  hire: `Contratar`,
  homepage: `Página de inicio`,
  howToContactYou: `Cómo contactarte`,
  howToFindYouOnOtherSocialNetworks: `Cómo encontrarte en otras redes sociales`,
  iAgreeWith: `Estoy de acuerdo con`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Si no hay respuesta para ${v[0]}, el pedido se marcará como completado automáticamente`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `La altura de la imagen debe ser mayor o igual que`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `El ancho de la imagen debe ser mayor o igual que`,
  impersonation: `Suplantación de identidad`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Incluye palabras clave que los compradores probablemente usarían para buscar un producto como el tuyo`,
  inProgress: `En progreso`,
  introduction: `Introducción`,
  includes: `Incluye`,
  invalidCode: `Código inválido`,
  invalidCurrentPassword: `Contraseña actual inválida`,
  invalidDate: `Fecha inválida`,
  invalidPartAfterAt: `Pieza no válida después de @`,
  invalidPartBeforeAt: `Pieza no válida antes de @`,
  jobDetails: `Detalles del trabajo`,
  joinAnimeClubCommunity: `Únete a la comunidad de Anime.club con miles de creadores activos y arte de anime genial todos los días`,
  joinChat: `Unirse al chat`,
  joinUsOnFacebook: `Únete a nosotros en Facebook`,
  language: `Idioma`,
  lackOfInformation: `Falta de información`,
  languages: `Idiomas`,
  letEveryoneKnowHowToDonateToYou: `Haz que todos sepan cómo donarte`,
  letOthersKnowAboutYou: `Haz que otros sepan sobre ti`,
  letsUploadYourFirstProduct: `Subamos su primer producto`,
  letUsKnowWhatsHappening: `Haznos saber qué está sucediendo y lo investigaremos`,
  lightDefault: `Predeterminado claro`,
  lightHighContrast: `Alto contraste claro`,
  likes: `Me gusta`,
  limit: `Límite`,
  linkCopiedToClipboard: `Enlace copiado en el portapapeles`,
  livesIn: `Viviendo en`,
  loading: `Cargando`,
  location: `Ubicación`,
  logInOrSignUp: `Iniciar sesión o registrarse`,
  logOut: `Cerrar sesión`,
  maximumNChars: (...v) => `Máximo ${v[0]} caracteres`,
  maximumNumberOfDaysToCompleteTheOrder: `Número máximo de días para completar el pedido`,
  maximumQuantity: `Cantidad máxima`,
  maxSize: `Tamaño máximo`,
  menu: `Menú`,
  message: `Mensaje`,
  messages: `Mensajes`,
  minHeight: `Altura mínima`,
  minimumNChars: (...v) => `Mínimo ${v[0]} caracteres`,
  minorAbuseOrSexualization: `Abuso o sexualización de menores`,
  makeSureToIncludeClearInstructions: `Asegúrate de incluir instrucciones claras sobre cómo debe usarse cada referencia`,
  makeSureYouFullyUnderstandTheRequirements: `Asegúrate de entender completamente los requisitos y de poder completar el pedido antes de la fecha límite`,
  makeSureYourProductsArePricedCompetitively: `Asegúrate de que tus productos tengan precios competitivos`,
  minWidth: `Ancho mínimo`,
  monthly: `Mensual`,
  moreFrom: (...v) => `Más de ${v[0]}`,
  mustBeNChars: (...v) => `Debe tener ${v[0]} caracteres`,
  myPayments: `Mis pagos`,
  myProfile: `Mi perfil`,
  mySettings: `Mis ajustes`,
  need1Lowercase: `Necesita 1 minúscula`,
  need1Number: `Necesita 1 número`,
  need1Uppercase: `Necesita 1 mayúscula`,
  needAtLeast1CharacterFromN: (...v) =>
    `Necesita al menos 1 carácter de [${v[0]}]`,
  needNCharacter: (...v) => `Debe tener ${v[0]} carácter`,
  newAccount: `Nueva cuenta`,
  newArt: `Arte nuevo`,
  newArtworks: `Nuevas obras de arte`,
  newBlog: `Nuevo blog`,
  newOrder: `Nuevo pedido`,
  newPassword: `Nueva contraseña`,
  newProduct: `Nuevo producto`,
  newProducts: `Nuevos productos`,
  newsFeed: `Noticias`,
  next: `Siguiente`,
  nextTimeYouAuthenticateYouCouldUseThe: `La próxima vez que te autentiques, podrías usar la cuenta conectada en lugar del inicio de sesión y la contraseña`,
  nightTheme: `Tema nocturno`,
  no: `No`,
  noInternetConnection: `¡Sin conexión a Internet!`,
  nonConsensualIntimateContent: `Contenido íntimo no consensuado`,
  none: `Ninguno`,
  noNotifications: `Sin notificaciones`,
  noResults: `Sin resultados`,
  noReviewsJustYet: `Aún no hay reseñas`,
  notifications: `Notificaciones`,
  noActiveOrdersToShow: `No hay pedidos activos para mostrar`,
  notAcceptingOrders: `No aceptando pedidos`,
  noSalesYetNoWorries: `¿Aún no tienes ventas? No te preocupes, acabas de empezar`,
  nsfwContent18Plus: `Contenido NSFW (18+)`,
  NSFWIndicatesAdultContent: `18+ NSFW indica contenido para adultos. Marca este campo solo si tu producto es para adultos`,
  numberOfAdjustmentsAClientCouldRequest: `Número de ajustes que un cliente podría solicitar`,
  online: `En línea`,
  onlyLatinLettersNumbersHyphen: `Sólo letras latinas, números, guiones, guiones bajos y puntos`,
  onlyNumbers: `Sólo números`,
  onlyYouCanSeeWhatYouveSaved: `Solo tú puedes ver lo que has guardado`,
  open: `Abierto`,
  openDispute: `Abrir disputa`,
  openGuestView: `Abrir vista de invitados`,
  openingSoon: `¡Próxima apertura!`,
  openToWork: `Abierto a trabajar`,
  optional: `Opcional`,
  requestDetails: `Detalles de la solicitud`,
  or: `O`,
  order: `Pedido`,
  outOfStock: `Agotado`,
  ordered: (...v) => `Pedido ${v[0]}`,
  orderAgain: `Volver a ordenar`,
  orderDetails: `Detalles del pedido`,
  orderConfirmed: `Pedido confirmado`,
  orderCompleted: `Pedido completado 🎉`,
  orderStatus: `Estado del pedido`,
  orderOptions: `Opciones de pedido`,
  otherReason: `Otra razón`,
  pageNotFound: `Página no encontrada`,
  password: `Contraseña`,
  payments: `Pagos`,
  personal: `Personal`,
  personalCircumstances: `Circunstancias personales`,
  pleaseCheckYour: (...v) => `Por favor, revisa tu ${v[0]}`,
  pleaseRateYourOrder: `Por favor, califica tu pedido`,
  feelFreeToShareReferenceImagesAndMaterials: `Siéntete libre de compartir imágenes y materiales de referencia para ayudar al artista a crear tu pieza`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Por favor, no compartas tu información privada con otros`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `Por favor, ingresa un número entre ${v[0]} y ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) =>
    `Por favor ingrese al menos ${v[0]} caracteres`,
  pleaseFillOutYourDetails: `Por favor complete sus datos`,
  pleaseFixTheErrorsBeforeSubmitting: `Por favor, corrige los errores antes de enviar`,
  pleaseSignInToYourAccount: `Por favor ingrese a su cuenta`,
  platform: `Plataforma`,
  pleaseStartTyping: `Por favor, comience a escribir`,
  pleaseTakeAMomentToReviewTheOrder: `Tómate un momento para revisar el pedido`,
  pleaseReviewTheBuyersReferenceFiles: `Revisa los archivos de referencia del comprador y síguelos según lo especificado en la descripción del pedido`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `Revisa los detalles cuidadosamente antes de continuar`,
  pleaseRespondToTheOrderBy: (...v) => `Responde al pedido antes del ${v[0]}`,
  pleaseTryAgainOrClick: (...v) => `Por favor intente de nuevo o clic ${v[0]}`,
  pleaseVerifyYourAccount: `Por favor verifique su cuenta`,
  pressHereTo: `Presione aquí para`,
  price: `Precio`,
  payouts: `Pagos`,
  privacyPolicy: `Política de Privacidad`,
  privateInformation: `Información privada`,
  proceedToCheckout: `Proceder al pago`,
  product: `Producto`,
  itemReviews: `Reseñas de artículos`,
  portfolio: `Portafolio`,
  profile: `Perfil`,
  promotions: `Promociones`,
  publicInformation: `Información pública`,
  publishOn: (...v) => `Publicar en ${v[0]}`,
  purchases: `Compras`,
  rankings: `Clasificaciones`,
  reorderFiles: `Reordenar archivos`,
  report: `Reportar`,
  review: `Reseña`,
  rules: `Reglas`,
  reviews: `Reseñas`,
  numOfReviews: (...v) => `Reseñas: ${v[0]} `,
  reviewed: `Reseñado`,
  reviewTitle: `Título de la reseña`,
  reason: `Razón`,
  revisions: `Revisiones`,
  includesXRevisionS: (...v) => `Incluye ${v[0]} revisión(es)`,
  sales: `Ventas`,
  save: `Guardar`,
  saveAvatar: `Guardar avatar`,
  saveChanges: `Guardar cambios`,
  selectAnime: `Seleccionar anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Selecciona un tema único o sincroniza con tu sistema y cambia automáticamente entre temas de día y noche`,
  selectAvatar: `Seleccionar avatar`,
  selectCharacters: `Seleccionar personaje(s)`,
  seller: `Vendedor`,
  selectFile: `Seleccionar archivo`,
  selectTheme: `Seleccionar tema`,
  selectThumbnail: `Seleccionar miniatura`,
  selfHarmOrSuicide: `Autolesión o suicidio`,
  sendEmail: `Enviar correo electrónico`,
  settings: `Configuraciones`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Configurar una tienda es gratis y solo lleva unos minutos`,
  share: `Compartir`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `Comparte tus reglas y los tipos de solicitudes que no aceptas`,
  shareYourShopOnSocialMedia: `Comparte tu tienda en redes sociales`,
  shareYourFavoritePiecesOn: (...v) =>
    `Comparte tus piezas favoritas en ${v[0]}`,
  shareYourArtWithTheWorld: `Comparte tu arte con el mundo`,
  shareYourStory: `¡Comparte tu historia!`,
  sharingPersonalInformation: `Compartir información personal`,
  shop: `Tienda`,
  shopReviews: `Reseñas de la tienda`,
  shopOrders: `Pedidos de la tienda`,
  showLess: `Mostrar menos`,
  showMore: `Mostrar más`,
  signIn: `Iniciar sesión`,
  singleTheme: `Tema único`,
  size: `Tamaño`,
  skip: `Omitir`,
  socialMedia: `Redes sociales`,
  spaceCharacterIsNotAllowed: `El carácter de espacio no está permitido`,
  spam: `Correo no deseado`,
  yourFavoritesWillShowUpHereAddSome: `Tus favoritos aparecerán aquí. ¡Agrega algunos!`,
  submitAReport: `Enviar un informe`,
  submitWork: `Enviar trabajo`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Suscríbete a talentos para mantenerte al día con su progreso`,
  successChangedPasswordPleaseSignIn: `Contraseña cambiada exitosamente. Por favor inicie sesión`,
  successCreatedRecord: `Registro creado exitosamente`,
  successUpdatedRecord: `Registro actualizado exitosamente`,
  successfullyDownloaded: `¡Descargado exitosamente!`,
  successfullyUploaded: `¡Subido exitosamente!`,
  supportMeOn: `Apóyame en`,
  syncWithSystem: `Sincronizar con el sistema`,
  tellUsAboutYourself: `Cuéntanos acerca de tí`,
  termsAndConditions: `Términos y condiciones`,
  termsOfUse: `Condiciones de uso`,
  thankYouForReport: `Gracias por ayudar a mantener una comunidad en línea segura y respetuosa`,
  thankYouForYourReview: `¡Gracias por tu reseña!`,
  thankForYourSupport: `¡Gracias por tu apoyo!`,
  theLinkIsBrokenOrPageHasBeenRemoved: `El enlace está roto o la página ha sido eliminada`,
  themeMode: `Modo de tema`,
  thisIsThePriceYouPropose: `Este es el precio que propones`,
  thisFieldIsOptional: `Este campo es opcional`,
  thisCannotBeUndone: `Esto no se puede deshacer`,
  ensureYouveUploadedTheFinalVersion: `Asegúrate de haber subido la versión final antes de enviar`,
  threateningViolence: `Amenaza de violencia`,
  title: `Título`,
  timeConstraints: `Restricciones de tiempo`,
  titleYourExtraService: `Titula tu servicio adicional`,
  theMaximumQuantityThatACustomerCanAdd: `La cantidad máxima que un cliente puede agregar`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `El período de revisión está limitado a ${v[0]} días`,
  toHelpTheCreatorCompleteYourOrder: `Para ayudar al creador a completar su pedido a su satisfacción, proporcione una descripción detallada de lo que desea. Incluya el tema deseado, el estilo y las características del personaje, así como cualquier otra especificación importante`,
  today: `Hoy`,
  toGetWorkRelatedNotifications: `Para recibir notificaciones relacionadas con el trabajo`,
  total: `Total`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Para ver estos datos, necesitas desbloquear a @${v[0]}`,
  trademarkViolation: `Violación de marca registrada`,
  typeYourTextHere: `Escribe tu texto aquí...`,
  theSellerHasUploadedTheseFilesForYou: `El vendedor ha subido estos archivos para ti`,
  unblock: `Desbloquear`,
  unblockUser: (...v) => `Desbloquear a @${v[0]}`,
  unfollow: `Dejar de seguir`,
  unlimited: `Ilimitado`,
  upload: `Subir`,
  uploadNew: `Subir nuevo`,
  uploadNewPost: `Subir nueva publicación`,
  uploadNewProduct: `Subir nuevo producto`,
  username: `Nombre de usuario`,
  pleaseUploadOnlyFinishedWorkHere: `Por favor, sube solo trabajos terminados aquí`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `Todos los archivos relacionados con WIP deben subirse en mensajes`,
  usernameAlreadyExists: `Nombre de usuario ya existe`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> y ${v[1]} más te siguen`,
  usernameAndXMoreReacted: (...v) =>
    `<b>${v[0]}</b> y ${v[1]} más reaccionaron`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b> te sigue`,
  usernameReacted: (...v) => `<b>${v[0]}</b> reaccionó`,
  useThisEmailTo: `Usa este correo electrónico para: autenticarte, recibir notificaciones`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `Desafortunadamente, ${v[0]} tuvo que cancelar este pedido`,
  valueIsNotTheSame: `Valor no es el mismo`,
  verificationCode: `Código de verificación`,
  verifyCode: `Verificar código`,
  viewDetails: `Ver detalles`,
  viewReview: `Ver reseña`,
  viewEveryNotificationOfAGroupSeparately: `Ver cada notificación de un grupo por separado`,
  visitOurDiscordChannelToGetMoreDetails: `Visite nuestro canal de desacuerdos para obtener más detalles`,
  weAreOnInstagram: `Estamos en Instagram`,
  weAreWorkingOnIt: `Estamos trabajando en ello`,
  wellDoneWorkHasBeenSuccessfullyCompleted: `¡Bien hecho! El trabajo se ha completado exitosamente`,
  weDoNotDisplayNSFWContentYet: `Todavía no mostramos contenido NSFW`,
  weekly: `Semanal`,
  whenYouPurchaseSomethingItWillAppearHere: `Cuando compres algo, aparecerá aquí`,
  weHaveSentTooManyEmails: `Hemos enviado demasiados correos electrónicos, por favor inténtalo de nuevo más tarde o contacta al soporte al cliente`,
  welcomeToAnimeClub: `¡Bienvenido a Anime.club!`,
  weSentAnEmailTo: `Enviamos un correo electrónico a:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Le enviamos un nuevo correo electrónico de verificación. Por favor ingrese el código`,
  weAreExcitedToSeeYourProgressKeepItUp: `Estamos emocionados de ver su progreso. ¡Siga así!`,
  weSupportOnlyTheFollowingFileExtensions: `Solo admitimos las siguientes extensiones de archivo:`,
  work: `Trabajo`,
  weWouldLoveToHearFromYou: `Nos encantaría saber de usted`,
  workDescription: `Descripción del trabajo`,
  leaveAReview: `Dejar una reseña`,
  wrongEmailOrPassword: `Correo electrónico o contraseña incorrecto`,
  yes: `si`,
  yesterday: `Ayer`,
  youReceivedANewOrderFrom: (...v) =>
    `Ha recibido un nuevo pedido de <b>${v[0]}</b>`,
  youReceivedAReview: `Has recibido una reseña`,
  youHaveSuccessfullyCreatedYourShop: `Ha creado su tienda con éxito`,
  youAreAlreadyAuthenticated: `Ya estas autenticado`,
  youCanAutoPublishToYourSocialMediaAccount: `Puedes publicar automáticamente en tu cuenta de redes sociales`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Puedes modificar los tipos de notificaciones que recibes por correo electrónico`,
  youCanRequestRemovalOfYourAccount: `Puedes solicitar la eliminación de tu cuenta con todos tus datos`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `Tu opinión guía a los compradores y ayuda a los vendedores a ofrecer mejores productos`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Todavía puede navegar a las páginas abiertas anteriormente`,
  youDidNotSelectAnyChats: `No seleccionó ningún chat`,
  youllSeeReviewsHereOnceBuyersShareTheirExperience: `Verás reseñas aquí una vez que los compradores compartan su experiencia`,
  youDidNotUpdateAnyValues: `No actualizaste ningún valor`,
  youDoNotHaveAnyChats: `No tiene ningún chat`,
  youHaveNotSetAPassword: `No has establecido una contraseña`,
  youHaveNotSharedAnythingYet: `Aún no has compartido nada`,
  youHaveReachedTheMaximumNumberOfFiles: `Has alcanzado el número máximo de archivos`,
  kindlyHoldOnForTheBuyersReview: `Por favor, espere la reseña del comprador sobre el pedido.`,
  yourAccountIsVerifiedPleaseSignIn: `Su cuenta está verificada. Por favor inicie sesión`,
  yourAccountWillBeRemoved: (...v) => `Tu cuenta será eliminada ${v[0]}`,
  youHaveNoPurchases: `No tienes compras`,
  couldYouPleaseProvideTheReasonForTheCancellation: `¿Podría proporcionar la razón de la cancelación?`,
  yourArts: `Tu arte`,
  youCanceledTheOrder: `Cancelaste el pedido`,
  yourAvatar: `Tu avatar`,
  yourBlog: `Tu blog`,
  yourFansAreWaiting: `Tus fans están esperando`,
  yourFeedIsEmpty: `Tu feed está vacío`,
  yourSessionHasExpiredPleaseSignInAgain: `Su sesión ha expirado, por favor inicie sesión de nuevo`,
}
