export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Sobre`,
  accept: `Aceptar`,
  accountActivation: `Activación de cuenta`,
  accountAlreadyExists: `La cuenta ya existe`,
  accountDoesNotExist: `La cuenta no existe`,
  add: `Agregar`,
  addArt: `Agregar arte`,
  addBlog: `Agregar blog`,
  addedNAgo: (n) => `Agregado hace ${n}`,
  addNewArt: `Agregar arte nuevo`,
  addPreview: `Agregar vista previa`,
  addSignInVia: `Añadir inicio de sesión mediante`,
  alreadySignedIn: `Sesión iniciada`,
  animeArtByArtistsFromAllOverTheWorld: `Arte anime de artistas de todo el mundo. El arte está curado para estar relacionado con el anime. La selección de arte es una lista infinita del mejor arte de anime.`,
  animeArtSubscribeToArtistsLikeAndCreate: `Arte de anime - suscríbase a artistas, me gusta y cree colecciones`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - la primera plataforma que ofrece pagos a los artistas a partir de las vistas a través de Google AdSense. Apoye a los artistas viendo su contenido o comience a ganar dinero con las vistas`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club: vea, publique y gane contenido de anime`,
  animeCommunity: `Comunidad de anime`,
  animeOnly: `Solo anime`,
  apply: `(en) Apply`,
  appsVersionIs: `La versión de la aplicación es`,
  areYouSureYouWantTo: `Estás seguro que quieres`,
  art: `Arte`,
  artAssociatedWithAnime: `Arte asociado con el anime`,
  artBy: `Arte de`,
  artCannotBeChanged: `Arte no se puede cambiar`,
  authenticationFailed: `Error de autenticación`,
  back: `Volver`,
  blog: `Blog`,
  bookmarks: `Guardados`,
  browseArt: `Examinar arte`,
  cancel: `cancelar`,
  cannotStartWithChars: `No puedo empezar con s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  changeArt: `Cambiar el arte`,
  changeAvatar: `Cambiar avatar`,
  changePassword: `Cambia la contraseña`,
  chooseExistingChatOrStartANewOne: `(en) Choose existing chat or start a new one`,
  city: `Ciudad`,
  clearAll: `Borrar todo`,
  close: `Cerca`,
  comingSoon: `Próximamente...`,
  community: `Comunidad`,
  confirmAccount: `Confirma la cuenta`,
  confirmPassword: `Confirma la contraseña`,
  copyLink: `Copiar enlace`,
  couldNotCreateANewRecord: `No se pudo crear un nuevo registro`,
  country: `País`,
  createANewAccountFailed: `No se pudo crear una nueva cuenta`,
  createNewAccount: `Crear una nueva cuenta`,
  delete: `Eliminar`,
  deleteArt: `Borrar arte`,
  deletePost: `Borrar publicación`,
  description: `Descripción`,
  details: `Detalles`,
  didntReceiveEmail: `¿No recibió correo electrónico?`,
  donations: `Donaciones`,
  done: `Hecho`,
  drawingContest: `Concurso de dibujo`,
  earningFromArts: `Ganar de las artes`,
  edit: `Editar`,
  editPost: `Editar el post`,
  editProfile: `Editar el perfil`,
  editTranslations: `Editar traducciones`,
  email: `Correo electrónico`,
  emailAlreadyUsedByAnotherAccount: `El correo electrónico ya es usado por otra cuenta`,
  emailSubscription: `Suscripción de correo electrónico`,
  enterOrPasteALink: `(en) Enter or paste a link`,
  error404NotFound: `Error 404 - No encontrado`,
  errorPleaseContactCustomerSupport: `¡Error! Póngase en contacto con el servicio de atención al cliente...`,
  exitEditor: `Salir del editor`,
  extensions: `Extensiones`,
  fileSizeIsTooBig: `El tamaño del archivo es demasiado grande`,
  filter: `Filtrar`,
  filterBy: `Filtrar por`,
  findUser: `(en) Find user`,
  follow: `Seguir`,
  followMeOn: `Sigueme en`,
  followUsOnTwitter: `Síguenos en Twitter`,
  forAllOtherInquiriesPleaseContactUsAt: `Para todas las demás consultas, comuníquese con nosotros a:`,
  forgotPassword: `Se te olvidó tu contraseña`,
  forNewMasterpieces: `Por nuevas obras maestras`,
  four04: `— 404! —`,
  getDetails: `Obtener detalles`,
  guestView: `Vista de invitado`,
  homepage: `Página de inicio `,
  iAgreeWith: `Estoy de acuerdo con`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `La altura del img debe ser mayor o igual que`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `El ancho de la imagen debe ser mayor o igual que`,
  introduction: `Introducción`,
  invalidCode: `Codigo invalido`,
  invalidPartAfterAt: `Pieza no válida después de @`,
  invalidPartBeforeAt: `Pieza no válida antes de @`,
  joinChat: `Unirse al chat`,
  joinUsOnFacebook: `Únete a nosotros en Facebook`,
  languages: `Idiomas`,
  linkCopiedToClipboard: `(en) Link copied to clipboard`,
  livingIn: `Viviendo en`,
  logout: `Cerrar la sesión`,
  maximumNChars: (n) => `Máximo ${n} caracteres`,
  maxSize: `Tamaño máximo`,
  menu: `Menú`,
  message: `Mensaje`,
  messages: `Mensajes`,
  minHeight: `Altura mínima`,
  minimumNChars: (n) => `Mínimo ${n} caracteres`,
  minWidth: `Ancho mínimo`,
  moreFrom: (n) => `Más de ${n}`,
  mustBeNChars: (n) => `Debe tener ${n} caracteres`,
  need1Lowercase: `Necesita 1 minúscula`,
  need1Number: `Necesita 1 número`,
  need1Uppercase: `Necesita 1 mayúscula`,
  needAtLeast1CharacterFromN: (n) => `Necesita al menos 1 carácter de [${n}]`,
  needNCharacter: (n) => `Debe tener ${n} carácter`,
  newAccount: `Nueva cuenta`,
  newArt: `Arte nuevo`,
  newBlog: `Nuevo blog`,
  newPassword: `Nueva contraseña`,
  newsFeed: `Noticias`,
  no: `No`,
  noAddedFavoriteArts: `no hay obras favoritas añadidas`,
  noInternetConnection: `¡Sin conexión a Internet!`,
  nsfwContent18Plus: `Contenido NSFW (18+)`,
  ohNoItIsNotHere: `¡Oh no! ¡No está aqui!`,
  oldPassword: `Contraseña anterior`,
  online: `En línea`,
  onlyHexNumbersStartsWithTChar: `Solo números hexadecimales [0-9a-fA-F], comienzan con 't' char`,
  onlyLatinLettersNumbersOrSpecialSymbols: `Solo letras latinas, números, símbolos especiales`,
  onlyNumbers: `Sólo números`,
  openGuestView: `Abrir la vista de invitados`,
  openingSoon: `¡Próxima apertura!`,
  or: `O`,
  password: `Contraseña`,
  payments: `Pagos`,
  pleaseCheckYour: `Por favor, compruebe su`,
  pleaseDropOnlyOneImage: `Por favor suelte solo una imagen`,
  pleaseEnterAtLeastNChars: (n) => `Por favor ingrese al menos ${n} caracteres`,
  pleaseFillOutYourDetails: `Por favor complete sus datos`,
  pleaseSignInToYourAccount: `Por favor ingrese a su cuenta`,
  pleaseTryAgainOrClick: (n) => `Intente de nuevo o haga clic en ${n}`,
  pleaseVerifyYourAccount: `Por favor verifique su cuenta`,
  pressHereTo: `Presione aquí para`,
  privacyPolicy: `Política de Privacidad`,
  profile: `Perfil`,
  save: `Guardar`,
  saveAvatar: `Guardar avatar`,
  saveChanges: `Guardar cambios`,
  selectAnime: `Seleccionar anime`,
  selectAvatar: `Seleccionar avatar`,
  selectCharacters: `Seleccionar personaje(s)`,
  selectFile: `Seleccionar archivo`,
  selectThumbnail: `Seleccionar miniatura`,
  sendEmail: `Enviar correo electrónico`,
  settings: `Configuraciones`,
  shareYourStory: `¡Comparte tu historia!`,
  shop: `Tienda`,
  showLess: `(en) Show less`,
  showMore: `(en) Show more`,
  signIn: `Iniciar sesión`,
  skip: `Omitir`,
  socialMedia: `Redes sociales`,
  spaceCharacterIsNotAllowed: `El carácter de espacio no está permitido`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Siga talentos para estar al tanto de su progreso`,
  successChangedPasswordPleaseSignIn: `¡Éxito! Contraseña cambiada. Por favor inicie sesión`,
  successCreatedRecord: `¡Éxito! Registro creado!`,
  successUpdatedRecord: `¡Éxito! Registro actualizado!`,
  supportMeOn: `Apóyame en`,
  tellUsAboutYourself: `Cuéntanos acerca de tí`,
  termsAndConditions: `Términos y condiciones`,
  termsOfUse: `Condiciones de uso`,
  title: `Título`,
  typeYourTextHere: `Escribe tu texto aquí...`,
  uploadAnotherArt: `Subir otro arte`,
  uploadAnotherAvatar: `Subir otro avatar`,
  uploadArtNow: `¡Sube arte ahora!`,
  uploadNew: `Subir nuevo`,
  uploadNewArt: `Subir arte nuevo`,
  uploadNewPost: `Subir nueva publicación`,
  username: `Nombre de usuario`,
  usernameAlreadyExists: `Nombre de usuario ya existe`,
  valueIsNotTheSame: `El valor no es el mismo`,
  verificationCode: `Código de verificación`,
  verifyCode: `Código de verificación`,
  visitOurDiscordChannelToGetMoreDetails: `Visite nuestro canal de desacuerdos para obtener más detalles`,
  weAreOnInstagram: `Nosotros estamos en Instagram`,
  weAreWorkingOnIt: `Estamos trabajando en ello`,
  weDoNotDisplayNSFWContentYet: `Todavía no mostramos contenido NSFW`,
  weHaveSentTooManyVerificationEmails: `Hemos enviado demasiados correos electrónicos de verificación. Vuelva a intentarlo transcurridos unos minutos.`,
  welcomeToAnimeClub: `¡Bienvenido a Anime.club!`,
  weSentAnEmailTo: `Enviamos un correo electrónico a:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Le enviamos un nuevo correo electrónico de verificación. Por favor ingrese el código`,
  weSupportOnlyTheFollowingFileExtensions: `Solo admitimos las siguientes extensiones de archivo:`,
  wrongEmailOrPassword: `Correo electrónico o contraseña incorrectos`,
  yes: `si`,
  youAreAlreadyAuthenticated: `Ya estas autenticado`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Todavía puede navegar a las páginas abiertas anteriormente`,
  youDidNotSelectAnyChats: `(en) You did not select any chats`,
  youDidNotUpdateAnyValues: `No actualizaste ningún valor`,
  youDoNotHaveAnyChats: `(en) You do not have any chats`,
  youHaveNotSavedAnyChanges: `No ha guardado ningún cambio.`,
  yourAccountIsVerifiedPleaseSignIn: `Su cuenta está verificada. Por favor inicie sesión`,
  yourArts: `Tus artes`,
  yourAvatar: `Tu avatar`,
  yourBlog: `Tu blog`,
  yourFansAreWaiting: `Tus fans estan esperando`,
  yourFeedIsEmpty: `su muro está vacío`,
  yourSessionHasExpiredPleaseSignInAgain: `Tu sesión ha expirado, por favor inicie sesión de nuevo`,
}
