export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `เกี่ยวกับ`,
  accept: `ยอมรับ`,
  account: `(en) Account`,
  accountActivation: `เปิดใช้งานบัญชีผู้ใช้`,
  accountAlreadyExists: `มีบัญชีผู้ใช้นี้แล้ว`,
  accountDoesNotExist: `ไม่พบบัญชีผู้ใช้นี้`,
  add: `เพิ่ม`,
  addArt: `เพิ่มงานวาด`,
  addBlog: `เพิ่มบล็อก`,
  addFile: `(en) Add file`,
  additionalResources: `(en) Additional resources`,
  addMore: `(en) Add more`,
  addNewArt: `เพิ่มงานวาดใหม่`,
  addPreview: `เพิ่มพรีวิว`,
  addSignInVia: `เพิ่มการเข้าสู่ระบบผ่าน`,
  addToCart: `(en) Add to cart`,
  advancedOptions: `(en) Advanced options`,
  all: `ทั้งหมด`,
  alreadySignedIn: `เข้าสู่ระบบแล้ว`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (...v) =>
    `(en) Amount should not be less than ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `ผลงานลายเส้นอนิเมะจากศิลปินทั่วโลก ศิลปะได้รับการจัดการให้เกี่ยวข้องกับอนิเมะ การเลือกศิลปะเป็นรายการศิลปะอะนิเมะที่ดีที่สุดที่ไม่มีที่สิ้นสุด`,
  animeArtSubscribeToArtistsLikeAndCreate: `ผลงานอนิเมะ - ติดตามศิลปิน ถูกใจ และสร้างคอลเลกชัน`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - แพลตฟอร์มแรกที่สนับสนุนศิลปินด้วยรายได้จากยอดวิวผ่าน Google AdSense สนับสนุนศิลปินด้วยการเยี่ยมชมผลงานของพวกเขาหรือเริ่มทำเงินจากยอดวิว`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - เข้าชม โพสต์ผลงาน และทำเงินจากเนื้อหาอนิเมะ`,
  animeCommunity: `คอมมูนิตี้ของเหล่าสาวกอนิเมะ`,
  animeDotclubNeverAsksForYourPrivateInformation: `(en) Anime.club never asks for your private information`,
  animeSocialNetwork: `(en) Anime
Social Network`,
  announcements: `(en) Announcements`,
  apply: `ใช้`,
  appSettings: `(en) App settings`,
  appsVersionIs: `แอปเวอร์ชัน`,
  areYouSureYouWantTo: `คุณแน่ใจหรือว่าจะ`,
  art: `ผลงาน`,
  artAssociatedWithAnime: `ผลงานที่เกี่ยวข้องกับอนิเมะ`,
  artBy: (...v) => `(en) Art by ${v[0]}`,
  artCannotBeChanged: `ไม่สามารถเปลี่ยนผลงาน`,
  artworksAvailableToView: (...v) => `(en) ${v[0]} artworks available to view`,
  authenticationFailed: `การยืนยันตัวตนล้มเหลว`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `กลับ`,
  blog: `บล็อก`,
  bookmarks: `บุ๊กมาร์ก`,
  browseArt: `ค้นหาผลงาน`,
  cancel: `ยกเลิก`,
  cannotStartWithChars: `ห้ามมี s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `(en) Change`,
  changeArt: `เปลี่ยนผลงาน`,
  changeAvatar: `เปลี่ยนรูปประจำตัว`,
  changeEmail: `(en) Change email`,
  changePassword: `เปลี่ยนรหัสผ่าน`,
  chooseExistingChatOrStartANewOne: `เลือกห้องแชทเดิมหรือสร้างใหม่`,
  city: `เมือง`,
  clearAll: `ลบออกทั้งหมด`,
  close: `ปิด`,
  colorTheme: `(en) Color theme`,
  comingSoon: `เร็วๆ นี้...`,
  commercialUse: `(en) Commercial use`,
  community: `คอมมูนิตี้`,
  confirmAccount: `ยืนยันบัญชี`,
  confirmPassword: `ยืนยันรหัสผ่าน`,
  connectWithUsOn: `(en) Connect with us on`,
  contactInformation: `(en) Contact information`,
  continue: `(en) Continue`,
  contractTitle: `(en) Contract Title`,
  copyLink: `คัดลอกลิงก์`,
  couldNotCreateANewRecord: `ไม่สามารถสร้างบันทึกใหม่ได้`,
  country: `ประเทศ`,
  cover: `(en) Cover`,
  createANewAccountFailed: `การสร้างบัญชีใหม่ล้มเหลว`,
  createExtrasForYourProduct: `(en) Create extras for your product`,
  createNewAccount: `สร้างบัญชีใหม่`,
  createYourShop: `(en) Create your shop`,
  currentPassword: `(en) Current password`,
  daily: `(en) Daily`,
  darkDefault: `(en) Dark default`,
  darkHighContrast: `(en) Dark high contrast`,
  dayTheme: `(en) Day theme`,
  delete: `ลบ`,
  deleteArt: `ลบผลงาน`,
  deletePost: `ลบโพสต์`,
  deleteProduct: `(en) Delete product`,
  deliveryTime: `(en) Delivery time`,
  describeTheDetailsOfYourProduct: `(en) Describe the details of your product`,
  description: `คำอธิบาย`,
  details: `รายละเอียด`,
  didntReceiveEmail: `ยังไม่ได้รับอีเมลใช่ไหม`,
  displayName: `(en) Display name`,
  donations: `การบริจาค`,
  done: `เสร็จ`,
  dragAndDropOrSelectFiles: `(en) Drag & Drop or Select file(s)`,
  drawingContest: `ประกวดวาดภาพ`,
  dueDate: `(en) Due date`,
  earlier: `(en) Earlier`,
  earningFromArts: `ทำเงินจากผลงาน`,
  edit: `แก้ไข`,
  editPost: `แก้ไขโพสต์`,
  editProfile: `แก้ไขโปรไฟล์`,
  editTranslations: `แก้ไขการแปลภาษา`,
  email: `อีเมล`,
  emailAlreadyUsedByAnotherAccount: `อีเมลใช้กับบัญชีอื่นแล้ว`,
  emailNotifications: `(en) Email Notifications`,
  enterOrPasteALink: `ป้อนลิงก์หรือวางลิงก์`,
  enterTheAddressAssociatedWithYourAccount: `(en) Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `(en) Enter your password`,
  error: `(en) Error`,
  errorPleaseContactCustomerSupport: `เกิดข้อผิดพลาด! โปรดติดต่อเจ้าหน้าที่ให้บริการ...`,
  exitEditor: `ออกจากการแก้ไข`,
  extensions: `ขยาย`,
  extras: `(en) Extras`,
  fileSizeIsTooBig: `ขนาดไฟล์ใหญ่เกินไป`,
  filter: `คัดกรอง`,
  filterBy: `คัดกรองจาก`,
  findUser: `ค้นหาผู้ใช้`,
  follow: `ติดตาม`,
  followers: `ผู้ติดตาม`,
  following: `กำลังติดตาม`,
  followMeOn: `ติดตามฉันผ่าน`,
  follows: `(en) Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `สำหรับการติดต่อในเรื่องอื่นๆ โปรดติดต่อเราผ่าน`,
  forgotPassword: `ลืมรหัสผ่าน`,
  fromAnimeDotClub: `(en) From anime.club`,
  getDetails: `ดูรายละเอียด`,
  getStarted: `(en) Get started`,
  guestView: `ผู้เยี่ยมชมชั่วคราว`,
  hasNotAddedADescriptionFor: (...v) =>
    `(en) @${v[0]} has not added a description for "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `(en) @${v[0]} has not shared any public details yet`,
  hire: `(en) Hire`,
  homepage: `หน้าหลัก`,
  howToContactYou: `(en) How to contact you`,
  howToFindYouOnOtherSocialNetworks: `(en) How to find you on other social networks`,
  iAgreeWith: `ฉันเห็นด้วยกับ`,
  id: `รหัสไอดี`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `ความสูงของรูปต้องมากกว่าหรือเท่ากับ`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `ความกว้างของรูปต้องมากกว่าหรือเท่ากับ`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `(en) Include keywords that buyers would likely use to search for a product like yours`,
  introduction: `แนะนำตัว`,
  invalidCode: `รหัสไม่ถูกต้อง`,
  invalidCurrentPassword: `(en) Invalid current password`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `ส่วนไม่ถูกต้องหลังจาก @`,
  invalidPartBeforeAt: `ส่วนไม่ถูกต้องก่อน @`,
  jobDetails: `(en) Job Details`,
  joinAnimeClubCommunity: `(en) Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `เข้าร่วมแชท`,
  joinUsOnFacebook: `ติดตามเราผ่าน Facebook`,
  language: `(en) Language`,
  languages: `ภาษา`,
  letEveryoneKnowHowToDonateToYou: `(en) Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `(en) Let others know about you`,
  licenseForForProfitBusinessUse: `(en) License for for-profit business use`,
  lightDefault: `(en) Light default`,
  lightHighContrast: `(en) Light high contrast`,
  likes: `ถูกใจ`,
  linkCopiedToClipboard: `คัดลอกลิงก์ไปยังคลิปบอร์ดแล้ว`,
  livesIn: `อาศัยอยู่ใน`,
  loading: `(en) Loading`,
  location: `(en) Location`,
  logInOrSignUp: `(en) Log in or sign up`,
  logOut: `(en) Log out`,
  maximumNChars: (...v) => `สูงสุด ${v[0]} ตัวอักษร`,
  maximumNumberOfDaysToCompleteTheOrder: `(en) Maximum number of days to complete the order`,
  maximumQuantity: `(en) Maximum quantity`,
  maxSize: `ขนาดสูงสุด`,
  menu: `เมนู`,
  message: `ข้อความ`,
  messages: `ข้อความ`,
  minHeight: `ความสูงขั้นต่ำ`,
  minimumNChars: (...v) => `ขั้นต่ำ ${v[0]} ตัวอักษร`,
  minWidth: `ความกว้างข้นต่ำ`,
  monthly: `(en) Monthly`,
  moreFrom: (...v) => `อื่นๆ จาก ${v[0]}`,
  mustBeNChars: (...v) => `ต้องมี ${v[0]} ตัวอักขระ`,
  myPayments: `(en) My payments`,
  myProfile: `(en) My profile`,
  mySettings: `(en) My settings`,
  need1Lowercase: `ต้องมี 1 ตัวพิมพ์เล็ก`,
  need1Number: `ต้องมี 1 ตัวเลข`,
  need1Uppercase: `ต้องมี 1 ตัวพิมพ์ใหญ่`,
  needAtLeast1CharacterFromN: (...v) =>
    `ต้องมีอย่างน้อย 1 ตัวอักษรจาก  [${v[0]}]`,
  needNCharacter: (...v) => `ต้องมี ${v[0]} ตัวอักษร`,
  newAccount: `บัญชีใหม่`,
  newArt: `ผลงานใหม่`,
  newArtworks: `(en) New artworks`,
  newBlog: `บล็อกใหม่`,
  newPassword: `รหัสผ่านใหม่`,
  newProduct: `(en) New product`,
  newsFeed: `ฟีดข่าว`,
  next: `(en) Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `(en) Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `(en) Night theme`,
  no: `ไม่`,
  noAddedFavoriteArts: `ยังไม่ได้เพิ่มผลงานที่ชื่นชอบ`,
  noInternetConnection: `ไม่ได้เชื่อมต่ออินเทอร์เน็ต!`,
  none: `(en) None`,
  noNotifications: `(en) No notifications`,
  noResults: `(en) No results`,
  notifications: `การแจ้งเตือน`,
  nsfwContent18Plus: `เนื้อหา NSFW (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `(en) Number of adjustments a client could request`,
  online: `ออนไลน์`,
  onlyLatinLettersNumbersHyphen: `(en) Only latin letters, numbers, hyphen, underscore, and dot characters`,
  onlyNumbers: `เฉพาะตัวเลข`,
  open: `(en) Open`,
  openGuestView: `เปิดโหมดผู้เยี่ยมชมชั่วคราว`,
  openingSoon: `จะมาเร็วๆ นี้!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `หรือ`,
  orderOptions: `(en) Order Options`,
  pageNotFound: `(en) Page not found`,
  password: `รหัสผ่าน`,
  payments: `การชำระเงิน`,
  personal: `(en) Personal`,
  pleaseCheckYour: (...v) => `(en) Please check your ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `(en) Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `โปรดลงแค่รูปเดียว`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `(en) Please enter a number between ${v[0]} and ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `โปรดใส่ตัวอักษรอย่างน้อย ${v[0]} ตัว`,
  pleaseFillOutYourDetails: `โปรดใส่รายละเอียดเพิ่มเติม`,
  pleaseSignInToYourAccount: `โปรดลงชื่อเข้าใช้บัญชีของคุณ`,
  pleaseTryAgainOrClick: (...v) => `โปรดลองอีกครั้งหรือคลิก ${v[0]}`,
  pleaseVerifyYourAccount: `โปรดยืนยันบัญชีของคุณ`,
  pressHereTo: `กดที่นี่เพื่อ`,
  price: `(en) Price`,
  privacyPolicy: `นโยบายความเป็นส่วนตัว`,
  privateInformation: `(en) Private information`,
  product: `(en) Product`,
  profile: `โปรไฟล์`,
  promotions: `(en) Promotions`,
  publicInformation: `(en) Public information`,
  publishOn: (...v) => `(en) Publish on ${v[0]}`,
  rankings: `(en) Rankings`,
  reorderFiles: `(en) Reorder files`,
  report: `(en) Report`,
  revisions: `(en) Revisions`,
  save: `บันทึก`,
  saveAvatar: `บันทึกรูปประจำตัว`,
  saveChanges: `บันทึกการเปลี่ยนแปลง`,
  selectAnime: `เลือกอนิเมะ`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `(en) Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `เลือกรูปประจำตัว`,
  selectCharacters: `เลือกตัวละคร`,
  selectFile: `เลือกไฟล์`,
  selectTheme: `(en) Select theme`,
  selectThumbnail: `เลือกภาพขนาดย่อ`,
  sendEmail: `ส่งอีเมล`,
  settings: `การตั้งค่า`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `(en) Setting up a shop is free and only takes a few minutes`,
  share: `(en) Share`,
  shareYourArtWithTheWorld: `(en) Share your art with the world`,
  shareYourStory: `แชร์เรื่องราวของคุณ!`,
  shop: `ร้านค้า`,
  showLess: `แสดงน้อยลง`,
  showMore: `แสดงเพิ่มขึ้น`,
  signIn: `เข้าสู่ระบบ`,
  singleTheme: `(en) Single theme`,
  size: `(en) Size`,
  skip: `ข้าม`,
  socialMedia: `โซเชียลมีเดีย`,
  spaceCharacterIsNotAllowed: `ไม่อนุญาตให้เว้นวรรค`,
  subscribeToTalentsToKeepUpWithTheirProgress: `สมัครรับการอัปเดตเนื้อหาเพื่อติดตามความคืบหน้า`,
  successChangedPasswordPleaseSignIn: `สำเร็จแล้ว! เปลี่ยนรหัสผ่านเรียบร้อย โปรดลงชื่อเข้าใช้`,
  successCreatedRecord: `สำเร็จแล้ว! สร้างบักทึกเรียบร้อย!`,
  successUpdatedRecord: `สำเร็จแล้ว! อัปเดตบักทึกเรียบร้อย!`,
  supportMeOn: `สนับสนุนฉันผ่าน`,
  syncWithSystem: `(en) Sync with system`,
  tellUsAboutYourself: `บอกเรื่องราวเกี่ยวกับตัวคุณ`,
  termsAndConditions: `ข้อกำหนดและเงื่อนไข`,
  termsOfUse: `ข้อตกลงในการใช้งาน`,
  theLinkIsBrokenOrPageHasBeenRemoved: `(en) The link is broken or page has been removed`,
  themeMode: `(en) Theme mode`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `หัวข้อ`,
  titleYourExtraService: `(en) Title your extra service`,
  today: `(en) Today`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  total: `(en) Total`,
  typeYourTextHere: `พิมพ์ข้อความที่นี่...`,
  unlimited: `(en) Unlimited`,
  upload: `(en) Upload`,
  uploadNew: `อัปโหลดใหม่`,
  uploadNewPost: `อัปโหลดโพสต์ใหม่`,
  username: `ชื่อผู้ใช้`,
  usernameAlreadyExists: `ชื่อผู้ใช้นี้มีอยู่แล้ว`,
  usernameAndXMoreFollowYou: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more follow you`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more like your artwork`,
  usernameFollowsYou: (...v) => `(en) <b>${v[0]}</b> follows you`,
  usernameLikesYourArt: (...v) => `(en) <b>${v[0]}</b> likes your art`,
  useThisEmailTo: `(en) Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `ค่าไม่เหมือนกัน`,
  verificationCode: `รหัสยืนยัน`,
  verifyCode: `ตรวจสอบรหัส`,
  viewEveryNotificationOfAGroupSeparately: `(en) View every notification of a group separately`,
  visitOurDiscordChannelToGetMoreDetails: `เข้าร่วมกลุ่ม Discord ของเราเพื่อดูข้อมูลเพิ่มเติม!`,
  weAreOnInstagram: `ติดตามเราผ่านทาง Instagram`,
  weAreWorkingOnIt: `เรากำลังดำเนินการอยู่`,
  weDoNotDisplayNSFWContentYet: `เราไม่สามารถเปิดเผยผลงานที่เป็น NSFW`,
  weekly: `(en) Weekly`,
  weHaveSentTooManyEmails: `(en) We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `ยินดีต้อนรับสู่ Anime.club!`,
  weSentAnEmailTo: `เราได้ส่งอีเมลไปยัง`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `เราได้ส่งรหัสยืนยันตัวตนใหม่ให้คุณทางอีเมลแล้ว โปรดป้อนรหัสผ่าน`,
  weSupportOnlyTheFollowingFileExtensions: `เรารองรับเฉพาะไฟล์ต่อไปนี้`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `อีเมลหรือรหัสผ่านไม่ถูกต้อง`,
  yes: `ใช่`,
  yesterday: `(en) Yesterday`,
  youAreAlreadyAuthenticated: `คุณได้ทำการยืนยันตัวตนแล้ว`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `(en) You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `คุณยังสามารถกลับไปที่หน้าเดิมได้`,
  youDidNotSelectAnyChats: `คุณยังไม่ได้เลือกการแชทเลย`,
  youDidNotUpdateAnyValues: `คุณยังไม่ได้อัปเดตค่าเลย`,
  youDoNotHaveAnyChats: `คุณยังไม่มีการแชทเลย`,
  youHaveNotSavedAnyChanges: `คุณยังไม่ได้บันทึกการเปลี่ยนแปลงนะ`,
  youHaveNotSetAPassword: `(en) You have not set a password`,
  youHaveNotSharedAnythingYet: `(en) You have not shared anything yet`,
  youHaveReachedTheMaximumNumberOfFiles: `(en) You have reached the maximum number of files`,
  yourAccountIsVerifiedPleaseSignIn: `บัญชีของคุณได้รับการยืนยันแล้ว โปรดลงชื่อเข้าใช้บัญชี`,
  yourArts: `ผลงานของคุณ`,
  yourAvatar: `รูปประจำตัวของคุณ`,
  yourBlog: `บล็อกของคุณ`,
  yourFansAreWaiting: `แฟนๆ กำลังรอคุณอยู่นะ`,
  yourFeedIsEmpty: `ฟีดของคุณยังว่างเปล่าอยู่นะ`,
  yourSessionHasExpiredPleaseSignInAgain: `เซสชันของคุณหมดอายุแล้ว โปรดลองใหม่อีกครั้ง`,
}
