export const text: text = {
  checkOrderStatus: `(en) Check order status`,
  congratulations: `(en) Congratulations!`,
  deleteShop: `(en) Delete shop`,
  decline: `(en) Decline`,
  letsUploadYourFirstProduct: `(en) Let's upload your first product`,
  openDispute: `(en) Open dispute`,
  ordered: (...v) => `(en) Ordered ${v[0]}`,
  theMaximumQuantityThatACustomerCanAdd: `(en) The maximum quantity that a customer can add`,
  toHelpTheCreatorCompleteYourOrder: `(en) To help the creator complete your order to your satisfaction, please provide a detailed description of what you want. Include the desired theme, style, and character features, as well as any other important specifications`,
  viewReview: `(en) View review`,
  youHaveSuccessfullyCreatedYourShop: `(en) You have successfully created your shop`,
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `เกี่ยวกับ`,
  accept: `ยอมรับ`,
  acceptOrder: `ยอมรับคำสั่งซื้อ`,
  account: `บัญชีผู้ใช้`,
  accountActivation: `เปิดใช้งานบัญชีผู้ใช้`,
  accountAlreadyExists: `มีบัญชีผู้ใช้นี้แล้ว`,
  accountDoesNotExist: `ไม่พบบัญชีผู้ใช้นี้`,
  accountRemoval: `การลบบัญชี`,
  add: `เพิ่ม`,
  addArt: `เพิ่มงานวาด`,
  addBlog: `เพิ่มบล็อก`,
  addFile: `เพิ่มไฟล์`,
  additionalResources: `ทรัพยากรเพิ่มเติม`,
  addMore: `เพิ่มเติม`,
  addNewArt: `เพิ่มงานวาดใหม่`,
  addPreview: `เพิ่มพรีวิว`,
  addSignInVia: `เพิ่มการเข้าสู่ระบบผ่าน`,
  addToCart: `เพิ่มลงในตะกร้า`,
  advancedOptions: `ตัวเลือกขั้นสูง`,
  all: `ทั้งหมด`,
  alreadySignedIn: `เข้าสู่ระบบแล้ว`,
  amount: `จำนวน`,
  amountShouldNotBeLessThan: (...v) => `จำนวนไม่ควรน้อยกว่า ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `ผลงานลายเส้นอนิเมะจากศิลปินทั่วโลก ศิลปะได้รับการจัดการให้เกี่ยวข้องกับอนิเมะ การเลือกศิลปะเป็นรายการศิลปะอะนิเมะที่ดีที่สุดที่ไม่มีที่สิ้นสุด`,
  animeArtSubscribeToArtistsLikeAndCreate: `ผลงานอนิเมะ - ติดตามศิลปิน ถูกใจ และสร้างคอลเลกชัน`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - แพลตฟอร์มแรกที่สนับสนุนศิลปินด้วยรายได้จากยอดวิวผ่าน Google AdSense สนับสนุนศิลปินด้วยการเยี่ยมชมผลงานของพวกเขาหรือเริ่มทำเงินจากยอดวิว`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - เข้าชม โพสต์ผลงาน และทำเงินจากเนื้อหาอนิเมะ`,
  animeCommunity: `คอมมูนิตี้ของเหล่าสาวกอนิเมะ`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club ไม่เคยขอข้อมูลส่วนตัวของคุณ`,
  animeSocialNetwork: `เครือข่ายสังคมแอนิเมะ`,
  announcements: `ประกาศ`,
  apply: `ใช้`,
  appSettings: `การตั้งค่าแอป`,
  appsVersionIs: `แอปเวอร์ชัน`,
  areYouSureYouWantTo: `คุณแน่ใจหรือว่าจะ`,
  art: `ผลงาน`,
  artAssociatedWithAnime: `ผลงานที่เกี่ยวข้องกับอนิเมะ`,
  artBy: (...v) => `ศิลปะโดย ${v[0]}`,
  artCannotBeChanged: `ไม่สามารถเปลี่ยนผลงาน`,
  artworksAvailableToView: (...v) => `มีงานศิลป์ ${v[0]} ชิ้นที่สามารถดูได้`,
  authenticationFailed: `การยืนยันตัวตนล้มเหลว`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `การเผยแพร่อัตโนมัติไปยัง Instagram สามารถใช้ได้เฉพาะบัญชีธุรกิจ Instagram เท่านั้น`,
  awaitingReview: `รอการตรวจสอบ`,
  awaitingSeller: `รอผู้ขาย`,
  back: `กลับ`,
  basePrice: `ราคาฐาน`,
  block: `บล็อก`,
  blockUser: (...v) => `บล็อก @${v[0]}`,
  blog: `บล็อก`,
  bookmarks: `บุ๊กมาร์ก`,
  browseArt: `ค้นหาผลงาน`,
  browseShop: `เรียกดูร้านค้า`,
  cancel: `ยกเลิก`,
  canceled: `ยกเลิกแล้ว`,
  cancelOrder: `ยกเลิกคำสั่งซื้อ`,
  cannotStartWithChars: `ห้ามมี s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `เปลี่ยนแปลง`,
  changeArt: `เปลี่ยนผลงาน`,
  changeAvatar: `เปลี่ยนรูปประจำตัว`,
  changeEmail: `เปลี่ยนอีเมล`,
  changePassword: `เปลี่ยนรหัสผ่าน`,
  chooseExistingChatOrStartANewOne: `เลือกห้องแชทเดิมหรือสร้างใหม่`,
  city: `เมือง`,
  clearAll: `ลบออกทั้งหมด`,
  clientReview: `รีวิวลูกค้า`,
  close: `ปิด`,
  colorTheme: `ธีมสี`,
  comingSoon: `เร็วๆ นี้...`,
  commercialUse: `ใช้เพื่อการค้า`,
  community: `คอมมูนิตี้`,
  completed: `เสร็จสมบูรณ์แล้ว`,
  confirmAccount: `ยืนยันบัญชี`,
  confirmOrder: `ยืนยันคำสั่งซื้อ`,
  confirmPassword: `ยืนยันรหัสผ่าน`,
  connectWithUsOn: `เชื่อมต่อกับเราบน`,
  contactCustomer: `ติดต่อลูกค้า`,
  contactInformation: `ข้อมูลติดต่อ`,
  contactSeller: `ติดต่อผู้ขาย`,
  contactSupport: `ติดต่อฝ่ายสนับสนุน`,
  continue: `ต่อไป`,
  contractTitle: `ชื่อสัญญา`,
  copyLink: `คัดลอกลิงก์`,
  copyrightViolation: `การละเมิดลิขสิทธิ์`,
  couldNotCreateANewRecord: `ไม่สามารถสร้างบันทึกใหม่ได้`,
  country: `ประเทศ`,
  cover: `ปก`,
  createANewAccountFailed: `การสร้างบัญชีใหม่ล้มเหลว`,
  createExtrasForYourProduct: `สร้างสิ่งที่เพิ่มเติมสำหรับผลิตภัณฑ์ของคุณ`,
  createNewAccount: `สร้างบัญชีใหม่`,
  createYourShop: `สร้างร้านค้าของคุณ`,
  currentPassword: `รหัสผ่านปัจจุบัน`,
  daily: `รายวัน`,
  darkDefault: `ค่าเริ่มต้นสีเข้ม`,
  darkHighContrast: `ความคมชัดสีเข้ม`,
  dayTheme: `ธีมวัน`,
  delete: `ลบ`,
  deleteAccount: `ลบบัญชี`,
  deleteArt: `ลบผลงาน`,
  deletePost: `ลบโพสต์`,
  deleteProduct: `ลบผลิตภัณฑ์`,
  deliveryTime: `เวลาจัดส่ง`,
  describeTheDetailsOfYourProduct: `อธิบายรายละเอียดของผลิตภัณฑ์ของคุณ`,
  description: `คำอธิบาย`,
  details: `รายละเอียด`,
  didntReceiveEmail: `ยังไม่ได้รับอีเมลใช่ไหม`,
  displayName: `ชื่อที่แสดง`,
  disputed: `โต้แย้ง`,
  donations: `การบริจาค`,
  done: `เสร็จ`,
  dragAndDropOrSelectFiles: `ลากและวางหรือเลือกไฟล์`,
  drawingContest: `ประกวดวาดภาพ`,
  dueDate: `วันที่ครบกำหนด`,
  earlier: `ก่อนหน้า`,
  earningFromArts: `ทำเงินจากผลงาน`,
  edit: `แก้ไข`,
  editPost: `แก้ไขโพสต์`,
  editProfile: `แก้ไขโปรไฟล์`,
  editTranslations: `แก้ไขการแปลภาษา`,
  email: `อีเมล`,
  emailAlreadyUsedByAnotherAccount: `อีเมลใช้กับบัญชีอื่นแล้ว`,
  emailNotifications: `การแจ้งเตือนทางอีเมล`,
  enterOrPasteALink: `ป้อนลิงก์หรือวางลิงก์`,
  enterTheAddressAssociatedWithYourAccount: `ป้อนที่อยู่ที่เกี่ยวข้องกับบัญชีของคุณและเราจะส่งอีเมลถึงคุณเพื่อรีเซ็ตรหัสผ่านของคุณ`,
  enterYourPassword: `ป้อนรหัสผ่านของคุณ`,
  error: `ข้อผิดพลาด`,
  errorPleaseContactCustomerSupport: `เกิดข้อผิดพลาด! โปรดติดต่อเจ้าหน้าที่ให้บริการ...`,
  exitWithoutSaving: `ออกโดยไม่บันทึก`,
  extensions: `ขยาย`,
  extras: `สิ่งที่เพิ่มเติม`,
  fileSizeIsTooBig: `ขนาดไฟล์ใหญ่เกินไป`,
  filter: `คัดกรอง`,
  filterBy: `คัดกรองจาก`,
  findUser: `ค้นหาผู้ใช้`,
  finishSettingUpYourShop: `เสร็จสิ้นการตั้งค่าร้านค้าของคุณ`,
  follow: `ติดตาม`,
  followers: `ผู้ติดตาม`,
  following: `กำลังติดตาม`,
  followMeOn: `ติดตามฉันผ่าน`,
  follows: `ติดตาม`,
  forAllOtherInquiriesPleaseContactUsAt: `สำหรับการติดต่อในเรื่องอื่นๆ โปรดติดต่อเราผ่าน`,
  forgotPassword: `ลืมรหัสผ่าน`,
  fromAnimeDotClub: `จาก anime.club`,
  getDetails: `ดูรายละเอียด`,
  getStarted: `เริ่มต้น`,
  guestView: `ผู้เยี่ยมชมชั่วคราว`,
  harassment: `การรังแก`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]} ยังไม่ได้เพิ่มคำอธิบายสำหรับ "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} ยังไม่ได้เผยแพร่รายละเอียดสาธารณะใด ๆ อีกเลย`,
  hate: `เกลียด`,
  hire: `จ้าง`,
  homepage: `หน้าหลัก`,
  howToContactYou: `วิธีการติดต่อคุณ`,
  howToFindYouOnOtherSocialNetworks: `วิธีการค้นหาคุณในเครือข่ายสังคมอื่น ๆ`,
  iAgreeWith: `ฉันเห็นด้วยกับ`,
  id: `รหัสไอดี`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `ความสูงของรูปต้องมากกว่าหรือเท่ากับ`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `ความกว้างของรูปต้องมากกว่าหรือเท่ากับ`,
  impersonation: `การปลอมตัว`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `รวมคำสำคัญที่ผู้ซื้อจะใช้ค้นหาผลิตภัณฑ์ของคุณ`,
  inProgress: `กำลังดำเนินการ`,
  introduction: `แนะนำตัว`,
  invalidCode: `รหัสไม่ถูกต้อง`,
  invalidCurrentPassword: `รหัสผ่านปัจจุบันไม่ถูกต้อง`,
  invalidDate: `วันที่ไม่ถูกต้อง`,
  invalidPartAfterAt: `ส่วนไม่ถูกต้องหลังจาก @`,
  invalidPartBeforeAt: `ส่วนไม่ถูกต้องก่อน @`,
  jobDetails: `รายละเอียดงาน`,
  joinAnimeClubCommunity: `เข้าร่วมชุมชน Anime.club ที่มีผู้สร้างกิจกรรมกิจกรรมและศิลปะแอนิเมะที่เจ๋งๆ ทุกวัน`,
  joinChat: `เข้าร่วมแชท`,
  joinUsOnFacebook: `ติดตามเราผ่าน Facebook`,
  language: `ภาษา`,
  languages: `ภาษา`,
  letEveryoneKnowHowToDonateToYou: `ให้ทุกคนทราบวิธีการบริจาคให้คุณ`,
  letOthersKnowAboutYou: `ให้ผู้อื่นทราบเกี่ยวกับคุณ`,
  letUsKnowWhatsHappening: `แจ้งให้เรารู้ว่าเกิดอะไรขึ้นแล้วเราจะตรวจสอบ`,
  licenseForForProfitBusinessUse: `ใบอนุญาตสำหรับการใช้งานเพื่อกำไร`,
  lightDefault: `ค่าเริ่มต้นสีอ่อน`,
  lightHighContrast: `ความคมชัดสีอ่อน`,
  likes: `ถูกใจ`,
  linkCopiedToClipboard: `คัดลอกลิงก์ไปยังคลิปบอร์ดแล้ว`,
  livesIn: `อาศัยอยู่ใน`,
  loading: `กำลังโหลด`,
  location: `สถานที่ตั้ง`,
  logInOrSignUp: `เข้าสู่ระบบหรือลงทะเบียน`,
  logOut: `ออกจากระบบ`,
  maximumNChars: (...v) => `สูงสุด ${v[0]} ตัวอักษร`,
  maximumNumberOfDaysToCompleteTheOrder: `จำนวนวันสูงสุดที่จะทำคำสั่งซื้อเสร็จ`,
  maximumQuantity: `จำนวนสูงสุด`,
  maxSize: `ขนาดสูงสุด`,
  menu: `เมนู`,
  message: `ข้อความ`,
  messages: `ข้อความ`,
  minHeight: `ความสูงขั้นต่ำ`,
  minimumNChars: (...v) => `ขั้นต่ำ ${v[0]} ตัวอักษร`,
  minorAbuseOrSexualization: `การล่วงละเมิดหรือเซ็กซ์ที่ไม่เหมาะสม`,
  minWidth: `ความกว้างข้นต่ำ`,
  monthly: `รายเดือน`,
  moreFrom: (...v) => `อื่นๆ จาก ${v[0]}`,
  mustBeNChars: (...v) => `ต้องมี ${v[0]} ตัวอักขระ`,
  myPayments: `การชำระเงินของฉัน`,
  myProfile: `โปรไฟล์ของฉัน`,
  mySettings: `การตั้งค่าของฉัน`,
  need1Lowercase: `ต้องมี 1 ตัวพิมพ์เล็ก`,
  need1Number: `ต้องมี 1 ตัวเลข`,
  need1Uppercase: `ต้องมี 1 ตัวพิมพ์ใหญ่`,
  needAtLeast1CharacterFromN: (...v) =>
    `ต้องมีอย่างน้อย 1 ตัวอักษรจาก  [${v[0]}]`,
  needNCharacter: (...v) => `ต้องมี ${v[0]} ตัวอักษร`,
  newAccount: `บัญชีใหม่`,
  newArt: `ผลงานใหม่`,
  newArtworks: `งานศิลปะใหม่`,
  newBlog: `บล็อกใหม่`,
  newOrder: `คำสั่งซื้อใหม่`,
  newPassword: `รหัสผ่านใหม่`,
  newProduct: `ผลิตภัณฑ์ใหม่`,
  newsFeed: `ฟีดข่าว`,
  next: `ถัดไป`,
  nextTimeYouAuthenticateYouCouldUseThe: `ครั้งต่อไปที่คุณตรวจสอบตัวตนคุณสามารถใช้บัญชีที่เชื่อมต่อได้แทนการเข้าสู่ระบบและรหัสผ่าน`,
  nightTheme: `ธีมกลางคืน`,
  no: `ไม่`,
  noAddedFavoriteArts: `ยังไม่ได้เพิ่มผลงานที่ชื่นชอบ`,
  noInternetConnection: `ไม่ได้เชื่อมต่ออินเทอร์เน็ต!`,
  nonConsensualIntimateContent: `เนื้อหาส่วนตัวที่ไม่ได้รับความยินยอม`,
  none: `ไม่มี`,
  noNotifications: `ไม่มีการแจ้งเตือน`,
  noResults: `ไม่พบผลลัพธ์`,
  notifications: `การแจ้งเตือน`,
  noActiveOrdersToShow: `ไม่มีคำสั่งซื้อที่ใช้งานอยู่`,
  nsfwContent18Plus: `เนื้อหา NSFW (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `จำนวนการปรับเปลี่ยนที่ลูกค้าสามารถขอได้`,
  online: `ออนไลน์`,
  onlyLatinLettersNumbersHyphen: `เฉพาะตัวอักษรละตัวเลขขีดเส้นและขีดล่าง`,
  onlyNumbers: `เฉพาะตัวเลข`,
  open: `เปิด`,
  openGuestView: `เปิดโหมดผู้เยี่ยมชมชั่วคราว`,
  openingSoon: `จะมาเร็วๆ นี้!`,
  openToWork: `เปิดรับงาน`,
  optional: `ไม่บังคับ`,
  or: `หรือ`,
  orderAgain: `สั่งซื้ออีกครั้ง`,
  orderDetails: `รายละเอียดคำสั่งซื้อ`,
  orderStatus: `สถานะคำสั่งซื้อ`,
  orderOptions: `ตัวเลือกคำสั่งซื้อ`,
  pageNotFound: `ไม่พบหน้า`,
  password: `รหัสผ่าน`,
  payments: `การชำระเงิน`,
  personal: `ส่วนตัว`,
  pleaseCheckYour: (...v) => `โปรดตรวจสอบ${v[0]}ของคุณ`,
  pleaseDoNotShareYourPrivateInformationToOthers: `โปรดอย่าแชร์ข้อมูลส่วนตัวของคุณกับผู้อื่น`,
  pleaseDropOnlyOneImage: `โปรดลงแค่รูปเดียว`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `โปรดป้อนตัวเลขระหว่าง ${v[0]} และ ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `โปรดใส่ตัวอักษรอย่างน้อย ${v[0]} ตัว`,
  pleaseFillOutYourDetails: `โปรดใส่รายละเอียดเพิ่มเติม`,
  pleaseSignInToYourAccount: `โปรดลงชื่อเข้าใช้บัญชีของคุณ`,
  pleaseTryAgainOrClick: (...v) => `โปรดลองอีกครั้งหรือคลิก ${v[0]}`,
  pleaseVerifyYourAccount: `โปรดยืนยันบัญชีของคุณ`,
  pressHereTo: `กดที่นี่เพื่อ`,
  price: `ราคา`,
  privacyPolicy: `นโยบายความเป็นส่วนตัว`,
  privateInformation: `ข้อมูลส่วนตัว`,
  proceedToCheckout: `ไปที่ชำระเงิน`,
  product: `ผลิตภัณฑ์`,
  profile: `โปรไฟล์`,
  prohibitedTransaction: `ธุรกรรมที่ห้าม`,
  promotions: `โปรโมชั่น`,
  publicInformation: `ข้อมูลสาธารณะ`,
  publishOn: (...v) => `เผยแพร่บน ${v[0]}`,
  purchases: `การซื้อ`,
  rankings: `อันดับ`,
  reorderFiles: `เรียงลำดับไฟล์ใหม่`,
  report: `รายงาน`,
  revisions: `การแก้ไข`,
  sales: `การขาย`,
  save: `บันทึก`,
  saveAvatar: `บันทึกรูปประจำตัว`,
  saveChanges: `บันทึกการเปลี่ยนแปลง`,
  selectAnime: `เลือกอนิเมะ`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `เลือกธีมเดียวหรือซิงค์กับระบบของคุณและสลับธีมกลางวันและกลางคืนโดยอัตโนมัติ`,
  selectAvatar: `เลือกรูปประจำตัว`,
  selectCharacters: `เลือกตัวละคร`,
  selectFile: `เลือกไฟล์`,
  selectTheme: `เลือกธีม`,
  selectThumbnail: `เลือกภาพขนาดย่อ`,
  selfHarmOrSuicide: `การทำร้ายตนเองหรือการฆ่าตัวตาย`,
  sendEmail: `ส่งอีเมล`,
  settings: `การตั้งค่า`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `การตั้งค่าร้านค้าฟรีและใช้เวลาเพียงไม่กี่นาทีเท่านั้น`,
  share: `แชร์`,
  shareYourArtWithTheWorld: `แชร์งานศิลปะของคุณกับโลก`,
  shareYourStory: `แชร์เรื่องราวของคุณ!`,
  sharingPersonalInformation: `การแชร์ข้อมูลส่วนตัว`,
  shop: `ร้านค้า`,
  shopOrders: `คำสั่งซื้อร้านค้า`,
  showLess: `แสดงน้อยลง`,
  showMore: `แสดงเพิ่มขึ้น`,
  signIn: `เข้าสู่ระบบ`,
  singleTheme: `ธีมเดียว`,
  size: `ขนาด`,
  skip: `ข้าม`,
  socialMedia: `โซเชียลมีเดีย`,
  spaceCharacterIsNotAllowed: `ไม่อนุญาตให้เว้นวรรค`,
  spam: `สแปม`,
  submitAReport: `ส่งรายงาน`,
  submitWork: `ส่งงาน`,
  subscribeToTalentsToKeepUpWithTheirProgress: `สมัครรับการอัปเดตเนื้อหาเพื่อติดตามความคืบหน้า`,
  successChangedPasswordPleaseSignIn: `สำเร็จแล้ว! เปลี่ยนรหัสผ่านเรียบร้อย โปรดลงชื่อเข้าใช้`,
  successCreatedRecord: `สำเร็จแล้ว! สร้างบักทึกเรียบร้อย!`,
  successUpdatedRecord: `สำเร็จแล้ว! อัปเดตบักทึกเรียบร้อย!`,
  supportMeOn: `สนับสนุนฉันผ่าน`,
  syncWithSystem: `ซิงค์กับระบบ`,
  tellUsAboutYourself: `บอกเรื่องราวเกี่ยวกับตัวคุณ`,
  termsAndConditions: `ข้อกำหนดและเงื่อนไข`,
  termsOfUse: `ข้อตกลงในการใช้งาน`,
  thankYouForReport: `ขอบคุณสำหรับการช่วยรักษาชุมชนออนไลน์ที่ปลอดภัยและเคารพ`,
  theLinkIsBrokenOrPageHasBeenRemoved: `ลิงก์ไม่สามารถใช้งานได้หรือหน้านี้ถูกลบแล้ว`,
  themeMode: `โหมดธีม`,
  thisIsThePriceYouPropose: `นี่คือราคาที่คุณเสนอ`,
  threateningViolence: `การข่มขู่ความรุนแรง`,
  title: `หัวข้อ`,
  titleYourExtraService: `ตั้งชื่อบริการเสริมของคุณ`,
  today: `วันนี้`,
  toGetWorkRelatedNotifications: `เพื่อรับการแจ้งเตือนที่เกี่ยวข้องกับงาน`,
  total: `รวม`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `เพื่อดูข้อมูลนี้ คุณต้องยกเลิกการบล็อก @${v[0]}`,
  trademarkViolation: `การละเมิดสิทธิ์การค้า`,
  typeYourTextHere: `พิมพ์ข้อความที่นี่...`,
  unblock: `ยกเลิกการบล็อก`,
  unblockUser: (...v) => `ยกเลิกการบล็อก @${v[0]}`,
  unfollow: `เลิกติดตาม`,
  unlimited: `ไม่จำกัด`,
  upload: `อัปโหลด`,
  uploadNew: `อัปโหลดใหม่`,
  uploadNewPost: `อัปโหลดโพสต์ใหม่`,
  uploadNewProduct: `อัปโหลดผลิตภัณฑ์ใหม่`,
  username: `ชื่อผู้ใช้`,
  usernameAlreadyExists: `ชื่อผู้ใช้นี้มีอยู่แล้ว`,
  usernameAndXMoreFollowYou: (...v) => `<b>${v[0]}</b> และ ${v[1]} คนติดตามคุณ`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `<b>${v[0]}</b> และ ${v[1]} คนถูกใจงานศิลปะของคุณ`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b> ติดตามคุณ`,
  usernameLikesYourArt: (...v) => `<b>${v[0]}</b> ถูกใจงานศิลปะของคุณ`,
  useThisEmailTo: `ใช้อีเมลนี้เพื่อ: ยืนยันตัวตน, รับการแจ้งเตือน`,
  valueIsNotTheSame: `ค่าไม่เหมือนกัน`,
  verificationCode: `รหัสยืนยัน`,
  verifyCode: `ตรวจสอบรหัส`,
  viewDetails: `ดูรายละเอียด`,
  viewEveryNotificationOfAGroupSeparately: `ดูการแจ้งเตือนแต่ละรายการของกลุ่มแยกต่างหาก`,
  visitOurDiscordChannelToGetMoreDetails: `เข้าร่วมกลุ่ม Discord ของเราเพื่อดูข้อมูลเพิ่มเติม!`,
  weAreOnInstagram: `ติดตามเราผ่านทาง Instagram`,
  weAreWorkingOnIt: `เรากำลังดำเนินการอยู่`,
  weDoNotDisplayNSFWContentYet: `เราไม่สามารถเปิดเผยผลงานที่เป็น NSFW`,
  weekly: `รายสัปดาห์`,
  whenYouPurchaseSomethingItWillAppearHere: `เมื่อคุณซื้อสิ่งใด จะปรากฏที่นี่`,
  weHaveSentTooManyEmails: `เราได้ส่งอีเมลมากเกินไป โปรดลองอีกครั้งในภายหลังหรือติดต่อฝ่ายบริการลูกค้า`,
  welcomeToAnimeClub: `ยินดีต้อนรับสู่ Anime.club!`,
  weSentAnEmailTo: `เราได้ส่งอีเมลไปยัง`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `เราได้ส่งรหัสยืนยันตัวตนใหม่ให้คุณทางอีเมลแล้ว โปรดป้อนรหัสผ่าน`,
  weSupportOnlyTheFollowingFileExtensions: `เรารองรับเฉพาะไฟล์ต่อไปนี้`,
  work: `งาน`,
  workDescription: `คำอธิบายงาน`,
  wrongEmailOrPassword: `อีเมลหรือรหัสผ่านไม่ถูกต้อง`,
  yes: `ใช่`,
  yesterday: `เมื่อวานนี้`,
  youAreAlreadyAuthenticated: `คุณได้ทำการยืนยันตัวตนแล้ว`,
  youCanAutoPublishToYourSocialMediaAccount: `คุณสามารถเผยแพร่โดยอัตโนมัติไปยังบัญชีโซเชียลมีเดียของคุณได้`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `คุณสามารถแก้ไขประเภทของการแจ้งเตือนที่คุณได้รับทางอีเมลได้`,
  youCanRequestRemovalOfYourAccount: `คุณสามารถขอลบบัญชีของคุณพร้อมกับข้อมูลทั้งหมดได้`,
  youCanStillNavigateToThePreviouslyOpenedPages: `คุณยังสามารถกลับไปที่หน้าเดิมได้`,
  youDidNotSelectAnyChats: `คุณยังไม่ได้เลือกการแชทเลย`,
  youDidNotUpdateAnyValues: `คุณยังไม่ได้อัปเดตค่าเลย`,
  youDoNotHaveAnyChats: `คุณยังไม่มีการแชทเลย`,
  youHaveNotSetAPassword: `คุณยังไม่ได้ตั้งรหัสผ่าน`,
  youHaveNotSharedAnythingYet: `คุณยังไม่ได้แชร์อะไร`,
  youHaveReachedTheMaximumNumberOfFiles: `คุณได้ถึงจำนวนไฟล์สูงสุดแล้ว`,
  yourAccountIsVerifiedPleaseSignIn: `บัญชีของคุณได้รับการยืนยันแล้ว โปรดลงชื่อเข้าใช้บัญชี`,
  yourAccountWillBeRemoved: (...v) => `บัญชีของคุณจะถูกลบ ${v[0]}`,
  youHaveNoPurchases: `คุณไม่มีการซื้อขาย`,
  yourArts: `ผลงานของคุณ`,
  yourAvatar: `รูปประจำตัวของคุณ`,
  yourBlog: `บล็อกของคุณ`,
  yourFansAreWaiting: `แฟนๆ กำลังรอคุณอยู่นะ`,
  yourFeedIsEmpty: `ฟีดของคุณยังว่างเปล่าอยู่นะ`,
  yourSessionHasExpiredPleaseSignInAgain: `เซสชันของคุณหมดอายุแล้ว โปรดลองใหม่อีกครั้ง`,
}
