export const text: text = {
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Giới thiệu`,
  accept: `Chấp nhận`,
  account: `(en) Account`,
  accountActivation: `Kích hoạt tài khoản`,
  accountAlreadyExists: `Tài khoản đã tồn tại`,
  accountDoesNotExist: `Tài khoản không tồn tại`,
  add: `Thêm`,
  addArt: `Thêm tác phẩm`,
  addBlog: `Thêm blog`,
  addFile: `(en) Add file`,
  additionalResources: `(en) Additional resources`,
  addMore: `(en) Add more`,
  addNewArt: `Thêm tác phẩm mới`,
  addPreview: `Thêm bản xem trước`,
  addSignInVia: `Thêm đăng nhập qua`,
  advancedOptions: `(en) Advanced options`,
  all: `Tất cả`,
  alreadySignedIn: `Đã đăng nhập`,
  amount: `(en) Amount`,
  amountShouldNotBeLessThan: (...v) =>
    `(en) Amount should not be less than ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Tác phẩm anime của các nghệ sĩ từ khắp nơi trên thế giới. Sáng tạo nghệ thuật liên quan đến anime. Lựa chọn từ danh sách vô hạn gồm các tác phẩm anime tuyệt nhất`,
  animeArtSubscribeToArtistsLikeAndCreate: `Nghệ thuật anime - đăng ký theo dõi nghệ sĩ, ấn thích và tạo bộ sưu tập`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - nền tảng đầu tiên thanh toán cho các nghệ sĩ bằng lượt xem thông qua Google AdSense. Ủng hộ nghệ sĩ bằng cách xem nội dung của họ hoặc bắt đầu kiếm tiền bằng lượt xem`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - xem, đăng và kiếm tiền từ nội dung anime`,
  animeCommunity: `Cộng đồng anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `(en) Anime.club never asks for your private information`,
  animeSocialNetwork: `(en) Anime
Social Network`,
  announcements: `(en) Announcements`,
  apply: `Áp dụng`,
  appSettings: `(en) App settings`,
  appsVersionIs: `Phiên bản ứng dụng là`,
  areYouSureYouWantTo: `Bạn có chắc muốn`,
  art: `Tác phẩm`,
  artAssociatedWithAnime: `Tác phẩm liên quan đến anime`,
  artBy: `Tác phẩm của`,
  artCannotBeChanged: `Không thể thay đổi tác phẩm`,
  authenticationFailed: `Xác thực không thành công`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `(en) Auto publishing to Instagram is only available to Instagram business accounts`,
  back: `Quay lại`,
  blog: `Blog`,
  bookmarks: `Dấu trang`,
  browseArt: `Duyệt tác phẩm`,
  cancel: `hủy`,
  cannotStartWithChars: `Không thể bắt đầu bằng s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `(en) Change`,
  changeArt: `Đổi tác phẩm`,
  changeAvatar: `Đổi hình đại diện`,
  changeEmail: `(en) Change email`,
  changePassword: `Đổi mật khẩu`,
  chooseExistingChatOrStartANewOne: `Chọn trò chuyện hiện có hoặc bắt đầu một phiên trò chuyện mới`,
  city: `Thành phố`,
  clearAll: `Xóa tất cả`,
  close: `Đóng`,
  colorTheme: `(en) Color theme`,
  comingSoon: `Sắp ra mắt...`,
  commercialUse: `(en) Commercial use`,
  community: `Cộng đồng`,
  confirmAccount: `Xác nhận tài khoản`,
  confirmPassword: `Xác nhận mật khẩu`,
  connectWithUsOn: `(en) Connect with us on`,
  contactInformation: `(en) Contact information`,
  continue: `(en) Continue`,
  contractTitle: `(en) Contract Title`,
  copyLink: `Sao chép liên kết`,
  couldNotCreateANewRecord: `Không thể tạo hồ sơ mới`,
  country: `Quốc gia`,
  cover: `(en) Cover`,
  createANewAccountFailed: `Tạo tài khoản mới không thành công`,
  createNewAccount: `Tạo tài khoản mới`,
  currentPassword: `(en) Current password`,
  daily: `(en) Daily`,
  darkDefault: `(en) Dark default`,
  darkHighContrast: `(en) Dark high contrast`,
  dayTheme: `(en) Day theme`,
  delete: `Xóa`,
  deleteArt: `Xóa tranh`,
  deletePost: `Xóa bài viết`,
  deliveryTime: `(en) Delivery time`,
  describeTheDetailsOfYourProduct: `(en) Describe the details of your product`,
  description: `Mô tả`,
  details: `Chi tiết`,
  didntReceiveEmail: `Không nhận được email?`,
  donations: `Quyên góp`,
  done: `Đã xong`,
  dragAndDropOrSelectFiles: `(en) Drag & Drop or Select file(s)`,
  drawingContest: `Cuộc thi vẽ`,
  dueDate: `(en) Due date`,
  earlier: `(en) Earlier`,
  earningFromArts: `Kiếm tiền từ tác phẩm`,
  edit: `Sửa`,
  editPost: `Chỉnh sửa bài đăng`,
  editProfile: `Chỉnh sửa hồ sơ`,
  editTranslations: `Sửa bản dịch`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email đã được một tài khoản khác sử dụng`,
  emailNotifications: `(en) Email Notifications`,
  enterOrPasteALink: `Nhập hoặc dán một liên kết`,
  enterTheAddressAssociatedWithYourAccount: `(en) Enter the address associated with your account, and we'll email you a link to reset your password`,
  enterYourPassword: `(en) Enter your password`,
  error: `(en) Error`,
  errorPleaseContactCustomerSupport: `Lỗi! Vui lòng liên hệ bộ phận hỗ trợ khách hàng...`,
  exitEditor: `Thoát trình chỉnh sửa`,
  extensions: `Phần mở rộng`,
  fileSizeIsTooBig: `Kích cỡ tệp quá lớn`,
  filter: `Bộ lọc`,
  filterBy: `Lọc theo`,
  findUser: `Tìm kiếm người dùng`,
  follow: `Theo dõi`,
  followers: `Người theo dõi`,
  following: `Theo dõi`,
  followMeOn: `Theo dõi tôi trên`,
  follows: `(en) Follows`,
  forAllOtherInquiriesPleaseContactUsAt: `Đối với mọi thắc mắc khác, vui lòng liên hệ chúng tôi theo:`,
  forgotPassword: `Quên mật khẩu`,
  fromAnimeDotClub: `(en) From anime.club`,
  getDetails: `Nhận chi tiết`,
  guestView: `Dạng xem cho khách`,
  hasNotAddedADescriptionFor: (...v) =>
    `(en) @${v[0]} has not added a description for "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `(en) @${v[0]} has not shared any public details yet`,
  hire: `(en) Hire`,
  homepage: `Trang chủ`,
  howToContactYou: `(en) How to contact you`,
  howToFindYouOnOtherSocialNetworks: `(en) How to find you on other social networks`,
  iAgreeWith: `Tôi đồng ý với`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Chiều cao hình ảnh phải lớn hơn hoặc bằng`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Chiều rộng hình ảnh phải lớn hơn hoặc bằng`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `(en) Include keywords that buyers would likely use to search for a product like yours`,
  introduction: `Giới thiệu`,
  invalidCode: `Mã không hợp lệ`,
  invalidCurrentPassword: `(en) Invalid current password`,
  invalidDate: `(en) Invalid date`,
  invalidPartAfterAt: `Phần không hợp lệ sau @`,
  invalidPartBeforeAt: `Phần không hợp lệ trước @`,
  jobDetails: `(en) Job Details`,
  joinAnimeClubCommunity: `(en) Join Anime.club community with thousands of active creators and cool anime art everyday`,
  joinChat: `Tham gia trò chuyện`,
  joinUsOnFacebook: `Tham gia cùng chúng tôi trên Facebook`,
  language: `(en) Language`,
  languages: `Ngôn ngữ`,
  letEveryoneKnowHowToDonateToYou: `(en) Let everyone know how to donate to you`,
  letOthersKnowAboutYou: `(en) Let others know about you`,
  lightDefault: `(en) Light default`,
  lightHighContrast: `(en) Light high contrast`,
  likes: `Thích`,
  linkCopiedToClipboard: `Đã sao chép liên kết vào khay nhớ tạm`,
  livesIn: `Sống tại`,
  loading: `(en) Loading`,
  location: `(en) Location`,
  logInOrSignUp: `(en) Log in or sign up`,
  logOut: `(en) Log out`,
  maximumNChars: (...v) => `Tối đa ${v[0]} ký tự`,
  maximumNumberOfDaysToCompleteTheOrder: `(en) Maximum number of days to complete the order`,
  maxSize: `Kích cỡ tối đa`,
  menu: `Menu`,
  message: `Tin nhắn`,
  messages: `Tin nhắn`,
  minHeight: `Chiều cao tối thiểu`,
  minimumNChars: (...v) => `Tối thiểu ${v[0]} ký tự`,
  minWidth: `Chiều rộng tối thiểu`,
  monthly: `(en) Monthly`,
  moreFrom: (...v) => `Thêm từ ${v[0]}`,
  mustBeNChars: (...v) => `Phải là ${v[0]} ký tự`,
  myPayments: `(en) My payments`,
  myProfile: `(en) My profile`,
  mySettings: `(en) My settings`,
  need1Lowercase: `Cần 1 chữ thường`,
  need1Number: `Cần 1 số`,
  need1Uppercase: `Cần 1 chữ hoa`,
  needAtLeast1CharacterFromN: (...v) => `Cần tối thiểu 1 nhân vật từ [${v[0]}]`,
  needNCharacter: (...v) => `Cần ${v[0]} nhân vật`,
  newAccount: `Tài khoản mới`,
  newArt: `Tác phẩm mới`,
  newArtworks: `(en) New artworks`,
  newBlog: `Blog mới`,
  newPassword: `Mật khẩu mới`,
  newProduct: `(en) New product`,
  newsFeed: `Bảng tin`,
  next: `(en) Next`,
  nextTimeYouAuthenticateYouCouldUseThe: `(en) Next time you authenticate, you could use the connected account, instead of the login and password`,
  nightTheme: `(en) Night theme`,
  no: `không`,
  noAddedFavoriteArts: `không có tranh ưa thích được thêm vào`,
  noInternetConnection: `Không có kết nối Internet!`,
  none: `(en) None`,
  noNotifications: `(en) No notifications`,
  noResults: `(en) No results`,
  notifications: `Thông báo`,
  nsfwContent18Plus: `Nội dung NSFW (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `(en) Number of adjustments a client could request`,
  online: `Trực tuyến`,
  onlyLatinLettersNumbersOrSpecialSymbols: `Chỉ sử dụng chữ cái Latinh, số, ký hiệu đặc biệt`,
  onlyNumbers: `Chỉ sử dụng số`,
  open: `(en) Open`,
  openGuestView: `Mở dạng xem cho khách`,
  openingSoon: `Sắp ra mắt!`,
  openToWork: `(en) Open to work`,
  optional: `(en) Optional`,
  or: `HOẶC`,
  pageNotFound: `(en) Page not found`,
  password: `Mật khẩu`,
  payments: `Thanh toán`,
  personal: `(en) Personal`,
  pleaseCheckYour: (...v) => `(en) Please check your ${v[0]}`,
  pleaseDoNotShareYourPrivateInformationToOthers: `(en) Please do not share your private information to others`,
  pleaseDropOnlyOneImage: `Vui lòng chỉ thả vào một hình ảnh`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `(en) Please enter a number between ${v[0]} and ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `Vui lòng nhập ít nhất ${v[0]} nhân vật`,
  pleaseFillOutYourDetails: `Vui lòng điền thông tin của bạn`,
  pleaseSignInToYourAccount: `Vui lòng đăng nhập vào tài khoản của bạn`,
  pleaseTryAgainOrClick: (...v) => `Vui lòng thử lại hoặc nhấn ${v[0]}`,
  pleaseVerifyYourAccount: `Vui lòng xác nhận tài khoản của bạn`,
  pressHereTo: `Nhấn vào đây để`,
  price: `(en) Price`,
  privacyPolicy: `Chính sách bảo mật`,
  privateInformation: `(en) Private information`,
  profile: `Thông tin`,
  promotions: `(en) Promotions`,
  publicInformation: `(en) Public information`,
  publishOn: (...v) => `(en) Publish on ${v[0]}`,
  rankings: `(en) Rankings`,
  reorderFiles: `(en) Reorder files`,
  report: `(en) Report`,
  revisions: `(en) Revisions`,
  save: `Lưu`,
  saveAvatar: `Lưu hình đại diện`,
  saveChanges: `Lưu thay đổi`,
  selectAnime: `Chọn anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `(en) Select a single theme, or sync with your system and automatically switch between day and night themes`,
  selectAvatar: `Chọn hình đại diện`,
  selectCharacters: `Chọn (các) nhân vật`,
  selectFile: `Chọn tệp`,
  selectTheme: `(en) Select theme`,
  selectThumbnail: `Chọn hình thu nhỏ`,
  sendEmail: `Chọn email`,
  settings: `Cài đặt`,
  share: `(en) Share`,
  shareYourArtWithTheWorld: `(en) Share your art with the world`,
  shareYourStory: `Chia sẻ câu chuyện của bạn!`,
  shop: `Cửa hàng`,
  showLess: `Ẩn bớt đi`,
  showMore: `Hiển thị thêm`,
  signIn: `Đăng nhập`,
  singleTheme: `(en) Single theme`,
  size: `(en) Size`,
  skip: `Bỏ qua`,
  socialMedia: `Mạng xã hội`,
  spaceCharacterIsNotAllowed: `Không được phép sử dụng khoảng trắng`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Nhấn theo dõi các họa sĩ để không bỏ lỡ cập nhật từ họ`,
  successChangedPasswordPleaseSignIn: `Thành công! Đã thay đổi mật khẩu. Vui lòng đăng nhập`,
  successCreatedRecord: `Thành công! Đã tạo hồ sơ!`,
  successUpdatedRecord: `Thành công! Đã cập nhật hồ sơ!`,
  supportMeOn: `Hãy ủng hộ tôi tại`,
  syncWithSystem: `(en) Sync with system`,
  tellUsAboutYourself: `Cho chúng tôi biết về bạn`,
  termsAndConditions: `Điều khoản và Điều kiện`,
  termsOfUse: `Điều khoản sử dụng`,
  theLinkIsBrokenOrPageHasBeenRemoved: `(en) The link is broken or page has been removed`,
  themeMode: `(en) Theme mode`,
  thisIsThePriceYouPropose: `(en) This is the price you propose`,
  title: `Tiêu đề`,
  today: `(en) Today`,
  toGetWorkRelatedNotifications: `(en) To get work-related notifications`,
  typeYourTextHere: `Nhập văn bản của bạn vào đây...`,
  unlimited: `(en) Unlimited`,
  upload: `(en) Upload`,
  uploadNew: `Tải lên mới`,
  uploadNewPost: `Tải lên bài đăng mới`,
  username: `Tên người dùng`,
  usernameAlreadyExists: `Tên người dùng đã tồn tại`,
  usernameAndXMoreFollowYou: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more follow you`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `(en) <b>${v[0]}</b> and ${v[1]} more like your artwork`,
  usernameFollowsYou: (...v) => `(en) <b>${v[0]}</b> follows you`,
  usernameLikesYourArt: (...v) => `(en) <b>${v[0]}</b> likes your art`,
  useThisEmailTo: `(en) Use this email to: authenticate, receive notifications`,
  valueIsNotTheSame: `Giá trị không trùng khớp`,
  verificationCode: `Mã xác minh`,
  verifyCode: `Xác minh mã`,
  visitOurDiscordChannelToGetMoreDetails: `Ghé thăm kênh phản hồi của chúng tôi để biết thêm chi tiết`,
  weAreOnInstagram: `Chúng tôi đã có mặt trên Instagram`,
  weAreWorkingOnIt: `Chúng tôi đang phát triển tính năng này`,
  weDoNotDisplayNSFWContentYet: `Chúng tôi chưa hiển thị nội dung NSFW`,
  weekly: `(en) Weekly`,
  weHaveSentTooManyEmails: `(en) We have sent too many emails, please try again later or contact customer support`,
  welcomeToAnimeClub: `Chào mừng bạn đến Anime.club!`,
  weSentAnEmailTo: `Chúng tôi đã gửi email đến:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Chúng tôi đã gửi email xác minh mới. Vui lòng nhập mã`,
  weSupportOnlyTheFollowingFileExtensions: `Chúng tôi chỉ hỗ trợ các phần mở rộng tệp sau:`,
  work: `(en) Work`,
  workDescription: `(en) Work description`,
  wrongEmailOrPassword: `Sai email hoặc mật khẩu`,
  yes: `có`,
  yesterday: `(en) Yesterday`,
  youAreAlreadyAuthenticated: `Bạn đã được xác thực`,
  youCanAutoPublishToYourSocialMediaAccount: `(en) You can auto publish to your social media account`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `(en) You can modify the types of notifications you receive via email`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Bạn vẫn có thể dẫn hướng đến các trang đã mở trước đó`,
  youDidNotSelectAnyChats: `Bạn chưa chọn trò chuyện nào`,
  youDidNotUpdateAnyValues: `Bạn đã không cập nhật giá trị nào`,
  youDoNotHaveAnyChats: `Bạn không có trò chuyện nào`,
  youHaveNotSavedAnyChanges: `Bạn chưa lưu thay đổi nào. Rời đi?`,
  youHaveNotSetAPassword: `(en) You have not set a password`,
  youHaveNotSharedAnythingYet: `(en) You have not shared anything yet`,
  youHaveReachedTheMaximumNumberOfFiles: `(en) You have reached the maximum number of files`,
  yourAccountIsVerifiedPleaseSignIn: `Tài khoản của bạn đã được xác minh. Vui lòng đăng nhập`,
  yourArts: `Tác phẩm của bạn`,
  yourAvatar: `Hình đại diện của bạn`,
  yourBlog: `Blog của bạn`,
  yourFansAreWaiting: `Người hâm mộ đang chờ bạn`,
  yourFeedIsEmpty: `bảng tin trống`,
  yourSessionHasExpiredPleaseSignInAgain: `Phiên của bạn đã hết hạn, vui lòng đăng nhập lại`,
}
