export const text: text = {
  _dash: `(en) - `,
  acceptTheOrder: `(en) Accept the order`,
  aiGeneratedImagesAndNeuralNetworkFiltersAreProhibited: `(en) AI-generated images and neural network filters are prohibited`,
  addMoreProductsToYourShop: `(en) Add more products to your shop`,
  allFilesYouUploadHereWillBeAvailableToTheBuyer: `(en) All files you upload here will be available to the buyer`,
  bigAppreciationToTheSellerForTheirHardWork: `(en) Big appreciation to the seller for their hard work`,
  beforeAcceptingPleaseReviewTheBuyersRequestCarefully: `(en) Before accepting, please review the buyer's request carefully`,
  checkOutMyShop: `(en) Check out my shop`,
  commercialUseAllowed: `(en) Commercial use allowed`,
  commercialUseAllowsBuyersToUseYourProduct: `(en) Commercial use allows buyers to use your product for business purposes, like selling or promoting their services`,
  congratulationsOnSuccessfullyCompletingYourOrder: `(en) Congratulations on successfully completing your order!`,
  createAShopWithStripe: `(en) Create a shop with Stripe`,
  createdBy: `(en) Created by`,
  download: `(en) Dowload`,
  describeTheDetailsOfYourExtra: `(en) Describe the details of your extra`,
  enjoyYourPurchase: `(en) Enjoy your purchase! 😊`,
  extrasAreOptionalAddOnsToEnhanceYourProduct: `(en) Extras are optional add-ons to enhance your product`,
  usernameHasSubmittedTheWork: (...v) =>
    `(en) <b>${v[0]}</b> has submitted the work`,
  hereAreAFewWaysToGetThingsRolling: `(en) Here are a few ways to get things rolling`,
  makeSureToIncludeClearInstructions: `(en) Make sure to include clear instructions on how each reference should be used`,
  makeSureYouFullyUnderstandTheRequirements: `(en) Make sure you fully understand the requirements and can complete the order by the deadline`,
  makeSureYourProductsArePricedCompetitively: `(en) Make sure your products are priced competitively`,
  noSalesYetNoWorries: `(en) No sales yet? No worries, you're just starting out`,
  NSFWIndicatesAdultContent: `(en) 18+ NSFW indicates adult content. Check this field only if your product is intended for mature audiences`,
  onlyYouCanSeeWhatYouveSaved: `(en) Only you can see what you've saved`,
  requestDetails: `(en) Request details`,
  orderCompleted: `(en) Order Completed 🎉`,
  pleaseRateYourOrder: `(en) Please rate your order`,
  feelFreeToShareReferenceImagesAndMaterials: `(en) Feel free to share reference images and materials to help the artist create your piece`,
  pleaseFixTheErrorsBeforeSubmitting: `(en) Please fix the errors before submitting`,
  pleaseTakeAMomentToReviewTheOrder: `(en) 🎉 Please take a moment to review the order`,
  pleaseReviewTheBuyersReferenceFiles: `(en) Please review the buyer's reference files and follow them as specified in the order's description`,
  pleaseReviewTheDetailsCarefullyBeforeProceeding: `(en) Please review the details carefully before proceeding`,
  pleaseRespondToTheOrderBy: (...v) =>
    `(en) Please respond to the order by ${v[0]}`,
  reason: `(en) Reason`,
  yourOrderIncludesXRevisionS: (...v) =>
    `(en) Your order includes ${v[0]} revision(s)`,
  shareYourRulesAndTheTypesOfRequestsYouDontAccept: `(en) Share your rules and the types of requests you don’t accept`,
  shareYourShopOnSocialMedia: `(en) Share your shop on social media`,
  shareYourFavoritePiecesOn: (...v) =>
    `(en) Share your favorite pieces on ${v[0]}`,
  startAddingFavoritesToSeeThemHere: `(en) Start adding favorites to see them here`,
  successfullyDownloaded: `(en) Successfully downloaded!`,
  tellTheBuyerWhatTheyWillGetWithThisProduct: `(en) Tell the buyer what they will get with this product`,
  thankForYourSupport: `(en) Thank you for your support!`,
  thisFieldIsOptional: `(en) This field is optional`,
  thisCannotBeUndone: `(en) This cannot be undone`,
  ensureYouveUploadedTheFinalVersion: `(en)  Ensure you've uploaded the final version before submitting`,
  theSellerHasUploadedTheseFilesForYou: `(en) The seller has uploaded these files for you. Download them below!`,
  pleaseUploadOnlyFinishedWorkHereMaximumFiles: `(en) Please upload only finished work here`,
  allWIPRelatedFilesShouldBeUploadedInMessages: `(en) All WIP-related files should be uploaded in messages`,
  unfortunatelyTheSellerHadToCancelThisOrder: (...v) =>
    `(en) Unfortunately, ${v[0]} had to cancel this order`,
  yourFeedbackGuidesBuyersAndHelpsSellersOfferBetterProducts: `(en) Your feedback guides buyers and helps sellers offer better products`,
  youCanceledTheOrder: `(en) You canceled the order`,
  _colon: `: `,
  _comma: `, `,
  _dot: `. `,
  _exclamation: `! `,
  _question: `? `,
  _space: ` `,
  about: `Giới thiệu`,
  accept: `Chấp nhận`,
  acceptOrder: `Chấp nhận đơn hàng`,
  account: `Tài khoản`,
  accountDeleted: `Tài khoản đã bị xóa`,
  accountActivation: `Kích hoạt tài khoản`,
  accountAlreadyExists: `Tài khoản đã tồn tại`,
  accountDoesNotExist: `Tài khoản không tồn tại`,
  accountRemoval: `Xóa tài khoản`,
  add: `Thêm`,
  addArt: `Thêm tác phẩm`,
  addBlog: `Thêm blog`,
  addFile: `Thêm tệp`,
  additionalResources: `Tài nguyên bổ sung`,
  addMore: `Thêm`,
  addNewArt: `Thêm tác phẩm mới`,
  addPreview: `Thêm bản xem trước`,
  addSignInVia: `Thêm đăng nhập qua`,
  addToCart: `Thêm vào giỏ hàng`,
  advancedOptions: `Tùy chọn nâng cao`,
  all: `Tất cả`,
  alreadySignedIn: `Đã đăng nhập`,
  amount: `Số tiền`,
  amountShouldNotBeLessThan: (...v) => `Số tiền không nên ít hơn ${v[0]}`,
  animeArtByArtistsFromAllOverTheWorld: `Tác phẩm anime của các nghệ sĩ từ khắp nơi trên thế giới. Sáng tạo nghệ thuật liên quan đến anime. Lựa chọn từ danh sách vô hạn gồm các tác phẩm anime tuyệt nhất`,
  animeArtSubscribeToArtistsLikeAndCreate: `Nghệ thuật anime - đăng ký theo dõi nghệ sĩ, ấn thích và tạo bộ sưu tập`,
  animeClubTheFirstPlatformToOfferArtistsPaymentsFromViews: `Anime.club - nền tảng đầu tiên thanh toán cho các nghệ sĩ bằng lượt xem thông qua Google AdSense. Ủng hộ nghệ sĩ bằng cách xem nội dung của họ hoặc bắt đầu kiếm tiền bằng lượt xem`,
  animeClubViewPostAndEarnFromAnimeContent: `Anime.club - xem, đăng và kiếm tiền từ nội dung anime`,
  animeCommunity: `Cộng đồng anime`,
  animeDotclubNeverAsksForYourPrivateInformation: `Anime.club không bao giờ yêu cầu thông tin cá nhân của bạn`,
  animeSocialNetwork: `Mạng xã hội Anime`,
  announcements: `Thông báo`,
  apply: `Áp dụng`,
  appSettings: `Cài đặt ứng dụng`,
  appsVersionIs: `Phiên bản ứng dụng là`,
  areYouSureYouWantTo: `Bạn có chắc muốn`,
  art: `Tác phẩm`,
  artAssociatedWithAnime: `Tác phẩm liên quan đến anime`,
  artBy: (...v) => `Tranh của ${v[0]}`,
  artCannotBeChanged: `Không thể thay đổi tác phẩm`,
  artworksAvailableToView: (...v) => `${v[0]} bức tranh có sẵn để xem`,
  authenticationFailed: `Xác thực không thành công`,
  autoPublishingToInstagramIsOnlyAvailableToInstagramBusinessAccounts: `Tự động xuất bản lên Instagram chỉ có sẵn cho tài khoản doanh nghiệp Instagram`,
  attentionYourOrderHasBeenDisputed: `Chú ý! Đơn hàng của bạn đã bị tranh chấp. Vui lòng kiểm tra chi tiết`,
  awaitingReview: `Đang chờ xét duyệt`,
  awaitingSeller: `Đang chờ người bán`,
  back: `Quay lại`,
  basePrice: `Giá cơ bản`,
  block: `Chặn`,
  blockUser: (...v) => `Chặn @${v[0]}`,
  blog: `Blog`,
  bookmarks: `Dấu trang`,
  browseArt: `Duyệt tác phẩm`,
  browseShop: `Duyệt cửa hàng`,
  buyer: `Người mua`,
  cancel: `hủy`,
  canceled: `Đã hủy`,
  cancelOrder: `Hủy đơn hàng`,
  cannotStartWithChars: `Không thể bắt đầu bằng s{:"^$*[]{}()?-"!@#%&/,><':;|~\`"`,
  change: `Thay đổi`,
  checkOrderStatus: `Kiểm tra trạng thái đơn hàng`,
  changeArt: `Đổi tác phẩm`,
  changeAvatar: `Đổi hình đại diện`,
  changeEmail: `Thay đổi email`,
  changePassword: `Đổi mật khẩu`,
  chooseExistingChatOrStartANewOne: `Chọn trò chuyện hiện có hoặc bắt đầu một phiên trò chuyện mới`,
  city: `Thành phố`,
  clearAll: `Xóa tất cả`,
  clientReview: `Đánh giá của khách hàng`,
  close: `Đóng`,
  colorTheme: `Chủ đề màu sắc`,
  comingSoon: `Sắp ra mắt...`,
  community: `Cộng đồng`,
  completed: `Đã hoàn thành`,
  confirmAccount: `Xác nhận tài khoản`,
  confirmOrder: `Xác nhận đơn hàng`,
  confirmPassword: `Xác nhận mật khẩu`,
  connectWithUsOn: `Kết nối với chúng tôi trên`,
  contactInformation: `Thông tin liên hệ`,
  contactSeller: `Liên hệ người bán`,
  contactSupport: `Liên hệ hỗ trợ`,
  contactUs: `Liên hệ với chúng tôi`,
  continue: `Tiếp tục`,
  contractTitle: `Tiêu đề hợp đồng`,
  copyLink: `Sao chép liên kết`,
  congratulations: `Chúc mừng!`,
  copyrightViolation: `Vi phạm bản quyền`,
  couldNotCreateANewRecord: `Không thể tạo hồ sơ mới`,
  country: `Quốc gia`,
  cover: `Bìa`,
  createANewAccountFailed: `Tạo tài khoản mới không thành công`,
  createExtrasForYourProduct: `Tạo thêm cho sản phẩm của bạn`,
  createNewAccount: `Tạo tài khoản mới`,
  currentPassword: `Mật khẩu hiện tại`,
  daily: `Hàng ngày`,
  darkDefault: `Mặc định tối`,
  darkHighContrast: `Chế độ tối cao cấp`,
  dayTheme: `Chủ đề ban ngày`,
  delete: `Xóa`,
  deleteShop: `Xóa cửa hàng`,
  deleteAccount: `Xóa tài khoản`,
  deleteArt: `Xóa tranh`,
  decline: `Từ chối`,
  deletePost: `Xóa bài viết`,
  deleteProduct: `Xóa sản phẩm`,
  deliveryTime: `Thời gian giao hàng`,
  description: `Mô tả`,
  details: `Chi tiết`,
  didntReceiveEmail: `Không nhận được email?`,
  displayName: `Tên hiển thị`,
  disputed: `Tranh chấp`,
  donations: `Quyên góp`,
  done: `Đã xong`,
  dragAndDropOrSelectFiles: `Kéo và thả hoặc chọn tệp`,
  drawingContest: `Cuộc thi vẽ`,
  dueDate: `Ngày đáo hạn`,
  earlier: `Sớm hơn`,
  earningFromArts: `Kiếm tiền từ tác phẩm`,
  edit: `Sửa`,
  editPost: `Chỉnh sửa bài đăng`,
  editProfile: `Chỉnh sửa hồ sơ`,
  editTranslations: `Sửa bản dịch`,
  email: `Email`,
  emailAlreadyUsedByAnotherAccount: `Email đã được một tài khoản khác sử dụng`,
  emailNotifications: `Thông báo qua email`,
  enterOrPasteALink: `Nhập hoặc dán một liên kết`,
  enterTheAddressAssociatedWithYourAccount: `Nhập địa chỉ liên kết với tài khoản của bạn và chúng tôi sẽ gửi cho bạn một liên kết để đặt lại mật khẩu`,
  enterYourPassword: `Nhập mật khẩu của bạn`,
  error: `Lỗi`,
  errorPleaseContactCustomerSupport: `Lỗi! Vui lòng liên hệ bộ phận hỗ trợ khách hàng...`,
  exitWithoutSaving: `Thoát mà không lưu`,
  extensions: `Phần mở rộng`,
  extras: `Thêm`,
  fileSizeIsTooBig: `Kích cỡ tệp quá lớn`,
  fileSizeIsTooSmall: `Kích thước tệp quá nhỏ`,
  filter: `Bộ lọc`,
  filterBy: `Lọc theo`,
  findUser: `Tìm kiếm người dùng`,
  finishSettingUpYourShop: `Hoàn tất thiết lập cửa hàng của bạn`,
  follow: `Theo dõi`,
  followers: `Người theo dõi`,
  following: `Theo dõi`,
  followMeOn: `Theo dõi tôi trên`,
  follows: `Theo dõi`,
  forAllOtherInquiriesPleaseContactUsAt: `Đối với mọi thắc mắc khác, vui lòng liên hệ chúng tôi theo:`,
  forgotPassword: `Quên mật khẩu`,
  fromAnimeDotClub: `Từ anime.club`,
  getDetails: `Nhận chi tiết`,
  getStarted: `Bắt đầu`,
  guestView: `Dạng xem cho khách`,
  greatNewsYourOrderIsNowInProgress: `Tin tốt! Đơn hàng của bạn đang được xử lý`,
  harassment: `Quấy rối`,
  haveAnyQuestions: `Có câu hỏi nào không?`,
  usernameHasCanceledTheOrder: (...v) => `<b>${v[0]}</b> đã hủy đơn hàng`,
  hasNotAddedADescriptionFor: (...v) =>
    `@${v[0]} chưa thêm mô tả cho "${v[1]}"`,
  hasNotSharedAnyPublicDetailsYet: (...v) =>
    `@${v[0]} chưa chia sẻ bất kỳ chi tiết công khai nào`,
  hate: `Kinh tởm`,
  hire: `Thuê`,
  homepage: `Trang chủ`,
  howToContactYou: `Làm thế nào để liên hệ với bạn`,
  howToFindYouOnOtherSocialNetworks: `Làm thế nào để tìm bạn trên các mạng xã hội khác`,
  iAgreeWith: `Tôi đồng ý với`,
  ifTheresNoResponseByTimeLimit: (...v) =>
    `Nếu không có phản hồi trước ${v[0]}, đơn hàng sẽ được tự động đánh dấu là đã hoàn thành`,
  id: `ID`,
  imgHeightNeedsToBeBiggerThanOrEqualTo: `Chiều cao hình ảnh phải lớn hơn hoặc bằng`,
  imgWidthNeedsToBeBiggerThanOrEqualTo: `Chiều rộng hình ảnh phải lớn hơn hoặc bằng`,
  impersonation: `Mạo danh`,
  includeKeywordsThatBuyersWouldLikelyUseToSearchForAProductLikeYours: `Bao gồm các từ khóa mà người mua có thể sử dụng để tìm kiếm sản phẩm giống của bạn`,
  inProgress: `Đang tiến hành`,
  introduction: `Giới thiệu`,
  invalidCode: `Mã không hợp lệ`,
  invalidCurrentPassword: `Mật khẩu hiện tại không hợp lệ`,
  invalidDate: `Ngày không hợp lệ`,
  invalidPartAfterAt: `Phần không hợp lệ sau @`,
  invalidPartBeforeAt: `Phần không hợp lệ trước @`,
  jobDetails: `Chi tiết công việc`,
  joinAnimeClubCommunity: `Tham gia cộng đồng Anime.club với hàng ngàn nhà sáng tạo hoạt động và nghệ thuật anime đẹp mỗi ngày`,
  joinChat: `Tham gia trò chuyện`,
  joinUsOnFacebook: `Tham gia cùng chúng tôi trên Facebook`,
  language: `Ngôn ngữ`,
  lackOfInformation: `Thiếu thông tin`,
  languages: `Ngôn ngữ`,
  letEveryoneKnowHowToDonateToYou: `Hãy cho mọi người biết cách quyên góp cho bạn`,
  letOthersKnowAboutYou: `Hãy để mọi người biết về bạn`,
  letsUploadYourFirstProduct: `Hãy tải lên sản phẩm đầu tiên của bạn`,
  letUsKnowWhatsHappening: `Hãy cho chúng tôi biết điều gì đang xảy ra và chúng tôi sẽ xem xét`,
  lightDefault: `Mặc định sáng`,
  lightHighContrast: `Chế độ sáng cao cấp`,
  likes: `Thích`,
  limit: `Giới hạn`,
  linkCopiedToClipboard: `Đã sao chép liên kết vào khay nhớ tạm`,
  livesIn: `Sống tại`,
  loading: `Đang tải`,
  location: `Địa điểm`,
  logInOrSignUp: `Đăng nhập hoặc đăng ký`,
  logOut: `Đăng xuất`,
  maximumNChars: (...v) => `Tối đa ${v[0]} ký tự`,
  maximumNumberOfDaysToCompleteTheOrder: `Số ngày tối đa để hoàn thành đơn hàng`,
  maximumQuantity: `Số lượng tối đa`,
  maxSize: `Kích cỡ tối đa`,
  menu: `Menu`,
  message: `Tin nhắn`,
  messages: `Tin nhắn`,
  minHeight: `Chiều cao tối thiểu`,
  minimumNChars: (...v) => `Tối thiểu ${v[0]} ký tự`,
  minorAbuseOrSexualization: `Lạm dụng hoặc tình dục với trẻ em`,
  minWidth: `Chiều rộng tối thiểu`,
  monthly: `Hàng tháng`,
  moreFrom: (...v) => `Thêm từ ${v[0]}`,
  mustBeNChars: (...v) => `Phải là ${v[0]} ký tự`,
  myPayments: `Thanh toán của tôi`,
  myProfile: `Hồ sơ của tôi`,
  mySettings: `Cài đặt của tôi`,
  need1Lowercase: `Cần 1 chữ thường`,
  need1Number: `Cần 1 số`,
  need1Uppercase: `Cần 1 chữ hoa`,
  needAtLeast1CharacterFromN: (...v) => `Cần tối thiểu 1 nhân vật từ [${v[0]}]`,
  needNCharacter: (...v) => `Cần ${v[0]} nhân vật`,
  newAccount: `Tài khoản mới`,
  newArt: `Tác phẩm mới`,
  newArtworks: `Tác phẩm mới`,
  newBlog: `Blog mới`,
  newOrder: `Đơn hàng mới`,
  newPassword: `Mật khẩu mới`,
  newProduct: `Sản phẩm mới`,
  newsFeed: `Bảng tin`,
  next: `Tiếp theo`,
  nextTimeYouAuthenticateYouCouldUseThe: `Lần đăng nhập tiếp theo, bạn có thể sử dụng tài khoản được kết nối thay vì đăng nhập và mật khẩu`,
  nightTheme: `Chủ đề đêm`,
  no: `không`,
  noInternetConnection: `Không có kết nối Internet!`,
  nonConsensualIntimateContent: `Nội dung thân mật không đồng ý`,
  none: `Không`,
  noNotifications: `Không có thông báo`,
  noResults: `Không có kết quả`,
  notifications: `Thông báo`,
  noActiveOrdersToShow: `Không có đơn hàng hoạt động để hiển thị`,
  notAcceptingOrders: `Không nhận đơn hàng`,
  nsfwContent18Plus: `Nội dung NSFW (18+)`,
  numberOfAdjustmentsAClientCouldRequest: `Số lần điều chỉnh mà khách hàng có thể yêu cầu`,
  online: `Trực tuyến`,
  onlyLatinLettersNumbersHyphen: `Chỉ chữ cái Latin, số, dấu gạch ngang, gạch dưới và dấu chấm`,
  onlyNumbers: `Chỉ sử dụng số`,
  open: `Mở`,
  openDispute: `Mở tranh chấp`,
  openGuestView: `Mở dạng xem cho khách`,
  openingSoon: `Sắp ra mắt!`,
  openToWork: `Mở để làm việc`,
  optional: `Tùy chọn`,
  or: `HOẶC`,
  order: `Đơn hàng`,
  outOfStock: `Hết hàng`,
  ordered: (...v) => `Đã đặt ${v[0]}`,
  orderAgain: `Đặt hàng lại`,
  orderDetails: `Chi tiết đơn hàng`,
  orderConfirmed: `Đơn hàng đã được xác nhận`,
  orderStatus: `Trạng thái đơn hàng`,
  orderOptions: `Tùy chọn đơn hàng`,
  otherReason: `Lý do khác`,
  pageNotFound: `Không tìm thấy trang`,
  password: `Mật khẩu`,
  payments: `Thanh toán`,
  personal: `Cá nhân`,
  personalCircumstances: `Hoàn cảnh cá nhân`,
  pleaseCheckYour: (...v) => `Vui lòng kiểm tra ${v[0]} của bạn`,
  pleaseDoNotShareYourPrivateInformationToOthers: `Vui lòng không chia sẻ thông tin cá nhân của bạn cho người khác`,
  pleaseEnterANumberBetweenXandX: (...v) =>
    `Vui lòng nhập một số giữa ${v[0]} và ${v[1]}`,
  pleaseEnterAtLeastNChars: (...v) => `Vui lòng nhập ít nhất ${v[0]} nhân vật`,
  pleaseFillOutYourDetails: `Vui lòng điền thông tin của bạn`,
  pleaseSignInToYourAccount: `Vui lòng đăng nhập vào tài khoản của bạn`,
  platform: `Nền tảng`,
  pleaseStartTyping: `Vui lòng bắt đầu nhập`,
  pleaseTryAgainOrClick: (...v) => `Vui lòng thử lại hoặc nhấn ${v[0]}`,
  pleaseVerifyYourAccount: `Vui lòng xác nhận tài khoản của bạn`,
  pressHereTo: `Nhấn vào đây để`,
  price: `Giá`,
  privacyPolicy: `Chính sách bảo mật`,
  privateInformation: `Thông tin cá nhân`,
  proceedToCheckout: `Tiến hành thanh toán`,
  product: `Sản phẩm`,
  profile: `Thông tin`,
  prohibitedTransaction: `Giao dịch bị cấm`,
  promotions: `Khuyến mãi`,
  publicInformation: `Thông tin công khai`,
  publishOn: (...v) => `Đăng trên ${v[0]}`,
  purchases: `Mua hàng`,
  rankings: `Xếp hạng`,
  reorderFiles: `Sắp xếp lại tệp`,
  report: `Báo cáo`,
  revisions: `Phiên bản sửa đổi`,
  sales: `Bán hàng`,
  save: `Lưu`,
  saveAvatar: `Lưu hình đại diện`,
  saveChanges: `Lưu thay đổi`,
  selectAnime: `Chọn anime`,
  selectASingleThemeOrSyncWithYourSystemAndAutomaticallySwitchBetweenDayAndNightThemes: `Chọn một chủ đề đơn hoặc đồng bộ hóa với hệ thống của bạn và tự động chuyển đổi giữa chủ đề ban ngày và đêm`,
  selectAvatar: `Chọn hình đại diện`,
  selectCharacters: `Chọn (các) nhân vật`,
  seller: `Người bán`,
  selectFile: `Chọn tệp`,
  selectTheme: `Chọn chủ đề`,
  selectThumbnail: `Chọn hình thu nhỏ`,
  selfHarmOrSuicide: `Tự tử hoặc tự gây thương tích`,
  sendEmail: `Chọn email`,
  settings: `Cài đặt`,
  settingUpAShopIsFreeAndOnlyTakesAFewMinutes: `Thiết lập cửa hàng miễn phí và chỉ mất vài phút`,
  share: `Chia sẻ`,
  shareYourArtWithTheWorld: `Chia sẻ nghệ thuật của bạn với thế giới`,
  shareYourStory: `Chia sẻ câu chuyện của bạn!`,
  sharingPersonalInformation: `Chia sẻ thông tin cá nhân`,
  shop: `Cửa hàng`,
  shopOrders: `Đơn hàng cửa hàng`,
  showLess: `Ẩn bớt đi`,
  showMore: `Hiển thị thêm`,
  signIn: `Đăng nhập`,
  singleTheme: `Chủ đề đơn`,
  size: `Kích thước`,
  skip: `Bỏ qua`,
  socialMedia: `Mạng xã hội`,
  spaceCharacterIsNotAllowed: `Không được phép sử dụng khoảng trắng`,
  spam: `Thư rác`,
  submitAReport: `Gửi báo cáo`,
  submitWork: `Gửi tác phẩm`,
  subscribeToTalentsToKeepUpWithTheirProgress: `Nhấn theo dõi các họa sĩ để không bỏ lỡ cập nhật từ họ`,
  successChangedPasswordPleaseSignIn: `Thành công! Đã thay đổi mật khẩu. Vui lòng đăng nhập`,
  successCreatedRecord: `Thành công! Đã tạo hồ sơ!`,
  successUpdatedRecord: `Thành công! Đã cập nhật hồ sơ!`,
  supportMeOn: `Hãy ủng hộ tôi tại`,
  syncWithSystem: `Đồng bộ hóa với hệ thống`,
  tellUsAboutYourself: `Cho chúng tôi biết về bạn`,
  termsAndConditions: `Điều khoản và Điều kiện`,
  termsOfUse: `Điều khoản sử dụng`,
  thankYouForReport: `Cảm ơn bạn đã giúp duy trì một cộng đồng trực tuyến an toàn và tôn trọng`,
  theLinkIsBrokenOrPageHasBeenRemoved: `Liên kết bị hỏng hoặc trang đã bị xóa`,
  themeMode: `Chế độ chủ đề`,
  thisIsThePriceYouPropose: `Đây là giá bạn đề xuất`,
  threateningViolence: `Đe dọa bạo lực`,
  title: `Tiêu đề`,
  timeConstraints: `Hạn chế thời gian`,
  titleYourExtraService: `Đặt tên cho dịch vụ bổ sung của bạn`,
  theMaximumQuantityThatACustomerCanAdd: `Số lượng tối đa mà khách hàng có thể thêm`,
  theReviewPeriodIsLimitedtoNdays: (...v) =>
    `Thời gian đánh giá được giới hạn trong ${v[0]} ngày`,
  toHelpTheCreatorCompleteYourOrder: `Để giúp người tạo hoàn thành đơn hàng của bạn một cách hài lòng, vui lòng cung cấp mô tả chi tiết về những gì bạn muốn. Bao gồm chủ đề mong muốn, phong cách và các đặc điểm của nhân vật, cũng như bất kỳ thông số kỹ thuật quan trọng nào khác`,
  today: `Hôm nay`,
  toGetWorkRelatedNotifications: `Để nhận thông báo liên quan đến công việc`,
  total: `Tổng`,
  toViewThisDataYouNeedToUnblock: (...v) =>
    `Để xem dữ liệu này, bạn cần bỏ chặn @${v[0]}`,
  trademarkViolation: `Vi phạm thương hiệu`,
  typeYourTextHere: `Nhập văn bản của bạn vào đây...`,
  unblock: `Bỏ chặn`,
  unblockUser: (...v) => `Bỏ chặn @${v[0]}`,
  unfollow: `Bỏ theo dõi`,
  unlimited: `Không giới hạn`,
  upload: `Tải lên`,
  uploadNew: `Tải lên mới`,
  uploadNewPost: `Tải lên bài đăng mới`,
  uploadNewProduct: `Tải lên sản phẩm mới`,
  username: `Tên người dùng`,
  usernameAlreadyExists: `Tên người dùng đã tồn tại`,
  usernameAndXMoreFollowYou: (...v) =>
    `<b>${v[0]}</b> và ${v[1]} người khác đang theo dõi bạn`,
  usernameAndXMoreLikeYourArtwork: (...v) =>
    `<b>${v[0]}</b> và ${v[1]} người khác thích tác phẩm của bạn`,
  usernameFollowsYou: (...v) => `<b>${v[0]}</b> đang theo dõi bạn`,
  usernameLikesYourArt: (...v) => `<b>${v[0]}</b> thích tác phẩm của bạn`,
  useThisEmailTo: `Sử dụng email này để: xác thực, nhận thông báo`,
  valueIsNotTheSame: `Giá trị không trùng khớp`,
  verificationCode: `Mã xác minh`,
  verifyCode: `Xác minh mã`,
  viewDetails: `Xem chi tiết`,
  viewReview: `Xem đánh giá`,
  viewEveryNotificationOfAGroupSeparately: `Xem từng thông báo của một nhóm riêng biệt`,
  visitOurDiscordChannelToGetMoreDetails: `Ghé thăm kênh phản hồi của chúng tôi để biết thêm chi tiết`,
  weAreOnInstagram: `Chúng tôi đã có mặt trên Instagram`,
  weAreWorkingOnIt: `Chúng tôi đang phát triển tính năng này`,
  wellDoneYourWorkHasBeenSuccessfullyCompleted: `Làm tốt lắm! Công việc của bạn đã hoàn thành thành công`,
  weDoNotDisplayNSFWContentYet: `Chúng tôi chưa hiển thị nội dung NSFW`,
  weekly: `Hàng tuần`,
  whenYouPurchaseSomethingItWillAppearHere: `Khi bạn mua một cái gì đó, nó sẽ xuất hiện ở đây`,
  weHaveSentTooManyEmails: `Chúng tôi đã gửi quá nhiều email, vui lòng thử lại sau hoặc liên hệ với bộ phận hỗ trợ khách hàng`,
  welcomeToAnimeClub: `Chào mừng bạn đến Anime.club!`,
  weSentAnEmailTo: `Chúng tôi đã gửi email đến:`,
  weSentYouANewVerificationEmailPleaseEnterTheCode: `Chúng tôi đã gửi email xác minh mới. Vui lòng nhập mã`,
  weAreExcitedToSeeYourProgressKeepItUp: `Chúng tôi rất vui mừng khi thấy tiến bộ của bạn. Tiếp tục phát huy!`,
  weSupportOnlyTheFollowingFileExtensions: `Chúng tôi chỉ hỗ trợ các phần mở rộng tệp sau:`,
  work: `Công việc`,
  weWouldLoveToHearFromYou: `Chúng tôi rất muốn nghe từ bạn`,
  workDescription: `Mô tả công việc`,
  leaveAReview: `Để lại đánh giá`,
  wrongEmailOrPassword: `Sai email hoặc mật khẩu`,
  yes: `có`,
  yesterday: `Hôm qua`,
  youReceivedANewOrderFrom: (...v) =>
    `Bạn đã nhận được đơn hàng mới từ <b>${v[0]}</b>`,
  youHaveSuccessfullyCreatedYourShop: `Bạn đã tạo cửa hàng của mình thành công`,
  youAreAlreadyAuthenticated: `Bạn đã được xác thực`,
  youCanAutoPublishToYourSocialMediaAccount: `Bạn có thể tự động xuất bản vào tài khoản mạng xã hội của mình`,
  youCanModifyTheTypesOfNotificationsYouReceiveViaEmail: `Bạn có thể sửa đổi các loại thông báo mà bạn nhận được qua email`,
  youCanRequestRemovalOfYourAccount: `Bạn có thể yêu cầu xóa tài khoản của mình với tất cả dữ liệu của bạn`,
  youCanStillNavigateToThePreviouslyOpenedPages: `Bạn vẫn có thể dẫn hướng đến các trang đã mở trước đó`,
  youDidNotSelectAnyChats: `Bạn chưa chọn trò chuyện nào`,
  youDidNotUpdateAnyValues: `Bạn đã không cập nhật giá trị nào`,
  youDoNotHaveAnyChats: `Bạn không có trò chuyện nào`,
  youHaveNotSetAPassword: `Bạn chưa đặt mật khẩu`,
  youHaveNotSharedAnythingYet: `Bạn chưa chia sẻ bất cứ điều gì`,
  youHaveReachedTheMaximumNumberOfFiles: `Bạn đã đạt đến số tệp tối đa`,
  kindlyHoldOnForTheBuyersReview: `Vui lòng chờ đánh giá của người mua về đơn hàng.`,
  yourAccountIsVerifiedPleaseSignIn: `Tài khoản của bạn đã được xác minh. Vui lòng đăng nhập`,
  yourAccountWillBeRemoved: (...v) => `Tài khoản của bạn sẽ bị xóa ${v[0]}`,
  youHaveNoPurchases: `Bạn chưa có mua hàng`,
  couldYouPleaseProvideTheReasonForTheCancellation: `Bạn có thể cung cấp lý do hủy không`,
  yourFeedbackWouldBeGreatlyAppreciated: `Phản hồi của bạn sẽ được đánh giá cao`,
  yourArts: `Tác phẩm của bạn`,
  yourAvatar: `Hình đại diện của bạn`,
  yourBlog: `Blog của bạn`,
  yourFansAreWaiting: `Người hâm mộ đang chờ bạn`,
  yourFeedIsEmpty: `bảng tin trống`,
  yourSessionHasExpiredPleaseSignInAgain: `Phiên của bạn đã hết hạn, vui lòng đăng nhập lại`,
}
