name: Bump package version
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/on-translation-change.yml"
      - "src/**"
      - "types/**"

jobs:
  updateVersion:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - run: |
          npm version patch --allow-same-version
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish
          git push
          git push --tags --force
          gh release create "v$(node -p -e "require('./package.json').version")"

      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN_REPOSITORY_DISPATCH }}
          repository: anime-club/common
          event-type: translation-version-bump

      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN_REPOSITORY_DISPATCH }}
          repository: anime-club/translations-automation
          event-type: translation-version-bump
